window.SHOW = {
  id: "LodossWarSeriesEnglishDub",
  title: "Lodoss War ( Series) English Dub",
  art: "LodossWarSeriesEnglishDub.jpg",
  storageProgressKey: "lodosswarseriesenglishdub-progress",
  storageSettingsKey: "lodosswarseriesenglishdub-settings",
  nestedPaths: true,
  grouping: "season",
  segments: "none",
  episodes: [
  ["lodoss-war-complete-series-english-dub-mp4s-ost", "LODOSS WAR ( SERIES) ENGLISH DUB - S01E01 - Lodoss War MP4s + OST/01. Record of Lodoss War/Record Of Lodoss War…",
    "Lodoss War MP4s + OST/01. Record of Lodoss War/Record Of Lodoss War 01_18.32.13.mp4"],
  ["lodoss-war-complete-series-english-dub-mp4s-ost", "LODOSS WAR ( SERIES) ENGLISH DUB - S01E02 - Lodoss War MP4s + OST/01. Record of Lodoss War/Record Of Lodoss War…",
    "Lodoss War MP4s + OST/01. Record of Lodoss War/Record Of Lodoss War 01.ia.mp4"],
  ["lodoss-war-complete-series-english-dub-mp4s-ost", "LODOSS WAR ( SERIES) ENGLISH DUB - S01E03 - Lodoss War MP4s + OST/01. Record of Lodoss War/Record Of Lodoss War…",
    "Lodoss War MP4s + OST/01. Record of Lodoss War/Record Of Lodoss War 02_18.33.34.mp4"],
  ["lodoss-war-complete-series-english-dub-mp4s-ost", "LODOSS WAR ( SERIES) ENGLISH DUB - S01E04 - Lodoss War MP4s + OST/01. Record of Lodoss War/Record Of Lodoss War…",
    "Lodoss War MP4s + OST/01. Record of Lodoss War/Record Of Lodoss War 02.ia.mp4"],
  ["lodoss-war-complete-series-english-dub-mp4s-ost", "LODOSS WAR ( SERIES) ENGLISH DUB - S01E05 - Lodoss War MP4s + OST/01. Record of Lodoss War/Record Of Lodoss War…",
    "Lodoss War MP4s + OST/01. Record of Lodoss War/Record Of Lodoss War 03_18.34.49.mp4"],
  ["lodoss-war-complete-series-english-dub-mp4s-ost", "LODOSS WAR ( SERIES) ENGLISH DUB - S01E06 - Lodoss War MP4s + OST/01. Record of Lodoss War/Record Of Lodoss War…",
    "Lodoss War MP4s + OST/01. Record of Lodoss War/Record Of Lodoss War 03.ia.mp4"],
  ["lodoss-war-complete-series-english-dub-mp4s-ost", "LODOSS WAR ( SERIES) ENGLISH DUB - S01E07 - Lodoss War MP4s + OST/01. Record of Lodoss War/Record Of Lodoss War…",
    "Lodoss War MP4s + OST/01. Record of Lodoss War/Record Of Lodoss War 04_18.36.8.mp4"],
  ["lodoss-war-complete-series-english-dub-mp4s-ost", "LODOSS WAR ( SERIES) ENGLISH DUB - S01E08 - Lodoss War MP4s + OST/01. Record of Lodoss War/Record Of Lodoss War…",
    "Lodoss War MP4s + OST/01. Record of Lodoss War/Record Of Lodoss War 04.ia.mp4"],
  ["lodoss-war-complete-series-english-dub-mp4s-ost", "LODOSS WAR ( SERIES) ENGLISH DUB - S01E09 - Lodoss War MP4s + OST/01. Record of Lodoss War/Record Of Lodoss War…",
    "Lodoss War MP4s + OST/01. Record of Lodoss War/Record Of Lodoss War 05_18.37.26.mp4"],
  ["lodoss-war-complete-series-english-dub-mp4s-ost", "LODOSS WAR ( SERIES) ENGLISH DUB - S01E10 - Lodoss War MP4s + OST/01. Record of Lodoss War/Record Of Lodoss War…",
    "Lodoss War MP4s + OST/01. Record of Lodoss War/Record Of Lodoss War 05.ia.mp4"],
  ["lodoss-war-complete-series-english-dub-mp4s-ost", "LODOSS WAR ( SERIES) ENGLISH DUB - S01E11 - Lodoss War MP4s + OST/01. Record of Lodoss War/Record Of Lodoss War…",
    "Lodoss War MP4s + OST/01. Record of Lodoss War/Record Of Lodoss War 06_18.38.44.mp4"],
  ["lodoss-war-complete-series-english-dub-mp4s-ost", "LODOSS WAR ( SERIES) ENGLISH DUB - S01E12 - Lodoss War MP4s + OST/01. Record of Lodoss War/Record Of Lodoss War…",
    "Lodoss War MP4s + OST/01. Record of Lodoss War/Record Of Lodoss War 06.ia.mp4"],
  ["lodoss-war-complete-series-english-dub-mp4s-ost", "LODOSS WAR ( SERIES) ENGLISH DUB - S01E13 - Lodoss War MP4s + OST/01. Record of Lodoss War/Record Of Lodoss War…",
    "Lodoss War MP4s + OST/01. Record of Lodoss War/Record Of Lodoss War 07_18.40.2.mp4"],
  ["lodoss-war-complete-series-english-dub-mp4s-ost", "LODOSS WAR ( SERIES) ENGLISH DUB - S01E14 - Lodoss War MP4s + OST/01. Record of Lodoss War/Record Of Lodoss War…",
    "Lodoss War MP4s + OST/01. Record of Lodoss War/Record Of Lodoss War 07.ia.mp4"],
  ["lodoss-war-complete-series-english-dub-mp4s-ost", "LODOSS WAR ( SERIES) ENGLISH DUB - S01E15 - Lodoss War MP4s + OST/01. Record of Lodoss War/Record Of Lodoss War…",
    "Lodoss War MP4s + OST/01. Record of Lodoss War/Record Of Lodoss War 08_18.41.21.mp4"],
  ["lodoss-war-complete-series-english-dub-mp4s-ost", "LODOSS WAR ( SERIES) ENGLISH DUB - S01E16 - Lodoss War MP4s + OST/01. Record of Lodoss War/Record Of Lodoss War…",
    "Lodoss War MP4s + OST/01. Record of Lodoss War/Record Of Lodoss War 08.ia.mp4"],
  ["lodoss-war-complete-series-english-dub-mp4s-ost", "LODOSS WAR ( SERIES) ENGLISH DUB - S01E17 - Lodoss War MP4s + OST/01. Record of Lodoss War/Record Of Lodoss War…",
    "Lodoss War MP4s + OST/01. Record of Lodoss War/Record Of Lodoss War 09_18.42.48.mp4"],
  ["lodoss-war-complete-series-english-dub-mp4s-ost", "LODOSS WAR ( SERIES) ENGLISH DUB - S01E18 - Lodoss War MP4s + OST/01. Record of Lodoss War/Record Of Lodoss War…",
    "Lodoss War MP4s + OST/01. Record of Lodoss War/Record Of Lodoss War 09.ia.mp4"],
  ["lodoss-war-complete-series-english-dub-mp4s-ost", "LODOSS WAR ( SERIES) ENGLISH DUB - S01E19 - Lodoss War MP4s + OST/01. Record of Lodoss War/Record Of Lodoss War…",
    "Lodoss War MP4s + OST/01. Record of Lodoss War/Record Of Lodoss War 10_18.44.9.mp4"],
  ["lodoss-war-complete-series-english-dub-mp4s-ost", "LODOSS WAR ( SERIES) ENGLISH DUB - S01E20 - Lodoss War MP4s + OST/01. Record of Lodoss War/Record Of Lodoss War…",
    "Lodoss War MP4s + OST/01. Record of Lodoss War/Record Of Lodoss War 10.ia.mp4"],
  ["lodoss-war-complete-series-english-dub-mp4s-ost", "LODOSS WAR ( SERIES) ENGLISH DUB - S01E21 - Lodoss War MP4s + OST/01. Record of Lodoss War/Record Of Lodoss War…",
    "Lodoss War MP4s + OST/01. Record of Lodoss War/Record Of Lodoss War 11_18.45.31.mp4"],
  ["lodoss-war-complete-series-english-dub-mp4s-ost", "LODOSS WAR ( SERIES) ENGLISH DUB - S01E22 - Lodoss War MP4s + OST/01. Record of Lodoss War/Record Of Lodoss War…",
    "Lodoss War MP4s + OST/01. Record of Lodoss War/Record Of Lodoss War 11.ia.mp4"],
  ["lodoss-war-complete-series-english-dub-mp4s-ost", "LODOSS WAR ( SERIES) ENGLISH DUB - S01E23 - Lodoss War MP4s + OST/01. Record of Lodoss War/Record Of Lodoss War…",
    "Lodoss War MP4s + OST/01. Record of Lodoss War/Record Of Lodoss War 12_18.46.55.mp4"],
  ["lodoss-war-complete-series-english-dub-mp4s-ost", "LODOSS WAR ( SERIES) ENGLISH DUB - S01E24 - Lodoss War MP4s + OST/01. Record of Lodoss War/Record Of Lodoss War…",
    "Lodoss War MP4s + OST/01. Record of Lodoss War/Record Of Lodoss War 12.ia.mp4"],
  ["lodoss-war-complete-series-english-dub-mp4s-ost", "LODOSS WAR ( SERIES) ENGLISH DUB - S01E25 - Lodoss War MP4s + OST/01. Record of Lodoss War/Record Of Lodoss War…",
    "Lodoss War MP4s + OST/01. Record of Lodoss War/Record Of Lodoss War 13_18.48.17.mp4"],
  ["lodoss-war-complete-series-english-dub-mp4s-ost", "LODOSS WAR ( SERIES) ENGLISH DUB - S01E26 - Lodoss War MP4s + OST/01. Record of Lodoss War/Record Of Lodoss War…",
    "Lodoss War MP4s + OST/01. Record of Lodoss War/Record Of Lodoss War 13.ia.mp4"],
  ["lodoss-war-complete-series-english-dub-mp4s-ost", "LODOSS WAR ( SERIES) ENGLISH DUB - S01E27 - Lodoss War MP4s + OST/02. Chronicles of the Heroic Knight/Chronicles Of The…",
    "Lodoss War MP4s + OST/02. Chronicles of the Heroic Knight/Chronicles Of The Heroic Knight 01_17.56.56.mp4"],
  ["lodoss-war-complete-series-english-dub-mp4s-ost", "LODOSS WAR ( SERIES) ENGLISH DUB - S01E28 - Lodoss War MP4s + OST/02. Chronicles of the Heroic Knight/Chronicles Of The…",
    "Lodoss War MP4s + OST/02. Chronicles of the Heroic Knight/Chronicles Of The Heroic Knight 01.ia.mp4"],
  ["lodoss-war-complete-series-english-dub-mp4s-ost", "LODOSS WAR ( SERIES) ENGLISH DUB - S01E29 - Lodoss War MP4s + OST/02. Chronicles of the Heroic Knight/Chronicles Of The…",
    "Lodoss War MP4s + OST/02. Chronicles of the Heroic Knight/Chronicles Of The Heroic Knight 02_17.58.18.mp4"],
  ["lodoss-war-complete-series-english-dub-mp4s-ost", "LODOSS WAR ( SERIES) ENGLISH DUB - S01E30 - Lodoss War MP4s + OST/02. Chronicles of the Heroic Knight/Chronicles Of The…",
    "Lodoss War MP4s + OST/02. Chronicles of the Heroic Knight/Chronicles Of The Heroic Knight 02.ia.mp4"],
  ["lodoss-war-complete-series-english-dub-mp4s-ost", "LODOSS WAR ( SERIES) ENGLISH DUB - S01E31 - Lodoss War MP4s + OST/02. Chronicles of the Heroic Knight/Chronicles Of The…",
    "Lodoss War MP4s + OST/02. Chronicles of the Heroic Knight/Chronicles Of The Heroic Knight 03_17.59.30.mp4"],
  ["lodoss-war-complete-series-english-dub-mp4s-ost", "LODOSS WAR ( SERIES) ENGLISH DUB - S01E32 - Lodoss War MP4s + OST/02. Chronicles of the Heroic Knight/Chronicles Of The…",
    "Lodoss War MP4s + OST/02. Chronicles of the Heroic Knight/Chronicles Of The Heroic Knight 03.ia.mp4"],
  ["lodoss-war-complete-series-english-dub-mp4s-ost", "LODOSS WAR ( SERIES) ENGLISH DUB - S01E33 - Lodoss War MP4s + OST/02. Chronicles of the Heroic Knight/Chronicles Of The…",
    "Lodoss War MP4s + OST/02. Chronicles of the Heroic Knight/Chronicles Of The Heroic Knight 04_18.0.42.mp4"],
  ["lodoss-war-complete-series-english-dub-mp4s-ost", "LODOSS WAR ( SERIES) ENGLISH DUB - S01E34 - Lodoss War MP4s + OST/02. Chronicles of the Heroic Knight/Chronicles Of The…",
    "Lodoss War MP4s + OST/02. Chronicles of the Heroic Knight/Chronicles Of The Heroic Knight 04.ia.mp4"],
  ["lodoss-war-complete-series-english-dub-mp4s-ost", "LODOSS WAR ( SERIES) ENGLISH DUB - S01E35 - Lodoss War MP4s + OST/02. Chronicles of the Heroic Knight/Chronicles Of The…",
    "Lodoss War MP4s + OST/02. Chronicles of the Heroic Knight/Chronicles Of The Heroic Knight 05_18.1.51.mp4"],
  ["lodoss-war-complete-series-english-dub-mp4s-ost", "LODOSS WAR ( SERIES) ENGLISH DUB - S01E36 - Lodoss War MP4s + OST/02. Chronicles of the Heroic Knight/Chronicles Of The…",
    "Lodoss War MP4s + OST/02. Chronicles of the Heroic Knight/Chronicles Of The Heroic Knight 05.ia.mp4"],
  ["lodoss-war-complete-series-english-dub-mp4s-ost", "LODOSS WAR ( SERIES) ENGLISH DUB - S01E37 - Lodoss War MP4s + OST/02. Chronicles of the Heroic Knight/Chronicles Of The…",
    "Lodoss War MP4s + OST/02. Chronicles of the Heroic Knight/Chronicles Of The Heroic Knight 06_18.3.0.mp4"],
  ["lodoss-war-complete-series-english-dub-mp4s-ost", "LODOSS WAR ( SERIES) ENGLISH DUB - S01E38 - Lodoss War MP4s + OST/02. Chronicles of the Heroic Knight/Chronicles Of The…",
    "Lodoss War MP4s + OST/02. Chronicles of the Heroic Knight/Chronicles Of The Heroic Knight 06.ia.mp4"],
  ["lodoss-war-complete-series-english-dub-mp4s-ost", "LODOSS WAR ( SERIES) ENGLISH DUB - S01E39 - Lodoss War MP4s + OST/02. Chronicles of the Heroic Knight/Chronicles Of The…",
    "Lodoss War MP4s + OST/02. Chronicles of the Heroic Knight/Chronicles Of The Heroic Knight 07_18.4.11.mp4"],
  ["lodoss-war-complete-series-english-dub-mp4s-ost", "LODOSS WAR ( SERIES) ENGLISH DUB - S01E40 - Lodoss War MP4s + OST/02. Chronicles of the Heroic Knight/Chronicles Of The…",
    "Lodoss War MP4s + OST/02. Chronicles of the Heroic Knight/Chronicles Of The Heroic Knight 07.ia.mp4"],
  ["lodoss-war-complete-series-english-dub-mp4s-ost", "LODOSS WAR ( SERIES) ENGLISH DUB - S01E41 - Lodoss War MP4s + OST/02. Chronicles of the Heroic Knight/Chronicles Of The…",
    "Lodoss War MP4s + OST/02. Chronicles of the Heroic Knight/Chronicles Of The Heroic Knight 08_18.5.20.mp4"],
  ["lodoss-war-complete-series-english-dub-mp4s-ost", "LODOSS WAR ( SERIES) ENGLISH DUB - S01E42 - Lodoss War MP4s + OST/02. Chronicles of the Heroic Knight/Chronicles Of The…",
    "Lodoss War MP4s + OST/02. Chronicles of the Heroic Knight/Chronicles Of The Heroic Knight 08.ia.mp4"],
  ["lodoss-war-complete-series-english-dub-mp4s-ost", "LODOSS WAR ( SERIES) ENGLISH DUB - S01E43 - Lodoss War MP4s + OST/02. Chronicles of the Heroic Knight/Chronicles Of The…",
    "Lodoss War MP4s + OST/02. Chronicles of the Heroic Knight/Chronicles Of The Heroic Knight 09_18.6.26.mp4"],
  ["lodoss-war-complete-series-english-dub-mp4s-ost", "LODOSS WAR ( SERIES) ENGLISH DUB - S01E44 - Lodoss War MP4s + OST/02. Chronicles of the Heroic Knight/Chronicles Of The…",
    "Lodoss War MP4s + OST/02. Chronicles of the Heroic Knight/Chronicles Of The Heroic Knight 09.ia.mp4"],
  ["lodoss-war-complete-series-english-dub-mp4s-ost", "LODOSS WAR ( SERIES) ENGLISH DUB - S01E45 - Lodoss War MP4s + OST/02. Chronicles of the Heroic Knight/Chronicles Of The…",
    "Lodoss War MP4s + OST/02. Chronicles of the Heroic Knight/Chronicles Of The Heroic Knight 10_18.7.31.mp4"],
  ["lodoss-war-complete-series-english-dub-mp4s-ost", "LODOSS WAR ( SERIES) ENGLISH DUB - S01E46 - Lodoss War MP4s + OST/02. Chronicles of the Heroic Knight/Chronicles Of The…",
    "Lodoss War MP4s + OST/02. Chronicles of the Heroic Knight/Chronicles Of The Heroic Knight 10.ia.mp4"],
  ["lodoss-war-complete-series-english-dub-mp4s-ost", "LODOSS WAR ( SERIES) ENGLISH DUB - S01E47 - Lodoss War MP4s + OST/02. Chronicles of the Heroic Knight/Chronicles Of The…",
    "Lodoss War MP4s + OST/02. Chronicles of the Heroic Knight/Chronicles Of The Heroic Knight 11_18.8.36.mp4"],
  ["lodoss-war-complete-series-english-dub-mp4s-ost", "LODOSS WAR ( SERIES) ENGLISH DUB - S01E48 - Lodoss War MP4s + OST/02. Chronicles of the Heroic Knight/Chronicles Of The…",
    "Lodoss War MP4s + OST/02. Chronicles of the Heroic Knight/Chronicles Of The Heroic Knight 11.ia.mp4"],
  ["lodoss-war-complete-series-english-dub-mp4s-ost", "LODOSS WAR ( SERIES) ENGLISH DUB - S01E49 - Lodoss War MP4s + OST/02. Chronicles of the Heroic Knight/Chronicles Of The…",
    "Lodoss War MP4s + OST/02. Chronicles of the Heroic Knight/Chronicles Of The Heroic Knight 12_18.9.50.mp4"],
  ["lodoss-war-complete-series-english-dub-mp4s-ost", "LODOSS WAR ( SERIES) ENGLISH DUB - S01E50 - Lodoss War MP4s + OST/02. Chronicles of the Heroic Knight/Chronicles Of The…",
    "Lodoss War MP4s + OST/02. Chronicles of the Heroic Knight/Chronicles Of The Heroic Knight 12.ia.mp4"],
  ["lodoss-war-complete-series-english-dub-mp4s-ost", "LODOSS WAR ( SERIES) ENGLISH DUB - S01E51 - Lodoss War MP4s + OST/02. Chronicles of the Heroic Knight/Chronicles Of The…",
    "Lodoss War MP4s + OST/02. Chronicles of the Heroic Knight/Chronicles Of The Heroic Knight 13_18.10.58.mp4"],
  ["lodoss-war-complete-series-english-dub-mp4s-ost", "LODOSS WAR ( SERIES) ENGLISH DUB - S01E52 - Lodoss War MP4s + OST/02. Chronicles of the Heroic Knight/Chronicles Of The…",
    "Lodoss War MP4s + OST/02. Chronicles of the Heroic Knight/Chronicles Of The Heroic Knight 13.ia.mp4"],
  ["lodoss-war-complete-series-english-dub-mp4s-ost", "LODOSS WAR ( SERIES) ENGLISH DUB - S01E53 - Lodoss War MP4s + OST/02. Chronicles of the Heroic Knight/Chronicles Of The…",
    "Lodoss War MP4s + OST/02. Chronicles of the Heroic Knight/Chronicles Of The Heroic Knight 14_18.12.6.mp4"],
  ["lodoss-war-complete-series-english-dub-mp4s-ost", "LODOSS WAR ( SERIES) ENGLISH DUB - S01E54 - Lodoss War MP4s + OST/02. Chronicles of the Heroic Knight/Chronicles Of The…",
    "Lodoss War MP4s + OST/02. Chronicles of the Heroic Knight/Chronicles Of The Heroic Knight 14.ia.mp4"],
  ["lodoss-war-complete-series-english-dub-mp4s-ost", "LODOSS WAR ( SERIES) ENGLISH DUB - S01E55 - Lodoss War MP4s + OST/02. Chronicles of the Heroic Knight/Chronicles Of The…",
    "Lodoss War MP4s + OST/02. Chronicles of the Heroic Knight/Chronicles Of The Heroic Knight 15_18.13.18.mp4"],
  ["lodoss-war-complete-series-english-dub-mp4s-ost", "LODOSS WAR ( SERIES) ENGLISH DUB - S01E56 - Lodoss War MP4s + OST/02. Chronicles of the Heroic Knight/Chronicles Of The…",
    "Lodoss War MP4s + OST/02. Chronicles of the Heroic Knight/Chronicles Of The Heroic Knight 15.ia.mp4"],
  ["lodoss-war-complete-series-english-dub-mp4s-ost", "LODOSS WAR ( SERIES) ENGLISH DUB - S01E57 - Lodoss War MP4s + OST/02. Chronicles of the Heroic Knight/Chronicles Of The…",
    "Lodoss War MP4s + OST/02. Chronicles of the Heroic Knight/Chronicles Of The Heroic Knight 16_18.14.25.mp4"],
  ["lodoss-war-complete-series-english-dub-mp4s-ost", "LODOSS WAR ( SERIES) ENGLISH DUB - S01E58 - Lodoss War MP4s + OST/02. Chronicles of the Heroic Knight/Chronicles Of The…",
    "Lodoss War MP4s + OST/02. Chronicles of the Heroic Knight/Chronicles Of The Heroic Knight 16.ia.mp4"],
  ["lodoss-war-complete-series-english-dub-mp4s-ost", "LODOSS WAR ( SERIES) ENGLISH DUB - S01E59 - Lodoss War MP4s + OST/02. Chronicles of the Heroic Knight/Chronicles Of The…",
    "Lodoss War MP4s + OST/02. Chronicles of the Heroic Knight/Chronicles Of The Heroic Knight 17_18.15.33.mp4"],
  ["lodoss-war-complete-series-english-dub-mp4s-ost", "LODOSS WAR ( SERIES) ENGLISH DUB - S01E60 - Lodoss War MP4s + OST/02. Chronicles of the Heroic Knight/Chronicles Of The…",
    "Lodoss War MP4s + OST/02. Chronicles of the Heroic Knight/Chronicles Of The Heroic Knight 17.ia.mp4"],
  ["lodoss-war-complete-series-english-dub-mp4s-ost", "LODOSS WAR ( SERIES) ENGLISH DUB - S01E61 - Lodoss War MP4s + OST/02. Chronicles of the Heroic Knight/Chronicles Of The…",
    "Lodoss War MP4s + OST/02. Chronicles of the Heroic Knight/Chronicles Of The Heroic Knight 18_18.16.45.mp4"],
  ["lodoss-war-complete-series-english-dub-mp4s-ost", "LODOSS WAR ( SERIES) ENGLISH DUB - S01E62 - Lodoss War MP4s + OST/02. Chronicles of the Heroic Knight/Chronicles Of The…",
    "Lodoss War MP4s + OST/02. Chronicles of the Heroic Knight/Chronicles Of The Heroic Knight 18.ia.mp4"],
  ["lodoss-war-complete-series-english-dub-mp4s-ost", "LODOSS WAR ( SERIES) ENGLISH DUB - S01E63 - Lodoss War MP4s + OST/02. Chronicles of the Heroic Knight/Chronicles Of The…",
    "Lodoss War MP4s + OST/02. Chronicles of the Heroic Knight/Chronicles Of The Heroic Knight 19_18.17.57.mp4"],
  ["lodoss-war-complete-series-english-dub-mp4s-ost", "LODOSS WAR ( SERIES) ENGLISH DUB - S01E64 - Lodoss War MP4s + OST/02. Chronicles of the Heroic Knight/Chronicles Of The…",
    "Lodoss War MP4s + OST/02. Chronicles of the Heroic Knight/Chronicles Of The Heroic Knight 19.ia.mp4"],
  ["lodoss-war-complete-series-english-dub-mp4s-ost", "LODOSS WAR ( SERIES) ENGLISH DUB - S01E65 - Lodoss War MP4s + OST/02. Chronicles of the Heroic Knight/Chronicles Of The…",
    "Lodoss War MP4s + OST/02. Chronicles of the Heroic Knight/Chronicles Of The Heroic Knight 20_18.19.10.mp4"],
  ["lodoss-war-complete-series-english-dub-mp4s-ost", "LODOSS WAR ( SERIES) ENGLISH DUB - S01E66 - Lodoss War MP4s + OST/02. Chronicles of the Heroic Knight/Chronicles Of The…",
    "Lodoss War MP4s + OST/02. Chronicles of the Heroic Knight/Chronicles Of The Heroic Knight 20.ia.mp4"],
  ["lodoss-war-complete-series-english-dub-mp4s-ost", "LODOSS WAR ( SERIES) ENGLISH DUB - S01E67 - Lodoss War MP4s + OST/02. Chronicles of the Heroic Knight/Chronicles Of The…",
    "Lodoss War MP4s + OST/02. Chronicles of the Heroic Knight/Chronicles Of The Heroic Knight 21_18.20.22.mp4"],
  ["lodoss-war-complete-series-english-dub-mp4s-ost", "LODOSS WAR ( SERIES) ENGLISH DUB - S01E68 - Lodoss War MP4s + OST/02. Chronicles of the Heroic Knight/Chronicles Of The…",
    "Lodoss War MP4s + OST/02. Chronicles of the Heroic Knight/Chronicles Of The Heroic Knight 21.ia.mp4"],
  ["lodoss-war-complete-series-english-dub-mp4s-ost", "LODOSS WAR ( SERIES) ENGLISH DUB - S01E69 - Lodoss War MP4s + OST/02. Chronicles of the Heroic Knight/Chronicles Of The…",
    "Lodoss War MP4s + OST/02. Chronicles of the Heroic Knight/Chronicles Of The Heroic Knight 22_18.21.35.mp4"],
  ["lodoss-war-complete-series-english-dub-mp4s-ost", "LODOSS WAR ( SERIES) ENGLISH DUB - S01E70 - Lodoss War MP4s + OST/02. Chronicles of the Heroic Knight/Chronicles Of The…",
    "Lodoss War MP4s + OST/02. Chronicles of the Heroic Knight/Chronicles Of The Heroic Knight 22.ia.mp4"],
  ["lodoss-war-complete-series-english-dub-mp4s-ost", "LODOSS WAR ( SERIES) ENGLISH DUB - S01E71 - Lodoss War MP4s + OST/02. Chronicles of the Heroic Knight/Chronicles Of The…",
    "Lodoss War MP4s + OST/02. Chronicles of the Heroic Knight/Chronicles Of The Heroic Knight 23_18.22.48.mp4"],
  ["lodoss-war-complete-series-english-dub-mp4s-ost", "LODOSS WAR ( SERIES) ENGLISH DUB - S01E72 - Lodoss War MP4s + OST/02. Chronicles of the Heroic Knight/Chronicles Of The…",
    "Lodoss War MP4s + OST/02. Chronicles of the Heroic Knight/Chronicles Of The Heroic Knight 23.ia.mp4"],
  ["lodoss-war-complete-series-english-dub-mp4s-ost", "LODOSS WAR ( SERIES) ENGLISH DUB - S01E73 - Lodoss War MP4s + OST/02. Chronicles of the Heroic Knight/Chronicles Of The…",
    "Lodoss War MP4s + OST/02. Chronicles of the Heroic Knight/Chronicles Of The Heroic Knight 24_18.24.0.mp4"],
  ["lodoss-war-complete-series-english-dub-mp4s-ost", "LODOSS WAR ( SERIES) ENGLISH DUB - S01E74 - Lodoss War MP4s + OST/02. Chronicles of the Heroic Knight/Chronicles Of The…",
    "Lodoss War MP4s + OST/02. Chronicles of the Heroic Knight/Chronicles Of The Heroic Knight 24.ia.mp4"],
  ["lodoss-war-complete-series-english-dub-mp4s-ost", "LODOSS WAR ( SERIES) ENGLISH DUB - S01E75 - Lodoss War MP4s + OST/02. Chronicles of the Heroic Knight/Chronicles Of The…",
    "Lodoss War MP4s + OST/02. Chronicles of the Heroic Knight/Chronicles Of The Heroic Knight 25_18.25.8.mp4"],
  ["lodoss-war-complete-series-english-dub-mp4s-ost", "LODOSS WAR ( SERIES) ENGLISH DUB - S01E76 - Lodoss War MP4s + OST/02. Chronicles of the Heroic Knight/Chronicles Of The…",
    "Lodoss War MP4s + OST/02. Chronicles of the Heroic Knight/Chronicles Of The Heroic Knight 25.ia.mp4"],
  ["lodoss-war-complete-series-english-dub-mp4s-ost", "LODOSS WAR ( SERIES) ENGLISH DUB - S01E77 - Lodoss War MP4s + OST/02. Chronicles of the Heroic Knight/Chronicles Of The…",
    "Lodoss War MP4s + OST/02. Chronicles of the Heroic Knight/Chronicles Of The Heroic Knight 26_18.26.18.mp4"],
  ["lodoss-war-complete-series-english-dub-mp4s-ost", "LODOSS WAR ( SERIES) ENGLISH DUB - S01E78 - Lodoss War MP4s + OST/02. Chronicles of the Heroic Knight/Chronicles Of The…",
    "Lodoss War MP4s + OST/02. Chronicles of the Heroic Knight/Chronicles Of The Heroic Knight 26.ia.mp4"],
  ["lodoss-war-complete-series-english-dub-mp4s-ost", "LODOSS WAR ( SERIES) ENGLISH DUB - S01E79 - Lodoss War MP4s + OST/02. Chronicles of the Heroic Knight/Chronicles Of The…",
    "Lodoss War MP4s + OST/02. Chronicles of the Heroic Knight/Chronicles Of The Heroic Knight 27_18.27.30.mp4"],
  ["lodoss-war-complete-series-english-dub-mp4s-ost", "LODOSS WAR ( SERIES) ENGLISH DUB - S01E80 - Lodoss War MP4s + OST/02. Chronicles of the Heroic Knight/Chronicles Of The…",
    "Lodoss War MP4s + OST/02. Chronicles of the Heroic Knight/Chronicles Of The Heroic Knight 27.ia.mp4"],
  ["lodoss-war-complete-series-english-dub-mp4s-ost", "LODOSS WAR ( SERIES) ENGLISH DUB - S01E81 - Lodoss War MP4s + OST/03. Legend of Crystania/Legend Of Crystania Movie",
    "Lodoss War MP4s + OST/03. Legend of Crystania/Legend Of Crystania Movie_18.28.49.mp4"],
  ["lodoss-war-complete-series-english-dub-mp4s-ost", "LODOSS WAR ( SERIES) ENGLISH DUB - S01E82 - Lodoss War MP4s + OST/03. Legend of Crystania/Legend Of Crystania Movie",
    "Lodoss War MP4s + OST/03. Legend of Crystania/Legend Of Crystania Movie.ia.mp4"],
  ["lodoss-war-complete-series-english-dub-mp4s-ost", "LODOSS WAR ( SERIES) ENGLISH DUB - S01E83 - Untitled",
    "Lodoss War MP4s + OST/04. The Chaos Ring OVA/The Chaos Ring 01_18.49.48.mp4"],
  ["lodoss-war-complete-series-english-dub-mp4s-ost", "LODOSS WAR ( SERIES) ENGLISH DUB - S01E84 - Untitled",
    "Lodoss War MP4s + OST/04. The Chaos Ring OVA/The Chaos Ring 01.ia.mp4"],
  ["lodoss-war-complete-series-english-dub-mp4s-ost", "LODOSS WAR ( SERIES) ENGLISH DUB - S01E85 - Untitled",
    "Lodoss War MP4s + OST/04. The Chaos Ring OVA/The Chaos Ring 02_18.51.51.mp4"],
  ["lodoss-war-complete-series-english-dub-mp4s-ost", "LODOSS WAR ( SERIES) ENGLISH DUB - S01E86 - Untitled",
    "Lodoss War MP4s + OST/04. The Chaos Ring OVA/The Chaos Ring 02.ia.mp4"],
  ["lodoss-war-complete-series-english-dub-mp4s-ost", "LODOSS WAR ( SERIES) ENGLISH DUB - S01E87 - Untitled",
    "Lodoss War MP4s + OST/04. The Chaos Ring OVA/The Chaos Ring 03_18.52.51.mp4"],
  ["lodoss-war-complete-series-english-dub-mp4s-ost", "LODOSS WAR ( SERIES) ENGLISH DUB - S01E88 - Untitled",
    "Lodoss War MP4s + OST/04. The Chaos Ring OVA/The Chaos Ring 03.ia.mp4"],
  ["lodoss-war-complete-series-english-dub-mp4s-ost", "LODOSS WAR ( SERIES) ENGLISH DUB - S01E89 - Untitled",
    "Lodoss War MP4s + OST/04. The Chaos Ring OVA/The Chaos Ring 04_18.53.47.mp4"],
  ["lodoss-war-complete-series-english-dub-mp4s-ost", "LODOSS WAR ( SERIES) ENGLISH DUB - S01E90 - Untitled",
    "Lodoss War MP4s + OST/04. The Chaos Ring OVA/The Chaos Ring 04.ia.mp4"],
],
  durations: {
  "lodoss-war-complete-series-english-dub-mp4s-ost::Lodoss War MP4s + OST/01. Record of Lodoss War/Record Of Lodoss War 01_18.32.13.mp4": 1484,
  "lodoss-war-complete-series-english-dub-mp4s-ost::Lodoss War MP4s + OST/01. Record of Lodoss War/Record Of Lodoss War 01.ia.mp4": 1484,
  "lodoss-war-complete-series-english-dub-mp4s-ost::Lodoss War MP4s + OST/01. Record of Lodoss War/Record Of Lodoss War 02_18.33.34.mp4": 1488,
  "lodoss-war-complete-series-english-dub-mp4s-ost::Lodoss War MP4s + OST/01. Record of Lodoss War/Record Of Lodoss War 02.ia.mp4": 1488,
  "lodoss-war-complete-series-english-dub-mp4s-ost::Lodoss War MP4s + OST/01. Record of Lodoss War/Record Of Lodoss War 03_18.34.49.mp4": 1487,
  "lodoss-war-complete-series-english-dub-mp4s-ost::Lodoss War MP4s + OST/01. Record of Lodoss War/Record Of Lodoss War 03.ia.mp4": 1487,
  "lodoss-war-complete-series-english-dub-mp4s-ost::Lodoss War MP4s + OST/01. Record of Lodoss War/Record Of Lodoss War 04_18.36.8.mp4": 1483,
  "lodoss-war-complete-series-english-dub-mp4s-ost::Lodoss War MP4s + OST/01. Record of Lodoss War/Record Of Lodoss War 04.ia.mp4": 1483,
  "lodoss-war-complete-series-english-dub-mp4s-ost::Lodoss War MP4s + OST/01. Record of Lodoss War/Record Of Lodoss War 05_18.37.26.mp4": 1490,
  "lodoss-war-complete-series-english-dub-mp4s-ost::Lodoss War MP4s + OST/01. Record of Lodoss War/Record Of Lodoss War 05.ia.mp4": 1490,
  "lodoss-war-complete-series-english-dub-mp4s-ost::Lodoss War MP4s + OST/01. Record of Lodoss War/Record Of Lodoss War 06_18.38.44.mp4": 1483,
  "lodoss-war-complete-series-english-dub-mp4s-ost::Lodoss War MP4s + OST/01. Record of Lodoss War/Record Of Lodoss War 06.ia.mp4": 1483,
  "lodoss-war-complete-series-english-dub-mp4s-ost::Lodoss War MP4s + OST/01. Record of Lodoss War/Record Of Lodoss War 07_18.40.2.mp4": 1489,
  "lodoss-war-complete-series-english-dub-mp4s-ost::Lodoss War MP4s + OST/01. Record of Lodoss War/Record Of Lodoss War 07.ia.mp4": 1489,
  "lodoss-war-complete-series-english-dub-mp4s-ost::Lodoss War MP4s + OST/01. Record of Lodoss War/Record Of Lodoss War 08_18.41.21.mp4": 1482,
  "lodoss-war-complete-series-english-dub-mp4s-ost::Lodoss War MP4s + OST/01. Record of Lodoss War/Record Of Lodoss War 08.ia.mp4": 1482,
  "lodoss-war-complete-series-english-dub-mp4s-ost::Lodoss War MP4s + OST/01. Record of Lodoss War/Record Of Lodoss War 09_18.42.48.mp4": 1488,
  "lodoss-war-complete-series-english-dub-mp4s-ost::Lodoss War MP4s + OST/01. Record of Lodoss War/Record Of Lodoss War 09.ia.mp4": 1488,
  "lodoss-war-complete-series-english-dub-mp4s-ost::Lodoss War MP4s + OST/01. Record of Lodoss War/Record Of Lodoss War 10_18.44.9.mp4": 1481,
  "lodoss-war-complete-series-english-dub-mp4s-ost::Lodoss War MP4s + OST/01. Record of Lodoss War/Record Of Lodoss War 10.ia.mp4": 1481,
  "lodoss-war-complete-series-english-dub-mp4s-ost::Lodoss War MP4s + OST/01. Record of Lodoss War/Record Of Lodoss War 11_18.45.31.mp4": 1480,
  "lodoss-war-complete-series-english-dub-mp4s-ost::Lodoss War MP4s + OST/01. Record of Lodoss War/Record Of Lodoss War 11.ia.mp4": 1480,
  "lodoss-war-complete-series-english-dub-mp4s-ost::Lodoss War MP4s + OST/01. Record of Lodoss War/Record Of Lodoss War 12_18.46.55.mp4": 1481,
  "lodoss-war-complete-series-english-dub-mp4s-ost::Lodoss War MP4s + OST/01. Record of Lodoss War/Record Of Lodoss War 12.ia.mp4": 1481,
  "lodoss-war-complete-series-english-dub-mp4s-ost::Lodoss War MP4s + OST/01. Record of Lodoss War/Record Of Lodoss War 13_18.48.17.mp4": 1486,
  "lodoss-war-complete-series-english-dub-mp4s-ost::Lodoss War MP4s + OST/01. Record of Lodoss War/Record Of Lodoss War 13.ia.mp4": 1486,
  "lodoss-war-complete-series-english-dub-mp4s-ost::Lodoss War MP4s + OST/02. Chronicles of the Heroic Knight/Chronicles Of The Heroic Knight 01_17.56.56.mp4": 1545,
  "lodoss-war-complete-series-english-dub-mp4s-ost::Lodoss War MP4s + OST/02. Chronicles of the Heroic Knight/Chronicles Of The Heroic Knight 01.ia.mp4": 1545,
  "lodoss-war-complete-series-english-dub-mp4s-ost::Lodoss War MP4s + OST/02. Chronicles of the Heroic Knight/Chronicles Of The Heroic Knight 02_17.58.18.mp4": 1505,
  "lodoss-war-complete-series-english-dub-mp4s-ost::Lodoss War MP4s + OST/02. Chronicles of the Heroic Knight/Chronicles Of The Heroic Knight 02.ia.mp4": 1505,
  "lodoss-war-complete-series-english-dub-mp4s-ost::Lodoss War MP4s + OST/02. Chronicles of the Heroic Knight/Chronicles Of The Heroic Knight 03_17.59.30.mp4": 1504,
  "lodoss-war-complete-series-english-dub-mp4s-ost::Lodoss War MP4s + OST/02. Chronicles of the Heroic Knight/Chronicles Of The Heroic Knight 03.ia.mp4": 1504,
  "lodoss-war-complete-series-english-dub-mp4s-ost::Lodoss War MP4s + OST/02. Chronicles of the Heroic Knight/Chronicles Of The Heroic Knight 04_18.0.42.mp4": 1503,
  "lodoss-war-complete-series-english-dub-mp4s-ost::Lodoss War MP4s + OST/02. Chronicles of the Heroic Knight/Chronicles Of The Heroic Knight 04.ia.mp4": 1503,
  "lodoss-war-complete-series-english-dub-mp4s-ost::Lodoss War MP4s + OST/02. Chronicles of the Heroic Knight/Chronicles Of The Heroic Knight 05_18.1.51.mp4": 1505,
  "lodoss-war-complete-series-english-dub-mp4s-ost::Lodoss War MP4s + OST/02. Chronicles of the Heroic Knight/Chronicles Of The Heroic Knight 05.ia.mp4": 1505,
  "lodoss-war-complete-series-english-dub-mp4s-ost::Lodoss War MP4s + OST/02. Chronicles of the Heroic Knight/Chronicles Of The Heroic Knight 06_18.3.0.mp4": 1504,
  "lodoss-war-complete-series-english-dub-mp4s-ost::Lodoss War MP4s + OST/02. Chronicles of the Heroic Knight/Chronicles Of The Heroic Knight 06.ia.mp4": 1504,
  "lodoss-war-complete-series-english-dub-mp4s-ost::Lodoss War MP4s + OST/02. Chronicles of the Heroic Knight/Chronicles Of The Heroic Knight 07_18.4.11.mp4": 1544,
  "lodoss-war-complete-series-english-dub-mp4s-ost::Lodoss War MP4s + OST/02. Chronicles of the Heroic Knight/Chronicles Of The Heroic Knight 07.ia.mp4": 1544,
  "lodoss-war-complete-series-english-dub-mp4s-ost::Lodoss War MP4s + OST/02. Chronicles of the Heroic Knight/Chronicles Of The Heroic Knight 08_18.5.20.mp4": 1503,
  "lodoss-war-complete-series-english-dub-mp4s-ost::Lodoss War MP4s + OST/02. Chronicles of the Heroic Knight/Chronicles Of The Heroic Knight 08.ia.mp4": 1503,
  "lodoss-war-complete-series-english-dub-mp4s-ost::Lodoss War MP4s + OST/02. Chronicles of the Heroic Knight/Chronicles Of The Heroic Knight 09_18.6.26.mp4": 1506,
  "lodoss-war-complete-series-english-dub-mp4s-ost::Lodoss War MP4s + OST/02. Chronicles of the Heroic Knight/Chronicles Of The Heroic Knight 09.ia.mp4": 1506,
  "lodoss-war-complete-series-english-dub-mp4s-ost::Lodoss War MP4s + OST/02. Chronicles of the Heroic Knight/Chronicles Of The Heroic Knight 10_18.7.31.mp4": 1504,
  "lodoss-war-complete-series-english-dub-mp4s-ost::Lodoss War MP4s + OST/02. Chronicles of the Heroic Knight/Chronicles Of The Heroic Knight 10.ia.mp4": 1504,
  "lodoss-war-complete-series-english-dub-mp4s-ost::Lodoss War MP4s + OST/02. Chronicles of the Heroic Knight/Chronicles Of The Heroic Knight 11_18.8.36.mp4": 1505,
  "lodoss-war-complete-series-english-dub-mp4s-ost::Lodoss War MP4s + OST/02. Chronicles of the Heroic Knight/Chronicles Of The Heroic Knight 11.ia.mp4": 1505,
  "lodoss-war-complete-series-english-dub-mp4s-ost::Lodoss War MP4s + OST/02. Chronicles of the Heroic Knight/Chronicles Of The Heroic Knight 12_18.9.50.mp4": 1504,
  "lodoss-war-complete-series-english-dub-mp4s-ost::Lodoss War MP4s + OST/02. Chronicles of the Heroic Knight/Chronicles Of The Heroic Knight 12.ia.mp4": 1504,
  "lodoss-war-complete-series-english-dub-mp4s-ost::Lodoss War MP4s + OST/02. Chronicles of the Heroic Knight/Chronicles Of The Heroic Knight 13_18.10.58.mp4": 1503,
  "lodoss-war-complete-series-english-dub-mp4s-ost::Lodoss War MP4s + OST/02. Chronicles of the Heroic Knight/Chronicles Of The Heroic Knight 13.ia.mp4": 1503,
  "lodoss-war-complete-series-english-dub-mp4s-ost::Lodoss War MP4s + OST/02. Chronicles of the Heroic Knight/Chronicles Of The Heroic Knight 14_18.12.6.mp4": 1543,
  "lodoss-war-complete-series-english-dub-mp4s-ost::Lodoss War MP4s + OST/02. Chronicles of the Heroic Knight/Chronicles Of The Heroic Knight 14.ia.mp4": 1543,
  "lodoss-war-complete-series-english-dub-mp4s-ost::Lodoss War MP4s + OST/02. Chronicles of the Heroic Knight/Chronicles Of The Heroic Knight 15_18.13.18.mp4": 1504,
  "lodoss-war-complete-series-english-dub-mp4s-ost::Lodoss War MP4s + OST/02. Chronicles of the Heroic Knight/Chronicles Of The Heroic Knight 15.ia.mp4": 1504,
  "lodoss-war-complete-series-english-dub-mp4s-ost::Lodoss War MP4s + OST/02. Chronicles of the Heroic Knight/Chronicles Of The Heroic Knight 16_18.14.25.mp4": 1504,
  "lodoss-war-complete-series-english-dub-mp4s-ost::Lodoss War MP4s + OST/02. Chronicles of the Heroic Knight/Chronicles Of The Heroic Knight 16.ia.mp4": 1504,
  "lodoss-war-complete-series-english-dub-mp4s-ost::Lodoss War MP4s + OST/02. Chronicles of the Heroic Knight/Chronicles Of The Heroic Knight 17_18.15.33.mp4": 1505,
  "lodoss-war-complete-series-english-dub-mp4s-ost::Lodoss War MP4s + OST/02. Chronicles of the Heroic Knight/Chronicles Of The Heroic Knight 17.ia.mp4": 1505,
  "lodoss-war-complete-series-english-dub-mp4s-ost::Lodoss War MP4s + OST/02. Chronicles of the Heroic Knight/Chronicles Of The Heroic Knight 18_18.16.45.mp4": 1504,
  "lodoss-war-complete-series-english-dub-mp4s-ost::Lodoss War MP4s + OST/02. Chronicles of the Heroic Knight/Chronicles Of The Heroic Knight 18.ia.mp4": 1504,
  "lodoss-war-complete-series-english-dub-mp4s-ost::Lodoss War MP4s + OST/02. Chronicles of the Heroic Knight/Chronicles Of The Heroic Knight 19_18.17.57.mp4": 1503,
  "lodoss-war-complete-series-english-dub-mp4s-ost::Lodoss War MP4s + OST/02. Chronicles of the Heroic Knight/Chronicles Of The Heroic Knight 19.ia.mp4": 1503,
  "lodoss-war-complete-series-english-dub-mp4s-ost::Lodoss War MP4s + OST/02. Chronicles of the Heroic Knight/Chronicles Of The Heroic Knight 20_18.19.10.mp4": 1502,
  "lodoss-war-complete-series-english-dub-mp4s-ost::Lodoss War MP4s + OST/02. Chronicles of the Heroic Knight/Chronicles Of The Heroic Knight 20.ia.mp4": 1502,
  "lodoss-war-complete-series-english-dub-mp4s-ost::Lodoss War MP4s + OST/02. Chronicles of the Heroic Knight/Chronicles Of The Heroic Knight 21_18.20.22.mp4": 1507,
  "lodoss-war-complete-series-english-dub-mp4s-ost::Lodoss War MP4s + OST/02. Chronicles of the Heroic Knight/Chronicles Of The Heroic Knight 21.ia.mp4": 1507,
  "lodoss-war-complete-series-english-dub-mp4s-ost::Lodoss War MP4s + OST/02. Chronicles of the Heroic Knight/Chronicles Of The Heroic Knight 22_18.21.35.mp4": 1504,
  "lodoss-war-complete-series-english-dub-mp4s-ost::Lodoss War MP4s + OST/02. Chronicles of the Heroic Knight/Chronicles Of The Heroic Knight 22.ia.mp4": 1504,
  "lodoss-war-complete-series-english-dub-mp4s-ost::Lodoss War MP4s + OST/02. Chronicles of the Heroic Knight/Chronicles Of The Heroic Knight 23_18.22.48.mp4": 1504,
  "lodoss-war-complete-series-english-dub-mp4s-ost::Lodoss War MP4s + OST/02. Chronicles of the Heroic Knight/Chronicles Of The Heroic Knight 23.ia.mp4": 1504,
  "lodoss-war-complete-series-english-dub-mp4s-ost::Lodoss War MP4s + OST/02. Chronicles of the Heroic Knight/Chronicles Of The Heroic Knight 24_18.24.0.mp4": 1502,
  "lodoss-war-complete-series-english-dub-mp4s-ost::Lodoss War MP4s + OST/02. Chronicles of the Heroic Knight/Chronicles Of The Heroic Knight 24.ia.mp4": 1502,
  "lodoss-war-complete-series-english-dub-mp4s-ost::Lodoss War MP4s + OST/02. Chronicles of the Heroic Knight/Chronicles Of The Heroic Knight 25_18.25.8.mp4": 1506,
  "lodoss-war-complete-series-english-dub-mp4s-ost::Lodoss War MP4s + OST/02. Chronicles of the Heroic Knight/Chronicles Of The Heroic Knight 25.ia.mp4": 1506,
  "lodoss-war-complete-series-english-dub-mp4s-ost::Lodoss War MP4s + OST/02. Chronicles of the Heroic Knight/Chronicles Of The Heroic Knight 26_18.26.18.mp4": 1505,
  "lodoss-war-complete-series-english-dub-mp4s-ost::Lodoss War MP4s + OST/02. Chronicles of the Heroic Knight/Chronicles Of The Heroic Knight 26.ia.mp4": 1505,
  "lodoss-war-complete-series-english-dub-mp4s-ost::Lodoss War MP4s + OST/02. Chronicles of the Heroic Knight/Chronicles Of The Heroic Knight 27_18.27.30.mp4": 1472,
  "lodoss-war-complete-series-english-dub-mp4s-ost::Lodoss War MP4s + OST/02. Chronicles of the Heroic Knight/Chronicles Of The Heroic Knight 27.ia.mp4": 1472,
  "lodoss-war-complete-series-english-dub-mp4s-ost::Lodoss War MP4s + OST/03. Legend of Crystania/Legend Of Crystania Movie_18.28.49.mp4": 4670,
  "lodoss-war-complete-series-english-dub-mp4s-ost::Lodoss War MP4s + OST/03. Legend of Crystania/Legend Of Crystania Movie.ia.mp4": 4670,
  "lodoss-war-complete-series-english-dub-mp4s-ost::Lodoss War MP4s + OST/04. The Chaos Ring OVA/The Chaos Ring 01_18.49.48.mp4": 2682,
  "lodoss-war-complete-series-english-dub-mp4s-ost::Lodoss War MP4s + OST/04. The Chaos Ring OVA/The Chaos Ring 01.ia.mp4": 2682,
  "lodoss-war-complete-series-english-dub-mp4s-ost::Lodoss War MP4s + OST/04. The Chaos Ring OVA/The Chaos Ring 02_18.51.51.mp4": 1318,
  "lodoss-war-complete-series-english-dub-mp4s-ost::Lodoss War MP4s + OST/04. The Chaos Ring OVA/The Chaos Ring 02.ia.mp4": 1318,
  "lodoss-war-complete-series-english-dub-mp4s-ost::Lodoss War MP4s + OST/04. The Chaos Ring OVA/The Chaos Ring 03_18.52.51.mp4": 1226,
  "lodoss-war-complete-series-english-dub-mp4s-ost::Lodoss War MP4s + OST/04. The Chaos Ring OVA/The Chaos Ring 03.ia.mp4": 1226,
  "lodoss-war-complete-series-english-dub-mp4s-ost::Lodoss War MP4s + OST/04. The Chaos Ring OVA/The Chaos Ring 04_18.53.47.mp4": 2600,
  "lodoss-war-complete-series-english-dub-mp4s-ost::Lodoss War MP4s + OST/04. The Chaos Ring OVA/The Chaos Ring 04.ia.mp4": 2600,
},
};
