window.SHOW = {
  id: "RoadRules",
  title: "Road Rules",
  art: "RoadRules.jpg",
  storageProgressKey: "roadrules-progress",
  storageSettingsKey: "roadrules-settings",
  nestedPaths: false,
  grouping: "season",
  segments: "none",
  seasonNames: {"0": "Specials"},
  episodes: [
  ["the-making-of-road-rules", "ROAD RULES - S00E01 - The Making of Road Rules",
    "The Making of Road Rules.mp4"],
  ["road-rules-s-01ep-15-visit-the-rockford-speedway-for-a-smash-up-time", "ROAD RULES - S01E15 - Visit the Rockford Speedway for a Smash-Up Time",
    "Road Rules - s01ep15 -Visit the Rockford Speedway for a Smash-Up Time.mp4"],
  ["road-rules-s2", "ROAD RULES - S02E01 - Hello, My Name Is",
    "Road Rules 2x01 - Hello, My Name Is.mp4"],
  ["road-rules-s2", "ROAD RULES - S02E02 - Your Mission Is",
    "Road Rules 2x02 - Your Mission Is.mp4"],
  ["road-rules-s2", "ROAD RULES - S02E03 - Walking on Water",
    "Road Rules 2x03 - Walking on Water.mp4"],
  ["road-rules-s2", "ROAD RULES - S02E04 - Beads and Resentment",
    "Road Rules 2x04 - Beads and Resentment.mp4"],
  ["road-rules-s2", "ROAD RULES - S02E05 - Love and the Battlefield",
    "Road Rules 2x05 - Love and the Battlefield.mp4"],
  ["road-rules-s2", "ROAD RULES - S02E06 - Bird's Eye View",
    "Road Rules 2x06 - Bird's Eye View.mp4"],
  ["road-rules-s2", "ROAD RULES - S02E07 - Choose or Lose",
    "Road Rules 2x07 - Choose or Lose.mp4"],
  ["road-rules-s2", "ROAD RULES - S02E08 - Elvis Time",
    "Road Rules 2x08 - Elvis Time.mp4"],
  ["road-rules-s2", "ROAD RULES - S02E09 - Cowboys and Newspeople",
    "Road Rules 2x09 - Cowboys and Newspeople.mp4"],
  ["road-rules-s2", "ROAD RULES - S02E10 - It's Raining, It's Snowing",
    "Road Rules 2x10 - It's Raining, It's Snowing.mp4"],
  ["road-rules-s2", "ROAD RULES - S02E11 - At the Old Ball Game",
    "Road Rules 2x11 - At the Old Ball Game.mp4"],
  ["road-rules-s2", "ROAD RULES - S02E12 - Bikes and Parents",
    "Road Rules 2x12 - Bikes and Parents.mp4"],
  ["road-rules-s2", "ROAD RULES - S02E13 - Matzah and Dogfights",
    "Road Rules 2x13 - Matzah and Dogfights.mp4"],
  ["road-rules-s2", "ROAD RULES - S02E14 - Pulling a Farley",
    "Road Rules 2x14 - Pulling a Farley.mp4"],
  ["road-rules-s2", "ROAD RULES - S02E15 - For Sale and Goodbye",
    "Road Rules 2x15 - For Sale and Goodbye.mp4"],
  ["road-rules-s2", "ROAD RULES - S02E16 - When Chickens Learn to Fly",
    "Road Rules 2x16 - When Chickens Learn to Fly.mp4"],
  ["road-rules-europe", "ROAD RULES - S03E01 - Bonjour Roadies",
    "Road Rules 3x01 - Bonjour Roadies.mp4"],
  ["road-rules-europe", "ROAD RULES - S03E02 - Love Hurts",
    "Road Rules 3x02 - Love Hurts.mp4"],
  ["road-rules-europe", "ROAD RULES - S03E03 - On the Edge of Your Fears",
    "Road Rules 3x03 - On the Edge of Your Fears.mp4"],
  ["road-rules-europe", "ROAD RULES - S03E04 - The Contest",
    "Road Rules 3x04 - The Contest.mp4"],
  ["road-rules-europe", "ROAD RULES - S03E05 - Water Games",
    "Road Rules 3x05 - Water Games.mp4"],
  ["road-rules-europe", "ROAD RULES - S03E06 - Knives on the Canal",
    "Road Rules 3x06 - Knives on the Canal.mp4"],
  ["road-rules-europe", "ROAD RULES - S03E07 - In the Ring",
    "Road Rules 3x07 - In the Ring.mp4"],
  ["road-rules-europe", "ROAD RULES - S03E08 - Giving a Helping Flipper",
    "Road Rules 3x08 - Giving a Helping Flipper.mp4"],
  ["road-rules-europe", "ROAD RULES - S03E09 - Strutting Their Stuff",
    "Road Rules 3x09 - Strutting Their Stuff.mp4"],
  ["road-rules-europe", "ROAD RULES - S03E10 - Out the Window",
    "Road Rules 3x10 - Out the Window.mp4"],
  ["road-rules-europe", "ROAD RULES - S03E11 - Sex Wax on the Beach",
    "Road Rules 3x11 - Sex Wax on the Beach.mp4"],
  ["road-rules-europe", "ROAD RULES - S03E12 - Flying with the Birds",
    "Road Rules 3x12 - Flying with the Birds.mp4"],
  ["road-rules-europe", "ROAD RULES - S03E13 - Tomatoes on the Mind",
    "Road Rules 3x13 - Tomatoes on the Mind.mp4"],
  ["road-rules-islands", "ROAD RULES - S04E01 - Nice to Meet You",
    "Road Rules 4x01 - Nice to Meet You.mp4"],
  ["road-rules-islands", "ROAD RULES - S04E02 - Latin Male + Assertive Female = Danger",
    "Road Rules 4x02 - Latin Male + Assertive Female = Danger.mp4"],
  ["road-rules-islands", "ROAD RULES - S04E03 - Comedy Is No Laughing Matter",
    "Road Rules 4x03 - Comedy Is No Laughing Matter.mp4"],
  ["road-rules-islands", "ROAD RULES - S04E04 - Fear of Heights",
    "Road Rules 4x04 - Fear of Heights.mp4"],
  ["road-rules-islands", "ROAD RULES - S04E05 - Hunters and Gatherers",
    "Road Rules 4x05 - Hunters and Gatherers.mp4"],
  ["road-rules-islands", "ROAD RULES - S04E06 - Bee Stung Lips and Deserted Island Tips",
    "Road Rules 4x06 - Bee Stung Lips and Deserted Island Tips.mp4"],
  ["road-rules-islands", "ROAD RULES - S04E07 - Grumpy Goats, Goofy Gang Members and a Gorgeous Girl",
    "Road Rules 4x07 - Grumpy Goats, Goofy Gang Members and a Gorgeous Girl.mp4"],
  ["road-rules-islands", "ROAD RULES - S04E08 - If Your Friend Jumped Off a Bridge",
    "Road Rules 4x08 - If Your Friend Jumped Off a Bridge.mp4"],
  ["road-rules-islands", "ROAD RULES - S04E09 - The Real World vs. Road Rules Challenge Part 1",
    "Road Rules 4x09 - The Real World vs. Road Rules Challenge Part 1.mp4"],
  ["road-rules-islands", "ROAD RULES - S04E10 - The Real World vs. Road Rules Challenge Part 2",
    "Road Rules 4x10 - The Real World vs. Road Rules Challenge Part 2.mp4"],
  ["road-rules-islands", "ROAD RULES - S04E11 - Three Legs, Two Broken Toes and One Lava Pit",
    "Road Rules 4x11 - Three Legs, Two Broken Toes and One Lava Pit.mp4"],
  ["road-rules-islands", "ROAD RULES - S04E12 - Love Is in the Airwaves",
    "Road Rules 4x12 - Love Is in the Airwaves.mp4"],
  ["road-rules-islands", "ROAD RULES - S04E13 - The Last Dance and a Slippery Romance",
    "Road Rules 4x13 - The Last Dance and a Slippery Romance.mp4"],
  ["road-rules-islands", "ROAD RULES - S04E14 - Don't Drop the Soap",
    "Road Rules 4x14 - Don't Drop the Soap.mp4"],
  ["road-rules-islands", "ROAD RULES - S04E15 - Fire and Water",
    "Road Rules 4x15 - Fire and Water.mp4"],
  ["rrasaiu", "ROAD RULES - S05E01 - Five Easy Pieces",
    "Road Rules All Stars 1x01 - Five Easy Pieces.mp4"],
  ["rrasaiu", "ROAD RULES - S05E02 - Shear Madness",
    "Road Rules All Stars 1x02 - Shear Madness.mp4"],
  ["rrasaiu", "ROAD RULES - S05E03 - A Radish In A Salad Spinner",
    "Road Rules All Stars 1x03 - A Radish In A Salad Spinner.mp4"],
  ["rrasaiu", "ROAD RULES - S05E04 - How To Eat Fried Worms",
    "Road Rules All Stars 1x04 - How To Eat Fried Worms.mp4"],
  ["rrasaiu", "ROAD RULES - S05E05 - Fresh Squeezed Creative Juices",
    "Road Rules All Stars 1x05 - Fresh Squeezed Creative Juices.mp4"],
  ["road-rules-6", "ROAD RULES - S06E01 - Clip a Koala to Your Collar",
    "Road Rules 6x01 - Clip a Koala to Your Collar.mp4"],
  ["road-rules-6", "ROAD RULES - S06E02 - Got Milk",
    "Road Rules 6x02 - Got Milk.mp4"],
  ["road-rules-6", "ROAD RULES - S06E03 - Where There's Smoke, There's a Mission",
    "Road Rules 6x03 - Where There's Smoke, There's a Mission.mp4"],
  ["road-rules-6", "ROAD RULES - S06E04 - Fast Food Drive Through",
    "Road Rules 6x04 - Fast Food Drive Through.mp4"],
  ["road-rules-6", "ROAD RULES - S06E05 - Aliens Abduct Road Rulers",
    "Road Rules 6x05 - Aliens Abduct Road Rulers.mp4"],
  ["road-rules-6", "ROAD RULES - S06E06 - How Not to Drown in the Ocean of Piggy Tension",
    "Road Rules 6x06 - How Not to Drown in the Ocean of Piggy Tension.mp4"],
  ["road-rules-6", "ROAD RULES - S06E07 - Teaching to Learn",
    "Road Rules 6x07 - Teaching to Learn.mp4"],
  ["road-rules-6", "ROAD RULES - S06E08 - Croc Farming and Susie Blossoming",
    "Road Rules 6x08 - Croc Farming and Susie Blossoming.mp4"],
  ["road-rules-6", "ROAD RULES - S06E09 - A Ghost Thrives Better Than Piggy Drives",
    "Road Rules 6x09 - A Ghost Thrives Better Than Piggy Drives.mp4"],
  ["road-rules-6", "ROAD RULES - S06E10 - An Order of Footie With a Side of Flirting",
    "Road Rules 6x10 - An Order of Footie With a Side of Flirting.mp4"],
  ["road-rules-6", "ROAD RULES - S06E11 - Australian Rules Romance",
    "Road Rules 6x11 - Australian Rules Romance.mp4"],
  ["road-rules-6", "ROAD RULES - S06E12 - End of the Road",
    "Road Rules 6x12 - End of the Road.mp4"],
  ["road-rules-7", "ROAD RULES - S07E01 - Ai Chihuahua",
    "Road Rules 7x01 - Ai Chihuahua.mp4"],
  ["road-rules-7", "ROAD RULES - S07E02 - Cinema Spaghettios",
    "Road Rules 7x02 - Cinema Spaghettios.mp4"],
  ["road-rules-7", "ROAD RULES - S07E03 - Trust",
    "Road Rules 7x03 - Trust.mp4"],
  ["road-rules-7", "ROAD RULES - S07E04 - Fight the Bull",
    "Road Rules 7x04 - Fight the Bull.mp4"],
  ["road-rules-7", "ROAD RULES - S07E05 - Tigers and Sharks",
    "Road Rules 7x05 - Tigers and Sharks.mp4"],
  ["road-rules-7", "ROAD RULES - S07E06 - Sticks and Stones",
    "Road Rules 7x06 - Sticks and Stones.mp4"],
  ["road-rules-7", "ROAD RULES - S07E07 - Deep Sea Therapy",
    "Road Rules 7x07 - Deep Sea Therapy.mp4"],
  ["road-rules-7", "ROAD RULES - S07E08 - This One's for Gladys",
    "Road Rules 7x08 - This One's for Gladys.mp4"],
  ["road-rules-7", "ROAD RULES - S07E09 - Strike the Gold",
    "Road Rules 7x09 - Strike the Gold.mp4"],
  ["road-rules-7", "ROAD RULES - S07E10 - Into the Heart of Darkness",
    "Road Rules 7x10 - Into the Heart of Darkness.mp4"],
  ["road-rules-7", "ROAD RULES - S07E11 - Image Is Everything",
    "Road Rules 7x11 - Image Is Everything.mp4"],
  ["road-rules-7", "ROAD RULES - S07E12 - The Renegades Strike",
    "Road Rules 7x12 - The Renegades Strike.mp4"],
  ["road-rules-7", "ROAD RULES - S07E13 - Sleepless on Snake Island",
    "Road Rules 7x13 - Sleepless on Snake Island.mp4"],
  ["road-rules-7", "ROAD RULES - S07E14 - Handsome Reward",
    "Road Rules 7x14 - Handsome Reward.mp4"],
  ["road-rules-semester-at-sea", "ROAD RULES - S08E01 - Semester at Sea",
    "Episode 1 - Semester at Sea.mp4"],
  ["road-rules-semester-at-sea", "ROAD RULES - S08E02 - All Aboard",
    "Episode 2 - All Aboard.mp4"],
  ["road-rules-semester-at-sea", "ROAD RULES - S08E03 - Running Off With the Circus",
    "Episode 3 - Running Off With the Circus.mp4"],
  ["road-rules-semester-at-sea", "ROAD RULES - S08E04 - Answering the School Bell",
    "Episode 4 - Answering the School Bell.mp4"],
  ["road-rules-semester-at-sea", "ROAD RULES - S08E05 - A Coming Home",
    "Episode 5 - A Coming Home.mp4"],
  ["road-rules-semester-at-sea", "ROAD RULES - S08E06 - A Coming Home",
    "Episode 6 - A Coming Home.mp4"],
  ["road-rules-semester-at-sea", "ROAD RULES - S08E07 - Pawel's Kenyan Experience",
    "Episode 7 - Pawel's Kenyan Experience.mp4"],
  ["road-rules-semester-at-sea", "ROAD RULES - S08E08 - Hot Voodoo",
    "Episode 8 - Hot Voodoo.mp4"],
  ["road-rules-semester-at-sea", "ROAD RULES - S08E09 - Putting Together",
    "Episode 9 - Putting Together.mp4"],
  ["road-rules-semester-at-sea", "ROAD RULES - S08E10 - Paint or Pay",
    "Episode 10 - Paint or Pay.mp4"],
  ["road-rules-semester-at-sea", "ROAD RULES - S08E11 - Just Say Yes",
    "Episode 11 - Just Say Yes.mp4"],
  ["road-rules-semester-at-sea", "ROAD RULES - S08E12 - Good Morning Vietnam",
    "Episode 12 - Good Morning Vietnam.mp4"],
  ["road-rules-semester-at-sea", "ROAD RULES - S08E13 - Ho Chih Minh's Millions",
    "Episode 13 - Ho Chih Minh's Millions.mp4"],
  ["road-rules-semester-at-sea", "ROAD RULES - S08E14 - Growing and Rowing",
    "Episode 14 - Growing and Rowing.mp4"],
  ["road-rules-semester-at-sea", "ROAD RULES - S08E15 - Shanghai Surprise",
    "Episode 15 - Shanghai Surprise.mp4"],
  ["road-rules-semester-at-sea", "ROAD RULES - S08E16 - The Perils of Pua",
    "Episode 16 - The Perils of Pua.mp4"],
  ["road-rules-semester-at-sea", "ROAD RULES - S08E17 - Accusations",
    "Episode 17 - Accusations.mp4"],
  ["road-rules-semester-at-sea", "ROAD RULES - S08E18 - 10 Days - Part 1",
    "Episode 18 - 10 Days - Part 1.mp4"],
  ["road-rules-semester-at-sea", "ROAD RULES - S08E19 - 10 Days - Part 2",
    "Episode 19 - 10 Days - Part 2.mp4"],
  ["road-rules-maximum-velocity-tour", "ROAD RULES - S09E01 - Walking on the Wind",
    "S09E01-Walking on the Wind-x264.mp4"],
  ["road-rules-maximum-velocity-tour", "ROAD RULES - S09E10 - A Square in a Social Circle",
    "S09E10-A Square in a Social Circle-x264.mp4"],
  ["road-rules-maximum-velocity-tour", "ROAD RULES - S09E19 - The Ball and Chain",
    "S09E19-The Ball and Chain-x264.mp4"],
  ["road-rules-the-quest", "ROAD RULES - S10E01 - Quest for the Crest",
    "S10E01 - Quest for the Crest.mp4"],
  ["road-rules-the-quest", "ROAD RULES - S10E02 - Snakes, Snakes Everywhere",
    "S10E02 - Snakes, Snakes Everywhere.mp4"],
  ["road-rules-the-quest", "ROAD RULES - S10E03 - Sex, Camels, and Deliveries",
    "S10E03 - Sex, Camels, and Deliveries.mp4"],
  ["road-rules-the-quest", "ROAD RULES - S10E04 - Falling Head over Heals",
    "S10E04 - Falling Head over Heals.mp4"],
  ["road-rules-the-quest", "ROAD RULES - S10E05 - Hanging by a Line",
    "S10E05 - Hanging by a Line.mp4"],
  ["road-rules-the-quest", "ROAD RULES - S10E06 - One by the Wayside",
    "S10E06 - One by the Wayside.mp4"],
  ["road-rules-the-quest", "ROAD RULES - S10E07 - Enter the Katie",
    "S10E07 - Enter the Katie.mp4"],
  ["road-rules-the-quest", "ROAD RULES - S10E08 - Just Eat Cake",
    "S10E08 - Just Eat Cake.mp4"],
  ["road-rules-the-quest", "ROAD RULES - S10E09 - Up a Slick Pole",
    "S10E09 - Up a Slick Pole.mp4"],
  ["road-rules-the-quest", "ROAD RULES - S10E10 - Swimming in the Dating Pool",
    "S10E10 - Swimming in the Dating Pool.mp4"],
  ["road-rules-the-quest", "ROAD RULES - S10E11 - Jumping with the Jones",
    "S10E11 - Jumping with the Jones.mp4"],
  ["road-rules-the-quest", "ROAD RULES - S10E12 - Hanging by a Line",
    "S10E12 - Hanging by a Line.mp4"],
  ["road-rules-the-quest", "ROAD RULES - S10E13 - Pigeons and Quitters",
    "S10E13 - Pigeons and Quitters.mp4"],
  ["road-rules-the-quest", "ROAD RULES - S10E14 - Desert Dueling",
    "S10E14 - Desert Dueling.mp4"],
  ["road-rules-the-quest", "ROAD RULES - S10E15 - Unfair Warfare",
    "S10E15 - Unfair Warfare.mp4"],
  ["road-rules-the-quest", "ROAD RULES - S10E16 - Sad Goodbyes",
    "S10E16 - Sad Goodbyes.mp4"],
  ["road-rules-11", "ROAD RULES - S11E01 - The Woodie Crawl",
    "Road Rules 11x01 - The Woodie Crawl.mp4"],
  ["road-rules-11", "ROAD RULES - S11E02 - Rollin Rollin",
    "Road Rules 11x02 - Rollin Rollin.mp4"],
  ["road-rules-11", "ROAD RULES - S11E03 - Marching to Sorrow",
    "Road Rules 11x03 - Marching to Sorrow.mp4"],
  ["road-rules-11", "ROAD RULES - S11E04 - Rappin to Win",
    "Road Rules 11x04 - Rappin to Win.mp4"],
  ["road-rules-11", "ROAD RULES - S11E05 - Slaps and Failure",
    "Road Rules 11x05 - Slaps and Failure.mp4"],
  ["road-rules-11", "ROAD RULES - S11E06 - Alligators, Bugs, and Snakes Oh My",
    "Road Rules 11x06 - Alligators, Bugs, and Snakes Oh My.mp4"],
  ["road-rules-11", "ROAD RULES - S11E07 - The Naked Truth",
    "Road Rules 11x07 - The Naked Truth.mp4"],
  ["road-rules-11", "ROAD RULES - S11E08 - Dean Jumping",
    "Road Rules 11x08 - Dean Jumping.mp4"],
  ["road-rules-11", "ROAD RULES - S11E09 - Surfing to Goodbye Part 1",
    "Road Rules 11x09 - Surfing to Goodbye Part 1.mp4"],
  ["road-rules-11", "ROAD RULES - S11E10 - Surfing to Goodbye Part 2",
    "Road Rules 11x10 - Surfing to Goodbye Part 2.mp4"],
  ["road-rules-11", "ROAD RULES - S11E11 - Organs Anyone",
    "Road Rules 11x11 - Organs Anyone.mp4"],
  ["road-rules-11", "ROAD RULES - S11E12 - Sex Ed Gross Style",
    "Road Rules 11x12 - Sex Ed Gross Style.mp4"],
  ["road-rules-11", "ROAD RULES - S11E13 - Falling Over Pain",
    "Road Rules 11x13 - Falling Over Pain.mp4"],
  ["road-rules-11", "ROAD RULES - S11E14 - Outwitting the World",
    "Road Rules 11x14 - Outwitting the World.mp4"],
  ["road-rules-11", "ROAD RULES - S11E15 - Drinking and Wrestling",
    "Road Rules 11x15 - Drinking and Wrestling.mp4"],
  ["road-rules-11", "ROAD RULES - S11E16 - Blindfolded Around the World",
    "Road Rules 11x16 - Blindfolded Around the World.mp4"],
  ["road-rules-south-pacific", "ROAD RULES - S12E00 - Get In, It's Road Rules South Pacific",
    "Episode 0 - Get In, It's Road Rules South Pacific.mp4"],
  ["road-rules-south-pacific", "ROAD RULES - S12E01 - Around the World",
    "Episode 1 - Around the World.mp4"],
  ["road-rules-south-pacific", "ROAD RULES - S12E02 - Buried Alive",
    "Episode 2 - Buried Alive.mp4"],
  ["road-rules-south-pacific", "ROAD RULES - S12E03 - Only the Strong Survive",
    "Episode 3 - Only the Strong Survive.mp4"],
  ["road-rules-south-pacific", "ROAD RULES - S12E04 - Search for the Cure",
    "Episode 4 - Search for the Cure.mp4"],
  ["road-rules-south-pacific", "ROAD RULES - S12E05 - Climb to Jump",
    "Episode 5 - Climb to Jump.mp4"],
  ["road-rules-south-pacific", "ROAD RULES - S12E06 - Family Feud - Roadies Style",
    "Episode 6 - Family Feud - Roadies Style.mp4"],
  ["road-rules-south-pacific", "ROAD RULES - S12E07 - Strip Tease",
    "Episode 7 - Strip Tease.mp4"],
  ["road-rules-south-pacific", "ROAD RULES - S12E08 - Catch Me If you Can",
    "Episode 8 - Catch Me If you Can.mp4"],
  ["road-rules-south-pacific", "ROAD RULES - S12E09 - Rock Diving",
    "Episode 9 - Rock Diving.mp4"],
  ["road-rules-south-pacific", "ROAD RULES - S12E10 - Glacier Climb",
    "Episode 10 - Glacier Climb.mp4"],
  ["road-rules-south-pacific", "ROAD RULES - S12E11 - Little House on the Prairie",
    "Episode 11 - Little House on the Prairie.mp4"],
  ["road-rules-south-pacific", "ROAD RULES - S12E12 - Sensory Race",
    "Episode 12 - Sensory Race.mp4"],
  ["road-rules-south-pacific", "ROAD RULES - S12E13 - Put the Skills to the Test",
    "Episode 13 - Put the Skills to the Test.mp4"],
  ["road-rules-south-pacific", "ROAD RULES - S12E14 - Face Off",
    "Episode 14 - Face Off.mp4"],
  ["road-rules-south-pacific", "ROAD RULES - S12E15 - Face Off 2",
    "Episode 15 - Face Off 2.mp4"],
  ["road-rules-south-pacific", "ROAD RULES - S12E16 - Fire Walk",
    "Episode 16 - Fire Walk.mp4"],
  ["road-rules-south-pacific", "ROAD RULES - S12E17 - Handsome Reward",
    "Episode 17 - Handsome Reward.mp4"],
  ["road-rules-x-treme", "ROAD RULES - S13E01 - Volcano Bungee",
    "S13E01 - Volcano Bungee.mp4"],
  ["road-rules-x-treme", "ROAD RULES - S13E02 - Waterfall Rappel",
    "S13E02 - Waterfall Rappel.mp4"],
  ["road-rules-x-treme", "ROAD RULES - S13E03 - Living Art",
    "S13E03 - Living Art.mp4"],
  ["road-rules-x-treme", "ROAD RULES - S13E04 - Don't Have a Cow",
    "S13E04 - Don't Have a Cow.mp4"],
  ["road-rules-x-treme", "ROAD RULES - S13E05 - Hold On!",
    "S13E05 - Hold On!.mp4"],
  ["road-rules-x-treme", "ROAD RULES - S13E06 - Blind Driving",
    "S13E06 - Blind Driving.mp4"],
  ["road-rules-x-treme", "ROAD RULES - S13E07 - Go Fetch",
    "S13E07 - Go Fetch.mp4"],
  ["road-rules-x-treme", "ROAD RULES - S13E08 - Leap Of Faith",
    "S13E08 - Leap Of Faith.mp4"],
  ["road-rules-x-treme", "ROAD RULES - S13E09 - Balance On Me",
    "S13E09 - Balance On Me.mp4"],
  ["road-rules-x-treme", "ROAD RULES - S13E10 - Falling At Your Feet",
    "S13E10 - Falling At Your Feet.mp4"],
  ["road-rules-x-treme", "ROAD RULES - S13E11 - Blind Leading The Blind",
    "S13E11 - Blind Leading The Blind.mp4"],
  ["road-rules-x-treme", "ROAD RULES - S13E12 - Measure Up",
    "S13E12 - Measure Up.mp4"],
  ["road-rules-x-treme", "ROAD RULES - S13E13 - Face Off (1)",
    "S13E13 Face Off (1).mp4"],
  ["road-rules-x-treme", "ROAD RULES - S13E14 - Face Off (2)",
    "S13E14 - Face Off (2).mp4"],
  ["road-rules-x-treme", "ROAD RULES - S13E15 - Stunt School",
    "S13E15 - Stunt School.mp4"],
  ["road-rules-x-treme", "ROAD RULES - S13E16 - Gondola Rescue",
    "S13E16 - Gondola Rescue.mp4"],
  ["road-rules-x-treme", "ROAD RULES - S13E17 - Handsome Reward",
    "S13E17 - Handsome Reward.mp4"],
  ["road-rules-2007", "ROAD RULES - S14E00 - Launch Special",
    "Launch Special.mp4"],
  ["road-rules-2007", "ROAD RULES - S14E01 - Road Rules is Back",
    "Road Rules 14x01 - Road Rules is Back.mp4"],
  ["road-rules-2007", "ROAD RULES - S14E02 - Abram Gets the Boot (Again)",
    "Road Rules 14x02 - Abram Gets the Boot (Again).mp4"],
  ["road-rules-2007", "ROAD RULES - S14E03 - A Pit Stop in the Sand",
    "Road Rules 14x03 - A Pit Stop in the Sand.mp4"],
  ["road-rules-2007", "ROAD RULES - S14E04 - Rocks and a Hard Place",
    "Road Rules 14x04 - Rocks and a Hard Place.mp4"],
  ["road-rules-2007", "ROAD RULES - S14E05 - Up to Speed",
    "Road Rules 14x05 - Up to Speed.mp4"],
  ["road-rules-2007", "ROAD RULES - S14E06 - World's Strongest Roadie",
    "Road Rules 14x06 - World's Strongest Roadie.mp4"],
  ["road-rules-2007", "ROAD RULES - S14E07 - The Roadies Do Spring Break",
    "Road Rules 14x07 - The Roadies Do Spring Break.mp4"],
  ["road-rules-2007", "ROAD RULES - S14E08 - Mountain Warfare",
    "Road Rules 14x08 - Mountain Warfare.mp4"],
  ["road-rules-2007", "ROAD RULES - S14E09 - Let's Get Dirty",
    "Road Rules 14x09 - Let's Get Dirty.mp4"],
  ["road-rules-2007", "ROAD RULES - S14E10 - Assassins in Training",
    "Road Rules 14x10 - Assassins in Training.mp4"],
  ["road-rules-2007", "ROAD RULES - S14E11 - Stick It",
    "Road Rules 14x11 - Stick It.mp4"],
  ["road-rules-2007", "ROAD RULES - S14E12 - The Viewers Revenge Bowl",
    "Road Rules 14x12 - The Viewers Revenge Bowl.mp4"],
  ["road-rules-2007", "ROAD RULES - S14E13 - The Condemned",
    "Road Rules 14x13 - The Condemned.mp4"],
  ["road-rules-2007", "ROAD RULES - S14E14 - Vegas Circus",
    "Road Rules 14x14 - Vegas Circus.mp4"],
  ["road-rules-2007", "ROAD RULES - S14E15 - Viewers Revenge Finale",
    "Road Rules 14x15 - Viewers Revenge Finale.mp4"],
],
  durations: {
  "the-making-of-road-rules::The Making of Road Rules.mp4": 3453,
  "road-rules-s-01ep-15-visit-the-rockford-speedway-for-a-smash-up-time::Road Rules - s01ep15 -Visit the Rockford Speedway for a Smash-Up Time.mp4": 1350,
  "road-rules-s2::Road Rules 2x01 - Hello, My Name Is.mp4": 1212,
  "road-rules-s2::Road Rules 2x02 - Your Mission Is.mp4": 1188,
  "road-rules-s2::Road Rules 2x03 - Walking on Water.mp4": 1210,
  "road-rules-s2::Road Rules 2x04 - Beads and Resentment.mp4": 1216,
  "road-rules-s2::Road Rules 2x05 - Love and the Battlefield.mp4": 1209,
  "road-rules-s2::Road Rules 2x06 - Bird's Eye View.mp4": 1211,
  "road-rules-s2::Road Rules 2x07 - Choose or Lose.mp4": 1217,
  "road-rules-s2::Road Rules 2x08 - Elvis Time.mp4": 1214,
  "road-rules-s2::Road Rules 2x09 - Cowboys and Newspeople.mp4": 1249,
  "road-rules-s2::Road Rules 2x10 - It's Raining, It's Snowing.mp4": 1242,
  "road-rules-s2::Road Rules 2x11 - At the Old Ball Game.mp4": 1207,
  "road-rules-s2::Road Rules 2x12 - Bikes and Parents.mp4": 1210,
  "road-rules-s2::Road Rules 2x13 - Matzah and Dogfights.mp4": 1218,
  "road-rules-s2::Road Rules 2x14 - Pulling a Farley.mp4": 1214,
  "road-rules-s2::Road Rules 2x15 - For Sale and Goodbye.mp4": 1202,
  "road-rules-s2::Road Rules 2x16 - When Chickens Learn to Fly.mp4": 1233,
  "road-rules-europe::Road Rules 3x01 - Bonjour Roadies.mp4": 1203,
  "road-rules-europe::Road Rules 3x02 - Love Hurts.mp4": 1183,
  "road-rules-europe::Road Rules 3x03 - On the Edge of Your Fears.mp4": 1215,
  "road-rules-europe::Road Rules 3x04 - The Contest.mp4": 1210,
  "road-rules-europe::Road Rules 3x05 - Water Games.mp4": 1205,
  "road-rules-europe::Road Rules 3x06 - Knives on the Canal.mp4": 1212,
  "road-rules-europe::Road Rules 3x07 - In the Ring.mp4": 1214,
  "road-rules-europe::Road Rules 3x08 - Giving a Helping Flipper.mp4": 1207,
  "road-rules-europe::Road Rules 3x09 - Strutting Their Stuff.mp4": 1209,
  "road-rules-europe::Road Rules 3x10 - Out the Window.mp4": 1206,
  "road-rules-europe::Road Rules 3x11 - Sex Wax on the Beach.mp4": 1202,
  "road-rules-europe::Road Rules 3x12 - Flying with the Birds.mp4": 1222,
  "road-rules-europe::Road Rules 3x13 - Tomatoes on the Mind.mp4": 1224,
  "road-rules-islands::Road Rules 4x01 - Nice to Meet You.mp4": 2401,
  "road-rules-islands::Road Rules 4x02 - Latin Male + Assertive Female = Danger.mp4": 1204,
  "road-rules-islands::Road Rules 4x03 - Comedy Is No Laughing Matter.mp4": 1210,
  "road-rules-islands::Road Rules 4x04 - Fear of Heights.mp4": 1211,
  "road-rules-islands::Road Rules 4x05 - Hunters and Gatherers.mp4": 1223,
  "road-rules-islands::Road Rules 4x06 - Bee Stung Lips and Deserted Island Tips.mp4": 1204,
  "road-rules-islands::Road Rules 4x07 - Grumpy Goats, Goofy Gang Members and a Gorgeous Girl.mp4": 1168,
  "road-rules-islands::Road Rules 4x08 - If Your Friend Jumped Off a Bridge.mp4": 1207,
  "road-rules-islands::Road Rules 4x09 - The Real World vs. Road Rules Challenge Part 1.mp4": 1287,
  "road-rules-islands::Road Rules 4x10 - The Real World vs. Road Rules Challenge Part 2.mp4": 1289,
  "road-rules-islands::Road Rules 4x11 - Three Legs, Two Broken Toes and One Lava Pit.mp4": 1190,
  "road-rules-islands::Road Rules 4x12 - Love Is in the Airwaves.mp4": 1208,
  "road-rules-islands::Road Rules 4x13 - The Last Dance and a Slippery Romance.mp4": 1207,
  "road-rules-islands::Road Rules 4x14 - Don't Drop the Soap.mp4": 1207,
  "road-rules-islands::Road Rules 4x15 - Fire and Water.mp4": 1267,
  "rrasaiu::Road Rules All Stars 1x01 - Five Easy Pieces.mp4": 1257,
  "rrasaiu::Road Rules All Stars 1x02 - Shear Madness.mp4": 1164,
  "rrasaiu::Road Rules All Stars 1x03 - A Radish In A Salad Spinner.mp4": 1170,
  "rrasaiu::Road Rules All Stars 1x04 - How To Eat Fried Worms.mp4": 1171,
  "rrasaiu::Road Rules All Stars 1x05 - Fresh Squeezed Creative Juices.mp4": 1226,
  "road-rules-6::Road Rules 6x01 - Clip a Koala to Your Collar.mp4": 2526,
  "road-rules-6::Road Rules 6x02 - Got Milk.mp4": 1289,
  "road-rules-6::Road Rules 6x03 - Where There's Smoke, There's a Mission.mp4": 1274,
  "road-rules-6::Road Rules 6x04 - Fast Food Drive Through.mp4": 1178,
  "road-rules-6::Road Rules 6x05 - Aliens Abduct Road Rulers.mp4": 1287,
  "road-rules-6::Road Rules 6x06 - How Not to Drown in the Ocean of Piggy Tension.mp4": 1236,
  "road-rules-6::Road Rules 6x07 - Teaching to Learn.mp4": 1208,
  "road-rules-6::Road Rules 6x08 - Croc Farming and Susie Blossoming.mp4": 1180,
  "road-rules-6::Road Rules 6x09 - A Ghost Thrives Better Than Piggy Drives.mp4": 1183,
  "road-rules-6::Road Rules 6x10 - An Order of Footie With a Side of Flirting.mp4": 1209,
  "road-rules-6::Road Rules 6x11 - Australian Rules Romance.mp4": 1243,
  "road-rules-6::Road Rules 6x12 - End of the Road.mp4": 1292,
  "road-rules-7::Road Rules 7x01 - Ai Chihuahua.mp4": 2469,
  "road-rules-7::Road Rules 7x02 - Cinema Spaghettios.mp4": 1181,
  "road-rules-7::Road Rules 7x03 - Trust.mp4": 1181,
  "road-rules-7::Road Rules 7x04 - Fight the Bull.mp4": 1178,
  "road-rules-7::Road Rules 7x05 - Tigers and Sharks.mp4": 1175,
  "road-rules-7::Road Rules 7x06 - Sticks and Stones.mp4": 1152,
  "road-rules-7::Road Rules 7x07 - Deep Sea Therapy.mp4": 1156,
  "road-rules-7::Road Rules 7x08 - This One's for Gladys.mp4": 1168,
  "road-rules-7::Road Rules 7x09 - Strike the Gold.mp4": 1166,
  "road-rules-7::Road Rules 7x10 - Into the Heart of Darkness.mp4": 1176,
  "road-rules-7::Road Rules 7x11 - Image Is Everything.mp4": 1180,
  "road-rules-7::Road Rules 7x12 - The Renegades Strike.mp4": 1164,
  "road-rules-7::Road Rules 7x13 - Sleepless on Snake Island.mp4": 1154,
  "road-rules-7::Road Rules 7x14 - Handsome Reward.mp4": 1186,
  "road-rules-semester-at-sea::Episode 1 - Semester at Sea.mp4": 1221,
  "road-rules-semester-at-sea::Episode 2 - All Aboard.mp4": 1190,
  "road-rules-semester-at-sea::Episode 3 - Running Off With the Circus.mp4": 1169,
  "road-rules-semester-at-sea::Episode 4 - Answering the School Bell.mp4": 1192,
  "road-rules-semester-at-sea::Episode 5 - A Coming Home.mp4": 1159,
  "road-rules-semester-at-sea::Episode 6 - A Coming Home.mp4": 1131,
  "road-rules-semester-at-sea::Episode 7 - Pawel's Kenyan Experience.mp4": 1187,
  "road-rules-semester-at-sea::Episode 8 - Hot Voodoo.mp4": 1192,
  "road-rules-semester-at-sea::Episode 9 - Putting Together.mp4": 1157,
  "road-rules-semester-at-sea::Episode 10 - Paint or Pay.mp4": 1161,
  "road-rules-semester-at-sea::Episode 11 - Just Say Yes.mp4": 1161,
  "road-rules-semester-at-sea::Episode 12 - Good Morning Vietnam.mp4": 1168,
  "road-rules-semester-at-sea::Episode 13 - Ho Chih Minh's Millions.mp4": 1162,
  "road-rules-semester-at-sea::Episode 14 - Growing and Rowing.mp4": 1173,
  "road-rules-semester-at-sea::Episode 15 - Shanghai Surprise.mp4": 1147,
  "road-rules-semester-at-sea::Episode 16 - The Perils of Pua.mp4": 1190,
  "road-rules-semester-at-sea::Episode 17 - Accusations.mp4": 1186,
  "road-rules-semester-at-sea::Episode 18 - 10 Days - Part 1.mp4": 1200,
  "road-rules-semester-at-sea::Episode 19 - 10 Days - Part 2.mp4": 1196,
  "road-rules-maximum-velocity-tour::S09E01-Walking on the Wind-x264.mp4": 2581,
  "road-rules-maximum-velocity-tour::S09E10-A Square in a Social Circle-x264.mp4": 1288,
  "road-rules-maximum-velocity-tour::S09E19-The Ball and Chain-x264.mp4": 1230,
  "road-rules-the-quest::S10E01 - Quest for the Crest.mp4": 2482,
  "road-rules-the-quest::S10E02 - Snakes, Snakes Everywhere.mp4": 1171,
  "road-rules-the-quest::S10E03 - Sex, Camels, and Deliveries.mp4": 1204,
  "road-rules-the-quest::S10E04 - Falling Head over Heals.mp4": 1217,
  "road-rules-the-quest::S10E05 - Hanging by a Line.mp4": 1198,
  "road-rules-the-quest::S10E06 - One by the Wayside.mp4": 1204,
  "road-rules-the-quest::S10E07 - Enter the Katie.mp4": 1191,
  "road-rules-the-quest::S10E08 - Just Eat Cake.mp4": 1210,
  "road-rules-the-quest::S10E09 - Up a Slick Pole.mp4": 1215,
  "road-rules-the-quest::S10E10 - Swimming in the Dating Pool.mp4": 1210,
  "road-rules-the-quest::S10E11 - Jumping with the Jones.mp4": 1210,
  "road-rules-the-quest::S10E12 - Hanging by a Line.mp4": 1205,
  "road-rules-the-quest::S10E13 - Pigeons and Quitters.mp4": 1211,
  "road-rules-the-quest::S10E14 - Desert Dueling.mp4": 1215,
  "road-rules-the-quest::S10E15 - Unfair Warfare.mp4": 1208,
  "road-rules-the-quest::S10E16 - Sad Goodbyes.mp4": 1209,
  "road-rules-11::Road Rules 11x01 - The Woodie Crawl.mp4": 2573,
  "road-rules-11::Road Rules 11x02 - Rollin Rollin.mp4": 1217,
  "road-rules-11::Road Rules 11x03 - Marching to Sorrow.mp4": 1264,
  "road-rules-11::Road Rules 11x04 - Rappin to Win.mp4": 1261,
  "road-rules-11::Road Rules 11x05 - Slaps and Failure.mp4": 1246,
  "road-rules-11::Road Rules 11x06 - Alligators, Bugs, and Snakes Oh My.mp4": 1222,
  "road-rules-11::Road Rules 11x07 - The Naked Truth.mp4": 1250,
  "road-rules-11::Road Rules 11x08 - Dean Jumping.mp4": 1261,
  "road-rules-11::Road Rules 11x09 - Surfing to Goodbye Part 1.mp4": 1270,
  "road-rules-11::Road Rules 11x10 - Surfing to Goodbye Part 2.mp4": 1150,
  "road-rules-11::Road Rules 11x11 - Organs Anyone.mp4": 1217,
  "road-rules-11::Road Rules 11x12 - Sex Ed Gross Style.mp4": 1236,
  "road-rules-11::Road Rules 11x13 - Falling Over Pain.mp4": 1245,
  "road-rules-11::Road Rules 11x14 - Outwitting the World.mp4": 1237,
  "road-rules-11::Road Rules 11x15 - Drinking and Wrestling.mp4": 1331,
  "road-rules-11::Road Rules 11x16 - Blindfolded Around the World.mp4": 1285,
  "road-rules-south-pacific::Episode 0 - Get In, It's Road Rules South Pacific.mp4": 1290,
  "road-rules-south-pacific::Episode 1 - Around the World.mp4": 1255,
  "road-rules-south-pacific::Episode 2 - Buried Alive.mp4": 1255,
  "road-rules-south-pacific::Episode 3 - Only the Strong Survive.mp4": 1255,
  "road-rules-south-pacific::Episode 4 - Search for the Cure.mp4": 1255,
  "road-rules-south-pacific::Episode 5 - Climb to Jump.mp4": 1255,
  "road-rules-south-pacific::Episode 6 - Family Feud - Roadies Style.mp4": 1230,
  "road-rules-south-pacific::Episode 7 - Strip Tease.mp4": 1255,
  "road-rules-south-pacific::Episode 8 - Catch Me If you Can.mp4": 1252,
  "road-rules-south-pacific::Episode 9 - Rock Diving.mp4": 1256,
  "road-rules-south-pacific::Episode 10 - Glacier Climb.mp4": 1256,
  "road-rules-south-pacific::Episode 11 - Little House on the Prairie.mp4": 1256,
  "road-rules-south-pacific::Episode 12 - Sensory Race.mp4": 1255,
  "road-rules-south-pacific::Episode 13 - Put the Skills to the Test.mp4": 1256,
  "road-rules-south-pacific::Episode 14 - Face Off.mp4": 1254,
  "road-rules-south-pacific::Episode 15 - Face Off 2.mp4": 1256,
  "road-rules-south-pacific::Episode 16 - Fire Walk.mp4": 1311,
  "road-rules-south-pacific::Episode 17 - Handsome Reward.mp4": 1274,
  "road-rules-x-treme::S13E01 - Volcano Bungee.mp4": 1209,
  "road-rules-x-treme::S13E02 - Waterfall Rappel.mp4": 1167,
  "road-rules-x-treme::S13E03 - Living Art.mp4": 1123,
  "road-rules-x-treme::S13E04 - Don't Have a Cow.mp4": 1193,
  "road-rules-x-treme::S13E05 - Hold On!.mp4": 1184,
  "road-rules-x-treme::S13E06 - Blind Driving.mp4": 1193,
  "road-rules-x-treme::S13E07 - Go Fetch.mp4": 1161,
  "road-rules-x-treme::S13E08 - Leap Of Faith.mp4": 1191,
  "road-rules-x-treme::S13E09 - Balance On Me.mp4": 1150,
  "road-rules-x-treme::S13E10 - Falling At Your Feet.mp4": 1148,
  "road-rules-x-treme::S13E11 - Blind Leading The Blind.mp4": 1247,
  "road-rules-x-treme::S13E12 - Measure Up.mp4": 1249,
  "road-rules-x-treme::S13E13 Face Off (1).mp4": 1272,
  "road-rules-x-treme::S13E14 - Face Off (2).mp4": 1283,
  "road-rules-x-treme::S13E15 - Stunt School.mp4": 1285,
  "road-rules-x-treme::S13E16 - Gondola Rescue.mp4": 1287,
  "road-rules-x-treme::S13E17 - Handsome Reward.mp4": 1291,
  "road-rules-2007::Launch Special.mp4": 1294,
  "road-rules-2007::Road Rules 14x01 - Road Rules is Back.mp4": 1284,
  "road-rules-2007::Road Rules 14x02 - Abram Gets the Boot (Again).mp4": 1269,
  "road-rules-2007::Road Rules 14x03 - A Pit Stop in the Sand.mp4": 1282,
  "road-rules-2007::Road Rules 14x04 - Rocks and a Hard Place.mp4": 1239,
  "road-rules-2007::Road Rules 14x05 - Up to Speed.mp4": 1237,
  "road-rules-2007::Road Rules 14x06 - World's Strongest Roadie.mp4": 1236,
  "road-rules-2007::Road Rules 14x07 - The Roadies Do Spring Break.mp4": 1239,
  "road-rules-2007::Road Rules 14x08 - Mountain Warfare.mp4": 1235,
  "road-rules-2007::Road Rules 14x09 - Let's Get Dirty.mp4": 1234,
  "road-rules-2007::Road Rules 14x10 - Assassins in Training.mp4": 1231,
  "road-rules-2007::Road Rules 14x11 - Stick It.mp4": 1230,
  "road-rules-2007::Road Rules 14x12 - The Viewers Revenge Bowl.mp4": 1239,
  "road-rules-2007::Road Rules 14x13 - The Condemned.mp4": 1232,
  "road-rules-2007::Road Rules 14x14 - Vegas Circus.mp4": 1234,
  "road-rules-2007::Road Rules 14x15 - Viewers Revenge Finale.mp4": 1276,
},
};
