window.SHOW = {
  id: "HandmaidsTaleSeries",
  title: "the Handmaid's Tale Series",
  art: "HandmaidsTaleSeries.png",
  storageProgressKey: "handmaidstaleseries-progress",
  storageSettingsKey: "handmaidstaleseries-settings",
  nestedPaths: true,
  grouping: "season",
  segments: "none",
  episodes: [
  ["the-handmaids-tale2017-2025-complete-series", "THE HANDMAID'S TALE SERIES - S01E01 - Watch The Handmaids Tale Night",
    "Watch The Handmaids Tale - S3 EP 1 Night.ia.mp4"],
  ["the-handmaids-tale2017-2025-complete-series", "THE HANDMAID'S TALE SERIES - S01E02 - Watch The Handmaids Tale Unwomen",
    "Watch The Handmaids Tale - S2 EP 2 Unwomen..ia.mp4"],
  ["the-handmaids-tale2017-2025-complete-series", "THE HANDMAID'S TALE SERIES - S01E03 - Watch The Handmaids Tale Baggage",
    "Watch The Handmaids Tale - S2 EP3 Baggage.ia.mp4"],
  ["the-handmaids-tale2017-2025-complete-series", "THE HANDMAID'S TALE SERIES - S01E04 - Watch The Handmaids Tale Other Women",
    "Watch The Handmaids Tale S2 EP4 Other Women.ia.mp4"],
  ["the-handmaids-tale2017-2025-complete-series", "THE HANDMAID'S TALE SERIES - S01E05 - Watch The Handmaids Tale Seeds",
    "Watch The Handmaids Tale - S2 EP 5 Seeds.ia.mp4"],
  ["the-handmaids-tale2017-2025-complete-series", "THE HANDMAID'S TALE SERIES - S01E06 - Watch The Handmaids Tale First Blood",
    "Watch The Handmaids Tale - S2 EP 6 First Blood.ia.mp4"],
  ["the-handmaids-tale2017-2025-complete-series", "THE HANDMAID'S TALE SERIES - S01E07 - The Handmaids Tale After",
    "The Handmaids Tale - S2 EP 7 After.ia.mp4"],
  ["the-handmaids-tale2017-2025-complete-series", "THE HANDMAID'S TALE SERIES - S01E08 - Watch The Handmaids Tale Womens Work",
    "Watch The Handmaids Tale - S2 EP 8 Womens Work.ia.mp4"],
  ["the-handmaids-tale2017-2025-complete-series", "THE HANDMAID'S TALE SERIES - S01E09 - Watch The Handmaids Tale Smart Power",
    "Watch The Handmaids Tale - S 2 EP 9 Smart Power .ia.mp4"],
  ["the-handmaids-tale2017-2025-complete-series", "THE HANDMAID'S TALE SERIES - S01E10 - The Handmaids Tale Night",
    "The Handmaids Tale - S1 EP 10 Night.ia.mp4"],
  ["the-handmaids-tale2017-2025-complete-series", "THE HANDMAID'S TALE SERIES - S01E11 - The Handmaids Tale Holly",
    "The Handmaids Tale - S2 EP 11 Holly.ia.mp4"],
  ["the-handmaids-tale2017-2025-complete-series", "THE HANDMAID'S TALE SERIES - S01E12 - The Handmaids Tale Postpartum",
    "The Handmaids Tale- S2 EP 12 Postpartum.ia.mp4"],
  ["the-handmaids-tale2017-2025-complete-series", "THE HANDMAID'S TALE SERIES - S01E13 - Watch The Handmaids Tale The Word",
    "Watch The Handmaids Tale - S2 EP 13 The Word.ia.mp4"],
],
  durations: {
  "the-handmaids-tale2017-2025-complete-series::Watch The Handmaids Tale - S3 EP 1 Night.ia.mp4": 3001,
  "the-handmaids-tale2017-2025-complete-series::Watch The Handmaids Tale - S2 EP 2 Unwomen..ia.mp4": 3310,
  "the-handmaids-tale2017-2025-complete-series::Watch The Handmaids Tale - S2 EP3 Baggage.ia.mp4": 3484,
  "the-handmaids-tale2017-2025-complete-series::Watch The Handmaids Tale S2 EP4 Other Women.ia.mp4": 3256,
  "the-handmaids-tale2017-2025-complete-series::Watch The Handmaids Tale - S2 EP 5 Seeds.ia.mp4": 3105,
  "the-handmaids-tale2017-2025-complete-series::Watch The Handmaids Tale - S2 EP 6 First Blood.ia.mp4": 3500,
  "the-handmaids-tale2017-2025-complete-series::The Handmaids Tale - S2 EP 7 After.ia.mp4": 3316,
  "the-handmaids-tale2017-2025-complete-series::Watch The Handmaids Tale - S2 EP 8 Womens Work.ia.mp4": 3149,
  "the-handmaids-tale2017-2025-complete-series::Watch The Handmaids Tale - S 2 EP 9 Smart Power .ia.mp4": 3425,
  "the-handmaids-tale2017-2025-complete-series::The Handmaids Tale - S1 EP 10 Night.ia.mp4": 3604,
  "the-handmaids-tale2017-2025-complete-series::The Handmaids Tale - S2 EP 11 Holly.ia.mp4": 2856,
  "the-handmaids-tale2017-2025-complete-series::The Handmaids Tale- S2 EP 12 Postpartum.ia.mp4": 3278,
  "the-handmaids-tale2017-2025-complete-series::Watch The Handmaids Tale - S2 EP 13 The Word.ia.mp4": 3812,
},
};
