window.SHOW = {
  id: "HomeMovies",
  title: "Home Movies",
  art: "HomeMovies.jpg",
  storageProgressKey: "homemovies-progress",
  storageSettingsKey: "homemovies-settings",
  nestedPaths: true,
  grouping: "season",
  segments: "none",
  episodes: [
  ["home-movies-dvdiso", "HOME MOVIES - S01E01 - Get Away From My Mom",
    "HOMEMOVIES_DISC1.mp4"],
  ["home-movies-dvdiso", "HOME MOVIES - S01E02 - I Don't Do Well in Parent-Teacher Conferences",
    "HOMEMOVIES_DISC2.mp4"],
  ["home-movies-dvdiso", "HOME MOVIES - S01E03 - The Art of the Sucker Punch",
    "HOMEMOVIES_DISC3.mp4"],
  ["home-movies-dvdiso", "HOME MOVIES - S01E04 - Brendon Gets Rabies",
    "HOMEMOVIES_SEASON2_DISC1.mp4"],
  ["home-movies-dvdiso", "HOME MOVIES - S01E05 - Yoko",
    "HOMEMOVIES_SEASON2_DISC2.mp4"],
  ["home-movies-dvdiso", "HOME MOVIES - S01E06 - Director's Cut",
    "HOMEMOVIES_SEASON2_DISC3.mp4"],
  ["home-movies-dvdiso", "HOME MOVIES - S01E07 - It Was Supposed to Be Funny",
    "HOMEMOVIES_SEASON3_DISC1.mp4"],
  ["home-movies-dvdiso", "HOME MOVIES - S01E08 - Method of Acting",
    "HOMEMOVIES_SEASON3_DISC2.mp4"],
  ["home-movies-dvdiso", "HOME MOVIES - S01E09 - Life Through a Fisheye Lens",
    "HOMEMOVIES_SEASON3_DISC3.mp4"],
  ["home-movies-dvdiso", "HOME MOVIES - S01E10 - School Nurse",
    "HOMEMOVIES_SEASON4_DISC1.mp4"],
  ["home-movies-dvdiso", "HOME MOVIES - S01E11 - Mortgages & Marbles",
    "HOMEMOVIES_SEASON4_DISC2.mp4"],
  ["home-movies-dvdiso", "HOME MOVIES - S01E12 - Law and Boarder",
    "HOMEMOVIES_SEASON4_DISC3.mp4"],
],
  durations: {
  "home-movies-dvdiso::HOMEMOVIES_DISC1.mp4": 6689,
  "home-movies-dvdiso::HOMEMOVIES_DISC2.mp4": 5229,
  "home-movies-dvdiso::HOMEMOVIES_DISC3.mp4": 5377,
  "home-movies-dvdiso::HOMEMOVIES_SEASON2_DISC1.mp4": 5488,
  "home-movies-dvdiso::HOMEMOVIES_SEASON2_DISC2.mp4": 5415,
  "home-movies-dvdiso::HOMEMOVIES_SEASON2_DISC3.mp4": 6781,
  "home-movies-dvdiso::HOMEMOVIES_SEASON3_DISC1.mp4": 5411,
  "home-movies-dvdiso::HOMEMOVIES_SEASON3_DISC2.mp4": 5490,
  "home-movies-dvdiso::HOMEMOVIES_SEASON3_DISC3.mp4": 6819,
  "home-movies-dvdiso::HOMEMOVIES_SEASON4_DISC1.mp4": 5599,
  "home-movies-dvdiso::HOMEMOVIES_SEASON4_DISC2.mp4": 5551,
  "home-movies-dvdiso::HOMEMOVIES_SEASON4_DISC3.mp4": 6830,
},
};
