window.SHOW = {
  id: "Godzilla",
  title: "Godzilla",
  art: "Godzilla.jpg",
  storageProgressKey: "godzilla-progress",
  storageSettingsKey: "godzilla-settings",
  nestedPaths: true,
  grouping: "season",
  segments: "none",
  episodes: [
  ["godzilla-tnt-cn", "GODZILLA - S01E01 - The Firebird",
    "Godzilla-The original animated series/1) THE FIREBIRD.mp4"],
  ["godzilla-tnt-cn", "GODZILLA - S01E02 - The Eartheater",
    "Godzilla-The original animated series/2) THE EARTHEATER.mp4"],
  ["godzilla-tnt-cn", "GODZILLA - S01E03 - Attack of the Stone Creature",
    "Godzilla-The original animated series/3) ATTACK OF THE STONE CREATURES.mp4"],
  ["godzilla-tnt-cn", "GODZILLA - S01E04 - The Megavolt Monster",
    "Godzilla-The original animated series/4) THE MEGAVOLT MONSTER.mp4"],
  ["godzilla-tnt-cn", "GODZILLA - S01E05 - The Seaweed Monster",
    "Godzilla-The original animated series/5) THE SEAWEED MONSTER.mp4"],
  ["godzilla-tnt-cn", "GODZILLA - S01E06 - The Energy Beast",
    "Godzilla-The original animated series/6) THE ENERGY BEAST.mp4"],
  ["godzilla-tnt-cn", "GODZILLA - S01E07 - The Colossus of Atlantis",
    "Godzilla-The original animated series/7) THE COLOSSUS OF ATLANTIS.mp4"],
  ["godzilla-tnt-cn", "GODZILLA - S01E08 - The Horror of Forgotten Island",
    "Godzilla-The original animated series/8) THE HORROR OF FORGOTTEN ISLAND.mp4"],
  ["godzilla-tnt-cn", "GODZILLA - S01E09 - Island of Lost Ships",
    "Godzilla-The original animated series/9) ISLAND OF LOST SHIPS.mp4"],
  ["godzilla-tnt-cn", "GODZILLA - S01E10 - The Magnetic Terror",
    "Godzilla-The original animated series/10) THE MAGNETIC TERROR.mp4"],
  ["godzilla-tnt-cn", "GODZILLA - S01E11 - The Breeder Beast",
    "Godzilla-The original animated series/11) THE BREEDER BEAST.mp4"],
  ["godzilla-tnt-cn", "GODZILLA - S01E12 - The Sub-Zero Terror",
    "Godzilla-The original animated series/12) THE SUB-ZERO TERROR.mp4"],
  ["godzilla-tnt-cn", "GODZILLA - S01E13 - The Time Dragons",
    "Godzilla-The original animated series/13) THE TIME DRAGONS.mp4"],
  ["godzilla-tnt-cn", "GODZILLA - S01E14 - Godzilla The original animated series/14) THE GOLDEN GUARDIANS",
    "Godzilla-The original animated series/14) THE GOLDEN GUARDIANS.mp4"],
  ["godzilla-tnt-cn", "GODZILLA - S01E15 - Godzilla The original animated series/15) CALICO CLONES",
    "Godzilla-The original animated series/15) CALICO CLONES.mp4"],
  ["godzilla-tnt-cn", "GODZILLA - S01E16 - Godzilla The original animated series/16) MICROGODZILLA",
    "Godzilla-The original animated series/16) MICROGODZILLA.mp4"],
  ["godzilla-tnt-cn", "GODZILLA - S01E17 - Godzilla The original animated series/17) GHOST SHIP",
    "Godzilla-The original animated series/17) GHOST SHIP.mp4"],
  ["godzilla-tnt-cn", "GODZILLA - S01E18 - Godzilla The original animated series/18) THE BEAST OF STORM ISLAND",
    "Godzilla-The original animated series/18) THE BEAST OF STORM ISLAND.mp4"],
  ["godzilla-tnt-cn", "GODZILLA - S01E19 - Godzilla The original animated series/19) VALLEY OF THE GIANTS",
    "Godzilla-The original animated series/19) VALLEY OF THE GIANTS.mp4"],
  ["godzilla-tnt-cn", "GODZILLA - S01E20 - Godzilla The original animated series/20) THE CYBORG WHALE",
    "Godzilla-The original animated series/20) THE CYBORG WHALE.mp4"],
  ["godzilla-tnt-cn", "GODZILLA - S01E21 - Godzilla The original animated series/21) THE CITY IN THE CLOUDS",
    "Godzilla-The original animated series/21) THE CITY IN THE CLOUDS.mp4"],
  ["godzilla-tnt-cn", "GODZILLA - S01E22 - Godzilla The original animated series/22) THE MACRO BEASTS",
    "Godzilla-The original animated series/22) THE MACRO-BEASTS.mp4"],
  ["godzilla-tnt-cn", "GODZILLA - S01E23 - Godzilla The original animated series/23) MOONLODE",
    "Godzilla-The original animated series/23) MOONLODE.mp4"],
  ["godzilla-tnt-cn", "GODZILLA - S01E24 - Godzilla The original animated series/24) PACIFIC PERIL",
    "Godzilla-The original animated series/24) PACIFIC PERIL.mp4"],
  ["godzilla-tnt-cn", "GODZILLA - S01E25 - Godzilla The original animated series/25) ISLAND OF DOOM",
    "Godzilla-The original animated series/25) ISLAND OF DOOM.mp4"],
  ["godzilla-tnt-cn", "GODZILLA - S01E26 - Untitled",
    "Godzilla-The original animated series/THE DEADLY ASTEROID.mp4"],
],
  durations: {
  "godzilla-tnt-cn::Godzilla-The original animated series/1) THE FIREBIRD.mp4": 1411,
  "godzilla-tnt-cn::Godzilla-The original animated series/2) THE EARTHEATER.mp4": 1424,
  "godzilla-tnt-cn::Godzilla-The original animated series/3) ATTACK OF THE STONE CREATURES.mp4": 1416,
  "godzilla-tnt-cn::Godzilla-The original animated series/4) THE MEGAVOLT MONSTER.mp4": 1372,
  "godzilla-tnt-cn::Godzilla-The original animated series/5) THE SEAWEED MONSTER.mp4": 1386,
  "godzilla-tnt-cn::Godzilla-The original animated series/6) THE ENERGY BEAST.mp4": 1401,
  "godzilla-tnt-cn::Godzilla-The original animated series/7) THE COLOSSUS OF ATLANTIS.mp4": 1395,
  "godzilla-tnt-cn::Godzilla-The original animated series/8) THE HORROR OF FORGOTTEN ISLAND.mp4": 1394,
  "godzilla-tnt-cn::Godzilla-The original animated series/9) ISLAND OF LOST SHIPS.mp4": 1389,
  "godzilla-tnt-cn::Godzilla-The original animated series/10) THE MAGNETIC TERROR.mp4": 1393,
  "godzilla-tnt-cn::Godzilla-The original animated series/11) THE BREEDER BEAST.mp4": 1418,
  "godzilla-tnt-cn::Godzilla-The original animated series/12) THE SUB-ZERO TERROR.mp4": 1390,
  "godzilla-tnt-cn::Godzilla-The original animated series/13) THE TIME DRAGONS.mp4": 1413,
  "godzilla-tnt-cn::Godzilla-The original animated series/14) THE GOLDEN GUARDIANS.mp4": 1332,
  "godzilla-tnt-cn::Godzilla-The original animated series/15) CALICO CLONES.mp4": 1322,
  "godzilla-tnt-cn::Godzilla-The original animated series/16) MICROGODZILLA.mp4": 1335,
  "godzilla-tnt-cn::Godzilla-The original animated series/17) GHOST SHIP.mp4": 1339,
  "godzilla-tnt-cn::Godzilla-The original animated series/18) THE BEAST OF STORM ISLAND.mp4": 1333,
  "godzilla-tnt-cn::Godzilla-The original animated series/19) VALLEY OF THE GIANTS.mp4": 1330,
  "godzilla-tnt-cn::Godzilla-The original animated series/20) THE CYBORG WHALE.mp4": 1333,
  "godzilla-tnt-cn::Godzilla-The original animated series/21) THE CITY IN THE CLOUDS.mp4": 1321,
  "godzilla-tnt-cn::Godzilla-The original animated series/22) THE MACRO-BEASTS.mp4": 1321,
  "godzilla-tnt-cn::Godzilla-The original animated series/23) MOONLODE.mp4": 1323,
  "godzilla-tnt-cn::Godzilla-The original animated series/24) PACIFIC PERIL.mp4": 1327,
  "godzilla-tnt-cn::Godzilla-The original animated series/25) ISLAND OF DOOM.mp4": 1334,
  "godzilla-tnt-cn::Godzilla-The original animated series/THE DEADLY ASTEROID.mp4": 1251,
},
};
