window.SHOW = {
  id: "TwinPeaks",
  title: "Twin Peaks",
  art: "TwinPeaks.jpg",
  storageProgressKey: "twinpeaks-progress",
  storageSettingsKey: "twinpeaks-settings",
  nestedPaths: true,
  grouping: "season",
  segments: "none",
  episodes: [
  ['season-2-episode-8-drive-with-a-dead-girl', "TWIN PEAKS - S01E00 - Pilot",
    "Twin peaks disk 1/Original Pilot.mp4"],
  ['season-2-episode-8-drive-with-a-dead-girl', "TWIN PEAKS - S01E01 - Traces To Nowhere (2)",
    "Twin Peaks Disk 2/Season 1 Episode 1 - Traces To Nowhere (2).mp4"],
  ['season-2-episode-8-drive-with-a-dead-girl', "TWIN PEAKS - S01E02 - Zen Or The Skill To Catch A Killer",
    "Twin Peaks Disk 2/Season 1 Episode 2 - Zen Or The Skill To Catch A Killer.mp4"],
  ['season-2-episode-8-drive-with-a-dead-girl', "TWIN PEAKS - S01E03 - Rest In Pain",
    "Twin Peaks Disk 2/Season 1 Episode 3 - Rest In Pain.mp4"],
  ['season-2-episode-8-drive-with-a-dead-girl', "TWIN PEAKS - S01E04 - The One-Armed Man",
    "Twin Peaks Disk 2/Season 1 Episode 4 -  The One-Armed Man.mp4"],
  ['season-2-episode-8-drive-with-a-dead-girl', "TWIN PEAKS - S01E05 - Cooper's Dreams 2",
    "Twin Peaks Disk 3/Season 1 Episode 5 - Cooper's Dreams 2.mp4"],
  ['season-2-episode-8-drive-with-a-dead-girl', "TWIN PEAKS - S01E06 - Realization Time",
    "Twin Peaks Disk 3/Season 1 Episode 6 - Realization Time.mp4"],
  ['season-2-episode-8-drive-with-a-dead-girl', "TWIN PEAKS - S01E07 - The Last Evening",
    "Twin Peaks Disk 3/Season 1 Episode 7 - The Last Evening.mp4"],
  ['season-2-episode-8-drive-with-a-dead-girl', "TWIN PEAKS - S02E01 - May The Giant Be With You (2)",
    "Twin Peaks disk 4/Season 2 Episode 1 - May The Giant Be With You (2).mp4"],
  ['season-2-episode-8-drive-with-a-dead-girl', "TWIN PEAKS - S02E02 - Coma",
    "Twin Peaks disk 4/Season 2 Episode 2 - Coma.mp4"],
  ['season-2-episode-8-drive-with-a-dead-girl', "TWIN PEAKS - S02E03 - The Man Behind Glass",
    "Twin Peaks disk 4/Season 2 episode 3 - The Man Behind Glass.mp4"],
  ['season-2-episode-8-drive-with-a-dead-girl', "TWIN PEAKS - S02E04 - Laura's Secret Diary (2)",
    "Twin Peaks Disk 5/Season 2 Episode 4 - Laura's Secret Diary (2).mp4"],
  ['season-2-episode-8-drive-with-a-dead-girl', "TWIN PEAKS - S02E05 - The Orchids Curse",
    "Twin Peaks Disk 5/Season 2 Episode 5 - The Orchids Curse.mp4"],
  ['season-2-episode-8-drive-with-a-dead-girl', "TWIN PEAKS - S02E06 - Demons",
    "Twin Peaks Disk 5/Season 2 Episode 6 - Demons.mp4"],
  ['season-2-episode-8-drive-with-a-dead-girl', "TWIN PEAKS - S02E07 - Lonely Souls",
    "Twin Peaks Disk 5/Season 2 Episode 7 - Lonely Souls.mp4"],
  ['season-2-episode-8-drive-with-a-dead-girl', "TWIN PEAKS - S02E08 - Drive With A Dead Girl (2)",
    "twin peaks disk 6/Season 2 Episode 8 - Drive With A Dead Girl (2).mp4"],
  ['season-2-episode-8-drive-with-a-dead-girl', "TWIN PEAKS - S02E09 - Arbitrary Law",
    "twin peaks disk 6/Season 2 Episode 9 - Arbitrary Law.mp4"],
  ['season-2-episode-8-drive-with-a-dead-girl', "TWIN PEAKS - S02E10 - Dispute Between Brothers",
    "twin peaks disk 6/Season 2 Episode 10 - Dispute Between Brothers.mp4"],
  ['season-2-episode-8-drive-with-a-dead-girl', "TWIN PEAKS - S02E11 - Masked Ball",
    "twin peaks disk 6/Season 2 Episode 11  - Masked Ball.mp4"],
  ['season-2-episode-8-drive-with-a-dead-girl', "TWIN PEAKS - S02E12 - The Black Widow (2)",
    "twin peaks disk 7/Season 2 Episode 12 - The Black Widow (2).mp4"],
  ['season-2-episode-8-drive-with-a-dead-girl', "TWIN PEAKS - S02E13 - Checkmate",
    "twin peaks disk 7/Season 2 Episode 13 - Checkmate.mp4"],
  ['season-2-episode-8-drive-with-a-dead-girl', "TWIN PEAKS - S02E14 - Double Play",
    "twin peaks disk 7/Season 2 Episode 14 - Double Play.mp4"],
  ['season-2-episode-8-drive-with-a-dead-girl', "TWIN PEAKS - S02E15 - Slaves And Masters",
    "twin peaks disk 7/Season 2 Episode 15 - Slaves And Masters.mp4"],
  ['season-2-episode-8-drive-with-a-dead-girl', "TWIN PEAKS - S02E16 - The Condemned Woman (2)",
    "Twin Peaks disk 8/Season 2 Episode 16 - The Condemned Woman (2).mp4"],
  ['season-2-episode-8-drive-with-a-dead-girl', "TWIN PEAKS - S02E17 - Wounds And Scars",
    "Twin Peaks disk 8/Season 2 Episode 17 - Wounds And Scars.mp4"],
  ['season-2-episode-8-drive-with-a-dead-girl', "TWIN PEAKS - S02E18 - On The Wings Of Love",
    "Twin Peaks disk 8/Season 2 Episode 18 - On The Wings Of Love.mp4"],
  ['season-2-episode-8-drive-with-a-dead-girl', "TWIN PEAKS - S02E19 - Variations And Revelations",
    "Twin Peaks disk 8/Season 2 Episode 19 - Variations And Revelations.mp4"],
  ['season-2-episode-8-drive-with-a-dead-girl', "TWIN PEAKS - S02E20 - The Path To The Black House (2)",
    "Twin peaks disk 9/Season 2 Episode 20 - The Path To The Black House (2).mp4"],
  ['season-2-episode-8-drive-with-a-dead-girl', "TWIN PEAKS - S02E21 - Miss Twin Peaks",
    "Twin peaks disk 9/Season 2 Episode 21 Miss Twin Peaks.mp4"],
  ['season-2-episode-8-drive-with-a-dead-girl', "TWIN PEAKS - S02E22 - Beyond Life And Death",
    "Twin peaks disk 9/Season 2 Episode 22 - Beyond Life And Death.mp4"],
],
  durations: {
  "season-2-episode-8-drive-with-a-dead-girl::Twin peaks disk 1/Original Pilot.mp4": 5643,
  "season-2-episode-8-drive-with-a-dead-girl::Twin Peaks Disk 2/Season 1 Episode 1 - Traces To Nowhere (2).mp4": 2787,
  "season-2-episode-8-drive-with-a-dead-girl::Twin Peaks Disk 2/Season 1 Episode 2 - Zen Or The Skill To Catch A Killer.mp4": 2894,
  "season-2-episode-8-drive-with-a-dead-girl::Twin Peaks Disk 2/Season 1 Episode 3 - Rest In Pain.mp4": 2815,
  "season-2-episode-8-drive-with-a-dead-girl::Twin Peaks Disk 2/Season 1 Episode 4 -  The One-Armed Man.mp4": 2817,
  "season-2-episode-8-drive-with-a-dead-girl::Twin Peaks Disk 3/Season 1 Episode 5 - Cooper's Dreams 2.mp4": 2785,
  "season-2-episode-8-drive-with-a-dead-girl::Twin Peaks Disk 3/Season 1 Episode 6 - Realization Time.mp4": 2815,
  "season-2-episode-8-drive-with-a-dead-girl::Twin Peaks Disk 3/Season 1 Episode 7 - The Last Evening.mp4": 2805,
  "season-2-episode-8-drive-with-a-dead-girl::Twin Peaks disk 4/Season 2 Episode 1 - May The Giant Be With You (2).mp4": 5651,
  "season-2-episode-8-drive-with-a-dead-girl::Twin Peaks disk 4/Season 2 Episode 2 - Coma.mp4": 2813,
  "season-2-episode-8-drive-with-a-dead-girl::Twin Peaks disk 4/Season 2 episode 3 - The Man Behind Glass.mp4": 2824,
  "season-2-episode-8-drive-with-a-dead-girl::Twin Peaks Disk 5/Season 2 Episode 4 - Laura's Secret Diary (2).mp4": 2816,
  "season-2-episode-8-drive-with-a-dead-girl::Twin Peaks Disk 5/Season 2 Episode 5 - The Orchids Curse.mp4": 2168,
  "season-2-episode-8-drive-with-a-dead-girl::Twin Peaks Disk 5/Season 2 Episode 6 - Demons.mp4": 774,
  "season-2-episode-8-drive-with-a-dead-girl::Twin Peaks Disk 5/Season 2 Episode 7 - Lonely Souls.mp4": 2845,
  "season-2-episode-8-drive-with-a-dead-girl::twin peaks disk 6/Season 2 Episode 8 - Drive With A Dead Girl (2).mp4": 2838,
  "season-2-episode-8-drive-with-a-dead-girl::twin peaks disk 6/Season 2 Episode 9 - Arbitrary Law.mp4": 2805,
  "season-2-episode-8-drive-with-a-dead-girl::twin peaks disk 6/Season 2 Episode 10 - Dispute Between Brothers.mp4": 2839,
  "season-2-episode-8-drive-with-a-dead-girl::twin peaks disk 6/Season 2 Episode 11  - Masked Ball.mp4": 2841,
  "season-2-episode-8-drive-with-a-dead-girl::twin peaks disk 7/Season 2 Episode 12 - The Black Widow (2).mp4": 2786,
  "season-2-episode-8-drive-with-a-dead-girl::twin peaks disk 7/Season 2 Episode 13 - Checkmate.mp4": 2036,
  "season-2-episode-8-drive-with-a-dead-girl::twin peaks disk 7/Season 2 Episode 14 - Double Play.mp4": 731,
  "season-2-episode-8-drive-with-a-dead-girl::twin peaks disk 7/Season 2 Episode 15 - Slaves And Masters.mp4": 2804,
  "season-2-episode-8-drive-with-a-dead-girl::Twin Peaks disk 8/Season 2 Episode 16 - The Condemned Woman (2).mp4": 2837,
  "season-2-episode-8-drive-with-a-dead-girl::Twin Peaks disk 8/Season 2 Episode 17 - Wounds And Scars.mp4": 2758,
  "season-2-episode-8-drive-with-a-dead-girl::Twin Peaks disk 8/Season 2 Episode 18 - On The Wings Of Love.mp4": 2808,
  "season-2-episode-8-drive-with-a-dead-girl::Twin Peaks disk 8/Season 2 Episode 19 - Variations And Revelations.mp4": 2816,
  "season-2-episode-8-drive-with-a-dead-girl::Twin peaks disk 9/Season 2 Episode 20 - The Path To The Black House (2).mp4": 2806,
  "season-2-episode-8-drive-with-a-dead-girl::Twin peaks disk 9/Season 2 Episode 21 Miss Twin Peaks.mp4": 271,
  "season-2-episode-8-drive-with-a-dead-girl::Twin peaks disk 9/Season 2 Episode 22 - Beyond Life And Death.mp4": 2443,
},
  incompleteEpisodes: ['S02E05', 'S02E06', 'S02E13', 'S02E14', 'S02E21', 'S02E22'],
};
