window.SHOW = {
  id: "CarolineInTheCity",
  title: "Caroline in the City",
  art: "CarolineInTheCity.jpg",
  storageProgressKey: "carolineinthecity-progress",
  storageSettingsKey: "carolineinthecity-settings",
  nestedPaths: true,
  grouping: "season",
  segments: "none",
  episodes: [
  ["caroline-in-the-city", "CAROLINE IN THE CITY - S01E01 - The Pilot",
    "Caroline in the City S1x01.mp4"],
  ["caroline-in-the-city", "CAROLINE IN THE CITY - S01E02 - Caroline and the Mugger",
    "Caroline in the City S1x02.mp4"],
  ["caroline-in-the-city", "CAROLINE IN THE CITY - S01E03 - Caroline and the Gay Art Show",
    "Caroline in the City S1x03.mp4"],
  ["caroline-in-the-city", "CAROLINE IN THE CITY - S01E04 - Caroline and the Bad Back",
    "Caroline in the City S1x04.mp4"],
  ["caroline-in-the-city", "CAROLINE IN THE CITY - S01E05 - Caroline and the ATM",
    "Caroline in the City S1x05.mp4"],
  ["caroline-in-the-city", "CAROLINE IN THE CITY - S01E06 - Caroline and the Folks",
    "Caroline in the City S1x06.mp4"],
  ["caroline-in-the-city", "CAROLINE IN THE CITY - S01E07 - Caroline and the Opera",
    "Caroline in the City S1x07.mp4"],
  ["caroline-in-the-city", "CAROLINE IN THE CITY - S01E08 - Caroline and the Balloon",
    "Caroline in the City S1x08.mp4"],
  ["caroline-in-the-city", "CAROLINE IN THE CITY - S01E09 - Caroline and the Convict",
    "Caroline in the City S1x09.mp4"],
  ["caroline-in-the-city", "CAROLINE IN THE CITY - S01E10 - Caroline and the Christmas Break",
    "Caroline in the City S1x10.mp4"],
  ["caroline-in-the-city", "CAROLINE IN THE CITY - S01E11 - Caroline and the Gift",
    "Caroline in the City S1x11.mp4"],
  ["caroline-in-the-city", "CAROLINE IN THE CITY - S01E12 - Caroline and the Married Man",
    "Caroline in the City S1x12.mp4"],
  ["caroline-in-the-city", "CAROLINE IN THE CITY - S01E13 - Caroline and the Twenty-Eight-Pound Walleye",
    "Caroline in the City S1x13.mp4"],
  ["caroline-in-the-city", "CAROLINE IN THE CITY - S01E14 - Caroline and the Watch",
    "Caroline in the City S1x14.mp4"],
  ["caroline-in-the-city", "CAROLINE IN THE CITY - S01E15 - Caroline and the Bad Date",
    "Caroline in the City S1x15.mp4"],
  ["caroline-in-the-city", "CAROLINE IN THE CITY - S01E16 - Caroline and the Proposal",
    "Caroline in the City S1x16.mp4"],
  ["caroline-in-the-city", "CAROLINE IN THE CITY - S01E17 - Caroline and the Kid",
    "Caroline in the City S1x17.mp4"],
  ["caroline-in-the-city", "CAROLINE IN THE CITY - S01E18 - Caroline and the Ex-Wife",
    "Caroline in the City S1x18.mp4"],
  ["caroline-in-the-city", "CAROLINE IN THE CITY - S01E19 - Caroline and the Movie",
    "Caroline in the City S1x19.mp4"],
  ["caroline-in-the-city", "CAROLINE IN THE CITY - S01E20 - Caroline and the Cereal",
    "Caroline in the City S1x20.mp4"],
  ["caroline-in-the-city", "CAROLINE IN THE CITY - S01E21 - Caroline and Richard's Mom",
    "Caroline in the City S1x21.mp4"],
  ["caroline-in-the-city", "CAROLINE IN THE CITY - S01E22 - Caroline and the Bridesmaids",
    "Caroline in the City S1x22.mp4"],
  ["caroline-in-the-city", "CAROLINE IN THE CITY - S01E23 - Caroline and the Wedding",
    "Caroline in the City S1x23.mp4"],
  ["caroline-in-the-city", "CAROLINE IN THE CITY - S01E24 - Caroline and the Condom",
    "Caroline in the City S1x24.mp4"],
  ["caroline-in-the-city", "CAROLINE IN THE CITY - S02E01 - Caroline and the Younger Man: Part 1",
    "Caroline in the City S2x01.mp4"],
  ["caroline-in-the-city", "CAROLINE IN THE CITY - S02E02 - Caroline and the Letter: Part 2",
    "Caroline in the City S2x02.mp4"],
  ["caroline-in-the-city", "CAROLINE IN THE CITY - S02E03 - Caroline and the Cat Dancer",
    "Caroline in the City S2x03.mp4"],
  ["caroline-in-the-city", "CAROLINE IN THE CITY - S02E04 - Caroline and the Guy Who Gets There Too Soon",
    "Caroline in the City S2x04.mp4"],
  ["caroline-in-the-city", "CAROLINE IN THE CITY - S02E05 - Caroline and the Dreamers",
    "Caroline in the City S2x05.mp4"],
  ["caroline-in-the-city", "CAROLINE IN THE CITY - S02E06 - Caroline and the Nice Jewish Boy",
    "Caroline in the City S2x06.mp4"],
  ["caroline-in-the-city", "CAROLINE IN THE CITY - S02E07 - Caroline and Victor/Victoria",
    "Caroline in the City S2x07.mp4"],
  ["caroline-in-the-city", "CAROLINE IN THE CITY - S02E08 - Caroline and the Comic",
    "Caroline in the City S2x08.mp4"],
  ["caroline-in-the-city", "CAROLINE IN THE CITY - S02E09 - Caroline and the Therapist",
    "Caroline in the City S2x09.mp4"],
  ["caroline-in-the-city", "CAROLINE IN THE CITY - S02E10 - Caroline and the Red Sauce",
    "Caroline in the City S2x10.mp4"],
  ["caroline-in-the-city", "CAROLINE IN THE CITY - S02E11 - Caroline and the Freight King",
    "Caroline in the City S2x11.mp4"],
  ["caroline-in-the-city", "CAROLINE IN THE CITY - S02E12 - Caroline and the Perfect Record",
    "Caroline in the City S2x12.mp4"],
  ["caroline-in-the-city", "CAROLINE IN THE CITY - S02E13 - Caroline and the Singer",
    "Caroline in the City S2x13.mp4"],
  ["caroline-in-the-city", "CAROLINE IN THE CITY - S02E14 - Caroline and the Kept Man",
    "Caroline in the City S2x14.mp4"],
  ["caroline-in-the-city", "CAROLINE IN THE CITY - S02E15 - Caroline and the Long Shot",
    "Caroline in the City S2x15.mp4"],
  ["caroline-in-the-city", "CAROLINE IN THE CITY - S02E16 - Caroline and the Dearly Departed",
    "Caroline in the City S2x16.mp4"],
  ["caroline-in-the-city", "CAROLINE IN THE CITY - S02E17 - Caroline and the Getaway",
    "Caroline in the City S2x17.mp4"],
  ["caroline-in-the-city", "CAROLINE IN THE CITY - S02E18 - Caroline and the Monkeys",
    "Caroline in the City S2x18.mp4"],
  ["caroline-in-the-city", "CAROLINE IN THE CITY - S02E19 - Caroline and the Buyer",
    "Caroline in the City S2x19.mp4"],
  ["caroline-in-the-city", "CAROLINE IN THE CITY - S02E20 - Caroline and the New Neighbor",
    "Caroline in the City S2x20.mp4"],
  ["caroline-in-the-city", "CAROLINE IN THE CITY - S02E21 - Caroline and the Critics",
    "Caroline in the City S2x21.mp4"],
  ["caroline-in-the-city", "CAROLINE IN THE CITY - S02E22 - Caroline and the Ombudsman",
    "Caroline in the City S2x22.mp4"],
  ["caroline-in-the-city", "CAROLINE IN THE CITY - S02E23 - Caroline and the Bad Trip: Part 1",
    "Caroline in the City S2x23.mp4"],
  ["caroline-in-the-city", "CAROLINE IN THE CITY - S02E24 - Caroline and Richard & Julia: Part 2",
    "Caroline in the City S2x24.mp4"],
  ["caroline-in-the-city", "CAROLINE IN THE CITY - S02E25 - Caroline and the Wayward Husband: Part 3",
    "Caroline in the City S2x25.mp4"],
  ["caroline-in-the-city", "CAROLINE IN THE CITY - S03E01 - Caroline and the Reception",
    "Caroline in the City S3x01.mp4"],
  ["caroline-in-the-city", "CAROLINE IN THE CITY - S03E02 - Caroline and the Kink",
    "Caroline in the City S3x02.mp4"],
  ["caroline-in-the-city", "CAROLINE IN THE CITY - S03E03 - Caroline and the Novelist",
    "Caroline in the City S3x03.mp4"],
  ["caroline-in-the-city", "CAROLINE IN THE CITY - S03E04 - Caroline and the Free Cable",
    "Caroline in the City S3x04.mp4"],
  ["caroline-in-the-city", "CAROLINE IN THE CITY - S03E05 - Caroline and the Blind Date",
    "Caroline in the City S3x05.mp4"],
  ["caroline-in-the-city", "CAROLINE IN THE CITY - S03E06 - Caroline and the Egg",
    "Caroline in the City S3x06.mp4"],
  ["caroline-in-the-city", "CAROLINE IN THE CITY - S03E07 - Caroline and the Desperate Cat",
    "Caroline in the City S3x07.mp4"],
  ["caroline-in-the-city", "CAROLINE IN THE CITY - S03E08 - Caroline and the Cold Sesame Noodles",
    "Caroline in the City S3x08.mp4"],
  ["caroline-in-the-city", "CAROLINE IN THE CITY - S03E09 - Caroline and the Bitter Beast",
    "Caroline in the City S3x09.mp4"],
  ["caroline-in-the-city", "CAROLINE IN THE CITY - S03E10 - Caroline and the Councilman",
    "Caroline in the City S3x10.mp4"],
  ["caroline-in-the-city", "CAROLINE IN THE CITY - S03E11 - Caroline and the Used Car Salesman",
    "Caroline in the City S3x11.mp4"],
  ["caroline-in-the-city", "CAROLINE IN THE CITY - S03E12 - Caroline and the Decanter",
    "Caroline in the City S3x12.mp4"],
  ["caroline-in-the-city", "CAROLINE IN THE CITY - S03E13 - Caroline and the Love That Dares Not Speak its Name",
    "Caroline in the City S3x13.mp4"],
  ["caroline-in-the-city", "CAROLINE IN THE CITY - S03E14 - Caroline and the Quiz Show",
    "Caroline in the City S3x14.mp4"],
  ["caroline-in-the-city", "CAROLINE IN THE CITY - S03E15 - Caroline and the Reluctant Father",
    "Caroline in the City S3x15.mp4"],
  ["caroline-in-the-city", "CAROLINE IN THE CITY - S03E16 - Caroline and the Outer Limits",
    "Caroline in the City S3x16.mp4"],
  ["caroline-in-the-city", "CAROLINE IN THE CITY - S03E17 - Caroline and the Toothbrush",
    "Caroline in the City S3x17.mp4"],
  ["caroline-in-the-city", "CAROLINE IN THE CITY - S03E18 - Caroline and the Cabbie",
    "Caroline in the City S3x18.mp4"],
  ["caroline-in-the-city", "CAROLINE IN THE CITY - S03E19 - Caroline and the Visit from Mom",
    "Caroline in the City S3x19.mp4"],
  ["caroline-in-the-city", "CAROLINE IN THE CITY - S03E20 - Caroline and the Little White Lies",
    "Caroline in the City S3x20.mp4"],
  ["caroline-in-the-city", "CAROLINE IN THE CITY - S03E21 - Caroline and the Killer Dad",
    "Caroline in the City S3x21.mp4"],
  ["caroline-in-the-city", "CAROLINE IN THE CITY - S03E22 - Caroline and the Sandwich",
    "Caroline in the City S3x22.mp4"],
  ["caroline-in-the-city", "CAROLINE IN THE CITY - S03E23 - Caroline and the Marriage Counselor: Part 1",
    "Caroline in the City S3x23.mp4"],
  ["caroline-in-the-city", "CAROLINE IN THE CITY - S03E24 - Caroline and the Marriage Counselor: Part 2",
    "Caroline in the City S3x24.mp4"],
  ["caroline-in-the-city", "CAROLINE IN THE CITY - S03E25 - Caroline and the Secret Bullfighter: Part 1",
    "Caroline in the City S3x25.mp4"],
  ["caroline-in-the-city", "CAROLINE IN THE CITY - S03E26 - Caroline and the Secret Bullfighter: Part 2",
    "Caroline in the City S3x26.mp4"],
  ["caroline-in-the-city", "CAROLINE IN THE CITY - S04E01 - Caroline and the Guys in the Bathroom",
    "Caroline in the City S4x01.mp4"],
  ["caroline-in-the-city", "CAROLINE IN THE CITY - S04E02 - Caroline and the Office",
    "Caroline in the City S4x02.mp4"],
  ["caroline-in-the-city", "CAROLINE IN THE CITY - S04E03 - Caroline and the Rotten Plum",
    "Caroline in the City S4x03.mp4"],
  ["caroline-in-the-city", "CAROLINE IN THE CITY - S04E04 - Caroline and the Drycleaner",
    "Caroline in the City S4x04.mp4"],
  ["caroline-in-the-city", "CAROLINE IN THE CITY - S04E05 - Caroline and the First Date",
    "Caroline in the City S4x05.mp4"],
  ["caroline-in-the-city", "CAROLINE IN THE CITY - S04E06 - Caroline and the Paper Chase",
    "Caroline in the City S4x06.mp4"],
  ["caroline-in-the-city", "CAROLINE IN THE CITY - S04E07 - Caroline and the Big Night",
    "Caroline in the City S4x07.mp4"],
  ["caroline-in-the-city", "CAROLINE IN THE CITY - S04E08 - Caroline and the Diva",
    "Caroline in the City S4x08.mp4"],
  ["caroline-in-the-city", "CAROLINE IN THE CITY - S04E09 - Caroline and the Booby Trap",
    "Caroline in the City S4x09.mp4"],
  ["caroline-in-the-city", "CAROLINE IN THE CITY - S04E10 - Caroline and the Bar Mitzvah",
    "Caroline in the City S4x10.mp4"],
  ["caroline-in-the-city", "CAROLINE IN THE CITY - S04E11 - Caroline and the Fright Before Christmas",
    "Caroline in the City S4x11.mp4"],
  ["caroline-in-the-city", "CAROLINE IN THE CITY - S04E12 - Caroline and the Big Bad Bed",
    "Caroline in the City S4x12.mp4"],
  ["caroline-in-the-city", "CAROLINE IN THE CITY - S04E13 - Caroline and the Horny Kid",
    "Caroline in the City S4x13.mp4"],
  ["caroline-in-the-city", "CAROLINE IN THE CITY - S04E14 - Caroline and the Firing Squad",
    "Caroline in the City S4x14.mp4"],
  ["caroline-in-the-city", "CAROLINE IN THE CITY - S04E15 - Caroline and Joanie and the Stick",
    "Caroline in the City S4x15.mp4"],
  ["caroline-in-the-city", "CAROLINE IN THE CITY - S04E16 - Caroline and the Ancestral Home",
    "Caroline in the City S4x16.mp4"],
  ["caroline-in-the-city", "CAROLINE IN THE CITY - S04E17 - Caroline and the 2000th Strip",
    "Caroline in the City S4x17.mp4"],
  ["caroline-in-the-city", "CAROLINE IN THE CITY - S04E18 - Caroline and the Sudsy Guy",
    "Caroline in the City S4x18.mp4"],
  ["caroline-in-the-city", "CAROLINE IN THE CITY - S04E19 - Caroline and the Return of the Sudsy Guy",
    "Caroline in the City S4x19.mp4"],
  ["caroline-in-the-city", "CAROLINE IN THE CITY - S04E20 - Caroline and the Ultimatum",
    "Caroline in the City S4x20.mp4"],
  ["caroline-in-the-city", "CAROLINE IN THE CITY - S04E21 - Caroline and El Niño",
    "Caroline in the City S4x21.mp4"],
  ["caroline-in-the-city", "CAROLINE IN THE CITY - S04E22 - Caroline and the Big Move",
    "Caroline in the City S4x22.mp4"],
],
  durations: {
  "caroline-in-the-city::Caroline in the City S1x01.mp4": 1365,
  "caroline-in-the-city::Caroline in the City S1x02.mp4": 1281,
  "caroline-in-the-city::Caroline in the City S1x03.mp4": 1289,
  "caroline-in-the-city::Caroline in the City S1x04.mp4": 1254,
  "caroline-in-the-city::Caroline in the City S1x05.mp4": 1289,
  "caroline-in-the-city::Caroline in the City S1x06.mp4": 1287,
  "caroline-in-the-city::Caroline in the City S1x07.mp4": 1278,
  "caroline-in-the-city::Caroline in the City S1x08.mp4": 1236,
  "caroline-in-the-city::Caroline in the City S1x09.mp4": 1224,
  "caroline-in-the-city::Caroline in the City S1x10.mp4": 1283,
  "caroline-in-the-city::Caroline in the City S1x11.mp4": 1284,
  "caroline-in-the-city::Caroline in the City S1x12.mp4": 1253,
  "caroline-in-the-city::Caroline in the City S1x13.mp4": 1278,
  "caroline-in-the-city::Caroline in the City S1x14.mp4": 1276,
  "caroline-in-the-city::Caroline in the City S1x15.mp4": 1284,
  "caroline-in-the-city::Caroline in the City S1x16.mp4": 1279,
  "caroline-in-the-city::Caroline in the City S1x17.mp4": 1277,
  "caroline-in-the-city::Caroline in the City S1x18.mp4": 1293,
  "caroline-in-the-city::Caroline in the City S1x19.mp4": 1258,
  "caroline-in-the-city::Caroline in the City S1x20.mp4": 1275,
  "caroline-in-the-city::Caroline in the City S1x21.mp4": 1285,
  "caroline-in-the-city::Caroline in the City S1x22.mp4": 1290,
  "caroline-in-the-city::Caroline in the City S1x23.mp4": 1292,
  "caroline-in-the-city::Caroline in the City S1x24.mp4": 1233,
  "caroline-in-the-city::Caroline in the City S2x01.mp4": 1314,
  "caroline-in-the-city::Caroline in the City S2x02.mp4": 1294,
  "caroline-in-the-city::Caroline in the City S2x03.mp4": 1276,
  "caroline-in-the-city::Caroline in the City S2x04.mp4": 1304,
  "caroline-in-the-city::Caroline in the City S2x05.mp4": 1303,
  "caroline-in-the-city::Caroline in the City S2x06.mp4": 1288,
  "caroline-in-the-city::Caroline in the City S2x07.mp4": 1295,
  "caroline-in-the-city::Caroline in the City S2x08.mp4": 1274,
  "caroline-in-the-city::Caroline in the City S2x09.mp4": 1300,
  "caroline-in-the-city::Caroline in the City S2x10.mp4": 1294,
  "caroline-in-the-city::Caroline in the City S2x11.mp4": 1304,
  "caroline-in-the-city::Caroline in the City S2x12.mp4": 1300,
  "caroline-in-the-city::Caroline in the City S2x13.mp4": 1284,
  "caroline-in-the-city::Caroline in the City S2x14.mp4": 1306,
  "caroline-in-the-city::Caroline in the City S2x15.mp4": 1210,
  "caroline-in-the-city::Caroline in the City S2x16.mp4": 1247,
  "caroline-in-the-city::Caroline in the City S2x17.mp4": 1266,
  "caroline-in-the-city::Caroline in the City S2x18.mp4": 1271,
  "caroline-in-the-city::Caroline in the City S2x19.mp4": 1228,
  "caroline-in-the-city::Caroline in the City S2x20.mp4": 1269,
  "caroline-in-the-city::Caroline in the City S2x21.mp4": 1283,
  "caroline-in-the-city::Caroline in the City S2x22.mp4": 1287,
  "caroline-in-the-city::Caroline in the City S2x23.mp4": 1288,
  "caroline-in-the-city::Caroline in the City S2x24.mp4": 1287,
  "caroline-in-the-city::Caroline in the City S2x25.mp4": 1348,
  "caroline-in-the-city::Caroline in the City S3x01.mp4": 1266,
  "caroline-in-the-city::Caroline in the City S3x02.mp4": 1286,
  "caroline-in-the-city::Caroline in the City S3x03.mp4": 1297,
  "caroline-in-the-city::Caroline in the City S3x04.mp4": 1232,
  "caroline-in-the-city::Caroline in the City S3x05.mp4": 1288,
  "caroline-in-the-city::Caroline in the City S3x06.mp4": 1288,
  "caroline-in-the-city::Caroline in the City S3x07.mp4": 1289,
  "caroline-in-the-city::Caroline in the City S3x08.mp4": 1264,
  "caroline-in-the-city::Caroline in the City S3x09.mp4": 1249,
  "caroline-in-the-city::Caroline in the City S3x10.mp4": 1288,
  "caroline-in-the-city::Caroline in the City S3x11.mp4": 1269,
  "caroline-in-the-city::Caroline in the City S3x12.mp4": 1284,
  "caroline-in-the-city::Caroline in the City S3x13.mp4": 1279,
  "caroline-in-the-city::Caroline in the City S3x14.mp4": 1255,
  "caroline-in-the-city::Caroline in the City S3x15.mp4": 1251,
  "caroline-in-the-city::Caroline in the City S3x16.mp4": 1262,
  "caroline-in-the-city::Caroline in the City S3x17.mp4": 1264,
  "caroline-in-the-city::Caroline in the City S3x18.mp4": 1277,
  "caroline-in-the-city::Caroline in the City S3x19.mp4": 1288,
  "caroline-in-the-city::Caroline in the City S3x20.mp4": 1288,
  "caroline-in-the-city::Caroline in the City S3x21.mp4": 1285,
  "caroline-in-the-city::Caroline in the City S3x22.mp4": 1259,
  "caroline-in-the-city::Caroline in the City S3x23.mp4": 1208,
  "caroline-in-the-city::Caroline in the City S3x24.mp4": 1288,
  "caroline-in-the-city::Caroline in the City S3x25.mp4": 1282,
  "caroline-in-the-city::Caroline in the City S3x26.mp4": 1288,
  "caroline-in-the-city::Caroline in the City S4x01.mp4": 1260,
  "caroline-in-the-city::Caroline in the City S4x02.mp4": 1273,
  "caroline-in-the-city::Caroline in the City S4x03.mp4": 1245,
  "caroline-in-the-city::Caroline in the City S4x04.mp4": 1259,
  "caroline-in-the-city::Caroline in the City S4x05.mp4": 1273,
  "caroline-in-the-city::Caroline in the City S4x06.mp4": 1244,
  "caroline-in-the-city::Caroline in the City S4x07.mp4": 1259,
  "caroline-in-the-city::Caroline in the City S4x08.mp4": 1275,
  "caroline-in-the-city::Caroline in the City S4x09.mp4": 1259,
  "caroline-in-the-city::Caroline in the City S4x10.mp4": 1274,
  "caroline-in-the-city::Caroline in the City S4x11.mp4": 1269,
  "caroline-in-the-city::Caroline in the City S4x12.mp4": 1273,
  "caroline-in-the-city::Caroline in the City S4x13.mp4": 1274,
  "caroline-in-the-city::Caroline in the City S4x14.mp4": 1274,
  "caroline-in-the-city::Caroline in the City S4x15.mp4": 1269,
  "caroline-in-the-city::Caroline in the City S4x16.mp4": 1245,
  "caroline-in-the-city::Caroline in the City S4x17.mp4": 1274,
  "caroline-in-the-city::Caroline in the City S4x18.mp4": 1231,
  "caroline-in-the-city::Caroline in the City S4x19.mp4": 1269,
  "caroline-in-the-city::Caroline in the City S4x20.mp4": 1274,
  "caroline-in-the-city::Caroline in the City S4x21.mp4": 1231,
  "caroline-in-the-city::Caroline in the City S4x22.mp4": 1274,
},
};
