window.SHOW = {
  id: "DuckTalesSeriesWorkinProgress",
  title: "DuckTales Series Work in Progress",
  art: "DuckTalesSeriesWorkinProgress.jpg",
  storageProgressKey: "ducktalesseriesworkinprogress-progress",
  storageSettingsKey: "ducktalesseriesworkinprogress-settings",
  nestedPaths: true,
  grouping: "season",
  segments: "none",
  episodes: [
  ["Ducktales-Complete-Series", "DUCKTALES SERIES WORK IN PROGRESS - S01E01 - DuckTales Dont give up the ship",
    "Season 1/DuckTales S01E01 Dont give up the ship.mp4"],
  ["Ducktales-Complete-Series", "DUCKTALES SERIES WORK IN PROGRESS - S01E02 - DuckTales Wronguay in Ronguay",
    "Season 1/DuckTales S01E02 Wronguay in Ronguay.mp4"],
  ["Ducktales-Complete-Series", "DUCKTALES SERIES WORK IN PROGRESS - S01E03 - DuckTales Three Ducks of the Condor",
    "Season 1/DuckTales S01E03 Three Ducks of the Condor.mp4"],
  ["Ducktales-Complete-Series", "DUCKTALES SERIES WORK IN PROGRESS - S01E04 - DuckTales Cold Duck",
    "Season 1/DuckTales S01E04 Cold Duck.mp4"],
  ["Ducktales-Complete-Series", "DUCKTALES SERIES WORK IN PROGRESS - S01E05 - DuckTales Too Much of a Gold Thing",
    "Season 1/DuckTales S01E05 Too Much of a Gold Thing.mp4"],
  ["Ducktales-Complete-Series", "DUCKTALES SERIES WORK IN PROGRESS - S01E06 - DuckTales Send in the Clones",
    "Season 1/DuckTales S01E06 Send in the Clones.mp4"],
  ["Ducktales-Complete-Series", "DUCKTALES SERIES WORK IN PROGRESS - S01E07 - DuckTales Sphinx for the Memories",
    "Season 1/DuckTales S01E07 Sphinx for the Memories.mp4"],
  ["Ducktales-Complete-Series", "DUCKTALES SERIES WORK IN PROGRESS - S01E08 - DuckTales No Duck Has Gone Before",
    "Season 1/DuckTales S01E08 No Duck Has Gone Before.mp4"],
  ["Ducktales-Complete-Series", "DUCKTALES SERIES WORK IN PROGRESS - S01E09 - DuckTales Armstong",
    "Season 1/DuckTales S01E09 Armstong.mp4"],
  ["Ducktales-Complete-Series", "DUCKTALES SERIES WORK IN PROGRESS - S01E10 - DuckTales Robot Robbers",
    "Season 1/DuckTales S01E10 Robot Robbers.mp4"],
  ["Ducktales-Complete-Series", "DUCKTALES SERIES WORK IN PROGRESS - S01E11 - DuckTales Magica s Shadow War",
    "Season 1/DuckTales S01E11 Magica_s Shadow War.mp4"],
  ["Ducktales-Complete-Series", "DUCKTALES SERIES WORK IN PROGRESS - S01E12 - DuckTales Master of Dijinni",
    "Season 1/DuckTales S01E12 Master of Dijinni.mp4"],
  ["Ducktales-Complete-Series", "DUCKTALES SERIES WORK IN PROGRESS - S01E13 - DuckTales Hotel Strangeduck",
    "Season 1/DuckTales S01E13 Hotel Strangeduck.mp4"],
  ["Ducktales-Complete-Series", "DUCKTALES SERIES WORK IN PROGRESS - S01E14 - DuckTales Lost Crown of Genghis Khan",
    "Season 1/DuckTales S01E14 Lost Crown of Genghis Khan.mp4"],
  ["Ducktales-Complete-Series", "DUCKTALES SERIES WORK IN PROGRESS - S01E15 - DuckTales Duckman Of Aquatrz",
    "Season 1/DuckTales S01E15 Duckman Of Aquatrz.mp4"],
  ["Ducktales-Complete-Series", "DUCKTALES SERIES WORK IN PROGRESS - S01E16 - DuckTales The Money Vanishes",
    "Season 1/DuckTales S01E16 The Money Vanishes.mp4"],
  ["Ducktales-Complete-Series", "DUCKTALES SERIES WORK IN PROGRESS - S01E17 - DuckTales Sir Gyro de Gearloose",
    "Season 1/DuckTales S01E17 Sir Gyro de Gearloose.mp4"],
  ["Ducktales-Complete-Series", "DUCKTALES SERIES WORK IN PROGRESS - S01E18 - DuckTales Dinosaur Ducks",
    "Season 1/DuckTales S01E18 Dinosaur Ducks.mp4"],
  ["Ducktales-Complete-Series", "DUCKTALES SERIES WORK IN PROGRESS - S01E19 - DuckTales Hero For Hire",
    "Season 1/DuckTales S01E19 Hero For Hire.mp4"],
  ["Ducktales-Complete-Series", "DUCKTALES SERIES WORK IN PROGRESS - S01E20 - DuckTales Superdoo",
    "Season 1/DuckTales S01E20 Superdoo!.mp4"],
  ["Ducktales-Complete-Series", "DUCKTALES SERIES WORK IN PROGRESS - S01E21 - DuckTales Maid of the Myth DuckTales",
    "Season 1/DuckTales Season 1 Episode 21 Maid of the Myth - DuckTales 1987.mp4"],
  ["Ducktales-Complete-Series", "DUCKTALES SERIES WORK IN PROGRESS - S01E22 - DuckTales Down & Out in Duckburg DuckTales",
    "Season 1/DuckTales Season 1 Episode 22 Down & Out in Duckburg - DuckTales 1987.mp4"],
  ["Ducktales-Complete-Series", "DUCKTALES SERIES WORK IN PROGRESS - S01E23 - DuckTales Much Ado About Scrooge DuckTales",
    "Season 1/DuckTales Season 1 Episode 23 Much Ado About Scrooge - DuckTales 1987.mp4"],
  ["Ducktales-Complete-Series", "DUCKTALES SERIES WORK IN PROGRESS - S01E24 - DuckTales Top Duck DuckTales",
    "Season 1/DuckTales Season 1 Episode 24 Top Duck - DuckTales 1987.mp4"],
  ["Ducktales-Complete-Series", "DUCKTALES SERIES WORK IN PROGRESS - S01E25 - DuckTales Pearl of Wisdom DuckTales",
    "Season 1/DuckTales Season 1 Episode 25 Pearl of Wisdom - DuckTales 1987.mp4"],
  ["Ducktales-Complete-Series", "DUCKTALES SERIES WORK IN PROGRESS - S01E26 - DuckTales The Curse of Castle McDuck DuckTales",
    "Season 1/DuckTales Season 1 Episode 26 The Curse of Castle McDuck - DuckTales 1987.mp4"],
  ["Ducktales-Complete-Series", "DUCKTALES SERIES WORK IN PROGRESS - S01E27 - DuckTales Launchpad’s Civil War DuckTales",
    "Season 1/DuckTales Season 1 Episode 27 Launchpad’s Civil War - DuckTales 1987.mp4"],
  ["Ducktales-Complete-Series", "DUCKTALES SERIES WORK IN PROGRESS - S01E28 - DuckTales Sweet Duck of Youth DuckTales",
    "Season 1/DuckTales Season 1 Episode 28 Sweet Duck of Youth - DuckTales 1987.mp4"],
  ["Ducktales-Complete-Series", "DUCKTALES SERIES WORK IN PROGRESS - S01E29 - DuckTales Earth Quack DuckTales",
    "Season 1/DuckTales Season 1 Episode 29 Earth Quack - DuckTales 1987.mp4"],
  ["Ducktales-Complete-Series", "DUCKTALES SERIES WORK IN PROGRESS - S01E30 - DuckTales Home Sweet Homer DuckTales",
    "Season 1/DuckTales Season 1 Episode 30 Home Sweet Homer - DuckTales 1987.mp4"],
  ["Ducktales-Complete-Series", "DUCKTALES SERIES WORK IN PROGRESS - S01E31 - DuckTales Bermuda Triangle Tangle DuckTales",
    "Season 1/DuckTales Season 1 Episode 31 Bermuda Triangle Tangle - DuckTales 1987.mp4"],
  ["Ducktales-Complete-Series", "DUCKTALES SERIES WORK IN PROGRESS - S01E33 - DuckTales Back to the Klondike DuckTales",
    "Season 1/DuckTales Season 1 Episode 33 Back to the Klondike - DuckTales 1987.mp4"],
  ["Ducktales-Complete-Series", "DUCKTALES SERIES WORK IN PROGRESS - S01E34 - DuckTales Horse Scents DuckTales",
    "Season 1/DuckTales Season 1 Episode 34 Horse Scents - DuckTales 1987.mp4"],
  ["Ducktales-Complete-Series", "DUCKTALES SERIES WORK IN PROGRESS - S01E35 - DuckTales Scrooge’s Pet DuckTales",
    "Season 1/DuckTales Season 1 Episode 35 Scrooge’s Pet - DuckTales 1987.mp4"],
  ["Ducktales-Complete-Series", "DUCKTALES SERIES WORK IN PROGRESS - S01E36 - DuckTales Catch as Cash Can A Drain on the Economy DuckTales",
    "Season 1/DuckTales Season 1 Episode 36 Catch as Cash Can- A Drain on the Economy - DuckTales 1987.mp4"],
  ["Ducktales-Complete-Series", "DUCKTALES SERIES WORK IN PROGRESS - S01E37 - DuckTales Catch as Cash Can A Whale of a Bad Time DuckTales",
    "Season 1/DuckTales Season 1 Episode 37 Catch as Cash Can- A Whale of a Bad Time - DuckTales 1987.mp4"],
  ["Ducktales-Complete-Series", "DUCKTALES SERIES WORK IN PROGRESS - S01E38 - DuckTales Catch as Cash Can Aqua Ducks DuckTales",
    "Season 1/DuckTales Season 1 Episode 38 Catch as Cash Can- Aqua Ducks - DuckTales 1987.mp4"],
  ["Ducktales-Complete-Series", "DUCKTALES SERIES WORK IN PROGRESS - S01E39 - DuckTales Catch as Cash Can Working for Scales DuckTales",
    "Season 1/DuckTales Season 1 Episode 39 Catch as Cash Can- Working for Scales - DuckTales 1987.mp4"],
  ["Ducktales-Complete-Series", "DUCKTALES SERIES WORK IN PROGRESS - S01E40 - DuckTales Merit Time Adventure DuckTales",
    "Season 1/DuckTales Season 1 Episode 40 Merit-Time Adventure - DuckTales 1987.mp4"],
  ["Ducktales-Complete-Series", "DUCKTALES SERIES WORK IN PROGRESS - S01E41 - DuckTales The Golden Fleecing DuckTales",
    "Season 1/DuckTales Season 1 Episode 41 The Golden Fleecing - DuckTales 1987.mp4"],
  ["Ducktales-Complete-Series", "DUCKTALES SERIES WORK IN PROGRESS - S01E42 - DuckTales Ducks of the West DuckTales",
    "Season 1/DuckTales Season 1 Episode 42 Ducks of the West - DuckTales 1987.mp4"],
  ["Ducktales-Complete-Series", "DUCKTALES SERIES WORK IN PROGRESS - S01E43 - DuckTales Time Teasers DuckTales",
    "Season 1/DuckTales Season 1 Episode 43 Time Teasers - DuckTales 1987.mp4"],
  ["Ducktales-Complete-Series", "DUCKTALES SERIES WORK IN PROGRESS - S01E44 - DuckTales Back Out in the Outback DuckTales",
    "Season 1/DuckTales Season 1 Episode 44 Back Out in the Outback - DuckTales 1987.mp4"],
  ["Ducktales-Complete-Series", "DUCKTALES SERIES WORK IN PROGRESS - S01E45 - DuckTales Raiders of the Lost Harp DuckTales",
    "Season 1/DuckTales Season 1 Episode 45 Raiders of the Lost Harp - DuckTales 1987.mp4"],
  ["Ducktales-Complete-Series", "DUCKTALES SERIES WORK IN PROGRESS - S01E46 - DuckTales The Right Duck DuckTales",
    "Season 1/DuckTales Season 1 Episode 46 The Right Duck - DuckTales 1987.mp4"],
  ["Ducktales-Complete-Series", "DUCKTALES SERIES WORK IN PROGRESS - S01E47 - DuckTales Scroogerello DuckTales",
    "Season 1/DuckTales Season 1 Episode 47 Scroogerello - DuckTales 1987.mp4"],
  ["Ducktales-Complete-Series", "DUCKTALES SERIES WORK IN PROGRESS - S01E48 - DuckTales Double O Duck DuckTales",
    "Season 1/DuckTales Season 1 Episode 48 Double-O-Duck - DuckTales 1987.mp4"],
  ["Ducktales-Complete-Series", "DUCKTALES SERIES WORK IN PROGRESS - S01E49 - DuckTales Luck o’ the Ducks DuckTales",
    "Season 1/DuckTales Season 1 Episode 49 Luck o’ the Ducks - DuckTales 1987.mp4"],
  ["Ducktales-Complete-Series", "DUCKTALES SERIES WORK IN PROGRESS - S01E50 - DuckTales Duckworth’s Revolt DuckTales",
    "Season 1/DuckTales Season 1 Episode 50 Duckworth’s Revolt - DuckTales 1987.mp4"],
  ["Ducktales-Complete-Series", "DUCKTALES SERIES WORK IN PROGRESS - S01E51 - DuckTales Magica’s Magic Mirror Take Me Out of the Ballgame DuckTales",
    "Season 1/DuckTales Season 1 Episode 51 Magica’s Magic Mirror - Take Me Out of the Ballgame - DuckTales 1987.mp4"],
  ["Ducktales-Complete-Series", "DUCKTALES SERIES WORK IN PROGRESS - S01E52 - DuckTales Duck to the Future DuckTales",
    "Season 1/DuckTales Season 1 Episode 52 Duck to the Future - DuckTales 1987.mp4"],
  ["Ducktales-Complete-Series", "DUCKTALES SERIES WORK IN PROGRESS - S01E53 - DuckTales Jungle Duck DuckTales",
    "Season 1/DuckTales Season 1 Episode 53 Jungle Duck - DuckTales 1987.mp4"],
  ["Ducktales-Complete-Series", "DUCKTALES SERIES WORK IN PROGRESS - S01E54 - DuckTales Launchpad’s First Crash DuckTales",
    "Season 1/DuckTales Season 1 Episode 54 Launchpad’s First Crash - DuckTales 1987.mp4"],
  ["Ducktales-Complete-Series", "DUCKTALES SERIES WORK IN PROGRESS - S01E55 - DuckTales Dime Enough for Luck DuckTales",
    "Season 1/DuckTales Season 1 Episode 55 Dime Enough for Luck - DuckTales 1987.mp4"],
  ["Ducktales-Complete-Series", "DUCKTALES SERIES WORK IN PROGRESS - S01E56 - DuckTales The Duck in the Iron Mask DuckTales",
    "Season 1/DuckTales Season 1 Episode 56 The Duck in the Iron Mask - DuckTales 1987.mp4"],
  ["Ducktales-Complete-Series", "DUCKTALES SERIES WORK IN PROGRESS - S01E57 - DuckTales The Uncrashable Hindentanic DuckTales",
    "Season 1/DuckTales Season 1 Episode 57 The Uncrashable Hindentanic - DuckTales 1987.mp4"],
  ["Ducktales-Complete-Series", "DUCKTALES SERIES WORK IN PROGRESS - S01E58 - DuckTales The Status Seekers DuckTales",
    "Season 1/DuckTales Season 1 Episode 58 The Status Seekers - DuckTales 1987.mp4"],
  ["Ducktales-Complete-Series", "DUCKTALES SERIES WORK IN PROGRESS - S01E59 - DuckTales Nothing to Fear DuckTales",
    "Season 1/DuckTales Season 1 Episode 59 Nothing to Fear - DuckTales 1987.mp4"],
  ["Ducktales-Complete-Series", "DUCKTALES SERIES WORK IN PROGRESS - S01E60 - DuckTales Dr. Jekyll & Mr. McDuck DuckTales",
    "Season 1/DuckTales Season 1 Episode 60 Dr. Jekyll & Mr. McDuck - DuckTales 1987.mp4"],
  ["Ducktales-Complete-Series", "DUCKTALES SERIES WORK IN PROGRESS - S01E61 - DuckTales Once Upon a Dime DuckTales",
    "Season 1/DuckTales Season 1 Episode 61 Once Upon a Dime - DuckTales 1987.mp4"],
  ["Ducktales-Complete-Series", "DUCKTALES SERIES WORK IN PROGRESS - S01E62 - DuckTales Spies in Their Eyes DuckTales",
    "Season 1/DuckTales Season 1 Episode 62 Spies in Their Eyes - DuckTales 1987.mp4"],
  ["Ducktales-Complete-Series", "DUCKTALES SERIES WORK IN PROGRESS - S01E63 - DuckTales All Ducks on Deck DuckTales",
    "Season 1/DuckTales Season 1 Episode 63 All Ducks on Deck - DuckTales 1987.mp4"],
  ["Ducktales-Complete-Series", "DUCKTALES SERIES WORK IN PROGRESS - S01E64 - DuckTales Ducky Horror Picture Show DuckTales",
    "Season 1/DuckTales Season 1 Episode 64 Ducky Horror Picture Show - DuckTales 1987.mp4"],
  ["Ducktales-Complete-Series", "DUCKTALES SERIES WORK IN PROGRESS - S01E65 - DuckTales Till Nephews Do Us Part DuckTales",
    "Season 1/DuckTales Season 1 Episode 65 Till Nephews Do Us Part - DuckTales 1987.mp4"],
  ["Ducktales-Complete-Series", "DUCKTALES SERIES WORK IN PROGRESS - S02E01 - DuckTales Time Is Money Marking Time DuckTales",
    "Season 2/DuckTales Season 2 Episode 1 Time Is Money- Marking Time - DuckTales 1987.mp4"],
  ["Ducktales-Complete-Series", "DUCKTALES SERIES WORK IN PROGRESS - S02E02 - DuckTales Time Is Money The Duck Who Would Be King DuckTales",
    "Season 2/DuckTales Season 2 Episode 2 Time Is Money- The Duck Who Would Be King - DuckTales 1987.mp4"],
  ["Ducktales-Complete-Series", "DUCKTALES SERIES WORK IN PROGRESS - S02E03 - DuckTales Time Is Money Bubba Trubba DuckTales",
    "Season 2/DuckTales Season 2 Episode 3 Time Is Money- Bubba Trubba - DuckTales 1987.mp4"],
  ["Ducktales-Complete-Series", "DUCKTALES SERIES WORK IN PROGRESS - S02E04 - DuckTales Time Is Money Ducks on the Lam DuckTales",
    "Season 2/DuckTales Season 2 Episode 4 Time Is Money- Ducks on the Lam - DuckTales 1987.mp4"],
  ["Ducktales-Complete-Series", "DUCKTALES SERIES WORK IN PROGRESS - S02E05 - DuckTales Time Is Money Ali Bubba’s Cave DuckTales",
    "Season 2/DuckTales Season 2 Episode 5 Time Is Money- Ali Bubba’s Cave - DuckTales 1987.mp4"],
  ["Ducktales-Complete-Series", "DUCKTALES SERIES WORK IN PROGRESS - S02E06 - DuckTales Super DuckTales Liquid Assets DuckTales",
    "Season 2/DuckTales Season 2 Episode 6 Super DuckTales- Liquid Assets - DuckTales 1987.mp4"],
  ["Ducktales-Complete-Series", "DUCKTALES SERIES WORK IN PROGRESS - S02E07 - DuckTales Super DuckTales Frozen Assets DuckTales",
    "Season 2/DuckTales Season 2 Episode 7 Super DuckTales- Frozen Assets - DuckTales 1987.mp4"],
  ["Ducktales-Complete-Series", "DUCKTALES SERIES WORK IN PROGRESS - S02E08 - DuckTales Super DuckTales Full Metal Duck DuckTales",
    "Season 2/DuckTales Season 2 Episode 8 Super DuckTales- Full Metal Duck - DuckTales 1987.mp4"],
  ["Ducktales-Complete-Series", "DUCKTALES SERIES WORK IN PROGRESS - S02E09 - DuckTales Super DuckTales The Billionaire Beagle Boys Club DuckTales",
    "Season 2/DuckTales Season 2 Episode 9 Super DuckTales- The Billionaire Beagle Boys Club - DuckTales 1987.mp4"],
  ["Ducktales-Complete-Series", "DUCKTALES SERIES WORK IN PROGRESS - S02E10 - DuckTales Super DuckTales Money to Burn DuckTales",
    "Season 2/DuckTales Season 2 Episode 10 Super DuckTales- Money to Burn - DuckTales 1987.mp4"],
],
  durations: {
  "Ducktales-Complete-Series::Season 1/DuckTales S01E01 Dont give up the ship.mp4": 1371,
  "Ducktales-Complete-Series::Season 1/DuckTales S01E02 Wronguay in Ronguay.mp4": 1370,
  "Ducktales-Complete-Series::Season 1/DuckTales S01E03 Three Ducks of the Condor.mp4": 1371,
  "Ducktales-Complete-Series::Season 1/DuckTales S01E04 Cold Duck.mp4": 1370,
  "Ducktales-Complete-Series::Season 1/DuckTales S01E05 Too Much of a Gold Thing.mp4": 1372,
  "Ducktales-Complete-Series::Season 1/DuckTales S01E06 Send in the Clones.mp4": 1371,
  "Ducktales-Complete-Series::Season 1/DuckTales S01E07 Sphinx for the Memories.mp4": 1371,
  "Ducktales-Complete-Series::Season 1/DuckTales S01E08 No Duck Has Gone Before.mp4": 1368,
  "Ducktales-Complete-Series::Season 1/DuckTales S01E09 Armstong.mp4": 1371,
  "Ducktales-Complete-Series::Season 1/DuckTales S01E10 Robot Robbers.mp4": 1373,
  "Ducktales-Complete-Series::Season 1/DuckTales S01E11 Magica_s Shadow War.mp4": 1369,
  "Ducktales-Complete-Series::Season 1/DuckTales S01E12 Master of Dijinni.mp4": 1371,
  "Ducktales-Complete-Series::Season 1/DuckTales S01E13 Hotel Strangeduck.mp4": 1371,
  "Ducktales-Complete-Series::Season 1/DuckTales S01E14 Lost Crown of Genghis Khan.mp4": 1371,
  "Ducktales-Complete-Series::Season 1/DuckTales S01E15 Duckman Of Aquatrz.mp4": 1371,
  "Ducktales-Complete-Series::Season 1/DuckTales S01E16 The Money Vanishes.mp4": 1370,
  "Ducktales-Complete-Series::Season 1/DuckTales S01E17 Sir Gyro de Gearloose.mp4": 1370,
  "Ducktales-Complete-Series::Season 1/DuckTales S01E18 Dinosaur Ducks.mp4": 1369,
  "Ducktales-Complete-Series::Season 1/DuckTales S01E19 Hero For Hire.mp4": 1371,
  "Ducktales-Complete-Series::Season 1/DuckTales S01E20 Superdoo!.mp4": 1371,
  "Ducktales-Complete-Series::Season 1/DuckTales Season 1 Episode 21 Maid of the Myth - DuckTales 1987.mp4": 1371,
  "Ducktales-Complete-Series::Season 1/DuckTales Season 1 Episode 22 Down & Out in Duckburg - DuckTales 1987.mp4": 1369,
  "Ducktales-Complete-Series::Season 1/DuckTales Season 1 Episode 23 Much Ado About Scrooge - DuckTales 1987.mp4": 1371,
  "Ducktales-Complete-Series::Season 1/DuckTales Season 1 Episode 24 Top Duck - DuckTales 1987.mp4": 1371,
  "Ducktales-Complete-Series::Season 1/DuckTales Season 1 Episode 25 Pearl of Wisdom - DuckTales 1987.mp4": 1370,
  "Ducktales-Complete-Series::Season 1/DuckTales Season 1 Episode 26 The Curse of Castle McDuck - DuckTales 1987.mp4": 1371,
  "Ducktales-Complete-Series::Season 1/DuckTales Season 1 Episode 27 Launchpad’s Civil War - DuckTales 1987.mp4": 1371,
  "Ducktales-Complete-Series::Season 1/DuckTales Season 1 Episode 28 Sweet Duck of Youth - DuckTales 1987.mp4": 1371,
  "Ducktales-Complete-Series::Season 1/DuckTales Season 1 Episode 29 Earth Quack - DuckTales 1987.mp4": 1370,
  "Ducktales-Complete-Series::Season 1/DuckTales Season 1 Episode 30 Home Sweet Homer - DuckTales 1987.mp4": 1370,
  "Ducktales-Complete-Series::Season 1/DuckTales Season 1 Episode 31 Bermuda Triangle Tangle - DuckTales 1987.mp4": 1371,
  "Ducktales-Complete-Series::Season 1/DuckTales Season 1 Episode 33 Back to the Klondike - DuckTales 1987.mp4": 1371,
  "Ducktales-Complete-Series::Season 1/DuckTales Season 1 Episode 34 Horse Scents - DuckTales 1987.mp4": 1372,
  "Ducktales-Complete-Series::Season 1/DuckTales Season 1 Episode 35 Scrooge’s Pet - DuckTales 1987.mp4": 1370,
  "Ducktales-Complete-Series::Season 1/DuckTales Season 1 Episode 36 Catch as Cash Can- A Drain on the Economy - DuckTales 1987.mp4": 1370,
  "Ducktales-Complete-Series::Season 1/DuckTales Season 1 Episode 37 Catch as Cash Can- A Whale of a Bad Time - DuckTales 1987.mp4": 1371,
  "Ducktales-Complete-Series::Season 1/DuckTales Season 1 Episode 38 Catch as Cash Can- Aqua Ducks - DuckTales 1987.mp4": 1373,
  "Ducktales-Complete-Series::Season 1/DuckTales Season 1 Episode 39 Catch as Cash Can- Working for Scales - DuckTales 1987.mp4": 1370,
  "Ducktales-Complete-Series::Season 1/DuckTales Season 1 Episode 40 Merit-Time Adventure - DuckTales 1987.mp4": 1370,
  "Ducktales-Complete-Series::Season 1/DuckTales Season 1 Episode 41 The Golden Fleecing - DuckTales 1987.mp4": 1369,
  "Ducktales-Complete-Series::Season 1/DuckTales Season 1 Episode 42 Ducks of the West - DuckTales 1987.mp4": 1371,
  "Ducktales-Complete-Series::Season 1/DuckTales Season 1 Episode 43 Time Teasers - DuckTales 1987.mp4": 1368,
  "Ducktales-Complete-Series::Season 1/DuckTales Season 1 Episode 44 Back Out in the Outback - DuckTales 1987.mp4": 1367,
  "Ducktales-Complete-Series::Season 1/DuckTales Season 1 Episode 45 Raiders of the Lost Harp - DuckTales 1987.mp4": 1370,
  "Ducktales-Complete-Series::Season 1/DuckTales Season 1 Episode 46 The Right Duck - DuckTales 1987.mp4": 1369,
  "Ducktales-Complete-Series::Season 1/DuckTales Season 1 Episode 47 Scroogerello - DuckTales 1987.mp4": 1369,
  "Ducktales-Complete-Series::Season 1/DuckTales Season 1 Episode 48 Double-O-Duck - DuckTales 1987.mp4": 1372,
  "Ducktales-Complete-Series::Season 1/DuckTales Season 1 Episode 49 Luck o’ the Ducks - DuckTales 1987.mp4": 1371,
  "Ducktales-Complete-Series::Season 1/DuckTales Season 1 Episode 50 Duckworth’s Revolt - DuckTales 1987.mp4": 1348,
  "Ducktales-Complete-Series::Season 1/DuckTales Season 1 Episode 51 Magica’s Magic Mirror - Take Me Out of the Ballgame - DuckTales 1987.mp4": 1368,
  "Ducktales-Complete-Series::Season 1/DuckTales Season 1 Episode 52 Duck to the Future - DuckTales 1987.mp4": 1371,
  "Ducktales-Complete-Series::Season 1/DuckTales Season 1 Episode 53 Jungle Duck - DuckTales 1987.mp4": 1370,
  "Ducktales-Complete-Series::Season 1/DuckTales Season 1 Episode 54 Launchpad’s First Crash - DuckTales 1987.mp4": 1368,
  "Ducktales-Complete-Series::Season 1/DuckTales Season 1 Episode 55 Dime Enough for Luck - DuckTales 1987.mp4": 1364,
  "Ducktales-Complete-Series::Season 1/DuckTales Season 1 Episode 56 The Duck in the Iron Mask - DuckTales 1987.mp4": 1369,
  "Ducktales-Complete-Series::Season 1/DuckTales Season 1 Episode 57 The Uncrashable Hindentanic - DuckTales 1987.mp4": 1367,
  "Ducktales-Complete-Series::Season 1/DuckTales Season 1 Episode 58 The Status Seekers - DuckTales 1987.mp4": 1365,
  "Ducktales-Complete-Series::Season 1/DuckTales Season 1 Episode 59 Nothing to Fear - DuckTales 1987.mp4": 1371,
  "Ducktales-Complete-Series::Season 1/DuckTales Season 1 Episode 60 Dr. Jekyll & Mr. McDuck - DuckTales 1987.mp4": 1371,
  "Ducktales-Complete-Series::Season 1/DuckTales Season 1 Episode 61 Once Upon a Dime - DuckTales 1987.mp4": 1368,
  "Ducktales-Complete-Series::Season 1/DuckTales Season 1 Episode 62 Spies in Their Eyes - DuckTales 1987.mp4": 1370,
  "Ducktales-Complete-Series::Season 1/DuckTales Season 1 Episode 63 All Ducks on Deck - DuckTales 1987.mp4": 1372,
  "Ducktales-Complete-Series::Season 1/DuckTales Season 1 Episode 64 Ducky Horror Picture Show - DuckTales 1987.mp4": 1371,
  "Ducktales-Complete-Series::Season 1/DuckTales Season 1 Episode 65 Till Nephews Do Us Part - DuckTales 1987.mp4": 1369,
  "Ducktales-Complete-Series::Season 2/DuckTales Season 2 Episode 1 Time Is Money- Marking Time - DuckTales 1987.mp4": 1375,
  "Ducktales-Complete-Series::Season 2/DuckTales Season 2 Episode 2 Time Is Money- The Duck Who Would Be King - DuckTales 1987.mp4": 1355,
  "Ducktales-Complete-Series::Season 2/DuckTales Season 2 Episode 3 Time Is Money- Bubba Trubba - DuckTales 1987.mp4": 1358,
  "Ducktales-Complete-Series::Season 2/DuckTales Season 2 Episode 4 Time Is Money- Ducks on the Lam - DuckTales 1987.mp4": 1373,
  "Ducktales-Complete-Series::Season 2/DuckTales Season 2 Episode 5 Time Is Money- Ali Bubba’s Cave - DuckTales 1987.mp4": 1372,
  "Ducktales-Complete-Series::Season 2/DuckTales Season 2 Episode 6 Super DuckTales- Liquid Assets - DuckTales 1987.mp4": 1373,
  "Ducktales-Complete-Series::Season 2/DuckTales Season 2 Episode 7 Super DuckTales- Frozen Assets - DuckTales 1987.mp4": 1372,
  "Ducktales-Complete-Series::Season 2/DuckTales Season 2 Episode 8 Super DuckTales- Full Metal Duck - DuckTales 1987.mp4": 1374,
  "Ducktales-Complete-Series::Season 2/DuckTales Season 2 Episode 9 Super DuckTales- The Billionaire Beagle Boys Club - DuckTales 1987.mp4": 1371,
  "Ducktales-Complete-Series::Season 2/DuckTales Season 2 Episode 10 Super DuckTales- Money to Burn - DuckTales 1987.mp4": 1368,
},
};
