window.SHOW = {
  id: "CaliforniaDreams",
  title: "California Dreams",
  art: "CaliforniaDreams.jpg",
  storageProgressKey: "californiadreams-progress",
  storageSettingsKey: "californiadreams-settings",
  nestedPaths: false,
  grouping: "season",
  segments: "none",
  episodes: [
  ["california-dreams-1992-season-one", "CALIFORNIA DREAMS - S01E01 - The First Gig",
    "California Dreams S01E01 The First Gig.mp4"],
  ["california-dreams-1992-season-one", "CALIFORNIA DREAMS - S01E02 - Battle of the Bands",
    "California Dreams S01E02 Battle of the Bands.mp4"],
  ["california-dreams-1992-season-one", "CALIFORNIA DREAMS - S01E03 - Beat of His Own Dream",
    "California Dreams S01E03 Beat of His Own Dream.mp4"],
  ["california-dreams-1992-season-one", "CALIFORNIA DREAMS - S01E04 - Double Date",
    "California Dreams S01E04 Double Date.mp4"],
  ["california-dreams-1992-season-one", "CALIFORNIA DREAMS - S01E05 - Dream Man",
    "California Dreams S01E05 Dream Man.mp4"],
  ["california-dreams-1992-season-one", "CALIFORNIA DREAMS - S01E06 - Friends First",
    "California Dreams S01E06 Friends First.mp4"],
  ["california-dreams-1992-season-one", "CALIFORNIA DREAMS - S01E07 - Guess Who's Coming to Brunch",
    "California Dreams S01E07 Guess Who's Coming to Brunch.mp4"],
  ["california-dreams-1992-season-one", "CALIFORNIA DREAMS - S01E08 - It's a Guy Thing",
    "California Dreams S01E08 It's a Guy Thing.mp4"],
  ["california-dreams-1992-season-one", "CALIFORNIA DREAMS - S01E09 - Mother and Child Reunion",
    "California Dreams S01E09 Mother and Child Reunion.mp4"],
  ["california-dreams-1992-season-one", "CALIFORNIA DREAMS - S01E10 - Romancing the Tube",
    "California Dreams S01E10 Romancing the Tube.mp4"],
  ["california-dreams-1992-season-one", "CALIFORNIA DREAMS - S01E11 - They Shoot Videos, Don't They?",
    "California Dreams S01E11 They Shoot Videos, Don't They.mp4"],
  ["california-dreams-1992-season-one", "CALIFORNIA DREAMS - S01E12 - This Time",
    "California Dreams S01E12 This Time.mp4"],
  ["california-dreams-1992-season-one", "CALIFORNIA DREAMS - S01E13 - Where's Dennis?",
    "California Dreams S01E13 Where's Dennis.mp4"],
],
  durations: {
  "california-dreams-1992-season-one::California Dreams S01E01 The First Gig.mp4": 1307,
  "california-dreams-1992-season-one::California Dreams S01E02 Battle of the Bands.mp4": 1347,
  "california-dreams-1992-season-one::California Dreams S01E03 Beat of His Own Dream.mp4": 1349,
  "california-dreams-1992-season-one::California Dreams S01E04 Double Date.mp4": 1308,
  "california-dreams-1992-season-one::California Dreams S01E05 Dream Man.mp4": 1349,
  "california-dreams-1992-season-one::California Dreams S01E06 Friends First.mp4": 1303,
  "california-dreams-1992-season-one::California Dreams S01E07 Guess Who's Coming to Brunch.mp4": 1348,
  "california-dreams-1992-season-one::California Dreams S01E08 It's a Guy Thing.mp4": 1304,
  "california-dreams-1992-season-one::California Dreams S01E09 Mother and Child Reunion.mp4": 1347,
  "california-dreams-1992-season-one::California Dreams S01E10 Romancing the Tube.mp4": 1347,
  "california-dreams-1992-season-one::California Dreams S01E11 They Shoot Videos, Don't They.mp4": 1307,
  "california-dreams-1992-season-one::California Dreams S01E12 This Time.mp4": 1302,
  "california-dreams-1992-season-one::California Dreams S01E13 Where's Dennis.mp4": 1301,
},
};
