window.SHOW = {
  id: "KarateKid",
  title: "The Karate Kid",
  art: "KarateKid.jpg",
  storageProgressKey: "karatekid-progress",
  storageSettingsKey: "karatekid-settings",
  nestedPaths: true,
  grouping: "season",
  segments: "none",
  episodes: [
  ["the-karate-kid-the-animated-series-complete-series-1989", "THE KARATE KID - S01E01 - My Brother's Keeper",
    "The Karate Kid - E01 (My Brothers Keeper).mp4"],
  ["the-karate-kid-the-animated-series-complete-series-1989", "THE KARATE KID - S01E02 - The Greatest Victory",
    "The Karate Kid - E02 (The Greatest Victory).mp4"],
  ["the-karate-kid-the-animated-series-complete-series-1989", "THE KARATE KID - S01E03 - The Homecoming",
    "The Karate Kid - E03 (The Homecoming).mp4"],
  ["the-karate-kid-the-animated-series-complete-series-1989", "THE KARATE KID - S01E04 - The Tomorrow Man",
    "The Karate Kid - E04 (The Tomorrow Man).mp4"],
  ["the-karate-kid-the-animated-series-complete-series-1989", "THE KARATE KID - S01E05 - The Paper Hero",
    "The Karate Kid - E05 (The Paper Hero).mp4"],
  ["the-karate-kid-the-animated-series-complete-series-1989", "THE KARATE KID - S01E06 - All the World His Stage",
    "The Karate Kid - E06 (All the World His Stage).mp4"],
  ["the-karate-kid-the-animated-series-complete-series-1989", "THE KARATE KID - S01E07 - Over the Rainbow",
    "The Karate Kid - E07 (Over the Rainbow).mp4"],
  ["the-karate-kid-the-animated-series-complete-series-1989", "THE KARATE KID - S01E08 - The Return of the Shrine",
    "The Karate Kid - E08 (The Return of the Shrine).mp4"],
  ["the-karate-kid-the-animated-series-complete-series-1989", "THE KARATE KID - S01E09 - Walkabout",
    "The Karate Kid - E09 (Walkabout).mp4"],
  ["the-karate-kid-the-animated-series-complete-series-1989", "THE KARATE KID - S01E10 - East Meets West",
    "The Karate Kid - E10 (East Meets West).mp4"],
  ["the-karate-kid-the-animated-series-complete-series-1989", "THE KARATE KID - S01E11 - The Hunt",
    "The Karate Kid - E11 (The Hunt).mp4"],
  ["the-karate-kid-the-animated-series-complete-series-1989", "THE KARATE KID - S01E12 - The Gray Ghosts",
    "The Karate Kid - E12 (The Gray Ghosts).mp4"],
  ["the-karate-kid-the-animated-series-complete-series-1989", "THE KARATE KID - S01E13 - A Little World of His Own",
    "The Karate Kid - E13 (A Little World of His Own).mp4"],
],
  durations: {
  "the-karate-kid-the-animated-series-complete-series-1989::The Karate Kid - E01 (My Brothers Keeper).mp4": 1394,
  "the-karate-kid-the-animated-series-complete-series-1989::The Karate Kid - E02 (The Greatest Victory).mp4": 1393,
  "the-karate-kid-the-animated-series-complete-series-1989::The Karate Kid - E03 (The Homecoming).mp4": 1393,
  "the-karate-kid-the-animated-series-complete-series-1989::The Karate Kid - E04 (The Tomorrow Man).mp4": 1393,
  "the-karate-kid-the-animated-series-complete-series-1989::The Karate Kid - E05 (The Paper Hero).mp4": 1391,
  "the-karate-kid-the-animated-series-complete-series-1989::The Karate Kid - E06 (All the World His Stage).mp4": 1390,
  "the-karate-kid-the-animated-series-complete-series-1989::The Karate Kid - E07 (Over the Rainbow).mp4": 1394,
  "the-karate-kid-the-animated-series-complete-series-1989::The Karate Kid - E08 (The Return of the Shrine).mp4": 1363,
  "the-karate-kid-the-animated-series-complete-series-1989::The Karate Kid - E09 (Walkabout).mp4": 1393,
  "the-karate-kid-the-animated-series-complete-series-1989::The Karate Kid - E10 (East Meets West).mp4": 1394,
  "the-karate-kid-the-animated-series-complete-series-1989::The Karate Kid - E11 (The Hunt).mp4": 1394,
  "the-karate-kid-the-animated-series-complete-series-1989::The Karate Kid - E12 (The Gray Ghosts).mp4": 1394,
  "the-karate-kid-the-animated-series-complete-series-1989::The Karate Kid - E13 (A Little World of His Own).mp4": 1392,
},
};
