window.SHOW = {
  id: "BuzzLightyearofStarCommand",
  title: "Buzz Lightyear of Star Command",
  art: "BuzzLightyearofStarCommand.jpg",
  storageProgressKey: "buzzlightyearofstarcommand-progress",
  storageSettingsKey: "buzzlightyearofstarcommand-settings",
  nestedPaths: true,
  grouping: "season",
  segments: "none",
  episodes: [
  ["blosc", "BUZZ LIGHTYEAR OF STAR COMMAND - S01E00 - Pilot The Adventure Begins, (Times Forgotten",
    "1x00 - Pilot - The Adventure Begins, Part 1 (Times Forgotten).mp4"],
  ["blosc", "BUZZ LIGHTYEAR OF STAR COMMAND - S01E01 - The Torque Armada (Times Forgotten",
    "1x01 - The Torque Armada (Times Forgotten).mp4"],
  ["blosc", "BUZZ LIGHTYEAR OF STAR COMMAND - S01E02 - Gravitina (Times Forgotten",
    "1x02 - Gravitina (Times Forgotten).mp4"],
  ["blosc", "BUZZ LIGHTYEAR OF STAR COMMAND - S01E03 - XL (Times Forgotten",
    "1x03 - XL (Times Forgotten).mp4"],
  ["blosc", "BUZZ LIGHTYEAR OF STAR COMMAND - S01E04 - Little Secrets (Times Forgotten",
    "1x04 - Little Secrets (Times Forgotten).mp4"],
  ["blosc", "BUZZ LIGHTYEAR OF STAR COMMAND - S01E05 - Inside Job (mbaldw",
    "1x05 - Inside Job (mbaldw).mp4"],
  ["blosc", "BUZZ LIGHTYEAR OF STAR COMMAND - S01E06 - NOS 4 A2 (Times Forgotten",
    "1x06 - NOS-4-A2 (Times Forgotten).mp4"],
  ["blosc", "BUZZ LIGHTYEAR OF STAR COMMAND - S01E07 - The Planet Destroyer (Times Forgotten",
    "1x07 - The Planet Destroyer (Times Forgotten).mp4"],
  ["blosc", "BUZZ LIGHTYEAR OF STAR COMMAND - S01E08 - The Beasts of Karn (Times Forgotten",
    "1x08 - The Beasts of Karn (Times Forgotten).mp4"],
  ["blosc", "BUZZ LIGHTYEAR OF STAR COMMAND - S01E09 - Tag Team (Times Forgotten",
    "1x09 - Tag Team (Times Forgotten).mp4"],
  ["blosc", "BUZZ LIGHTYEAR OF STAR COMMAND - S01E10 - The Main Event (Times Forgotten",
    "1x10 - The Main Event (Times Forgotten).mp4"],
  ["blosc", "BUZZ LIGHTYEAR OF STAR COMMAND - S01E11 - The Return of XL (Times Forgotten",
    "1x11 - The Return of XL (Times Forgotten).mp4"],
  ["blosc", "BUZZ LIGHTYEAR OF STAR COMMAND - S01E12 - Lost in Time (Times Forgotten",
    "1x12 - Lost in Time (Times Forgotten).mp4"],
  ["blosc", "BUZZ LIGHTYEAR OF STAR COMMAND - S01E13 - Strange Invasion (Times Forgotten",
    "1x13 - Strange Invasion (Times Forgotten).mp4"],
  ["blosc", "BUZZ LIGHTYEAR OF STAR COMMAND - S01E14 - The Taking of PC 7 (Times Forgotten",
    "1x14 - The Taking of PC-7 (Times Forgotten).mp4"],
  ["blosc", "BUZZ LIGHTYEAR OF STAR COMMAND - S01E15 - Mindwarp (Times Forgotten",
    "1x15 - Mindwarp (Times Forgotten).mp4"],
  ["blosc", "BUZZ LIGHTYEAR OF STAR COMMAND - S01E16 - Mira's Wedding (Times Forgotten",
    "1x16 - Mira's Wedding (Times Forgotten).mp4"],
  ["blosc", "BUZZ LIGHTYEAR OF STAR COMMAND - S01E17 - Panic on Bathyos (Times Forgotten",
    "1x17 - Panic on Bathyos (Times Forgotten).mp4"],
  ["blosc", "BUZZ LIGHTYEAR OF STAR COMMAND - S01E18 - Shiv Katall (Times Forgotten",
    "1x18 - Shiv Katall (Times Forgotten).mp4"],
  ["blosc", "BUZZ LIGHTYEAR OF STAR COMMAND - S01E19 - Rookie of the Year (Times Forgotten",
    "1x19 - Rookie of the Year (Times Forgotten).mp4"],
  ["blosc", "BUZZ LIGHTYEAR OF STAR COMMAND - S01E20 - Stress Test (Times Forgotten",
    "1x20 - Stress Test (Times Forgotten).mp4"],
  ["blosc", "BUZZ LIGHTYEAR OF STAR COMMAND - S01E21 - A Zoo Out There (Times Forgotten",
    "1x21 - A Zoo Out There (Times Forgotten).mp4"],
  ["blosc", "BUZZ LIGHTYEAR OF STAR COMMAND - S01E22 - Root of Evil (Times Forgotten",
    "1x22 - Root of Evil (Times Forgotten).mp4"],
  ["blosc", "BUZZ LIGHTYEAR OF STAR COMMAND - S01E23 - Super Nova (mbaldw",
    "1x23 - Super Nova (mbaldw).mp4"],
  ["blosc", "BUZZ LIGHTYEAR OF STAR COMMAND - S01E24 - Downloaded (Times Forgotten",
    "1x24 - Downloaded (Times Forgotten).mp4"],
  ["blosc", "BUZZ LIGHTYEAR OF STAR COMMAND - S01E25 - The Plasma Monster (Times Forgotten",
    "1x25 - The Plasma Monster (Times Forgotten).mp4"],
  ["blosc", "BUZZ LIGHTYEAR OF STAR COMMAND - S01E26 - Wirewolf (Times Forgotten",
    "1x26 - Wirewolf (Times Forgotten).mp4"],
  ["blosc", "BUZZ LIGHTYEAR OF STAR COMMAND - S01E27 - The Crawling Flesh (Times Forgotten",
    "1x27 - The Crawling Flesh (Times Forgotten).mp4"],
  ["blosc", "BUZZ LIGHTYEAR OF STAR COMMAND - S01E28 - Dirty Work (Times Forgotten",
    "1x28 - Dirty Work (Times Forgotten).mp4"],
  ["blosc", "BUZZ LIGHTYEAR OF STAR COMMAND - S01E29 - The Slayer (Times Forgotten",
    "1x29 - The Slayer (Times Forgotten).mp4"],
  ["blosc", "BUZZ LIGHTYEAR OF STAR COMMAND - S01E30 - The Lightyear Factor (Times Forgotten",
    "1x30 - The Lightyear Factor (Times Forgotten).mp4"],
  ["blosc", "BUZZ LIGHTYEAR OF STAR COMMAND - S01E31 - Clone Rangers (Times Forgotten",
    "1x31 - Clone Rangers (Times Forgotten).mp4"],
  ["blosc", "BUZZ LIGHTYEAR OF STAR COMMAND - S01E32 - Bunzel Fever (Times Forgotten",
    "1x32 - Bunzel Fever (Times Forgotten).mp4"],
  ["blosc", "BUZZ LIGHTYEAR OF STAR COMMAND - S01E33 - Rescue Mission (Times Forgotten",
    "1x33 - Rescue Mission (Times Forgotten).mp4"],
  ["blosc", "BUZZ LIGHTYEAR OF STAR COMMAND - S01E34 - Devolutionaries (Times Forgotten",
    "1x34 - Devolutionaries (Times Forgotten).mp4"],
  ["blosc", "BUZZ LIGHTYEAR OF STAR COMMAND - S01E35 - Head Case (Times Forgotten",
    "1x35 - Head Case (Times Forgotten).mp4"],
  ["blosc", "BUZZ LIGHTYEAR OF STAR COMMAND - S01E36 - The Yukari Imprint (Times Forgotten",
    "1x36 - The Yukari Imprint (Times Forgotten).mp4"],
  ["blosc", "BUZZ LIGHTYEAR OF STAR COMMAND - S01E37 - The Shape Stealer (Times Forgotten",
    "1x37 - The Shape Stealer (Times Forgotten).mp4"],
  ["blosc", "BUZZ LIGHTYEAR OF STAR COMMAND - S01E38 - Star Crossed (Times Forgotten",
    "1x38 - Star Crossed (Times Forgotten).mp4"],
  ["blosc", "BUZZ LIGHTYEAR OF STAR COMMAND - S01E39 - Haunted Moon (Times Forgotten",
    "1x39 - Haunted Moon (Times Forgotten).mp4"],
  ["blosc", "BUZZ LIGHTYEAR OF STAR COMMAND - S01E40 - Star Smasher (Times Forgotten",
    "1x40 - Star Smasher (Times Forgotten).mp4"],
  ["blosc", "BUZZ LIGHTYEAR OF STAR COMMAND - S01E41 - Stranger Invasion (Times Forgotten",
    "1x41 - Stranger Invasion (Times Forgotten).mp4"],
  ["blosc", "BUZZ LIGHTYEAR OF STAR COMMAND - S01E42 - Eye of the Tempest (Times Forgotten",
    "1x42 - Eye of the Tempest (Times Forgotten).mp4"],
  ["blosc", "BUZZ LIGHTYEAR OF STAR COMMAND - S01E43 - Revenge of the Monsters (Times Forgotten",
    "1x43 - Revenge of the Monsters (Times Forgotten).mp4"],
  ["blosc", "BUZZ LIGHTYEAR OF STAR COMMAND - S01E44 - Lone Wolf (Times Forgotten",
    "1x44 - Lone Wolf (Times Forgotten).mp4"],
  ["blosc", "BUZZ LIGHTYEAR OF STAR COMMAND - S01E45 - Planet of the Lost (Times Forgotten",
    "1x45 - Planet of the Lost (Times Forgotten).mp4"],
  ["blosc", "BUZZ LIGHTYEAR OF STAR COMMAND - S01E46 - Revenge of the Raenoks (Times Forgotten",
    "1x46 - Revenge of the Raenoks (Times Forgotten).mp4"],
  ["blosc", "BUZZ LIGHTYEAR OF STAR COMMAND - S01E47 - Enemy Without a Face (Times Forgotten",
    "1x47 - Enemy Without a Face (Times Forgotten).mp4"],
  ["blosc", "BUZZ LIGHTYEAR OF STAR COMMAND - S01E48 - The Starthought (Times Forgotten",
    "1x48 - The Starthought (Times Forgotten).mp4"],
  ["blosc", "BUZZ LIGHTYEAR OF STAR COMMAND - S01E49 - Millennial Bugs (Times Forgotten",
    "1x49 - Millennial Bugs (Times Forgotten).mp4"],
  ["blosc", "BUZZ LIGHTYEAR OF STAR COMMAND - S01E50 - Conspiracy (mbaldw",
    "1x50 - Conspiracy (mbaldw).mp4"],
  ["blosc", "BUZZ LIGHTYEAR OF STAR COMMAND - S01E51 - At Large on a Small Planet (Times Forgotten",
    "1x51 - At Large on a Small Planet (Times Forgotten).mp4"],
  ["blosc", "BUZZ LIGHTYEAR OF STAR COMMAND - S01E52 - Sunquake (Times Forgotten",
    "1x52 - Sunquake (Times Forgotten).mp4"],
  ["blosc", "BUZZ LIGHTYEAR OF STAR COMMAND - S01E53 - Good Ol' Buzz (Times Forgotten",
    "1x53 - Good Ol' Buzz (Times Forgotten).mp4"],
  ["blosc", "BUZZ LIGHTYEAR OF STAR COMMAND - S01E54 - First Missions (Times Forgotten",
    "1x54 - First Missions (Times Forgotten).mp4"],
  ["blosc", "BUZZ LIGHTYEAR OF STAR COMMAND - S01E55 - Large Target (Times Forgotten",
    "1x55 - Large Target (Times Forgotten).mp4"],
  ["blosc", "BUZZ LIGHTYEAR OF STAR COMMAND - S01E56 - War, and Peace and War (Times Forgotten",
    "1x56 - War, and Peace and War (Times Forgotten).mp4"],
  ["blosc", "BUZZ LIGHTYEAR OF STAR COMMAND - S01E57 - Return to Karn (Times Forgotten",
    "1x57 - Return to Karn (Times Forgotten).mp4"],
  ["blosc", "BUZZ LIGHTYEAR OF STAR COMMAND - S01E58 - Speed Trap (Times Forgotten",
    "1x58 - Speed Trap (Times Forgotten).mp4"],
  ["blosc", "BUZZ LIGHTYEAR OF STAR COMMAND - S01E59 - Holiday Time (Times Forgotten",
    "1x59 - Holiday Time (Times Forgotten).mp4"],
  ["blosc", "BUZZ LIGHTYEAR OF STAR COMMAND - S01E60 - Opposites Attract (Times Forgotten",
    "1x60 - Opposites Attract (Times Forgotten).mp4"],
  ["blosc", "BUZZ LIGHTYEAR OF STAR COMMAND - S01E61 - Ancient Evil (Times Forgotten",
    "1x61 - Ancient Evil (Times Forgotten).mp4"],
  ["blosc", "BUZZ LIGHTYEAR OF STAR COMMAND - S01E62 - 42 (Times Forgotten",
    "1x62 - 42 (Times Forgotten).mp4"],
],
  durations: {
  "blosc::1x00 - Pilot - The Adventure Begins, Part 1 (Times Forgotten).mp4": 1361,
  "blosc::1x01 - The Torque Armada (Times Forgotten).mp4": 1364,
  "blosc::1x02 - Gravitina (Times Forgotten).mp4": 1364,
  "blosc::1x03 - XL (Times Forgotten).mp4": 1365,
  "blosc::1x04 - Little Secrets (Times Forgotten).mp4": 1364,
  "blosc::1x05 - Inside Job (mbaldw).mp4": 1283,
  "blosc::1x06 - NOS-4-A2 (Times Forgotten).mp4": 1365,
  "blosc::1x07 - The Planet Destroyer (Times Forgotten).mp4": 1366,
  "blosc::1x08 - The Beasts of Karn (Times Forgotten).mp4": 1354,
  "blosc::1x09 - Tag Team (Times Forgotten).mp4": 1363,
  "blosc::1x10 - The Main Event (Times Forgotten).mp4": 1366,
  "blosc::1x11 - The Return of XL (Times Forgotten).mp4": 1364,
  "blosc::1x12 - Lost in Time (Times Forgotten).mp4": 1366,
  "blosc::1x13 - Strange Invasion (Times Forgotten).mp4": 1364,
  "blosc::1x14 - The Taking of PC-7 (Times Forgotten).mp4": 1365,
  "blosc::1x15 - Mindwarp (Times Forgotten).mp4": 1365,
  "blosc::1x16 - Mira's Wedding (Times Forgotten).mp4": 1363,
  "blosc::1x17 - Panic on Bathyos (Times Forgotten).mp4": 1365,
  "blosc::1x18 - Shiv Katall (Times Forgotten).mp4": 1365,
  "blosc::1x19 - Rookie of the Year (Times Forgotten).mp4": 1365,
  "blosc::1x20 - Stress Test (Times Forgotten).mp4": 1364,
  "blosc::1x21 - A Zoo Out There (Times Forgotten).mp4": 1364,
  "blosc::1x22 - Root of Evil (Times Forgotten).mp4": 1367,
  "blosc::1x23 - Super Nova (mbaldw).mp4": 1291,
  "blosc::1x24 - Downloaded (Times Forgotten).mp4": 1365,
  "blosc::1x25 - The Plasma Monster (Times Forgotten).mp4": 1345,
  "blosc::1x26 - Wirewolf (Times Forgotten).mp4": 1364,
  "blosc::1x27 - The Crawling Flesh (Times Forgotten).mp4": 1364,
  "blosc::1x28 - Dirty Work (Times Forgotten).mp4": 1363,
  "blosc::1x29 - The Slayer (Times Forgotten).mp4": 1364,
  "blosc::1x30 - The Lightyear Factor (Times Forgotten).mp4": 1366,
  "blosc::1x31 - Clone Rangers (Times Forgotten).mp4": 1365,
  "blosc::1x32 - Bunzel Fever (Times Forgotten).mp4": 1364,
  "blosc::1x33 - Rescue Mission (Times Forgotten).mp4": 1362,
  "blosc::1x34 - Devolutionaries (Times Forgotten).mp4": 1369,
  "blosc::1x35 - Head Case (Times Forgotten).mp4": 1366,
  "blosc::1x36 - The Yukari Imprint (Times Forgotten).mp4": 1366,
  "blosc::1x37 - The Shape Stealer (Times Forgotten).mp4": 1367,
  "blosc::1x38 - Star Crossed (Times Forgotten).mp4": 1366,
  "blosc::1x39 - Haunted Moon (Times Forgotten).mp4": 1363,
  "blosc::1x40 - Star Smasher (Times Forgotten).mp4": 1365,
  "blosc::1x41 - Stranger Invasion (Times Forgotten).mp4": 1364,
  "blosc::1x42 - Eye of the Tempest (Times Forgotten).mp4": 1366,
  "blosc::1x43 - Revenge of the Monsters (Times Forgotten).mp4": 1364,
  "blosc::1x44 - Lone Wolf (Times Forgotten).mp4": 1361,
  "blosc::1x45 - Planet of the Lost (Times Forgotten).mp4": 1367,
  "blosc::1x46 - Revenge of the Raenoks (Times Forgotten).mp4": 1365,
  "blosc::1x47 - Enemy Without a Face (Times Forgotten).mp4": 1363,
  "blosc::1x48 - The Starthought (Times Forgotten).mp4": 1365,
  "blosc::1x49 - Millennial Bugs (Times Forgotten).mp4": 1365,
  "blosc::1x50 - Conspiracy (mbaldw).mp4": 1305,
  "blosc::1x51 - At Large on a Small Planet (Times Forgotten).mp4": 1364,
  "blosc::1x52 - Sunquake (Times Forgotten).mp4": 1363,
  "blosc::1x53 - Good Ol' Buzz (Times Forgotten).mp4": 1364,
  "blosc::1x54 - First Missions (Times Forgotten).mp4": 1364,
  "blosc::1x55 - Large Target (Times Forgotten).mp4": 1363,
  "blosc::1x56 - War, and Peace and War (Times Forgotten).mp4": 1364,
  "blosc::1x57 - Return to Karn (Times Forgotten).mp4": 1366,
  "blosc::1x58 - Speed Trap (Times Forgotten).mp4": 1363,
  "blosc::1x59 - Holiday Time (Times Forgotten).mp4": 1364,
  "blosc::1x60 - Opposites Attract (Times Forgotten).mp4": 1363,
  "blosc::1x61 - Ancient Evil (Times Forgotten).mp4": 1363,
  "blosc::1x62 - 42 (Times Forgotten).mp4": 1363,
},
};
