window.SHOW = {
  id: "JuryDutySeries",
  title: "Jury Duty Series",
  art: "JuryDutySeries.png",
  storageProgressKey: "jurydutyseries-progress",
  storageSettingsKey: "jurydutyseries-settings",
  nestedPaths: true,
  grouping: "season",
  segments: "none",
  episodes: [
  ["jury-duty", "JURY DUTY SERIES - S01E01 - Jury Duty E01 Voir Dire",
    "Jury Duty E01 - Voir Dire.ia.mp4"],
  ["jury-duty", "JURY DUTY SERIES - S01E02 - Jury Duty E02 Opening Arguments",
    "Jury Duty E02 - Opening Arguments.ia.mp4"],
  ["jury-duty", "JURY DUTY SERIES - S01E03 - Jury Duty E03 Foreperson",
    "Jury Duty E03 - Foreperson.ia.mp4"],
  ["jury-duty", "JURY DUTY SERIES - S01E04 - Jury Duty E04 Field Trip",
    "Jury Duty E04 - Field Trip.ia.mp4"],
  ["jury-duty", "JURY DUTY SERIES - S01E05 - Jury Duty E05 Inneffective Assistence",
    "Jury Duty E05 - Inneffective Assistence.ia.mp4"],
  ["jury-duty", "JURY DUTY SERIES - S01E06 - Jury Duty E06 Closing Arguments",
    "Jury Duty E06 - Closing Arguments.ia.mp4"],
  ["jury-duty", "JURY DUTY SERIES - S01E07 - Jury Duty E07 Deliberations",
    "Jury Duty E07 - Deliberations.ia.mp4"],
  ["jury-duty", "JURY DUTY SERIES - S01E08 - Jury Duty E08 The Verdict",
    "Jury Duty E08 - The Verdict.ia.mp4"],
],
  durations: {
  "jury-duty::Jury Duty E01 - Voir Dire.ia.mp4": 1584,
  "jury-duty::Jury Duty E02 - Opening Arguments.ia.mp4": 1724,
  "jury-duty::Jury Duty E03 - Foreperson.ia.mp4": 1760,
  "jury-duty::Jury Duty E04 - Field Trip.ia.mp4": 1604,
  "jury-duty::Jury Duty E05 - Inneffective Assistence.ia.mp4": 1823,
  "jury-duty::Jury Duty E06 - Closing Arguments.ia.mp4": 1790,
  "jury-duty::Jury Duty E07 - Deliberations.ia.mp4": 1676,
  "jury-duty::Jury Duty E08 - The Verdict.ia.mp4": 1780,
},
};
