window.SHOW = {
  id: "ALFtheSeries",
  title: "ALF the Series",
  art: "ALFtheSeries.jpg",
  storageProgressKey: "alftheseries-progress",
  storageSettingsKey: "alftheseries-settings",
  nestedPaths: true,
  grouping: "season",
  segments: "none",
  episodes: [
  ["ALF-The-Complete-Series", "ALF THE SERIES - S00E01 - Untitled",
    "Alf/Specials/ALF - S00E01 - Pilot (Unaired) SDTV.mp4"],
  ["ALF-The-Complete-Series", "ALF THE SERIES - S00E02 - Untitled",
    "Alf/Specials/ALF - S00E02 - Project - ALF SDTV.mp4"],
  ["ALF-The-Complete-Series", "ALF THE SERIES - S01E01 - Alf/ /ALF A.L.F SDTV",
    "Alf/Season 01/ALF - S01E01 - A.L.F SDTV.mp4"],
  ["ALF-The-Complete-Series", "ALF THE SERIES - S01E02 - Alf/ /ALF Strangers in the Night SDTV",
    "Alf/Season 01/ALF - S01E02 - Strangers in the Night SDTV.mp4"],
  ["ALF-The-Complete-Series", "ALF THE SERIES - S01E03 - Alf/ /ALF Looking for Lucky SDTV",
    "Alf/Season 01/ALF - S01E03 - Looking for Lucky SDTV.mp4"],
  ["ALF-The-Complete-Series", "ALF THE SERIES - S01E04 - Alf/ /ALF Pennsylvania 6 5000 SDTV",
    "Alf/Season 01/ALF - S01E04 - Pennsylvania 6-5000 SDTV.mp4"],
  ["ALF-The-Complete-Series", "ALF THE SERIES - S01E05 - Alf/ /ALF Keepin' the Faith SDTV",
    "Alf/Season 01/ALF - S01E05 - Keepin' the Faith SDTV.mp4"],
  ["ALF-The-Complete-Series", "ALF THE SERIES - S01E06 - Alf/ /ALF For Your Eyes Only SDTV",
    "Alf/Season 01/ALF - S01E06 - For Your Eyes Only SDTV.mp4"],
  ["ALF-The-Complete-Series", "ALF THE SERIES - S01E07 - Alf/ /ALF Help Me, Rhonda SDTV",
    "Alf/Season 01/ALF - S01E07 - Help Me, Rhonda SDTV.mp4"],
  ["ALF-The-Complete-Series", "ALF THE SERIES - S01E08 - Alf/ /ALF Don't It Make My Brown Eyes Blue SDTV",
    "Alf/Season 01/ALF - S01E08 - Don't It Make My Brown Eyes Blue SDTV.mp4"],
  ["ALF-The-Complete-Series", "ALF THE SERIES - S01E09 - Alf/ /ALF Jump SDTV",
    "Alf/Season 01/ALF - S01E09 - Jump SDTV.mp4"],
  ["ALF-The-Complete-Series", "ALF THE SERIES - S01E10 - Alf/ /ALF Baby, You Can Drive My Car SDTV",
    "Alf/Season 01/ALF - S01E10 - Baby, You Can Drive My Car SDTV.mp4"],
  ["ALF-The-Complete-Series", "ALF THE SERIES - S01E11 - Alf/ /ALF On the Road Again SDTV",
    "Alf/Season 01/ALF - S01E11 - On the Road Again SDTV.mp4"],
  ["ALF-The-Complete-Series", "ALF THE SERIES - S01E12 - Alf/ /ALF Oh, Tannerbaum SDTV",
    "Alf/Season 01/ALF - S01E12 - Oh, Tannerbaum SDTV.mp4"],
  ["ALF-The-Complete-Series", "ALF THE SERIES - S01E13 - Alf/ /ALF Mother and Child Reunion SDTV",
    "Alf/Season 01/ALF - S01E13 - Mother and Child Reunion SDTV.mp4"],
  ["ALF-The-Complete-Series", "ALF THE SERIES - S01E14 - Alf/ /ALF A Little Bit of Soap SDTV",
    "Alf/Season 01/ALF - S01E14 - A Little Bit of Soap SDTV.mp4"],
  ["ALF-The-Complete-Series", "ALF THE SERIES - S01E15 - Alf/ /ALF I've Got a New Attitude SDTV",
    "Alf/Season 01/ALF - S01E15 - I've Got a New Attitude SDTV.mp4"],
  ["ALF-The-Complete-Series", "ALF THE SERIES - S01E16 - Alf/ /ALF E17 Try to Remember SDTV",
    "Alf/Season 01/ALF - S01E16-E17 - Try to Remember SDTV.mp4"],
  ["ALF-The-Complete-Series", "ALF THE SERIES - S01E18 - Alf/ /ALF Border Song SDTV",
    "Alf/Season 01/ALF - S01E18 - Border Song SDTV.mp4"],
  ["ALF-The-Complete-Series", "ALF THE SERIES - S01E19 - Alf/ /ALF Wild Thing SDTV",
    "Alf/Season 01/ALF - S01E19 - Wild Thing SDTV.mp4"],
  ["ALF-The-Complete-Series", "ALF THE SERIES - S01E20 - Alf/ /ALF Going Out of My Head Over You SDTV",
    "Alf/Season 01/ALF - S01E20 - Going Out of My Head Over You SDTV.mp4"],
  ["ALF-The-Complete-Series", "ALF THE SERIES - S01E21 - Alf/ /ALF Lookin' Through the Windows SDTV",
    "Alf/Season 01/ALF - S01E21 - Lookin' Through the Windows SDTV.mp4"],
  ["ALF-The-Complete-Series", "ALF THE SERIES - S01E22 - Alf/ /ALF It's Not Easy Being Green SDTV",
    "Alf/Season 01/ALF - S01E22 - It's Not Easy Being Green SDTV.mp4"],
  ["ALF-The-Complete-Series", "ALF THE SERIES - S01E23 - Alf/ /ALF The Gambler SDTV",
    "Alf/Season 01/ALF - S01E23 - The Gambler SDTV.mp4"],
  ["ALF-The-Complete-Series", "ALF THE SERIES - S01E24 - Alf/ /ALF Weird Science SDTV",
    "Alf/Season 01/ALF - S01E24 - Weird Science SDTV.mp4"],
  ["ALF-The-Complete-Series", "ALF THE SERIES - S01E25 - Alf/ /ALF La Cucaracha SDTV",
    "Alf/Season 01/ALF - S01E25 - La Cucaracha SDTV.mp4"],
  ["ALF-The-Complete-Series", "ALF THE SERIES - S01E26 - Alf/ /ALF Come Fly with Me SDTV",
    "Alf/Season 01/ALF - S01E26 - Come Fly with Me SDTV.mp4"],
  ["ALF-The-Complete-Series", "ALF THE SERIES - S02E01 - Alf/ /ALF Working My Way Back to You SDTV",
    "Alf/Season 02/ALF - S02E01 - Working My Way Back to You SDTV.mp4"],
  ["ALF-The-Complete-Series", "ALF THE SERIES - S02E02 - Alf/ /ALF Somewhere Over the Rerun (aka The Ballad of Gilligan's Island)…",
    "Alf/Season 02/ALF - S02E02 - Somewhere Over the Rerun (aka The Ballad of Gilligan's Island) SDTV.mp4"],
  ["ALF-The-Complete-Series", "ALF THE SERIES - S02E03 - Alf/ /ALF Take a Look at Me Now SDTV",
    "Alf/Season 02/ALF - S02E03 - Take a Look at Me Now SDTV.mp4"],
  ["ALF-The-Complete-Series", "ALF THE SERIES - S02E04 - Alf/ /ALF Wedding Bell Blues SDTV",
    "Alf/Season 02/ALF - S02E04 - Wedding Bell Blues SDTV.mp4"],
  ["ALF-The-Complete-Series", "ALF THE SERIES - S02E05 - Alf/ /ALF Prime Time SDTV",
    "Alf/Season 02/ALF - S02E05 - Prime Time SDTV.mp4"],
  ["ALF-The-Complete-Series", "ALF THE SERIES - S02E06 - Alf/ /ALF Some Enchanted Evening SDTV",
    "Alf/Season 02/ALF - S02E06 - Some Enchanted Evening SDTV.mp4"],
  ["ALF-The-Complete-Series", "ALF THE SERIES - S02E07 - Alf/ /ALF Oh, Pretty Woman SDTV",
    "Alf/Season 02/ALF - S02E07 - Oh, Pretty Woman SDTV.mp4"],
  ["ALF-The-Complete-Series", "ALF THE SERIES - S02E08 - Alf/ /ALF Something's Wrong with Me SDTV",
    "Alf/Season 02/ALF - S02E08 - Something's Wrong with Me SDTV.mp4"],
  ["ALF-The-Complete-Series", "ALF THE SERIES - S02E09 - Alf/ /ALF Night Train SDTV",
    "Alf/Season 02/ALF - S02E09 - Night Train SDTV.mp4"],
  ["ALF-The-Complete-Series", "ALF THE SERIES - S02E10 - Alf/ /ALF Isn't It Romantic SDTV",
    "Alf/Season 02/ALF - S02E10 - Isn't It Romantic SDTV.mp4"],
  ["ALF-The-Complete-Series", "ALF THE SERIES - S02E11 - Alf/ /ALF Hail to the Chief SDTV",
    "Alf/Season 02/ALF - S02E11 - Hail to the Chief SDTV.mp4"],
  ["ALF-The-Complete-Series", "ALF THE SERIES - S02E12 - Untitled",
    "Alf/Season 02/ALF - S02E12-E13 - ALF's Special Christmas SDTV.mp4"],
  ["ALF-The-Complete-Series", "ALF THE SERIES - S02E14 - Alf/ /ALF The Boy Next Door SDTV",
    "Alf/Season 02/ALF - S02E14 - The Boy Next Door SDTV.mp4"],
  ["ALF-The-Complete-Series", "ALF THE SERIES - S02E15 - Alf/ /ALF Can I Get a Witness SDTV",
    "Alf/Season 02/ALF - S02E15 - Can I Get a Witness SDTV.mp4"],
  ["ALF-The-Complete-Series", "ALF THE SERIES - S02E16 - Alf/ /ALF We're So Sorry, Uncle Albert SDTV",
    "Alf/Season 02/ALF - S02E16 - We're So Sorry, Uncle Albert SDTV.mp4"],
  ["ALF-The-Complete-Series", "ALF THE SERIES - S02E17 - Alf/ /ALF Someone to Watch Over Me (1) SDTV",
    "Alf/Season 02/ALF - S02E17 - Someone to Watch Over Me (1) SDTV.mp4"],
  ["ALF-The-Complete-Series", "ALF THE SERIES - S02E18 - Alf/ /ALF Someone to Watch Over Me (2) SDTV",
    "Alf/Season 02/ALF - S02E18 - Someone to Watch Over Me (2) SDTV.mp4"],
  ["ALF-The-Complete-Series", "ALF THE SERIES - S02E19 - Alf/ /ALF We Gotta Get Out of This Place SDTV",
    "Alf/Season 02/ALF - S02E19 - We Gotta Get Out of This Place SDTV.mp4"],
  ["ALF-The-Complete-Series", "ALF THE SERIES - S02E20 - Alf/ /ALF You Ain't Nothin' but a Hound Dog SDTV",
    "Alf/Season 02/ALF - S02E20 - You Ain't Nothin' but a Hound Dog SDTV.mp4"],
  ["ALF-The-Complete-Series", "ALF THE SERIES - S02E21 - Alf/ /ALF Hit Me with Your Best Shot SDTV",
    "Alf/Season 02/ALF - S02E21 - Hit Me with Your Best Shot SDTV.mp4"],
  ["ALF-The-Complete-Series", "ALF THE SERIES - S02E22 - Alf/ /ALF Movin' Out SDTV",
    "Alf/Season 02/ALF - S02E22 - Movin' Out SDTV.mp4"],
  ["ALF-The-Complete-Series", "ALF THE SERIES - S02E23 - Alf/ /ALF I'm Your Puppet SDTV",
    "Alf/Season 02/ALF - S02E23 - I'm Your Puppet SDTV.mp4"],
  ["ALF-The-Complete-Series", "ALF THE SERIES - S02E24 - Alf/ /ALF Tequila SDTV",
    "Alf/Season 02/ALF - S02E24 - Tequila SDTV.mp4"],
  ["ALF-The-Complete-Series", "ALF THE SERIES - S02E25 - Alf/ /ALF We Are Family SDTV",
    "Alf/Season 02/ALF - S02E25 - We Are Family SDTV.mp4"],
  ["ALF-The-Complete-Series", "ALF THE SERIES - S02E26 - Alf/ /ALF Varsity Drag SDTV",
    "Alf/Season 02/ALF - S02E26 - Varsity Drag SDTV.mp4"],
  ["ALF-The-Complete-Series", "ALF THE SERIES - S03E01 - Alf/ /ALF Stop in the Name of Love SDTV",
    "Alf/Season 03/ALF - S03E01 - Stop in the Name of Love SDTV.mp4"],
  ["ALF-The-Complete-Series", "ALF THE SERIES - S03E02 - Alf/ /ALF Stairway to Heaven SDTV",
    "Alf/Season 03/ALF - S03E02 - Stairway to Heaven SDTV.mp4"],
  ["ALF-The-Complete-Series", "ALF THE SERIES - S03E03 - Alf/ /ALF Breaking up is Hard to Do SDTV",
    "Alf/Season 03/ALF - S03E03 - Breaking up is Hard to Do SDTV.mp4"],
  ["ALF-The-Complete-Series", "ALF THE SERIES - S03E04 - Alf/ /ALF Tonight, Tonight (1) SDTV",
    "Alf/Season 03/ALF - S03E04 - Tonight, Tonight (1) SDTV.mp4"],
  ["ALF-The-Complete-Series", "ALF THE SERIES - S03E05 - Alf/ /ALF Tonight, Tonight (2) SDTV",
    "Alf/Season 03/ALF - S03E05 - Tonight, Tonight (2) SDTV.mp4"],
  ["ALF-The-Complete-Series", "ALF THE SERIES - S03E06 - Alf/ /ALF Promises, Promises SDTV",
    "Alf/Season 03/ALF - S03E06 - Promises, Promises SDTV.mp4"],
  ["ALF-The-Complete-Series", "ALF THE SERIES - S03E07 - Alf/ /ALF Turkey in the Straw (1) SDTV",
    "Alf/Season 03/ALF - S03E07 - Turkey in the Straw (1) SDTV.mp4"],
  ["ALF-The-Complete-Series", "ALF THE SERIES - S03E08 - Alf/ /ALF Turkey in the Straw (2) SDTV",
    "Alf/Season 03/ALF - S03E08 - Turkey in the Straw (2) SDTV.mp4"],
  ["ALF-The-Complete-Series", "ALF THE SERIES - S03E09 - Alf/ /ALF Changes SDTV",
    "Alf/Season 03/ALF - S03E09 - Changes SDTV.mp4"],
  ["ALF-The-Complete-Series", "ALF THE SERIES - S03E10 - Alf/ /ALF My Back Pages SDTV",
    "Alf/Season 03/ALF - S03E10 - My Back Pages SDTV.mp4"],
  ["ALF-The-Complete-Series", "ALF THE SERIES - S03E11 - Alf/ /ALF Alone Again, Naturally SDTV",
    "Alf/Season 03/ALF - S03E11 - Alone Again, Naturally SDTV.mp4"],
  ["ALF-The-Complete-Series", "ALF THE SERIES - S03E12 - Alf/ /ALF Do You Believe in Magic SDTV",
    "Alf/Season 03/ALF - S03E12 - Do You Believe in Magic SDTV.mp4"],
  ["ALF-The-Complete-Series", "ALF THE SERIES - S03E13 - Alf/ /ALF Hide Away SDTV",
    "Alf/Season 03/ALF - S03E13 - Hide Away SDTV.mp4"],
  ["ALF-The-Complete-Series", "ALF THE SERIES - S03E14 - Alf/ /ALF Fight Back SDTV",
    "Alf/Season 03/ALF - S03E14 - Fight Back SDTV.mp4"],
  ["ALF-The-Complete-Series", "ALF THE SERIES - S03E15 - Alf/ /ALF Suspicious Minds SDTV",
    "Alf/Season 03/ALF - S03E15 - Suspicious Minds SDTV.mp4"],
  ["ALF-The-Complete-Series", "ALF THE SERIES - S03E16 - Alf/ /ALF Baby Love SDTV",
    "Alf/Season 03/ALF - S03E16 - Baby Love SDTV.mp4"],
  ["ALF-The-Complete-Series", "ALF THE SERIES - S03E17 - Alf/ /ALF Running Scared SDTV",
    "Alf/Season 03/ALF - S03E17 - Running Scared SDTV.mp4"],
  ["ALF-The-Complete-Series", "ALF THE SERIES - S03E18 - Alf/ /ALF Standing in the Shadows of Love SDTV",
    "Alf/Season 03/ALF - S03E18 - Standing in the Shadows of Love SDTV.mp4"],
  ["ALF-The-Complete-Series", "ALF THE SERIES - S03E19 - Alf/ /ALF Superstition SDTV",
    "Alf/Season 03/ALF - S03E19 - Superstition SDTV.mp4"],
  ["ALF-The-Complete-Series", "ALF THE SERIES - S03E20 - Alf/ /ALF Torn Between Two Lovers SDTV",
    "Alf/Season 03/ALF - S03E20 - Torn Between Two Lovers SDTV.mp4"],
  ["ALF-The-Complete-Series", "ALF THE SERIES - S03E21 - Alf/ /ALF Funeral for a Friend SDTV",
    "Alf/Season 03/ALF - S03E21 - Funeral for a Friend SDTV.mp4"],
  ["ALF-The-Complete-Series", "ALF THE SERIES - S03E22 - Alf/ /ALF Don't Be Afraid of the Dark SDTV",
    "Alf/Season 03/ALF - S03E22 - Don't Be Afraid of the Dark SDTV.mp4"],
  ["ALF-The-Complete-Series", "ALF THE SERIES - S03E23 - Alf/ /ALF Have You Seen Your Mother, Baby SDTV",
    "Alf/Season 03/ALF - S03E23 - Have You Seen Your Mother, Baby SDTV.mp4"],
  ["ALF-The-Complete-Series", "ALF THE SERIES - S03E24 - Alf/ /ALF Like an Old Time Movie SDTV",
    "Alf/Season 03/ALF - S03E24 - Like an Old Time Movie SDTV.mp4"],
  ["ALF-The-Complete-Series", "ALF THE SERIES - S03E25 - Alf/ /ALF Shake, Rattle and Roll SDTV",
    "Alf/Season 03/ALF - S03E25 - Shake, Rattle and Roll SDTV.mp4"],
  ["ALF-The-Complete-Series", "ALF THE SERIES - S03E26 - Alf/ /ALF Having My Baby SDTV",
    "Alf/Season 03/ALF - S03E26 - Having My Baby SDTV.mp4"],
  ["ALF-The-Complete-Series", "ALF THE SERIES - S04E01 - Alf/ /ALF Baby, Come Back SDTV",
    "Alf/Season 04/ALF - S04E01 - Baby, Come Back SDTV.mp4"],
  ["ALF-The-Complete-Series", "ALF THE SERIES - S04E02 - Alf/ /ALF Lies SDTV",
    "Alf/Season 04/ALF - S04E02 - Lies SDTV.mp4"],
  ["ALF-The-Complete-Series", "ALF THE SERIES - S04E03 - Alf/ /ALF Wanted Dead or Alive SDTV",
    "Alf/Season 04/ALF - S04E03 - Wanted - Dead or Alive SDTV.mp4"],
  ["ALF-The-Complete-Series", "ALF THE SERIES - S04E04 - Alf/ /ALF We're in the Money SDTV",
    "Alf/Season 04/ALF - S04E04 - We're in the Money SDTV.mp4"],
  ["ALF-The-Complete-Series", "ALF THE SERIES - S04E05 - Alf/ /ALF Mind Games SDTV",
    "Alf/Season 04/ALF - S04E05 - Mind Games SDTV.mp4"],
  ["ALF-The-Complete-Series", "ALF THE SERIES - S04E06 - Alf/ /ALF Hooked on a Feeling SDTV",
    "Alf/Season 04/ALF - S04E06 - Hooked on a Feeling SDTV.mp4"],
  ["ALF-The-Complete-Series", "ALF THE SERIES - S04E07 - Alf/ /ALF He Ain't Heavy, He's Willie's Brother SDTV",
    "Alf/Season 04/ALF - S04E07 - He Ain't Heavy, He's Willie's Brother SDTV.mp4"],
  ["ALF-The-Complete-Series", "ALF THE SERIES - S04E08 - Alf/ /ALF The First Time Ever I Saw Your Face SDTV",
    "Alf/Season 04/ALF - S04E08 - The First Time Ever I Saw Your Face SDTV.mp4"],
  ["ALF-The-Complete-Series", "ALF THE SERIES - S04E09 - Alf/ /ALF Live and Let Die SDTV",
    "Alf/Season 04/ALF - S04E09 - Live and Let Die SDTV.mp4"],
  ["ALF-The-Complete-Series", "ALF THE SERIES - S04E10 - Alf/ /ALF Break Up to Make Up SDTV",
    "Alf/Season 04/ALF - S04E10 - Break Up to Make Up SDTV.mp4"],
  ["ALF-The-Complete-Series", "ALF THE SERIES - S04E11 - Alf/ /ALF Happy Together SDTV",
    "Alf/Season 04/ALF - S04E11 - Happy Together SDTV.mp4"],
  ["ALF-The-Complete-Series", "ALF THE SERIES - S04E12 - Alf/ /ALF Fever SDTV",
    "Alf/Season 04/ALF - S04E12 - Fever SDTV.mp4"],
  ["ALF-The-Complete-Series", "ALF THE SERIES - S04E13 - Alf/ /ALF It's My Party SDTV",
    "Alf/Season 04/ALF - S04E13 - It's My Party SDTV.mp4"],
  ["ALF-The-Complete-Series", "ALF THE SERIES - S04E14 - Alf/ /ALF Make 'em Laugh SDTV",
    "Alf/Season 04/ALF - S04E14 - Make 'em Laugh SDTV.mp4"],
  ["ALF-The-Complete-Series", "ALF THE SERIES - S04E15 - Alf/ /ALF Love on the Rocks SDTV",
    "Alf/Season 04/ALF - S04E15 - Love on the Rocks SDTV.mp4"],
  ["ALF-The-Complete-Series", "ALF THE SERIES - S04E16 - Alf/ /ALF True Colors SDTV",
    "Alf/Season 04/ALF - S04E16 - True Colors SDTV.mp4"],
  ["ALF-The-Complete-Series", "ALF THE SERIES - S04E17 - Alf/ /ALF Gimme That Old Time Religion SDTV",
    "Alf/Season 04/ALF - S04E17 - Gimme That Old Time Religion SDTV.mp4"],
  ["ALF-The-Complete-Series", "ALF THE SERIES - S04E18 - Alf/ /ALF Future's So Bright, I Gotta Wear Shades SDTV",
    "Alf/Season 04/ALF - S04E18 - Future's So Bright, I Gotta Wear Shades SDTV.mp4"],
  ["ALF-The-Complete-Series", "ALF THE SERIES - S04E19 - Alf/ /ALF When I'm Sixty Four SDTV",
    "Alf/Season 04/ALF - S04E19 - When I'm Sixty-Four SDTV.mp4"],
  ["ALF-The-Complete-Series", "ALF THE SERIES - S04E20 - Alf/ /ALF Mr. Sandman SDTV",
    "Alf/Season 04/ALF - S04E20 - Mr. Sandman SDTV.mp4"],
  ["ALF-The-Complete-Series", "ALF THE SERIES - S04E21 - Alf/ /ALF Stayin' Alive SDTV",
    "Alf/Season 04/ALF - S04E21 - Stayin' Alive SDTV.mp4"],
  ["ALF-The-Complete-Series", "ALF THE SERIES - S04E22 - Alf/ /ALF Hungry Like a Wolf SDTV",
    "Alf/Season 04/ALF - S04E22 - Hungry Like a Wolf SDTV.mp4"],
  ["ALF-The-Complete-Series", "ALF THE SERIES - S04E23 - Alf/ /ALF I Gotta Be Me SDTV",
    "Alf/Season 04/ALF - S04E23 - I Gotta Be Me SDTV.mp4"],
  ["ALF-The-Complete-Series", "ALF THE SERIES - S04E24 - Alf/ /ALF Consider Me Gone SDTV",
    "Alf/Season 04/ALF - S04E24 - Consider Me Gone SDTV.mp4"],
],
  durations: {
  "ALF-The-Complete-Series::Alf/Specials/ALF - S00E01 - Pilot (Unaired) SDTV.mp4": 1432,
  "ALF-The-Complete-Series::Alf/Specials/ALF - S00E02 - Project - ALF SDTV.mp4": 5513,
  "ALF-The-Complete-Series::Alf/Season 01/ALF - S01E01 - A.L.F SDTV.mp4": 1455,
  "ALF-The-Complete-Series::Alf/Season 01/ALF - S01E02 - Strangers in the Night SDTV.mp4": 1485,
  "ALF-The-Complete-Series::Alf/Season 01/ALF - S01E03 - Looking for Lucky SDTV.mp4": 1425,
  "ALF-The-Complete-Series::Alf/Season 01/ALF - S01E04 - Pennsylvania 6-5000 SDTV.mp4": 1483,
  "ALF-The-Complete-Series::Alf/Season 01/ALF - S01E05 - Keepin' the Faith SDTV.mp4": 1484,
  "ALF-The-Complete-Series::Alf/Season 01/ALF - S01E06 - For Your Eyes Only SDTV.mp4": 1412,
  "ALF-The-Complete-Series::Alf/Season 01/ALF - S01E07 - Help Me, Rhonda SDTV.mp4": 1485,
  "ALF-The-Complete-Series::Alf/Season 01/ALF - S01E08 - Don't It Make My Brown Eyes Blue SDTV.mp4": 1481,
  "ALF-The-Complete-Series::Alf/Season 01/ALF - S01E09 - Jump SDTV.mp4": 1487,
  "ALF-The-Complete-Series::Alf/Season 01/ALF - S01E10 - Baby, You Can Drive My Car SDTV.mp4": 1485,
  "ALF-The-Complete-Series::Alf/Season 01/ALF - S01E11 - On the Road Again SDTV.mp4": 1425,
  "ALF-The-Complete-Series::Alf/Season 01/ALF - S01E12 - Oh, Tannerbaum SDTV.mp4": 1485,
  "ALF-The-Complete-Series::Alf/Season 01/ALF - S01E13 - Mother and Child Reunion SDTV.mp4": 1483,
  "ALF-The-Complete-Series::Alf/Season 01/ALF - S01E14 - A Little Bit of Soap SDTV.mp4": 1476,
  "ALF-The-Complete-Series::Alf/Season 01/ALF - S01E15 - I've Got a New Attitude SDTV.mp4": 1485,
  "ALF-The-Complete-Series::Alf/Season 01/ALF - S01E16-E17 - Try to Remember SDTV.mp4": 2893,
  "ALF-The-Complete-Series::Alf/Season 01/ALF - S01E18 - Border Song SDTV.mp4": 1486,
  "ALF-The-Complete-Series::Alf/Season 01/ALF - S01E19 - Wild Thing SDTV.mp4": 1485,
  "ALF-The-Complete-Series::Alf/Season 01/ALF - S01E20 - Going Out of My Head Over You SDTV.mp4": 1466,
  "ALF-The-Complete-Series::Alf/Season 01/ALF - S01E21 - Lookin' Through the Windows SDTV.mp4": 1486,
  "ALF-The-Complete-Series::Alf/Season 01/ALF - S01E22 - It's Not Easy Being Green SDTV.mp4": 1485,
  "ALF-The-Complete-Series::Alf/Season 01/ALF - S01E23 - The Gambler SDTV.mp4": 1476,
  "ALF-The-Complete-Series::Alf/Season 01/ALF - S01E24 - Weird Science SDTV.mp4": 1476,
  "ALF-The-Complete-Series::Alf/Season 01/ALF - S01E25 - La Cucaracha SDTV.mp4": 1468,
  "ALF-The-Complete-Series::Alf/Season 01/ALF - S01E26 - Come Fly with Me SDTV.mp4": 1476,
  "ALF-The-Complete-Series::Alf/Season 02/ALF - S02E01 - Working My Way Back to You SDTV.mp4": 1468,
  "ALF-The-Complete-Series::Alf/Season 02/ALF - S02E02 - Somewhere Over the Rerun (aka The Ballad of Gilligan's Island) SDTV.mp4": 1294,
  "ALF-The-Complete-Series::Alf/Season 02/ALF - S02E03 - Take a Look at Me Now SDTV.mp4": 1480,
  "ALF-The-Complete-Series::Alf/Season 02/ALF - S02E04 - Wedding Bell Blues SDTV.mp4": 1437,
  "ALF-The-Complete-Series::Alf/Season 02/ALF - S02E05 - Prime Time SDTV.mp4": 1456,
  "ALF-The-Complete-Series::Alf/Season 02/ALF - S02E06 - Some Enchanted Evening SDTV.mp4": 1447,
  "ALF-The-Complete-Series::Alf/Season 02/ALF - S02E07 - Oh, Pretty Woman SDTV.mp4": 1486,
  "ALF-The-Complete-Series::Alf/Season 02/ALF - S02E08 - Something's Wrong with Me SDTV.mp4": 1488,
  "ALF-The-Complete-Series::Alf/Season 02/ALF - S02E09 - Night Train SDTV.mp4": 1488,
  "ALF-The-Complete-Series::Alf/Season 02/ALF - S02E10 - Isn't It Romantic SDTV.mp4": 1447,
  "ALF-The-Complete-Series::Alf/Season 02/ALF - S02E11 - Hail to the Chief SDTV.mp4": 1489,
  "ALF-The-Complete-Series::Alf/Season 02/ALF - S02E12-E13 - ALF's Special Christmas SDTV.mp4": 2912,
  "ALF-The-Complete-Series::Alf/Season 02/ALF - S02E14 - The Boy Next Door SDTV.mp4": 1469,
  "ALF-The-Complete-Series::Alf/Season 02/ALF - S02E15 - Can I Get a Witness SDTV.mp4": 1487,
  "ALF-The-Complete-Series::Alf/Season 02/ALF - S02E16 - We're So Sorry, Uncle Albert SDTV.mp4": 1489,
  "ALF-The-Complete-Series::Alf/Season 02/ALF - S02E17 - Someone to Watch Over Me (1) SDTV.mp4": 1487,
  "ALF-The-Complete-Series::Alf/Season 02/ALF - S02E18 - Someone to Watch Over Me (2) SDTV.mp4": 1467,
  "ALF-The-Complete-Series::Alf/Season 02/ALF - S02E19 - We Gotta Get Out of This Place SDTV.mp4": 1486,
  "ALF-The-Complete-Series::Alf/Season 02/ALF - S02E20 - You Ain't Nothin' but a Hound Dog SDTV.mp4": 1467,
  "ALF-The-Complete-Series::Alf/Season 02/ALF - S02E21 - Hit Me with Your Best Shot SDTV.mp4": 1467,
  "ALF-The-Complete-Series::Alf/Season 02/ALF - S02E22 - Movin' Out SDTV.mp4": 1487,
  "ALF-The-Complete-Series::Alf/Season 02/ALF - S02E23 - I'm Your Puppet SDTV.mp4": 1473,
  "ALF-The-Complete-Series::Alf/Season 02/ALF - S02E24 - Tequila SDTV.mp4": 1476,
  "ALF-The-Complete-Series::Alf/Season 02/ALF - S02E25 - We Are Family SDTV.mp4": 1426,
  "ALF-The-Complete-Series::Alf/Season 02/ALF - S02E26 - Varsity Drag SDTV.mp4": 1459,
  "ALF-The-Complete-Series::Alf/Season 03/ALF - S03E01 - Stop in the Name of Love SDTV.mp4": 1459,
  "ALF-The-Complete-Series::Alf/Season 03/ALF - S03E02 - Stairway to Heaven SDTV.mp4": 1458,
  "ALF-The-Complete-Series::Alf/Season 03/ALF - S03E03 - Breaking up is Hard to Do SDTV.mp4": 1457,
  "ALF-The-Complete-Series::Alf/Season 03/ALF - S03E04 - Tonight, Tonight (1) SDTV.mp4": 1534,
  "ALF-The-Complete-Series::Alf/Season 03/ALF - S03E05 - Tonight, Tonight (2) SDTV.mp4": 1440,
  "ALF-The-Complete-Series::Alf/Season 03/ALF - S03E06 - Promises, Promises SDTV.mp4": 1457,
  "ALF-The-Complete-Series::Alf/Season 03/ALF - S03E07 - Turkey in the Straw (1) SDTV.mp4": 1456,
  "ALF-The-Complete-Series::Alf/Season 03/ALF - S03E08 - Turkey in the Straw (2) SDTV.mp4": 1394,
  "ALF-The-Complete-Series::Alf/Season 03/ALF - S03E09 - Changes SDTV.mp4": 1454,
  "ALF-The-Complete-Series::Alf/Season 03/ALF - S03E10 - My Back Pages SDTV.mp4": 1406,
  "ALF-The-Complete-Series::Alf/Season 03/ALF - S03E11 - Alone Again, Naturally SDTV.mp4": 1436,
  "ALF-The-Complete-Series::Alf/Season 03/ALF - S03E12 - Do You Believe in Magic SDTV.mp4": 1426,
  "ALF-The-Complete-Series::Alf/Season 03/ALF - S03E13 - Hide Away SDTV.mp4": 1406,
  "ALF-The-Complete-Series::Alf/Season 03/ALF - S03E14 - Fight Back SDTV.mp4": 1396,
  "ALF-The-Complete-Series::Alf/Season 03/ALF - S03E15 - Suspicious Minds SDTV.mp4": 1425,
  "ALF-The-Complete-Series::Alf/Season 03/ALF - S03E16 - Baby Love SDTV.mp4": 1416,
  "ALF-The-Complete-Series::Alf/Season 03/ALF - S03E17 - Running Scared SDTV.mp4": 1446,
  "ALF-The-Complete-Series::Alf/Season 03/ALF - S03E18 - Standing in the Shadows of Love SDTV.mp4": 1406,
  "ALF-The-Complete-Series::Alf/Season 03/ALF - S03E19 - Superstition SDTV.mp4": 1396,
  "ALF-The-Complete-Series::Alf/Season 03/ALF - S03E20 - Torn Between Two Lovers SDTV.mp4": 1445,
  "ALF-The-Complete-Series::Alf/Season 03/ALF - S03E21 - Funeral for a Friend SDTV.mp4": 1396,
  "ALF-The-Complete-Series::Alf/Season 03/ALF - S03E22 - Don't Be Afraid of the Dark SDTV.mp4": 1396,
  "ALF-The-Complete-Series::Alf/Season 03/ALF - S03E23 - Have You Seen Your Mother, Baby SDTV.mp4": 1396,
  "ALF-The-Complete-Series::Alf/Season 03/ALF - S03E24 - Like an Old Time Movie SDTV.mp4": 1415,
  "ALF-The-Complete-Series::Alf/Season 03/ALF - S03E25 - Shake, Rattle and Roll SDTV.mp4": 1397,
  "ALF-The-Complete-Series::Alf/Season 03/ALF - S03E26 - Having My Baby SDTV.mp4": 1436,
  "ALF-The-Complete-Series::Alf/Season 04/ALF - S04E01 - Baby, Come Back SDTV.mp4": 1394,
  "ALF-The-Complete-Series::Alf/Season 04/ALF - S04E02 - Lies SDTV.mp4": 1413,
  "ALF-The-Complete-Series::Alf/Season 04/ALF - S04E03 - Wanted - Dead or Alive SDTV.mp4": 1376,
  "ALF-The-Complete-Series::Alf/Season 04/ALF - S04E04 - We're in the Money SDTV.mp4": 1414,
  "ALF-The-Complete-Series::Alf/Season 04/ALF - S04E05 - Mind Games SDTV.mp4": 1397,
  "ALF-The-Complete-Series::Alf/Season 04/ALF - S04E06 - Hooked on a Feeling SDTV.mp4": 1370,
  "ALF-The-Complete-Series::Alf/Season 04/ALF - S04E07 - He Ain't Heavy, He's Willie's Brother SDTV.mp4": 1376,
  "ALF-The-Complete-Series::Alf/Season 04/ALF - S04E08 - The First Time Ever I Saw Your Face SDTV.mp4": 1429,
  "ALF-The-Complete-Series::Alf/Season 04/ALF - S04E09 - Live and Let Die SDTV.mp4": 1429,
  "ALF-The-Complete-Series::Alf/Season 04/ALF - S04E10 - Break Up to Make Up SDTV.mp4": 1404,
  "ALF-The-Complete-Series::Alf/Season 04/ALF - S04E11 - Happy Together SDTV.mp4": 1369,
  "ALF-The-Complete-Series::Alf/Season 04/ALF - S04E12 - Fever SDTV.mp4": 1376,
  "ALF-The-Complete-Series::Alf/Season 04/ALF - S04E13 - It's My Party SDTV.mp4": 1375,
  "ALF-The-Complete-Series::Alf/Season 04/ALF - S04E14 - Make 'em Laugh SDTV.mp4": 1426,
  "ALF-The-Complete-Series::Alf/Season 04/ALF - S04E15 - Love on the Rocks SDTV.mp4": 1424,
  "ALF-The-Complete-Series::Alf/Season 04/ALF - S04E16 - True Colors SDTV.mp4": 1406,
  "ALF-The-Complete-Series::Alf/Season 04/ALF - S04E17 - Gimme That Old Time Religion SDTV.mp4": 1433,
  "ALF-The-Complete-Series::Alf/Season 04/ALF - S04E18 - Future's So Bright, I Gotta Wear Shades SDTV.mp4": 1395,
  "ALF-The-Complete-Series::Alf/Season 04/ALF - S04E19 - When I'm Sixty-Four SDTV.mp4": 1387,
  "ALF-The-Complete-Series::Alf/Season 04/ALF - S04E20 - Mr. Sandman SDTV.mp4": 1375,
  "ALF-The-Complete-Series::Alf/Season 04/ALF - S04E21 - Stayin' Alive SDTV.mp4": 1434,
  "ALF-The-Complete-Series::Alf/Season 04/ALF - S04E22 - Hungry Like a Wolf SDTV.mp4": 1406,
  "ALF-The-Complete-Series::Alf/Season 04/ALF - S04E23 - I Gotta Be Me SDTV.mp4": 1384,
  "ALF-The-Complete-Series::Alf/Season 04/ALF - S04E24 - Consider Me Gone SDTV.mp4": 1435,
},
};
