window.SHOW = {
  id: "FactsofLife",
  title: "The Facts of Life",
  art: "FactsofLife.jpg",
  storageProgressKey: "factsoflife-progress",
  storageSettingsKey: "factsoflife-settings",
  nestedPaths: true,
  grouping: "season",
  segments: "none",
  episodes: [
  ["the-facts-of-life-complete-series", "THE FACTS OF LIFE - S01E01 - Rough Housing",
    "The Facts of Life S01E01 - Rough House.ia.mp4"],
  ["the-facts-of-life-complete-series", "THE FACTS OF LIFE - S01E02 - Like Mother, Like Daughter",
    "The Facts of Life S01E02 - Like Mother, Like Daughter.ia.mp4"],
  ["the-facts-of-life-complete-series", "THE FACTS OF LIFE - S01E03 - The Return of Mr. Garrett",
    "The Facts of Life S01E03 - The Return of Mr. Garrett.ia.mp4"],
  ["the-facts-of-life-complete-series", "THE FACTS OF LIFE - S01E04 - I.Q.",
    "The Facts of Life S01E04 - I.Q..ia.mp4"],
  ["the-facts-of-life-complete-series", "THE FACTS OF LIFE - S01E05 - Overachieving",
    "The Facts of Life S01E05 - Overachieving.ia.mp4"],
  ["the-facts-of-life-complete-series", "THE FACTS OF LIFE - S01E06 - Emily Dickinson",
    "The Facts of Life S01E06 - Emily Dickinson.ia.mp4"],
  ["the-facts-of-life-complete-series", "THE FACTS OF LIFE - S01E07 - Dieting",
    "The Facts of Life S01E07 - Dieting.ia.mp4"],
  ["the-facts-of-life-complete-series", "THE FACTS OF LIFE - S01E08 - The Facts of Love",
    "The Facts of Life S01E08 - The Facts of Love.ia.mp4"],
  ["the-facts-of-life-complete-series", "THE FACTS OF LIFE - S01E09 - Flash Flood",
    "The Facts of Life S01E09 - Flash Flood.ia.mp4"],
  ["the-facts-of-life-complete-series", "THE FACTS OF LIFE - S01E10 - Adoption",
    "The Facts of Life S01E10 - Adoption.ia.mp4"],
  ["the-facts-of-life-complete-series", "THE FACTS OF LIFE - S01E11 - Running",
    "The Facts of Life S01E11 - Running.ia.mp4"],
  ["the-facts-of-life-complete-series", "THE FACTS OF LIFE - S01E12 - Molly's Holiday",
    "The Facts of Life S01E12 - Molly's Holiday.ia.mp4"],
  ["the-facts-of-life-complete-series", "THE FACTS OF LIFE - S01E13 - Dope",
    "The Facts of Life S01E13 - Dope.ia.mp4"],
  ["the-facts-of-life-complete-series", "THE FACTS OF LIFE - S02E01 - The New Girl (Part 1)",
    "The Facts of Life S02E01 - The New Girl (Part 1).ia.mp4"],
  ["the-facts-of-life-complete-series", "THE FACTS OF LIFE - S02E02 - The New Girl (Part 2)",
    "The Facts of Life S02E02 - The New Girl (Part 2).ia.mp4"],
  ["the-facts-of-life-complete-series", "THE FACTS OF LIFE - S02E03 - Double Standard",
    "The Facts of Life S02E03 - Double Standard.ia.mp4"],
  ["the-facts-of-life-complete-series", "THE FACTS OF LIFE - S02E04 - Who Am I?",
    "The Facts of Life S02E04 - Who Am I.ia.mp4"],
  ["the-facts-of-life-complete-series", "THE FACTS OF LIFE - S02E05 - Cousin Geri",
    "The Facts of Life S02E05 - Cousin Geri.ia.mp4"],
  ["the-facts-of-life-complete-series", "THE FACTS OF LIFE - S02E06 - Shoplifting",
    "The Facts of Life S02E06 - Shoplifting.ia.mp4"],
  ["the-facts-of-life-complete-series", "THE FACTS OF LIFE - S02E07 - Teenage Marriage (Part 1)",
    "The Facts of Life S02E07 - Teenage Marriage (Part 1).ia.mp4"],
  ["the-facts-of-life-complete-series", "THE FACTS OF LIFE - S02E08 - Teenage Marriage (Part 2)",
    "The Facts of Life S02E08 - Teenage Marriage (Part 2).ia.mp4"],
  ["the-facts-of-life-complete-series", "THE FACTS OF LIFE - S02E09 - Gossip",
    "The Facts of Life S02E09 - Gossip.ia.mp4"],
  ["the-facts-of-life-complete-series", "THE FACTS OF LIFE - S02E10 - Breaking Point",
    "The Facts of Life S02E10 - Breaking Point.ia.mp4"],
  ["the-facts-of-life-complete-series", "THE FACTS OF LIFE - S02E11 - Sex Symbol",
    "The Facts of Life S02E11 - Sex Symbol.ia.mp4"],
  ["the-facts-of-life-complete-series", "THE FACTS OF LIFE - S02E12 - The Secret",
    "The Facts of Life S02E12 - The Secret.ia.mp4"],
  ["the-facts-of-life-complete-series", "THE FACTS OF LIFE - S02E13 - Pretty Babies",
    "The Facts of Life S02E13 - Bought and Sold.ia.mp4"],
  ["the-facts-of-life-complete-series", "THE FACTS OF LIFE - S02E14 - Bought and Sold",
    "The Facts of Life S02E14 - Pretty Babies.ia.mp4"],
  ["the-facts-of-life-complete-series", "THE FACTS OF LIFE - S02E15 - Free Spirit",
    "The Facts of Life S02E15 - Free Spirit.ia.mp4"],
  ["the-facts-of-life-complete-series", "THE FACTS OF LIFE - S02E16 - Brian and Sylvia",
    "The Facts of Life S02E16 - Brian and Sylvia.ia.mp4"],
  ["the-facts-of-life-complete-series", "THE FACTS OF LIFE - S03E01 - Growing Pains",
    "The Facts of Life S03E01 - Growing Pains.ia.mp4"],
  ["the-facts-of-life-complete-series", "THE FACTS OF LIFE - S03E02 - Fear Strikes Back",
    "The Facts of Life S03E02 - Fear Strikes Back.ia.mp4"],
  ["the-facts-of-life-complete-series", "THE FACTS OF LIFE - S03E03 - A Baby in the House",
    "The Facts of Life S03E03 - A Baby in The House.ia.mp4"],
  ["the-facts-of-life-complete-series", "THE FACTS OF LIFE - S03E04 - A Friend in Deed",
    "The Facts of Life S03E04 - A Friend in Deed.ia.mp4"],
  ["the-facts-of-life-complete-series", "THE FACTS OF LIFE - S03E05 - Front Page",
    "The Facts of Life S03E05 - Front Page.ia.mp4"],
  ["the-facts-of-life-complete-series", "THE FACTS OF LIFE - S03E06 - Give and Take",
    "The Facts of Life S03E06 - Give and Take.ia.mp4"],
  ["the-facts-of-life-complete-series", "THE FACTS OF LIFE - S03E07 - Sweet Sorrow",
    "The Facts of Life S03E07 - Sweet Sorrow.ia.mp4"],
  ["the-facts-of-life-complete-series", "THE FACTS OF LIFE - S03E08 - From Russia with Love",
    "The Facts of Life S03E08 - From Russia with Love.ia.mp4"],
  ["the-facts-of-life-complete-series", "THE FACTS OF LIFE - S03E09 - Dear Me",
    "The Facts of Life S03E09 - Dear Me.ia.mp4"],
  ["the-facts-of-life-complete-series", "THE FACTS OF LIFE - S03E10 - Cousin Geri Returns",
    "The Facts of Life S03E10 - Cousin Geri Returns.ia.mp4"],
  ["the-facts-of-life-complete-series", "THE FACTS OF LIFE - S03E11 - Legacy",
    "The Facts of Life S03E11 - Legacy.ia.mp4"],
  ["the-facts-of-life-complete-series", "THE FACTS OF LIFE - S03E12 - Green-Eyed Monster",
    "The Facts of Life S03E12 - Green-Eyed Monster.ia.mp4"],
  ["the-facts-of-life-complete-series", "THE FACTS OF LIFE - S03E13 - The Americanization of Miko",
    "The Facts of Life S03E13 - The Americanization of Miko.ia.mp4"],
  ["the-facts-of-life-complete-series", "THE FACTS OF LIFE - S03E14 - The Marriage Brokers",
    "The Facts of Life S03E14 - The Marriage Brokers.ia.mp4"],
  ["the-facts-of-life-complete-series", "THE FACTS OF LIFE - S03E15 - Starstruck",
    "The Facts of Life S03E15 - Starstruck.ia.mp4"],
  ["the-facts-of-life-complete-series", "THE FACTS OF LIFE - S03E16 - The Four Musketeers",
    "The Facts of Life S03E16 - The Four Musketeers.ia.mp4"],
  ["the-facts-of-life-complete-series", "THE FACTS OF LIFE - S03E17 - The Affair",
    "The Facts of Life S03E17 -The Affair.ia.mp4"],
  ["the-facts-of-life-complete-series", "THE FACTS OF LIFE - S03E18 - Runaway",
    "The Facts of Life S03E18 - Runaway.ia.mp4"],
  ["the-facts-of-life-complete-series", "THE FACTS OF LIFE - S03E19 - New York, New York",
    "The Facts of Life S03E19 - New York, New York.ia.mp4"],
  ["the-facts-of-life-complete-series", "THE FACTS OF LIFE - S03E20 - Kids Can Be Cruel",
    "The Facts of Life S03E20 - Kids Can be Cruel.ia.mp4"],
  ["the-facts-of-life-complete-series", "THE FACTS OF LIFE - S03E21 - Mind Your Own Business",
    "The Facts of Life S03E21 - Mind Your Own Business.ia.mp4"],
  ["the-facts-of-life-complete-series", "THE FACTS OF LIFE - S03E22 - The Academy",
    "The Facts of Life S03E22 - The Academy.ia.mp4"],
  ["the-facts-of-life-complete-series", "THE FACTS OF LIFE - S03E23 - Jo's Cousin",
    "The Facts of Life S03E23 - Jo's Cousin.ia.mp4"],
  ["the-facts-of-life-complete-series", "THE FACTS OF LIFE - S03E24 - Read No Evil",
    "The Facts of Life S03E24 - Read No Evil.ia.mp4"],
  ["the-facts-of-life-complete-series", "THE FACTS OF LIFE - S04E01 - Ain't Miss Beholden",
    "The Facts of Life S04E01 - Ain't Miss Beholden.ia.mp4"],
  ["the-facts-of-life-complete-series", "THE FACTS OF LIFE - S04E02 - The Source",
    "The Facts of Life S04E02 - The Source.ia.mp4"],
  ["the-facts-of-life-complete-series", "THE FACTS OF LIFE - S04E03 - The Sound of Silence",
    "The Facts of Life S04E03 - The Sounds of Silence.ia.mp4"],
  ["the-facts-of-life-complete-series", "THE FACTS OF LIFE - S04E04 - The Oldest Living Graduate",
    "The Facts of Life S04E04 - The Oldest Living Graduate.ia.mp4"],
  ["the-facts-of-life-complete-series", "THE FACTS OF LIFE - S04E05 - Different Drummer",
    "The Facts of Life S04E05 - Different Drummer.ia.mp4"],
  ["the-facts-of-life-complete-series", "THE FACTS OF LIFE - S04E06 - Dearest Mommie",
    "The Facts of Life S04E06 - Dearest Mommie.ia.mp4"],
  ["the-facts-of-life-complete-series", "THE FACTS OF LIFE - S04E07 - A Woman's Place",
    "The Facts of Life S04E07 - A Woman's Place.ia.mp4"],
  ["the-facts-of-life-complete-series", "THE FACTS OF LIFE - S04E08 - Daddy's Girl",
    "The Facts of Life S04E08 - Daddy's Girl.ia.mp4"],
  ["the-facts-of-life-complete-series", "THE FACTS OF LIFE - S04E09 - The Big Fight",
    "The Facts of Life S04E09 - Academy II.ia.mp4"],
  ["the-facts-of-life-complete-series", "THE FACTS OF LIFE - S04E10 - For the Asking",
    "The Facts of Life S04E10 - For The Asking.ia.mp4"],
  ["the-facts-of-life-complete-series", "THE FACTS OF LIFE - S04E11 - September Song",
    "The Facts of Life S04E11 - September Song.ia.mp4"],
  ["the-facts-of-life-complete-series", "THE FACTS OF LIFE - S04E12 - A Royal Pain",
    "The Facts of Life S04E12 - A Royal Pain.ia.mp4"],
  ["the-facts-of-life-complete-series", "THE FACTS OF LIFE - S04E13 - Magnificent Obsession",
    "The Facts of Life S04E13 - Magnificent Obsession.ia.mp4"],
  ["the-facts-of-life-complete-series", "THE FACTS OF LIFE - S04E14 - Under Pressure",
    "The Facts of Life S04E14 - Under Pressure.ia.mp4"],
  ["the-facts-of-life-complete-series", "THE FACTS OF LIFE - S04E15 - Teacher's Pet",
    "The Facts of Life S04E15 - Teacher's Pet.ia.mp4"],
  ["the-facts-of-life-complete-series", "THE FACTS OF LIFE - S04E16 - Let's Party!",
    "The Facts of Life S04E16 Let's Party.ia.mp4"],
  ["the-facts-of-life-complete-series", "THE FACTS OF LIFE - S04E17 - Best Sister (Part 1)",
    "The Facts of Life S04E17 - The Best Sister (Part 1).ia.mp4"],
  ["the-facts-of-life-complete-series", "THE FACTS OF LIFE - S04E18 - Best Sister (Part 2)",
    "The Facts of Life S04E18 - The Best Sister (Part 2).ia.mp4"],
  ["the-facts-of-life-complete-series", "THE FACTS OF LIFE - S04E19 - Guess Who's Coming to Dinner",
    "The Facts of Life S04E19 - Guess Who's Coming to Dinner.ia.mp4"],
  ["the-facts-of-life-complete-series", "THE FACTS OF LIFE - S04E20 - Who's on First?",
    "The Facts of Life S04E20 - Who's on First.ia.mp4"],
  ["the-facts-of-life-complete-series", "THE FACTS OF LIFE - S04E21 - Help from Home",
    "The Facts of Life S04E21 - Help from Home.ia.mp4"],
  ["the-facts-of-life-complete-series", "THE FACTS OF LIFE - S04E22 - Take My Finals, Please",
    "The Facts of Life S04E22 - Take My Finals, Please.ia.mp4"],
  ["the-facts-of-life-complete-series", "THE FACTS OF LIFE - S04E23 - Graduation",
    "The Facts of Life S04E23 & E24 - Graduation.ia.mp4"],
  ["the-facts-of-life-complete-series", "THE FACTS OF LIFE - S05E01 - Brave New World (1)",
    "The Facts of Life S05E01 & E02 - Brave New World.ia.mp4"],
  ["the-facts-of-life-complete-series", "THE FACTS OF LIFE - S05E03 - Gamma Gamma or Bust",
    "The Facts of Life S05E03 - Gamma Gamma.ia.mp4"],
  ["the-facts-of-life-complete-series", "THE FACTS OF LIFE - S05E04 - Just My Bill",
    "The Facts of Life S05E04 - Just My Bill.ia.mp4"],
  ["the-facts-of-life-complete-series", "THE FACTS OF LIFE - S05E05 - What Price Glory?",
    "The Facts of Life S05E05 - What Price Glory.ia.mp4"],
  ["the-facts-of-life-complete-series", "THE FACTS OF LIFE - S05E06 - The Halloween Show",
    "The Facts of Life S05E06 - Halloween.ia.mp4"],
  ["the-facts-of-life-complete-series", "THE FACTS OF LIFE - S05E07 - Advance Placement",
    "The Facts of Life S05E07 - Advanced Placement.ia.mp4"],
  ["the-facts-of-life-complete-series", "THE FACTS OF LIFE - S05E08 - I'm Dancing as Fast as I Can",
    "The Facts of Life S05E08 - I'm Dancin' as Fast as I Can.ia.mp4"],
  ["the-facts-of-life-complete-series", "THE FACTS OF LIFE - S05E09 - Small But Dangerous",
    "The Facts of Life S05E09 - Small But Dangerous.ia.mp4"],
  ["the-facts-of-life-complete-series", "THE FACTS OF LIFE - S05E10 - Store Games",
    "The Facts of Life S05E10 - Store Games.ia.mp4"],
  ["the-facts-of-life-complete-series", "THE FACTS OF LIFE - S05E11 - The Second Time Around",
    "The Facts of Life S05E11 - The Second Time Around.ia.mp4"],
  ["the-facts-of-life-complete-series", "THE FACTS OF LIFE - S05E12 - The Christmas Show",
    "The Facts of Life S05E12 - The Christmas Show.ia.mp4"],
  ["the-facts-of-life-complete-series", "THE FACTS OF LIFE - S05E13 - The Chain Letter",
    "The Facts of Life S05E13 - The Chain Letter.ia.mp4"],
  ["the-facts-of-life-complete-series", "THE FACTS OF LIFE - S05E14 - Next Door",
    "The Facts of Life S05E14 - Next Door.ia.mp4"],
  ["the-facts-of-life-complete-series", "THE FACTS OF LIFE - S05E15 - Crossing the Line",
    "The Facts of Life S05E15 - Crossing The Line.ia.mp4"],
  ["the-facts-of-life-complete-series", "THE FACTS OF LIFE - S05E16 - All or Nothing",
    "The Facts of Life S05E16 - All or Nothing.ia.mp4"],
  ["the-facts-of-life-complete-series", "THE FACTS OF LIFE - S05E17 - A Death in the Family",
    "The Facts of Life S05E17 - A Death in The Family.ia.mp4"],
  ["the-facts-of-life-complete-series", "THE FACTS OF LIFE - S05E18 - Big Fish/Little Fish",
    "The Facts of Life S05E18 - Big Fish - Little Fish.ia.mp4"],
  ["the-facts-of-life-complete-series", "THE FACTS OF LIFE - S05E19 - Star at Langley",
    "The Facts of Life S05E19 - Star at Langley.ia.mp4"],
  ["the-facts-of-life-complete-series", "THE FACTS OF LIFE - S05E20 - Dream Marriage",
    "The Facts of Life S05E20 - Dream Marriage.ia.mp4"],
  ["the-facts-of-life-complete-series", "THE FACTS OF LIFE - S05E21 - Mother and Daughter",
    "The Facts of Life S05E21 - Mother and Daughter.ia.mp4"],
  ["the-facts-of-life-complete-series", "THE FACTS OF LIFE - S05E22 - All by Herself",
    "The Facts of Life S05E22 - All By Herself.ia.mp4"],
  ["the-facts-of-life-complete-series", "THE FACTS OF LIFE - S05E23 - Seems Like Old Times",
    "The Facts of Life S05E23 - Seems Like Old Times.ia.mp4"],
  ["the-facts-of-life-complete-series", "THE FACTS OF LIFE - S05E24 - Joint Custody",
    "The Facts of Life S05E24 - Joint Custody.ia.mp4"],
  ["the-facts-of-life-complete-series", "THE FACTS OF LIFE - S05E25 - The Way We Were (1)",
    "The Facts of Life S05E25 & E26 - The Way We Were.ia.mp4"],
  ["the-facts-of-life-complete-series", "THE FACTS OF LIFE - S06E01 - The Summer of '84",
    "The Facts of Life S06E01 - The Summer of '84.ia.mp4"],
  ["the-facts-of-life-complete-series", "THE FACTS OF LIFE - S06E02 - Slices of Life",
    "The Facts of Life S06E02 - A Slice of Life.ia.mp4"],
  ["the-facts-of-life-complete-series", "THE FACTS OF LIFE - S06E03 - Love at First Byte",
    "The Facts of Life S06E03 - Love at First Byte.ia.mp4"],
  ["the-facts-of-life-complete-series", "THE FACTS OF LIFE - S06E04 - My Boyfriend's Back",
    "The Facts of Life S06E04 - My Boyfriend's Back.ia.mp4"],
  ["the-facts-of-life-complete-series", "THE FACTS OF LIFE - S06E05 - Cruisin'",
    "The Facts of Life S06E05 - Cruisin'.ia.mp4"],
  ["the-facts-of-life-complete-series", "THE FACTS OF LIFE - S06E06 - Taking a Chance on Love (1)",
    "The Facts of Life S06E06, & E07 - Taking A Chance on Love.ia.mp4"],
  ["the-facts-of-life-complete-series", "THE FACTS OF LIFE - S06E08 - E.G.O.C. (Edna Garrett on Campus)",
    "The Facts of Life S06E08 - Edna Garrett on Campus.ia.mp4"],
  ["the-facts-of-life-complete-series", "THE FACTS OF LIFE - S06E09 - Dear Apple",
    "The Facts of Life S06E09 - Dear Apple.ia.mp4"],
  ["the-facts-of-life-complete-series", "THE FACTS OF LIFE - S06E10 - Talk, Talk, Talk",
    "The Facts of Life S06E10 - Talk, Talk, Talk.ia.mp4"],
  ["the-facts-of-life-complete-series", "THE FACTS OF LIFE - S06E11 - Smile",
    "The Facts of Life S06E11 - Smile.ia.mp4"],
  ["the-facts-of-life-complete-series", "THE FACTS OF LIFE - S06E12 - The Rich Aren't Different",
    "The Facts of Life S06E12 - The Rich Aren't Different.ia.mp4"],
  ["the-facts-of-life-complete-series", "THE FACTS OF LIFE - S06E13 - Christmas in the Big House",
    "The Facts of Life S06E13 - Christmasin The Big House).ia.mp4"],
  ["the-facts-of-life-complete-series", "THE FACTS OF LIFE - S06E14 - Me and Eleanor",
    "The Facts of Life S06E14 - Me and Eleanor.ia.mp4"],
  ["the-facts-of-life-complete-series", "THE FACTS OF LIFE - S06E15 - Working It Out",
    "The Facts of Life S06E15 - Working it Out.ia.mp4"],
  ["the-facts-of-life-complete-series", "THE FACTS OF LIFE - S06E16 - Jazzbeau",
    "The Facts of Life S06E16 - Jazzbeau.ia.mp4"],
  ["the-facts-of-life-complete-series", "THE FACTS OF LIFE - S06E17 - Two Guys from Appleton",
    "The Facts of Life S06E17 - Two Guys from Appleton.ia.mp4"],
  ["the-facts-of-life-complete-series", "THE FACTS OF LIFE - S06E18 - With a Little Help from My Friends",
    "The Facts of Life S06E18 - With A Little Help from My Friends.ia.mp4"],
  ["the-facts-of-life-complete-series", "THE FACTS OF LIFE - S06E19 - Gone with the Wind (1)",
    "The Facts of Life S06E19 - Gone with The Wind (Part 1).ia.mp4"],
  ["the-facts-of-life-complete-series", "THE FACTS OF LIFE - S06E20 - Gone with the Wind (2)",
    "The Facts of Life S06E20 - Gone with The Wind (Part 2).ia.mp4"],
  ["the-facts-of-life-complete-series", "THE FACTS OF LIFE - S06E21 - Man in the Attic",
    "The Facts of Life S06E21 - Man in The Attic.ia.mp4"],
  ["the-facts-of-life-complete-series", "THE FACTS OF LIFE - S06E22 - The Last Drive-In",
    "The Facts of Life S06E22 - The Last Drive-In.ia.mp4"],
  ["the-facts-of-life-complete-series", "THE FACTS OF LIFE - S06E23 - Sisters",
    "The Facts of Life S06E23 - Sisters.ia.mp4"],
  ["the-facts-of-life-complete-series", "THE FACTS OF LIFE - S06E24 - It's Lonely at the Top",
    "The Facts of Life S06E24 - It's Lonely at The Top.ia.mp4"],
  ["the-facts-of-life-complete-series", "THE FACTS OF LIFE - S06E25 - Bus Stop",
    "The Facts of Life S06E25 - Bus Stop.ia.mp4"],
  ["the-facts-of-life-complete-series", "THE FACTS OF LIFE - S06E26 - The Interview Show",
    "The Facts of Life S06E26 - The Interview Show.ia.mp4"],
  ["the-facts-of-life-complete-series", "THE FACTS OF LIFE - S07E01 - Out of the Fire...",
    "The Facts of Life S07E01 - Out of The Fire....ia.mp4"],
  ["the-facts-of-life-complete-series", "THE FACTS OF LIFE - S07E02 - Into the Frying Pan",
    "The Facts of Life S07E02 - Into The Frying Pan.ia.mp4"],
  ["the-facts-of-life-complete-series", "THE FACTS OF LIFE - S07E04 - Teacher, Teacher",
    "The Facts of Life S07E04 - Teacher, Teacher.ia.mp4"],
  ["the-facts-of-life-complete-series", "THE FACTS OF LIFE - S07E05 - Men for All Seasons",
    "The Facts of Life S07E05 - Men for All Seasons.ia.mp4"],
  ["the-facts-of-life-complete-series", "THE FACTS OF LIFE - S07E06 - A New Life",
    "The Facts of Life S07E06 - A New Life.ia.mp4"],
  ["the-facts-of-life-complete-series", "THE FACTS OF LIFE - S07E07 - Doo-Wah",
    "The Facts of Life S07E07 - Doo-Wah.ia.mp4"],
  ["the-facts-of-life-complete-series", "THE FACTS OF LIFE - S07E08 - Come Back to the Truck Stop, Natalie Green, Natalie Green",
    "The Facts of Life S07E08 - Truck Stop.ia.mp4"],
  ["the-facts-of-life-complete-series", "THE FACTS OF LIFE - S07E09 - Born Too Late",
    "The Facts of Life S07E09 - Born Too Late.ia.mp4"],
  ["the-facts-of-life-complete-series", "THE FACTS OF LIFE - S07E10 - 3, 2, 1",
    "The Facts of Life S07E10 - 3,2,1.ia.mp4"],
  ["the-facts-of-life-complete-series", "THE FACTS OF LIFE - S07E11 - We Get Letters",
    "The Facts of Life S07E11 - We Get Letters.ia.mp4"],
  ["the-facts-of-life-complete-series", "THE FACTS OF LIFE - S07E12 - Ballroom Dance",
    "The Facts of Life S07E12 - Ballroom Dance.ia.mp4"],
  ["the-facts-of-life-complete-series", "THE FACTS OF LIFE - S07E13 - Christmas Baby",
    "The Facts of Life S07E13 - Christmas Baby.ia.mp4"],
  ["the-facts-of-life-complete-series", "THE FACTS OF LIFE - S07E14 - Tootie Drives",
    "The Facts of Life S07E14 - Tootie Drives.ia.mp4"],
  ["the-facts-of-life-complete-series", "THE FACTS OF LIFE - S07E15 - Stake-Out Blues",
    "The Facts of Life S07E15 - Stakeout.ia.mp4"],
  ["the-facts-of-life-complete-series", "THE FACTS OF LIFE - S07E16 - The Agent",
    "The Facts of Life S07E16 - The Agent.ia.mp4"],
  ["the-facts-of-life-complete-series", "THE FACTS OF LIFE - S07E17 - The Reunion",
    "The Facts of Life S07E17 - The Reunion.ia.mp4"],
  ["the-facts-of-life-complete-series", "THE FACTS OF LIFE - S07E18 - Concentration",
    "The Facts of Life S07E18 - Concentration.ia.mp4"],
  ["the-facts-of-life-complete-series", "THE FACTS OF LIFE - S07E19 - Atlantic City",
    "The Facts of Life S07E19 - Atlantic City.ia.mp4"],
  ["the-facts-of-life-complete-series", "THE FACTS OF LIFE - S07E20 - The Lady Who Came to Dinner",
    "The Facts of Life S07E20 - The Lady Who Came to Dinner.ia.mp4"],
  ["the-facts-of-life-complete-series", "THE FACTS OF LIFE - S07E21 - The Candidate",
    "The Facts of Life S07E21 - The Candidate.ia.mp4"],
  ["the-facts-of-life-complete-series", "THE FACTS OF LIFE - S07E22 - Big Time Charlie",
    "The Facts of Life S07E22 - Big Time Charlie.ia.mp4"],
  ["the-facts-of-life-complete-series", "THE FACTS OF LIFE - S07E23 - The Graduate",
    "The Facts of Life S07E23 - The Graduate.ia.mp4"],
  ["the-facts-of-life-complete-series", "THE FACTS OF LIFE - S07E24 - The Apartment",
    "The Facts of Life S07E24 - The Apartment.ia.mp4"],
  ["the-facts-of-life-complete-series", "THE FACTS OF LIFE - S08E01 - Out of Peekskill (1)",
    "The Facts of Life S08E01 & E02 - Out of Peekskill.ia.mp4"],
  ["the-facts-of-life-complete-series", "THE FACTS OF LIFE - S08E03 - Ready or Not",
    "The Facts of Life S08E03 - Ready or Not.ia.mp4"],
  ["the-facts-of-life-complete-series", "THE FACTS OF LIFE - S08E04 - Another Room",
    "The Facts of Life S08E04 - Another Room.ia.mp4"],
  ["the-facts-of-life-complete-series", "THE FACTS OF LIFE - S08E05 - Off-Broadway Baby",
    "The Facts of Life S08E05 - Off-Broadway Baby.ia.mp4"],
  ["the-facts-of-life-complete-series", "THE FACTS OF LIFE - S08E06 - The Little Chill",
    "The Facts of Life S08E06 - The Little Chill.ia.mp4"],
  ["the-facts-of-life-complete-series", "THE FACTS OF LIFE - S08E07 - The Ratings Game",
    "The Facts of Life S08E07 - The Ratings Game.ia.mp4"],
  ["the-facts-of-life-complete-series", "THE FACTS OF LIFE - S08E08 - The Wedding Day",
    "The Facts of Life S08E08 - The Wedding Day.ia.mp4"],
  ["the-facts-of-life-complete-series", "THE FACTS OF LIFE - S08E09 - Fast Food",
    "The Facts of Life S08E09 - Fast Food.ia.mp4"],
  ["the-facts-of-life-complete-series", "THE FACTS OF LIFE - S08E10 - Where's Poppa?",
    "The Facts of Life S08E10 - Where's Poppa.ia.mp4"],
  ["the-facts-of-life-complete-series", "THE FACTS OF LIFE - S08E11 - Write and Wrong",
    "The Facts of Life S08E11 - Write and Wrong.ia.mp4"],
  ["the-facts-of-life-complete-series", "THE FACTS OF LIFE - S08E12 - Seven Little Indians",
    "The Facts of Life S08E12 - Seven Little Indians.ia.mp4"],
  ["the-facts-of-life-complete-series", "THE FACTS OF LIFE - S08E13 - The Greek Connection",
    "The Facts of Life S08E13 - The Greek Connection.ia.mp4"],
  ["the-facts-of-life-complete-series", "THE FACTS OF LIFE - S08E14 - Post-Christmas Card",
    "The Facts of Life S08E14 - Post-Christmas Card.ia.mp4"],
  ["the-facts-of-life-complete-series", "THE FACTS OF LIFE - S08E15 - A Star is Torn",
    "The Facts of Life S08E15 - A Star is Torn.ia.mp4"],
  ["the-facts-of-life-complete-series", "THE FACTS OF LIFE - S08E16 - A Winter's Tale",
    "The Facts of Life S08E16 - A Winter's Tale.ia.mp4"],
  ["the-facts-of-life-complete-series", "THE FACTS OF LIFE - S08E17 - Cupid's Revenge",
    "The Facts of Life S08E17 - Cupid's Revenge.ia.mp4"],
  ["the-facts-of-life-complete-series", "THE FACTS OF LIFE - S08E18 - 62 Pick-Up",
    "The Facts of Life S08E18 - 62 Pick-Up.ia.mp4"],
  ["the-facts-of-life-complete-series", "THE FACTS OF LIFE - S08E19 - Boy About the House",
    "The Facts of Life S08E19 - Boy About the House.ia.mp4"],
  ["the-facts-of-life-complete-series", "THE FACTS OF LIFE - S08E20 - Ex Marks the Spot",
    "The Facts of Life S08E20 - Ex Marks The Spot.ia.mp4"],
  ["the-facts-of-life-complete-series", "THE FACTS OF LIFE - S08E21 - Younger Than Springtime",
    "The Facts of Life S08E21 - Younger than Springtime.ia.mp4"],
  ["the-facts-of-life-complete-series", "THE FACTS OF LIFE - S08E22 - This is Only a Test",
    "The Facts of Life S08E22 - This is Only A Test.ia.mp4"],
  ["the-facts-of-life-complete-series", "THE FACTS OF LIFE - S08E23 - Rites of Passage (1)",
    "The Facts of Life S08E23 - Rites of Passage.ia.mp4"],
  ["the-facts-of-life-complete-series", "THE FACTS OF LIFE - S08E24 - Rites of Passage (2)",
    "The Facts of Life S08E24 - Rites of Passage Too.ia.mp4"],
  ["the-facts-of-life-complete-series", "THE FACTS OF LIFE - S09E01 - Down and Out in Malibu (1)",
    "The Facts of Life S09E01 - Down and Out in Malibu (Part 1).ia.mp4"],
  ["the-facts-of-life-complete-series", "THE FACTS OF LIFE - S09E02 - Down and Out in Malibu (2)",
    "The Facts of Life S09E02 - Down and Out in Malibu (Part 2).ia.mp4"],
  ["the-facts-of-life-complete-series", "THE FACTS OF LIFE - S09E03 - Rumor Has It",
    "The Facts of Life S09E03 - Rumor Has It.ia.mp4"],
  ["the-facts-of-life-complete-series", "THE FACTS OF LIFE - S09E04 - Before the Fall",
    "The Facts of Life S09E04 - Before The Fall.ia.mp4"],
  ["the-facts-of-life-complete-series", "THE FACTS OF LIFE - S09E05 - Sweet Charity",
    "The Facts of Life S09E05 - Sweet Charity.ia.mp4"],
  ["the-facts-of-life-complete-series", "THE FACTS OF LIFE - S09E06 - Up from Down Under",
    "The Facts of Life S09E06 - Up from Down Under.ia.mp4"],
  ["the-facts-of-life-complete-series", "THE FACTS OF LIFE - S09E07 - The More the Marrier",
    "The Facts of Life S09E07 - The More The Merrier.ia.mp4"],
  ["the-facts-of-life-complete-series", "THE FACTS OF LIFE - S09E08 - A Rose by Any Other Age",
    "The Facts of Life S09E08 - A Rose By any Other Age.ia.mp4"],
  ["the-facts-of-life-complete-series", "THE FACTS OF LIFE - S09E09 - Adventures in Baileysitting",
    "The Facts of Life S09E09 - Adventures in Baileysitting.ia.mp4"],
  ["the-facts-of-life-complete-series", "THE FACTS OF LIFE - S09E10 - It's a Wonderful Christmas",
    "The Facts of Life S09E10 - It's A Wonderful Christmas.ia.mp4"],
  ["the-facts-of-life-complete-series", "THE FACTS OF LIFE - S09E11 - Golden Oldies",
    "The Facts of Life S09E11 - Golden Oldie.ia.mp4"],
  ["the-facts-of-life-complete-series", "THE FACTS OF LIFE - S09E12 - A Thousand Frowns",
    "The Facts of Life S09E12 - A Thousand Frowns.ia.mp4"],
  ["the-facts-of-life-complete-series", "THE FACTS OF LIFE - S09E13 - Something in Common",
    "The Facts of Life S09E13 - Something in Common.ia.mp4"],
  ["the-facts-of-life-complete-series", "THE FACTS OF LIFE - S09E14 - Peekskill Law",
    "The Facts of Life S09E14 - Peekskill Law.ia.mp4"],
  ["the-facts-of-life-complete-series", "THE FACTS OF LIFE - S09E15 - A House Divided",
    "The Facts of Life S09E15 - A House Divided.ia.mp4"],
  ["the-facts-of-life-complete-series", "THE FACTS OF LIFE - S09E16 - The First Time",
    "The Facts of Life S09E16 - The First Time.ia.mp4"],
  ["the-facts-of-life-complete-series", "THE FACTS OF LIFE - S09E17 - Let's Face the Music",
    "The Facts of Life S09E17 - Let's Face The Music.ia.mp4"],
  ["the-facts-of-life-complete-series", "THE FACTS OF LIFE - S09E18 - Less Than Perfect",
    "The Facts of Life S09E18 - Less Than Perfect.ia.mp4"],
  ["the-facts-of-life-complete-series", "THE FACTS OF LIFE - S09E19 - Till Marriage Do Us Part",
    "The Facts of Life S09E19 - Till Marriage Do Us Part.ia.mp4"],
  ["the-facts-of-life-complete-series", "THE FACTS OF LIFE - S09E20 - Present Imperfect",
    "The Facts of Life S09E20 - Present Imperfect.ia.mp4"],
  ["the-facts-of-life-complete-series", "THE FACTS OF LIFE - S09E21 - On the Edge",
    "The Facts of Life S09E21 - On The Edge.ia.mp4"],
  ["the-facts-of-life-complete-series", "THE FACTS OF LIFE - S09E22 - Big Apple Blues",
    "The Facts of Life S09E22 - Big Apple Blues.ia.mp4"],
  ["the-facts-of-life-complete-series", "THE FACTS OF LIFE - S09E23 - The Beginning of the End",
    "The Facts of Life S09E23 - The Beginning of The End.ia.mp4"],
  ["the-facts-of-life-complete-series", "THE FACTS OF LIFE - S09E24 - The Beginning of the Beginning",
    "The Facts of Life S09E24 - The Beginning of The Beginning.ia.mp4"],
],
  durations: {
  "the-facts-of-life-complete-series::The Facts of Life S01E01 - Rough House.ia.mp4": 1385,
  "the-facts-of-life-complete-series::The Facts of Life S01E02 - Like Mother, Like Daughter.ia.mp4": 1460,
  "the-facts-of-life-complete-series::The Facts of Life S01E03 - The Return of Mr. Garrett.ia.mp4": 1419,
  "the-facts-of-life-complete-series::The Facts of Life S01E04 - I.Q..ia.mp4": 1463,
  "the-facts-of-life-complete-series::The Facts of Life S01E05 - Overachieving.ia.mp4": 1457,
  "the-facts-of-life-complete-series::The Facts of Life S01E06 - Emily Dickinson.ia.mp4": 1461,
  "the-facts-of-life-complete-series::The Facts of Life S01E07 - Dieting.ia.mp4": 1466,
  "the-facts-of-life-complete-series::The Facts of Life S01E08 - The Facts of Love.ia.mp4": 1460,
  "the-facts-of-life-complete-series::The Facts of Life S01E09 - Flash Flood.ia.mp4": 1460,
  "the-facts-of-life-complete-series::The Facts of Life S01E10 - Adoption.ia.mp4": 1450,
  "the-facts-of-life-complete-series::The Facts of Life S01E11 - Running.ia.mp4": 1461,
  "the-facts-of-life-complete-series::The Facts of Life S01E12 - Molly's Holiday.ia.mp4": 1461,
  "the-facts-of-life-complete-series::The Facts of Life S01E13 - Dope.ia.mp4": 1461,
  "the-facts-of-life-complete-series::The Facts of Life S02E01 - The New Girl (Part 1).ia.mp4": 1475,
  "the-facts-of-life-complete-series::The Facts of Life S02E02 - The New Girl (Part 2).ia.mp4": 1482,
  "the-facts-of-life-complete-series::The Facts of Life S02E03 - Double Standard.ia.mp4": 1485,
  "the-facts-of-life-complete-series::The Facts of Life S02E04 - Who Am I.ia.mp4": 1487,
  "the-facts-of-life-complete-series::The Facts of Life S02E05 - Cousin Geri.ia.mp4": 1486,
  "the-facts-of-life-complete-series::The Facts of Life S02E06 - Shoplifting.ia.mp4": 1486,
  "the-facts-of-life-complete-series::The Facts of Life S02E07 - Teenage Marriage (Part 1).ia.mp4": 1486,
  "the-facts-of-life-complete-series::The Facts of Life S02E08 - Teenage Marriage (Part 2).ia.mp4": 1473,
  "the-facts-of-life-complete-series::The Facts of Life S02E09 - Gossip.ia.mp4": 1487,
  "the-facts-of-life-complete-series::The Facts of Life S02E10 - Breaking Point.ia.mp4": 1487,
  "the-facts-of-life-complete-series::The Facts of Life S02E11 - Sex Symbol.ia.mp4": 1488,
  "the-facts-of-life-complete-series::The Facts of Life S02E12 - The Secret.ia.mp4": 1486,
  "the-facts-of-life-complete-series::The Facts of Life S02E13 - Bought and Sold.ia.mp4": 1465,
  "the-facts-of-life-complete-series::The Facts of Life S02E14 - Pretty Babies.ia.mp4": 1467,
  "the-facts-of-life-complete-series::The Facts of Life S02E15 - Free Spirit.ia.mp4": 1467,
  "the-facts-of-life-complete-series::The Facts of Life S02E16 - Brian and Sylvia.ia.mp4": 1466,
  "the-facts-of-life-complete-series::The Facts of Life S03E01 - Growing Pains.ia.mp4": 1511,
  "the-facts-of-life-complete-series::The Facts of Life S03E02 - Fear Strikes Back.ia.mp4": 1511,
  "the-facts-of-life-complete-series::The Facts of Life S03E03 - A Baby in The House.ia.mp4": 1512,
  "the-facts-of-life-complete-series::The Facts of Life S03E04 - A Friend in Deed.ia.mp4": 1511,
  "the-facts-of-life-complete-series::The Facts of Life S03E05 - Front Page.ia.mp4": 1481,
  "the-facts-of-life-complete-series::The Facts of Life S03E06 - Give and Take.ia.mp4": 1512,
  "the-facts-of-life-complete-series::The Facts of Life S03E07 - Sweet Sorrow.ia.mp4": 1512,
  "the-facts-of-life-complete-series::The Facts of Life S03E08 - From Russia with Love.ia.mp4": 1512,
  "the-facts-of-life-complete-series::The Facts of Life S03E09 - Dear Me.ia.mp4": 1512,
  "the-facts-of-life-complete-series::The Facts of Life S03E10 - Cousin Geri Returns.ia.mp4": 1512,
  "the-facts-of-life-complete-series::The Facts of Life S03E11 - Legacy.ia.mp4": 1512,
  "the-facts-of-life-complete-series::The Facts of Life S03E12 - Green-Eyed Monster.ia.mp4": 1512,
  "the-facts-of-life-complete-series::The Facts of Life S03E13 - The Americanization of Miko.ia.mp4": 1512,
  "the-facts-of-life-complete-series::The Facts of Life S03E14 - The Marriage Brokers.ia.mp4": 1512,
  "the-facts-of-life-complete-series::The Facts of Life S03E15 - Starstruck.ia.mp4": 1510,
  "the-facts-of-life-complete-series::The Facts of Life S03E16 - The Four Musketeers.ia.mp4": 1512,
  "the-facts-of-life-complete-series::The Facts of Life S03E17 -The Affair.ia.mp4": 1512,
  "the-facts-of-life-complete-series::The Facts of Life S03E18 - Runaway.ia.mp4": 1511,
  "the-facts-of-life-complete-series::The Facts of Life S03E19 - New York, New York.ia.mp4": 1513,
  "the-facts-of-life-complete-series::The Facts of Life S03E20 - Kids Can be Cruel.ia.mp4": 1513,
  "the-facts-of-life-complete-series::The Facts of Life S03E21 - Mind Your Own Business.ia.mp4": 1512,
  "the-facts-of-life-complete-series::The Facts of Life S03E22 - The Academy.ia.mp4": 1512,
  "the-facts-of-life-complete-series::The Facts of Life S03E23 - Jo's Cousin.ia.mp4": 1440,
  "the-facts-of-life-complete-series::The Facts of Life S03E24 - Read No Evil.ia.mp4": 1513,
  "the-facts-of-life-complete-series::The Facts of Life S04E01 - Ain't Miss Beholden.ia.mp4": 1501,
  "the-facts-of-life-complete-series::The Facts of Life S04E02 - The Source.ia.mp4": 1500,
  "the-facts-of-life-complete-series::The Facts of Life S04E03 - The Sounds of Silence.ia.mp4": 1499,
  "the-facts-of-life-complete-series::The Facts of Life S04E04 - The Oldest Living Graduate.ia.mp4": 1501,
  "the-facts-of-life-complete-series::The Facts of Life S04E05 - Different Drummer.ia.mp4": 1500,
  "the-facts-of-life-complete-series::The Facts of Life S04E06 - Dearest Mommie.ia.mp4": 1503,
  "the-facts-of-life-complete-series::The Facts of Life S04E07 - A Woman's Place.ia.mp4": 1497,
  "the-facts-of-life-complete-series::The Facts of Life S04E08 - Daddy's Girl.ia.mp4": 1499,
  "the-facts-of-life-complete-series::The Facts of Life S04E09 - Academy II.ia.mp4": 1501,
  "the-facts-of-life-complete-series::The Facts of Life S04E10 - For The Asking.ia.mp4": 1499,
  "the-facts-of-life-complete-series::The Facts of Life S04E11 - September Song.ia.mp4": 1501,
  "the-facts-of-life-complete-series::The Facts of Life S04E12 - A Royal Pain.ia.mp4": 1498,
  "the-facts-of-life-complete-series::The Facts of Life S04E13 - Magnificent Obsession.ia.mp4": 1500,
  "the-facts-of-life-complete-series::The Facts of Life S04E14 - Under Pressure.ia.mp4": 1497,
  "the-facts-of-life-complete-series::The Facts of Life S04E15 - Teacher's Pet.ia.mp4": 1499,
  "the-facts-of-life-complete-series::The Facts of Life S04E16 Let's Party.ia.mp4": 1496,
  "the-facts-of-life-complete-series::The Facts of Life S04E17 - The Best Sister (Part 1).ia.mp4": 1498,
  "the-facts-of-life-complete-series::The Facts of Life S04E18 - The Best Sister (Part 2).ia.mp4": 1499,
  "the-facts-of-life-complete-series::The Facts of Life S04E19 - Guess Who's Coming to Dinner.ia.mp4": 1497,
  "the-facts-of-life-complete-series::The Facts of Life S04E20 - Who's on First.ia.mp4": 1498,
  "the-facts-of-life-complete-series::The Facts of Life S04E21 - Help from Home.ia.mp4": 1498,
  "the-facts-of-life-complete-series::The Facts of Life S04E22 - Take My Finals, Please.ia.mp4": 1496,
  "the-facts-of-life-complete-series::The Facts of Life S04E23 & E24 - Graduation.ia.mp4": 2920,
  "the-facts-of-life-complete-series::The Facts of Life S05E01 & E02 - Brave New World.ia.mp4": 2916,
  "the-facts-of-life-complete-series::The Facts of Life S05E03 - Gamma Gamma.ia.mp4": 1498,
  "the-facts-of-life-complete-series::The Facts of Life S05E04 - Just My Bill.ia.mp4": 1502,
  "the-facts-of-life-complete-series::The Facts of Life S05E05 - What Price Glory.ia.mp4": 1500,
  "the-facts-of-life-complete-series::The Facts of Life S05E06 - Halloween.ia.mp4": 1500,
  "the-facts-of-life-complete-series::The Facts of Life S05E07 - Advanced Placement.ia.mp4": 1501,
  "the-facts-of-life-complete-series::The Facts of Life S05E08 - I'm Dancin' as Fast as I Can.ia.mp4": 1501,
  "the-facts-of-life-complete-series::The Facts of Life S05E09 - Small But Dangerous.ia.mp4": 1502,
  "the-facts-of-life-complete-series::The Facts of Life S05E10 - Store Games.ia.mp4": 1502,
  "the-facts-of-life-complete-series::The Facts of Life S05E11 - The Second Time Around.ia.mp4": 1501,
  "the-facts-of-life-complete-series::The Facts of Life S05E12 - The Christmas Show.ia.mp4": 1501,
  "the-facts-of-life-complete-series::The Facts of Life S05E13 - The Chain Letter.ia.mp4": 1502,
  "the-facts-of-life-complete-series::The Facts of Life S05E14 - Next Door.ia.mp4": 1498,
  "the-facts-of-life-complete-series::The Facts of Life S05E15 - Crossing The Line.ia.mp4": 1501,
  "the-facts-of-life-complete-series::The Facts of Life S05E16 - All or Nothing.ia.mp4": 1501,
  "the-facts-of-life-complete-series::The Facts of Life S05E17 - A Death in The Family.ia.mp4": 1503,
  "the-facts-of-life-complete-series::The Facts of Life S05E18 - Big Fish - Little Fish.ia.mp4": 1502,
  "the-facts-of-life-complete-series::The Facts of Life S05E19 - Star at Langley.ia.mp4": 1501,
  "the-facts-of-life-complete-series::The Facts of Life S05E20 - Dream Marriage.ia.mp4": 1501,
  "the-facts-of-life-complete-series::The Facts of Life S05E21 - Mother and Daughter.ia.mp4": 1501,
  "the-facts-of-life-complete-series::The Facts of Life S05E22 - All By Herself.ia.mp4": 1500,
  "the-facts-of-life-complete-series::The Facts of Life S05E23 - Seems Like Old Times.ia.mp4": 1500,
  "the-facts-of-life-complete-series::The Facts of Life S05E24 - Joint Custody.ia.mp4": 1500,
  "the-facts-of-life-complete-series::The Facts of Life S05E25 & E26 - The Way We Were.ia.mp4": 2927,
  "the-facts-of-life-complete-series::The Facts of Life S06E01 - The Summer of '84.ia.mp4": 1491,
  "the-facts-of-life-complete-series::The Facts of Life S06E02 - A Slice of Life.ia.mp4": 1490,
  "the-facts-of-life-complete-series::The Facts of Life S06E03 - Love at First Byte.ia.mp4": 1489,
  "the-facts-of-life-complete-series::The Facts of Life S06E04 - My Boyfriend's Back.ia.mp4": 1490,
  "the-facts-of-life-complete-series::The Facts of Life S06E05 - Cruisin'.ia.mp4": 1488,
  "the-facts-of-life-complete-series::The Facts of Life S06E06, & E07 - Taking A Chance on Love.ia.mp4": 2910,
  "the-facts-of-life-complete-series::The Facts of Life S06E08 - Edna Garrett on Campus.ia.mp4": 1486,
  "the-facts-of-life-complete-series::The Facts of Life S06E09 - Dear Apple.ia.mp4": 1488,
  "the-facts-of-life-complete-series::The Facts of Life S06E10 - Talk, Talk, Talk.ia.mp4": 1487,
  "the-facts-of-life-complete-series::The Facts of Life S06E11 - Smile.ia.mp4": 1490,
  "the-facts-of-life-complete-series::The Facts of Life S06E12 - The Rich Aren't Different.ia.mp4": 1489,
  "the-facts-of-life-complete-series::The Facts of Life S06E13 - Christmasin The Big House).ia.mp4": 1488,
  "the-facts-of-life-complete-series::The Facts of Life S06E14 - Me and Eleanor.ia.mp4": 1489,
  "the-facts-of-life-complete-series::The Facts of Life S06E15 - Working it Out.ia.mp4": 1489,
  "the-facts-of-life-complete-series::The Facts of Life S06E16 - Jazzbeau.ia.mp4": 1487,
  "the-facts-of-life-complete-series::The Facts of Life S06E17 - Two Guys from Appleton.ia.mp4": 1489,
  "the-facts-of-life-complete-series::The Facts of Life S06E18 - With A Little Help from My Friends.ia.mp4": 1486,
  "the-facts-of-life-complete-series::The Facts of Life S06E19 - Gone with The Wind (Part 1).ia.mp4": 1486,
  "the-facts-of-life-complete-series::The Facts of Life S06E20 - Gone with The Wind (Part 2).ia.mp4": 1489,
  "the-facts-of-life-complete-series::The Facts of Life S06E21 - Man in The Attic.ia.mp4": 1489,
  "the-facts-of-life-complete-series::The Facts of Life S06E22 - The Last Drive-In.ia.mp4": 1489,
  "the-facts-of-life-complete-series::The Facts of Life S06E23 - Sisters.ia.mp4": 1489,
  "the-facts-of-life-complete-series::The Facts of Life S06E24 - It's Lonely at The Top.ia.mp4": 1489,
  "the-facts-of-life-complete-series::The Facts of Life S06E25 - Bus Stop.ia.mp4": 1334,
  "the-facts-of-life-complete-series::The Facts of Life S06E26 - The Interview Show.ia.mp4": 1486,
  "the-facts-of-life-complete-series::The Facts of Life S07E01 - Out of The Fire....ia.mp4": 1434,
  "the-facts-of-life-complete-series::The Facts of Life S07E02 - Into The Frying Pan.ia.mp4": 1435,
  "the-facts-of-life-complete-series::The Facts of Life S07E04 - Teacher, Teacher.ia.mp4": 1434,
  "the-facts-of-life-complete-series::The Facts of Life S07E05 - Men for All Seasons.ia.mp4": 1431,
  "the-facts-of-life-complete-series::The Facts of Life S07E06 - A New Life.ia.mp4": 1435,
  "the-facts-of-life-complete-series::The Facts of Life S07E07 - Doo-Wah.ia.mp4": 1432,
  "the-facts-of-life-complete-series::The Facts of Life S07E08 - Truck Stop.ia.mp4": 1434,
  "the-facts-of-life-complete-series::The Facts of Life S07E09 - Born Too Late.ia.mp4": 1435,
  "the-facts-of-life-complete-series::The Facts of Life S07E10 - 3,2,1.ia.mp4": 1436,
  "the-facts-of-life-complete-series::The Facts of Life S07E11 - We Get Letters.ia.mp4": 1434,
  "the-facts-of-life-complete-series::The Facts of Life S07E12 - Ballroom Dance.ia.mp4": 1434,
  "the-facts-of-life-complete-series::The Facts of Life S07E13 - Christmas Baby.ia.mp4": 1435,
  "the-facts-of-life-complete-series::The Facts of Life S07E14 - Tootie Drives.ia.mp4": 1436,
  "the-facts-of-life-complete-series::The Facts of Life S07E15 - Stakeout.ia.mp4": 1435,
  "the-facts-of-life-complete-series::The Facts of Life S07E16 - The Agent.ia.mp4": 1435,
  "the-facts-of-life-complete-series::The Facts of Life S07E17 - The Reunion.ia.mp4": 1440,
  "the-facts-of-life-complete-series::The Facts of Life S07E18 - Concentration.ia.mp4": 1440,
  "the-facts-of-life-complete-series::The Facts of Life S07E19 - Atlantic City.ia.mp4": 1437,
  "the-facts-of-life-complete-series::The Facts of Life S07E20 - The Lady Who Came to Dinner.ia.mp4": 1432,
  "the-facts-of-life-complete-series::The Facts of Life S07E21 - The Candidate.ia.mp4": 1475,
  "the-facts-of-life-complete-series::The Facts of Life S07E22 - Big Time Charlie.ia.mp4": 1405,
  "the-facts-of-life-complete-series::The Facts of Life S07E23 - The Graduate.ia.mp4": 1399,
  "the-facts-of-life-complete-series::The Facts of Life S07E24 - The Apartment.ia.mp4": 1438,
  "the-facts-of-life-complete-series::The Facts of Life S08E01 & E02 - Out of Peekskill.ia.mp4": 2905,
  "the-facts-of-life-complete-series::The Facts of Life S08E03 - Ready or Not.ia.mp4": 1481,
  "the-facts-of-life-complete-series::The Facts of Life S08E04 - Another Room.ia.mp4": 1478,
  "the-facts-of-life-complete-series::The Facts of Life S08E05 - Off-Broadway Baby.ia.mp4": 1478,
  "the-facts-of-life-complete-series::The Facts of Life S08E06 - The Little Chill.ia.mp4": 1479,
  "the-facts-of-life-complete-series::The Facts of Life S08E07 - The Ratings Game.ia.mp4": 1481,
  "the-facts-of-life-complete-series::The Facts of Life S08E08 - The Wedding Day.ia.mp4": 1480,
  "the-facts-of-life-complete-series::The Facts of Life S08E09 - Fast Food.ia.mp4": 1480,
  "the-facts-of-life-complete-series::The Facts of Life S08E10 - Where's Poppa.ia.mp4": 1480,
  "the-facts-of-life-complete-series::The Facts of Life S08E11 - Write and Wrong.ia.mp4": 1478,
  "the-facts-of-life-complete-series::The Facts of Life S08E12 - Seven Little Indians.ia.mp4": 1481,
  "the-facts-of-life-complete-series::The Facts of Life S08E13 - The Greek Connection.ia.mp4": 1479,
  "the-facts-of-life-complete-series::The Facts of Life S08E14 - Post-Christmas Card.ia.mp4": 1481,
  "the-facts-of-life-complete-series::The Facts of Life S08E15 - A Star is Torn.ia.mp4": 1480,
  "the-facts-of-life-complete-series::The Facts of Life S08E16 - A Winter's Tale.ia.mp4": 1479,
  "the-facts-of-life-complete-series::The Facts of Life S08E17 - Cupid's Revenge.ia.mp4": 1481,
  "the-facts-of-life-complete-series::The Facts of Life S08E18 - 62 Pick-Up.ia.mp4": 1482,
  "the-facts-of-life-complete-series::The Facts of Life S08E19 - Boy About the House.ia.mp4": 1048,
  "the-facts-of-life-complete-series::The Facts of Life S08E20 - Ex Marks The Spot.ia.mp4": 1480,
  "the-facts-of-life-complete-series::The Facts of Life S08E21 - Younger than Springtime.ia.mp4": 1481,
  "the-facts-of-life-complete-series::The Facts of Life S08E22 - This is Only A Test.ia.mp4": 1479,
  "the-facts-of-life-complete-series::The Facts of Life S08E23 - Rites of Passage.ia.mp4": 1482,
  "the-facts-of-life-complete-series::The Facts of Life S08E24 - Rites of Passage Too.ia.mp4": 1480,
  "the-facts-of-life-complete-series::The Facts of Life S09E01 - Down and Out in Malibu (Part 1).ia.mp4": 1480,
  "the-facts-of-life-complete-series::The Facts of Life S09E02 - Down and Out in Malibu (Part 2).ia.mp4": 1480,
  "the-facts-of-life-complete-series::The Facts of Life S09E03 - Rumor Has It.ia.mp4": 1480,
  "the-facts-of-life-complete-series::The Facts of Life S09E04 - Before The Fall.ia.mp4": 1485,
  "the-facts-of-life-complete-series::The Facts of Life S09E05 - Sweet Charity.ia.mp4": 1482,
  "the-facts-of-life-complete-series::The Facts of Life S09E06 - Up from Down Under.ia.mp4": 1480,
  "the-facts-of-life-complete-series::The Facts of Life S09E07 - The More The Merrier.ia.mp4": 1484,
  "the-facts-of-life-complete-series::The Facts of Life S09E08 - A Rose By any Other Age.ia.mp4": 1481,
  "the-facts-of-life-complete-series::The Facts of Life S09E09 - Adventures in Baileysitting.ia.mp4": 1484,
  "the-facts-of-life-complete-series::The Facts of Life S09E10 - It's A Wonderful Christmas.ia.mp4": 1481,
  "the-facts-of-life-complete-series::The Facts of Life S09E11 - Golden Oldie.ia.mp4": 1480,
  "the-facts-of-life-complete-series::The Facts of Life S09E12 - A Thousand Frowns.ia.mp4": 1479,
  "the-facts-of-life-complete-series::The Facts of Life S09E13 - Something in Common.ia.mp4": 1480,
  "the-facts-of-life-complete-series::The Facts of Life S09E14 - Peekskill Law.ia.mp4": 1480,
  "the-facts-of-life-complete-series::The Facts of Life S09E15 - A House Divided.ia.mp4": 1481,
  "the-facts-of-life-complete-series::The Facts of Life S09E16 - The First Time.ia.mp4": 1479,
  "the-facts-of-life-complete-series::The Facts of Life S09E17 - Let's Face The Music.ia.mp4": 1481,
  "the-facts-of-life-complete-series::The Facts of Life S09E18 - Less Than Perfect.ia.mp4": 1483,
  "the-facts-of-life-complete-series::The Facts of Life S09E19 - Till Marriage Do Us Part.ia.mp4": 1482,
  "the-facts-of-life-complete-series::The Facts of Life S09E20 - Present Imperfect.ia.mp4": 1482,
  "the-facts-of-life-complete-series::The Facts of Life S09E21 - On The Edge.ia.mp4": 1480,
  "the-facts-of-life-complete-series::The Facts of Life S09E22 - Big Apple Blues.ia.mp4": 1479,
  "the-facts-of-life-complete-series::The Facts of Life S09E23 - The Beginning of The End.ia.mp4": 1480,
  "the-facts-of-life-complete-series::The Facts of Life S09E24 - The Beginning of The Beginning.ia.mp4": 1482,
},
};
