window.SHOW = {
  id: "ArchiesWeirdMysteries",
  title: "Archie's Weird Mysteries",
  art: "ArchiesWeirdMysteries.jpg",
  storageProgressKey: "archiesweirdmysteries-progress",
  storageSettingsKey: "archiesweirdmysteries-settings",
  nestedPaths: true,
  grouping: "season",
  segments: "none",
  episodes: [
  ["archies-weird-mysteries-complete-series-1999", "ARCHIE'S WEIRD MYSTERIES - S01E01 - Attack of the Killer Spuds",
    "Archie's Weird Mysteries - E01 (Attack of the Killer Spuds).mp4"],
  ["archies-weird-mysteries-complete-series-1999", "ARCHIE'S WEIRD MYSTERIES - S01E02 - Driven to Distraction",
    "Archie's Weird Mysteries - E02 (Me Me Me!).mp4"],
  ["archies-weird-mysteries-complete-series-1999", "ARCHIE'S WEIRD MYSTERIES - S01E03 - Me! Me! Me!",
    "Archie's Weird Mysteries - E03 (Driven to Distraction).mp4"],
  ["archies-weird-mysteries-complete-series-1999", "ARCHIE'S WEIRD MYSTERIES - S01E04 - Invisible Archie",
    "Archie's Weird Mysteries - E04 (Attack of the 50-Foot Veronica).mp4"],
  ["archies-weird-mysteries-complete-series-1999", "ARCHIE'S WEIRD MYSTERIES - S01E05 - Attack of the 50-Foot Veronica",
    "Archie's Weird Mysteries - E05 (Invisible Archie).mp4"],
  ["archies-weird-mysteries-complete-series-1999", "ARCHIE'S WEIRD MYSTERIES - S01E06 - The Haunting of Riverdale",
    "Archie's Weird Mysteries - E06 (The Haunting of Riverdale).mp4"],
  ["archies-weird-mysteries-complete-series-1999", "ARCHIE'S WEIRD MYSTERIES - S01E07 - Curse of the Mummy",
    "Archie's Weird Mysteries - E07 (The Curse of the Mummy).mp4"],
  ["archies-weird-mysteries-complete-series-1999", "ARCHIE'S WEIRD MYSTERIES - S01E08 - Fleas Release Me",
    "Archie's Weird Mysteries - E08 (Fleas Release Me).mp4"],
  ["archies-weird-mysteries-complete-series-1999", "ARCHIE'S WEIRD MYSTERIES - S01E09 - The Jughead Incident",
    "Archie's Weird Mysteries - E09 (Mega-Mall of Horrors).mp4"],
  ["archies-weird-mysteries-complete-series-1999", "ARCHIE'S WEIRD MYSTERIES - S01E10 - Virtually Evil",
    "Archie's Weird Mysteries - E10 (The Jughead Incident).mp4"],
  ["archies-weird-mysteries-complete-series-1999", "ARCHIE'S WEIRD MYSTERIES - S01E11 - Zombies of Love",
    "Archie's Weird Mysteries - E11 (Virtually Evil).mp4"],
  ["archies-weird-mysteries-complete-series-1999", "ARCHIE'S WEIRD MYSTERIES - S01E12 - Brain of Terror",
    "Archie's Weird Mysteries - E12 (Zombies of Love).mp4"],
  ["archies-weird-mysteries-complete-series-1999", "ARCHIE'S WEIRD MYSTERIES - S01E13 - Twisted Youth",
    "Archie's Weird Mysteries - E13 (Brain of Terror).mp4"],
  ["archies-weird-mysteries-complete-series-1999", "ARCHIE'S WEIRD MYSTERIES - S01E14 - Monster in the Night",
    "Archie's Weird Mysteries - E14 (Twisted Youth).mp4"],
  ["archies-weird-mysteries-complete-series-1999", "ARCHIE'S WEIRD MYSTERIES - S01E15 - Mega-Mall of Horrors",
    "Archie's Weird Mysteries - E15 (Compu-Terror).mp4"],
  ["archies-weird-mysteries-complete-series-1999", "ARCHIE'S WEIRD MYSTERIES - S01E16 - Compu-Terror",
    "Archie's Weird Mysteries - E16 (Monster in the Night).mp4"],
  ["archies-weird-mysteries-complete-series-1999", "ARCHIE'S WEIRD MYSTERIES - S01E17 - Misfortune Hunters",
    "Archie's Weird Mysteries - E17 (Misfortune Hunters).mp4"],
  ["archies-weird-mysteries-complete-series-1999", "ARCHIE'S WEIRD MYSTERIES - S01E18 - Ship of Ghouls",
    "Archie's Weird Mysteries - E18 (Ship of Ghouls).mp4"],
  ["archies-weird-mysteries-complete-series-1999", "ARCHIE'S WEIRD MYSTERIES - S01E19 - Something is Haunting Riverdale High",
    "Archie's Weird Mysteries - E19 (Something is Haunting Riverdale High).mp4"],
  ["archies-weird-mysteries-complete-series-1999", "ARCHIE'S WEIRD MYSTERIES - S01E20 - Supreme Girl vs. Dr. Arachnid",
    "Archie's Weird Mysteries - E20 (Supreme Girl vs. Dr. Arachnid).mp4"],
  ["archies-weird-mysteries-complete-series-1999", "ARCHIE'S WEIRD MYSTERIES - S01E21 - Reggie or Not",
    "Archie's Weird Mysteries - E21 (Reggie or Not).mp4"],
  ["archies-weird-mysteries-complete-series-1999", "ARCHIE'S WEIRD MYSTERIES - S01E22 - It Lives in the Sewers",
    "Archie's Weird Mysteries - E22 (It Lives in the Sewers).mp4"],
  ["archies-weird-mysteries-complete-series-1999", "ARCHIE'S WEIRD MYSTERIES - S01E23 - Dream Girl",
    "Archie's Weird Mysteries - E23 (Dream Girl).mp4"],
  ["archies-weird-mysteries-complete-series-1999", "ARCHIE'S WEIRD MYSTERIES - S01E24 - Green-Eyed Monster",
    "Archie's Weird Mysteries - E24 (Green-Eyed Monster).mp4"],
  ["archies-weird-mysteries-complete-series-1999", "ARCHIE'S WEIRD MYSTERIES - S01E25 - Cinemadness",
    "Archie's Weird Mysteries - E25 (Cinemadness).mp4"],
  ["archies-weird-mysteries-complete-series-1999", "ARCHIE'S WEIRD MYSTERIES - S01E26 - Beware of the Glob!",
    "Archie's Weird Mysteries - E26 (Beware the Glob!).mp4"],
  ["archies-weird-mysteries-complete-series-1999", "ARCHIE'S WEIRD MYSTERIES - S01E27 - The Day the Earth Moved",
    "Archie's Weird Mysteries - E27 (The Day the Earth Moved).mp4"],
  ["archies-weird-mysteries-complete-series-1999", "ARCHIE'S WEIRD MYSTERIES - S01E28 - Dance of the Killer Bees",
    "Archie's Weird Mysteries - E28 (Dance of the Killer Bees).mp4"],
  ["archies-weird-mysteries-complete-series-1999", "ARCHIE'S WEIRD MYSTERIES - S01E29 - Extra Terror-estrial",
    "Archie's Weird Mysteries - E29 (Extra Terror-Estrial).mp4"],
  ["archies-weird-mysteries-complete-series-1999", "ARCHIE'S WEIRD MYSTERIES - S01E30 - The Christmas Phantom",
    "Archie's Weird Mysteries - E30 (Big Monster on Campus).mp4"],
  ["archies-weird-mysteries-complete-series-1999", "ARCHIE'S WEIRD MYSTERIES - S01E31 - Scarlet Night",
    "Archie's Weird Mysteries - E31 (The Christmas Phantom).mp4"],
  ["archies-weird-mysteries-complete-series-1999", "ARCHIE'S WEIRD MYSTERIES - S01E32 - I Was a Teenage Vampire",
    "Archie's Weird Mysteries - E32 (Scarlet Night).mp4"],
  ["archies-weird-mysteries-complete-series-1999", "ARCHIE'S WEIRD MYSTERIES - S01E33 - Halloween of Horror",
    "Archie's Weird Mysteries - E33 (I was a Teenaged Vampire).mp4"],
  ["archies-weird-mysteries-complete-series-1999", "ARCHIE'S WEIRD MYSTERIES - S01E34 - Archie's Date with Fate",
    "Archie's Weird Mysteries - E34 (Halloween of Horror).mp4"],
  ["archies-weird-mysteries-complete-series-1999", "ARCHIE'S WEIRD MYSTERIES - S01E35 - Alternate Riverdales",
    "Archie's Weird Mysteries - E35 (Archie's Date with Fate).mp4"],
  ["archies-weird-mysteries-complete-series-1999", "ARCHIE'S WEIRD MYSTERIES - S01E36 - Teen Out of Time",
    "Archie's Weird Mysteries - E36 (Alternate Riverdales).mp4"],
  ["archies-weird-mysteries-complete-series-1999", "ARCHIE'S WEIRD MYSTERIES - S01E37 - Invasion of the Cockroaches",
    "Archie's Weird Mysteries - E37 (Teen Out of Time).mp4"],
  ["archies-weird-mysteries-complete-series-1999", "ARCHIE'S WEIRD MYSTERIES - S01E38 - The Incredible Shrinking Teens",
    "Archie's Weird Mysteries - E38 (Invasion of the Cockroaches).mp4"],
  ["archies-weird-mysteries-complete-series-1999", "ARCHIE'S WEIRD MYSTERIES - S01E39 - Little Chock'Lit Shoppe of Horrors",
    "Archie's Weird Mysteries - E39 (The Incredible Shrinking Teens).mp4"],
  ["archies-weird-mysteries-complete-series-1999", "ARCHIE'S WEIRD MYSTERIES - S01E40 - Big Monster on Campus",
    "Archie's Weird Mysteries - E40 (Little Chock'lit Shoppe of Horrors).mp4"],
  ["archies-weird-mysteries-complete-series-1999", "ARCHIE'S WEIRD MYSTERIES - S01E41 - Archie's Weird Mysteries E41 (Jugman",
    "Archie's Weird Mysteries - E41 (Jugman) [Series Finale].mp4"],
],
  durations: {
  "archies-weird-mysteries-complete-series-1999::Archie's Weird Mysteries - E01 (Attack of the Killer Spuds).mp4": 1393,
  "archies-weird-mysteries-complete-series-1999::Archie's Weird Mysteries - E02 (Me Me Me!).mp4": 1393,
  "archies-weird-mysteries-complete-series-1999::Archie's Weird Mysteries - E03 (Driven to Distraction).mp4": 1393,
  "archies-weird-mysteries-complete-series-1999::Archie's Weird Mysteries - E04 (Attack of the 50-Foot Veronica).mp4": 1394,
  "archies-weird-mysteries-complete-series-1999::Archie's Weird Mysteries - E05 (Invisible Archie).mp4": 1393,
  "archies-weird-mysteries-complete-series-1999::Archie's Weird Mysteries - E06 (The Haunting of Riverdale).mp4": 1395,
  "archies-weird-mysteries-complete-series-1999::Archie's Weird Mysteries - E07 (The Curse of the Mummy).mp4": 1392,
  "archies-weird-mysteries-complete-series-1999::Archie's Weird Mysteries - E08 (Fleas Release Me).mp4": 1392,
  "archies-weird-mysteries-complete-series-1999::Archie's Weird Mysteries - E09 (Mega-Mall of Horrors).mp4": 1393,
  "archies-weird-mysteries-complete-series-1999::Archie's Weird Mysteries - E10 (The Jughead Incident).mp4": 1393,
  "archies-weird-mysteries-complete-series-1999::Archie's Weird Mysteries - E11 (Virtually Evil).mp4": 1393,
  "archies-weird-mysteries-complete-series-1999::Archie's Weird Mysteries - E12 (Zombies of Love).mp4": 1393,
  "archies-weird-mysteries-complete-series-1999::Archie's Weird Mysteries - E13 (Brain of Terror).mp4": 1393,
  "archies-weird-mysteries-complete-series-1999::Archie's Weird Mysteries - E14 (Twisted Youth).mp4": 1393,
  "archies-weird-mysteries-complete-series-1999::Archie's Weird Mysteries - E15 (Compu-Terror).mp4": 1393,
  "archies-weird-mysteries-complete-series-1999::Archie's Weird Mysteries - E16 (Monster in the Night).mp4": 1393,
  "archies-weird-mysteries-complete-series-1999::Archie's Weird Mysteries - E17 (Misfortune Hunters).mp4": 1393,
  "archies-weird-mysteries-complete-series-1999::Archie's Weird Mysteries - E18 (Ship of Ghouls).mp4": 1393,
  "archies-weird-mysteries-complete-series-1999::Archie's Weird Mysteries - E19 (Something is Haunting Riverdale High).mp4": 1393,
  "archies-weird-mysteries-complete-series-1999::Archie's Weird Mysteries - E20 (Supreme Girl vs. Dr. Arachnid).mp4": 1393,
  "archies-weird-mysteries-complete-series-1999::Archie's Weird Mysteries - E21 (Reggie or Not).mp4": 1393,
  "archies-weird-mysteries-complete-series-1999::Archie's Weird Mysteries - E22 (It Lives in the Sewers).mp4": 1393,
  "archies-weird-mysteries-complete-series-1999::Archie's Weird Mysteries - E23 (Dream Girl).mp4": 1393,
  "archies-weird-mysteries-complete-series-1999::Archie's Weird Mysteries - E24 (Green-Eyed Monster).mp4": 1393,
  "archies-weird-mysteries-complete-series-1999::Archie's Weird Mysteries - E25 (Cinemadness).mp4": 1393,
  "archies-weird-mysteries-complete-series-1999::Archie's Weird Mysteries - E26 (Beware the Glob!).mp4": 1393,
  "archies-weird-mysteries-complete-series-1999::Archie's Weird Mysteries - E27 (The Day the Earth Moved).mp4": 1393,
  "archies-weird-mysteries-complete-series-1999::Archie's Weird Mysteries - E28 (Dance of the Killer Bees).mp4": 1393,
  "archies-weird-mysteries-complete-series-1999::Archie's Weird Mysteries - E29 (Extra Terror-Estrial).mp4": 1393,
  "archies-weird-mysteries-complete-series-1999::Archie's Weird Mysteries - E30 (Big Monster on Campus).mp4": 1393,
  "archies-weird-mysteries-complete-series-1999::Archie's Weird Mysteries - E31 (The Christmas Phantom).mp4": 1393,
  "archies-weird-mysteries-complete-series-1999::Archie's Weird Mysteries - E32 (Scarlet Night).mp4": 1393,
  "archies-weird-mysteries-complete-series-1999::Archie's Weird Mysteries - E33 (I was a Teenaged Vampire).mp4": 1393,
  "archies-weird-mysteries-complete-series-1999::Archie's Weird Mysteries - E34 (Halloween of Horror).mp4": 1393,
  "archies-weird-mysteries-complete-series-1999::Archie's Weird Mysteries - E35 (Archie's Date with Fate).mp4": 1393,
  "archies-weird-mysteries-complete-series-1999::Archie's Weird Mysteries - E36 (Alternate Riverdales).mp4": 1393,
  "archies-weird-mysteries-complete-series-1999::Archie's Weird Mysteries - E37 (Teen Out of Time).mp4": 1393,
  "archies-weird-mysteries-complete-series-1999::Archie's Weird Mysteries - E38 (Invasion of the Cockroaches).mp4": 1393,
  "archies-weird-mysteries-complete-series-1999::Archie's Weird Mysteries - E39 (The Incredible Shrinking Teens).mp4": 1393,
  "archies-weird-mysteries-complete-series-1999::Archie's Weird Mysteries - E40 (Little Chock'lit Shoppe of Horrors).mp4": 1393,
  "archies-weird-mysteries-complete-series-1999::Archie's Weird Mysteries - E41 (Jugman) [Series Finale].mp4": 4235,
},
};
