window.SHOW = {
  id: "Spooksville",
  title: "Spooksville",
  art: "Spooksville.jpg",
  storageProgressKey: "spooksville-progress",
  storageSettingsKey: "spooksville-settings",
  nestedPaths: true,
  grouping: "season",
  segments: "none",
  episodes: [
  ["spooksville-the-complete-series", "SPOOKSVILLE - S01E01 - The Secret Path - Part 1",
    "Spooksville S01E01 The Secret Path Pt1.mp4"],
  ["spooksville-the-complete-series", "SPOOKSVILLE - S01E02 - The Secret Path - Part 2",
    "Spooksville S01E02 The Secret Path Pt2.mp4"],
  ["spooksville-the-complete-series", "SPOOKSVILLE - S01E03 - The Evil House",
    "Spooksville S01E03 The Evil House.mp4"],
  ["spooksville-the-complete-series", "SPOOKSVILLE - S01E04 - The Howling Ghost",
    "Spooksville S01E04 The Howling Ghost.mp4"],
  ["spooksville-the-complete-series", "SPOOKSVILLE - S01E05 - The Haunted Cave",
    "Spooksville S01E05 The Haunted Cave.mp4"],
  ["spooksville-the-complete-series", "SPOOKSVILLE - S01E06 - The Thing In The Closet",
    "Spooksville S01E06 The Thing In The Closet.mp4"],
  ["spooksville-the-complete-series", "SPOOKSVILLE - S01E07 - The Fire Inside",
    "Spooksville S01E07 The Fire Inside.mp4"],
  ["spooksville-the-complete-series", "SPOOKSVILLE - S01E08 - The Wishing Stone",
    "Spooksville S01E08 The Wishing Stone.mp4"],
  ["spooksville-the-complete-series", "SPOOKSVILLE - S01E09 - The Wicked Cat",
    "Spooksville S01E09 The Wicked Cat.mp4"],
  ["spooksville-the-complete-series", "SPOOKSVILLE - S01E10 - The No-ones",
    "Spooksville S01E10 The No-Ones.mp4"],
  ["spooksville-the-complete-series", "SPOOKSVILLE - S01E11 - The Dark Corner",
    "Spooksville S01E11 The Dark Corner.mp4"],
  ["spooksville-the-complete-series", "SPOOKSVILLE - S01E12 - Shell Shock",
    "Spooksville S01E12 Shell Shock.mp4"],
  ["spooksville-the-complete-series", "SPOOKSVILLE - S01E13 - Flowers Of Evil",
    "Spooksville S01E13 Flowers Of Evil.mp4"],
  ["spooksville-the-complete-series", "SPOOKSVILLE - S01E14 - Phone Fear",
    "Spooksville S01E14 Phone Fear.mp4"],
  ["spooksville-the-complete-series", "SPOOKSVILLE - S01E15 - Critical Care",
    "Spooksville S01E15 Critical Care.mp4"],
  ["spooksville-the-complete-series", "SPOOKSVILLE - S01E16 - Blood Drive",
    "Spooksville S01E16 Blood Drive.mp4"],
  ["spooksville-the-complete-series", "SPOOKSVILLE - S01E17 - Fathers And Sons",
    "Spooksville S01E17 Fathers And Sons.mp4"],
  ["spooksville-the-complete-series", "SPOOKSVILLE - S01E18 - Gnome Alone",
    "Spooksville S01E18 Gnome Alone.mp4"],
  ["spooksville-the-complete-series", "SPOOKSVILLE - S01E19 - Oh Monster, My Monster",
    "Spooksville S01E19 Oh Monster My Monster.mp4"],
  ["spooksville-the-complete-series", "SPOOKSVILLE - S01E20 - The Maze",
    "Spooksville S01E20 The Maze.mp4"],
  ["spooksville-the-complete-series", "SPOOKSVILLE - S01E21 - Run",
    "Spooksville S01E21 Run.mp4"],
  ["spooksville-the-complete-series", "SPOOKSVILLE - S01E22 - Stone",
    "Spooksville S01E22 Stone.mp4"],
],
  durations: {
  "spooksville-the-complete-series::Spooksville S01E01 The Secret Path Pt1.mp4": 1302,
  "spooksville-the-complete-series::Spooksville S01E02 The Secret Path Pt2.mp4": 1302,
  "spooksville-the-complete-series::Spooksville S01E03 The Evil House.mp4": 1302,
  "spooksville-the-complete-series::Spooksville S01E04 The Howling Ghost.mp4": 1300,
  "spooksville-the-complete-series::Spooksville S01E05 The Haunted Cave.mp4": 1300,
  "spooksville-the-complete-series::Spooksville S01E06 The Thing In The Closet.mp4": 1302,
  "spooksville-the-complete-series::Spooksville S01E07 The Fire Inside.mp4": 1296,
  "spooksville-the-complete-series::Spooksville S01E08 The Wishing Stone.mp4": 1302,
  "spooksville-the-complete-series::Spooksville S01E09 The Wicked Cat.mp4": 1302,
  "spooksville-the-complete-series::Spooksville S01E10 The No-Ones.mp4": 1302,
  "spooksville-the-complete-series::Spooksville S01E11 The Dark Corner.mp4": 1299,
  "spooksville-the-complete-series::Spooksville S01E12 Shell Shock.mp4": 1301,
  "spooksville-the-complete-series::Spooksville S01E13 Flowers Of Evil.mp4": 1294,
  "spooksville-the-complete-series::Spooksville S01E14 Phone Fear.mp4": 1302,
  "spooksville-the-complete-series::Spooksville S01E15 Critical Care.mp4": 1300,
  "spooksville-the-complete-series::Spooksville S01E16 Blood Drive.mp4": 1301,
  "spooksville-the-complete-series::Spooksville S01E17 Fathers And Sons.mp4": 1301,
  "spooksville-the-complete-series::Spooksville S01E18 Gnome Alone.mp4": 1302,
  "spooksville-the-complete-series::Spooksville S01E19 Oh Monster My Monster.mp4": 1302,
  "spooksville-the-complete-series::Spooksville S01E20 The Maze.mp4": 1302,
  "spooksville-the-complete-series::Spooksville S01E21 Run.mp4": 1302,
  "spooksville-the-complete-series::Spooksville S01E22 Stone.mp4": 1302,
},
};
