window.SHOW = {
  id: "MorphFiles",
  title: "The Morph Files",
  art: "MorphFiles.jpg",
  storageProgressKey: "morphfiles-progress",
  storageSettingsKey: "morphfiles-settings",
  nestedPaths: true,
  grouping: "season",
  segments: "none",
  episodes: [
  ["the-morph-files-the-complete-series-1996", "THE MORPH FILES - S01E01 - Babysitting",
    "The Morph Files E01 - Babysitting.mp4"],
  ["the-morph-files-the-complete-series-1996", "THE MORPH FILES - S01E02 - Skiing",
    "The Morph Files E02 - Skiing.mp4"],
  ["the-morph-files-the-complete-series-1996", "THE MORPH FILES - S01E03 - Gobbledygook",
    "The Morph Files E03 - Gobbledygook.mp4"],
  ["the-morph-files-the-complete-series-1996", "THE MORPH FILES - S01E04 - Doctor Morph",
    "The Morph Files E04 - Doctor Morph.mp4"],
  ["the-morph-files-the-complete-series-1996", "THE MORPH FILES - S01E05 - The Dog Show",
    "The Morph Files E05 - The Dog Show.mp4"],
  ["the-morph-files-the-complete-series-1996", "THE MORPH FILES - S01E06 - Exercising",
    "The Morph Files E06 - Exercising.mp4"],
  ["the-morph-files-the-complete-series-1996", "THE MORPH FILES - S01E07 - Games",
    "The Morph Files E07 - Games.mp4"],
  ["the-morph-files-the-complete-series-1996", "THE MORPH FILES - S01E08 - The Film Show",
    "The Morph Files E08 - The Film Show.mp4"],
  ["the-morph-files-the-complete-series-1996", "THE MORPH FILES - S01E09 - Gardening",
    "The Morph Files E09 - Gardening.mp4"],
  ["the-morph-files-the-complete-series-1996", "THE MORPH FILES - S01E10 - Mirrors",
    "The Morph Files E10 - Mirrors.mp4"],
  ["the-morph-files-the-complete-series-1996", "THE MORPH FILES - S01E11 - Little Green",
    "The Morph Files E11 - Little Green.mp4"],
  ["the-morph-files-the-complete-series-1996", "THE MORPH FILES - S01E12 - Cowboys",
    "The Morph Files E12 - Cowboys.mp4"],
  ["the-morph-files-the-complete-series-1996", "THE MORPH FILES - S01E13 - The Birthday Party",
    "The Morph Files E13 - The Birthday Party.mp4"],
],
  durations: {
  "the-morph-files-the-complete-series-1996::The Morph Files E01 - Babysitting.mp4": 563,
  "the-morph-files-the-complete-series-1996::The Morph Files E02 - Skiing.mp4": 560,
  "the-morph-files-the-complete-series-1996::The Morph Files E03 - Gobbledygook.mp4": 562,
  "the-morph-files-the-complete-series-1996::The Morph Files E04 - Doctor Morph.mp4": 558,
  "the-morph-files-the-complete-series-1996::The Morph Files E05 - The Dog Show.mp4": 558,
  "the-morph-files-the-complete-series-1996::The Morph Files E06 - Exercising.mp4": 560,
  "the-morph-files-the-complete-series-1996::The Morph Files E07 - Games.mp4": 560,
  "the-morph-files-the-complete-series-1996::The Morph Files E08 - The Film Show.mp4": 562,
  "the-morph-files-the-complete-series-1996::The Morph Files E09 - Gardening.mp4": 557,
  "the-morph-files-the-complete-series-1996::The Morph Files E10 - Mirrors.mp4": 560,
  "the-morph-files-the-complete-series-1996::The Morph Files E11 - Little Green.mp4": 562,
  "the-morph-files-the-complete-series-1996::The Morph Files E12 - Cowboys.mp4": 555,
  "the-morph-files-the-complete-series-1996::The Morph Files E13 - The Birthday Party.mp4": 560,
},
};
