window.SHOW = {
  id: "HarryandtheHendersons",
  title: "Harry and the Hendersons",
  art: "HarryandtheHendersons.jpg",
  storageProgressKey: "harryandthehendersons-progress",
  storageSettingsKey: "harryandthehendersons-settings",
  nestedPaths: true,
  grouping: "season",
  segments: "none",
  episodes: [
  ["harry-and-the-hendersons-complete-series", "HARRY AND THE HENDERSONS - S01E01 - The Arrival",
    "S01E01 - The Arrival.mp4"],
  ["harry-and-the-hendersons-complete-series", "HARRY AND THE HENDERSONS - S01E02 - The Day After",
    "S01E02 - The Day After.mp4"],
  ["harry-and-the-hendersons-complete-series", "HARRY AND THE HENDERSONS - S01E03 - Cool",
    "S01E03 - Cool.mp4"],
  ["harry-and-the-hendersons-complete-series", "HARRY AND THE HENDERSONS - S01E04 - Harry Goes Home (1)",
    "S01E04 - Harry Goes Home.mp4"],
  ["harry-and-the-hendersons-complete-series", "HARRY AND THE HENDERSONS - S01E05 - Whose Forest Is It Anyway? (2)",
    "S01E05 - Whose Forest Is It Anyway.mp4"],
  ["harry-and-the-hendersons-complete-series", "HARRY AND THE HENDERSONS - S01E06 - The Father and Son Game",
    "S01E06 - The Father and Son Game.mp4"],
  ["harry-and-the-hendersons-complete-series", "HARRY AND THE HENDERSONS - S01E07 - Baggin' the Big One",
    "S01E07 - Baggin the Big One.mp4"],
  ["harry-and-the-hendersons-complete-series", "HARRY AND THE HENDERSONS - S01E08 - Harry the Hero",
    "S01E08 - Harry the Hero.mp4"],
  ["harry-and-the-hendersons-complete-series", "HARRY AND THE HENDERSONS - S01E09 - Roots, the Herb",
    "S01E09 - Roots, the Herb.mp4"],
  ["harry-and-the-hendersons-complete-series", "HARRY AND THE HENDERSONS - S01E10 - The Mentor",
    "S01E10 - The Mentor.mp4"],
  ["harry-and-the-hendersons-complete-series", "HARRY AND THE HENDERSONS - S01E11 - The Bodyguard",
    "S01E11 - The Bodyguard.mp4"],
  ["harry-and-the-hendersons-complete-series", "HARRY AND THE HENDERSONS - S01E12 - Harry and the Homeless Man",
    "S01E12 - Harry and the Homeless Man.mp4"],
  ["harry-and-the-hendersons-complete-series", "HARRY AND THE HENDERSONS - S01E13 - Harry Goes Ape",
    "S01E13 - Harry Goes Ape.mp4"],
  ["harry-and-the-hendersons-complete-series", "HARRY AND THE HENDERSONS - S01E14 - Pet Psychic",
    "S01E14 - Pet Psychic.mp4"],
  ["harry-and-the-hendersons-complete-series", "HARRY AND THE HENDERSONS - S01E15 - The Bigfoot That Ate Seattle",
    "S01E15 - The Bigfoot That Ate Seattle.mp4"],
  ["harry-and-the-hendersons-complete-series", "HARRY AND THE HENDERSONS - S01E16 - Harry and the Masked Wrestler",
    "S01E16 - Harry and the Masked Wrestler.mp4"],
  ["harry-and-the-hendersons-complete-series", "HARRY AND THE HENDERSONS - S01E17 - When Harry Met Sammy",
    "S01E17 - When Harry Met Sammy.mp4"],
  ["harry-and-the-hendersons-complete-series", "HARRY AND THE HENDERSONS - S01E18 - Harry and the Cheerleaders",
    "S01E18 - Harry and the Cheerleaders.mp4"],
  ["harry-and-the-hendersons-complete-series", "HARRY AND THE HENDERSONS - S02E01 - Retrospective",
    "S02E01 - Retrospective.mp4"],
  ["harry-and-the-hendersons-complete-series", "HARRY AND THE HENDERSONS - S02E02 - The Terror of the Trees",
    "S02E02 - The Terror of the Trees.mp4"],
  ["harry-and-the-hendersons-complete-series", "HARRY AND THE HENDERSONS - S02E03 - Sarah Sings the Blues",
    "S02E03 - Sarah Sings the Blues.mp4"],
  ["harry-and-the-hendersons-complete-series", "HARRY AND THE HENDERSONS - S02E04 - Mom",
    "S02E04 - Mom.mp4"],
  ["harry-and-the-hendersons-complete-series", "HARRY AND THE HENDERSONS - S02E05 - The Ransom of Bigfoot",
    "S02E05 - The Ransom of Bigfoot.mp4"],
  ["harry-and-the-hendersons-complete-series", "HARRY AND THE HENDERSONS - S02E06 - Halloween",
    "S02E06 - Halloween.mp4"],
  ["harry-and-the-hendersons-complete-series", "HARRY AND THE HENDERSONS - S02E07 - Brett Hits Home",
    "S02E07 - Brett Hits Home.mp4"],
  ["harry-and-the-hendersons-complete-series", "HARRY AND THE HENDERSONS - S02E08 - George's White Light",
    "S02E08 - George's White Light.mp4"],
  ["harry-and-the-hendersons-complete-series", "HARRY AND THE HENDERSONS - S02E09 - Working Stiffs",
    "S02E09 - Working Stiffs.mp4"],
  ["harry-and-the-hendersons-complete-series", "HARRY AND THE HENDERSONS - S02E10 - Love Mask",
    "S02E10 - The Love Mask.mp4"],
  ["harry-and-the-hendersons-complete-series", "HARRY AND THE HENDERSONS - S02E11 - Blue Parrot",
    "S02E11 - The Blue Parrot.mp4"],
  ["harry-and-the-hendersons-complete-series", "HARRY AND THE HENDERSONS - S02E12 - Winning",
    "S02E12 - Winning.mp4"],
  ["harry-and-the-hendersons-complete-series", "HARRY AND THE HENDERSONS - S02E13 - Til Theft Do Us Part",
    "S02E13 - Til Theft Do Us Part.mp4"],
  ["harry-and-the-hendersons-complete-series", "HARRY AND THE HENDERSONS - S02E14 - The Genius",
    "S02E14 - The Genius.mp4"],
  ["harry-and-the-hendersons-complete-series", "HARRY AND THE HENDERSONS - S02E15 - Wild Things",
    "S02E15 - Wild Things.mp4"],
  ["harry-and-the-hendersons-complete-series", "HARRY AND THE HENDERSONS - S02E16 - Fatherhood",
    "S02E16 - Fatherhood.mp4"],
  ["harry-and-the-hendersons-complete-series", "HARRY AND THE HENDERSONS - S02E17 - Sara Spills the Bigfoot Beans",
    "S02E17 - Sarah Spills the Bigfoot Beans.mp4"],
  ["harry-and-the-hendersons-complete-series", "HARRY AND THE HENDERSONS - S02E18 - Moonlighting",
    "S02E18 - Moonlighting.mp4"],
  ["harry-and-the-hendersons-complete-series", "HARRY AND THE HENDERSONS - S02E19 - The Green Eyed Bigfoot",
    "S02E19 - The Green-Eyed Bigfoot.mp4"],
  ["harry-and-the-hendersons-complete-series", "HARRY AND THE HENDERSONS - S02E20 - The Itchologist",
    "S02E20 - The Ittchyologist.mp4"],
  ["harry-and-the-hendersons-complete-series", "HARRY AND THE HENDERSONS - S02E21 - Selling Out",
    "S02E21 - Selling Out.mp4"],
  ["harry-and-the-hendersons-complete-series", "HARRY AND THE HENDERSONS - S02E22 - The Girl Who Cried Bigfoot",
    "S02E22 - Girl Who Cried Bigfoot.mp4"],
  ["harry-and-the-hendersons-complete-series", "HARRY AND THE HENDERSONS - S02E23 - The Busybody",
    "S02E23 - The Busybody.mp4"],
  ["harry-and-the-hendersons-complete-series", "HARRY AND THE HENDERSONS - S02E24 - I Got Your Birthday Right Here",
    "S02E24 - I Got Your Birthday Right Here.mp4"],
  ["harry-and-the-hendersons-complete-series", "HARRY AND THE HENDERSONS - S03E01 - Yo Richie!",
    "S03E01 - Yo, Richie.mp4"],
  ["harry-and-the-hendersons-complete-series", "HARRY AND THE HENDERSONS - S03E02 - The Candidate",
    "S03E02 - The Candidate.mp4"],
  ["harry-and-the-hendersons-complete-series", "HARRY AND THE HENDERSONS - S03E03 - The Bride and the Gloom",
    "S03E03 - The Bride and the Gloom.mp4"],
  ["harry-and-the-hendersons-complete-series", "HARRY AND THE HENDERSONS - S03E04 - Born Again",
    "S03E04 - Born Again.mp4"],
  ["harry-and-the-hendersons-complete-series", "HARRY AND THE HENDERSONS - S03E05 - The Old Bigfoot",
    "S03E05 - The Old Bigfoot.mp4"],
  ["harry-and-the-hendersons-complete-series", "HARRY AND THE HENDERSONS - S03E06 - The Outing",
    "S03E06 - The Outing.mp4"],
  ["harry-and-the-hendersons-complete-series", "HARRY AND THE HENDERSONS - S03E07 - Harry Henderson National Treasure",
    "S03E07 - Harry Henderson National Park.mp4"],
  ["harry-and-the-hendersons-complete-series", "HARRY AND THE HENDERSONS - S03E08 - Retrospective Two",
    "S03E08 - Breaking Up Is Hard to Do.mp4"],
  ["harry-and-the-hendersons-complete-series", "HARRY AND THE HENDERSONS - S03E09 - Blood Is Thicker Than...",
    "S03E09 - Blood Is Thicker Than Karma.mp4"],
  ["harry-and-the-hendersons-complete-series", "HARRY AND THE HENDERSONS - S03E10 - Pitch, Pitch, Pitch",
    "S03E10 - Pitch, Pitch, Pitch.mp4"],
  ["harry-and-the-hendersons-complete-series", "HARRY AND THE HENDERSONS - S03E11 - Harry the Mascot",
    "S03E11 - Harry the Mascot.mp4"],
  ["harry-and-the-hendersons-complete-series", "HARRY AND THE HENDERSONS - S03E12 - The Big Kiss Off",
    "S03E12 - The Big Kiss-Off.mp4"],
  ["harry-and-the-hendersons-complete-series", "HARRY AND THE HENDERSONS - S03E13 - The Frenchman",
    "S03E13 - The Frenchman.mp4"],
  ["harry-and-the-hendersons-complete-series", "HARRY AND THE HENDERSONS - S03E14 - Laid Up",
    "S03E14 - Laid Up.mp4"],
  ["harry-and-the-hendersons-complete-series", "HARRY AND THE HENDERSONS - S03E15 - Harrywood Babylon",
    "S03E15 - Harrywood Babylon.mp4"],
  ["harry-and-the-hendersons-complete-series", "HARRY AND THE HENDERSONS - S03E16 - Witness (1)",
    "S03E16 - Witness Pt.1.mp4"],
  ["harry-and-the-hendersons-complete-series", "HARRY AND THE HENDERSONS - S03E17 - Harry the Hostage (2)",
    "S03E17 - Harry the Hostage Pt.2.mp4"],
  ["harry-and-the-hendersons-complete-series", "HARRY AND THE HENDERSONS - S03E18 - Exterminator",
    "S03E18 - The Ex-Terminator.mp4"],
  ["harry-and-the-hendersons-complete-series", "HARRY AND THE HENDERSONS - S03E19 - Beauty and the Beast",
    "S03E19 - Beauty and the Beast.mp4"],
  ["harry-and-the-hendersons-complete-series", "HARRY AND THE HENDERSONS - S03E20 - Big Feet, Small Minds",
    "S03E20 - Big Feet, Small Minds.mp4"],
  ["harry-and-the-hendersons-complete-series", "HARRY AND THE HENDERSONS - S03E21 - Surf's Down",
    "S03E21 - Surf's Down.mp4"],
  ["harry-and-the-hendersons-complete-series", "HARRY AND THE HENDERSONS - S03E22 - Follow Your Art",
    "S03E22 - Follow Your Art.mp4"],
  ["harry-and-the-hendersons-complete-series", "HARRY AND THE HENDERSONS - S03E23 - Them Bones",
    "S03E23 - Them Bones.mp4"],
  ["harry-and-the-hendersons-complete-series", "HARRY AND THE HENDERSONS - S03E24 - The Three Facts of Brett",
    "S03E24 - The Three Faces of Brett.mp4"],
  ["harry-and-the-hendersons-complete-series", "HARRY AND THE HENDERSONS - S03E25 - Ernie Confidential",
    "S03E25 - Ernie Confidential.mp4"],
  ["harry-and-the-hendersons-complete-series", "HARRY AND THE HENDERSONS - S03E26 - Uncle Mack Comes Back",
    "S03E26 - Uncle Mack Comes Back.mp4"],
  ["harry-and-the-hendersons-complete-series", "HARRY AND THE HENDERSONS - S03E27 - Skin Deep",
    "S03E27 - Skin Deep.mp4"],
  ["harry-and-the-hendersons-complete-series", "HARRY AND THE HENDERSONS - S03E28 - Retrospective Three",
    "S03E28 - The Write Stuff.mp4"],
  ["harry-and-the-hendersons-complete-series", "HARRY AND THE HENDERSONS - S03E29 - The Long Goodbyes (1)",
    "S03E29 - The Long Goodbyes Pt.1.mp4"],
  ["harry-and-the-hendersons-complete-series", "HARRY AND THE HENDERSONS - S03E30 - The Long Goodbyes (2)",
    "S03E30 - The Long Goodbyes Pt.2.mp4"],
],
  durations: {
  "harry-and-the-hendersons-complete-series::S01E01 - The Arrival.mp4": 1298,
  "harry-and-the-hendersons-complete-series::S01E02 - The Day After.mp4": 1301,
  "harry-and-the-hendersons-complete-series::S01E03 - Cool.mp4": 1299,
  "harry-and-the-hendersons-complete-series::S01E04 - Harry Goes Home.mp4": 1304,
  "harry-and-the-hendersons-complete-series::S01E05 - Whose Forest Is It Anyway.mp4": 1303,
  "harry-and-the-hendersons-complete-series::S01E06 - The Father and Son Game.mp4": 1304,
  "harry-and-the-hendersons-complete-series::S01E07 - Baggin the Big One.mp4": 1305,
  "harry-and-the-hendersons-complete-series::S01E08 - Harry the Hero.mp4": 1301,
  "harry-and-the-hendersons-complete-series::S01E09 - Roots, the Herb.mp4": 1300,
  "harry-and-the-hendersons-complete-series::S01E10 - The Mentor.mp4": 1303,
  "harry-and-the-hendersons-complete-series::S01E11 - The Bodyguard.mp4": 1298,
  "harry-and-the-hendersons-complete-series::S01E12 - Harry and the Homeless Man.mp4": 1296,
  "harry-and-the-hendersons-complete-series::S01E13 - Harry Goes Ape.mp4": 1304,
  "harry-and-the-hendersons-complete-series::S01E14 - Pet Psychic.mp4": 1303,
  "harry-and-the-hendersons-complete-series::S01E15 - The Bigfoot That Ate Seattle.mp4": 1303,
  "harry-and-the-hendersons-complete-series::S01E16 - Harry and the Masked Wrestler.mp4": 1303,
  "harry-and-the-hendersons-complete-series::S01E17 - When Harry Met Sammy.mp4": 1304,
  "harry-and-the-hendersons-complete-series::S01E18 - Harry and the Cheerleaders.mp4": 1304,
  "harry-and-the-hendersons-complete-series::S02E01 - Retrospective.mp4": 1301,
  "harry-and-the-hendersons-complete-series::S02E02 - The Terror of the Trees.mp4": 1304,
  "harry-and-the-hendersons-complete-series::S02E03 - Sarah Sings the Blues.mp4": 1303,
  "harry-and-the-hendersons-complete-series::S02E04 - Mom.mp4": 1305,
  "harry-and-the-hendersons-complete-series::S02E05 - The Ransom of Bigfoot.mp4": 1303,
  "harry-and-the-hendersons-complete-series::S02E06 - Halloween.mp4": 1302,
  "harry-and-the-hendersons-complete-series::S02E07 - Brett Hits Home.mp4": 1354,
  "harry-and-the-hendersons-complete-series::S02E08 - George's White Light.mp4": 1354,
  "harry-and-the-hendersons-complete-series::S02E09 - Working Stiffs.mp4": 1355,
  "harry-and-the-hendersons-complete-series::S02E10 - The Love Mask.mp4": 1356,
  "harry-and-the-hendersons-complete-series::S02E11 - The Blue Parrot.mp4": 1356,
  "harry-and-the-hendersons-complete-series::S02E12 - Winning.mp4": 1356,
  "harry-and-the-hendersons-complete-series::S02E13 - Til Theft Do Us Part.mp4": 1300,
  "harry-and-the-hendersons-complete-series::S02E14 - The Genius.mp4": 1353,
  "harry-and-the-hendersons-complete-series::S02E15 - Wild Things.mp4": 1355,
  "harry-and-the-hendersons-complete-series::S02E16 - Fatherhood.mp4": 1354,
  "harry-and-the-hendersons-complete-series::S02E17 - Sarah Spills the Bigfoot Beans.mp4": 1354,
  "harry-and-the-hendersons-complete-series::S02E18 - Moonlighting.mp4": 1355,
  "harry-and-the-hendersons-complete-series::S02E19 - The Green-Eyed Bigfoot.mp4": 1356,
  "harry-and-the-hendersons-complete-series::S02E20 - The Ittchyologist.mp4": 1300,
  "harry-and-the-hendersons-complete-series::S02E21 - Selling Out.mp4": 1354,
  "harry-and-the-hendersons-complete-series::S02E22 - Girl Who Cried Bigfoot.mp4": 1355,
  "harry-and-the-hendersons-complete-series::S02E23 - The Busybody.mp4": 1355,
  "harry-and-the-hendersons-complete-series::S02E24 - I Got Your Birthday Right Here.mp4": 1353,
  "harry-and-the-hendersons-complete-series::S03E01 - Yo, Richie.mp4": 1354,
  "harry-and-the-hendersons-complete-series::S03E02 - The Candidate.mp4": 1353,
  "harry-and-the-hendersons-complete-series::S03E03 - The Bride and the Gloom.mp4": 1354,
  "harry-and-the-hendersons-complete-series::S03E04 - Born Again.mp4": 1354,
  "harry-and-the-hendersons-complete-series::S03E05 - The Old Bigfoot.mp4": 1355,
  "harry-and-the-hendersons-complete-series::S03E06 - The Outing.mp4": 1299,
  "harry-and-the-hendersons-complete-series::S03E07 - Harry Henderson National Park.mp4": 1299,
  "harry-and-the-hendersons-complete-series::S03E08 - Breaking Up Is Hard to Do.mp4": 1353,
  "harry-and-the-hendersons-complete-series::S03E09 - Blood Is Thicker Than Karma.mp4": 1303,
  "harry-and-the-hendersons-complete-series::S03E10 - Pitch, Pitch, Pitch.mp4": 1356,
  "harry-and-the-hendersons-complete-series::S03E11 - Harry the Mascot.mp4": 1299,
  "harry-and-the-hendersons-complete-series::S03E12 - The Big Kiss-Off.mp4": 1297,
  "harry-and-the-hendersons-complete-series::S03E13 - The Frenchman.mp4": 1303,
  "harry-and-the-hendersons-complete-series::S03E14 - Laid Up.mp4": 1300,
  "harry-and-the-hendersons-complete-series::S03E15 - Harrywood Babylon.mp4": 1298,
  "harry-and-the-hendersons-complete-series::S03E16 - Witness Pt.1.mp4": 1299,
  "harry-and-the-hendersons-complete-series::S03E17 - Harry the Hostage Pt.2.mp4": 1300,
  "harry-and-the-hendersons-complete-series::S03E18 - The Ex-Terminator.mp4": 1299,
  "harry-and-the-hendersons-complete-series::S03E19 - Beauty and the Beast.mp4": 1297,
  "harry-and-the-hendersons-complete-series::S03E20 - Big Feet, Small Minds.mp4": 1300,
  "harry-and-the-hendersons-complete-series::S03E21 - Surf's Down.mp4": 1299,
  "harry-and-the-hendersons-complete-series::S03E22 - Follow Your Art.mp4": 1300,
  "harry-and-the-hendersons-complete-series::S03E23 - Them Bones.mp4": 1298,
  "harry-and-the-hendersons-complete-series::S03E24 - The Three Faces of Brett.mp4": 1300,
  "harry-and-the-hendersons-complete-series::S03E25 - Ernie Confidential.mp4": 1297,
  "harry-and-the-hendersons-complete-series::S03E26 - Uncle Mack Comes Back.mp4": 1301,
  "harry-and-the-hendersons-complete-series::S03E27 - Skin Deep.mp4": 1301,
  "harry-and-the-hendersons-complete-series::S03E28 - The Write Stuff.mp4": 1301,
  "harry-and-the-hendersons-complete-series::S03E29 - The Long Goodbyes Pt.1.mp4": 1300,
  "harry-and-the-hendersons-complete-series::S03E30 - The Long Goodbyes Pt.2.mp4": 1300,
},
};
