window.SHOW = {
  id: "MarriedWithChildren",
  title: "Married... with Children",
  storageProgressKey: "marriedwithchildren-progress",
  storageSettingsKey: "marriedwithchildren-settings",
  nestedPaths: true,
  grouping: "season",
  segments: "none",
  episodes: [
  ['married...-with-children_202602', "MARRIED... WITH CHILDREN - S04E01 - Hot Off the Grill",
    "Married... with Children - S04E01 - Hot Off the Grill.mp4"],
  ['married...-with-children_202602', "MARRIED... WITH CHILDREN - S04E02 - Dead Men Don't Do Aerobics",
    "Married... with Children - S04E02 - Dead Men Don't Do Aerobics.mp4"],
  ['married...-with-children_202602', "MARRIED... WITH CHILDREN - S04E03 - Buck Saves the Day",
    "Married... with Children - S04E03 - Buck Saves the Day.mp4"],
  ['married...-with-children_202602', "MARRIED... WITH CHILDREN - S04E04 - Tooth or Consequences",
    "Married... with Children - S04E04 - Tooth or Consequences.mp4"],
  ['married...-with-children_202602', "MARRIED... WITH CHILDREN - S04E05 - He Ain't Much, But He's Mine",
    "Married... with Children - S04E05 - He Ain't Much, But He's Mine.mp4"],
  ['married...-with-children_202602', "MARRIED... WITH CHILDREN - S04E06 - Fair Exchange",
    "Married... with Children - S04E06 - Fair Exchange.mp4"],
  ['married...-with-children_202602', "MARRIED... WITH CHILDREN - S04E07 - Desperately Seeking Miss October",
    "Married... with Children - S04E07 - Desperately Seeking Miss October.mp4"],
  ['married...-with-children_202602', "MARRIED... WITH CHILDREN - S04E08 - 976-SHOE",
    "Married... with Children - S04E08 - 976-SHOE.mp4"],
  ['married...-with-children_202602', "MARRIED... WITH CHILDREN - S04E09 - Oh, What a Feeling",
    "Married... with Children - S04E09 - Oh, What a Feeling.mp4"],
  ['married...-with-children_202602', "MARRIED... WITH CHILDREN - S04E10 - At the Zoo",
    "Married... with Children - S04E10 - At the Zoo.mp4"],
  ['married...-with-children_202602', "MARRIED... WITH CHILDREN - S04E11-12 - It's a Bundyful Life",
    "Married... with Children - S04E11-12 - It's a Bundyful Life.mp4"],
  ['married...-with-children_202602', "MARRIED... WITH CHILDREN - S04E13 - Who'll Stop the Rain",
    "Married... with Children - S04E13 - Who'll Stop the Rain.mp4"],
  ['married...-with-children_202602', "MARRIED... WITH CHILDREN - S04E14 - A Taxing Problem",
    "Married... with Children - S04E14 - A Taxing Problem.mp4"],
  ['married...-with-children_202602', "MARRIED... WITH CHILDREN - S04E15 - Rock and Roll Girl",
    "Married... with Children - S04E15 - Rock and Roll Girl.mp4"],
  ['married...-with-children_202602', "MARRIED... WITH CHILDREN - S04E16 - You Gotta Know When to Hold 'Em (1)",
    "Married... with Children - S04E16 - You Gotta Know When to Hold 'Em (1).mp4"],
  ['married...-with-children_202602', "MARRIED... WITH CHILDREN - S04E17 - You Gotta Know When to Fold 'Em (2)",
    "Married... with Children - S04E17 - You Gotta Know When to Fold 'Em (2).mp4"],
  ['married...-with-children_202602', "MARRIED... WITH CHILDREN - S04E18 - What Goes Around Came Around",
    "Married... with Children - S04E18 - What Goes Around Came Around.mp4"],
  ['married...-with-children_202602', "MARRIED... WITH CHILDREN - S04E19 - Peggy Turns 300",
    "Married... with Children - S04E19 - Peggy Turns 300.mp4"],
  ['married...-with-children_202602', "MARRIED... WITH CHILDREN - S04E20 - Peggy Made a Little Lamb",
    "Married... with Children - S04E20 - Peggy Made a Little Lamb.mp4"],
  ['married...-with-children_202602', "MARRIED... WITH CHILDREN - S04E21 - Rain Girl",
    "Married... with Children - S04E21 - Rain Girl.mp4"],
  ['married...-with-children_202602', "MARRIED... WITH CHILDREN - S04E22 - The Agony of De Feet",
    "Married... with Children - S04E22 - The Agony of De Feet.mp4"],
  ['married...-with-children_202602', "MARRIED... WITH CHILDREN - S04E23 - Yard Sale",
    "Married... with Children - S04E23 - Yard Sale.mp4"],
],
  durations: {},
};
