window.SHOW = {
  id: "AllInTheFamily",
  title: "All in the Family",
  art: "AllInTheFamily.jpg",
  storageProgressKey: "allinthefamily-progress",
  storageSettingsKey: "allinthefamily-settings",
  nestedPaths: true,
  grouping: "season",
  segments: "none",
  episodes: [
  ["arcibaldo", "\"ALL IN THE FAMILY\" - S01E01 - Meet the Bunkers",
    "arcibaldo 1x01.mp4"],
  ["arcibaldo", "\"ALL IN THE FAMILY\" - S01E02 - Writing the President",
    "arcibaldo 1x02.mp4"],
  ["arcibaldo", "\"ALL IN THE FAMILY\" - S01E03 - Oh, My Aching Back",
    "arcibaldo 1x03.mp4"],
  ["arcibaldo", "\"ALL IN THE FAMILY\" - S01E04 - Archie Gives Blood",
    "arcibaldo 1x04.mp4"],
  ["arcibaldo", "\"ALL IN THE FAMILY\" - S01E05 - Judging Books by Covers",
    "arcibaldo 1x05.mp4"],
  ["arcibaldo", "\"ALL IN THE FAMILY\" - S01E06 - Gloria's Pregnancy",
    "arcibaldo 1x06.mp4"],
  ["arcibaldo", "\"ALL IN THE FAMILY\" - S01E07 - Mike's Hippie Friends Come to Visit",
    "arcibaldo 1x07.mp4"],
  ["arcibaldo", "\"ALL IN THE FAMILY\" - S01E08 - Lionel Moves Into the Neighborhood",
    "arcibaldo 1x08.mp4"],
  ["arcibaldo", "\"ALL IN THE FAMILY\" - S01E10 - Archie is Worried About His Job",
    "arcibaldo 1x10.mp4"],
  ["arcibaldo", "\"ALL IN THE FAMILY\" - S01E13 - The First and Last Supper",
    "arcibaldo 1x13.mp4"],
  ["arcibaldo", "\"ALL IN THE FAMILY\" - S02E01 - The Saga of Cousin Oscar",
    "arcibaldo 2x01.mp4"],
  ["arcibaldo", "\"ALL IN THE FAMILY\" - S02E03 - Archie and the Lock-Up",
    "arcibaldo 2x03.mp4"],
  ["arcibaldo", "\"ALL IN THE FAMILY\" - S02E04 - Edith Writes a Song",
    "arcibaldo 2x04.mp4"],
  ["arcibaldo", "\"ALL IN THE FAMILY\" - S02E05 - Flashback: Mike Meets Archie",
    "arcibaldo 2x05.mp4"],
  ["arcibaldo", "\"ALL IN THE FAMILY\" - S02E06 - The Election Story",
    "arcibaldo 2x06.mp4"],
  ["arcibaldo", "\"ALL IN THE FAMILY\" - S02E07 - Edith's Accident",
    "arcibaldo 2x07.mp4"],
  ["arcibaldo", "\"ALL IN THE FAMILY\" - S02E08 - The Blockbuster",
    "arcibaldo 2x08.mp4"],
  ["1998-all-in-the-family-nick-at-nite-norman-lear-picks-marathon-5-nights-woc_202506", "\"ALL IN THE FAMILY\" - S02E09 - Mike's Problem",
    "1998 All In The Family Nick At Nite Norman Lear Picks Marathon 5 Nights WOC/05 1971 All In The Family S2E9 Mikes Problem (1998 Nick At Nite) WOC 720p.mp4"],
  ["arcibaldo", "\"ALL IN THE FAMILY\" - S02E12 - Cousin Maude's Visit",
    "arcibldo ep 2x12.mp4"],
  ["1998-all-in-the-family-nick-at-nite-norman-lear-picks-marathon-5-nights-woc_202506", "\"ALL IN THE FAMILY\" - S02E14 - The Elevator Story",
    "1998 All In The Family Nick At Nite Norman Lear Picks Marathon 5 Nights WOC/14 1972 All In The Family S2E14 The Elevator Story (1998 Nick At Nite) WOC 720p.mp4"],
  ["1998-all-in-the-family-nick-at-nite-norman-lear-picks-marathon-5-nights-woc_202506", "\"ALL IN THE FAMILY\" - S02E15 - Edith's Problem",
    "1998 All In The Family Nick At Nite Norman Lear Picks Marathon 5 Nights WOC/19 1972 All In The Family S2E15 Ediths Problem (1998 Nick At Nite) WOC 720p.mp4"],
  ["arcibaldo", "\"ALL IN THE FAMILY\" - S02E20 - Edith Gets a Mink",
    "arcibaldo 2x20.mp4"],
  ["arcibaldo", "\"ALL IN THE FAMILY\" - S02E21 - Sammy's Visit",
    "arcibaldo 2x21.mp4"],
  ["arcibaldo", "\"ALL IN THE FAMILY\" - S02E22 - Edith, the Judge",
    "arcibaldo 2x22.mp4"],
  ["arcibaldo", "\"ALL IN THE FAMILY\" - S02E23 - Archie is Jealous",
    "arcibaldo 2x23.mp4"],
  ["all-in-the-family-s3", "\"ALL IN THE FAMILY\" - S03E01 - Archie and the Editorial",
    "All In The Family (Disc 1).mp4"],
  ["all-in-the-family-s3", "\"ALL IN THE FAMILY\" - S03E02 - Archie's Fraud",
    "All In The Family (Disc 1)1.mp4"],
  ["all-in-the-family-s3", "\"ALL IN THE FAMILY\" - S03E03 - The Threat",
    "All In The Family (Disc 1)3.mp4"],
  ["all-in-the-family-s3", "\"ALL IN THE FAMILY\" - S03E04 - Gloria and the Riddle",
    "All In The Family (Disc 1)4.mp4"],
  ["all-in-the-family-s3", "\"ALL IN THE FAMILY\" - S03E05 - Lionel Steps Out",
    "All In The Family (Disc 1)6.mp4"],
  ["all-in-the-family-s3", "\"ALL IN THE FAMILY\" - S03E06 - Edith Flips Her Wig",
    "All In The Family (Disc 1)7.mp4"],
  ["all-in-the-family-s3", "\"ALL IN THE FAMILY\" - S03E07 - The Bunkers and the Swingers",
    "All In The Family (Disc 1)8.mp4"],
  ["all-in-the-family-s3", "\"ALL IN THE FAMILY\" - S03E08 - Mike Comes Into Money",
    "All In The Family (Disc 1)9.mp4"],
  ["all-in-the-family-s3", "\"ALL IN THE FAMILY\" - S03E09 - Flashback: Mike and Gloria's Wedding (1)",
    "All In The Family (Disc 2).mp4"],
  ["all-in-the-family-s3", "\"ALL IN THE FAMILY\" - S03E10 - Flashback: Mike and Gloria's Wedding (2)",
    "All In The Family (Disc 2)1.mp4"],
  ["all-in-the-family-s3", "\"ALL IN THE FAMILY\" - S03E11 - The Locket",
    "All In The Family (Disc 2)4.mp4"],
  ["all-in-the-family-s3", "\"ALL IN THE FAMILY\" - S03E12 - Mike's Appendix",
    "All In The Family (Disc 2)5.mp4"],
  ["all-in-the-family-s3", "\"ALL IN THE FAMILY\" - S03E13 - Edith's Winning Ticket",
    "All In The Family (Disc 2)6.mp4"],
  ["all-in-the-family-s3", "\"ALL IN THE FAMILY\" - S03E14 - Archie and the Bowling Team",
    "All In The Family (Disc 2)7.mp4"],
  ["all-in-the-family-s3", "\"ALL IN THE FAMILY\" - S03E15 - Archie in the Hospital",
    "All In The Family (Disc 2)8.mp4"],
  ["all-in-the-family-s3", "\"ALL IN THE FAMILY\" - S03E16 - Oh Say Can You See",
    "All In The Family (Disc 2)9.mp4"],
  ["all-in-the-family-s3", "\"ALL IN THE FAMILY\" - S03E17 - Archie Goes Too Far",
    "All In The Family (Disc 3).mp4"],
  ["all-in-the-family-s3", "\"ALL IN THE FAMILY\" - S03E18 - Class Reunion",
    "All In The Family (Disc 3)1.mp4"],
  ["all-in-the-family-s3", "\"ALL IN THE FAMILY\" - S03E19 - Hot Watch",
    "All In The Family (Disc 3)3.mp4"],
  ["all-in-the-family-s3", "\"ALL IN THE FAMILY\" - S03E20 - Archie is Branded",
    "All In The Family (Disc 3)4.mp4"],
  ["all-in-the-family-s3", "\"ALL IN THE FAMILY\" - S03E21 - Everybody Tells the Truth",
    "All In The Family (Disc 3)6.mp4"],
  ["all-in-the-family-s3", "\"ALL IN THE FAMILY\" - S03E22 - Archie Learns His Lesson",
    "All In The Family (Disc 3)7.mp4"],
  ["all-in-the-family-s3", "\"ALL IN THE FAMILY\" - S03E23 - Gloria, the Victim",
    "All In The Family (Disc 3)8.mp4"],
  ["all-in-the-family-s3", "\"ALL IN THE FAMILY\" - S03E24 - The Battle of the Month",
    "All In The Family (Disc 3)9.mp4"],
  ["all-in-the-family-s4", "\"ALL IN THE FAMILY\" - S04E01 - We're Having a Heat Wave",
    "All in the Family Season 4 Disc 1.mp4"],
  ["all-in-the-family-s4", "\"ALL IN THE FAMILY\" - S04E02 - We're Still Having a Heat Wave",
    "All in the Family Season 4 Disc 11.mp4"],
  ["all-in-the-family-s4", "\"ALL IN THE FAMILY\" - S04E03 - Edith Finds an Old Man",
    "All in the Family Season 4 Disc 13.mp4"],
  ["all-in-the-family-s4", "\"ALL IN THE FAMILY\" - S04E04 - Archie and the Kiss",
    "All in the Family Season 4 Disc 14.mp4"],
  ["all-in-the-family-s4", "\"ALL IN THE FAMILY\" - S04E05 - Archie, the Gambler",
    "All in the Family Season 4 Disc 15.mp4"],
  ["all-in-the-family-s4", "\"ALL IN THE FAMILY\" - S04E06 - Henry's Farewell",
    "All in the Family Season 4 Disc 16.mp4"],
  ["all-in-the-family-s4", "\"ALL IN THE FAMILY\" - S04E07 - Archie and the Computer",
    "All in the Family Season 4 Disc 17.mp4"],
  ["all-in-the-family-s4", "\"ALL IN THE FAMILY\" - S04E08 - The Games Bunkers Play",
    "All in the Family Season 4 Disc 18.mp4"],
  ["all-in-the-family-s4", "\"ALL IN THE FAMILY\" - S04E09 - Edith's Conversion",
    "All in the Family Season 4 Disc 2.mp4"],
  ["all-in-the-family-s4", "\"ALL IN THE FAMILY\" - S04E10 - Archie in the Cellar",
    "All in the Family Season 4 Disc 21.mp4"],
  ["all-in-the-family-s4", "\"ALL IN THE FAMILY\" - S04E11 - Black is the Color of My True Love's Wig",
    "All in the Family Season 4 Disc 22.mp4"],
  ["all-in-the-family-s4", "\"ALL IN THE FAMILY\" - S04E12 - Second Honeymoon",
    "All in the Family Season 4 Disc 23.mp4"],
  ["all-in-the-family-s4", "\"ALL IN THE FAMILY\" - S04E13 - The Taxi Caper",
    "All in the Family Season 4 Disc 24.mp4"],
  ["all-in-the-family-s4", "\"ALL IN THE FAMILY\" - S04E14 - Archie is Cursed",
    "All in the Family Season 4 Disc 25.mp4"],
  ["all-in-the-family-s4", "\"ALL IN THE FAMILY\" - S04E15 - Edith's Christmas Story",
    "All in the Family Season 4 Disc 26.mp4"],
  ["all-in-the-family-s4", "\"ALL IN THE FAMILY\" - S04E16 - Mike and Gloria Mix It Up",
    "All in the Family Season 4 Disc 27.mp4"],
  ["all-in-the-family-s4", "\"ALL IN THE FAMILY\" - S04E17 - Archie Feels Left Out",
    "All in the Family Season 4 Disc 3.mp4"],
  ["all-in-the-family-s4", "\"ALL IN THE FAMILY\" - S04E18 - Et Tu, Archie?",
    "All in the Family Season 4 Disc 31.mp4"],
  ["all-in-the-family-s4", "\"ALL IN THE FAMILY\" - S04E19 - Gloria's Boyfriend",
    "All in the Family Season 4 Disc 32.mp4"],
  ["all-in-the-family-s4", "\"ALL IN THE FAMILY\" - S04E20 - Lionel's Engagement",
    "All in the Family Season 4 Disc 33.mp4"],
  ["all-in-the-family-s4", "\"ALL IN THE FAMILY\" - S04E21 - Archie Eats and Runs",
    "All in the Family Season 4 Disc 34.mp4"],
  ["all-in-the-family-s4", "\"ALL IN THE FAMILY\" - S04E22 - Gloria Sings the Blues",
    "All in the Family Season 4 Disc 36.mp4"],
  ["all-in-the-family-s4", "\"ALL IN THE FAMILY\" - S04E23 - Pay the Twenty Dollars",
    "All in the Family Season 4 Disc 37.mp4"],
  ["all-in-the-family-s4", "\"ALL IN THE FAMILY\" - S04E24 - Mike's Graduation",
    "All in the Family Season 4 Disc 38.mp4"],
  ["1976-all-in-the-family-s-6-e-21-2001-nick-at-nite-woc-720p", "\"ALL IN THE FAMILY\" - S06E21 - Love by Appointment",
    "1976 All In The Family S6E21 (2001 Nick At Nite) WOC 720p.mp4"],
],
  durations: {
  "arcibaldo::arcibaldo 1x01.mp4": 1537,
  "arcibaldo::arcibaldo 1x02.mp4": 1536,
  "arcibaldo::arcibaldo 1x03.mp4": 1560,
  "arcibaldo::arcibaldo 1x04.mp4": 1550,
  "arcibaldo::arcibaldo 1x05.mp4": 1513,
  "arcibaldo::arcibaldo 1x06.mp4": 1529,
  "arcibaldo::arcibaldo 1x07.mp4": 1550,
  "arcibaldo::arcibaldo 1x08.mp4": 1546,
  "arcibaldo::arcibaldo 1x10.mp4": 1534,
  "arcibaldo::arcibaldo 1x13.mp4": 1525,
  "arcibaldo::arcibaldo 2x01.mp4": 1542,
  "arcibaldo::arcibaldo 2x03.mp4": 1551,
  "arcibaldo::arcibaldo 2x04.mp4": 1537,
  "arcibaldo::arcibaldo 2x05.mp4": 1557,
  "arcibaldo::arcibaldo 2x06.mp4": 1541,
  "arcibaldo::arcibaldo 2x07.mp4": 1541,
  "arcibaldo::arcibaldo 2x08.mp4": 1585,
  "1998-all-in-the-family-nick-at-nite-norman-lear-picks-marathon-5-nights-woc_202506::1998 All In The Family Nick At Nite Norman Lear Picks Marathon 5 Nights WOC/05 1971 All In The Family S2E9 Mikes Problem (1998 Nick At Nite) WOC 720p.mp4": 1789,
  "arcibaldo::arcibldo ep 2x12.mp4": 1563,
  "1998-all-in-the-family-nick-at-nite-norman-lear-picks-marathon-5-nights-woc_202506::1998 All In The Family Nick At Nite Norman Lear Picks Marathon 5 Nights WOC/14 1972 All In The Family S2E14 The Elevator Story (1998 Nick At Nite) WOC 720p.mp4": 1774,
  "1998-all-in-the-family-nick-at-nite-norman-lear-picks-marathon-5-nights-woc_202506::1998 All In The Family Nick At Nite Norman Lear Picks Marathon 5 Nights WOC/19 1972 All In The Family S2E15 Ediths Problem (1998 Nick At Nite) WOC 720p.mp4": 1835,
  "arcibaldo::arcibaldo 2x20.mp4": 1518,
  "arcibaldo::arcibaldo 2x21.mp4": 1566,
  "arcibaldo::arcibaldo 2x22.mp4": 1533,
  "arcibaldo::arcibaldo 2x23.mp4": 1550,
  "all-in-the-family-s3::All In The Family (Disc 1).mp4": 1554,
  "all-in-the-family-s3::All In The Family (Disc 1)1.mp4": 1539,
  "all-in-the-family-s3::All In The Family (Disc 1)3.mp4": 1552,
  "all-in-the-family-s3::All In The Family (Disc 1)4.mp4": 1525,
  "all-in-the-family-s3::All In The Family (Disc 1)6.mp4": 1551,
  "all-in-the-family-s3::All In The Family (Disc 1)7.mp4": 1545,
  "all-in-the-family-s3::All In The Family (Disc 1)8.mp4": 1550,
  "all-in-the-family-s3::All In The Family (Disc 1)9.mp4": 1550,
  "all-in-the-family-s3::All In The Family (Disc 2).mp4": 1550,
  "all-in-the-family-s3::All In The Family (Disc 2)1.mp4": 1561,
  "all-in-the-family-s3::All In The Family (Disc 2)4.mp4": 1539,
  "all-in-the-family-s3::All In The Family (Disc 2)5.mp4": 1543,
  "all-in-the-family-s3::All In The Family (Disc 2)6.mp4": 1547,
  "all-in-the-family-s3::All In The Family (Disc 2)7.mp4": 1528,
  "all-in-the-family-s3::All In The Family (Disc 2)8.mp4": 1531,
  "all-in-the-family-s3::All In The Family (Disc 2)9.mp4": 1515,
  "all-in-the-family-s3::All In The Family (Disc 3).mp4": 1552,
  "all-in-the-family-s3::All In The Family (Disc 3)1.mp4": 1566,
  "all-in-the-family-s3::All In The Family (Disc 3)3.mp4": 1547,
  "all-in-the-family-s3::All In The Family (Disc 3)4.mp4": 1552,
  "all-in-the-family-s3::All In The Family (Disc 3)6.mp4": 1548,
  "all-in-the-family-s3::All In The Family (Disc 3)7.mp4": 1543,
  "all-in-the-family-s3::All In The Family (Disc 3)8.mp4": 1548,
  "all-in-the-family-s3::All In The Family (Disc 3)9.mp4": 1504,
  "all-in-the-family-s4::All in the Family Season 4 Disc 1.mp4": 1539,
  "all-in-the-family-s4::All in the Family Season 4 Disc 11.mp4": 1537,
  "all-in-the-family-s4::All in the Family Season 4 Disc 13.mp4": 1521,
  "all-in-the-family-s4::All in the Family Season 4 Disc 14.mp4": 1487,
  "all-in-the-family-s4::All in the Family Season 4 Disc 15.mp4": 1509,
  "all-in-the-family-s4::All in the Family Season 4 Disc 16.mp4": 1538,
  "all-in-the-family-s4::All in the Family Season 4 Disc 17.mp4": 1528,
  "all-in-the-family-s4::All in the Family Season 4 Disc 18.mp4": 1522,
  "all-in-the-family-s4::All in the Family Season 4 Disc 2.mp4": 1540,
  "all-in-the-family-s4::All in the Family Season 4 Disc 21.mp4": 1528,
  "all-in-the-family-s4::All in the Family Season 4 Disc 22.mp4": 1537,
  "all-in-the-family-s4::All in the Family Season 4 Disc 23.mp4": 1500,
  "all-in-the-family-s4::All in the Family Season 4 Disc 24.mp4": 1529,
  "all-in-the-family-s4::All in the Family Season 4 Disc 25.mp4": 1533,
  "all-in-the-family-s4::All in the Family Season 4 Disc 26.mp4": 1535,
  "all-in-the-family-s4::All in the Family Season 4 Disc 27.mp4": 1503,
  "all-in-the-family-s4::All in the Family Season 4 Disc 3.mp4": 1540,
  "all-in-the-family-s4::All in the Family Season 4 Disc 31.mp4": 1515,
  "all-in-the-family-s4::All in the Family Season 4 Disc 32.mp4": 1507,
  "all-in-the-family-s4::All in the Family Season 4 Disc 33.mp4": 1538,
  "all-in-the-family-s4::All in the Family Season 4 Disc 34.mp4": 1539,
  "all-in-the-family-s4::All in the Family Season 4 Disc 36.mp4": 1503,
  "all-in-the-family-s4::All in the Family Season 4 Disc 37.mp4": 1534,
  "all-in-the-family-s4::All in the Family Season 4 Disc 38.mp4": 1538,
  "1976-all-in-the-family-s-6-e-21-2001-nick-at-nite-woc-720p::1976 All In The Family S6E21 (2001 Nick At Nite) WOC 720p.mp4": 1836,
},
};
