window.SHOW = {
  id: "Middleman",
  title: "The Middleman",
  art: "Middleman.jpg",
  storageProgressKey: "middleman-progress",
  storageSettingsKey: "middleman-settings",
  nestedPaths: true,
  grouping: "season",
  segments: "none",
  episodes: [
  ["the-middleman-complete", "THE MIDDLEMAN - S01E01 - The Pilot Episode Sanction",
    "The_Middleman_1x01_The_Pilot_Episode_Sanction_commentary.mp4"],
  ["the-middleman-complete", "THE MIDDLEMAN - S01E02 - The Accidental Occidental Conception",
    "The_Middleman_1x02_The_Accidental_Occidental_Conception.mp4"],
  ["the-middleman-complete", "THE MIDDLEMAN - S01E03 - The Sino-Mexican Revelation",
    "The_Middleman_1x03_The_Sino-Mexican_Revelation.mp4"],
  ["the-middleman-complete", "THE MIDDLEMAN - S01E04 - The Manicoid Teleportation Conundrum",
    "The_Middleman_1x04_The_Manicoid_Teleportation_Conundrum.mp4"],
  ["the-middleman-complete", "THE MIDDLEMAN - S01E05 - The Flying Fish Zombification",
    "The_Middleman_1x05_The_Flying_Fish_Zombification.mp4"],
  ["the-middleman-complete", "THE MIDDLEMAN - S01E06 - The Boy-Band Superfan Interrogation",
    "The_Middleman_1x06_The_Boy-Band_Superfan_Interrogation.mp4"],
  ["the-middleman-complete", "THE MIDDLEMAN - S01E07 - The Cursed Tuba Contingency",
    "The_Middleman_1x07_The_Cursed_Tuba_Contingency_commentary.mp4"],
  ["the-middleman-complete", "THE MIDDLEMAN - S01E08 - The Ectoplasmic Panhellenic Investigation",
    "The_Middleman_1x08_The_Ectoplasmic_Pan-Hellenic_Investigation.mp4"],
  ["the-middleman-complete", "THE MIDDLEMAN - S01E09 - The Obsolescent Cryogenic Meltdown",
    "The_Middleman_1x09_The_Obsolescent_Cryogenic_Meltdown.mp4"],
  ["the-middleman-complete", "THE MIDDLEMAN - S01E10 - The Vampiric Puppet Lamentation",
    "The_Middleman_1x10_The_Vampiric_Puppet_Lamentation.mp4"],
  ["the-middleman-complete", "THE MIDDLEMAN - S01E11 - The Clotharian Contamination Protocol",
    "The_Middleman_1x11_The_Clotharian_Contamination_Protocol_commentary.mp4"],
  ["the-middleman-complete", "THE MIDDLEMAN - S01E12 - The Palindrome Reversal Palindrome",
    "The_Middleman_1x12_The_Palindrome_Reversal_Palindrome_commentary.mp4"],
],
  durations: {
  "the-middleman-complete::The_Middleman_1x01_The_Pilot_Episode_Sanction_commentary.mp4": 2545,
  "the-middleman-complete::The_Middleman_1x02_The_Accidental_Occidental_Conception.mp4": 2651,
  "the-middleman-complete::The_Middleman_1x03_The_Sino-Mexican_Revelation.mp4": 2680,
  "the-middleman-complete::The_Middleman_1x04_The_Manicoid_Teleportation_Conundrum.mp4": 2633,
  "the-middleman-complete::The_Middleman_1x05_The_Flying_Fish_Zombification.mp4": 2630,
  "the-middleman-complete::The_Middleman_1x06_The_Boy-Band_Superfan_Interrogation.mp4": 2675,
  "the-middleman-complete::The_Middleman_1x07_The_Cursed_Tuba_Contingency_commentary.mp4": 2651,
  "the-middleman-complete::The_Middleman_1x08_The_Ectoplasmic_Pan-Hellenic_Investigation.mp4": 2661,
  "the-middleman-complete::The_Middleman_1x09_The_Obsolescent_Cryogenic_Meltdown.mp4": 2712,
  "the-middleman-complete::The_Middleman_1x10_The_Vampiric_Puppet_Lamentation.mp4": 2633,
  "the-middleman-complete::The_Middleman_1x11_The_Clotharian_Contamination_Protocol_commentary.mp4": 2705,
  "the-middleman-complete::The_Middleman_1x12_The_Palindrome_Reversal_Palindrome_commentary.mp4": 2713,
},
};
