window.SHOW = {
  id: "Animorphs",
  title: "Animorphs",
  art: "Animorphs.jpg",
  storageProgressKey: "animorphs-progress",
  storageSettingsKey: "animorphs-settings",
  nestedPaths: true,
  grouping: "season",
  segments: "none",
  episodes: [
  ["animorphs-season-1-and-2-the-complete-series", "ANIMORPHS - S01E01 - My Name is Jake: Part 1",
    "Animorphs.S01E01.My.Name.Is.Jake.1.ia.mp4"],
  ["animorphs-season-1-and-2-the-complete-series", "ANIMORPHS - S01E02 - My Name is Jake: Part 2",
    "Animorphs.S01E02.My.Name.Is.Jake.2.ia.mp4"],
  ["animorphs-season-1-and-2-the-complete-series", "ANIMORPHS - S01E03 - Underground",
    "Animorphs.S01E03.Underground.ia.mp4"],
  ["animorphs-season-1-and-2-the-complete-series", "ANIMORPHS - S01E04 - On the Run",
    "Animorphs.S01E04.On.the.Run.ia.mp4"],
  ["animorphs-season-1-and-2-the-complete-series", "ANIMORPHS - S01E05 - Between Friends",
    "Animorphs.S01E05.Between.Friends.ia.mp4"],
  ["animorphs-season-1-and-2-the-complete-series", "ANIMORPHS - S01E06 - The Message",
    "Animorphs.S01E06.The.Message.ia.mp4"],
  ["animorphs-season-1-and-2-the-complete-series", "ANIMORPHS - S01E07 - The Escape",
    "Animorphs.S01E07.The.Escape.ia.mp4"],
  ["animorphs-season-1-and-2-the-complete-series", "ANIMORPHS - S01E08 - The Alien",
    "Animorphs.S01E08.The.Alien.ia.mp4"],
  ["animorphs-season-1-and-2-the-complete-series", "ANIMORPHS - S01E09 - The Reaction",
    "Animorphs.S01E09.The.Capture.Part.1.ia.mp4"],
  ["animorphs-season-1-and-2-the-complete-series", "ANIMORPHS - S01E10 - The Stranger",
    "Animorphs.S01E10.The.Capture.Part.2.ia.mp4"],
  ["animorphs-season-1-and-2-the-complete-series", "ANIMORPHS - S01E11 - The Forgotten",
    "Animorphs.S01E11.The.Reaction.ia.mp4"],
  ["animorphs-season-1-and-2-the-complete-series", "ANIMORPHS - S01E12 - The Capture: Part 1",
    "Animorphs.S01E12.The.Stranger.ia.mp4"],
  ["animorphs-season-1-and-2-the-complete-series", "ANIMORPHS - S01E13 - The Capture: Part 2",
    "Animorphs.S01E13.The.Forgotten.ia.mp4"],
  ["animorphs-season-1-and-2-the-complete-series", "ANIMORPHS - S01E14 - Tobias",
    "Animorphs.S01E14.The.Leader.Part.1.ia.mp4"],
  ["animorphs-season-1-and-2-the-complete-series", "ANIMORPHS - S01E15 - Not My Problem",
    "Animorphs.S01E15.The.Leader.Part.2.ia.mp4"],
  ["animorphs-season-1-and-2-the-complete-series", "ANIMORPHS - S01E16 - The Leader: Part 1",
    "Animorphs.S01E16.Tobias.ia.mp4"],
  ["animorphs-season-1-and-2-the-complete-series", "ANIMORPHS - S01E17 - The Leader: Part 2",
    "Animorphs.S01E17.Not.My.Problem.ia.mp4"],
  ["animorphs-season-1-and-2-the-complete-series", "ANIMORPHS - S01E18 - The Release",
    "Animorphs.S01E18.The.Release.ia.mp4"],
  ["animorphs-season-1-and-2-the-complete-series", "ANIMORPHS - S01E19 - Face Off: Part 1",
    "Animorphs.S01E19.Face.Off.Part.1.ia.mp4"],
  ["animorphs-season-1-and-2-the-complete-series", "ANIMORPHS - S01E20 - Face Off: Part 2",
    "Animorphs.S01E20.Face.Off.Part.2.ia.mp4"],
  ["animorphs-season-1-and-2-the-complete-series", "ANIMORPHS - S02E01 - Face Off: Part 3",
    "Animorphs.S02E01.Face.Off.Part.3.ia.mp4"],
  ["animorphs-season-1-and-2-the-complete-series", "ANIMORPHS - S02E02 - My Name is Erek",
    "Animorphs.S02E02.My.Name.Is.Erek.ia.mp4"],
  ["animorphs-season-1-and-2-the-complete-series", "ANIMORPHS - S02E03 - Changes: Part 1",
    "Animorphs.S02E03.The.Front.ia.mp4"],
  ["animorphs-season-1-and-2-the-complete-series", "ANIMORPHS - S02E04 - Changes: Part 2",
    "Animorphs.S02E04.Changes.Part.1.ia.mp4"],
  ["animorphs-season-1-and-2-the-complete-series", "ANIMORPHS - S02E05 - Changes: Part 3",
    "Animorphs.S02E05.Changes.Part.2.ia.mp4"],
  ["animorphs-season-1-and-2-the-complete-series", "ANIMORPHS - S02E06 - The Front",
    "Animorphs.S02E06.Changes.Part.3.ia.mp4"],
],
  durations: {
  "animorphs-season-1-and-2-the-complete-series::Animorphs.S01E01.My.Name.Is.Jake.1.ia.mp4": 1465,
  "animorphs-season-1-and-2-the-complete-series::Animorphs.S01E02.My.Name.Is.Jake.2.ia.mp4": 1464,
  "animorphs-season-1-and-2-the-complete-series::Animorphs.S01E03.Underground.ia.mp4": 1465,
  "animorphs-season-1-and-2-the-complete-series::Animorphs.S01E04.On.the.Run.ia.mp4": 1456,
  "animorphs-season-1-and-2-the-complete-series::Animorphs.S01E05.Between.Friends.ia.mp4": 1464,
  "animorphs-season-1-and-2-the-complete-series::Animorphs.S01E06.The.Message.ia.mp4": 1464,
  "animorphs-season-1-and-2-the-complete-series::Animorphs.S01E07.The.Escape.ia.mp4": 1464,
  "animorphs-season-1-and-2-the-complete-series::Animorphs.S01E08.The.Alien.ia.mp4": 1464,
  "animorphs-season-1-and-2-the-complete-series::Animorphs.S01E09.The.Capture.Part.1.ia.mp4": 1464,
  "animorphs-season-1-and-2-the-complete-series::Animorphs.S01E10.The.Capture.Part.2.ia.mp4": 1464,
  "animorphs-season-1-and-2-the-complete-series::Animorphs.S01E11.The.Reaction.ia.mp4": 1456,
  "animorphs-season-1-and-2-the-complete-series::Animorphs.S01E12.The.Stranger.ia.mp4": 1466,
  "animorphs-season-1-and-2-the-complete-series::Animorphs.S01E13.The.Forgotten.ia.mp4": 1469,
  "animorphs-season-1-and-2-the-complete-series::Animorphs.S01E14.The.Leader.Part.1.ia.mp4": 1471,
  "animorphs-season-1-and-2-the-complete-series::Animorphs.S01E15.The.Leader.Part.2.ia.mp4": 1468,
  "animorphs-season-1-and-2-the-complete-series::Animorphs.S01E16.Tobias.ia.mp4": 1476,
  "animorphs-season-1-and-2-the-complete-series::Animorphs.S01E17.Not.My.Problem.ia.mp4": 1468,
  "animorphs-season-1-and-2-the-complete-series::Animorphs.S01E18.The.Release.ia.mp4": 1470,
  "animorphs-season-1-and-2-the-complete-series::Animorphs.S01E19.Face.Off.Part.1.ia.mp4": 1476,
  "animorphs-season-1-and-2-the-complete-series::Animorphs.S01E20.Face.Off.Part.2.ia.mp4": 1471,
  "animorphs-season-1-and-2-the-complete-series::Animorphs.S02E01.Face.Off.Part.3.ia.mp4": 1470,
  "animorphs-season-1-and-2-the-complete-series::Animorphs.S02E02.My.Name.Is.Erek.ia.mp4": 1470,
  "animorphs-season-1-and-2-the-complete-series::Animorphs.S02E03.The.Front.ia.mp4": 1478,
  "animorphs-season-1-and-2-the-complete-series::Animorphs.S02E04.Changes.Part.1.ia.mp4": 1469,
  "animorphs-season-1-and-2-the-complete-series::Animorphs.S02E05.Changes.Part.2.ia.mp4": 1471,
  "animorphs-season-1-and-2-the-complete-series::Animorphs.S02E06.Changes.Part.3.ia.mp4": 1472,
},
};
