window.SHOW = {
  id: "WillAndGrace",
  title: "Will & Grace",
  art: "WillAndGrace.jpg",
  storageProgressKey: "willandgrace-progress",
  storageSettingsKey: "willandgrace-settings",
  nestedPaths: true,
  grouping: "season",
  segments: "none",
  episodes: [
  ['will-grace-season-1', "WILL & GRACE - S01E01 - Love and Marriage (Pilot)",
    "A. Love and Marriage.mp4"],
  ['will-grace-season-1', "WILL & GRACE - S01E02 - A New Lease on Life",
    "B. A New Lease on Life.mp4"],
  ['will-grace-season-1', "WILL & GRACE - S01E03 - Head Case",
    "C. Head Case.mp4"],
  ['will-grace-season-1', "WILL & GRACE - S01E04 - Between a Rock and Harlin's Place",
    "D. Between A Rock and Harlin's Place.mp4"],
  ['will-grace-season-1', "WILL & GRACE - S01E05 - Boo! Humbug",
    "E. Boo! Humbug.mp4"],
  ['will-grace-season-1', "WILL & GRACE - S01E06 - William, Tell",
    "F. William, Tell.ia.mp4"],
  ['will-grace-season-1', "WILL & GRACE - S01E07 - Where There's a Will, There's No Way",
    "G. Where There's A Will, There's No Way.ia.mp4"],
  ['will-grace-season-1', "WILL & GRACE - S01E08 - The Buying Game",
    "H. The Buying Game.ia.mp4"],
  ['will-grace-season-1', "WILL & GRACE - S01E09 - The Truth About Will and Dogs",
    "I. The Truth About Will and Dogs.ia.mp4"],
  ['will-grace-season-1', "WILL & GRACE - S01E10 - The Big Vent",
    "J. The Big Event.ia.mp4"],
  ['will-grace-season-1', "WILL & GRACE - S01E11 - Will on Ice",
    "K. Will on Ice.ia.mp4"],
  ['will-grace-season-1', "WILL & GRACE - S01E12 - My Fair Maid-y",
    "L. My Fair Maid-y.ia.mp4"],
  ['will-grace-season-1', "WILL & GRACE - S01E13 - The Unsinkable Mommy Adler",
    "M. The Unsinkable Mommy Adler.ia.mp4"],
  ['will-grace-season-1', "WILL & GRACE - S01E14 - Big Brother Is Coming: Part I",
    "N. Big Brother is Coming Part 1.ia.mp4"],
  ['will-grace-season-1', "WILL & GRACE - S01E15 - Big Brother Is Coming: Part II",
    "O. Big Brother is Coming Part 2.ia.mp4"],
  ['will-grace-season-1', "WILL & GRACE - S01E16 - Yours, Mine or Ours",
    "P. Yours Mine or Ours.ia.mp4"],
  ['will-grace-season-1', "WILL & GRACE - S01E17 - Secrets and Lays",
    "Q. Secrets and Lays.ia.mp4"],
  ['will-grace-season-1', "WILL & GRACE - S01E18 - Grace, Replaced",
    "R. Grace Replaced.ia.mp4"],
  ['will-grace-season-1', "WILL & GRACE - S01E19 - Will Works Out",
    "S. Will Works Out.ia.mp4"],
  ['will-grace-season-1', "WILL & GRACE - S01E20 - Saving Grace",
    "T. Saving Grace.ia.mp4"],
  ['will-grace-season-1', "WILL & GRACE - S01E21 - Alley Cats",
    "U. Alley Cats.ia.mp4"],
  ['will-grace-season-1', "WILL & GRACE - S01E22 - Object of My Rejection",
    "V. Object of My Rejection.ia.mp4"],
  ['will-grace-season-2_202407', "WILL & GRACE - S02E01 - Guess Who's Not Coming to Dinner",
    "A. Guess Who's Not Coming To Dinner.mp4"],
  ['will-grace-season-2_202407', "WILL & GRACE - S02E02 - Election",
    "B. Election.ia.mp4"],
  ['will-grace-season-2_202407', "WILL & GRACE - S02E03 - Das Boob",
    "C. Das Boob.ia.mp4"],
  ['will-grace-season-2_202407', "WILL & GRACE - S02E04 - Whose Mom is it Anyway?",
    "D. Who's Mom Is It Anyway.mp4"],
  ['will-grace-season-2_202407', "WILL & GRACE - S02E05 - Polk Defeats Truman",
    "E. Polk Defeats Truman.mp4"],
  ['will-grace-season-2_202407', "WILL & GRACE - S02E06 - To Serve and Disinfect",
    "F. To Serve And Disinfect.mp4"],
  ['will-grace-season-2_202407', "WILL & GRACE - S02E07 - Homo for the Holidays",
    "G. Homo For The Holidays.mp4"],
  ['will-grace-season-2_202407', "WILL & GRACE - S02E08 - Terms of Employment",
    "H. Terms of Employment.mp4"],
  ['will-grace-season-2_202407', "WILL & GRACE - S02E09 - I Never Promised You An Olive Garden",
    "I. I Never Promised You An Olive Garden.mp4"],
  ['will-grace-season-2_202407', "WILL & GRACE - S02E10 - Tea and a Total Lack of Sympathy",
    "J. Tea And A Total Lack Of Sympathy.mp4"],
  ['will-grace-season-2_202407', "WILL & GRACE - S02E11 - Seeds of Discontent",
    "K. Seeds Of Discontent.mp4"],
  ['will-grace-season-2_202407', "WILL & GRACE - S02E12 - He's Come Undone",
    "L. He's Coming Undone.mp4"],
  ['will-grace-season-2_202407', "WILL & GRACE - S02E13 - Oh Dad, Poor Dad, He's Kept Me in the Closet and I'm So Sad",
    "M. Oh Dad Poor Dad He's Kept Me in the Closet and I'm So Sad.mp4"],
  ['will-grace-season-2_202407', "WILL & GRACE - S02E14 - Acting Out",
    "N. Acting Out.mp4"],
  ['will-grace-season-2_202407', "WILL & GRACE - S02E15 - Advise and Resent",
    "O. Advise and Resent.mp4"],
  ['will-grace-season-2_202407', "WILL & GRACE - S02E16 - Hey La, Hey La, My Ex-Boyfriend's Back",
    "P. Hey La Hey La My Ex-Boyfriend's Back.mp4"],
  ['will-grace-season-2_202407', "WILL & GRACE - S02E17 - The Hospital Show",
    "Q. The Hospital Show.mp4"],
  ['will-grace-season-2_202407', "WILL & GRACE - S02E18 - Sweet and Sour Charity",
    "R. Sweet And Sour Charity.mp4"],
  ['will-grace-season-2_202407', "WILL & GRACE - S02E19 - An Affair to Forget",
    "S. An Affair To Forget.mp4"],
  ['will-grace-season-2_202407', "WILL & GRACE - S02E20 - Girls, Interrupted",
    "T. Girls Interrupted.mp4"],
  ['will-grace-season-2_202407', "WILL & GRACE - S02E21 - There But for the Grace of Grace",
    "U. There But for the Grace of Grace.mp4"],
  ['will-grace-season-2_202407', "WILL & GRACE - S02E22 - My Best Friend's Tush",
    "V. My Best Friend's Tush.mp4"],
  ['will-grace-season-2_202407', "WILL & GRACE - S02E23-24 - Ben? Her?",
    "W. Ben, Her.mp4"],
],
  durations: {
  "will-grace-season-1::A. Love and Marriage.mp4": 1332,
  "will-grace-season-1::B. A New Lease on Life.mp4": 1245,
  "will-grace-season-1::C. Head Case.mp4": 1249,
  "will-grace-season-1::D. Between A Rock and Harlin's Place.mp4": 1227,
  "will-grace-season-1::E. Boo! Humbug.mp4": 1248,
  "will-grace-season-1::F. William, Tell.ia.mp4": 1256,
  "will-grace-season-1::G. Where There's A Will, There's No Way.ia.mp4": 1256,
  "will-grace-season-1::H. The Buying Game.ia.mp4": 1258,
  "will-grace-season-1::I. The Truth About Will and Dogs.ia.mp4": 1255,
  "will-grace-season-1::J. The Big Event.ia.mp4": 1258,
  "will-grace-season-1::K. Will on Ice.ia.mp4": 1254,
  "will-grace-season-1::L. My Fair Maid-y.ia.mp4": 1256,
  "will-grace-season-1::M. The Unsinkable Mommy Adler.ia.mp4": 1231,
  "will-grace-season-1::N. Big Brother is Coming Part 1.ia.mp4": 1249,
  "will-grace-season-1::O. Big Brother is Coming Part 2.ia.mp4": 1214,
  "will-grace-season-1::P. Yours Mine or Ours.ia.mp4": 1254,
  "will-grace-season-1::Q. Secrets and Lays.ia.mp4": 1257,
  "will-grace-season-1::R. Grace Replaced.ia.mp4": 1253,
  "will-grace-season-1::S. Will Works Out.ia.mp4": 1242,
  "will-grace-season-1::T. Saving Grace.ia.mp4": 1257,
  "will-grace-season-1::U. Alley Cats.ia.mp4": 1245,
  "will-grace-season-1::V. Object of My Rejection.ia.mp4": 1258,
  "will-grace-season-2_202407::A. Guess Who's Not Coming To Dinner.mp4": 1264,
  "will-grace-season-2_202407::B. Election.ia.mp4": 1271,
  "will-grace-season-2_202407::C. Das Boob.ia.mp4": 1272,
  "will-grace-season-2_202407::D. Who's Mom Is It Anyway.mp4": 1264,
  "will-grace-season-2_202407::E. Polk Defeats Truman.mp4": 1262,
  "will-grace-season-2_202407::F. To Serve And Disinfect.mp4": 1262,
  "will-grace-season-2_202407::G. Homo For The Holidays.mp4": 1221,
  "will-grace-season-2_202407::H. Terms of Employment.mp4": 1262,
  "will-grace-season-2_202407::I. I Never Promised You An Olive Garden.mp4": 1262,
  "will-grace-season-2_202407::J. Tea And A Total Lack Of Sympathy.mp4": 1262,
  "will-grace-season-2_202407::K. Seeds Of Discontent.mp4": 1263,
  "will-grace-season-2_202407::L. He's Coming Undone.mp4": 1262,
  "will-grace-season-2_202407::M. Oh Dad Poor Dad He's Kept Me in the Closet and I'm So Sad.mp4": 1264,
  "will-grace-season-2_202407::N. Acting Out.mp4": 1263,
  "will-grace-season-2_202407::O. Advise and Resent.mp4": 1263,
  "will-grace-season-2_202407::P. Hey La Hey La My Ex-Boyfriend's Back.mp4": 1264,
  "will-grace-season-2_202407::Q. The Hospital Show.mp4": 1258,
  "will-grace-season-2_202407::R. Sweet And Sour Charity.mp4": 1236,
  "will-grace-season-2_202407::S. An Affair To Forget.mp4": 1262,
  "will-grace-season-2_202407::T. Girls Interrupted.mp4": 1259,
  "will-grace-season-2_202407::U. There But for the Grace of Grace.mp4": 1261,
  "will-grace-season-2_202407::V. My Best Friend's Tush.mp4": 1261,
  "will-grace-season-2_202407::W. Ben, Her.mp4": 2583,
},
};
