window.SHOW = {
  id: "DextersLaboratorytheSeries",
  title: "Dexter's Laboratory the Series",
  art: "DextersLaboratorytheSeries.png",
  storageProgressKey: "dexterslaboratorytheseries-progress",
  storageSettingsKey: "dexterslaboratorytheseries-settings",
  nestedPaths: true,
  grouping: "season",
  segments: "none",
  episodes: [
  ["dexters-laboratory-the-complete-series", "DEXTER'S LABORATORY THE SERIES - S01E01 - Dexter s Laboratory",
    "Dexter_s_Laboratory_S01E01.mp4"],
  ["dexters-laboratory-the-complete-series", "DEXTER'S LABORATORY THE SERIES - S01E02 - Dexter s Laboratory",
    "Dexter_s_Laboratory_S01E02.mp4"],
  ["dexters-laboratory-the-complete-series", "DEXTER'S LABORATORY THE SERIES - S01E03 - Dexter s Laboratory",
    "Dexter_s_Laboratory_S01E03.mp4"],
  ["dexters-laboratory-the-complete-series", "DEXTER'S LABORATORY THE SERIES - S01E04 - Dexter s Laboratory",
    "Dexter_s_Laboratory_S01E04.mp4"],
  ["dexters-laboratory-the-complete-series", "DEXTER'S LABORATORY THE SERIES - S01E05 - Dexter s Laboratory",
    "Dexter_s_Laboratory_S01E05.mp4"],
  ["dexters-laboratory-the-complete-series", "DEXTER'S LABORATORY THE SERIES - S01E06 - Dexter s Laboratory",
    "Dexter_s_Laboratory_S01E06.mp4"],
  ["dexters-laboratory-the-complete-series", "DEXTER'S LABORATORY THE SERIES - S01E07 - Dexter s Laboratory",
    "Dexter_s_Laboratory_S01E07.mp4"],
  ["dexters-laboratory-the-complete-series", "DEXTER'S LABORATORY THE SERIES - S01E08 - Dexter s Laboratory",
    "Dexter_s_Laboratory_S01E08.mp4"],
  ["dexters-laboratory-the-complete-series", "DEXTER'S LABORATORY THE SERIES - S01E09 - Dexter s Laboratory",
    "Dexter_s_Laboratory_S01E09.mp4"],
  ["dexters-laboratory-the-complete-series", "DEXTER'S LABORATORY THE SERIES - S01E10 - Dexter s Laboratory",
    "Dexter_s_Laboratory_S01E10.mp4"],
  ["dexters-laboratory-the-complete-series", "DEXTER'S LABORATORY THE SERIES - S01E11 - Dexter s Laboratory",
    "Dexter_s_Laboratory_S01E11.mp4"],
  ["dexters-laboratory-the-complete-series", "DEXTER'S LABORATORY THE SERIES - S01E12 - Dexter s Laboratory",
    "Dexter_s_Laboratory_S01E12.mp4"],
  ["dexters-laboratory-the-complete-series", "DEXTER'S LABORATORY THE SERIES - S01E13 - Dexter s Laboratory",
    "Dexter_s_Laboratory_S01E13.mp4"],
  ["dexters-laboratory-the-complete-series", "DEXTER'S LABORATORY THE SERIES - S02E01 - Dexter s Laboratory",
    "Dexter_s_Laboratory_S02E01.mp4"],
  ["dexters-laboratory-the-complete-series", "DEXTER'S LABORATORY THE SERIES - S02E02 - Dexter s Laboratory",
    "Dexter_s_Laboratory_S02E02.mp4"],
  ["dexters-laboratory-the-complete-series", "DEXTER'S LABORATORY THE SERIES - S02E03 - Dexter s Laboratory",
    "Dexter_s_Laboratory_S02E03.mp4"],
  ["dexters-laboratory-the-complete-series", "DEXTER'S LABORATORY THE SERIES - S02E04 - Dexter s Laboratory",
    "Dexter_s_Laboratory_S02E04.mp4"],
  ["dexters-laboratory-the-complete-series", "DEXTER'S LABORATORY THE SERIES - S02E05 - Dexter s Laboratory",
    "Dexter_s_Laboratory_S02E05.mp4"],
  ["dexters-laboratory-the-complete-series", "DEXTER'S LABORATORY THE SERIES - S02E06 - Dexter s Laboratory",
    "Dexter_s_Laboratory_S02E06.mp4"],
  ["dexters-laboratory-the-complete-series", "DEXTER'S LABORATORY THE SERIES - S02E07 - Dexter s Laboratory",
    "Dexter_s_Laboratory_S02E07.mp4"],
  ["dexters-laboratory-the-complete-series", "DEXTER'S LABORATORY THE SERIES - S02E08 - Dexter s Laboratory",
    "Dexter_s_Laboratory_S02E08.mp4"],
  ["dexters-laboratory-the-complete-series", "DEXTER'S LABORATORY THE SERIES - S02E09 - Dexter s Laboratory",
    "Dexter_s_Laboratory_S02E09.mp4"],
  ["dexters-laboratory-the-complete-series", "DEXTER'S LABORATORY THE SERIES - S02E10 - Dexter s Laboratory",
    "Dexter_s_Laboratory_S02E10.mp4"],
  ["dexters-laboratory-the-complete-series", "DEXTER'S LABORATORY THE SERIES - S02E11 - Dexter s Laboratory",
    "Dexter_s_Laboratory_S02E11.mp4"],
  ["dexters-laboratory-the-complete-series", "DEXTER'S LABORATORY THE SERIES - S02E12 - Dexter s Laboratory",
    "Dexter_s_Laboratory_S02E12.mp4"],
  ["dexters-laboratory-the-complete-series", "DEXTER'S LABORATORY THE SERIES - S02E13 - Dexter s Laboratory",
    "Dexter_s_Laboratory_S02E13.mp4"],
  ["dexters-laboratory-the-complete-series", "DEXTER'S LABORATORY THE SERIES - S02E14 - Dexter s Laboratory",
    "Dexter_s_Laboratory_S02E14.mp4"],
  ["dexters-laboratory-the-complete-series", "DEXTER'S LABORATORY THE SERIES - S02E15 - Dexter s Laboratory",
    "Dexter_s_Laboratory_S02E15.mp4"],
  ["dexters-laboratory-the-complete-series", "DEXTER'S LABORATORY THE SERIES - S02E16 - Dexter s Laboratory",
    "Dexter_s_Laboratory_S02E16.mp4"],
  ["dexters-laboratory-the-complete-series", "DEXTER'S LABORATORY THE SERIES - S02E17 - Dexter s Laboratory",
    "Dexter_s_Laboratory_S02E17.mp4"],
  ["dexters-laboratory-the-complete-series", "DEXTER'S LABORATORY THE SERIES - S02E18 - Dexter s Laboratory",
    "Dexter_s_Laboratory_S02E18.mp4"],
  ["dexters-laboratory-the-complete-series", "DEXTER'S LABORATORY THE SERIES - S02E19 - Dexter s Laboratory",
    "Dexter_s_Laboratory_S02E19.mp4"],
  ["dexters-laboratory-the-complete-series", "DEXTER'S LABORATORY THE SERIES - S02E20 - Dexter s Laboratory",
    "Dexter_s_Laboratory_S02E20.mp4"],
  ["dexters-laboratory-the-complete-series", "DEXTER'S LABORATORY THE SERIES - S02E21 - Dexter s Laboratory",
    "Dexter_s_Laboratory_S02E21.mp4"],
  ["dexters-laboratory-the-complete-series", "DEXTER'S LABORATORY THE SERIES - S02E22 - Dexter s Laboratory",
    "Dexter_s_Laboratory_S02E22.mp4"],
  ["dexters-laboratory-the-complete-series", "DEXTER'S LABORATORY THE SERIES - S02E23 - Dexter s Laboratory",
    "Dexter_s_Laboratory_S02E23.mp4"],
  ["dexters-laboratory-the-complete-series", "DEXTER'S LABORATORY THE SERIES - S02E24 - Dexter s Laboratory",
    "Dexter_s_Laboratory_S02E24.mp4"],
  ["dexters-laboratory-the-complete-series", "DEXTER'S LABORATORY THE SERIES - S02E25 - Dexter s Laboratory",
    "Dexter_s_Laboratory_S02E25.mp4"],
  ["dexters-laboratory-the-complete-series", "DEXTER'S LABORATORY THE SERIES - S02E26 - Dexter s Laboratory",
    "Dexter_s_Laboratory_S02E26.mp4"],
  ["dexters-laboratory-the-complete-series", "DEXTER'S LABORATORY THE SERIES - S02E27 - Dexter s Laboratory",
    "Dexter_s_Laboratory_S02E27.mp4"],
  ["dexters-laboratory-the-complete-series", "DEXTER'S LABORATORY THE SERIES - S02E28 - Dexter s Laboratory",
    "Dexter_s_Laboratory_S02E28.mp4"],
  ["dexters-laboratory-the-complete-series", "DEXTER'S LABORATORY THE SERIES - S02E29 - Dexter s Laboratory",
    "Dexter_s_Laboratory_S02E29.mp4"],
  ["dexters-laboratory-the-complete-series", "DEXTER'S LABORATORY THE SERIES - S02E30 - Dexter s Laboratory",
    "Dexter_s_Laboratory_S02E30.mp4"],
  ["dexters-laboratory-the-complete-series", "DEXTER'S LABORATORY THE SERIES - S02E31 - Dexter s Laboratory",
    "Dexter_s_Laboratory_S02E31.mp4"],
  ["dexters-laboratory-the-complete-series", "DEXTER'S LABORATORY THE SERIES - S02E32 - Dexter s Laboratory",
    "Dexter_s_Laboratory_S02E32.mp4"],
  ["dexters-laboratory-the-complete-series", "DEXTER'S LABORATORY THE SERIES - S02E33 - Dexter s Laboratory",
    "Dexter_s_Laboratory_S02E33.mp4"],
  ["dexters-laboratory-the-complete-series", "DEXTER'S LABORATORY THE SERIES - S02E34 - Dexter s Laboratory",
    "Dexter_s_Laboratory_S02E34.mp4"],
  ["dexters-laboratory-the-complete-series", "DEXTER'S LABORATORY THE SERIES - S02E35 - Dexter s Laboratory",
    "Dexter_s_Laboratory_S02E35.mp4"],
  ["dexters-laboratory-the-complete-series", "DEXTER'S LABORATORY THE SERIES - S02E36 - Dexter s Laboratory",
    "Dexter_s_Laboratory_S02E36.mp4"],
  ["dexters-laboratory-the-complete-series", "DEXTER'S LABORATORY THE SERIES - S02E37 - Dexter s Laboratory",
    "Dexter_s_Laboratory_S02E37.mp4"],
  ["dexters-laboratory-the-complete-series", "DEXTER'S LABORATORY THE SERIES - S02E38 - Dexter s Laboratory",
    "Dexter_s_Laboratory_S02E38.mp4"],
  ["dexters-laboratory-the-complete-series", "DEXTER'S LABORATORY THE SERIES - S02E39 - Dexter s Laboratory",
    "Dexter_s_Laboratory_S02E39.mp4"],
  ["dexters-laboratory-the-complete-series", "DEXTER'S LABORATORY THE SERIES - S03E01 - Dexter s Laboratory",
    "Dexter_s_Laboratory_S03E01.mp4"],
  ["dexters-laboratory-the-complete-series", "DEXTER'S LABORATORY THE SERIES - S03E02 - Dexter s Laboratory",
    "Dexter_s_Laboratory_S03E02.mp4"],
  ["dexters-laboratory-the-complete-series", "DEXTER'S LABORATORY THE SERIES - S03E03 - Dexter s Laboratory",
    "Dexter_s_Laboratory_S03E03.mp4"],
  ["dexters-laboratory-the-complete-series", "DEXTER'S LABORATORY THE SERIES - S03E04 - Dexter s Laboratory",
    "Dexter_s_Laboratory_S03E04.mp4"],
  ["dexters-laboratory-the-complete-series", "DEXTER'S LABORATORY THE SERIES - S03E05 - Dexter s Laboratory",
    "Dexter_s_Laboratory_S03E05.mp4"],
  ["dexters-laboratory-the-complete-series", "DEXTER'S LABORATORY THE SERIES - S03E06 - Dexter s Laboratory",
    "Dexter_s_Laboratory_S03E06.mp4"],
  ["dexters-laboratory-the-complete-series", "DEXTER'S LABORATORY THE SERIES - S03E07 - Dexter s Laboratory",
    "Dexter_s_Laboratory_S03E07.mp4"],
  ["dexters-laboratory-the-complete-series", "DEXTER'S LABORATORY THE SERIES - S03E08 - Dexter s Laboratory",
    "Dexter_s_Laboratory_S03E08.mp4"],
  ["dexters-laboratory-the-complete-series", "DEXTER'S LABORATORY THE SERIES - S03E09 - Dexter s Laboratory",
    "Dexter_s_Laboratory_S03E09.mp4"],
  ["dexters-laboratory-the-complete-series", "DEXTER'S LABORATORY THE SERIES - S03E10 - Dexter s Laboratory",
    "Dexter_s_Laboratory_S03E10.mp4"],
  ["dexters-laboratory-the-complete-series", "DEXTER'S LABORATORY THE SERIES - S03E11 - Dexter s Laboratory",
    "Dexter_s_Laboratory_S03E11.mp4"],
  ["dexters-laboratory-the-complete-series", "DEXTER'S LABORATORY THE SERIES - S03E12 - Dexter s Laboratory",
    "Dexter_s_Laboratory_S03E12.mp4"],
  ["dexters-laboratory-the-complete-series", "DEXTER'S LABORATORY THE SERIES - S03E13 - Dexter s Laboratory",
    "Dexter_s_Laboratory_S03E13.mp4"],
  ["dexters-laboratory-the-complete-series", "DEXTER'S LABORATORY THE SERIES - S04E01 - Dexter s Laboratory",
    "Dexter_s_Laboratory_S04E01.mp4"],
  ["dexters-laboratory-the-complete-series", "DEXTER'S LABORATORY THE SERIES - S04E02 - Dexter s Laboratory",
    "Dexter_s_Laboratory_S04E02.mp4"],
  ["dexters-laboratory-the-complete-series", "DEXTER'S LABORATORY THE SERIES - S04E03 - Dexter s Laboratory",
    "Dexter_s_Laboratory_S04E03.mp4"],
  ["dexters-laboratory-the-complete-series", "DEXTER'S LABORATORY THE SERIES - S04E04 - Dexter s Laboratory",
    "Dexter_s_Laboratory_S04E04.mp4"],
  ["dexters-laboratory-the-complete-series", "DEXTER'S LABORATORY THE SERIES - S04E05 - Dexter s Laboratory",
    "Dexter_s_Laboratory_S04E05.mp4"],
  ["dexters-laboratory-the-complete-series", "DEXTER'S LABORATORY THE SERIES - S04E06 - Dexter s Laboratory",
    "Dexter_s_Laboratory_S04E06.mp4"],
  ["dexters-laboratory-the-complete-series", "DEXTER'S LABORATORY THE SERIES - S04E07 - Dexter s Laboratory",
    "Dexter_s_Laboratory_S04E07.mp4"],
  ["dexters-laboratory-the-complete-series", "DEXTER'S LABORATORY THE SERIES - S04E08 - Dexter s Laboratory",
    "Dexter_s_Laboratory_S04E08.mp4"],
  ["dexters-laboratory-the-complete-series", "DEXTER'S LABORATORY THE SERIES - S04E09 - Dexter s Laboratory",
    "Dexter_s_Laboratory_S04E09.mp4"],
  ["dexters-laboratory-the-complete-series", "DEXTER'S LABORATORY THE SERIES - S04E10 - Dexter s Laboratory",
    "Dexter_s_Laboratory_S04E10.mp4"],
  ["dexters-laboratory-the-complete-series", "DEXTER'S LABORATORY THE SERIES - S04E11 - Dexter s Laboratory",
    "Dexter_s_Laboratory_S04E11.mp4"],
  ["dexters-laboratory-the-complete-series", "DEXTER'S LABORATORY THE SERIES - S04E12 - Dexter s Laboratory",
    "Dexter_s_Laboratory_S04E12.mp4"],
  ["dexters-laboratory-the-complete-series", "DEXTER'S LABORATORY THE SERIES - S04E13 - Dexter s Laboratory",
    "Dexter_s_Laboratory_S04E13.mp4"],
],
  durations: {
  "dexters-laboratory-the-complete-series::Dexter_s_Laboratory_S01E01.mp4": 1326,
  "dexters-laboratory-the-complete-series::Dexter_s_Laboratory_S01E02.mp4": 1323,
  "dexters-laboratory-the-complete-series::Dexter_s_Laboratory_S01E03.mp4": 1329,
  "dexters-laboratory-the-complete-series::Dexter_s_Laboratory_S01E04.mp4": 1349,
  "dexters-laboratory-the-complete-series::Dexter_s_Laboratory_S01E05.mp4": 1316,
  "dexters-laboratory-the-complete-series::Dexter_s_Laboratory_S01E06.mp4": 1314,
  "dexters-laboratory-the-complete-series::Dexter_s_Laboratory_S01E07.mp4": 1337,
  "dexters-laboratory-the-complete-series::Dexter_s_Laboratory_S01E08.mp4": 1335,
  "dexters-laboratory-the-complete-series::Dexter_s_Laboratory_S01E09.mp4": 1337,
  "dexters-laboratory-the-complete-series::Dexter_s_Laboratory_S01E10.mp4": 1331,
  "dexters-laboratory-the-complete-series::Dexter_s_Laboratory_S01E11.mp4": 1333,
  "dexters-laboratory-the-complete-series::Dexter_s_Laboratory_S01E12.mp4": 1333,
  "dexters-laboratory-the-complete-series::Dexter_s_Laboratory_S01E13.mp4": 1338,
  "dexters-laboratory-the-complete-series::Dexter_s_Laboratory_S02E01.mp4": 1334,
  "dexters-laboratory-the-complete-series::Dexter_s_Laboratory_S02E02.mp4": 1340,
  "dexters-laboratory-the-complete-series::Dexter_s_Laboratory_S02E03.mp4": 1359,
  "dexters-laboratory-the-complete-series::Dexter_s_Laboratory_S02E04.mp4": 1330,
  "dexters-laboratory-the-complete-series::Dexter_s_Laboratory_S02E05.mp4": 1334,
  "dexters-laboratory-the-complete-series::Dexter_s_Laboratory_S02E06.mp4": 1335,
  "dexters-laboratory-the-complete-series::Dexter_s_Laboratory_S02E07.mp4": 1340,
  "dexters-laboratory-the-complete-series::Dexter_s_Laboratory_S02E08.mp4": 1403,
  "dexters-laboratory-the-complete-series::Dexter_s_Laboratory_S02E09.mp4": 1336,
  "dexters-laboratory-the-complete-series::Dexter_s_Laboratory_S02E10.mp4": 1330,
  "dexters-laboratory-the-complete-series::Dexter_s_Laboratory_S02E11.mp4": 1338,
  "dexters-laboratory-the-complete-series::Dexter_s_Laboratory_S02E12.mp4": 1342,
  "dexters-laboratory-the-complete-series::Dexter_s_Laboratory_S02E13.mp4": 1338,
  "dexters-laboratory-the-complete-series::Dexter_s_Laboratory_S02E14.mp4": 1339,
  "dexters-laboratory-the-complete-series::Dexter_s_Laboratory_S02E15.mp4": 1335,
  "dexters-laboratory-the-complete-series::Dexter_s_Laboratory_S02E16.mp4": 1337,
  "dexters-laboratory-the-complete-series::Dexter_s_Laboratory_S02E17.mp4": 1338,
  "dexters-laboratory-the-complete-series::Dexter_s_Laboratory_S02E18.mp4": 1337,
  "dexters-laboratory-the-complete-series::Dexter_s_Laboratory_S02E19.mp4": 1339,
  "dexters-laboratory-the-complete-series::Dexter_s_Laboratory_S02E20.mp4": 1337,
  "dexters-laboratory-the-complete-series::Dexter_s_Laboratory_S02E21.mp4": 1339,
  "dexters-laboratory-the-complete-series::Dexter_s_Laboratory_S02E22.mp4": 1334,
  "dexters-laboratory-the-complete-series::Dexter_s_Laboratory_S02E23.mp4": 1360,
  "dexters-laboratory-the-complete-series::Dexter_s_Laboratory_S02E24.mp4": 1364,
  "dexters-laboratory-the-complete-series::Dexter_s_Laboratory_S02E25.mp4": 1338,
  "dexters-laboratory-the-complete-series::Dexter_s_Laboratory_S02E26.mp4": 1335,
  "dexters-laboratory-the-complete-series::Dexter_s_Laboratory_S02E27.mp4": 1334,
  "dexters-laboratory-the-complete-series::Dexter_s_Laboratory_S02E28.mp4": 1345,
  "dexters-laboratory-the-complete-series::Dexter_s_Laboratory_S02E29.mp4": 1341,
  "dexters-laboratory-the-complete-series::Dexter_s_Laboratory_S02E30.mp4": 1344,
  "dexters-laboratory-the-complete-series::Dexter_s_Laboratory_S02E31.mp4": 1338,
  "dexters-laboratory-the-complete-series::Dexter_s_Laboratory_S02E32.mp4": 1335,
  "dexters-laboratory-the-complete-series::Dexter_s_Laboratory_S02E33.mp4": 1350,
  "dexters-laboratory-the-complete-series::Dexter_s_Laboratory_S02E34.mp4": 1336,
  "dexters-laboratory-the-complete-series::Dexter_s_Laboratory_S02E35.mp4": 1353,
  "dexters-laboratory-the-complete-series::Dexter_s_Laboratory_S02E36.mp4": 1340,
  "dexters-laboratory-the-complete-series::Dexter_s_Laboratory_S02E37.mp4": 1337,
  "dexters-laboratory-the-complete-series::Dexter_s_Laboratory_S02E38.mp4": 1347,
  "dexters-laboratory-the-complete-series::Dexter_s_Laboratory_S02E39.mp4": 1481,
  "dexters-laboratory-the-complete-series::Dexter_s_Laboratory_S03E01.mp4": 1340,
  "dexters-laboratory-the-complete-series::Dexter_s_Laboratory_S03E02.mp4": 1337,
  "dexters-laboratory-the-complete-series::Dexter_s_Laboratory_S03E03.mp4": 1332,
  "dexters-laboratory-the-complete-series::Dexter_s_Laboratory_S03E04.mp4": 1333,
  "dexters-laboratory-the-complete-series::Dexter_s_Laboratory_S03E05.mp4": 1337,
  "dexters-laboratory-the-complete-series::Dexter_s_Laboratory_S03E06.mp4": 1340,
  "dexters-laboratory-the-complete-series::Dexter_s_Laboratory_S03E07.mp4": 1325,
  "dexters-laboratory-the-complete-series::Dexter_s_Laboratory_S03E08.mp4": 1339,
  "dexters-laboratory-the-complete-series::Dexter_s_Laboratory_S03E09.mp4": 1314,
  "dexters-laboratory-the-complete-series::Dexter_s_Laboratory_S03E10.mp4": 1341,
  "dexters-laboratory-the-complete-series::Dexter_s_Laboratory_S03E11.mp4": 1326,
  "dexters-laboratory-the-complete-series::Dexter_s_Laboratory_S03E12.mp4": 1328,
  "dexters-laboratory-the-complete-series::Dexter_s_Laboratory_S03E13.mp4": 1348,
  "dexters-laboratory-the-complete-series::Dexter_s_Laboratory_S04E01.mp4": 1335,
  "dexters-laboratory-the-complete-series::Dexter_s_Laboratory_S04E02.mp4": 1315,
  "dexters-laboratory-the-complete-series::Dexter_s_Laboratory_S04E03.mp4": 1304,
  "dexters-laboratory-the-complete-series::Dexter_s_Laboratory_S04E04.mp4": 1341,
  "dexters-laboratory-the-complete-series::Dexter_s_Laboratory_S04E05.mp4": 1327,
  "dexters-laboratory-the-complete-series::Dexter_s_Laboratory_S04E06.mp4": 1347,
  "dexters-laboratory-the-complete-series::Dexter_s_Laboratory_S04E07.mp4": 1325,
  "dexters-laboratory-the-complete-series::Dexter_s_Laboratory_S04E08.mp4": 1318,
  "dexters-laboratory-the-complete-series::Dexter_s_Laboratory_S04E09.mp4": 1308,
  "dexters-laboratory-the-complete-series::Dexter_s_Laboratory_S04E10.mp4": 1346,
  "dexters-laboratory-the-complete-series::Dexter_s_Laboratory_S04E11.mp4": 1347,
  "dexters-laboratory-the-complete-series::Dexter_s_Laboratory_S04E12.mp4": 1347,
  "dexters-laboratory-the-complete-series::Dexter_s_Laboratory_S04E13.mp4": 1312,
},
};
