window.SHOW = {
  id: "WhitestKidsUKnow",
  title: "The Whitest Kids U'Know",
  art: "WhitestKidsUKnow.jpg",
  storageProgressKey: "whitestkidsuknow-progress",
  storageSettingsKey: "whitestkidsuknow-settings",
  nestedPaths: true,
  grouping: "season",
  segments: "none",
  // 50 files hold 60 episodes — season 3 bundles two per file, as its
  // S03E01-02 codes record. The card headlines episodes, so expand the ranges.
  cardCountBasis: "episodes",
  episodes: [
  ['WhitestKidsUKnowSeries', "THE WHITEST KIDS U'KNOW - S01E01 - Hitler Rap, Sexy Fawn, Get a New Daddy",
    "S1E1.mp4"],
  ['WhitestKidsUKnowSeries', "THE WHITEST KIDS U'KNOW - S01E02 - Movie Pitching Guy, Whip Boy, Brothers in Arms",
    "S1E2.mp4"],
  ['WhitestKidsUKnowSeries', "THE WHITEST KIDS U'KNOW - S01E03 - Cubicle Boss, Pimp Pun Disaster, Whiskey Super Size",
    "S1E3.mp4"],
  ['WhitestKidsUKnowSeries', "THE WHITEST KIDS U'KNOW - S01E04 - Slow Jerk, Bigfoot, Race War",
    "S1E4.mp4"],
  ['WhitestKidsUKnowSeries', "THE WHITEST KIDS U'KNOW - S01E05 - Acting Class, Pie, Demon Ouija Board",
    "S1E5.mp4"],
  ['WhitestKidsUKnowSeries', "THE WHITEST KIDS U'KNOW - S01E06 - Dear Black People, Accidental Puke, Kool-Aid",
    "S1E6.mp4"],
  ['WhitestKidsUKnowSeries', "THE WHITEST KIDS U'KNOW - S01E07 - Dating Game, You're Peeing on My Leg, John Wilkes Booth",
    "S1E7.mp4"],
  ['WhitestKidsUKnowSeries', "THE WHITEST KIDS U'KNOW - S01E08 - Scaring Babies, Funeral Request, Opposite Day Lawyer",
    "S1E8.mp4"],
  ['WhitestKidsUKnowSeries', "THE WHITEST KIDS U'KNOW - S01E09 - Glory Hole, Attention Guy, Tattoo Parlor",
    "S1E9.mp4"],
  ['WhitestKidsUKnowSeries', "THE WHITEST KIDS U'KNOW - S01E10 - We Gon' Make Love, Motorcycle Mama, Mountain of Chairs",
    "S1E10.mp4"],
  ['WhitestKidsUKnowSeries', "THE WHITEST KIDS U'KNOW - S02E01 - Sam's Nut, Neil & Buzz, Air Dry",
    "S2E1.mp4"],
  ['WhitestKidsUKnowSeries', "THE WHITEST KIDS U'KNOW - S02E02 - Never Song, Feeler Doc, Blue Whale Dick",
    "S2E2.mp4"],
  ['WhitestKidsUKnowSeries', "THE WHITEST KIDS U'KNOW - S02E03 - Weird, Jack and Oswald, Totally Gay for America",
    "S2E3.mp4"],
  ['WhitestKidsUKnowSeries', "THE WHITEST KIDS U'KNOW - S02E04 - Forever Puppies, Francis Scott Key, Opus",
    "S2E4.mp4"],
  ['WhitestKidsUKnowSeries', "THE WHITEST KIDS U'KNOW - S02E05 - Reverse Psychology, Kicking Guy, Whale Tail, Nail Gun",
    "S2E5.mp4"],
  ['WhitestKidsUKnowSeries', "THE WHITEST KIDS U'KNOW - S02E06 - Forest Whitaker, Period Sketch, Our Label is Run by Homos",
    "S2E6.mp4"],
  ['WhitestKidsUKnowSeries', "THE WHITEST KIDS U'KNOW - S02E07 - Tar Toast, Drunk Dad, Time Travel Friends",
    "S2E7.mp4"],
  ['WhitestKidsUKnowSeries', "THE WHITEST KIDS U'KNOW - S02E08 - Face Off, Auto Erotic, Good Morning Dad",
    "S2E8.mp4"],
  ['WhitestKidsUKnowSeries', "THE WHITEST KIDS U'KNOW - S02E09 - Invincible Kid, Keg Stand Dad, Virtual Reality",
    "S2E9.mp4"],
  ['WhitestKidsUKnowSeries', "THE WHITEST KIDS U'KNOW - S02E10 - Blind Guys, Sonic Gets Mugged, The Dinosaur Rap",
    "S2E10.mp4"],
  ['WhitestKidsUKnowSeries', "THE WHITEST KIDS U'KNOW - S03E01-02 - Chaplin, Bible Stories, Feline Delights, Dumb Newscast, Car Dealership / Little Rascals, Call of Duty, God Says Song",
    "S3E1&2.mp4"],
  ['WhitestKidsUKnowSeries', "THE WHITEST KIDS U'KNOW - S03E03-04 - Water Balloons, Hot Dog Timmy, JJ Marvin / Foot Touch Oh Gross Gay Sketch, Bad Panda, Gandalf",
    "S3E3&4.mp4"],
  ['WhitestKidsUKnowSeries', "THE WHITEST KIDS U'KNOW - S03E05-06 - Presidential Props, Island Cannibal, Helicopter Door, Super Dog / Trent Reznor, Homeschool, Telekinesis, Dog Park",
    "S3E5&6.mp4"],
  ['WhitestKidsUKnowSeries', "THE WHITEST KIDS U'KNOW - S03E07-08 - Asian Hooker Business, Skatefall, Earthquake, Bonersong / Tit Slap, John Hancock, Bad Dominatrix, Bobo the Monkey",
    "S3E7&8.mp4"],
  ['WhitestKidsUKnowSeries', "THE WHITEST KIDS U'KNOW - S03E09-10 - Horses Love, Lovliest Bride, Fight Club, Pop Tart / Shoshan, Lawnmower Dad, Elves, Blue Hair",
    "S3E9&10.mp4"],
  ['WhitestKidsUKnowSeries', "THE WHITEST KIDS U'KNOW - S03E11-12 - Shitchest Boner Neck, Crack, What is It Baby, Last Action Hero / Mustard Gas, Kindergarden Cons, Table Monster",
    "S3E11&12.mp4"],
  ['WhitestKidsUKnowSeries', "THE WHITEST KIDS U'KNOW - S03E13-14 - Genie, Epilepsy Test, Throw Up Employee / Grapist, Lottery, Ronnie, John & George",
    "S3E13&14.mp4"],
  ['WhitestKidsUKnowSeries', "THE WHITEST KIDS U'KNOW - S03E15-16 - Suicide Show, Anarchy, RC Glow / Courtroom Stripper, Dad Story, Life Goes Alien",
    "S3E15&16.mp4"],
  ['WhitestKidsUKnowSeries', "THE WHITEST KIDS U'KNOW - S03E17-18 - Wheel of Money, Butler Sketch, Hiking Documentary, Backseat / Edge of Space, Daddy with a Donkey, T-Shirt, The Hippo Song",
    "S3E17&18.mp4"],
  ['WhitestKidsUKnowSeries', "THE WHITEST KIDS U'KNOW - S03E19-20 - Jerkocaust, Trophy Coach, Helicopter Wife Cheating / Another Astronaut Sketch, Not Particularly Sure, Maroon President, Bathroom Camera",
    "S3E19&20.mp4"],
  ['WhitestKidsUKnowSeries', "THE WHITEST KIDS U'KNOW - S04E01 - Grandma's Cookies, My Mouth Stuck Open, Alien Autopsy",
    "S4E1.mp4"],
  ['WhitestKidsUKnowSeries', "THE WHITEST KIDS U'KNOW - S04E02 - You Talkin' to Me, Dr. Kyle, Changing Channels",
    "S4E2.mp4"],
  ['WhitestKidsUKnowSeries', "THE WHITEST KIDS U'KNOW - S04E03 - Spaghetti Dinner Date, Mission Impossible, Walk of Shame",
    "S4E3.mp4"],
  ['WhitestKidsUKnowSeries', "THE WHITEST KIDS U'KNOW - S04E04 - Old Man Winters, Booger Blasters, Moon Landing",
    "S4E4.mp4"],
  ['WhitestKidsUKnowSeries', "THE WHITEST KIDS U'KNOW - S04E05 - Jumbo Tron, Kid Mechanic, Bananas",
    "S4E5.mp4"],
  ['WhitestKidsUKnowSeries', "THE WHITEST KIDS U'KNOW - S04E06 - John Cleese, 50 Cal Bar, Juror",
    "S4E6.mp4"],
  ['WhitestKidsUKnowSeries', "THE WHITEST KIDS U'KNOW - S04E07 - Cash Quiz, Great Grandmas, History Reset",
    "S4E7.mp4"],
  ['WhitestKidsUKnowSeries', "THE WHITEST KIDS U'KNOW - S04E08 - Valentine's Day, Simple Chore, Pun Army, Chad's Rad",
    "S4E8.mp4"],
  ['WhitestKidsUKnowSeries', "THE WHITEST KIDS U'KNOW - S04E09 - Babe Magnet, Freaky Thursday, One of You is, Hell's Kitchen",
    "S4E9.mp4"],
  ['WhitestKidsUKnowSeries', "THE WHITEST KIDS U'KNOW - S04E10 - Halloweiner, Things We Need, Landmine Factory, Job Interview Mess Up",
    "S4E10.mp4"],
  ['WhitestKidsUKnowSeries', "THE WHITEST KIDS U'KNOW - S05E01 - Baked Beans, War Letter, Finger Ring Friends",
    "S5E1.mp4"],
  ['WhitestKidsUKnowSeries', "THE WHITEST KIDS U'KNOW - S05E02 - Slo-mo Squirrel, Wedding Flip-Flop, Ocean 2.0, First Date",
    "S5E2.mp4"],
  ['WhitestKidsUKnowSeries', "THE WHITEST KIDS U'KNOW - S05E03 - Jizzle, Ants!, Darren & the Giraffe, Bikini Day",
    "S5E3.mp4"],
  ['WhitestKidsUKnowSeries', "THE WHITEST KIDS U'KNOW - S05E04 - Firetruck Pullover, Spanking Dads, Careful Commandos, Teachers' Union, Didgeradoo",
    "S5E4.mp4"],
  ['WhitestKidsUKnowSeries', "THE WHITEST KIDS U'KNOW - S05E05 - Black Light, Stork Factor, CW5",
    "S5E5.mp4"],
  ['WhitestKidsUKnowSeries', "THE WHITEST KIDS U'KNOW - S05E06 - Dad Will Take Care of It, Bad Drivers, Hot Sister, Making Animals Kiss",
    "S5E6.mp4"],
  ['WhitestKidsUKnowSeries', "THE WHITEST KIDS U'KNOW - S05E07 - Going Home Alone, Liquor Store Robbery, Pledge of Allegiance, Escape Artist",
    "S5E7.mp4"],
  ['WhitestKidsUKnowSeries', "THE WHITEST KIDS U'KNOW - S05E08 - Timmy Future, Baby Traits, Horse Announcer",
    "S5E8.mp4"],
  ['WhitestKidsUKnowSeries', "THE WHITEST KIDS U'KNOW - S05E09 - Worst Orchestra, Come Down Here, Spaghettios, Homeless Show, Cactus Wasp",
    "S5E9.mp4"],
  ['WhitestKidsUKnowSeries', "THE WHITEST KIDS U'KNOW - S05E10 - Mom Phone, It Was Pretty Good, Sophomores",
    "S5E10.mp4"],
],
  durations: {
  "WhitestKidsUKnowSeries::S1E1.mp4": 1313,
  "WhitestKidsUKnowSeries::S1E2.mp4": 1309,
  "WhitestKidsUKnowSeries::S1E3.mp4": 1312,
  "WhitestKidsUKnowSeries::S1E4.mp4": 1309,
  "WhitestKidsUKnowSeries::S1E5.mp4": 1308,
  "WhitestKidsUKnowSeries::S1E6.mp4": 1312,
  "WhitestKidsUKnowSeries::S1E7.mp4": 1312,
  "WhitestKidsUKnowSeries::S1E8.mp4": 1309,
  "WhitestKidsUKnowSeries::S1E9.mp4": 1310,
  "WhitestKidsUKnowSeries::S1E10.mp4": 1312,
  "WhitestKidsUKnowSeries::S2E1.mp4": 1336,
  "WhitestKidsUKnowSeries::S2E2.mp4": 1323,
  "WhitestKidsUKnowSeries::S2E3.mp4": 1338,
  "WhitestKidsUKnowSeries::S2E4.mp4": 1325,
  "WhitestKidsUKnowSeries::S2E5.mp4": 1354,
  "WhitestKidsUKnowSeries::S2E6.mp4": 1231,
  "WhitestKidsUKnowSeries::S2E7.mp4": 1250,
  "WhitestKidsUKnowSeries::S2E8.mp4": 1333,
  "WhitestKidsUKnowSeries::S2E9.mp4": 1323,
  "WhitestKidsUKnowSeries::S2E10.mp4": 1364,
  "WhitestKidsUKnowSeries::S3E1&2.mp4": 1432,
  "WhitestKidsUKnowSeries::S3E3&4.mp4": 1461,
  "WhitestKidsUKnowSeries::S3E5&6.mp4": 1396,
  "WhitestKidsUKnowSeries::S3E7&8.mp4": 1304,
  "WhitestKidsUKnowSeries::S3E9&10.mp4": 1384,
  "WhitestKidsUKnowSeries::S3E11&12.mp4": 1395,
  "WhitestKidsUKnowSeries::S3E13&14.mp4": 1298,
  "WhitestKidsUKnowSeries::S3E15&16.mp4": 1221,
  "WhitestKidsUKnowSeries::S3E17&18.mp4": 1312,
  "WhitestKidsUKnowSeries::S3E19&20.mp4": 1349,
  "WhitestKidsUKnowSeries::S4E1.mp4": 1424,
  "WhitestKidsUKnowSeries::S4E2.mp4": 1335,
  "WhitestKidsUKnowSeries::S4E3.mp4": 1419,
  "WhitestKidsUKnowSeries::S4E4.mp4": 1336,
  "WhitestKidsUKnowSeries::S4E5.mp4": 1411,
  "WhitestKidsUKnowSeries::S4E6.mp4": 1423,
  "WhitestKidsUKnowSeries::S4E7.mp4": 1369,
  "WhitestKidsUKnowSeries::S4E8.mp4": 1259,
  "WhitestKidsUKnowSeries::S4E9.mp4": 1287,
  "WhitestKidsUKnowSeries::S4E10.mp4": 1262,
  "WhitestKidsUKnowSeries::S5E1.mp4": 1354,
  "WhitestKidsUKnowSeries::S5E2.mp4": 1354,
  "WhitestKidsUKnowSeries::S5E3.mp4": 1354,
  "WhitestKidsUKnowSeries::S5E4.mp4": 1354,
  "WhitestKidsUKnowSeries::S5E5.mp4": 1354,
  "WhitestKidsUKnowSeries::S5E6.mp4": 1354,
  "WhitestKidsUKnowSeries::S5E7.mp4": 1312,
  "WhitestKidsUKnowSeries::S5E8.mp4": 1353,
  "WhitestKidsUKnowSeries::S5E9.mp4": 1353,
  "WhitestKidsUKnowSeries::S5E10.mp4": 1354,
},
};
