window.SHOW = {
  id: "Recess",
  title: "Recess",
  storageProgressKey: "recess-progress",
  storageSettingsKey: "recess-settings",
  nestedPaths: true,
  grouping: "season",
  segments: "none",
  episodes: [
  ['recessfullseries', "RECESS - S00E01 - Recess Schools Out",
    "Recess/Movies/Recess Schools Out.mp4"],
  ['recessfullseries', "RECESS - S00E02 - Taking The Fifth Grade",
    "Recess/Movies/Taking The Fifth Grade.mp4"],
  ['recessfullseries', "RECESS - S00E03 - All Growed Down",
    "Recess/Movies/All Growed Down.mp4"],
  ['recessfullseries', "RECESS - S00E04 - Miracle On Third Street",
    "Recess/Movies/Miracle On Third Street.mp4"],
  ['recessfullseries', "RECESS - S01E01 - The Break In",
    "Recess/Season 1/recess_-_s01e01_-_the_break_in_[jpv711].mp4"],
  ['recessfullseries', "RECESS - S01E02 - The New Kid",
    "Recess/Season 1/recess_-_s01e02_-_the_new_kid_[jpv711].mp4"],
  ['recessfullseries', "RECESS - S01E03 - Parents' Night",
    "Recess/Season 1/recess_-_s01e03_-_parents'_night_[jpv711].mp4"],
  ['recessfullseries', "RECESS - S01E04 - Swing On Thru To The Other Side",
    "Recess/Season 1/recess_-_s01e04_-_swing_on_thru_to_the_other_side_[jpv711].mp4"],
  ['recessfullseries', "RECESS - S01E05 - First Name Ashley",
    "Recess/Season 1/recess_-_s01e05_-_first_name_ashley_[jpv711].mp4"],
  ['recessfullseries', "RECESS - S01E06 - To Finster With Love",
    "Recess/Season 1/recess_-_s01e06_-_to_finster_with_love_[jpv711].mp4"],
  ['recessfullseries', "RECESS - S01E07 - King Gus",
    "Recess/Season 1/recess_-_s01e07_-_king_gus_[jpv711].mp4"],
  ['recessfullseries', "RECESS - S01E08 - Big Brother Chad",
    "Recess/Season 1/recess_-_s01e08_-_big_brother_chad_[jpv711].mp4"],
  ['recessfullseries', "RECESS - S01E09 - My Fair Gretchen",
    "Recess/Season 1/recess_-_s01e09_-_my_fair_gretchen_[jpv711].mp4"],
  ['recessfullseries', "RECESS - S01E10 - Speedy, We Hardly Knew Ye",
    "Recess/Season 1/recess_-_s01e10_-_speedy,_we_hardly_knew_ye_[jpv711].mp4"],
  ['recessfullseries', "RECESS - S01E11 - I Will Kick No More Forever",
    "Recess/Season 1/recess_-_s01e11_-_i_will_kick_no_more_forever_[jpv711].mp4"],
  ['recessfullseries', "RECESS - S01E12 - The Kid Came Back",
    "Recess/Season 1/recess_-_s01e12_-_the_kid_came_back_[jpv711].mp4"],
  ['recessfullseries', "RECESS - S01E13 - The Pest",
    "Recess/Season 1/recess_-_s01e13_-_the_pest_[jpv711].mp4"],
  ['recessfullseries', "RECESS - S01E14 - The Legend Of Big Kid",
    "Recess/Season 1/recess_-_s01e14_-_the_legend_of_big_kid_[jpv711].mp4"],
  ['recessfullseries', "RECESS - S01E15 - The Box",
    "Recess/Season 1/recess_-_s01e15_-_the_box_[jpv711].mp4"],
  ['recessfullseries', "RECESS - S01E16 - The Trial",
    "Recess/Season 1/recess_-_s01e16_-_the_trial_[jpv711].mp4"],
  ['recessfullseries', "RECESS - S01E17 - Teachers Lounge",
    "Recess/Season 1/recess_-_s01e17_-_teachers_lounge_[jpv711].mp4"],
  ['recessfullseries', "RECESS - S01E18 - Randall's Reform",
    "Recess/Season 1/recess_-_s01e18_-_randall's_reform_[jpv711].mp4"],
  ['recessfullseries', "RECESS - S01E19 - Rainy Days",
    "Recess/Season 1/recess_-_s01e19_-_rainy_days_[jpv711].mp4"],
  ['recessfullseries', "RECESS - S01E20 - The Great Can Drive",
    "Recess/Season 1/recess_-_s01e20_-_the_great_can_drive_[jpv711].mp4"],
  ['recessfullseries', "RECESS - S01E21 - The Great Jungle Gym Stand Off",
    "Recess/Season 1/recess_-_s01e21_-_the_great_jungle_gym_stand_off_[jpv711].mp4"],
  ['recessfullseries', "RECESS - S01E22 - Jinxed",
    "Recess/Season 1/recess_-_s01e22_-_jinxed_[jpv711].mp4"],
  ['recessfullseries', "RECESS - S01E23 - The Experiment",
    "Recess/Season 1/recess_-_s01e23_-_the_experiment_[jpv711].mp4"],
  ['recessfullseries', "RECESS - S01E24 - Officer Mikey",
    "Recess/Season 1/recess_-_s01e24_-_officer_mikey_[jpv711].mp4"],
  ['recessfullseries', "RECESS - S01E25 - The Voice",
    "Recess/Season 1/recess_-_s01e25_-_the_voice_[jpv711].mp4"],
  ['recessfullseries', "RECESS - S01E26 - Kids In The Mist",
    "Recess/Season 1/recess_-_s01e26_-_kids_in_the_mist_[jpv711].mp4"],
  ['recessfullseries', "RECESS - S02E01 - The Game",
    "Recess/Season 2/recess_-_s02e01_-_the_game_[jpv711].mp4"],
  ['recessfullseries', "RECESS - S02E02 - The Lost Ball",
    "Recess/Season 2/recess_-_s02e02_-_the_lost_ball_[jpv711].mp4"],
  ['recessfullseries', "RECESS - S02E03 - Gus' Last Stand",
    "Recess/Season 2/recess_-_s02e03_-_gus'_last_stand_[jpv711].mp4"],
  ['recessfullseries', "RECESS - S02E04 - Operation Field Trip",
    "Recess/Season 2/recess_-_s02e04_-_operation_field_trip_[jpv711].mp4"],
  ['recessfullseries', "RECESS - S02E05 - The Challenge",
    "Recess/Season 2/recess_-_s02e05_-_the_challenge_[jpv711].mp4"],
  ['recessfullseries', "RECESS - S02E06 - Wild Child",
    "Recess/Season 2/recess_-_s02e06_-_wild_child_[jpv711].mp4"],
  ['recessfullseries', "RECESS - S02E07 - The Substitute",
    "Recess/Season 2/recess_-_s02e07_-_the_substitute_[jpv711].mp4"],
  ['recessfullseries', "RECESS - S02E08 - Gretchen And The Secret Of Yo",
    "Recess/Season 2/recess_-_s02e08_-_gretchen_and_the_secret_of_yo_[jpv711].mp4"],
  ['recessfullseries', "RECESS - S02E09 - The Girl Was Trouble",
    "Recess/Season 2/recess_-_s02e09_-_the_girl_was_trouble_[jpv711].mp4"],
  ['recessfullseries', "RECESS - S02E10 - Copycat Kid",
    "Recess/Season 2/recess_-_s02e10_-_copycat_kid_[jpv711].mp4"],
  ['recessfullseries', "RECESS - S02E11 - Operation Stuart",
    "Recess/Season 2/recess_-_s02e11_-_operation_stuart_[jpv711].mp4"],
  ['recessfullseries', "RECESS - S02E12 - Pharaoh Bob",
    "Recess/Season 2/recess_-_s02e12_-_pharaoh_bob_[jpv711].mp4"],
  ['recessfullseries', "RECESS - S02E13 - The Hypnotist",
    "Recess/Season 2/recess_-_s02e13_-_the_hypnotist_[jpv711].mp4"],
  ['recessfullseries', "RECESS - S02E14 - Mama's Girl",
    "Recess/Season 2/recess_-_s02e14_-_mama's_girl_[jpv711].mp4"],
  ['recessfullseries', "RECESS - S02E15 - Economics Of Recess",
    "Recess/Season 2/recess_-_s02e15_-_economics_of_recess_[jpv711].mp4"],
  ['recessfullseries', "RECESS - S02E16 - Omega Kids",
    "Recess/Season 2/recess_-_s02e16_-_omega_kids_[jpv711].mp4"],
  ['recessfullseries', "RECESS - S02E17-18 - Yes, Mikey, Santa Does Shave, Part 1 & 2",
    "Recess/Season 2/recess_-_s02e17_&_s02e18_-_yes,_mikey,_santa_does_shave,_part_1_&_2_[jpv711].mp4"],
  ['recessfullseries', "RECESS - S02E19 - The Story Of Whomps",
    "Recess/Season 2/recess_-_s02e19_-_the_story_of_whomps_[jpv711].mp4"],
  ['recessfullseries', "RECESS - S02E20 - Weekend At Muriel's",
    "Recess/Season 2/recess_-_s02e20_-_weekend_at_muriel's_[jpv711].mp4"],
  ['recessfullseries', "RECESS - S02E21 - Bad Hair Day",
    "Recess/Season 2/recess_-_s02e21_-_bad_hair_day_[jpv711].mp4"],
  ['recessfullseries', "RECESS - S02E22 - Dance Lessons",
    "Recess/Season 2/recess_-_s02e22_-_dance_lessons_[jpv711].mp4"],
  ['recessfullseries', "RECESS - S02E23 - Principal For A Day",
    "Recess/Season 2/recess_-_s02e23_-_principal_for_a_day_[jpv711].mp4"],
  ['recessfullseries', "RECESS - S02E24 - The Beauty Contest",
    "Recess/Season 2/recess_-_s02e24_-_the_beauty_contest_[jpv711].mp4"],
  ['recessfullseries', "RECESS - S02E25 - The Break-up",
    "Recess/Season 2/recess_-_s02e25_-_the_break-up_[jpv711].mp4"],
  ['recessfullseries', "RECESS - S02E26 - Outcast Ashley",
    "Recess/Season 2/recess_-_s02e26_-_outcast_ashley_[jpv711].mp4"],
  ['recessfullseries', "RECESS - S03E01 - One Stayed Clean",
    "Recess/Season 3/recess_-_s03e01_-_one_stayed_clean_[jpv711].mp4"],
  ['recessfullseries', "RECESS - S03E02 - A Genius Among Us",
    "Recess/Season 3/recess_-_s03e02_-_a_genius_among_us_[jpv711].mp4"],
  ['recessfullseries', "RECESS - S03E03 - Dodgeball City",
    "Recess/Season 3/recess_-_s03e03_-_dodgeball_city_[jpv711].mp4"],
  ['recessfullseries', "RECESS - S03E04 - A Career To Remember",
    "Recess/Season 3/recess_-_s03e04_-_a_career_to_remember_[jpv711].mp4"],
  ['recessfullseries', "RECESS - S03E05 - Kindergarten Derby",
    "Recess/Season 3/recess_-_s03e05_-_kindergarten_derby_[jpv711].mp4"],
  ['recessfullseries', "RECESS - S03E06 - The Bet",
    "Recess/Season 3/recess_-_s03e06_-_the_bet_[jpv711].mp4"],
  ['recessfullseries', "RECESS - S03E07 - Space Cadet",
    "Recess/Season 3/recess_-_s03e07_-_space_cadet_[jpv711].mp4"],
  ['recessfullseries', "RECESS - S03E08 - Stand Up Randall",
    "Recess/Season 3/recess_-_s03e08_-_stand_up_randall_[jpv711].mp4"],
  ['recessfullseries', "RECESS - S03E09 - The Shiner",
    "Recess/Season 3/recess_-_s03e09_-_the_shiner_[jpv711].mp4"],
  ['recessfullseries', "RECESS - S03E10 - Lord Of The Nerds",
    "Recess/Season 3/recess_-_s03e10_-_lord_of_the_nerds_[jpv711].mp4"],
  ['recessfullseries', "RECESS - S03E11 - That Stinking Feeling",
    "Recess/Season 3/recess_-_s03e11_-_that_stinking_feeling_[jpv711].mp4"],
  ['recessfullseries', "RECESS - S03E12 - My Funny Valentines",
    "Recess/Season 3/recess_-_s03e12_-_my_funny_valentines_[jpv711].mp4"],
  ['recessfullseries', "RECESS - S03E13 - The Barnaby Boys",
    "Recess/Season 3/recess_-_s03e13_-_the_barnaby_boys_[jpv711].mp4"],
  ['recessfullseries', "RECESS - S03E14 - Buried Treasure",
    "Recess/Season 3/recess_-_s03e14_-_buried_treasure_[jpv711].mp4"],
  ['recessfullseries', "RECESS - S03E15 - The Library Kid",
    "Recess/Season 3/recess_-_s03e15_-_the_library_kid_[jpv711].mp4"],
  ['recessfullseries', "RECESS - S03E16 - The Ratings Game",
    "Recess/Season 3/recess_-_s03e16_-_the_ratings_game_[jpv711].mp4"],
  ['recessfullseries', "RECESS - S04E01 - The First Picture Show",
    "Recess/Season 4/recess_-_s04e01_-_the_first_picture_show_[jpv711].mp4"],
  ['recessfullseries', "RECESS - S04E02 - The Big Prank",
    "Recess/Season 4/recess_-_s04e02_-_the_big_prank_[jpv711].mp4"],
  ['recessfullseries', "RECESS - S04E03 - Hustler's Apprentice",
    "Recess/Season 4/recess_-_s04e03_-_hustler's_apprentice_[jpv711].mp4"],
  ['recessfullseries', "RECESS - S04E04 - The Spy Who Came In From The Playground",
    "Recess/Season 4/recess_-_s04e04_-_the_spy_who_came_in_from_the_playground_[jpv711].mp4"],
  ['recessfullseries', "RECESS - S04E05 - Gus' Fortune",
    "Recess/Season 4/recess_-_s04e05_-_gus'_fortune_[jpv711].mp4"],
  ['recessfullseries', "RECESS - S04E06 - Rumor Mill",
    "Recess/Season 4/recess_-_s04e06_-_rumor_mill_[jpv711].mp4"],
  ['recessfullseries', "RECESS - S04E07 - Recess Is Cancelled",
    "Recess/Season 4/recess_-_s04e07_-_recess_is_cancelled_[jpv711].mp4"],
  ['recessfullseries', "RECESS - S04E08 - Tattletale Heart",
    "Recess/Season 4/recess_-_s04e08_-_tattletale_heart_[jpv711].mp4"],
  ['recessfullseries', "RECESS - S04E09 - The Madness Of King Bob",
    "Recess/Season 4/recess_-_s04e09_-_the_madness_of_king_bob_[jpv711].mp4"],
  ['recessfullseries', "RECESS - S04E10 - Call Me Guy",
    "Recess/Season 4/recess_-_s04e10_-_call_me_guy_[jpv711].mp4"],
  ['recessfullseries', "RECESS - S04E11 - Prickly Is Leaving",
    "Recess/Season 4/recess_-_s04e11_-_prickly_is_leaving_[jpv711].mp4"],
  ['recessfullseries', "RECESS - S04E12 - Randall's Friends",
    "Recess/Season 4/recess_-_s04e12_-_randall's_friends_[jpv711].mp4"],
  ['recessfullseries', "RECESS - S04E13 - The Biggest Trouble Ever",
    "Recess/Season 4/recess_-_s04e13_-_the_biggest_trouble_ever_[jpv711].mp4"],
  ['recessfullseries', "RECESS - S04E14 - The Rules",
    "Recess/Season 4/recess_-_s04e14_-_the_rules_[jpv711].mp4"],
  ['recessfullseries', "RECESS - S04E15 - Gus And Misdemeanors",
    "Recess/Season 4/recess_-_s04e15_-_gus_and_misdemeanors_[jpv711].mp4"],
  ['recessfullseries', "RECESS - S04E16 - A Science Fair To Remember",
    "Recess/Season 4/recess_-_s04e16_-_a_science_fair_to_remember_[jpv711].mp4"],
  ['recessfullseries', "RECESS - S04E17 - Mikey's Pants",
    "Recess/Season 4/recess_-_s04e17_-_mikey's_pants_[jpv711].mp4"],
  ['recessfullseries', "RECESS - S04E18 - Here Comes Mr. Perfect",
    "Recess/Season 4/recess_-_s04e18_-_here_comes_mr._perfect_[jpv711].mp4"],
  ['recessfullseries', "RECESS - S04E19 - Good Luck Charm",
    "Recess/Season 4/recess_-_s04e19_-_good_luck_charm_[jpv711].mp4"],
  ['recessfullseries', "RECESS - S04E20 - Diggers Split Up",
    "Recess/Season 4/recess_-_s04e20_-_diggers_split_up_[jpv711].mp4"],
  ['recessfullseries', "RECESS - S04E21 - Schoolworld",
    "Recess/Season 4/recess_-_s04e21_-_schoolworld_[jpv711].mp4"],
  ['recessfullseries', "RECESS - S04E22 - Bachelor Gus",
    "Recess/Season 4/recess_-_s04e22_-_bachelor_gus_[jpv711].mp4"],
  ['recessfullseries', "RECESS - S04E23 - The Dude",
    "Recess/Season 4/recess_-_s04e23_-_the_dude_[jpv711].mp4"],
  ['recessfullseries', "RECESS - S04E24 - Partners In Crime",
    "Recess/Season 4/recess_-_s04e24_-_partners_in_crime_[jpv711].mp4"],
  ['recessfullseries', "RECESS - S04E25 - The Candidates",
    "Recess/Season 4/recess_-_s04e25_-_the_candidates_[jpv711].mp4"],
  ['recessfullseries', "RECESS - S04E26 - This Brain For Hire",
    "Recess/Season 4/recess_-_s04e26_-_this_brain_for_hire_[jpv711].mp4"],
  ['recessfullseries', "RECESS - S04E27 - Spinelli's Masterpiece",
    "Recess/Season 4/recess_-_s04e27_-_spinelli's_masterpiece_[jpv711].mp4"],
  ['recessfullseries', "RECESS - S04E28 - Nobody Doesn't Like T.J.",
    "Recess/Season 4/recess_-_s04e28_-_nobody_doesn't_like_t.j._[jpv711].mp4"],
  ['recessfullseries', "RECESS - S04E29 - Yope From Norway",
    "Recess/Season 4/recess_-_s04e29_-_yope_from_norway_[jpv711].mp4"],
  ['recessfullseries', "RECESS - S04E30 - Bonky Fever",
    "Recess/Season 4/recess_-_s04e30_-_bonky_fever_[jpv711].mp4"],
  ['recessfullseries', "RECESS - S04E31 - Don't Ask Me",
    "Recess/Season 4/recess_-_s04e31_-_don't_ask_me_[jpv711]_(1).mp4"],
  ['recessfullseries', "RECESS - S04E32 - The Secret Life Of Grotke",
    "Recess/Season 4/recess_-_s04e32_-_the_secret_life_of_grotke_[jpv711].mp4"],
  ['recessfullseries', "RECESS - S04E33 - The Fuss Over Finster",
    "Recess/Season 4/recess_-_s04e33_-_the_fuss_over_finster_[jpv711].mp4"],
  ['recessfullseries', "RECESS - S04E34 - Soccer Boy",
    "Recess/Season 4/recess_-_s04e34_-_soccer_boy_[jpv711].mp4"],
  ['recessfullseries', "RECESS - S04E35 - Fort Tender",
    "Recess/Season 4/recess_-_s04e35_-_fort_tender_[jpv711].mp4"],
  ['recessfullseries', "RECESS - S04E36 - Germ Warfare",
    "Recess/Season 4/recess_-_s04e36_-_germ_warfare_[jpv711].mp4"],
  ['recessfullseries', "RECESS - S04E37 - More Like Gretchen",
    "Recess/Season 4/recess_-_s04e37_-_more_like_gretchen_[jpv711].mp4"],
  ['recessfullseries', "RECESS - S04E38 - Prince Randall",
    "Recess/Season 4/recess_-_s04e38_-_prince_randall_[jpv711].mp4"],
  ['recessfullseries', "RECESS - S04E39 - Me No Know",
    "Recess/Season 4/recess_-_s04e39_-_me_no_know_[jpv711].mp4"],
  ['recessfullseries', "RECESS - S04E40 - Good Ole T.J.",
    "Recess/Season 4/recess_-_s04e40_-_good_ole_t.j._[jpv711].mp4"],
  ['recessfullseries', "RECESS - S04E41 - Chez Vince",
    "Recess/Season 4/recess_-_s04e41_-_chez_vince_[jpv711].mp4"],
  ['recessfullseries', "RECESS - S04E42 - Tucked In Mikey",
    "Recess/Season 4/recess_-_s04e42_-_tucked_in_mikey_[jpv711].mp4"],
  ['recessfullseries', "RECESS - S04E43 - Old Folks Home",
    "Recess/Season 4/recess_-_s04e43_-_old_folks_home_[jpv711].mp4"],
  ['recessfullseries', "RECESS - S04E44 - Some Friend",
    "Recess/Season 4/recess_-_s04e44_-_some_friend_[jpv711].mp4"],
  ['recessfullseries', "RECESS - S05E01 - The Coolest Heatwave Ever",
    "Recess/Season 5/recess_-_s05e01_-_the_coolest_heatwave_ever_[jpv711].mp4"],
  ['recessfullseries', "RECESS - S05E02 - No Strings Attached",
    "Recess/Season 5/recess_-_s05e02_-_no_strings_attached_[jpv711].mp4"],
  ['recessfullseries', "RECESS - S05E03 - Beyond A Reasonable Scout",
    "Recess/Season 5/recess_-_s05e03_-_beyond_a_reasonable_scout_[jpv711].mp4"],
  ['recessfullseries', "RECESS - S05E04 - The C Note",
    "Recess/Season 5/recess_-_s05e04_-_the_c_note_[jpv711].mp4"],
  ['recessfullseries', "RECESS - S05E05 - The Army Navy Game",
    "Recess/Season 5/recess_-_s05e05_-_the_army_navy_game_[jpv711].mp4"],
  ['recessfullseries', "RECESS - S05E06 - Big Ol' Mikey",
    "Recess/Season 5/recess_-_s05e06_-_big_ol'_mikey_[jpv711].mp4"],
  ['recessfullseries', "RECESS - S05E07 - A Great State Fair",
    "Recess/Season 5/recess_-_s05e07_-_a_great_state_fair_[jpv711].mp4"],
  ['recessfullseries', "RECESS - S05E08 - The A.V. Kid",
    "Recess/Season 5/recess_-_s05e08_-_the_a.v._kid_[jpv711].mp4"],
  ['recessfullseries', "RECESS - S05E09 - The Principals Of Golf",
    "Recess/Season 5/recess_-_s05e09_-_the_principals_of_golf_[jpv711].mp4"],
  ['recessfullseries', "RECESS - S05E10 - All The Principal's Men",
    "Recess/Season 5/recess_-_s05e10_-_all_the_principal's_men_[jpv711].mp4"],
  ['recessfullseries', "RECESS - S05E11-12 - Lawson And His Crew Part, 1 & 2",
    "Recess/Season 5/recess_-_s05e11_&_s05e12_-_lawson_and_his_crew_part,_1_&_2_[jpv711].mp4"],
  ['recessfullseries', "RECESS - S06E01 - Terrifying Tales Of Recess",
    "Recess/Season 6/recess_-_s06e01_-_terrifying_tales_of_recess_[jpv711].mp4"],
  ['recessfullseries', "RECESS - S06E02 - Kurst The Not So Bad",
    "Recess/Season 6/recess_-_s06e02_-_kurst_the_not_so_bad_[jpv711].mp4"],
  ['recessfullseries', "RECESS - S06E03 - League Of Randalls",
    "Recess/Season 6/recess_-_s06e03_-_league_of_randalls_[jpv711].mp4"],
  ['recessfullseries', "RECESS - S06E04 - Mundy, Mundy",
    "Recess/Season 6/recess_-_s06e04_-_mundy,_mundy_[jpv711].mp4"],
  ['recessfullseries', "RECESS - S06E05 - Lost Leader",
    "Recess/Season 6/recess_-_s06e05_-_lost_leader_[jpv711].mp4"],
],
  durations: {},
};
