window.SHOW = {
  id: "WkrpinCincinnati",
  title: "Wkrp in Cincinnati",
  art: "WkrpinCincinnati.jpg",
  storageProgressKey: "wkrpincincinnati-progress",
  storageSettingsKey: "wkrpincincinnati-settings",
  nestedPaths: true,
  grouping: "season",
  segments: "none",
  episodes: [
  ["wkrp-s-1-e-20-young-master-carlson", "WKRP IN CINCINNATI - S01E01 - WKRP Pilot",
    "WKRP S1E01 Pilot Pt 1.mp4"],
  ["wkrp-s-1-e-20-young-master-carlson", "WKRP IN CINCINNATI - S01E02 - WKRP Pilot",
    "WKRP S1E02 Pilot Pt 2.mp4"],
  ["wkrp-s-1-e-20-young-master-carlson", "WKRP IN CINCINNATI - S01E03 - WKRP Les on a Ledge",
    "WKRP S1E03 Les on a Ledge.mp4"],
  ["wkrp-s-1-e-20-young-master-carlson", "WKRP IN CINCINNATI - S01E04 - WKRP Hoodlum Rock",
    "WKRP S1E04 Hoodlum Rock.mp4"],
  ["wkrp-s-1-e-20-young-master-carlson", "WKRP IN CINCINNATI - S01E05 - WKRP Hold Up",
    "WKRP S1E05 Hold-Up.mp4"],
  ["wkrp-in-cincinnati-season-01-episode-06-baileys-show", "WKRP IN CINCINNATI - S01E06 - WKRP In Cincinnati Bailey's Show",
    "WKRP In Cincinnati S01E06 Bailey's Show.mp4"],
  ["wkrp-in-cincinnati-season-01-episodes-07-08-turkeys-awaylove-returns", "WKRP IN CINCINNATI - S01E07 - WKRP In Cincinnati 8 Turkey's Away Love Returns",
    "WKRP In Cincinnati S01E07-8 Turkey's Away-Love Returns.mp4"],
  ["wkrp-s-1-e-20-young-master-carlson", "WKRP IN CINCINNATI - S01E08 - WKRP Love Returns",
    "WKRP S1E08 Love Returns.mp4"],
  ["wkrp-in-cincinnati-season-1-episodes-09-10-mamas-reviewa-date-with-jennifer", "WKRP IN CINCINNATI - S01E09 - WKRP In Cincinnati 10 Mama's Review A Date With Jennifer",
    "WKRP In Cincinnati S01E09-10 Mama's Review-A Date With Jennifer.mp4"],
  ["wkrp-s-1-e-20-young-master-carlson", "WKRP IN CINCINNATI - S01E10 - WKRP A Date with Jennifer",
    "WKRP S1E10 A Date with Jennifer.mp4"],
  ["wkrp-in-cincinnati-season-01-episodes-11-12-the-contest-nobody-could-win-origina", "WKRP IN CINCINNATI - S01E11 - WKRP In Cincinnati 12 The Contest Nobody Could Win (Original Version),The Contest…",
    "WKRP In Cincinnati S01E11-12 The Contest Nobody Could Win (Original Version),The Contest Nobody Could Win (Deleted Scenes)-Tornado.mp4"],
  ["wkrp-s-1-e-20-young-master-carlson", "WKRP IN CINCINNATI - S01E12 - WKRP Tornado",
    "WKRP S1E12 Tornado.mp4"],
  ["wkrp-in-cincinnati-season-01-episodes-13-14-goodbye-johnnyjohnny-comes-back", "WKRP IN CINCINNATI - S01E13 - WKRP In Cincinnati 14 Goodbye Johnny Johnny Comes Back",
    "WKRP In Cincinnati S01E13-14 Goodbye Johnny-Johnny Comes Back.mp4"],
  ["wkrp-s-1-e-20-young-master-carlson", "WKRP IN CINCINNATI - S01E14 - WKRP Johnny Comes Back",
    "WKRP S1E14 Johnny Comes Back.mp4"],
  ["wkrp-in-cincinnati-season-01-episodes-15-16-never-leave-me-lucillei-want-to-keep-my-baby", "WKRP IN CINCINNATI - S01E15 - WKRP In Cincinnati 16 Never Leave Me, Lucille I Want To Keep…",
    "WKRP In Cincinnati S01E15-16 Never Leave Me, Lucille- I Want To Keep My Baby.mp4"],
  ["wkrp-s-1-e-20-young-master-carlson", "WKRP IN CINCINNATI - S01E16 - WKRP I Want to Keep My Baby",
    "WKRP S1E16 I Want to Keep My Baby.mp4"],
  ["wkrp-in-cincinnati-season-01-episodes-17-18-a-commercial-breakwho-is-gordon-sims", "WKRP IN CINCINNATI - S01E17 - WKRP In Cincinnati 18 A Commercial Break Who Is Gordon Sims",
    "WKRP In Cincinnati S01E17-18 A Commercial Break-Who Is Gordon Sims.mp4"],
  ["wkrp-s-1-e-20-young-master-carlson", "WKRP IN CINCINNATI - S01E18 - WKRP Who is Gordon Sims",
    "WKRP S1E18 Who is Gordon Sims.mp4"],
  ["wkrp-in-cincinnati-season-01-episodes-19-20-i-do-i-do...-for-nowyoung-master-carlson", "WKRP IN CINCINNATI - S01E19 - WKRP In Cincinnati 20 I Do, I Do... For Now Young Master…",
    "WKRP In Cincinnati S01E19-20 I Do, I Do... For Now-Young Master Carlson.mp4"],
  ["wkrp-s-1-e-20-young-master-carlson", "WKRP IN CINCINNATI - S01E20 - WKRP Young Master Carlson",
    "WKRP S1E20 Young Master Carlson.mp4"],
  ["wkrp-in-cincinnati-season-01-episodes-21-22-fish-storypreacher", "WKRP IN CINCINNATI - S01E21 - WKRP In Cincinnati 22 Fish Story Preacher",
    "WKRP In Cincinnati S01E21-22 Fish Story-Preacher.mp4"],
  ["wkrp-s-1-e-20-young-master-carlson", "WKRP IN CINCINNATI - S01E22 - WKRP Preacher",
    "WKRP S1E22 Preacher.mp4"],
  ["wkrp-in-cincinnati-season-02-episodes-01-02-for-the-love-or-money", "WKRP IN CINCINNATI - S02E01 - WKRP In Cincinnati 2 For The Love Or Money",
    "WKRP In Cincinnati S02E01-2 For The Love Or Money.mp4"],
  ["wkrp-s-1-e-20-young-master-carlson", "WKRP IN CINCINNATI - S02E02 - WKRP For Love or Money",
    "WKRP S2E02 For Love or Money Pt 2.mp4"],
  ["wkrp-in-cincinnati-season-02-episodes-03-04-baseballbad-risk", "WKRP IN CINCINNATI - S02E03 - WKRP In Cincinnati 4 Baseball Bad Risk",
    "WKRP In Cincinnati S02E03-4 Baseball-Bad Risk.mp4"],
  ["wkrp-s-1-e-20-young-master-carlson", "WKRP IN CINCINNATI - S02E04 - WKRP Bad Risk",
    "WKRP S2E04 Bad Risk.mp4"],
  ["wkrp-in-cincinnati-season-02-episodes-05-6-jennifer-falls-in-lovecarlson-for-president", "WKRP IN CINCINNATI - S02E05 - WKRP in Cincinnati 6 Jennifer Falls In Love Carlson For President",
    "WKRP in Cincinnati S02E05-6 Jennifer Falls In Love-Carlson For President.mp4"],
  ["wkrp-s-1-e-20-young-master-carlson", "WKRP IN CINCINNATI - S02E06 - WKRP Carlson for President",
    "WKRP S2E06 Carlson for President.mp4"],
  ["wkrp-in-cincinnati-season-02-episodes-07-8-mike-frightpatter-of-little-feet", "WKRP IN CINCINNATI - S02E07 - WKRP In Cincinnati 8 Mike Fright Patter Of Little Feet",
    "WKRP In Cincinnati S02E07-8 Mike Fright-Patter Of Little Feet.mp4"],
  ["wkrp-s-1-e-20-young-master-carlson", "WKRP IN CINCINNATI - S02E08 - WKRP Patter of Little Feet",
    "WKRP S2E08 Patter of Little Feet.mp4"],
  ["wkrp-in-cincinnati-season-02-episodes-09-10-baby-if-youve-ever-wonderedbaileys-big-break", "WKRP IN CINCINNATI - S02E09 - WKRP in Cincinnati 10 Baby, If You've Ever Wondered Bailey's Big Break",
    "WKRP in Cincinnati S02E09-10 Baby, If You've Ever Wondered-Bailey's Big Break.mp4"],
  ["wkrp-s-1-e-20-young-master-carlson", "WKRP IN CINCINNATI - S02E10 - WKRP Bailey's Big Break",
    "WKRP S2E10 Bailey's Big Break.mp4"],
  ["wkrp-in-cincinnati-s-02-e-11-12-jennifers-home-for-christmas-sparky", "WKRP IN CINCINNATI - S02E11 - WKRP in Cincinnati 12 Jennifer's Home For Christmas Sparky",
    "WKRP in Cincinnati S02E11-12 Jennifer's Home For Christmas-Sparky.mp4"],
  ["wkrp-s-1-e-20-young-master-carlson", "WKRP IN CINCINNATI - S02E12 - WKRP Sparky",
    "WKRP S2E12 Sparky.mp4"],
  ["wkrp-in-cincinnati-season-02-episodes-13-14-god-talks-to-johnnya-family-affair", "WKRP IN CINCINNATI - S02E13 - WKRP in Cincinnati 14 God Talks To Johnny A Family Affair",
    "WKRP in Cincinnati S02E13-14 God Talks To Johnny-A Family Affair.mp4"],
  ["wkrp-s-1-e-20-young-master-carlson", "WKRP IN CINCINNATI - S02E14 - WKRP A Family Affair",
    "WKRP S2E14 A Family Affair.mp4"],
  ["wkrp-in-cincinnati-season-02-episodes-15-16-herbs-dad-put-up-or-shut-up", "WKRP IN CINCINNATI - S02E15 - WKRP In Cincinnati 16 Herb's Dad Put Up Or Shut Up",
    "WKRP In Cincinnati S02E15-16 Herb's Dad-Put Up Or Shut Up.mp4"],
  ["wkrp-s-1-e-20-young-master-carlson", "WKRP IN CINCINNATI - S02E16 - WKRP Put Up or Shut Up",
    "WKRP S2E16 Put Up or Shut Up.mp4"],
  ["wkrp-in-cincinnati-season-02-episodes-17-18-the-americanization-of-ivan-less-groupe", "WKRP IN CINCINNATI - S02E17 - WKRP In Cincinnati 18 The Americanization of Ivan Les's Groupe",
    "WKRP In Cincinnati S02E17-18 The Americanization of Ivan-Les's Groupe.mp4"],
  ["wkrp-s-1-e-20-young-master-carlson", "WKRP IN CINCINNATI - S02E18 - WKRP Les' Groupie",
    "WKRP S2E18 Les' Groupie.mp4"],
  ["wkrp-in-cincinnati-season-02-episodes-19-20-in-concert-the-doctor-daughter", "WKRP IN CINCINNATI - S02E19 - WKRP In Cincinnati 20 In Concert The Doctor Daughter",
    "WKRP In Cincinnati S02E19-20 In Concert-The Doctor Daughter.mp4"],
  ["wkrp-s-1-e-20-young-master-carlson", "WKRP IN CINCINNATI - S02E20 - WKRP The Doctor's Daughter",
    "WKRP S2E20 The Doctor's Daughter.mp4"],
  ["wkrp-in-cincinnati-season-02-episodes-21-22-fifty-pictures", "WKRP IN CINCINNATI - S02E21 - WKRP In Cincinnati 22 Fifty Pictures",
    "WKRP In Cincinnati S02E21-22 Fifty Pictures.mp4"],
  ["wkrp-in-cincinnati-season-02-episodes-23-24-venus-risingmost-improved-station", "WKRP IN CINCINNATI - S02E23 - WKRP In Cincinnati 24 Venus Rising Most Improved Station",
    "WKRP In Cincinnati S02E23-24 Venus Rising-Most Improved Station.mp4"],
  ["wkrp-s-1-e-20-young-master-carlson", "WKRP IN CINCINNATI - S02E24 - WKRP Most Improved Station",
    "WKRP S2E24 Most Improved Station.mp4"],
  ["wkrp-in-cincinnati-season-03-episodes-01-03-the-airplane-showreal-families", "WKRP IN CINCINNATI - S03E01 - WKRP In Cincinnati 3 The Airplane Show Real Families",
    "WKRP In Cincinnati S03E01-3 The Airplane Show-Real Families.mp4"],
  ["wkrp-s-1-e-20-young-master-carlson", "WKRP IN CINCINNATI - S03E02 - WKRP Jennifer Moves",
    "WKRP S3E02 Jennifer Moves.mp4"],
  ["wkrp-s-1-e-20-young-master-carlson", "WKRP IN CINCINNATI - S03E03 - WKRP Real Families",
    "WKRP S3E03 Real Families.mp4"],
  ["wkrp-in-cincinnati-season-03-episodes-04-05-the-babyhotel-oceanview", "WKRP IN CINCINNATI - S03E04 - WKRP In Cincinnati 5 The Baby Hotel Oceanview",
    "WKRP In Cincinnati S03E04-5 The Baby-Hotel Oceanview.mp4"],
  ["wkrp-s-1-e-20-young-master-carlson", "WKRP IN CINCINNATI - S03E05 - WKRP Hotel Oceanview",
    "WKRP S3E05 Hotel Oceanview.mp4"],
  ["wkrp-in-cincinnati-season-03-episode-06-a-mile-in-my-shoes", "WKRP IN CINCINNATI - S03E06 - WKRP in Cincinnati A Mile in My Shoes",
    "WKRP in Cincinnati S03E06 A Mile in My Shoes.mp4"],
  ["wkrp-s-1-e-20-young-master-carlson", "WKRP IN CINCINNATI - S03E07 - WKRP Bah, Humbug",
    "WKRP S3E07 Bah, Humbug.mp4"],
  ["wkrp-in-cincinnati-season-03-episodes-08-09-baby-its-cold-outsidethe-painting", "WKRP IN CINCINNATI - S03E08 - WKRP In Cincinnati 9 Baby, It's Cold Outside The Painting",
    "WKRP In Cincinnati S03E08-9 Baby, It's Cold Outside-The Painting.mp4"],
  ["wkrp-s-1-e-20-young-master-carlson", "WKRP IN CINCINNATI - S03E09 - WKRP The Painting",
    "WKRP S3E09 The Painting.mp4"],
  ["wkrp-in-cincinnati-season-03-episodes-10-11-daydreamsfrog-story", "WKRP IN CINCINNATI - S03E10 - WKRP In Cincinnati 11 Daydreams Frog Story",
    "WKRP In Cincinnati S03E10-11 Daydreams-Frog Story.mp4"],
  ["wkrp-s-1-e-20-young-master-carlson", "WKRP IN CINCINNATI - S03E11 - WKRP Frog Story",
    "WKRP S3E11 Frog Story.mp4"],
  ["wkrp-s-1-e-20-young-master-carlson", "WKRP IN CINCINNATI - S03E12 - WKRP Venus and the Man",
    "WKRP S3E12 Venus and the Man.mp4"],
  ["wkrp-in-cincinnati-season-03-episodes-13-14-dr.-fever-mr.-tide", "WKRP IN CINCINNATI - S03E13 - WKRP In Cincinnati 14 Dr. Fever & Mr. Tide",
    "WKRP In Cincinnati S03E13-14 Dr. Fever & Mr. Tide.mp4"],
  ["wkrp-in-cincinnati-season-03-episodes-15-16-ask-jenniferi-am-woman", "WKRP IN CINCINNATI - S03E15 - WKRP in Cincinnati 16 Ask Jennifer I Am Woman",
    "WKRP in Cincinnati S03E15-16 Ask Jennifer-I Am Woman.mp4"],
  ["wkrp-s-1-e-20-young-master-carlson", "WKRP IN CINCINNATI - S03E16 - WKRP I Am Woman",
    "WKRP S3E16 I Am Woman.mp4"],
  ["wkrp-in-cincinnati-season-03-episodes-17-18-secrets-of-dayton-heightsout-to-lunch", "WKRP IN CINCINNATI - S03E17 - WKRP In Cincinnati 18 Secrets of Dayton Heights Out To Lunch",
    "WKRP In Cincinnati S03E17-18 Secrets of Dayton Heights-Out To Lunch.mp4"],
  ["wkrp-s-1-e-20-young-master-carlson", "WKRP IN CINCINNATI - S03E18 - WKRP Out to Lunch",
    "WKRP S3E18 Out to Lunch.mp4"],
  ["wkrp-in-cincinnati-season-03-episodes-19-20-a-simple-little-weddingnothing-to-fear-but...", "WKRP IN CINCINNATI - S03E19 - WKRP In Cincinnati 20 A Simple Little Wedding Nothing to Fear But",
    "WKRP In Cincinnati S03E19-20 A Simple Little Wedding-Nothing to Fear But....mp4"],
  ["wkrp-s-1-e-20-young-master-carlson", "WKRP IN CINCINNATI - S03E20 - WKRP Nothing to Fear But",
    "WKRP S3E20 Nothing to Fear But....mp4"],
  ["wkrp-in-cincinnati-season-03-episode-21-till-debt-do-us-part", "WKRP IN CINCINNATI - S03E21 - WKRP In Cincinnati Till Debt Do Us Part",
    "WKRP In Cincinnati S03E21 Till Debt Do Us Part.mp4"],
  ["wkrp-in-cincinnati-season-03-episode-22-clean-up-radio-everywhere", "WKRP IN CINCINNATI - S03E22 - WKRP In Cincinnati Clean Up Radio Everywhere",
    "WKRP In Cincinnati S03E22 Clean Up Radio Everywhere.mp4"],
  ["wkrp-in-cincinnati-season-04-episodes-01-02-an-explosive-affair", "WKRP IN CINCINNATI - S04E01 - WKRP In Cincinnati 02 An Explosive Affair",
    "WKRP In Cincinnati S04E01-02 An Explosive Affair.mp4"],
  ["wkrp-s-1-e-20-young-master-carlson", "WKRP IN CINCINNATI - S04E02 - WKRP An Explosive Affair",
    "WKRP S4E02 An Explosive Affair Pt 2.mp4"],
  ["wkrp-in-cincinnati-season-04-episodes-03-04-the-unionrumors", "WKRP IN CINCINNATI - S04E03 - WKRP In Cincinnati 4 The Union Rumors",
    "WKRP In Cincinnati S04E03-4 The Union-Rumors.mp4"],
  ["wkrp-s-1-e-20-young-master-carlson", "WKRP IN CINCINNATI - S04E04 - WKRP Rumors",
    "WKRP S4E04 Rumors.mp4"],
  ["wkrp-in-cincinnati-season-04-episodes-05-06-straight-from-the-heartwhos-on-first", "WKRP IN CINCINNATI - S04E05 - WKRP In Cincinnati 06 Straight From The Heart Who's On First",
    "WKRP In Cincinnati S04E05-06 Straight From The Heart-Who's On First.mp4"],
  ["wkrp-s-1-e-20-young-master-carlson", "WKRP IN CINCINNATI - S04E06 - WKRP Who's on First",
    "WKRP S4E06 Who's on First.mp4"],
  ["wkrp-s-1-e-20-young-master-carlson", "WKRP IN CINCINNATI - S04E07 - WKRP Three Days of the Condo",
    "WKRP S4E07 Three Days of the Condo.mp4"],
  ["wkrp-s-1-e-20-young-master-carlson", "WKRP IN CINCINNATI - S04E08 - WKRP Jennifer and the Will",
    "WKRP S4E08 Jennifer and the Will.mp4"],
  ["wkrp-s-1-e-20-young-master-carlson", "WKRP IN CINCINNATI - S04E09 - WKRP The Consultant",
    "WKRP S4E09 The Consultant.mp4"],
  ["wkrp-s-1-e-20-young-master-carlson", "WKRP IN CINCINNATI - S04E10 - WKRP Love+Exciting and New",
    "WKRP S4E10 Love+Exciting and New.mp4"],
  ["wkrp-in-cincinnati-season-04-episodes-11-12-you-cant-go-out-of-town-againpills", "WKRP IN CINCINNATI - S04E11 - WKRP In Cincinnati 12 You Can't Go Out of Town Again Pills",
    "WKRP In Cincinnati S04E11-12 You Can't Go Out of Town Again-Pills.mp4"],
  ["wkrp-s-1-e-20-young-master-carlson", "WKRP IN CINCINNATI - S04E12 - WKRP Pills",
    "WKRP S4E12 Pills.mp4"],
  ["wkrp-in-cincinnati-season-04-episode-13-changes", "WKRP IN CINCINNATI - S04E13 - WKRP In Cincinnati Changes",
    "WKRP In Cincinnati S04E13 Changes.mp4"],
  ["wkrp-s-1-e-20-young-master-carlson", "WKRP IN CINCINNATI - S04E14 - WKRP Jennifer and Johnny's Charity",
    "WKRP S4E14 Jennifer and Johnny's Charity.mp4"],
  ["wkrp-in-cincinnati-season-04-episode-15-ill-take-romance", "WKRP IN CINCINNATI - S04E15 - WKRP In Cincinnati I'll Take Romance",
    "WKRP In Cincinnati S04E15 I'll Take Romance.mp4"],
  ["wkrp-in-cincinnati-season-04-episode-16-circumstantial-evidence", "WKRP IN CINCINNATI - S04E16 - WKRP In Cincinnati Circumstantial Evidence",
    "WKRP In Cincinnati S04E16 Circumstantial Evidence.mp4"],
  ["wkrp-in-cincinnati-season-04-episode-17-fire", "WKRP IN CINCINNATI - S04E17 - WKRP In Cincinnati Fire",
    "WKRP In Cincinnati S04E17 Fire.mp4"],
  ["wkrp-s-1-e-20-young-master-carlson", "WKRP IN CINCINNATI - S04E18 - WKRP Dear Liar",
    "WKRP S4E18 Dear Liar.mp4"],
  ["wkrp-s-1-e-20-young-master-carlson", "WKRP IN CINCINNATI - S04E19 - WKRP The Creation of Venus",
    "WKRP S4E19 The Creation of Venus.mp4"],
  ["wkrp-in-cincinnati-season-04-episode-20-the-impossible-dream", "WKRP IN CINCINNATI - S04E20 - WKRP In Cincinnati The Impossible Dream",
    "WKRP In Cincinnati S04E20 The Impossible Dream.mp4"],
  ["wkrp-in-cincinnati-season-04-episode-21-to-err-is-human", "WKRP IN CINCINNATI - S04E21 - WKRP In Cincinnati To Err Is Human",
    "WKRP In Cincinnati S04E21 To Err Is Human.mp4"],
  ["wkrp-in-cincinnati-season-04-episode-22-up-and-down-the-dial-last-final-episode", "WKRP IN CINCINNATI - S04E22 - WKRP In Cincinnati Up And Down The Dial (Last Final Episode",
    "WKRP In Cincinnati S04E22 Up And Down The Dial (Last Final Episode).mp4"],
],
  durations: {
  "wkrp-s-1-e-20-young-master-carlson::WKRP S1E01 Pilot Pt 1.mp4": 1496,
  "wkrp-s-1-e-20-young-master-carlson::WKRP S1E02 Pilot Pt 2.mp4": 1514,
  "wkrp-s-1-e-20-young-master-carlson::WKRP S1E03 Les on a Ledge.mp4": 1515,
  "wkrp-s-1-e-20-young-master-carlson::WKRP S1E04 Hoodlum Rock.mp4": 1496,
  "wkrp-s-1-e-20-young-master-carlson::WKRP S1E05 Hold-Up.mp4": 1461,
  "wkrp-in-cincinnati-season-01-episode-06-baileys-show::WKRP In Cincinnati S01E06 Bailey's Show.mp4": 1507,
  "wkrp-in-cincinnati-season-01-episodes-07-08-turkeys-awaylove-returns::WKRP In Cincinnati S01E07-8 Turkey's Away-Love Returns.mp4": 3023,
  "wkrp-s-1-e-20-young-master-carlson::WKRP S1E08 Love Returns.mp4": 1510,
  "wkrp-in-cincinnati-season-1-episodes-09-10-mamas-reviewa-date-with-jennifer::WKRP In Cincinnati S01E09-10 Mama's Review-A Date With Jennifer.mp4": 3013,
  "wkrp-s-1-e-20-young-master-carlson::WKRP S1E10 A Date with Jennifer.mp4": 1508,
  "wkrp-in-cincinnati-season-01-episodes-11-12-the-contest-nobody-could-win-origina::WKRP In Cincinnati S01E11-12 The Contest Nobody Could Win (Original Version),The Contest Nobody Could Win (Deleted Scenes)-Tornado.mp4": 3441,
  "wkrp-s-1-e-20-young-master-carlson::WKRP S1E12 Tornado.mp4": 1510,
  "wkrp-in-cincinnati-season-01-episodes-13-14-goodbye-johnnyjohnny-comes-back::WKRP In Cincinnati S01E13-14 Goodbye Johnny-Johnny Comes Back.mp4": 2931,
  "wkrp-s-1-e-20-young-master-carlson::WKRP S1E14 Johnny Comes Back.mp4": 1498,
  "wkrp-in-cincinnati-season-01-episodes-15-16-never-leave-me-lucillei-want-to-keep-my-baby::WKRP In Cincinnati S01E15-16 Never Leave Me, Lucille- I Want To Keep My Baby.mp4": 2989,
  "wkrp-s-1-e-20-young-master-carlson::WKRP S1E16 I Want to Keep My Baby.mp4": 1486,
  "wkrp-in-cincinnati-season-01-episodes-17-18-a-commercial-breakwho-is-gordon-sims::WKRP In Cincinnati S01E17-18 A Commercial Break-Who Is Gordon Sims.mp4": 2974,
  "wkrp-s-1-e-20-young-master-carlson::WKRP S1E18 Who is Gordon Sims.mp4": 1497,
  "wkrp-in-cincinnati-season-01-episodes-19-20-i-do-i-do...-for-nowyoung-master-carlson::WKRP In Cincinnati S01E19-20 I Do, I Do... For Now-Young Master Carlson.mp4": 2982,
  "wkrp-s-1-e-20-young-master-carlson::WKRP S1E20 Young Master Carlson.mp4": 1498,
  "wkrp-in-cincinnati-season-01-episodes-21-22-fish-storypreacher::WKRP In Cincinnati S01E21-22 Fish Story-Preacher.mp4": 2922,
  "wkrp-s-1-e-20-young-master-carlson::WKRP S1E22 Preacher.mp4": 1470,
  "wkrp-in-cincinnati-season-02-episodes-01-02-for-the-love-or-money::WKRP In Cincinnati S02E01-2 For The Love Or Money.mp4": 2747,
  "wkrp-s-1-e-20-young-master-carlson::WKRP S2E02 For Love or Money Pt 2.mp4": 1495,
  "wkrp-in-cincinnati-season-02-episodes-03-04-baseballbad-risk::WKRP In Cincinnati S02E03-4 Baseball-Bad Risk.mp4": 2999,
  "wkrp-s-1-e-20-young-master-carlson::WKRP S2E04 Bad Risk.mp4": 1502,
  "wkrp-in-cincinnati-season-02-episodes-05-6-jennifer-falls-in-lovecarlson-for-president::WKRP in Cincinnati S02E05-6 Jennifer Falls In Love-Carlson For President.mp4": 2989,
  "wkrp-s-1-e-20-young-master-carlson::WKRP S2E06 Carlson for President.mp4": 1500,
  "wkrp-in-cincinnati-season-02-episodes-07-8-mike-frightpatter-of-little-feet::WKRP In Cincinnati S02E07-8 Mike Fright-Patter Of Little Feet.mp4": 2997,
  "wkrp-s-1-e-20-young-master-carlson::WKRP S2E08 Patter of Little Feet.mp4": 1498,
  "wkrp-in-cincinnati-season-02-episodes-09-10-baby-if-youve-ever-wonderedbaileys-big-break::WKRP in Cincinnati S02E09-10 Baby, If You've Ever Wondered-Bailey's Big Break.mp4": 2973,
  "wkrp-s-1-e-20-young-master-carlson::WKRP S2E10 Bailey's Big Break.mp4": 1499,
  "wkrp-in-cincinnati-s-02-e-11-12-jennifers-home-for-christmas-sparky::WKRP in Cincinnati S02E11-12 Jennifer's Home For Christmas-Sparky.mp4": 2962,
  "wkrp-s-1-e-20-young-master-carlson::WKRP S2E12 Sparky.mp4": 1467,
  "wkrp-in-cincinnati-season-02-episodes-13-14-god-talks-to-johnnya-family-affair::WKRP in Cincinnati S02E13-14 God Talks To Johnny-A Family Affair.mp4": 2946,
  "wkrp-s-1-e-20-young-master-carlson::WKRP S2E14 A Family Affair.mp4": 1444,
  "wkrp-in-cincinnati-season-02-episodes-15-16-herbs-dad-put-up-or-shut-up::WKRP In Cincinnati S02E15-16 Herb's Dad-Put Up Or Shut Up.mp4": 2983,
  "wkrp-s-1-e-20-young-master-carlson::WKRP S2E16 Put Up or Shut Up.mp4": 1485,
  "wkrp-in-cincinnati-season-02-episodes-17-18-the-americanization-of-ivan-less-groupe::WKRP In Cincinnati S02E17-18 The Americanization of Ivan-Les's Groupe.mp4": 2997,
  "wkrp-s-1-e-20-young-master-carlson::WKRP S2E18 Les' Groupie.mp4": 1498,
  "wkrp-in-cincinnati-season-02-episodes-19-20-in-concert-the-doctor-daughter::WKRP In Cincinnati S02E19-20 In Concert-The Doctor Daughter.mp4": 2976,
  "wkrp-s-1-e-20-young-master-carlson::WKRP S2E20 The Doctor's Daughter.mp4": 1478,
  "wkrp-in-cincinnati-season-02-episodes-21-22-fifty-pictures::WKRP In Cincinnati S02E21-22 Fifty Pictures.mp4": 2931,
  "wkrp-in-cincinnati-season-02-episodes-23-24-venus-risingmost-improved-station::WKRP In Cincinnati S02E23-24 Venus Rising-Most Improved Station.mp4": 3001,
  "wkrp-s-1-e-20-young-master-carlson::WKRP S2E24 Most Improved Station.mp4": 1500,
  "wkrp-in-cincinnati-season-03-episodes-01-03-the-airplane-showreal-families::WKRP In Cincinnati S03E01-3 The Airplane Show-Real Families.mp4": 2939,
  "wkrp-s-1-e-20-young-master-carlson::WKRP S3E02 Jennifer Moves.mp4": 1495,
  "wkrp-s-1-e-20-young-master-carlson::WKRP S3E03 Real Families.mp4": 1492,
  "wkrp-in-cincinnati-season-03-episodes-04-05-the-babyhotel-oceanview::WKRP In Cincinnati S03E04-5 The Baby-Hotel Oceanview.mp4": 2879,
  "wkrp-s-1-e-20-young-master-carlson::WKRP S3E05 Hotel Oceanview.mp4": 1457,
  "wkrp-in-cincinnati-season-03-episode-06-a-mile-in-my-shoes::WKRP in Cincinnati S03E06 A Mile in My Shoes.mp4": 1500,
  "wkrp-s-1-e-20-young-master-carlson::WKRP S3E07 Bah, Humbug.mp4": 1445,
  "wkrp-in-cincinnati-season-03-episodes-08-09-baby-its-cold-outsidethe-painting::WKRP In Cincinnati S03E08-9 Baby, It's Cold Outside-The Painting.mp4": 2998,
  "wkrp-s-1-e-20-young-master-carlson::WKRP S3E09 The Painting.mp4": 1499,
  "wkrp-in-cincinnati-season-03-episodes-10-11-daydreamsfrog-story::WKRP In Cincinnati S03E10-11 Daydreams-Frog Story.mp4": 2992,
  "wkrp-s-1-e-20-young-master-carlson::WKRP S3E11 Frog Story.mp4": 1499,
  "wkrp-s-1-e-20-young-master-carlson::WKRP S3E12 Venus and the Man.mp4": 1496,
  "wkrp-in-cincinnati-season-03-episodes-13-14-dr.-fever-mr.-tide::WKRP In Cincinnati S03E13-14 Dr. Fever & Mr. Tide.mp4": 2852,
  "wkrp-in-cincinnati-season-03-episodes-15-16-ask-jenniferi-am-woman::WKRP in Cincinnati S03E15-16 Ask Jennifer-I Am Woman.mp4": 3000,
  "wkrp-s-1-e-20-young-master-carlson::WKRP S3E16 I Am Woman.mp4": 1501,
  "wkrp-in-cincinnati-season-03-episodes-17-18-secrets-of-dayton-heightsout-to-lunch::WKRP In Cincinnati S03E17-18 Secrets of Dayton Heights-Out To Lunch.mp4": 2988,
  "wkrp-s-1-e-20-young-master-carlson::WKRP S3E18 Out to Lunch.mp4": 1500,
  "wkrp-in-cincinnati-season-03-episodes-19-20-a-simple-little-weddingnothing-to-fear-but...::WKRP In Cincinnati S03E19-20 A Simple Little Wedding-Nothing to Fear But....mp4": 2970,
  "wkrp-s-1-e-20-young-master-carlson::WKRP S3E20 Nothing to Fear But....mp4": 1498,
  "wkrp-in-cincinnati-season-03-episode-21-till-debt-do-us-part::WKRP In Cincinnati S03E21 Till Debt Do Us Part.mp4": 1493,
  "wkrp-in-cincinnati-season-03-episode-22-clean-up-radio-everywhere::WKRP In Cincinnati S03E22 Clean Up Radio Everywhere.mp4": 1495,
  "wkrp-in-cincinnati-season-04-episodes-01-02-an-explosive-affair::WKRP In Cincinnati S04E01-02 An Explosive Affair.mp4": 2619,
  "wkrp-s-1-e-20-young-master-carlson::WKRP S4E02 An Explosive Affair Pt 2.mp4": 1446,
  "wkrp-in-cincinnati-season-04-episodes-03-04-the-unionrumors::WKRP In Cincinnati S04E03-4 The Union-Rumors.mp4": 2869,
  "wkrp-s-1-e-20-young-master-carlson::WKRP S4E04 Rumors.mp4": 1446,
  "wkrp-in-cincinnati-season-04-episodes-05-06-straight-from-the-heartwhos-on-first::WKRP In Cincinnati S04E05-06 Straight From The Heart-Who's On First.mp4": 2891,
  "wkrp-s-1-e-20-young-master-carlson::WKRP S4E06 Who's on First.mp4": 1447,
  "wkrp-s-1-e-20-young-master-carlson::WKRP S4E07 Three Days of the Condo.mp4": 1447,
  "wkrp-s-1-e-20-young-master-carlson::WKRP S4E08 Jennifer and the Will.mp4": 1446,
  "wkrp-s-1-e-20-young-master-carlson::WKRP S4E09 The Consultant.mp4": 1446,
  "wkrp-s-1-e-20-young-master-carlson::WKRP S4E10 Love+Exciting and New.mp4": 1426,
  "wkrp-in-cincinnati-season-04-episodes-11-12-you-cant-go-out-of-town-againpills::WKRP In Cincinnati S04E11-12 You Can't Go Out of Town Again-Pills.mp4": 2888,
  "wkrp-s-1-e-20-young-master-carlson::WKRP S4E12 Pills.mp4": 1445,
  "wkrp-in-cincinnati-season-04-episode-13-changes::WKRP In Cincinnati S04E13 Changes.mp4": 1497,
  "wkrp-s-1-e-20-young-master-carlson::WKRP S4E14 Jennifer and Johnny's Charity.mp4": 1496,
  "wkrp-in-cincinnati-season-04-episode-15-ill-take-romance::WKRP In Cincinnati S04E15 I'll Take Romance.mp4": 1494,
  "wkrp-in-cincinnati-season-04-episode-16-circumstantial-evidence::WKRP In Cincinnati S04E16 Circumstantial Evidence.mp4": 1496,
  "wkrp-in-cincinnati-season-04-episode-17-fire::WKRP In Cincinnati S04E17 Fire.mp4": 1486,
  "wkrp-s-1-e-20-young-master-carlson::WKRP S4E18 Dear Liar.mp4": 1497,
  "wkrp-s-1-e-20-young-master-carlson::WKRP S4E19 The Creation of Venus.mp4": 1498,
  "wkrp-in-cincinnati-season-04-episode-20-the-impossible-dream::WKRP In Cincinnati S04E20 The Impossible Dream.mp4": 1468,
  "wkrp-in-cincinnati-season-04-episode-21-to-err-is-human::WKRP In Cincinnati S04E21 To Err Is Human.mp4": 1495,
  "wkrp-in-cincinnati-season-04-episode-22-up-and-down-the-dial-last-final-episode::WKRP In Cincinnati S04E22 Up And Down The Dial (Last Final Episode).mp4": 1495,
},
};
