window.SHOW = {
  id: "BattlestarGalactica2004",
  title: "Battlestar Galactica (2004)",
  art: "BattlestarGalactica2004.jpg",
  storageProgressKey: "battlestargalactica2004-progress",
  storageSettingsKey: "battlestargalactica2004-settings",
  nestedPaths: true,
  grouping: "season",
  segments: "none",
  seasonNames: { 0: "Miniseries" },
  episodes: [
  ["battlestar-galactica-s-02-e-20", "BATTLESTAR GALACTICA - S00E01 - Miniseries (Part 1)",
    "BATTLESTAR GALACTICA/MINISERIES/Battlestar Galactica Miniseries Part 1  (1080p x265 10bit Joy).mp4"],
  ["battlestar-galactica-s-02-e-20", "BATTLESTAR GALACTICA - S00E02 - Miniseries (Part 2)",
    "BATTLESTAR GALACTICA/MINISERIES/Battlestar Galactica Miniseries Part 2  (1080p x265 10bit Joy).mp4"],
  ["battlestar-galactica-s-02-e-20", "BATTLESTAR GALACTICA - S01E01 - 33",
    "BATTLESTAR GALACTICA/Battlestar.Galactica.Season.1/Battlestar_Galactica_-_S01E01.mp4"],
  ["battlestar-galactica-s-02-e-20", "BATTLESTAR GALACTICA - S01E02 - Water",
    "BATTLESTAR GALACTICA/Battlestar.Galactica.Season.1/Battlestar_Galactica_-_S01E02.mp4"],
  ["battlestar-galactica-s-02-e-20", "BATTLESTAR GALACTICA - S01E03 - Bastille Day",
    "BATTLESTAR GALACTICA/Battlestar.Galactica.Season.1/Battlestar_Galactica_-_S01E03.mp4"],
  ["battlestar-galactica-s-02-e-20", "BATTLESTAR GALACTICA - S01E04 - Act of Contrition",
    "BATTLESTAR GALACTICA/Battlestar.Galactica.Season.1/Battlestar_Galactica_-_S01E04.mp4"],
  ["battlestar-galactica-s-02-e-20", "BATTLESTAR GALACTICA - S01E05 - You Can't Go Home Again",
    "BATTLESTAR GALACTICA/Battlestar.Galactica.Season.1/Battlestar_Galactica_-_S01E05.mp4"],
  ["battlestar-galactica-s-02-e-20", "BATTLESTAR GALACTICA - S01E06 - Litmus",
    "BATTLESTAR GALACTICA/Battlestar.Galactica.Season.1/Battlestar_Galactica_-_S01E06.mp4"],
  ["battlestar-galactica-s-02-e-20", "BATTLESTAR GALACTICA - S01E07 - Six Degrees of Separation",
    "BATTLESTAR GALACTICA/Battlestar.Galactica.Season.1/Battlestar_Galactica_-_S01E07.mp4"],
  ["battlestar-galactica-s-02-e-20", "BATTLESTAR GALACTICA - S01E08 - Flesh and Bone",
    "BATTLESTAR GALACTICA/Battlestar.Galactica.Season.1/Battlestar_Galactica_-_S01E08.mp4"],
  ["battlestar-galactica-s-02-e-20", "BATTLESTAR GALACTICA - S01E09 - Tigh Me Up, Tigh Me Down",
    "BATTLESTAR GALACTICA/Battlestar.Galactica.Season.1/Battlestar_Galactica_-_S01E09.mp4"],
  ["battlestar-galactica-s-02-e-20", "BATTLESTAR GALACTICA - S01E10 - The Hand of God",
    "BATTLESTAR GALACTICA/Battlestar.Galactica.Season.1/Battlestar_Galactica_-_S01E10.mp4"],
  ["battlestar-galactica-s-02-e-20", "BATTLESTAR GALACTICA - S01E11 - Colonial Day",
    "BATTLESTAR GALACTICA/Battlestar.Galactica.Season.1/Battlestar_Galactica_-_S01E11.mp4"],
  ["battlestar-galactica-s-02-e-20", "BATTLESTAR GALACTICA - S01E12 - Kobol's Last Gleaming (Part 1)",
    "BATTLESTAR GALACTICA/Battlestar.Galactica.Season.1/Battlestar_Galactica_-_S01E12.mp4"],
  ["battlestar-galactica-s-02-e-20", "BATTLESTAR GALACTICA - S01E13 - Kobol's Last Gleaming (Part 2)",
    "BATTLESTAR GALACTICA/Battlestar.Galactica.Season.1/Battlestar_Galactica_-_S01E13.mp4"],
  ["battlestar-galactica-s-02-e-20", "BATTLESTAR GALACTICA - S02E01 - Scattered",
    "BATTLESTAR GALACTICA/Battlestar.Galactica.Season.2/Battlestar_Galactica_-_S02E01.mp4"],
  ["battlestar-galactica-s-02-e-20", "BATTLESTAR GALACTICA - S02E02 - Valley of Darkness",
    "BATTLESTAR GALACTICA/Battlestar.Galactica.Season.2/Battlestar_Galactica_-_S02E02.mp4"],
  ["battlestar-galactica-s-02-e-20", "BATTLESTAR GALACTICA - S02E03 - Fragged",
    "BATTLESTAR GALACTICA/Battlestar.Galactica.Season.2/Battlestar_Galactica_-_S02E03.mp4"],
  ["battlestar-galactica-s-02-e-20", "BATTLESTAR GALACTICA - S02E04 - Resistance",
    "BATTLESTAR GALACTICA/Battlestar.Galactica.Season.2/Battlestar_Galactica_-_S02E04.mp4"],
  ["battlestar-galactica-s-02-e-20", "BATTLESTAR GALACTICA - S02E05 - The Farm",
    "BATTLESTAR GALACTICA/Battlestar.Galactica.Season.2/Battlestar_Galactica_-_S02E05.mp4"],
  ["battlestar-galactica-s-02-e-20", "BATTLESTAR GALACTICA - S02E06 - Home (Part 1)",
    "BATTLESTAR GALACTICA/Battlestar.Galactica.Season.2/Battlestar_Galactica_-_S02E06.mp4"],
  ["battlestar-galactica-s-02-e-20", "BATTLESTAR GALACTICA - S02E07 - Home (Part 2)",
    "BATTLESTAR GALACTICA/Battlestar.Galactica.Season.2/Battlestar_Galactica_-_S02E07.mp4"],
  ["battlestar-galactica-s-02-e-20", "BATTLESTAR GALACTICA - S02E08 - Final Cut",
    "BATTLESTAR GALACTICA/Battlestar.Galactica.Season.2/Battlestar_Galactica_-_S02E08.mp4"],
  ["battlestar-galactica-s-02-e-20", "BATTLESTAR GALACTICA - S02E09 - Flight of the Phoenix",
    "BATTLESTAR GALACTICA/Battlestar.Galactica.Season.2/Battlestar_Galactica_-_S02E09.mp4"],
  ["battlestar-galactica-s-02-e-20", "BATTLESTAR GALACTICA - S02E10 - Pegasus",
    "BATTLESTAR GALACTICA/Battlestar.Galactica.Season.2/Battlestar_Galactica_-_S02E10.mp4"],
  ["battlestar-galactica-s-02-e-20", "BATTLESTAR GALACTICA - S02E11 - Resurrection Ship (Part 1)",
    "BATTLESTAR GALACTICA/Battlestar.Galactica.Season.2/Battlestar_Galactica_-_S02E11.mp4"],
  ["battlestar-galactica-s-02-e-20", "BATTLESTAR GALACTICA - S02E12 - Resurrection Ship (Part 2)",
    "BATTLESTAR GALACTICA/Battlestar.Galactica.Season.2/Battlestar_Galactica_-_S02E12.mp4"],
  ["battlestar-galactica-s-02-e-20", "BATTLESTAR GALACTICA - S02E13 - Epiphanies",
    "BATTLESTAR GALACTICA/Battlestar.Galactica.Season.2/Battlestar_Galactica_-_S02E13.mp4"],
  ["battlestar-galactica-s-02-e-20", "BATTLESTAR GALACTICA - S02E14 - Black Market",
    "BATTLESTAR GALACTICA/Battlestar.Galactica.Season.2/Battlestar_Galactica_-_S02E14.mp4"],
  ["battlestar-galactica-s-02-e-20", "BATTLESTAR GALACTICA - S02E15 - Scar",
    "BATTLESTAR GALACTICA/Battlestar.Galactica.Season.2/Battlestar_Galactica_-_S02E15.mp4"],
  ["battlestar-galactica-s-02-e-20", "BATTLESTAR GALACTICA - S02E16 - Sacrifice",
    "BATTLESTAR GALACTICA/Battlestar.Galactica.Season.2/Battlestar_Galactica_-_S02E16.mp4"],
  ["battlestar-galactica-s-02-e-20", "BATTLESTAR GALACTICA - S02E17 - The Captain's Hand",
    "BATTLESTAR GALACTICA/Battlestar.Galactica.Season.2/Battlestar_Galactica_-_S02E17.mp4"],
  ["battlestar-galactica-s-02-e-20", "BATTLESTAR GALACTICA - S02E18 - Downloaded",
    "BATTLESTAR GALACTICA/Battlestar.Galactica.Season.2/Battlestar_Galactica_-_S02E18.mp4"],
  ["battlestar-galactica-s-02-e-20", "BATTLESTAR GALACTICA - S02E19 - Lay Down Your Burdens (Part 1)",
    "BATTLESTAR GALACTICA/Battlestar.Galactica.Season.2/Battlestar_Galactica_-_S02E19.mp4"],
  ["battlestar-galactica-s-02-e-20", "BATTLESTAR GALACTICA - S02E20 - Lay Down Your Burdens (Part 2)",
    "BATTLESTAR GALACTICA/Battlestar.Galactica.Season.2/Battlestar_Galactica_-_S02E20.mp4"],
  ["battlestar-galactica-s-02-e-20", "BATTLESTAR GALACTICA - S03E01 - Occupation",
    "BATTLESTAR GALACTICA/Battlestar.Galactica.Season.3/Battlestar_Galactica_-_S03E01.mp4"],
  ["battlestar-galactica-s-02-e-20", "BATTLESTAR GALACTICA - S03E02 - Precipice",
    "BATTLESTAR GALACTICA/Battlestar.Galactica.Season.3/Battlestar_Galactica_-_S03E02.mp4"],
  ["battlestar-galactica-s-02-e-20", "BATTLESTAR GALACTICA - S03E03 - Exodus (Part 1)",
    "BATTLESTAR GALACTICA/Battlestar.Galactica.Season.3/Battlestar_Galactica_-_S03E03.mp4"],
  ["battlestar-galactica-s-02-e-20", "BATTLESTAR GALACTICA - S03E04 - Exodus (Part 2)",
    "BATTLESTAR GALACTICA/Battlestar.Galactica.Season.3/Battlestar_Galactica_-_S03E04.mp4"],
  ["battlestar-galactica-s-02-e-20", "BATTLESTAR GALACTICA - S03E05 - Collaborators",
    "BATTLESTAR GALACTICA/Battlestar.Galactica.Season.3/Battlestar_Galactica_-_S03E05.mp4"],
  ["battlestar-galactica-s-02-e-20", "BATTLESTAR GALACTICA - S03E06 - Torn",
    "BATTLESTAR GALACTICA/Battlestar.Galactica.Season.3/Battlestar_Galactica_-_S03E06.mp4"],
  ["battlestar-galactica-s-02-e-20", "BATTLESTAR GALACTICA - S03E07 - A Measure of Salvation",
    "BATTLESTAR GALACTICA/Battlestar.Galactica.Season.3/Battlestar_Galactica_-_S03E07.mp4"],
  ["battlestar-galactica-s-02-e-20", "BATTLESTAR GALACTICA - S03E08 - Hero",
    "BATTLESTAR GALACTICA/Battlestar.Galactica.Season.3/Battlestar_Galactica_-_S03E08.mp4"],
  ["battlestar-galactica-s-02-e-20", "BATTLESTAR GALACTICA - S03E09 - Unfinished Business",
    "BATTLESTAR GALACTICA/Battlestar.Galactica.Season.3/Battlestar_Galactica_-_S03E09.mp4"],
  ["battlestar-galactica-s-02-e-20", "BATTLESTAR GALACTICA - S03E10 - The Passage",
    "BATTLESTAR GALACTICA/Battlestar.Galactica.Season.3/Battlestar_Galactica_-_S03E10.mp4"],
  ["battlestar-galactica-s-02-e-20", "BATTLESTAR GALACTICA - S03E11 - The Eye of Jupiter",
    "BATTLESTAR GALACTICA/Battlestar.Galactica.Season.3/Battlestar_Galactica_-_S03E11.mp4"],
  ["battlestar-galactica-s-02-e-20", "BATTLESTAR GALACTICA - S03E12 - Rapture",
    "BATTLESTAR GALACTICA/Battlestar.Galactica.Season.3/Battlestar_Galactica_-_S03E12.mp4"],
  ["battlestar-galactica-s-02-e-20", "BATTLESTAR GALACTICA - S03E13 - Taking a Break from All Your Worries",
    "BATTLESTAR GALACTICA/Battlestar.Galactica.Season.3/Battlestar_Galactica_-_S03E13.mp4"],
  ["battlestar-galactica-s-02-e-20", "BATTLESTAR GALACTICA - S03E14 - The Woman King",
    "BATTLESTAR GALACTICA/Battlestar.Galactica.Season.3/Battlestar_Galactica_-_S03E14.mp4"],
  ["battlestar-galactica-s-02-e-20", "BATTLESTAR GALACTICA - S03E15 - A Day in the Life",
    "BATTLESTAR GALACTICA/Battlestar.Galactica.Season.3/Battlestar_Galactica_-_S03E15.mp4"],
  ["battlestar-galactica-s-02-e-20", "BATTLESTAR GALACTICA - S03E16 - Dirty Hands",
    "BATTLESTAR GALACTICA/Battlestar.Galactica.Season.3/Battlestar_Galactica_-_S03E16.mp4"],
  ["battlestar-galactica-s-02-e-20", "BATTLESTAR GALACTICA - S03E17 - Maelstrom",
    "BATTLESTAR GALACTICA/Battlestar.Galactica.Season.3/Battlestar_Galactica_-_S03E17.mp4"],
  ["battlestar-galactica-s-02-e-20", "BATTLESTAR GALACTICA - S03E18 - The Son Also Rises",
    "BATTLESTAR GALACTICA/Battlestar.Galactica.Season.3/Battlestar_Galactica_-_S03E18.mp4"],
  ["battlestar-galactica-s-02-e-20", "BATTLESTAR GALACTICA - S03E19 - Crossroads (Part 1)",
    "BATTLESTAR GALACTICA/Battlestar.Galactica.Season.3/Battlestar_Galactica_-_S03E19.mp4"],
  ["battlestar-galactica-s-02-e-20", "BATTLESTAR GALACTICA - S03E20 - Crossroads (Part 2)",
    "BATTLESTAR GALACTICA/Battlestar.Galactica.Season.3/Battlestar_Galactica_-_S03E20.mp4"],
  ["battlestar-galactica-s-02-e-20", "BATTLESTAR GALACTICA - S04E01 - He That Believeth in Me",
    "BATTLESTAR GALACTICA/Battlestar.Galactica.Season.4/Battlestar Galactica - S04E01 - He That Believeth In Me.mp4"],
  ["battlestar-galactica-s-02-e-20", "BATTLESTAR GALACTICA - S04E02 - Six of One",
    "BATTLESTAR GALACTICA/Battlestar.Galactica.Season.4/Battlestar Galactica - S04E02 - Six Of One.mp4"],
  ["battlestar-galactica-s-02-e-20", "BATTLESTAR GALACTICA - S04E03 - The Ties That Bind",
    "BATTLESTAR GALACTICA/Battlestar.Galactica.Season.4/Battlestar Galactica - S04E03 - The Ties That Bind.mp4"],
  ["battlestar-galactica-s-02-e-20", "BATTLESTAR GALACTICA - S04E04 - Escape Velocity",
    "BATTLESTAR GALACTICA/Battlestar.Galactica.Season.4/Battlestar Galactica - S04E04 - Escape Velocity.mp4"],
  ["battlestar-galactica-s-02-e-20", "BATTLESTAR GALACTICA - S04E05 - The Road Less Traveled",
    "BATTLESTAR GALACTICA/Battlestar.Galactica.Season.4/Battlestar Galactica - S04E05 - The Road Less Travelled.mp4"],
  ["battlestar-galactica-s-02-e-20", "BATTLESTAR GALACTICA - S04E06 - Faith",
    "BATTLESTAR GALACTICA/Battlestar.Galactica.Season.4/Battlestar Galactica - S04E06 - Faith.mp4"],
  ["battlestar-galactica-s-02-e-20", "BATTLESTAR GALACTICA - S04E07 - Guess What's Coming to Dinner?",
    "BATTLESTAR GALACTICA/Battlestar.Galactica.Season.4/Battlestar Galactica - S04E07 - Guess What's Coming To Dinner.mp4"],
  ["battlestar-galactica-s-02-e-20", "BATTLESTAR GALACTICA - S04E08 - Sine Qua Non",
    "BATTLESTAR GALACTICA/Battlestar.Galactica.Season.4/Battlestar Galactica - S04E08 - Sine Qua Non.mp4"],
  ["battlestar-galactica-s-02-e-20", "BATTLESTAR GALACTICA - S04E09 - The Hub",
    "BATTLESTAR GALACTICA/Battlestar.Galactica.Season.4/Battlestar Galactica - S04E09 - The Hub.mp4"],
  ["battlestar-galactica-s-02-e-20", "BATTLESTAR GALACTICA - S04E10 - Revelations",
    "BATTLESTAR GALACTICA/Battlestar.Galactica.Season.4/Battlestar Galactica - S04E10 - Revelations.mp4"],
  ["battlestar-galactica-s-02-e-20", "BATTLESTAR GALACTICA - S04E11 - Sometimes a Great Notion",
    "BATTLESTAR GALACTICA/Battlestar.Galactica.Season.4/Battlestar Galactica - S04E11 - Sometimes A Great Notion.mp4"],
  ["battlestar-galactica-s-02-e-20", "BATTLESTAR GALACTICA - S04E12 - A Disquiet Follows My Soul",
    "BATTLESTAR GALACTICA/Battlestar.Galactica.Season.4/Battlestar Galactica - S04E12 - A Disquiet Follows My Soul.mp4"],
  ["battlestar-galactica-s-02-e-20", "BATTLESTAR GALACTICA - S04E13 - The Oath",
    "BATTLESTAR GALACTICA/Battlestar.Galactica.Season.4/Battlestar Galactica - S04E13 - The Oath.mp4"],
  ["battlestar-galactica-s-02-e-20", "BATTLESTAR GALACTICA - S04E14 - Blood on the Scales",
    "BATTLESTAR GALACTICA/Battlestar.Galactica.Season.4/Battlestar Galactica - S04E14 - Blood On The Scales.mp4"],
  ["battlestar-galactica-s-02-e-20", "BATTLESTAR GALACTICA - S04E15 - No Exit",
    "BATTLESTAR GALACTICA/Battlestar.Galactica.Season.4/Battlestar Galactica - S04E15.mp4"],
  ["battlestar-galactica-s-02-e-20", "BATTLESTAR GALACTICA - S04E16 - Deadlock",
    "BATTLESTAR GALACTICA/Battlestar.Galactica.Season.4/Battlestar Galactica - S04E16.mp4"],
  ["battlestar-galactica-s-02-e-20", "BATTLESTAR GALACTICA - S04E17 - Someone to Watch Over Me",
    "BATTLESTAR GALACTICA/Battlestar.Galactica.Season.4/Battlestar Galactica - S04E17.mp4"],
  ["battlestar-galactica-s-02-e-20", "BATTLESTAR GALACTICA - S04E18 - Islanded in a Stream of Stars",
    "BATTLESTAR GALACTICA/Battlestar.Galactica.Season.4/Battlestar Galactica - S04E18.mp4"],
  ["battlestar-galactica-s-02-e-20", "BATTLESTAR GALACTICA - S04E19 - Daybreak (Part 1)",
    "BATTLESTAR GALACTICA/Battlestar.Galactica.Season.4/Battlestar Galactica - S04E19.mp4"],
  ["battlestar-galactica-s-02-e-20", "BATTLESTAR GALACTICA - S04E20-21 - Daybreak (Part 2) / Daybreak (Part 3)",
    "BATTLESTAR GALACTICA/Battlestar.Galactica.Season.4/Battlestar Galactica - S04E20 The Frakking Series Finale.mp4"],
  ],
  durations: {
  "battlestar-galactica-s-02-e-20::BATTLESTAR GALACTICA/MINISERIES/Battlestar Galactica Miniseries Part 1  (1080p x265 10bit Joy).mp4": 5679,
  "battlestar-galactica-s-02-e-20::BATTLESTAR GALACTICA/MINISERIES/Battlestar Galactica Miniseries Part 2  (1080p x265 10bit Joy).mp4": 5370,
  "battlestar-galactica-s-02-e-20::BATTLESTAR GALACTICA/Battlestar.Galactica.Season.1/Battlestar_Galactica_-_S01E01.mp4": 2574,
  "battlestar-galactica-s-02-e-20::BATTLESTAR GALACTICA/Battlestar.Galactica.Season.1/Battlestar_Galactica_-_S01E02.mp4": 2512,
  "battlestar-galactica-s-02-e-20::BATTLESTAR GALACTICA/Battlestar.Galactica.Season.1/Battlestar_Galactica_-_S01E03.mp4": 2520,
  "battlestar-galactica-s-02-e-20::BATTLESTAR GALACTICA/Battlestar.Galactica.Season.1/Battlestar_Galactica_-_S01E04.mp4": 2508,
  "battlestar-galactica-s-02-e-20::BATTLESTAR GALACTICA/Battlestar.Galactica.Season.1/Battlestar_Galactica_-_S01E05.mp4": 2517,
  "battlestar-galactica-s-02-e-20::BATTLESTAR GALACTICA/Battlestar.Galactica.Season.1/Battlestar_Galactica_-_S01E06.mp4": 2519,
  "battlestar-galactica-s-02-e-20::BATTLESTAR GALACTICA/Battlestar.Galactica.Season.1/Battlestar_Galactica_-_S01E07.mp4": 2519,
  "battlestar-galactica-s-02-e-20::BATTLESTAR GALACTICA/Battlestar.Galactica.Season.1/Battlestar_Galactica_-_S01E08.mp4": 2515,
  "battlestar-galactica-s-02-e-20::BATTLESTAR GALACTICA/Battlestar.Galactica.Season.1/Battlestar_Galactica_-_S01E09.mp4": 2516,
  "battlestar-galactica-s-02-e-20::BATTLESTAR GALACTICA/Battlestar.Galactica.Season.1/Battlestar_Galactica_-_S01E10.mp4": 2518,
  "battlestar-galactica-s-02-e-20::BATTLESTAR GALACTICA/Battlestar.Galactica.Season.1/Battlestar_Galactica_-_S01E11.mp4": 2517,
  "battlestar-galactica-s-02-e-20::BATTLESTAR GALACTICA/Battlestar.Galactica.Season.1/Battlestar_Galactica_-_S01E12.mp4": 2519,
  "battlestar-galactica-s-02-e-20::BATTLESTAR GALACTICA/Battlestar.Galactica.Season.1/Battlestar_Galactica_-_S01E13.mp4": 2516,
  "battlestar-galactica-s-02-e-20::BATTLESTAR GALACTICA/Battlestar.Galactica.Season.2/Battlestar_Galactica_-_S02E01.mp4": 2640,
  "battlestar-galactica-s-02-e-20::BATTLESTAR GALACTICA/Battlestar.Galactica.Season.2/Battlestar_Galactica_-_S02E02.mp4": 2632,
  "battlestar-galactica-s-02-e-20::BATTLESTAR GALACTICA/Battlestar.Galactica.Season.2/Battlestar_Galactica_-_S02E03.mp4": 2643,
  "battlestar-galactica-s-02-e-20::BATTLESTAR GALACTICA/Battlestar.Galactica.Season.2/Battlestar_Galactica_-_S02E04.mp4": 2646,
  "battlestar-galactica-s-02-e-20::BATTLESTAR GALACTICA/Battlestar.Galactica.Season.2/Battlestar_Galactica_-_S02E05.mp4": 2642,
  "battlestar-galactica-s-02-e-20::BATTLESTAR GALACTICA/Battlestar.Galactica.Season.2/Battlestar_Galactica_-_S02E06.mp4": 2644,
  "battlestar-galactica-s-02-e-20::BATTLESTAR GALACTICA/Battlestar.Galactica.Season.2/Battlestar_Galactica_-_S02E07.mp4": 2644,
  "battlestar-galactica-s-02-e-20::BATTLESTAR GALACTICA/Battlestar.Galactica.Season.2/Battlestar_Galactica_-_S02E08.mp4": 2648,
  "battlestar-galactica-s-02-e-20::BATTLESTAR GALACTICA/Battlestar.Galactica.Season.2/Battlestar_Galactica_-_S02E09.mp4": 2645,
  "battlestar-galactica-s-02-e-20::BATTLESTAR GALACTICA/Battlestar.Galactica.Season.2/Battlestar_Galactica_-_S02E10.mp4": 2747,
  "battlestar-galactica-s-02-e-20::BATTLESTAR GALACTICA/Battlestar.Galactica.Season.2/Battlestar_Galactica_-_S02E11.mp4": 2622,
  "battlestar-galactica-s-02-e-20::BATTLESTAR GALACTICA/Battlestar.Galactica.Season.2/Battlestar_Galactica_-_S02E12.mp4": 2623,
  "battlestar-galactica-s-02-e-20::BATTLESTAR GALACTICA/Battlestar.Galactica.Season.2/Battlestar_Galactica_-_S02E13.mp4": 2626,
  "battlestar-galactica-s-02-e-20::BATTLESTAR GALACTICA/Battlestar.Galactica.Season.2/Battlestar_Galactica_-_S02E14.mp4": 2517,
  "battlestar-galactica-s-02-e-20::BATTLESTAR GALACTICA/Battlestar.Galactica.Season.2/Battlestar_Galactica_-_S02E15.mp4": 2636,
  "battlestar-galactica-s-02-e-20::BATTLESTAR GALACTICA/Battlestar.Galactica.Season.2/Battlestar_Galactica_-_S02E16.mp4": 2565,
  "battlestar-galactica-s-02-e-20::BATTLESTAR GALACTICA/Battlestar.Galactica.Season.2/Battlestar_Galactica_-_S02E17.mp4": 2519,
  "battlestar-galactica-s-02-e-20::BATTLESTAR GALACTICA/Battlestar.Galactica.Season.2/Battlestar_Galactica_-_S02E18.mp4": 2493,
  "battlestar-galactica-s-02-e-20::BATTLESTAR GALACTICA/Battlestar.Galactica.Season.2/Battlestar_Galactica_-_S02E19.mp4": 2516,
  "battlestar-galactica-s-02-e-20::BATTLESTAR GALACTICA/Battlestar.Galactica.Season.2/Battlestar_Galactica_-_S02E20.mp4": 3905,
  "battlestar-galactica-s-02-e-20::BATTLESTAR GALACTICA/Battlestar.Galactica.Season.3/Battlestar_Galactica_-_S03E01.mp4": 2591,
  "battlestar-galactica-s-02-e-20::BATTLESTAR GALACTICA/Battlestar.Galactica.Season.3/Battlestar_Galactica_-_S03E02.mp4": 2587,
  "battlestar-galactica-s-02-e-20::BATTLESTAR GALACTICA/Battlestar.Galactica.Season.3/Battlestar_Galactica_-_S03E03.mp4": 2513,
  "battlestar-galactica-s-02-e-20::BATTLESTAR GALACTICA/Battlestar.Galactica.Season.3/Battlestar_Galactica_-_S03E04.mp4": 2510,
  "battlestar-galactica-s-02-e-20::BATTLESTAR GALACTICA/Battlestar.Galactica.Season.3/Battlestar_Galactica_-_S03E05.mp4": 2525,
  "battlestar-galactica-s-02-e-20::BATTLESTAR GALACTICA/Battlestar.Galactica.Season.3/Battlestar_Galactica_-_S03E06.mp4": 2524,
  "battlestar-galactica-s-02-e-20::BATTLESTAR GALACTICA/Battlestar.Galactica.Season.3/Battlestar_Galactica_-_S03E07.mp4": 2464,
  "battlestar-galactica-s-02-e-20::BATTLESTAR GALACTICA/Battlestar.Galactica.Season.3/Battlestar_Galactica_-_S03E08.mp4": 2599,
  "battlestar-galactica-s-02-e-20::BATTLESTAR GALACTICA/Battlestar.Galactica.Season.3/Battlestar_Galactica_-_S03E09.mp4": 2519,
  "battlestar-galactica-s-02-e-20::BATTLESTAR GALACTICA/Battlestar.Galactica.Season.3/Battlestar_Galactica_-_S03E10.mp4": 2520,
  "battlestar-galactica-s-02-e-20::BATTLESTAR GALACTICA/Battlestar.Galactica.Season.3/Battlestar_Galactica_-_S03E11.mp4": 2516,
  "battlestar-galactica-s-02-e-20::BATTLESTAR GALACTICA/Battlestar.Galactica.Season.3/Battlestar_Galactica_-_S03E12.mp4": 2519,
  "battlestar-galactica-s-02-e-20::BATTLESTAR GALACTICA/Battlestar.Galactica.Season.3/Battlestar_Galactica_-_S03E13.mp4": 2517,
  "battlestar-galactica-s-02-e-20::BATTLESTAR GALACTICA/Battlestar.Galactica.Season.3/Battlestar_Galactica_-_S03E14.mp4": 2520,
  "battlestar-galactica-s-02-e-20::BATTLESTAR GALACTICA/Battlestar.Galactica.Season.3/Battlestar_Galactica_-_S03E15.mp4": 2510,
  "battlestar-galactica-s-02-e-20::BATTLESTAR GALACTICA/Battlestar.Galactica.Season.3/Battlestar_Galactica_-_S03E16.mp4": 2517,
  "battlestar-galactica-s-02-e-20::BATTLESTAR GALACTICA/Battlestar.Galactica.Season.3/Battlestar_Galactica_-_S03E17.mp4": 2513,
  "battlestar-galactica-s-02-e-20::BATTLESTAR GALACTICA/Battlestar.Galactica.Season.3/Battlestar_Galactica_-_S03E18.mp4": 2569,
  "battlestar-galactica-s-02-e-20::BATTLESTAR GALACTICA/Battlestar.Galactica.Season.3/Battlestar_Galactica_-_S03E19.mp4": 2570,
  "battlestar-galactica-s-02-e-20::BATTLESTAR GALACTICA/Battlestar.Galactica.Season.3/Battlestar_Galactica_-_S03E20.mp4": 2755,
  "battlestar-galactica-s-02-e-20::BATTLESTAR GALACTICA/Battlestar.Galactica.Season.4/Battlestar Galactica - S04E01 - He That Believeth In Me.mp4": 2515,
  "battlestar-galactica-s-02-e-20::BATTLESTAR GALACTICA/Battlestar.Galactica.Season.4/Battlestar Galactica - S04E02 - Six Of One.mp4": 2499,
  "battlestar-galactica-s-02-e-20::BATTLESTAR GALACTICA/Battlestar.Galactica.Season.4/Battlestar Galactica - S04E03 - The Ties That Bind.mp4": 2520,
  "battlestar-galactica-s-02-e-20::BATTLESTAR GALACTICA/Battlestar.Galactica.Season.4/Battlestar Galactica - S04E04 - Escape Velocity.mp4": 2517,
  "battlestar-galactica-s-02-e-20::BATTLESTAR GALACTICA/Battlestar.Galactica.Season.4/Battlestar Galactica - S04E05 - The Road Less Travelled.mp4": 2515,
  "battlestar-galactica-s-02-e-20::BATTLESTAR GALACTICA/Battlestar.Galactica.Season.4/Battlestar Galactica - S04E06 - Faith.mp4": 2520,
  "battlestar-galactica-s-02-e-20::BATTLESTAR GALACTICA/Battlestar.Galactica.Season.4/Battlestar Galactica - S04E07 - Guess What's Coming To Dinner.mp4": 2520,
  "battlestar-galactica-s-02-e-20::BATTLESTAR GALACTICA/Battlestar.Galactica.Season.4/Battlestar Galactica - S04E08 - Sine Qua Non.mp4": 2517,
  "battlestar-galactica-s-02-e-20::BATTLESTAR GALACTICA/Battlestar.Galactica.Season.4/Battlestar Galactica - S04E09 - The Hub.mp4": 2524,
  "battlestar-galactica-s-02-e-20::BATTLESTAR GALACTICA/Battlestar.Galactica.Season.4/Battlestar Galactica - S04E10 - Revelations.mp4": 2523,
  "battlestar-galactica-s-02-e-20::BATTLESTAR GALACTICA/Battlestar.Galactica.Season.4/Battlestar Galactica - S04E11 - Sometimes A Great Notion.mp4": 2688,
  "battlestar-galactica-s-02-e-20::BATTLESTAR GALACTICA/Battlestar.Galactica.Season.4/Battlestar Galactica - S04E12 - A Disquiet Follows My Soul.mp4": 2519,
  "battlestar-galactica-s-02-e-20::BATTLESTAR GALACTICA/Battlestar.Galactica.Season.4/Battlestar Galactica - S04E13 - The Oath.mp4": 2515,
  "battlestar-galactica-s-02-e-20::BATTLESTAR GALACTICA/Battlestar.Galactica.Season.4/Battlestar Galactica - S04E14 - Blood On The Scales.mp4": 2517,
  "battlestar-galactica-s-02-e-20::BATTLESTAR GALACTICA/Battlestar.Galactica.Season.4/Battlestar Galactica - S04E15.mp4": 2588,
  "battlestar-galactica-s-02-e-20::BATTLESTAR GALACTICA/Battlestar.Galactica.Season.4/Battlestar Galactica - S04E16.mp4": 2582,
  "battlestar-galactica-s-02-e-20::BATTLESTAR GALACTICA/Battlestar.Galactica.Season.4/Battlestar Galactica - S04E17.mp4": 2599,
  "battlestar-galactica-s-02-e-20::BATTLESTAR GALACTICA/Battlestar.Galactica.Season.4/Battlestar Galactica - S04E18.mp4": 2594,
  "battlestar-galactica-s-02-e-20::BATTLESTAR GALACTICA/Battlestar.Galactica.Season.4/Battlestar Galactica - S04E19.mp4": 2595,
  "battlestar-galactica-s-02-e-20::BATTLESTAR GALACTICA/Battlestar.Galactica.Season.4/Battlestar Galactica - S04E20 The Frakking Series Finale.mp4": 5734,
  },
};
