window.SHOW = {
  id: "ABCsFridays",
  title: "ABC's Fridays",
  art: "ABCsFridays.jpg",
  storageProgressKey: "abcsfridays-progress",
  storageSettingsKey: "abcsfridays-settings",
  nestedPaths: true,
  grouping: "season",
  segments: "none",
  episodes: [
  ["fridaynightlive", "ABC'S FRIDAYS - S01E01 - Kenny Loggins",
    "S01E01 Kenny Loggins.mp4"],
  ["fridaynightlive", "ABC'S FRIDAYS - S01E02 - The Boomtown Rats",
    "S01E02 The Boomtown Rats.mp4"],
  ["fridaynightlive", "ABC'S FRIDAYS - S01E03 - The Clash",
    "S01E03 The Clash.mp4"],
  ["fridaynightlive", "ABC'S FRIDAYS - S01E05 - Boz Scaggs",
    "S01E05 Boz Scaggs.mp4"],
  ["fridaynightlive", "ABC'S FRIDAYS - S01E06 - Devo",
    "S01E06 Devo.mp4"],
  ["fridaynightlive", "ABC'S FRIDAYS - S01E08 - Tom Petty",
    "S01E08 Tom Petty.mp4"],
  ["fridaynightlive", "ABC'S FRIDAYS - S01E09 - The Beach Boys",
    "S01E09 The Beach Boys.mp4"],
  ["fridaynightlive", "ABC'S FRIDAYS - S01E10 - Graham Parker",
    "S01E10 Graham Parker.mp4"],
  ["fridaynightlive", "ABC'S FRIDAYS - S01E12 - The Jam",
    "S01E12 The Jam.mp4"],
  ["fridaynightlive", "ABC'S FRIDAYS - S01E13 - Journey",
    "S01E13 Journey.mp4"],
  ["fridaynightlive", "ABC'S FRIDAYS - S02E03 - The Cars",
    "S02E03 The Cars.mp4"],
  ["fridaynightlive", "ABC'S FRIDAYS - S02E07 - Dire Straits",
    "S02E07 Dire Straits.mp4"],
  ["fridaynightlive", "ABC'S FRIDAYS - S02E08 - Devo Again",
    "S02E08 Devo Again [Alternate Source].mp4"],
  ["fridaynightlive", "ABC'S FRIDAYS - S02E09 - The Busboys",
    "S02E09 The Busboys.mp4"],
  ["fridaynightlive", "ABC'S FRIDAYS - S02E11 - Pat Benatar",
    "S02E11 Pat Benatar [Alternate Source].mp4"],
  ["fridaynightlive", "ABC'S FRIDAYS - S02E13 - Steve Forbert",
    "S02E13 Steve Forbert.mp4"],
  ["fridaynightlive", "ABC'S FRIDAYS - S02E15 - George Carlin; George Thorogood",
    "S02E15 George Carlin; George Thorogood.mp4"],
  ["fridaynightlive", "ABC'S FRIDAYS - S02E16 - Shelley Winters; The Plasmatics",
    "S02E16 Shelley Winters; The Plasmatics.mp4"],
  ["fridaynightlive", "ABC'S FRIDAYS - S02E17 - Henny Youngman; REO Speedwagon",
    "S02E17 Henny Youngman; REO Speedwagon.mp4"],
  ["fridaynightlive", "ABC'S FRIDAYS - S02E18 - Valerie Bertinelli; Jim Carroll",
    "S02E18 Valerie Bertinelli; Jim Carroll.mp4"],
  ["fridaynightlive", "ABC'S FRIDAYS - S02E19 - Michael McKean & David Lander; Kool & The Gang",
    "S02E19 Michael McKean & David Lander; Kool & The Gang.mp4"],
  ["fridaynightlive", "ABC'S FRIDAYS - S02E20 - Andy Kaufman; The Sir Douglas Quintet",
    "S02E20 Andy Kaufman; The Sir Douglas Quintet.mp4"],
  ["fridaynightlive", "ABC'S FRIDAYS - S02E21 - Billy Crystal; Randy Meisner",
    "S02E21 Billy Crystal; Randy Meisner.ia.mp4"],
  ["fridaynightlive", "ABC'S FRIDAYS - S02E22 - David Steinberg; The Marshall Tucker Band",
    "S02E22 David Steinberg; The Marshall Tucker Band.mp4"],
  ["fridaynightlive", "ABC'S FRIDAYS - S02E24 - Madeline Kahn; Frankie & The Knockouts",
    "S02E24 Madeline Kahn; Frankie & The Knockouts.mp4"],
  ["fridaynightlive", "ABC'S FRIDAYS - S02E25 - Mark Hamill; Jimmy Buffett",
    "S02E25 Mark Hamill; Jimmy Buffett [Alternate Source].mp4"],
  ["fridaynightlive", "ABC'S FRIDAYS - S02E26 - Gary Hamilton; The Gary U.S. Bonds",
    "S02E26 Gary Hamilton; The Gary U.S. Bonds.mp4"],
  ["fridaynightlive", "ABC'S FRIDAYS - S03E01 - Andy Kaufman; The Pretenders",
    "S03E01 Andy Kaufman; The Pretenders.mp4"],
  ["fridaynightlive", "ABC'S FRIDAYS - S03E02 - William Shatner; Kim Carnes",
    "S03E02 William Shatner; Kim Carnes.mp4"],
  ["fridaynightlive", "ABC'S FRIDAYS - S03E03 - TOny Geary & Genie Francis; Devo",
    "S03E03 TOny Geary & Genie Francis; Devo.mp4"],
  ["fridaynightlive", "ABC'S FRIDAYS - S03E04 - Karen Allen; The Stray Cats",
    "S03E04 Karen Allen; The Stray Cats.ia.mp4"],
  ["fridaynightlive", "ABC'S FRIDAYS - S03E05 - Marty Feldman; The Manhattan Transfer",
    "S03E05 Marty Feldman; The Manhattan Transfer.mp4"],
  ["fridaynightlive", "ABC'S FRIDAYS - S03E06 - David Naughton; Billy & The Beaters",
    "S03E06 David Naughton; Billy & The Beaters.mp4"],
  ["fridaynightlive", "ABC'S FRIDAYS - S03E10 - Susan Sarandon; The Four Tops",
    "S03E10 Susan Sarandon; The Four Tops.mp4"],
  ["fridaynightlive", "ABC'S FRIDAYS - S03E12 - Valerie Harper; The Cars",
    "S03E12 Valerie Harper; The Cars.mp4"],
  ["fridaynightlive", "ABC'S FRIDAYS - S03E13 - Tab Hunter; Kiss",
    "S03E13 Tab Hunter; Kiss.ia.mp4"],
  ["fridaynightlive", "ABC'S FRIDAYS - S03E14 - Howard E. Rollins Jr.; Quarterflash",
    "S03E14 Howard E. Rollins Jr.; Quarterflash.mp4"],
],
  durations: {
  "fridaynightlive::S01E01 Kenny Loggins.mp4": 2700,
  "fridaynightlive::S01E02 The Boomtown Rats.mp4": 3138,
  "fridaynightlive::S01E03 The Clash.mp4": 2492,
  "fridaynightlive::S01E05 Boz Scaggs.mp4": 3192,
  "fridaynightlive::S01E06 Devo.mp4": 3130,
  "fridaynightlive::S01E08 Tom Petty.mp4": 2898,
  "fridaynightlive::S01E09 The Beach Boys.mp4": 3120,
  "fridaynightlive::S01E10 Graham Parker.mp4": 2720,
  "fridaynightlive::S01E12 The Jam.mp4": 4230,
  "fridaynightlive::S01E13 Journey.mp4": 3060,
  "fridaynightlive::S02E03 The Cars.mp4": 2219,
  "fridaynightlive::S02E07 Dire Straits.mp4": 2791,
  "fridaynightlive::S02E08 Devo Again [Alternate Source].mp4": 4171,
  "fridaynightlive::S02E09 The Busboys.mp4": 2281,
  "fridaynightlive::S02E11 Pat Benatar [Alternate Source].mp4": 3587,
  "fridaynightlive::S02E13 Steve Forbert.mp4": 2060,
  "fridaynightlive::S02E15 George Carlin; George Thorogood.mp4": 2566,
  "fridaynightlive::S02E16 Shelley Winters; The Plasmatics.mp4": 4134,
  "fridaynightlive::S02E17 Henny Youngman; REO Speedwagon.mp4": 3106,
  "fridaynightlive::S02E18 Valerie Bertinelli; Jim Carroll.mp4": 3094,
  "fridaynightlive::S02E19 Michael McKean & David Lander; Kool & The Gang.mp4": 4298,
  "fridaynightlive::S02E20 Andy Kaufman; The Sir Douglas Quintet.mp4": 2330,
  "fridaynightlive::S02E21 Billy Crystal; Randy Meisner.ia.mp4": 2780,
  "fridaynightlive::S02E22 David Steinberg; The Marshall Tucker Band.mp4": 4040,
  "fridaynightlive::S02E24 Madeline Kahn; Frankie & The Knockouts.mp4": 4200,
  "fridaynightlive::S02E25 Mark Hamill; Jimmy Buffett [Alternate Source].mp4": 5428,
  "fridaynightlive::S02E26 Gary Hamilton; The Gary U.S. Bonds.mp4": 4455,
  "fridaynightlive::S03E01 Andy Kaufman; The Pretenders.mp4": 3903,
  "fridaynightlive::S03E02 William Shatner; Kim Carnes.mp4": 5341,
  "fridaynightlive::S03E03 TOny Geary & Genie Francis; Devo.mp4": 4008,
  "fridaynightlive::S03E04 Karen Allen; The Stray Cats.ia.mp4": 2376,
  "fridaynightlive::S03E05 Marty Feldman; The Manhattan Transfer.mp4": 5283,
  "fridaynightlive::S03E06 David Naughton; Billy & The Beaters.mp4": 3993,
  "fridaynightlive::S03E10 Susan Sarandon; The Four Tops.mp4": 1866,
  "fridaynightlive::S03E12 Valerie Harper; The Cars.mp4": 3175,
  "fridaynightlive::S03E13 Tab Hunter; Kiss.ia.mp4": 2710,
  "fridaynightlive::S03E14 Howard E. Rollins Jr.; Quarterflash.mp4": 3946,
},
};
