window.SHOW = {
  id: "BakersfieldPD",
  title: "Bakersfield, P.D.",
  art: "BakersfieldPD.jpg",
  storageProgressKey: "bakersfieldpd-progress",
  storageSettingsKey: "bakersfieldpd-settings",
  nestedPaths: true,
  grouping: "season",
  segments: "none",
  episodes: [
  ["bakersfield_pd", "BAKERSFIELD, P.D. - S01E01 - Pilot",
    "Bakersfield, P.D. S01E01 Pilot.mp4"],
  ["bakersfield_pd", "BAKERSFIELD, P.D. - S01E02 - The Imposter",
    "Bakersfield, P.D. S01E02 The Imposter.mp4"],
  ["bakersfield_pd", "BAKERSFIELD, P.D. - S01E03 - Unsolved Mysteries of Love",
    "Bakersfield, P.D. S01E03 Unsolved Mysteries of Love.mp4"],
  ["bakersfield_pd", "BAKERSFIELD, P.D. - S01E04 - The Snake Charmer",
    "Bakersfield, P.D. S01E04 The Snake Charmer.mp4"],
  ["bakersfield_pd", "BAKERSFIELD, P.D. - S01E05 - The Poker Game",
    "Bakersfield, P.D. S01E05 The Poker Game.mp4"],
  ["bakersfield_pd", "BAKERSFIELD, P.D. - S01E06 - The Bust",
    "Bakersfield, P.D. S01E06 The Bust.mp4"],
  ["bakersfield_pd", "BAKERSFIELD, P.D. - S01E07 - The Ex-Partner",
    "Bakersfield, P.D. S01E07 The Ex-Partner.mp4"],
  ["bakersfield_pd", "BAKERSFIELD, P.D. - S01E08 - Bakersfield Madam",
    "Bakersfield, P.D. S01E08 Bakersfield Madam.mp4"],
  ["bakersfield_pd", "BAKERSFIELD, P.D. - S01E09 - Cable Does Not Pay",
    "Bakersfield, P.D. S01E09 Cable Does Not Pay.mp4"],
  ["bakersfield_pd", "BAKERSFIELD, P.D. - S01E10 - The Gift",
    "Bakersfield, P.D. S01E10 The Gift.mp4"],
  ["bakersfield_pd", "BAKERSFIELD, P.D. - S01E11 - The President's Coming",
    "Bakersfield, P.D. S01E11 The President's Coming.mp4"],
  ["bakersfield_pd", "BAKERSFIELD, P.D. - S01E12 - A Bullet for Stiles",
    "Bakersfield, P.D. S01E12 A Bullet for Stiles.mp4"],
  ["bakersfield_pd", "BAKERSFIELD, P.D. - S01E13 - Lucky 13",
    "Bakersfield, P.D. S01E13 Lucky 13.mp4"],
  ["bakersfield_pd", "BAKERSFIELD, P.D. - S01E14 - Arms and the Men",
    "Bakersfield, P.D. S01E14 Arms and the Men.mp4"],
  ["bakersfield_pd", "BAKERSFIELD, P.D. - S01E15 - There Goes the Neighborhood",
    "Bakersfield, P.D. S01E15 There Goes the Neighborhood.mp4"],
  ["bakersfield_pd", "BAKERSFIELD, P.D. - S01E16 - The Psychic and the C-Cup",
    "Bakersfield, P.D. S01E16 The Psychic and the C-Cup.mp4"],
  ["bakersfield_pd", "BAKERSFIELD, P.D. - S01E17 - Last One Into the Water",
    "Bakersfield, P.D. S01E17 Last One Into the Water.mp4"],
],
  durations: {
  "bakersfield_pd::Bakersfield, P.D. S01E01 Pilot.mp4": 1365,
  "bakersfield_pd::Bakersfield, P.D. S01E02 The Imposter.mp4": 1318,
  "bakersfield_pd::Bakersfield, P.D. S01E03 Unsolved Mysteries of Love.mp4": 1316,
  "bakersfield_pd::Bakersfield, P.D. S01E04 The Snake Charmer.mp4": 1289,
  "bakersfield_pd::Bakersfield, P.D. S01E05 The Poker Game.mp4": 1312,
  "bakersfield_pd::Bakersfield, P.D. S01E06 The Bust.mp4": 1316,
  "bakersfield_pd::Bakersfield, P.D. S01E07 The Ex-Partner.mp4": 1314,
  "bakersfield_pd::Bakersfield, P.D. S01E08 Bakersfield Madam.mp4": 1317,
  "bakersfield_pd::Bakersfield, P.D. S01E09 Cable Does Not Pay.mp4": 1314,
  "bakersfield_pd::Bakersfield, P.D. S01E10 The Gift.mp4": 1287,
  "bakersfield_pd::Bakersfield, P.D. S01E11 The President's Coming.mp4": 1312,
  "bakersfield_pd::Bakersfield, P.D. S01E12 A Bullet for Stiles.mp4": 1316,
  "bakersfield_pd::Bakersfield, P.D. S01E13 Lucky 13.mp4": 1310,
  "bakersfield_pd::Bakersfield, P.D. S01E14 Arms and the Men.mp4": 1316,
  "bakersfield_pd::Bakersfield, P.D. S01E15 There Goes the Neighborhood.mp4": 1314,
  "bakersfield_pd::Bakersfield, P.D. S01E16 The Psychic and the C-Cup.mp4": 1317,
  "bakersfield_pd::Bakersfield, P.D. S01E17 Last One Into the Water.mp4": 1314,
},
};
