window.SHOW = {
  id: "MightyMousetheNewAdventures",
  title: "Mighty Mouse: The New Adventures",
  art: "MightyMousetheNewAdventures.jpg",
  storageProgressKey: "mightymousethenewadventures-progress",
  storageSettingsKey: "mightymousethenewadventures-settings",
  nestedPaths: true,
  grouping: "season",
  segments: "none",
  episodes: [
  ["mighty-mouse-the-new-adventures-season-1", "MIGHTY MOUSE THE NEW ADVENTURES - S01E01 - Night on Bald Pate",
    "S01 E01 - Night on Bald Pate + Mouse from Another House.mp4"],
  ["mighty-mouse-the-new-adventures-season-1", "MIGHTY MOUSE THE NEW ADVENTURES - S01E02 - Mouse from Another House",
    "S01 E02 - Me-Yowww! + Witch Tricks.mp4"],
  ["mighty-mouse-the-new-adventures-season-1", "MIGHTY MOUSE THE NEW ADVENTURES - S01E03 - Me-Yowww!",
    "S01 E03 - Night of the Bat-Bat + Scrap-Happy.mp4"],
  ["mighty-mouse-the-new-adventures-season-1", "MIGHTY MOUSE THE NEW ADVENTURES - S01E04 - Witch Tricks",
    "S01 E04 - Catastrophe Cat + Scrappy's Field Day.mp4"],
  ["mighty-mouse-the-new-adventures-season-1", "MIGHTY MOUSE THE NEW ADVENTURES - S01E05 - Night of the Bat-Bat",
    "S01 E05 - The Bagmouse + The First Deadly Cheese.mp4"],
  ["mighty-mouse-the-new-adventures-season-1", "MIGHTY MOUSE THE NEW ADVENTURES - S01E06 - Scrap-Happy",
    "S01 E06 - This Island is Mouseville + Mighty's Musical Classics.mp4"],
  ["mighty-mouse-the-new-adventures-season-1", "MIGHTY MOUSE THE NEW ADVENTURES - S01E07 - Catastrophe Cat",
    "S01 E07 - The Littlest Tramp + Puffy Goes Berserk.mp4"],
  ["mighty-mouse-the-new-adventures-season-1", "MIGHTY MOUSE THE NEW ADVENTURES - S01E08 - Scrappy's Field Day",
    "S01 E08 - The League of Super-Rodents + Scrappy's Playhouse.mp4"],
  ["mighty-mouse-the-new-adventures-season-1", "MIGHTY MOUSE THE NEW ADVENTURES - S01E09 - The Bagmouse",
    "S01 E09 - All You Need is Glove + It's Scrappy's Birthday.mp4"],
  ["mighty-mouse-the-new-adventures-season-1", "MIGHTY MOUSE THE NEW ADVENTURES - S01E10 - The First Deadly Cheese",
    "S01 E10 - Aqua-Guppy + Animation Concerto.mp4"],
  ["mighty-mouse-the-new-adventures-season-1", "MIGHTY MOUSE THE NEW ADVENTURES - S01E11 - This Island Mouseville",
    "S01 E11 - The Ice Goose Cometh + Pirates with Dirty Faces.mp4"],
  ["mighty-mouse-the-new-adventures-season-1", "MIGHTY MOUSE THE NEW ADVENTURES - S01E12 - Mighty's Musical Classics",
    "S01 E12 - Mighty's Benefit Plan + See You in the Funny Papers.mp4"],
  ["mighty-mouse-the-new-adventures-season-1", "MIGHTY MOUSE THE NEW ADVENTURES - S01E13 - The Littlest Tramp",
    "S01 E13 - Heroes and Zeroes + Stress for Success.mp4"],
  ["mighty-mouse-the-new-adventures-season-2", "MIGHTY MOUSE THE NEW ADVENTURES - S02E01 - Day of the Mice",
    "S02 E01 - Day of the Mice + Still Oily After All These Years.mp4"],
  ["mighty-mouse-the-new-adventures-season-2", "MIGHTY MOUSE THE NEW ADVENTURES - S02E02 - Still Oily After All These Years",
    "S02 E02 - Mighty's Wedlock Whimsy + Anatomy of a Milquetoast.mp4"],
  ["mighty-mouse-the-new-adventures-season-2", "MIGHTY MOUSE THE NEW ADVENTURES - S02E03 - Mighty's Wedlock Whimsy",
    "S02 E03 - Bat with a Golden Tounge + Mundane Voyage.mp4"],
  ["mighty-mouse-the-new-adventures-season-2", "MIGHTY MOUSE THE NEW ADVENTURES - S02E04 - Anatomy of a Milquetoast",
    "S02 E04 - Snow White & the Motor City Dwarfs + Don't Touch That Dial!.mp4"],
  ["mighty-mouse-the-new-adventures-season-2", "MIGHTY MOUSE THE NEW ADVENTURES - S02E05 - Bat with a Golden Tongue",
    "S02 E05 - Mouse and Supermouse + The Bride of Mighty Mouse.mp4"],
  ["mighty-mouse-the-new-adventures-season-2", "MIGHTY MOUSE THE NEW ADVENTURES - S02E06 - Mundane Voyage",
    "S02 E06 - A Star is Milked + Mighty's Tone Poem.mp4"],
],
  durations: {
  "mighty-mouse-the-new-adventures-season-1::S01 E01 - Night on Bald Pate + Mouse from Another House.mp4": 1440,
  "mighty-mouse-the-new-adventures-season-1::S01 E02 - Me-Yowww! + Witch Tricks.mp4": 1440,
  "mighty-mouse-the-new-adventures-season-1::S01 E03 - Night of the Bat-Bat + Scrap-Happy.mp4": 1440,
  "mighty-mouse-the-new-adventures-season-1::S01 E04 - Catastrophe Cat + Scrappy's Field Day.mp4": 1440,
  "mighty-mouse-the-new-adventures-season-1::S01 E05 - The Bagmouse + The First Deadly Cheese.mp4": 1440,
  "mighty-mouse-the-new-adventures-season-1::S01 E06 - This Island is Mouseville + Mighty's Musical Classics.mp4": 1440,
  "mighty-mouse-the-new-adventures-season-1::S01 E07 - The Littlest Tramp + Puffy Goes Berserk.mp4": 1440,
  "mighty-mouse-the-new-adventures-season-1::S01 E08 - The League of Super-Rodents + Scrappy's Playhouse.mp4": 1440,
  "mighty-mouse-the-new-adventures-season-1::S01 E09 - All You Need is Glove + It's Scrappy's Birthday.mp4": 1440,
  "mighty-mouse-the-new-adventures-season-1::S01 E10 - Aqua-Guppy + Animation Concerto.mp4": 1440,
  "mighty-mouse-the-new-adventures-season-1::S01 E11 - The Ice Goose Cometh + Pirates with Dirty Faces.mp4": 1440,
  "mighty-mouse-the-new-adventures-season-1::S01 E12 - Mighty's Benefit Plan + See You in the Funny Papers.mp4": 1440,
  "mighty-mouse-the-new-adventures-season-1::S01 E13 - Heroes and Zeroes + Stress for Success.mp4": 1440,
  "mighty-mouse-the-new-adventures-season-2::S02 E01 - Day of the Mice + Still Oily After All These Years.mp4": 1440,
  "mighty-mouse-the-new-adventures-season-2::S02 E02 - Mighty's Wedlock Whimsy + Anatomy of a Milquetoast.mp4": 1440,
  "mighty-mouse-the-new-adventures-season-2::S02 E03 - Bat with a Golden Tounge + Mundane Voyage.mp4": 1440,
  "mighty-mouse-the-new-adventures-season-2::S02 E04 - Snow White & the Motor City Dwarfs + Don't Touch That Dial!.mp4": 1445,
  "mighty-mouse-the-new-adventures-season-2::S02 E05 - Mouse and Supermouse + The Bride of Mighty Mouse.mp4": 1440,
  "mighty-mouse-the-new-adventures-season-2::S02 E06 - A Star is Milked + Mighty's Tone Poem.mp4": 1440,
},
};
