window.SHOW = {
  id: "Everwood",
  title: "Everwood",
  art: "Everwood.jpg",
  storageProgressKey: "everwood-progress",
  storageSettingsKey: "everwood-settings",
  nestedPaths: true,
  grouping: "season",
  segments: "none",
  episodes: [
  ["everwood-the-complete-series", "EVERWOOD - S01E01 - Pilot",
    "Everwood S01E01 - Pilot.mp4"],
  ["everwood-the-complete-series", "EVERWOOD - S01E02 - The Great Doctor Brown",
    "Everwood S01E02 - The Great Doctor Brown.mp4"],
  ["everwood-the-complete-series", "EVERWOOD - S01E03 - Friendly Fire",
    "Everwood S01E03 - Friendly Fire.mp4"],
  ["everwood-the-complete-series", "EVERWOOD - S01E04 - The Kissing Bridge",
    "Everwood S01E04 - The Kissing Bridge..mp4"],
  ["everwood-the-complete-series", "EVERWOOD - S01E05 - Deer God",
    "Everwood S01E05 - Deer God.mp4"],
  ["everwood-the-complete-series", "EVERWOOD - S01E06 - The Doctor Is In",
    "Everwood S01E06 - The Doctor is in.mp4"],
  ["everwood-the-complete-series", "EVERWOOD - S01E07 - We Hold These Truths",
    "Everwood S01E07 - We Hold These Truths.mp4"],
  ["everwood-the-complete-series", "EVERWOOD - S01E08 - Till Death Do Us Part",
    "Everwood S01E08 - Till Death Do Us Part.mp4"],
  ["everwood-the-complete-series", "EVERWOOD - S01E09 - Turf Wars",
    "Everwood S01E09 - Turf Wars.mp4"],
  ["everwood-the-complete-series", "EVERWOOD - S01E10 - Is There a Doctor in the House?",
    "Everwood S01E10 - Is There A Doctor in The House.mp4"],
  ["everwood-the-complete-series", "EVERWOOD - S01E11 - A Thanksgiving Tale",
    "Everwood S01E11- A Thanksgiving Tale.mp4"],
  ["everwood-the-complete-series", "EVERWOOD - S01E12 - Vegetative State",
    "Everwood S01E12 - Vegetative State.mp4"],
  ["everwood-the-complete-series", "EVERWOOD - S01E13 - The Price of Fame",
    "Everwood S01E13 - The Price of Fame.mp4"],
  ["everwood-the-complete-series", "EVERWOOD - S01E14 - Colin the Second",
    "Everwood S01E14 - Colin The Second.mp4"],
  ["everwood-the-complete-series", "EVERWOOD - S01E15 - Snow Job",
    "Everwood S01E15 - Snow Job.mp4"],
  ["everwood-the-complete-series", "EVERWOOD - S01E16 - My Funny Valentine",
    "Everwood S01E16 - My Funny Valentine.mp4"],
  ["everwood-the-complete-series", "EVERWOOD - S01E17 - Everwood Confidential",
    "Everwood S01E17 - Everwood Confidential.mp4"],
  ["everwood-the-complete-series", "EVERWOOD - S01E18 - The Unveiling",
    "Everwood S01E18 - The Unveiling.mp4"],
  ["everwood-the-complete-series", "EVERWOOD - S01E19 - The Miracle of Everwood",
    "Everwood S01E19 - The Miracle of Everwood.mp4"],
  ["everwood-the-complete-series", "EVERWOOD - S01E20 - Moonlight Sonata",
    "Everwood S01E20 - Moonlight Sonata.mp4"],
  ["everwood-the-complete-series", "EVERWOOD - S01E21 - Episode 20",
    "Everwood S01E21 - Episode 20.mp4"],
  ["everwood-the-complete-series", "EVERWOOD - S01E22 - Fear Itself",
    "Everwood S01E22 - Fear Itself.mp4"],
  ["everwood-the-complete-series", "EVERWOOD - S01E23 - Home",
    "Everwood S01E23- Home.mp4"],
  ["everwood-the-complete-series", "EVERWOOD - S02E01 - The Last of Summer",
    "Everwood S02E01 - The Last of Summer.mp4"],
  ["everwood-the-complete-series", "EVERWOOD - S02E02 - Extra Ordinary",
    "Everwood S02E02 - Extra Ordinary.mp4"],
  ["everwood-the-complete-series", "EVERWOOD - S02E03 - My Brother's Keeper",
    "Everwood S02E03 - My Brothers Keeper.mp4"],
  ["everwood-the-complete-series", "EVERWOOD - S02E04 - East Meets West",
    "Everwood S02E04 - East Meets West.mp4"],
  ["everwood-the-complete-series", "EVERWOOD - S02E05 - Daddy's Little Girl",
    "Everwood S02E05 - Daddys Little Girl.mp4"],
  ["everwood-the-complete-series", "EVERWOOD - S02E06 - Blind Faith",
    "Everwood S02E06- Blind Faith.mp4"],
  ["everwood-the-complete-series", "EVERWOOD - S02E07 - Three Miners from Everwood",
    "Everwood S02E07 - Three Miners from Everwood.mp4"],
  ["everwood-the-complete-series", "EVERWOOD - S02E08 - The Burden of Truth",
    "Everwood S02E08 - Burden of Truth.mp4"],
  ["everwood-the-complete-series", "EVERWOOD - S02E09 - Just Like in the Movies",
    "Everwood S02E09 - Just Like in The Movies.mp4"],
  ["everwood-the-complete-series", "EVERWOOD - S02E10 - Unhappy Holidays",
    "Everwood S02E10 - Unhappy Holidays.mp4"],
  ["everwood-the-complete-series", "EVERWOOD - S02E11 - Family Dynamics",
    "Everwood S02E11 - Family Dynamics.mp4"],
  ["everwood-the-complete-series", "EVERWOOD - S02E12 - Controlling Interest",
    "Everwood S02E12 - Controlling Interest.mp4"],
  ["everwood-the-complete-series", "EVERWOOD - S02E13 - Forget Me Not",
    "Everwood S02E13 - Forget Me Not.mp4"],
  ["everwood-the-complete-series", "EVERWOOD - S02E14 - No Sure Thing",
    "Everwood S02E14 - No Sure Thing.mp4"],
  ["everwood-the-complete-series", "EVERWOOD - S02E15 - The L Word",
    "Everwood S02E15 - The L Word.mp4"],
  ["everwood-the-complete-series", "EVERWOOD - S02E16 - Unspoken Truths",
    "Everwood S02E16 - Unspoken Truths.mp4"],
  ["everwood-the-complete-series", "EVERWOOD - S02E17 - Unfinished Business",
    "Everwood S02E17 - Unfinished Business.mp4"],
  ["everwood-the-complete-series", "EVERWOOD - S02E18 - Last Looks",
    "Everwood S02E18 - Last Looks.mp4"],
  ["everwood-the-complete-series", "EVERWOOD - S02E19 - Sick",
    "Everwood S02E19 - Sick.mp4"],
  ["everwood-the-complete-series", "EVERWOOD - S02E20 - Do or Die",
    "Everwood S02E20 -Do or Die.mp4"],
  ["everwood-the-complete-series", "EVERWOOD - S02E21 - Your Future Awaits",
    "Everwood S02E21 - Your Future Awaits.mp4"],
  ["everwood-the-complete-series", "EVERWOOD - S02E22 - The Day Is Done",
    "Everwood S02E22 - The Day is Done.mp4"],
  ["everwood-the-complete-series", "EVERWOOD - S03E01 - For Every Action...",
    "Everwood S03E01 - For Every Action.mp4"],
  ["everwood-the-complete-series", "EVERWOOD - S03E02 - ...There is a Reaction",
    "Everwood S03E02 - There  is A Reaction.mp4"],
  ["everwood-the-complete-series", "EVERWOOD - S03E03 - Staking Claim",
    "Everwood S03E03 - Staking Claim.mp4"],
  ["everwood-the-complete-series", "EVERWOOD - S03E04 - The Birds and the Batteries",
    "Everwood S03E04 - The Birds and The Batteries.mp4"],
  ["everwood-the-complete-series", "EVERWOOD - S03E05 - Sacrifice",
    "Everwood S03E05 - Sacrifice.mp4"],
  ["everwood-the-complete-series", "EVERWOOD - S03E06 - Shoot the Moon",
    "Everwood S03E06 - Shoot The Moon.mp4"],
  ["everwood-the-complete-series", "EVERWOOD - S03E07 - Best Laid Plans",
    "Everwood S03E07 - Best Laid Plans.mp4"],
  ["everwood-the-complete-series", "EVERWOOD - S03E08 - The Tipping Point",
    "Everwood S03E08 - The Tipping Point.mp4"],
  ["everwood-the-complete-series", "EVERWOOD - S03E09 - The Reflex",
    "Everwood S03E09 - The Reflex.mp4"],
  ["everwood-the-complete-series", "EVERWOOD - S03E10 - Need to Know",
    "Everwood S03E10 - Need to Know.mp4"],
  ["everwood-the-complete-series", "EVERWOOD - S03E11 - Complex Guilt",
    "Everwood S03E11 - Complex Guilt.mp4"],
  ["everwood-the-complete-series", "EVERWOOD - S03E12 - Giving Up the Girl",
    "Everwood S03E12 - Giving Up The. Girl.mp4"],
  ["everwood-the-complete-series", "EVERWOOD - S03E13 - The Perfect Day",
    "Everwood S03E13 - The Perfect Day.mp4"],
  ["everwood-the-complete-series", "EVERWOOD - S03E14 - Since You've Been Gone",
    "Everwood S03E14 - Since Youve Been Gone.mp4"],
  ["everwood-the-complete-series", "EVERWOOD - S03E15 - Surprise",
    "Everwood S03E15 - Surprise.mp4"],
  ["everwood-the-complete-series", "EVERWOOD - S03E16 - A Moment in Manhattan (a.k.a. A Mountain Town)",
    "Everwood S03E16 - A Mountain Town.mp4"],
  ["everwood-the-complete-series", "EVERWOOD - S03E17 - Fate Accomplis",
    "Everwood S03E17 - Fate Accomplis.mp4"],
  ["everwood-the-complete-series", "EVERWOOD - S03E18 - Fallout",
    "Everwood S03E18 - Fallout.mp4"],
  ["everwood-the-complete-series", "EVERWOOD - S03E19 - Acceptance",
    "Everwood S03E19 - Acceptance.mp4"],
  ["everwood-the-complete-series", "EVERWOOD - S03E20 - He Who Hesitates",
    "Everwood S03E20 - He Who Hesitates.mp4"],
  ["everwood-the-complete-series", "EVERWOOD - S03E21 - Good to Go",
    "Everwood S03E21 - Oh The Places Youll Go.mp4"],
  ["everwood-the-complete-series", "EVERWOOD - S03E22 - Where the Heart Is",
    "Everwood S03E22 - Where The Heart is.mp4"],
  ["everwood-the-complete-series", "EVERWOOD - S04E01 - A Kiss to Build a Dream On",
    "Everwood S04E01 - A Kiss to Build A Dream On.mp4"],
  ["everwood-the-complete-series", "EVERWOOD - S04E02 - The Next Step",
    "Everwood S04E02 - The Next Step.mp4"],
  ["everwood-the-complete-series", "EVERWOOD - S04E03 - Put On a Happy Face",
    "Everwood S04E03 - Put on A Happy Face.mp4"],
  ["everwood-the-complete-series", "EVERWOOD - S04E04 - Pieces of Me",
    "Everwood S04E04 - Pieces of Me.mp4"],
  ["everwood-the-complete-series", "EVERWOOD - S04E05 - Connect Four",
    "Everwood S04E05 - Connect Four.mp4"],
  ["everwood-the-complete-series", "EVERWOOD - S04E06 - Free Fall",
    "Everwood S04E06 - Free Fall.mp4"],
  ["everwood-the-complete-series", "EVERWOOD - S04E07 - Pro Choice",
    "Everwood S04E07 - Pro Choice.mp4"],
  ["everwood-the-complete-series", "EVERWOOD - S04E08 - So Long, Farewell...",
    "Everwood S04E08 - So Long Farewell.mp4"],
  ["everwood-the-complete-series", "EVERWOOD - S04E09 - Getting to Know You",
    "Everwood S04E09 - Getting to Know You.mp4"],
  ["everwood-the-complete-series", "EVERWOOD - S04E10 - Ghosts",
    "Everwood S04E10 - Ghosts.mp4"],
  ["everwood-the-complete-series", "EVERWOOD - S04E11 - Lost and Found",
    "Everwood S04E11 - Lost and Found.mp4"],
  ["everwood-the-complete-series", "EVERWOOD - S04E12 - You're a Good Man, Andy Brown",
    "Everwood S04E12 - Youre A Good Man Andy Brown.mp4"],
  ["everwood-the-complete-series", "EVERWOOD - S04E13 - An Ounce of Prevention",
    "Everwood S04E13 - An Ounce of Prevention.mp4"],
  ["everwood-the-complete-series", "EVERWOOD - S04E14 - Across the Lines",
    "Everwood S04E14 - Across The Lines.mp4"],
  ["everwood-the-complete-series", "EVERWOOD - S04E15 - The Land of Confusion",
    "Everwood S04E15 - The Land of Confusion.mp4"],
  ["everwood-the-complete-series", "EVERWOOD - S04E16 - Truth...",
    "Everwood S04E16 - Truth.mp4"],
  ["everwood-the-complete-series", "EVERWOOD - S04E17 - All the Lonely People",
    "Everwood S04E17 - All The Lonely People.mp4"],
  ["everwood-the-complete-series", "EVERWOOD - S04E18 - Enjoy the Ride",
    "Everwood S04E18 - Enjoy The Ride.mp4"],
  ["everwood-the-complete-series", "EVERWOOD - S04E19 - Reckoning",
    "Everwood S04E19 - Reckoning.mp4"],
  ["everwood-the-complete-series", "EVERWOOD - S04E20 - Goodbye, Love",
    "Everwood S04E20 - Goodbye Love..mp4"],
  ["everwood-the-complete-series", "EVERWOOD - S04E21 - Foreverwood (1)",
    "Everwood S04E21 - Foreverwood (Part 1).mp4"],
  ["everwood-the-complete-series", "EVERWOOD - S04E22 - Foreverwood (2)",
    "Everwood S04E22 - Foreverwood (Part 2).mp4"],
],
  durations: {
  "everwood-the-complete-series::Everwood S01E01 - Pilot.mp4": 2639,
  "everwood-the-complete-series::Everwood S01E02 - The Great Doctor Brown.mp4": 2606,
  "everwood-the-complete-series::Everwood S01E03 - Friendly Fire.mp4": 2595,
  "everwood-the-complete-series::Everwood S01E04 - The Kissing Bridge..mp4": 2544,
  "everwood-the-complete-series::Everwood S01E05 - Deer God.mp4": 2639,
  "everwood-the-complete-series::Everwood S01E06 - The Doctor is in.mp4": 2637,
  "everwood-the-complete-series::Everwood S01E07 - We Hold These Truths.mp4": 2600,
  "everwood-the-complete-series::Everwood S01E08 - Till Death Do Us Part.mp4": 2772,
  "everwood-the-complete-series::Everwood S01E09 - Turf Wars.mp4": 2644,
  "everwood-the-complete-series::Everwood S01E10 - Is There A Doctor in The House.mp4": 2560,
  "everwood-the-complete-series::Everwood S01E11- A Thanksgiving Tale.mp4": 2590,
  "everwood-the-complete-series::Everwood S01E12 - Vegetative State.mp4": 2634,
  "everwood-the-complete-series::Everwood S01E13 - The Price of Fame.mp4": 2662,
  "everwood-the-complete-series::Everwood S01E14 - Colin The Second.mp4": 2666,
  "everwood-the-complete-series::Everwood S01E15 - Snow Job.mp4": 2643,
  "everwood-the-complete-series::Everwood S01E16 - My Funny Valentine.mp4": 2696,
  "everwood-the-complete-series::Everwood S01E17 - Everwood Confidential.mp4": 2663,
  "everwood-the-complete-series::Everwood S01E18 - The Unveiling.mp4": 2641,
  "everwood-the-complete-series::Everwood S01E19 - The Miracle of Everwood.mp4": 2653,
  "everwood-the-complete-series::Everwood S01E20 - Moonlight Sonata.mp4": 2607,
  "everwood-the-complete-series::Everwood S01E21 - Episode 20.mp4": 2752,
  "everwood-the-complete-series::Everwood S01E22 - Fear Itself.mp4": 2622,
  "everwood-the-complete-series::Everwood S01E23- Home.mp4": 2703,
  "everwood-the-complete-series::Everwood S02E01 - The Last of Summer.mp4": 2669,
  "everwood-the-complete-series::Everwood S02E02 - Extra Ordinary.mp4": 2641,
  "everwood-the-complete-series::Everwood S02E03 - My Brothers Keeper.mp4": 2648,
  "everwood-the-complete-series::Everwood S02E04 - East Meets West.mp4": 2644,
  "everwood-the-complete-series::Everwood S02E05 - Daddys Little Girl.mp4": 2658,
  "everwood-the-complete-series::Everwood S02E06- Blind Faith.mp4": 2642,
  "everwood-the-complete-series::Everwood S02E07 - Three Miners from Everwood.mp4": 2639,
  "everwood-the-complete-series::Everwood S02E08 - Burden of Truth.mp4": 2641,
  "everwood-the-complete-series::Everwood S02E09 - Just Like in The Movies.mp4": 2632,
  "everwood-the-complete-series::Everwood S02E10 - Unhappy Holidays.mp4": 2642,
  "everwood-the-complete-series::Everwood S02E11 - Family Dynamics.mp4": 2697,
  "everwood-the-complete-series::Everwood S02E12 - Controlling Interest.mp4": 2612,
  "everwood-the-complete-series::Everwood S02E13 - Forget Me Not.mp4": 2634,
  "everwood-the-complete-series::Everwood S02E14 - No Sure Thing.mp4": 2619,
  "everwood-the-complete-series::Everwood S02E15 - The L Word.mp4": 2611,
  "everwood-the-complete-series::Everwood S02E16 - Unspoken Truths.mp4": 2600,
  "everwood-the-complete-series::Everwood S02E17 - Unfinished Business.mp4": 2621,
  "everwood-the-complete-series::Everwood S02E18 - Last Looks.mp4": 2583,
  "everwood-the-complete-series::Everwood S02E19 - Sick.mp4": 2557,
  "everwood-the-complete-series::Everwood S02E20 -Do or Die.mp4": 2628,
  "everwood-the-complete-series::Everwood S02E21 - Your Future Awaits.mp4": 2625,
  "everwood-the-complete-series::Everwood S02E22 - The Day is Done.mp4": 2620,
  "everwood-the-complete-series::Everwood S03E01 - For Every Action.mp4": 2622,
  "everwood-the-complete-series::Everwood S03E02 - There  is A Reaction.mp4": 2609,
  "everwood-the-complete-series::Everwood S03E03 - Staking Claim.mp4": 2636,
  "everwood-the-complete-series::Everwood S03E04 - The Birds and The Batteries.mp4": 2567,
  "everwood-the-complete-series::Everwood S03E05 - Sacrifice.mp4": 2620,
  "everwood-the-complete-series::Everwood S03E06 - Shoot The Moon.mp4": 2604,
  "everwood-the-complete-series::Everwood S03E07 - Best Laid Plans.mp4": 2607,
  "everwood-the-complete-series::Everwood S03E08 - The Tipping Point.mp4": 2610,
  "everwood-the-complete-series::Everwood S03E09 - The Reflex.mp4": 2610,
  "everwood-the-complete-series::Everwood S03E10 - Need to Know.mp4": 2608,
  "everwood-the-complete-series::Everwood S03E11 - Complex Guilt.mp4": 2570,
  "everwood-the-complete-series::Everwood S03E12 - Giving Up The. Girl.mp4": 2604,
  "everwood-the-complete-series::Everwood S03E13 - The Perfect Day.mp4": 2616,
  "everwood-the-complete-series::Everwood S03E14 - Since Youve Been Gone.mp4": 2591,
  "everwood-the-complete-series::Everwood S03E15 - Surprise.mp4": 2609,
  "everwood-the-complete-series::Everwood S03E16 - A Mountain Town.mp4": 2561,
  "everwood-the-complete-series::Everwood S03E17 - Fate Accomplis.mp4": 2624,
  "everwood-the-complete-series::Everwood S03E18 - Fallout.mp4": 2610,
  "everwood-the-complete-series::Everwood S03E19 - Acceptance.mp4": 2610,
  "everwood-the-complete-series::Everwood S03E20 - He Who Hesitates.mp4": 2613,
  "everwood-the-complete-series::Everwood S03E21 - Oh The Places Youll Go.mp4": 2614,
  "everwood-the-complete-series::Everwood S03E22 - Where The Heart is.mp4": 2610,
  "everwood-the-complete-series::Everwood S04E01 - A Kiss to Build A Dream On.mp4": 2578,
  "everwood-the-complete-series::Everwood S04E02 - The Next Step.mp4": 2578,
  "everwood-the-complete-series::Everwood S04E03 - Put on A Happy Face.mp4": 2574,
  "everwood-the-complete-series::Everwood S04E04 - Pieces of Me.mp4": 2463,
  "everwood-the-complete-series::Everwood S04E05 - Connect Four.mp4": 2562,
  "everwood-the-complete-series::Everwood S04E06 - Free Fall.mp4": 2492,
  "everwood-the-complete-series::Everwood S04E07 - Pro Choice.mp4": 2538,
  "everwood-the-complete-series::Everwood S04E08 - So Long Farewell.mp4": 2574,
  "everwood-the-complete-series::Everwood S04E09 - Getting to Know You.mp4": 2579,
  "everwood-the-complete-series::Everwood S04E10 - Ghosts.mp4": 2581,
  "everwood-the-complete-series::Everwood S04E11 - Lost and Found.mp4": 2568,
  "everwood-the-complete-series::Everwood S04E12 - Youre A Good Man Andy Brown.mp4": 2547,
  "everwood-the-complete-series::Everwood S04E13 - An Ounce of Prevention.mp4": 2572,
  "everwood-the-complete-series::Everwood S04E14 - Across The Lines.mp4": 2483,
  "everwood-the-complete-series::Everwood S04E15 - The Land of Confusion.mp4": 2483,
  "everwood-the-complete-series::Everwood S04E16 - Truth.mp4": 2574,
  "everwood-the-complete-series::Everwood S04E17 - All The Lonely People.mp4": 2452,
  "everwood-the-complete-series::Everwood S04E18 - Enjoy The Ride.mp4": 2572,
  "everwood-the-complete-series::Everwood S04E19 - Reckoning.mp4": 2506,
  "everwood-the-complete-series::Everwood S04E20 - Goodbye Love..mp4": 2576,
  "everwood-the-complete-series::Everwood S04E21 - Foreverwood (Part 1).mp4": 2548,
  "everwood-the-complete-series::Everwood S04E22 - Foreverwood (Part 2).mp4": 2524,
},
};
