window.SHOW = {
  id: "TheNetAmericanTVseries",
  title: "The Net (American TV series)",
  art: "TheNetAmericanTVseries.jpg",
  storageProgressKey: "thenetamericantvseries-progress",
  storageSettingsKey: "thenetamericantvseries-settings",
  grouping: "season",
  segments: "none",
  episodes: [
    [
      "the-net-complete-tv-series",
      "THE NET (AMERICAN TV SERIES) - S01E01 - Deleted",
      "The.Net.-.S01E01.-.Deleted.mp4",
    ],
    [
      "the-net-complete-tv-series",
      "THE NET (AMERICAN TV SERIES) - S01E02 - North by Northwestern",
      "The.Net.-.S01E02.-.North.by.Northwestern.mp4",
    ],
    [
      "the-net-complete-tv-series",
      "THE NET (AMERICAN TV SERIES) - S01E03 - Transplant",
      "The.Net.-.S01E03.-.Transplant.mp4",
    ],
    [
      "the-net-complete-tv-series",
      "THE NET (AMERICAN TV SERIES) - S01E04 - Bulls and Bears",
      "The.Net.-.S01E04.-.Bulls.and.Bears_corrected.mp4",
    ],
    [
      "the-net-complete-tv-series",
      "THE NET (AMERICAN TV SERIES) - S01E05 - Death of an Angel",
      "The.Net.-.S01E05.-.Death.of.an.Angel.mp4",
    ],
    [
      "the-net-complete-tv-series",
      "THE NET (AMERICAN TV SERIES) - S01E06 - Kill the Buddha",
      "The.Net.-.S01E06.-.Kill.the.Buddha_corrected.mp4",
    ],
    [
      "the-net-complete-tv-series",
      "THE NET (AMERICAN TV SERIES) - S01E07 - Fireball",
      "The.Net.-.S01E07.-.Fireball_corrected.mp4",
    ],
    [
      "the-net-complete-tv-series",
      "THE NET (AMERICAN TV SERIES) - S01E08 - Jump Vector",
      "The.Net.-.S01E08.-.Jump.Vector_corrected.mp4",
    ],
    [
      "the-net-complete-tv-series",
      "THE NET (AMERICAN TV SERIES) - S01E09 - Go Like You Know",
      "The.Net.-.S01E09.-.Go.Like.You.Know_corrected.mp4",
    ],
    [
      "the-net-complete-tv-series",
      "THE NET (AMERICAN TV SERIES) - S01E10 - Harvest",
      "The.Net.-.S01E10.-.Harvest_corrected.mp4",
    ],
    [
      "the-net-complete-tv-series",
      "THE NET (AMERICAN TV SERIES) - S01E11 - Diamonds Aren't Forever",
      "The.Net.-.S01E11.-.Diamonds.Arent.Forever_corrected.mp4",
    ],
    [
      "the-net-complete-tv-series",
      "THE NET (AMERICAN TV SERIES) - S01E12 - Pandora's Box",
      "The.Net.-.S01E12.-.Pandoras.Box_corrected.mp4",
    ],
    [
      "the-net-complete-tv-series",
      "THE NET (AMERICAN TV SERIES) - S01E13 - Sample",
      "The.Net.-.S01E13.-.Sample_corrected.mp4",
    ],
    [
      "the-net-complete-tv-series",
      "THE NET (AMERICAN TV SERIES) - S01E14 - Lucy's Life",
      "The.Net.-.S01E14.-.Lucy's.Life_corrected.mp4",
    ],
    [
      "the-net-complete-tv-series",
      "THE NET (AMERICAN TV SERIES) - S01E15 - Pay the Line",
      "The.Net.-.S01E15.-.Pay.the.line_corrected.mp4",
    ],
    [
      "the-net-complete-tv-series",
      "THE NET (AMERICAN TV SERIES) - S01E16 - Lunatic Fringe",
      "The.Net.-.S01E16.-.Lunatic Fringe_corrected.mp4",
    ],
    [
      "the-net-complete-tv-series",
      "THE NET (AMERICAN TV SERIES) - S01E17 - In Dreams",
      "The.Net.-.S01E17.-.In.Dreams_corrected.mp4",
    ],
    [
      "the-net-complete-tv-series",
      "THE NET (AMERICAN TV SERIES) - S01E18 - Y2K: Total System Failure",
      "The.Net.-.S01E18.-.Y2K-.Total.System.Failure_corrected.mp4",
    ],
    [
      "the-net-complete-tv-series",
      "THE NET (AMERICAN TV SERIES) - S01E19 - Zero",
      "The.Net.-.S01E19.-.Zero.mp4",
    ],
    [
      "the-net-complete-tv-series",
      "THE NET (AMERICAN TV SERIES) - S01E20 - Last Man Standing",
      "The.Net.-.S01E20.-.Last.Man.Standing.mp4",
    ],
    [
      "the-net-complete-tv-series",
      "THE NET (AMERICAN TV SERIES) - S01E21 - Chem Club",
      "The.Net.-.S01E21.-.Chem.Lab.mp4",
    ],
    [
      "the-net-complete-tv-series",
      "THE NET (AMERICAN TV SERIES) - S01E22 - Eye-see-you.com",
      "The.Net.-.S01E22.-.eye-see-you.com.mp4",
    ],
  ],
  durations: {
    "the-net-complete-tv-series::The.Net.-.S01E01.-.Deleted.mp4": 2579,
    "the-net-complete-tv-series::The.Net.-.S01E02.-.North.by.Northwestern.mp4": 2556,
    "the-net-complete-tv-series::The.Net.-.S01E03.-.Transplant.mp4": 2560,
    "the-net-complete-tv-series::The.Net.-.S01E04.-.Bulls.and.Bears_corrected.mp4": 2580,
    "the-net-complete-tv-series::The.Net.-.S01E05.-.Death.of.an.Angel.mp4": 2579,
    "the-net-complete-tv-series::The.Net.-.S01E06.-.Kill.the.Buddha_corrected.mp4": 2577,
    "the-net-complete-tv-series::The.Net.-.S01E07.-.Fireball_corrected.mp4": 2580,
    "the-net-complete-tv-series::The.Net.-.S01E08.-.Jump.Vector_corrected.mp4": 2580,
    "the-net-complete-tv-series::The.Net.-.S01E09.-.Go.Like.You.Know_corrected.mp4": 2583,
    "the-net-complete-tv-series::The.Net.-.S01E10.-.Harvest_corrected.mp4": 2581,
    "the-net-complete-tv-series::The.Net.-.S01E11.-.Diamonds.Arent.Forever_corrected.mp4": 2581,
    "the-net-complete-tv-series::The.Net.-.S01E12.-.Pandoras.Box_corrected.mp4": 2576,
    "the-net-complete-tv-series::The.Net.-.S01E13.-.Sample_corrected.mp4": 2580,
    "the-net-complete-tv-series::The.Net.-.S01E14.-.Lucy's.Life_corrected.mp4": 2583,
    "the-net-complete-tv-series::The.Net.-.S01E15.-.Pay.the.line_corrected.mp4": 2580,
    "the-net-complete-tv-series::The.Net.-.S01E16.-.Lunatic Fringe_corrected.mp4": 2579,
    "the-net-complete-tv-series::The.Net.-.S01E17.-.In.Dreams_corrected.mp4": 2581,
    "the-net-complete-tv-series::The.Net.-.S01E18.-.Y2K-.Total.System.Failure_corrected.mp4": 2581,
    "the-net-complete-tv-series::The.Net.-.S01E19.-.Zero.mp4": 2582,
    "the-net-complete-tv-series::The.Net.-.S01E20.-.Last.Man.Standing.mp4": 2583,
    "the-net-complete-tv-series::The.Net.-.S01E21.-.Chem.Lab.mp4": 2578,
    "the-net-complete-tv-series::The.Net.-.S01E22.-.eye-see-you.com.mp4": 2580,
  },
};
