window.SHOW = {
  id: "WhereInTheWorldIsCarmenSandiego",
  title: "Where in the World Is Carmen Sandiego?",
  art: "WhereInTheWorldIsCarmenSandiego.jpg",
  storageProgressKey: "whereintheworldiscarmensandiego-progress",
  storageSettingsKey: "whereintheworldiscarmensandiego-settings",
  nestedPaths: false,
  grouping: "season",
  segments: "none",
  episodes: [
  ['where-in-the-world-is-carmen-sandiego-tv-show-series', "WHERE IN THE WORLD IS CARMEN SANDIEGO? - S01E01 - The Taking of the Shrew",
    "WitWiCS S01 E01 The Taking of the Shrew.mp4"],
  ['where-in-the-world-is-carmen-sandiego-tv-show-series', "WHERE IN THE WORLD IS CARMEN SANDIEGO? - S01E02 - The Case of the Cribbed Crater",
    "WitWiCS S01 E02 The Case of the Cribbed Crater.mp4"],
  ['where-in-the-world-is-carmen-sandiego-tv-show-series', "WHERE IN THE WORLD IS CARMEN SANDIEGO? - S01E03 - It's the Pits",
    "WitWiCS S01 E03 It's the Pits.mp4"],
  ['where-in-the-world-is-carmen-sandiego-tv-show-series', "WHERE IN THE WORLD IS CARMEN SANDIEGO? - S01E04 - The Big Ness Mess",
    "WitWiCS S01 E04 The Big Ness Mess.mp4"],
  ['where-in-the-world-is-carmen-sandiego-tv-show-series', "WHERE IN THE WORLD IS CARMEN SANDIEGO? - S01E05 - Seizing the Sea",
    "WitWiCS S01 E05 Seizing the Sea.mp4"],
  ['where-in-the-world-is-carmen-sandiego-tv-show-series', "WHERE IN THE WORLD IS CARMEN SANDIEGO? - S01E06 - The Gateway Getaway",
    "WitWiCS S01 E06 The Gateway Getaway.mp4"],
  ['where-in-the-world-is-carmen-sandiego-tv-show-series', "WHERE IN THE WORLD IS CARMEN SANDIEGO? - S01E07 - Ripping Off the Rock",
    "WitWiCS S01 E07 Ripping Off the Rock.mp4"],
  ['where-in-the-world-is-carmen-sandiego-tv-show-series', "WHERE IN THE WORLD IS CARMEN SANDIEGO? - S01E08 - The Case of the False False Teeth",
    "WitWiCS S01 E08 The Case of the False False Teeth.mp4"],
  ['where-in-the-world-is-carmen-sandiego-tv-show-series', "WHERE IN THE WORLD IS CARMEN SANDIEGO? - S01E09 - The Lincoln Conspiracy",
    "WitWiCS S01 E09 The Lincoln Conspiracy.mp4"],
  ['where-in-the-world-is-carmen-sandiego-tv-show-series', "WHERE IN THE WORLD IS CARMEN SANDIEGO? - S01E10 - The Canal Caper",
    "WitWiCS S01 E10 The Canal Caper.mp4"],
  ['where-in-the-world-is-carmen-sandiego-tv-show-series', "WHERE IN THE WORLD IS CARMEN SANDIEGO? - S01E11 - The Great Wall Haul",
    "WitWiCS S01 E11 The Great Wall Haul.mp4"],
  ['where-in-the-world-is-carmen-sandiego-tv-show-series', "WHERE IN THE WORLD IS CARMEN SANDIEGO? - S01E12 - The Case of the Burgled Bugatti",
    "WitWiCS S01 E12 The Case of the Burgled Bugatti.mp4"],
  ['where-in-the-world-is-carmen-sandiego-tv-show-series', "WHERE IN THE WORLD IS CARMEN SANDIEGO? - S01E13 - The Square Scam",
    "WitWiCS S01 E13 The Square Scam.mp4"],
  ['where-in-the-world-is-carmen-sandiego-tv-show-series', "WHERE IN THE WORLD IS CARMEN SANDIEGO? - S01E14 - The Case of the Purloined Pen",
    "WitWiCS S01 E14 The Case of the Purloined Pen.mp4"],
  ['where-in-the-world-is-carmen-sandiego-tv-show-series', "WHERE IN THE WORLD IS CARMEN SANDIEGO? - S01E15 - The Great Liberty Lift",
    "WitWiCS S01 E15 The Great Liberty Lift.mp4"],
  ['where-in-the-world-is-carmen-sandiego-tv-show-series', "WHERE IN THE WORLD IS CARMEN SANDIEGO? - S01E16 - The S.A.T. Score Scam",
    "WitWiCS S01 E16 The S.A.T. Score Scam.mp4"],
  ['where-in-the-world-is-carmen-sandiego-tv-show-series', "WHERE IN THE WORLD IS CARMEN SANDIEGO? - S01E17 - Torch Song",
    "WitWiCS S01 E17 Torch Song.mp4"],
  ['where-in-the-world-is-carmen-sandiego-tv-show-series', "WHERE IN THE WORLD IS CARMEN SANDIEGO? - S01E18 - The Hammering Hank Heist",
    "WitWiCS S01 E18 The Hammering Hank Heist.mp4"],
  ['where-in-the-world-is-carmen-sandiego-tv-show-series', "WHERE IN THE WORLD IS CARMEN SANDIEGO? - S01E19 - Big Ben Bagged",
    "WitWiCS S01 E19 Big Ben Bagged.mp4"],
  ['where-in-the-world-is-carmen-sandiego-tv-show-series', "WHERE IN THE WORLD IS CARMEN SANDIEGO? - S01E20 - Diamonds Are a Crook's Best Friend",
    "WitWiCS S01 E20 Diamonds Are a Crook's Best Friend.mp4"],
  ['where-in-the-world-is-carmen-sandiego-tv-show-series', "WHERE IN THE WORLD IS CARMEN SANDIEGO? - S01E21 - The Bridge Bust",
    "WitWiCS S01 E21 The Bridge Bust.mp4"],
  ['where-in-the-world-is-carmen-sandiego-tv-show-series', "WHERE IN THE WORLD IS CARMEN SANDIEGO? - S01E22 - The Fall Collection Caper",
    "WitWiCS S01 E22 The Fall Collection Caper.mp4"],
  ['where-in-the-world-is-carmen-sandiego-tv-show-series', "WHERE IN THE WORLD IS CARMEN SANDIEGO? - S01E23 - Minnehaha: The Filching of the Falls",
    "WitWiCS S01 E23 Minnehaha - The Filching of the Falls.mp4"],
  ['where-in-the-world-is-carmen-sandiego-tv-show-series', "WHERE IN THE WORLD IS CARMEN SANDIEGO? - S01E24 - The Radioscope Rip-off",
    "WitWiCS S01 E24 The Radioscope Rip-off.mp4"],
  ['where-in-the-world-is-carmen-sandiego-tv-show-series', "WHERE IN THE WORLD IS CARMEN SANDIEGO? - S01E25 - Who Pinched Pisa?",
    "WitWiCS S01 E25 Who Pinched Pisa_.mp4"],
  ['where-in-the-world-is-carmen-sandiego-tv-show-series', "WHERE IN THE WORLD IS CARMEN SANDIEGO? - S01E26 - The Checkmate Checkout",
    "WitWiCS S01 E26 The Checkmate Checkout.mp4"],
  ['where-in-the-world-is-carmen-sandiego-tv-show-series', "WHERE IN THE WORLD IS CARMEN SANDIEGO? - S01E27 - The Forbidden City Snatch",
    "WitWiCS S01 E27 The Forbidden City Snatch.mp4"],
  ['where-in-the-world-is-carmen-sandiego-tv-show-series', "WHERE IN THE WORLD IS CARMEN SANDIEGO? - S01E28 - The Case of the Missing Queen",
    "WitWiCS S01 E28 The Case of the Missing Queen.mp4"],
  ['where-in-the-world-is-carmen-sandiego-tv-show-series', "WHERE IN THE WORLD IS CARMEN SANDIEGO? - S01E29 - The Raceway Rip-Off",
    "WitWiCS S01 E29 The Raceway Rip-Off.mp4"],
  ['where-in-the-world-is-carmen-sandiego-tv-show-series', "WHERE IN THE WORLD IS CARMEN SANDIEGO? - S01E30 - Brandenburglary",
    "WitWiCS S01 E30 Brandenburglary.mp4"],
  ['where-in-the-world-is-carmen-sandiego-tv-show-series', "WHERE IN THE WORLD IS CARMEN SANDIEGO? - S01E31 - The Case of the Reef Thief",
    "WitWiCS S01 E31 The Case of the Reef Thief.mp4"],
  ['where-in-the-world-is-carmen-sandiego-tv-show-series', "WHERE IN THE WORLD IS CARMEN SANDIEGO? - S01E32 - The Library Lift",
    "WitWiCS S01 E32 The Library Lift.mp4"],
  ['where-in-the-world-is-carmen-sandiego-tv-show-series', "WHERE IN THE WORLD IS CARMEN SANDIEGO? - S01E33 - The Great Head Heist",
    "WitWiCS S01 E33 The Great Head Heist.mp4"],
  ['where-in-the-world-is-carmen-sandiego-tv-show-series', "WHERE IN THE WORLD IS CARMEN SANDIEGO? - S01E34 - The Nose Knows",
    "WitWiCS S01 E34 The Nose Knows.mp4"],
  ['where-in-the-world-is-carmen-sandiego-tv-show-series', "WHERE IN THE WORLD IS CARMEN SANDIEGO? - S01E35 - The Troubled Triangle",
    "WitWiCS S01 E35 The Troubled Triangle.mp4"],
  ['where-in-the-world-is-carmen-sandiego-tv-show-series', "WHERE IN THE WORLD IS CARMEN SANDIEGO? - S01E36 - The Chunnel Channel Caper",
    "WitWiCS S01 E36 The Chunnel Channel Caper.mp4"],
  ['where-in-the-world-is-carmen-sandiego-tv-show-series', "WHERE IN THE WORLD IS CARMEN SANDIEGO? - S01E37 - The Taking of the Tower",
    "WitWiCS S01 E37 The Taking of the Tower.mp4"],
  ['where-in-the-world-is-carmen-sandiego-tv-show-series', "WHERE IN THE WORLD IS CARMEN SANDIEGO? - S01E38 - The Case of the Purloined Pipeline",
    "WitWiCS S01 E38 The Case of the Purloined Pipeline.mp4"],
  ['where-in-the-world-is-carmen-sandiego-tv-show-series', "WHERE IN THE WORLD IS CARMEN SANDIEGO? - S01E39 - Monumental Malfeasance",
    "WitWiCS S01 E39 Monumental Malfeasance.mp4"],
  ['where-in-the-world-is-carmen-sandiego-tv-show-series', "WHERE IN THE WORLD IS CARMEN SANDIEGO? - S01E40 - The Case of the Lifted Lines",
    "WitWiCS S01 E40 The Case of the Lifted Lines.mp4"],
  ['where-in-the-world-is-carmen-sandiego-tv-show-series', "WHERE IN THE WORLD IS CARMEN SANDIEGO? - S01E41 - Stompin' at the Stock Exchange",
    "WitWiCS S01 E41 Stompin' at the Stock Exchange.mp4"],
  ['where-in-the-world-is-carmen-sandiego-tv-show-series', "WHERE IN THE WORLD IS CARMEN SANDIEGO? - S01E42 - The Rosetta Rip-off",
    "WitWiCS S01 E42 The Rosetta Rip-off.mp4"],
  ['where-in-the-world-is-carmen-sandiego-tv-show-series', "WHERE IN THE WORLD IS CARMEN SANDIEGO? - S01E43 - The Time Bandit",
    "WitWiCS S01 E43 The Time Bandit.mp4"],
  ['where-in-the-world-is-carmen-sandiego-tv-show-series', "WHERE IN THE WORLD IS CARMEN SANDIEGO? - S01E44 - Who Stole the Hole?",
    "WitWiCS S01 E44 Who Stole the Hole_.mp4"],
  ['where-in-the-world-is-carmen-sandiego-tv-show-series', "WHERE IN THE WORLD IS CARMEN SANDIEGO? - S01E45 - The Fat Lady Sings No More",
    "WitWiCS S01 E45 The Fat Lady Sings No More.mp4"],
  ['where-in-the-world-is-carmen-sandiego-tv-show-series', "WHERE IN THE WORLD IS CARMEN SANDIEGO? - S01E46 - What Goes Up...",
    "WitWiCS S01 E46 What Goes Up.mp4"],
  ['where-in-the-world-is-carmen-sandiego-tv-show-series', "WHERE IN THE WORLD IS CARMEN SANDIEGO? - S01E47 - The Taking of the Towers",
    "WitWiCS S01 E47 The Taking of the Towers.mp4"],
  ['where-in-the-world-is-carmen-sandiego-tv-show-series', "WHERE IN THE WORLD IS CARMEN SANDIEGO? - S01E48 - The Case of the Roamin' Roman Ruin",
    "WitWiCS S01 E48 The Case of the Roamin' Roman Ruin.mp4"],
  ['where-in-the-world-is-carmen-sandiego-tv-show-series', "WHERE IN THE WORLD IS CARMEN SANDIEGO? - S01E49 - Hot Potato",
    "WitWiCS S01 E49 Hot Potato.mp4"],
  ['where-in-the-world-is-carmen-sandiego-tv-show-series', "WHERE IN THE WORLD IS CARMEN SANDIEGO? - S01E50 - The Case of the Pilfered Palace",
    "WitWiCS S01 E50 The Case of the Pilfered Palace.mp4"],
  ['where-in-the-world-is-carmen-sandiego-tv-show-series', "WHERE IN THE WORLD IS CARMEN SANDIEGO? - S01E51 - The Case of the Purloined Pole",
    "WitWiCS S01 E51 The Case of the Purloined Pole.mp4"],
  ['where-in-the-world-is-carmen-sandiego-tv-show-series', "WHERE IN THE WORLD IS CARMEN SANDIEGO? - S01E52 - The Case of the Missing Mountain",
    "WitWiCS S01 E52 The Case of the Missing Mountain.mp4"],
  ['where-in-the-world-is-carmen-sandiego-tv-show-series', "WHERE IN THE WORLD IS CARMEN SANDIEGO? - S01E53 - The Case of the Creep in the Concorde",
    "WitWiCS S01 E53 The Case of the Creep in the Concorde.mp4"],
  ['where-in-the-world-is-carmen-sandiego-tv-show-series', "WHERE IN THE WORLD IS CARMEN SANDIEGO? - S01E54 - The Disappearing Declaration",
    "WitWiCS S01 E54 The Disappearing Declaration.mp4"],
  ['where-in-the-world-is-carmen-sandiego-tv-show-series', "WHERE IN THE WORLD IS CARMEN SANDIEGO? - S01E55 - The Return of Dracula's Castle",
    "WitWiCS S01 E55 The Return of Dracula's Castle.mp4"],
  ['where-in-the-world-is-carmen-sandiego-tv-show-series', "WHERE IN THE WORLD IS CARMEN SANDIEGO? - S01E56 - Who Stole the Bowl?",
    "WitWiCS S01 E56 Who Stole the Bowl_.mp4"],
  ['where-in-the-world-is-carmen-sandiego-tv-show-series', "WHERE IN THE WORLD IS CARMEN SANDIEGO? - S01E57 - The Case of the Pinched Paws",
    "WitWiCS S01 E57 The Case of the Pinched Paws.mp4"],
  ['where-in-the-world-is-carmen-sandiego-tv-show-series', "WHERE IN THE WORLD IS CARMEN SANDIEGO? - S01E58 - The Purloined Pooch",
    "WitWiCS S01 E58 The Purloined Pooch.mp4"],
  ['where-in-the-world-is-carmen-sandiego-tv-show-series', "WHERE IN THE WORLD IS CARMEN SANDIEGO? - S01E59 - End of the Trail",
    "WitWiCS S01 E59 End of the Trail.mp4"],
  ['where-in-the-world-is-carmen-sandiego-tv-show-series', "WHERE IN THE WORLD IS CARMEN SANDIEGO? - S01E60 - The White Gator Caper",
    "WitWiCS S01 E60 The White Gator Caper.mp4"],
  ['where-in-the-world-is-carmen-sandiego-tv-show-series', "WHERE IN THE WORLD IS CARMEN SANDIEGO? - S01E61 - The Spot Lifter",
    "WitWiCS S01 E61 The Spot Lifter.mp4"],
  ['where-in-the-world-is-carmen-sandiego-tv-show-series', "WHERE IN THE WORLD IS CARMEN SANDIEGO? - S01E62 - The Disoriented Express",
    "WitWiCS S01 E62 The Disoriented Express.mp4"],
  ['where-in-the-world-is-carmen-sandiego-tv-show-series', "WHERE IN THE WORLD IS CARMEN SANDIEGO? - S01E63 - Island Copping",
    "WitWiCS S01 E63 Island Copping.mp4"],
  ['where-in-the-world-is-carmen-sandiego-tv-show-series', "WHERE IN THE WORLD IS CARMEN SANDIEGO? - S01E64 - The Case of the Glommed Geyser",
    "WitWiCS S01 E64 The Case of the Glommed Geyser.mp4"],
  ['where-in-the-world-is-carmen-sandiego-tv-show-series', "WHERE IN THE WORLD IS CARMEN SANDIEGO? - S01E65 - The Costume Caper",
    "WitWiCS S01 E65 The Costume Caper.mp4"],
  ['where-in-the-world-is-carmen-sandiego-tv-show-series', "WHERE IN THE WORLD IS CARMEN SANDIEGO? - S02E01 - Disturbing the Heavenly Peace",
    "WitWiCS S02 E01 Disturbing the Heavenly Peace.mp4"],
  ['where-in-the-world-is-carmen-sandiego-tv-show-series', "WHERE IN THE WORLD IS CARMEN SANDIEGO? - S02E02 - The Immigration Station Perpetration",
    "WitWiCS S02 E02 The Immigration Station Perpetration.mp4"],
  ['where-in-the-world-is-carmen-sandiego-tv-show-series', "WHERE IN THE WORLD IS CARMEN SANDIEGO? - S02E03 - The Blarney Burglary",
    "WitWiCS S02 E03 The Blarney Burglary.mp4"],
  ['where-in-the-world-is-carmen-sandiego-tv-show-series', "WHERE IN THE WORLD IS CARMEN SANDIEGO? - S02E04 - What's What With Watts?",
    "WitWiCS S02 E04 What's What With Watts_.mp4"],
  ['where-in-the-world-is-carmen-sandiego-tv-show-series', "WHERE IN THE WORLD IS CARMEN SANDIEGO? - S02E05 - A Carmen for Carmen",
    "WitWiCS S02 E05 A Carmen for Carmen.mp4"],
  ['where-in-the-world-is-carmen-sandiego-tv-show-series', "WHERE IN THE WORLD IS CARMEN SANDIEGO? - S02E06 - No Brainer",
    "WitWiCS S02 E06 No Brainer.mp4"],
  ['where-in-the-world-is-carmen-sandiego-tv-show-series', "WHERE IN THE WORLD IS CARMEN SANDIEGO? - S02E07 - The Autobahn Con",
    "WitWiCS S02 E07 The Autobahn Con.mp4"],
  ['where-in-the-world-is-carmen-sandiego-tv-show-series', "WHERE IN THE WORLD IS CARMEN SANDIEGO? - S02E08 - The Cave Art Caper",
    "WitWiCS S02 E08 The Cave Art Caper.mp4"],
  ['where-in-the-world-is-carmen-sandiego-tv-show-series', "WHERE IN THE WORLD IS CARMEN SANDIEGO? - S02E09 - Trouble on Tanganyika",
    "WitWiCS S02 E09 Trouble on Tanganyika.mp4"],
  ['where-in-the-world-is-carmen-sandiego-tv-show-series', "WHERE IN THE WORLD IS CARMEN SANDIEGO? - S02E10 - Bad Day on Broadway",
    "WitWiCS S02 E10 Bad Day on Broadway.mp4"],
  ['where-in-the-world-is-carmen-sandiego-tv-show-series', "WHERE IN THE WORLD IS CARMEN SANDIEGO? - S02E11 - The Boll Weevil Retrieval",
    "WitWiCS S02 E11 The Boll Weevil Retrieval.mp4"],
  ['where-in-the-world-is-carmen-sandiego-tv-show-series', "WHERE IN THE WORLD IS CARMEN SANDIEGO? - S02E12 - Greasy Getaway",
    "WitWiCS S02 E12 Greasy Getaway.mp4"],
  ['where-in-the-world-is-carmen-sandiego-tv-show-series', "WHERE IN THE WORLD IS CARMEN SANDIEGO? - S02E13 - Tango Mysterioso",
    "WitWiCS S02 E13 Tango Mysterioso.mp4"],
  ['where-in-the-world-is-carmen-sandiego-tv-show-series', "WHERE IN THE WORLD IS CARMEN SANDIEGO? - S02E14 - The Statue Steal",
    "WitWiCS S02 E14 The Statue Steal.mp4"],
  ['where-in-the-world-is-carmen-sandiego-tv-show-series', "WHERE IN THE WORLD IS CARMEN SANDIEGO? - S02E15 - The Amazing Boomerang Effect",
    "WitWiCS S02 E15 The Amazing Boomerang Effect.mp4"],
  ['where-in-the-world-is-carmen-sandiego-tv-show-series', "WHERE IN THE WORLD IS CARMEN SANDIEGO? - S02E16 - School's Out",
    "WitWiCS S02 E16 School's Out.mp4"],
  ['where-in-the-world-is-carmen-sandiego-tv-show-series', "WHERE IN THE WORLD IS CARMEN SANDIEGO? - S02E17 - Rockin' Rio Ripoff",
    "WitWiCS S02 E17 Rockin' Rio Ripoff.mp4"],
  ['where-in-the-world-is-carmen-sandiego-tv-show-series', "WHERE IN THE WORLD IS CARMEN SANDIEGO? - S02E18 - Where'd the Alamo Go?",
    "WitWiCS S02 E18 Where'd the Alamo Go_.mp4"],
  ['where-in-the-world-is-carmen-sandiego-tv-show-series', "WHERE IN THE WORLD IS CARMEN SANDIEGO? - S02E19 - The Case of the Little Boy Lost",
    "WitWiCS S02 E19 The Case of the Little Boy Lost.mp4"],
  ['where-in-the-world-is-carmen-sandiego-tv-show-series', "WHERE IN THE WORLD IS CARMEN SANDIEGO? - S02E20 - Superscam",
    "WitWiCS S02 E20 Superscam.mp4"],
  ['where-in-the-world-is-carmen-sandiego-tv-show-series', "WHERE IN THE WORLD IS CARMEN SANDIEGO? - S02E21 - Chumps D'Elysees",
    "WitWiCS S02 E21 Chumps D'Elysees.mp4"],
  ['where-in-the-world-is-carmen-sandiego-tv-show-series', "WHERE IN THE WORLD IS CARMEN SANDIEGO? - S02E22 - Baaaaad News in New Zealand",
    "WitWiCS S02 E22 Baaaaad News in New Zealand.mp4"],
  ['where-in-the-world-is-carmen-sandiego-tv-show-series', "WHERE IN THE WORLD IS CARMEN SANDIEGO? - S02E23 - Boosting the Belt",
    "WitWiCS S02 E23 Boosting the Belt.mp4"],
  ['where-in-the-world-is-carmen-sandiego-tv-show-series', "WHERE IN THE WORLD IS CARMEN SANDIEGO? - S02E24 - The Ta-ta Kenyatta Cantata",
    "WitWiCS S02 E24 The Ta-ta Kenyatta Cantata.mp4"],
  ['where-in-the-world-is-carmen-sandiego-tv-show-series', "WHERE IN THE WORLD IS CARMEN SANDIEGO? - S02E25 - WSK Gone",
    "WitWiCS S02 E25 WSK Gone.mp4"],
  ['where-in-the-world-is-carmen-sandiego-tv-show-series', "WHERE IN THE WORLD IS CARMEN SANDIEGO? - S02E26 - The Brazen Bean Bamboozlement",
    "WitWiCS S02 E26 The Brazen Bean Bamboozlement.mp4"],
  ['where-in-the-world-is-carmen-sandiego-tv-show-series', "WHERE IN THE WORLD IS CARMEN SANDIEGO? - S02E27 - Wondering Where the Water Went",
    "WitWiCS S02 E27 Wondering Where the Water Went.mp4"],
  ['where-in-the-world-is-carmen-sandiego-tv-show-series', "WHERE IN THE WORLD IS CARMEN SANDIEGO? - S02E28 - Gorgeous George",
    "WitWiCS S02 E28 Gorgeous George.mp4"],
  ['where-in-the-world-is-carmen-sandiego-tv-show-series', "WHERE IN THE WORLD IS CARMEN SANDIEGO? - S02E29 - Big Bad Lug Bags Big Egg",
    "WitWiCS S02 E29 Big Bad Lug Bags Big Egg.mp4"],
  ['where-in-the-world-is-carmen-sandiego-tv-show-series', "WHERE IN THE WORLD IS CARMEN SANDIEGO? - S02E30 - Crook Nicks Kid Pix",
    "WitWiCS S02 E30 Crook Nicks Kid Pix.mp4"],
  ['where-in-the-world-is-carmen-sandiego-tv-show-series', "WHERE IN THE WORLD IS CARMEN SANDIEGO? - S02E31 - Big Bank Bingo",
    "WitWiCS S02 E31 Big Bank Bingo.mp4"],
  ['where-in-the-world-is-carmen-sandiego-tv-show-series', "WHERE IN THE WORLD IS CARMEN SANDIEGO? - S02E32 - The Lip Stick Up",
    "WitWiCS S02 E32 The Lip Stick Up.mp4"],
  ['where-in-the-world-is-carmen-sandiego-tv-show-series', "WHERE IN THE WORLD IS CARMEN SANDIEGO? - S02E33 - Who Copped Khufu?",
    "WitWiCS S02 E33 Who Copped Khufu_.mp4"],
  ['where-in-the-world-is-carmen-sandiego-tv-show-series', "WHERE IN THE WORLD IS CARMEN SANDIEGO? - S02E34 - Who Bagged the Bull?",
    "WitWiCS S02 E34 Who Bagged the Bull_.mp4"],
  ['where-in-the-world-is-carmen-sandiego-tv-show-series', "WHERE IN THE WORLD IS CARMEN SANDIEGO? - S02E35 - My Cup Runneth Away",
    "WitWiCS S02 E35 My Cup Runneth Away.mp4"],
  ['where-in-the-world-is-carmen-sandiego-tv-show-series', "WHERE IN THE WORLD IS CARMEN SANDIEGO? - S02E36 - Tsealing the Tsar Bell",
    "WitWiCS S02 E36 Tsealing the Tsar Bell.mp4"],
  ['where-in-the-world-is-carmen-sandiego-tv-show-series', "WHERE IN THE WORLD IS CARMEN SANDIEGO? - S02E37 - Beach Blanket Bye-Bye",
    "WitWiCS S02 E37 Beach Blanket Bye-Bye.mp4"],
  ['where-in-the-world-is-carmen-sandiego-tv-show-series', "WHERE IN THE WORLD IS CARMEN SANDIEGO? - S02E38 - Where's Dave?",
    "WitWiCS S02 E38 Where's Dave_.mp4"],
  ['where-in-the-world-is-carmen-sandiego-tv-show-series', "WHERE IN THE WORLD IS CARMEN SANDIEGO? - S02E39 - The Perilous Penguin Pilferage",
    "WitWiCS S02 E39 The Perilous Penguin Pilferage.mp4"],
  ['where-in-the-world-is-carmen-sandiego-tv-show-series', "WHERE IN THE WORLD IS CARMEN SANDIEGO? - S02E40 - Churchill Downer",
    "WitWiCS S02 E40 Churchill Downer.mp4"],
  ['where-in-the-world-is-carmen-sandiego-tv-show-series', "WHERE IN THE WORLD IS CARMEN SANDIEGO? - S02E41 - The Dog Race Rat Case",
    "WitWiCS S02 E41 The Dog Race Rat Case.mp4"],
  ['where-in-the-world-is-carmen-sandiego-tv-show-series', "WHERE IN THE WORLD IS CARMEN SANDIEGO? - S02E42 - Topkapi Turban Topper",
    "WitWiCS S02 E42 Topkapi Turban Topper.mp4"],
  ['where-in-the-world-is-carmen-sandiego-tv-show-series', "WHERE IN THE WORLD IS CARMEN SANDIEGO? - S02E43 - The Oranges of Wrath",
    "WitWiCS S02 E43 The Oranges of Wrath.mp4"],
  ['where-in-the-world-is-carmen-sandiego-tv-show-series', "WHERE IN THE WORLD IS CARMEN SANDIEGO? - S02E44 - Boosting the Bounty",
    "WitWiCS S02 E44 Boosting the Bounty.mp4"],
  ['where-in-the-world-is-carmen-sandiego-tv-show-series', "WHERE IN THE WORLD IS CARMEN SANDIEGO? - S02E45 - The Nefarious Nobel Napper",
    "WitWiCS S02 E45 The Nefarious Nobel Napper.mp4"],
  ['where-in-the-world-is-carmen-sandiego-tv-show-series', "WHERE IN THE WORLD IS CARMEN SANDIEGO? - S02E46 - The Machu Picchu Pinch",
    "WitWiCS S02 E46 The Machu Picchu Pinch.mp4"],
  ['where-in-the-world-is-carmen-sandiego-tv-show-series', "WHERE IN THE WORLD IS CARMEN SANDIEGO? - S02E47 - Twinkle Twinkle Little Rat",
    "WitWiCS S02 E47 Twinkle Twinkle Little Rat.mp4"],
  ['where-in-the-world-is-carmen-sandiego-tv-show-series', "WHERE IN THE WORLD IS CARMEN SANDIEGO? - S02E48 - Fortress Felony",
    "WitWiCS S02 E48 Fortress Felony.mp4"],
  ['where-in-the-world-is-carmen-sandiego-tv-show-series', "WHERE IN THE WORLD IS CARMEN SANDIEGO? - S02E49 - In the Rat Bird Seat",
    "WitWiCS S02 E49 In the Rat Bird Seat.mp4"],
  ['where-in-the-world-is-carmen-sandiego-tv-show-series', "WHERE IN THE WORLD IS CARMEN SANDIEGO? - S02E50 - Mountainous Mayhem",
    "WitWiCS S02 E50 Mountainous Mayhem.mp4"],
  ['where-in-the-world-is-carmen-sandiego-tv-show-series', "WHERE IN THE WORLD IS CARMEN SANDIEGO? - S02E51 - The Merlion Mystery",
    "WitWiCS S02 E51 The Merlion Mystery.mp4"],
  ['where-in-the-world-is-carmen-sandiego-tv-show-series', "WHERE IN THE WORLD IS CARMEN SANDIEGO? - S02E52 - The Artificial Army Abduction",
    "WitWiCS S02 E52 The Artificial Army Abduction.mp4"],
  ['where-in-the-world-is-carmen-sandiego-tv-show-series', "WHERE IN THE WORLD IS CARMEN SANDIEGO? - S02E53 - VIII is Enough",
    "WitWiCS S02 E53 VIII is Enough.mp4"],
  ['where-in-the-world-is-carmen-sandiego-tv-show-series', "WHERE IN THE WORLD IS CARMEN SANDIEGO? - S02E54 - The Heinous Hockey Heist",
    "WitWiCS S02 E54 The Heinous Hockey Heist.mp4"],
  ['where-in-the-world-is-carmen-sandiego-tv-show-series', "WHERE IN THE WORLD IS CARMEN SANDIEGO? - S02E55 - Tomfoolery in Thailand",
    "WitWiCS S02 E55 Tomfoolery in Thailand.mp4"],
  ['where-in-the-world-is-carmen-sandiego-tv-show-series', "WHERE IN THE WORLD IS CARMEN SANDIEGO? - S02E56 - She Took the Notes Right Out of My Mouth",
    "WitWiCS S02 E56 She Took the Notes Right Out of My Mouth.mp4"],
  ['where-in-the-world-is-carmen-sandiego-tv-show-series', "WHERE IN THE WORLD IS CARMEN SANDIEGO? - S02E57 - The Great Train Slobbery",
    "WitWiCS S02 E57 The Great Train Slobbery.mp4"],
  ['where-in-the-world-is-carmen-sandiego-tv-show-series', "WHERE IN THE WORLD IS CARMEN SANDIEGO? - S02E58 - The Case of the Filched Freedom Fighter",
    "WitWiCS S02 E58 The Case of the Filched Freedom Fighter.mp4"],
  ['where-in-the-world-is-carmen-sandiego-tv-show-series', "WHERE IN THE WORLD IS CARMEN SANDIEGO? - S02E59 - I Lost Lucy",
    "WitWiCS S02 E59 I Lost Lucy.mp4"],
  ['where-in-the-world-is-carmen-sandiego-tv-show-series', "WHERE IN THE WORLD IS CARMEN SANDIEGO? - S02E60 - Stoneheist",
    "WitWiCS S02 E60 Stoneheist.mp4"],
  ['where-in-the-world-is-carmen-sandiego-tv-show-series', "WHERE IN THE WORLD IS CARMEN SANDIEGO? - S02E61 - Cur Cribs Curves",
    "WitWiCS S02 E61 Cur Cribs Curves.mp4"],
  ['where-in-the-world-is-carmen-sandiego-tv-show-series', "WHERE IN THE WORLD IS CARMEN SANDIEGO? - S02E62 - The Perfidious Party Poach",
    "WitWiCS S02 E62 The Perfidious Party Poach.mp4"],
  ['where-in-the-world-is-carmen-sandiego-tv-show-series', "WHERE IN THE WORLD IS CARMEN SANDIEGO? - S02E63 - Swiping the Supremes",
    "WitWiCS S02 E63 Swiping the Supremes.mp4"],
  ['where-in-the-world-is-carmen-sandiego-tv-show-series', "WHERE IN THE WORLD IS CARMEN SANDIEGO? - S02E64 - The Waltz Whammy",
    "WitWiCS S02 E64 The Waltz Whammy.mp4"],
  ['where-in-the-world-is-carmen-sandiego-tv-show-series', "WHERE IN THE WORLD IS CARMEN SANDIEGO? - S02E65 - Gotta Get a Yeti",
    "WitWiCS S02 E65 Gotta Get a Yeti.mp4"],
  ['where-in-the-world-is-carmen-sandiego-tv-show-series', "WHERE IN THE WORLD IS CARMEN SANDIEGO? - S03E01 - Bathing Booty",
    "WitWiCS S03 E01 Bathing Booty.mp4"],
  ['where-in-the-world-is-carmen-sandiego-tv-show-series', "WHERE IN THE WORLD IS CARMEN SANDIEGO? - S03E02 - Robot Robotnapper",
    "WitWiCS S03 E02 Robot Robotnapper.mp4"],
  ['where-in-the-world-is-carmen-sandiego-tv-show-series', "WHERE IN THE WORLD IS CARMEN SANDIEGO? - S03E03 - Little Dog Gone",
    "WitWiCS S03 E03 Little Dog Gone.mp4"],
  ['where-in-the-world-is-carmen-sandiego-tv-show-series', "WHERE IN THE WORLD IS CARMEN SANDIEGO? - S03E04 - Tricky Trickle Trapper",
    "WitWiCS S03 E04 Tricky Trickle Trapper.mp4"],
  ['where-in-the-world-is-carmen-sandiego-tv-show-series', "WHERE IN THE WORLD IS CARMEN SANDIEGO? - S03E05 - Might Takes Wright",
    "WitWiCS S03 E05 Might Takes Wright.mp4"],
  ['where-in-the-world-is-carmen-sandiego-tv-show-series', "WHERE IN THE WORLD IS CARMEN SANDIEGO? - S03E06 - Feckless Felons of Fenway",
    "WitWiCS S03 E06 Feckless Felons of Fenway.mp4"],
  ['where-in-the-world-is-carmen-sandiego-tv-show-series', "WHERE IN THE WORLD IS CARMEN SANDIEGO? - S03E07 - Where the Wandering Wildebeests Went",
    "WitWiCS S03 E07 Where the Wandering Wildebeests Went.mp4"],
  ['where-in-the-world-is-carmen-sandiego-tv-show-series', "WHERE IN THE WORLD IS CARMEN SANDIEGO? - S03E08 - Withdrawal Symptoms",
    "WitWiCS S03 E08 Withdrawal Symptoms.mp4"],
  ['where-in-the-world-is-carmen-sandiego-tv-show-series', "WHERE IN THE WORLD IS CARMEN SANDIEGO? - S03E09 - Officers' Mess",
    "WitWiCS S03 E09 Officers' Mess.mp4"],
  ['where-in-the-world-is-carmen-sandiego-tv-show-series', "WHERE IN THE WORLD IS CARMEN SANDIEGO? - S03E10 - Roaring Rodent Road Show",
    "WitWiCS S03 E10 Roaring Rodent Road Show.mp4"],
  ['where-in-the-world-is-carmen-sandiego-tv-show-series', "WHERE IN THE WORLD IS CARMEN SANDIEGO? - S03E11 - The Pied Pirates of Petra",
    "WitWiCS S03 E11 The Pied Pirates of Petra.mp4"],
  ['where-in-the-world-is-carmen-sandiego-tv-show-series', "WHERE IN THE WORLD IS CARMEN SANDIEGO? - S03E12 - The Gambian Gambit",
    "WitWiCS S03 E12 The Gambian Gambit.mp4"],
  ['where-in-the-world-is-carmen-sandiego-tv-show-series', "WHERE IN THE WORLD IS CARMEN SANDIEGO? - S03E13 - The Persian Subversion",
    "WitWiCS S03 E13 The Persian Subversion.mp4"],
  ['where-in-the-world-is-carmen-sandiego-tv-show-series', "WHERE IN THE WORLD IS CARMEN SANDIEGO? - S03E14 - The Outback Soundtrack Hijack",
    "WitWiCS S03 E14 The Outback Soundtrack Hijack.mp4"],
  ['where-in-the-world-is-carmen-sandiego-tv-show-series', "WHERE IN THE WORLD IS CARMEN SANDIEGO? - S03E15 - Come Back With That Kibbutz, Toots",
    "WitWiCS S03 E15 Come Back With That Kibbutz, Toots.mp4"],
  ['where-in-the-world-is-carmen-sandiego-tv-show-series', "WHERE IN THE WORLD IS CARMEN SANDIEGO? - S03E16 - The Kazanluk Cologne Caper",
    "WitWiCS S03 E16 The Kazanluk Cologne Caper.mp4"],
  ['where-in-the-world-is-carmen-sandiego-tv-show-series', "WHERE IN THE WORLD IS CARMEN SANDIEGO? - S03E17 - The Glacier Erasure",
    "WitWiCS S03 E17 The Glacier Erasure.mp4"],
  ['where-in-the-world-is-carmen-sandiego-tv-show-series', "WHERE IN THE WORLD IS CARMEN SANDIEGO? - S03E18 - Rio Rock Wranglers",
    "WitWiCS S03 E18 Rio Rock Wranglers.mp4"],
  ['where-in-the-world-is-carmen-sandiego-tv-show-series', "WHERE IN THE WORLD IS CARMEN SANDIEGO? - S03E19 - The Grand Trunk Punk",
    "WitWiCS S03 E19 The Grand Trunk Punk.mp4"],
  ['where-in-the-world-is-carmen-sandiego-tv-show-series', "WHERE IN THE WORLD IS CARMEN SANDIEGO? - S03E20 - The Bee-Bird Burglary",
    "WitWiCS S03 E20 The Bee-Bird Burglary.mp4"],
],
  durations: {
  "where-in-the-world-is-carmen-sandiego-tv-show-series::WitWiCS S01 E01 The Taking of the Shrew.mp4": 1656,
  "where-in-the-world-is-carmen-sandiego-tv-show-series::WitWiCS S01 E02 The Case of the Cribbed Crater.mp4": 1623,
  "where-in-the-world-is-carmen-sandiego-tv-show-series::WitWiCS S01 E03 It's the Pits.mp4": 1643,
  "where-in-the-world-is-carmen-sandiego-tv-show-series::WitWiCS S01 E04 The Big Ness Mess.mp4": 1633,
  "where-in-the-world-is-carmen-sandiego-tv-show-series::WitWiCS S01 E05 Seizing the Sea.mp4": 1554,
  "where-in-the-world-is-carmen-sandiego-tv-show-series::WitWiCS S01 E06 The Gateway Getaway.mp4": 1382,
  "where-in-the-world-is-carmen-sandiego-tv-show-series::WitWiCS S01 E07 Ripping Off the Rock.mp4": 1707,
  "where-in-the-world-is-carmen-sandiego-tv-show-series::WitWiCS S01 E08 The Case of the False False Teeth.mp4": 1604,
  "where-in-the-world-is-carmen-sandiego-tv-show-series::WitWiCS S01 E09 The Lincoln Conspiracy.mp4": 1618,
  "where-in-the-world-is-carmen-sandiego-tv-show-series::WitWiCS S01 E10 The Canal Caper.mp4": 1660,
  "where-in-the-world-is-carmen-sandiego-tv-show-series::WitWiCS S01 E11 The Great Wall Haul.mp4": 1538,
  "where-in-the-world-is-carmen-sandiego-tv-show-series::WitWiCS S01 E12 The Case of the Burgled Bugatti.mp4": 1654,
  "where-in-the-world-is-carmen-sandiego-tv-show-series::WitWiCS S01 E13 The Square Scam.mp4": 1658,
  "where-in-the-world-is-carmen-sandiego-tv-show-series::WitWiCS S01 E14 The Case of the Purloined Pen.mp4": 1676,
  "where-in-the-world-is-carmen-sandiego-tv-show-series::WitWiCS S01 E15 The Great Liberty Lift.mp4": 1561,
  "where-in-the-world-is-carmen-sandiego-tv-show-series::WitWiCS S01 E16 The S.A.T. Score Scam.mp4": 1667,
  "where-in-the-world-is-carmen-sandiego-tv-show-series::WitWiCS S01 E17 Torch Song.mp4": 1731,
  "where-in-the-world-is-carmen-sandiego-tv-show-series::WitWiCS S01 E18 The Hammering Hank Heist.mp4": 1661,
  "where-in-the-world-is-carmen-sandiego-tv-show-series::WitWiCS S01 E19 Big Ben Bagged.mp4": 1627,
  "where-in-the-world-is-carmen-sandiego-tv-show-series::WitWiCS S01 E20 Diamonds Are a Crook's Best Friend.mp4": 1682,
  "where-in-the-world-is-carmen-sandiego-tv-show-series::WitWiCS S01 E21 The Bridge Bust.mp4": 1503,
  "where-in-the-world-is-carmen-sandiego-tv-show-series::WitWiCS S01 E22 The Fall Collection Caper.mp4": 1670,
  "where-in-the-world-is-carmen-sandiego-tv-show-series::WitWiCS S01 E23 Minnehaha - The Filching of the Falls.mp4": 1630,
  "where-in-the-world-is-carmen-sandiego-tv-show-series::WitWiCS S01 E24 The Radioscope Rip-off.mp4": 1697,
  "where-in-the-world-is-carmen-sandiego-tv-show-series::WitWiCS S01 E25 Who Pinched Pisa_.mp4": 1614,
  "where-in-the-world-is-carmen-sandiego-tv-show-series::WitWiCS S01 E26 The Checkmate Checkout.mp4": 1570,
  "where-in-the-world-is-carmen-sandiego-tv-show-series::WitWiCS S01 E27 The Forbidden City Snatch.mp4": 1650,
  "where-in-the-world-is-carmen-sandiego-tv-show-series::WitWiCS S01 E28 The Case of the Missing Queen.mp4": 1622,
  "where-in-the-world-is-carmen-sandiego-tv-show-series::WitWiCS S01 E29 The Raceway Rip-Off.mp4": 1552,
  "where-in-the-world-is-carmen-sandiego-tv-show-series::WitWiCS S01 E30 Brandenburglary.mp4": 1590,
  "where-in-the-world-is-carmen-sandiego-tv-show-series::WitWiCS S01 E31 The Case of the Reef Thief.mp4": 1651,
  "where-in-the-world-is-carmen-sandiego-tv-show-series::WitWiCS S01 E32 The Library Lift.mp4": 1598,
  "where-in-the-world-is-carmen-sandiego-tv-show-series::WitWiCS S01 E33 The Great Head Heist.mp4": 1656,
  "where-in-the-world-is-carmen-sandiego-tv-show-series::WitWiCS S01 E34 The Nose Knows.mp4": 1549,
  "where-in-the-world-is-carmen-sandiego-tv-show-series::WitWiCS S01 E35 The Troubled Triangle.mp4": 1525,
  "where-in-the-world-is-carmen-sandiego-tv-show-series::WitWiCS S01 E36 The Chunnel Channel Caper.mp4": 1532,
  "where-in-the-world-is-carmen-sandiego-tv-show-series::WitWiCS S01 E37 The Taking of the Tower.mp4": 1551,
  "where-in-the-world-is-carmen-sandiego-tv-show-series::WitWiCS S01 E38 The Case of the Purloined Pipeline.mp4": 1633,
  "where-in-the-world-is-carmen-sandiego-tv-show-series::WitWiCS S01 E39 Monumental Malfeasance.mp4": 1615,
  "where-in-the-world-is-carmen-sandiego-tv-show-series::WitWiCS S01 E40 The Case of the Lifted Lines.mp4": 1630,
  "where-in-the-world-is-carmen-sandiego-tv-show-series::WitWiCS S01 E41 Stompin' at the Stock Exchange.mp4": 1652,
  "where-in-the-world-is-carmen-sandiego-tv-show-series::WitWiCS S01 E42 The Rosetta Rip-off.mp4": 1551,
  "where-in-the-world-is-carmen-sandiego-tv-show-series::WitWiCS S01 E43 The Time Bandit.mp4": 1618,
  "where-in-the-world-is-carmen-sandiego-tv-show-series::WitWiCS S01 E44 Who Stole the Hole_.mp4": 1645,
  "where-in-the-world-is-carmen-sandiego-tv-show-series::WitWiCS S01 E45 The Fat Lady Sings No More.mp4": 1662,
  "where-in-the-world-is-carmen-sandiego-tv-show-series::WitWiCS S01 E46 What Goes Up.mp4": 1572,
  "where-in-the-world-is-carmen-sandiego-tv-show-series::WitWiCS S01 E47 The Taking of the Towers.mp4": 1517,
  "where-in-the-world-is-carmen-sandiego-tv-show-series::WitWiCS S01 E48 The Case of the Roamin' Roman Ruin.mp4": 1524,
  "where-in-the-world-is-carmen-sandiego-tv-show-series::WitWiCS S01 E49 Hot Potato.mp4": 1453,
  "where-in-the-world-is-carmen-sandiego-tv-show-series::WitWiCS S01 E50 The Case of the Pilfered Palace.mp4": 1276,
  "where-in-the-world-is-carmen-sandiego-tv-show-series::WitWiCS S01 E51 The Case of the Purloined Pole.mp4": 1570,
  "where-in-the-world-is-carmen-sandiego-tv-show-series::WitWiCS S01 E52 The Case of the Missing Mountain.mp4": 1426,
  "where-in-the-world-is-carmen-sandiego-tv-show-series::WitWiCS S01 E53 The Case of the Creep in the Concorde.mp4": 1494,
  "where-in-the-world-is-carmen-sandiego-tv-show-series::WitWiCS S01 E54 The Disappearing Declaration.mp4": 1572,
  "where-in-the-world-is-carmen-sandiego-tv-show-series::WitWiCS S01 E55 The Return of Dracula's Castle.mp4": 1697,
  "where-in-the-world-is-carmen-sandiego-tv-show-series::WitWiCS S01 E56 Who Stole the Bowl_.mp4": 1534,
  "where-in-the-world-is-carmen-sandiego-tv-show-series::WitWiCS S01 E57 The Case of the Pinched Paws.mp4": 1673,
  "where-in-the-world-is-carmen-sandiego-tv-show-series::WitWiCS S01 E58 The Purloined Pooch.mp4": 1585,
  "where-in-the-world-is-carmen-sandiego-tv-show-series::WitWiCS S01 E59 End of the Trail.mp4": 1538,
  "where-in-the-world-is-carmen-sandiego-tv-show-series::WitWiCS S01 E60 The White Gator Caper.mp4": 1379,
  "where-in-the-world-is-carmen-sandiego-tv-show-series::WitWiCS S01 E61 The Spot Lifter.mp4": 1642,
  "where-in-the-world-is-carmen-sandiego-tv-show-series::WitWiCS S01 E62 The Disoriented Express.mp4": 1638,
  "where-in-the-world-is-carmen-sandiego-tv-show-series::WitWiCS S01 E63 Island Copping.mp4": 1655,
  "where-in-the-world-is-carmen-sandiego-tv-show-series::WitWiCS S01 E64 The Case of the Glommed Geyser.mp4": 1528,
  "where-in-the-world-is-carmen-sandiego-tv-show-series::WitWiCS S01 E65 The Costume Caper.mp4": 1671,
  "where-in-the-world-is-carmen-sandiego-tv-show-series::WitWiCS S02 E01 Disturbing the Heavenly Peace.mp4": 1646,
  "where-in-the-world-is-carmen-sandiego-tv-show-series::WitWiCS S02 E02 The Immigration Station Perpetration.mp4": 1704,
  "where-in-the-world-is-carmen-sandiego-tv-show-series::WitWiCS S02 E03 The Blarney Burglary.mp4": 1669,
  "where-in-the-world-is-carmen-sandiego-tv-show-series::WitWiCS S02 E04 What's What With Watts_.mp4": 1647,
  "where-in-the-world-is-carmen-sandiego-tv-show-series::WitWiCS S02 E05 A Carmen for Carmen.mp4": 1553,
  "where-in-the-world-is-carmen-sandiego-tv-show-series::WitWiCS S02 E06 No Brainer.mp4": 1707,
  "where-in-the-world-is-carmen-sandiego-tv-show-series::WitWiCS S02 E07 The Autobahn Con.mp4": 1607,
  "where-in-the-world-is-carmen-sandiego-tv-show-series::WitWiCS S02 E08 The Cave Art Caper.mp4": 1656,
  "where-in-the-world-is-carmen-sandiego-tv-show-series::WitWiCS S02 E09 Trouble on Tanganyika.mp4": 1682,
  "where-in-the-world-is-carmen-sandiego-tv-show-series::WitWiCS S02 E10 Bad Day on Broadway.mp4": 1668,
  "where-in-the-world-is-carmen-sandiego-tv-show-series::WitWiCS S02 E11 The Boll Weevil Retrieval.mp4": 1630,
  "where-in-the-world-is-carmen-sandiego-tv-show-series::WitWiCS S02 E12 Greasy Getaway.mp4": 1674,
  "where-in-the-world-is-carmen-sandiego-tv-show-series::WitWiCS S02 E13 Tango Mysterioso.mp4": 1668,
  "where-in-the-world-is-carmen-sandiego-tv-show-series::WitWiCS S02 E14 The Statue Steal.mp4": 1698,
  "where-in-the-world-is-carmen-sandiego-tv-show-series::WitWiCS S02 E15 The Amazing Boomerang Effect.mp4": 1517,
  "where-in-the-world-is-carmen-sandiego-tv-show-series::WitWiCS S02 E16 School's Out.mp4": 1652,
  "where-in-the-world-is-carmen-sandiego-tv-show-series::WitWiCS S02 E17 Rockin' Rio Ripoff.mp4": 1625,
  "where-in-the-world-is-carmen-sandiego-tv-show-series::WitWiCS S02 E18 Where'd the Alamo Go_.mp4": 1635,
  "where-in-the-world-is-carmen-sandiego-tv-show-series::WitWiCS S02 E19 The Case of the Little Boy Lost.mp4": 1705,
  "where-in-the-world-is-carmen-sandiego-tv-show-series::WitWiCS S02 E20 Superscam.mp4": 1684,
  "where-in-the-world-is-carmen-sandiego-tv-show-series::WitWiCS S02 E21 Chumps D'Elysees.mp4": 1681,
  "where-in-the-world-is-carmen-sandiego-tv-show-series::WitWiCS S02 E22 Baaaaad News in New Zealand.mp4": 1627,
  "where-in-the-world-is-carmen-sandiego-tv-show-series::WitWiCS S02 E23 Boosting the Belt.mp4": 1673,
  "where-in-the-world-is-carmen-sandiego-tv-show-series::WitWiCS S02 E24 The Ta-ta Kenyatta Cantata.mp4": 1651,
  "where-in-the-world-is-carmen-sandiego-tv-show-series::WitWiCS S02 E25 WSK Gone.mp4": 1614,
  "where-in-the-world-is-carmen-sandiego-tv-show-series::WitWiCS S02 E26 The Brazen Bean Bamboozlement.mp4": 1619,
  "where-in-the-world-is-carmen-sandiego-tv-show-series::WitWiCS S02 E27 Wondering Where the Water Went.mp4": 1666,
  "where-in-the-world-is-carmen-sandiego-tv-show-series::WitWiCS S02 E28 Gorgeous George.mp4": 1692,
  "where-in-the-world-is-carmen-sandiego-tv-show-series::WitWiCS S02 E29 Big Bad Lug Bags Big Egg.mp4": 1704,
  "where-in-the-world-is-carmen-sandiego-tv-show-series::WitWiCS S02 E30 Crook Nicks Kid Pix.mp4": 1613,
  "where-in-the-world-is-carmen-sandiego-tv-show-series::WitWiCS S02 E31 Big Bank Bingo.mp4": 1601,
  "where-in-the-world-is-carmen-sandiego-tv-show-series::WitWiCS S02 E32 The Lip Stick Up.mp4": 1613,
  "where-in-the-world-is-carmen-sandiego-tv-show-series::WitWiCS S02 E33 Who Copped Khufu_.mp4": 1597,
  "where-in-the-world-is-carmen-sandiego-tv-show-series::WitWiCS S02 E34 Who Bagged the Bull_.mp4": 1651,
  "where-in-the-world-is-carmen-sandiego-tv-show-series::WitWiCS S02 E35 My Cup Runneth Away.mp4": 1576,
  "where-in-the-world-is-carmen-sandiego-tv-show-series::WitWiCS S02 E36 Tsealing the Tsar Bell.mp4": 1611,
  "where-in-the-world-is-carmen-sandiego-tv-show-series::WitWiCS S02 E37 Beach Blanket Bye-Bye.mp4": 1697,
  "where-in-the-world-is-carmen-sandiego-tv-show-series::WitWiCS S02 E38 Where's Dave_.mp4": 1412,
  "where-in-the-world-is-carmen-sandiego-tv-show-series::WitWiCS S02 E39 The Perilous Penguin Pilferage.mp4": 1510,
  "where-in-the-world-is-carmen-sandiego-tv-show-series::WitWiCS S02 E40 Churchill Downer.mp4": 1664,
  "where-in-the-world-is-carmen-sandiego-tv-show-series::WitWiCS S02 E41 The Dog Race Rat Case.mp4": 1707,
  "where-in-the-world-is-carmen-sandiego-tv-show-series::WitWiCS S02 E42 Topkapi Turban Topper.mp4": 1651,
  "where-in-the-world-is-carmen-sandiego-tv-show-series::WitWiCS S02 E43 The Oranges of Wrath.mp4": 1499,
  "where-in-the-world-is-carmen-sandiego-tv-show-series::WitWiCS S02 E44 Boosting the Bounty.mp4": 1650,
  "where-in-the-world-is-carmen-sandiego-tv-show-series::WitWiCS S02 E45 The Nefarious Nobel Napper.mp4": 1630,
  "where-in-the-world-is-carmen-sandiego-tv-show-series::WitWiCS S02 E46 The Machu Picchu Pinch.mp4": 1467,
  "where-in-the-world-is-carmen-sandiego-tv-show-series::WitWiCS S02 E47 Twinkle Twinkle Little Rat.mp4": 1582,
  "where-in-the-world-is-carmen-sandiego-tv-show-series::WitWiCS S02 E48 Fortress Felony.mp4": 1541,
  "where-in-the-world-is-carmen-sandiego-tv-show-series::WitWiCS S02 E49 In the Rat Bird Seat.mp4": 1653,
  "where-in-the-world-is-carmen-sandiego-tv-show-series::WitWiCS S02 E50 Mountainous Mayhem.mp4": 1686,
  "where-in-the-world-is-carmen-sandiego-tv-show-series::WitWiCS S02 E51 The Merlion Mystery.mp4": 1410,
  "where-in-the-world-is-carmen-sandiego-tv-show-series::WitWiCS S02 E52 The Artificial Army Abduction.mp4": 1558,
  "where-in-the-world-is-carmen-sandiego-tv-show-series::WitWiCS S02 E53 VIII is Enough.mp4": 1313,
  "where-in-the-world-is-carmen-sandiego-tv-show-series::WitWiCS S02 E54 The Heinous Hockey Heist.mp4": 1329,
  "where-in-the-world-is-carmen-sandiego-tv-show-series::WitWiCS S02 E55 Tomfoolery in Thailand.mp4": 1529,
  "where-in-the-world-is-carmen-sandiego-tv-show-series::WitWiCS S02 E56 She Took the Notes Right Out of My Mouth.mp4": 1647,
  "where-in-the-world-is-carmen-sandiego-tv-show-series::WitWiCS S02 E57 The Great Train Slobbery.mp4": 1618,
  "where-in-the-world-is-carmen-sandiego-tv-show-series::WitWiCS S02 E58 The Case of the Filched Freedom Fighter.mp4": 1662,
  "where-in-the-world-is-carmen-sandiego-tv-show-series::WitWiCS S02 E59 I Lost Lucy.mp4": 1701,
  "where-in-the-world-is-carmen-sandiego-tv-show-series::WitWiCS S02 E60 Stoneheist.mp4": 1636,
  "where-in-the-world-is-carmen-sandiego-tv-show-series::WitWiCS S02 E61 Cur Cribs Curves.mp4": 1486,
  "where-in-the-world-is-carmen-sandiego-tv-show-series::WitWiCS S02 E62 The Perfidious Party Poach.mp4": 1597,
  "where-in-the-world-is-carmen-sandiego-tv-show-series::WitWiCS S02 E63 Swiping the Supremes.mp4": 1654,
  "where-in-the-world-is-carmen-sandiego-tv-show-series::WitWiCS S02 E64 The Waltz Whammy.mp4": 1645,
  "where-in-the-world-is-carmen-sandiego-tv-show-series::WitWiCS S02 E65 Gotta Get a Yeti.mp4": 1557,
  "where-in-the-world-is-carmen-sandiego-tv-show-series::WitWiCS S03 E01 Bathing Booty.mp4": 1652,
  "where-in-the-world-is-carmen-sandiego-tv-show-series::WitWiCS S03 E02 Robot Robotnapper.mp4": 1687,
  "where-in-the-world-is-carmen-sandiego-tv-show-series::WitWiCS S03 E03 Little Dog Gone.mp4": 1732,
  "where-in-the-world-is-carmen-sandiego-tv-show-series::WitWiCS S03 E04 Tricky Trickle Trapper.mp4": 1684,
  "where-in-the-world-is-carmen-sandiego-tv-show-series::WitWiCS S03 E05 Might Takes Wright.mp4": 1681,
  "where-in-the-world-is-carmen-sandiego-tv-show-series::WitWiCS S03 E06 Feckless Felons of Fenway.mp4": 1682,
  "where-in-the-world-is-carmen-sandiego-tv-show-series::WitWiCS S03 E07 Where the Wandering Wildebeests Went.mp4": 1629,
  "where-in-the-world-is-carmen-sandiego-tv-show-series::WitWiCS S03 E08 Withdrawal Symptoms.mp4": 1650,
  "where-in-the-world-is-carmen-sandiego-tv-show-series::WitWiCS S03 E09 Officers' Mess.mp4": 1609,
  "where-in-the-world-is-carmen-sandiego-tv-show-series::WitWiCS S03 E10 Roaring Rodent Road Show.mp4": 1608,
  "where-in-the-world-is-carmen-sandiego-tv-show-series::WitWiCS S03 E11 The Pied Pirates of Petra.mp4": 1615,
  "where-in-the-world-is-carmen-sandiego-tv-show-series::WitWiCS S03 E12 The Gambian Gambit.mp4": 1664,
  "where-in-the-world-is-carmen-sandiego-tv-show-series::WitWiCS S03 E13 The Persian Subversion.mp4": 1627,
  "where-in-the-world-is-carmen-sandiego-tv-show-series::WitWiCS S03 E14 The Outback Soundtrack Hijack.mp4": 1681,
  "where-in-the-world-is-carmen-sandiego-tv-show-series::WitWiCS S03 E15 Come Back With That Kibbutz, Toots.mp4": 1495,
  "where-in-the-world-is-carmen-sandiego-tv-show-series::WitWiCS S03 E16 The Kazanluk Cologne Caper.mp4": 1577,
  "where-in-the-world-is-carmen-sandiego-tv-show-series::WitWiCS S03 E17 The Glacier Erasure.mp4": 1685,
  "where-in-the-world-is-carmen-sandiego-tv-show-series::WitWiCS S03 E18 Rio Rock Wranglers.mp4": 1665,
  "where-in-the-world-is-carmen-sandiego-tv-show-series::WitWiCS S03 E19 The Grand Trunk Punk.mp4": 1635,
  "where-in-the-world-is-carmen-sandiego-tv-show-series::WitWiCS S03 E20 The Bee-Bird Burglary.mp4": 1674,
},
};
