window.SHOW = {
  id: "BerenstainBears",
  title: "the Berenstain Bears",
  art: "BerenstainBears.jpg",
  storageProgressKey: "berenstainbears-progress",
  storageSettingsKey: "berenstainbears-settings",
  nestedPaths: true,
  grouping: "season",
  segments: "none",
  episodes: [
  ["theberenstainbearscompleteseries", "THE BERENSTAIN BEARS - S01E01 - The Berenstain Bears /101 Trouble At School",
    "The Berenstain Bears (2003)/101 Trouble At School.mp4"],
  ["theberenstainbearscompleteseries", "THE BERENSTAIN BEARS - S01E02 - The Berenstain Bears /102 Visit The Dentist",
    "The Berenstain Bears (2003)/102 Visit The Dentist.mp4"],
  ["theberenstainbearscompleteseries", "THE BERENSTAIN BEARS - S01E03 - The Berenstain Bears /103 Mama's New Job",
    "The Berenstain Bears (2003)/103 Mama's New Job.mp4"],
  ["theberenstainbearscompleteseries", "THE BERENSTAIN BEARS - S01E04 - The Berenstain Bears /104 Mighty Milton",
    "The Berenstain Bears (2003)/104 Mighty Milton.mp4"],
  ["theberenstainbearscompleteseries", "THE BERENSTAIN BEARS - S01E05 - The Berenstain Bears /105 Go To School",
    "The Berenstain Bears (2003)/105 Go To School.mp4"],
  ["theberenstainbearscompleteseries", "THE BERENSTAIN BEARS - S01E06 - The Berenstain Bears /106 Week At Grandma's",
    "The Berenstain Bears (2003)/106 Week At Grandma's.mp4"],
  ["theberenstainbearscompleteseries", "THE BERENSTAIN BEARS - S01E07 - The Berenstain Bears /107 Trouble With Pets",
    "The Berenstain Bears (2003)/107 Trouble With Pets.mp4"],
  ["theberenstainbearscompleteseries", "THE BERENSTAIN BEARS - S01E08 - The Berenstain Bears /108 The Sitter",
    "The Berenstain Bears (2003)/108 The Sitter.mp4"],
  ["theberenstainbearscompleteseries", "THE BERENSTAIN BEARS - S01E09 - The Berenstain Bears /109 Too Much TV",
    "The Berenstain Bears (2003)/109 Too Much TV.mp4"],
  ["theberenstainbearscompleteseries", "THE BERENSTAIN BEARS - S01E10 - The Berenstain Bears /110 Trick Or Treat",
    "The Berenstain Bears (2003)/110 Trick Or Treat.mp4"],
  ["theberenstainbearscompleteseries", "THE BERENSTAIN BEARS - S01E11 - The Berenstain Bears /111 Trouble With Money",
    "The Berenstain Bears (2003)/111 Trouble With Money.mp4"],
  ["theberenstainbearscompleteseries", "THE BERENSTAIN BEARS - S01E12 - The Berenstain Bears /112 The Double Dare",
    "The Berenstain Bears (2003)/112 The Double Dare.mp4"],
  ["theberenstainbearscompleteseries", "THE BERENSTAIN BEARS - S01E13 - The Berenstain Bears /113 Out For The Team",
    "The Berenstain Bears (2003)/113 Out For The Team.mp4"],
  ["theberenstainbearscompleteseries", "THE BERENSTAIN BEARS - S01E14 - The Berenstain Bears /114 Count Their Blessings",
    "The Berenstain Bears (2003)/114 Count Their Blessings.mp4"],
  ["theberenstainbearscompleteseries", "THE BERENSTAIN BEARS - S01E15 - The Berenstain Bears /115 The Slumber Party",
    "The Berenstain Bears (2003)/115 The Slumber Party.mp4"],
  ["theberenstainbearscompleteseries", "THE BERENSTAIN BEARS - S01E16 - The Berenstain Bears /116 The Homework Hassle",
    "The Berenstain Bears (2003)/116 The Homework Hassle.mp4"],
  ["theberenstainbearscompleteseries", "THE BERENSTAIN BEARS - S01E17 - The Berenstain Bears /117 The Talent Show",
    "The Berenstain Bears (2003)/117 The Talent Show.mp4"],
  ["theberenstainbearscompleteseries", "THE BERENSTAIN BEARS - S01E18 - The Berenstain Bears /118 The Haunted Lighthouse",
    "The Berenstain Bears (2003)/118 The Haunted Lighthouse.mp4"],
  ["theberenstainbearscompleteseries", "THE BERENSTAIN BEARS - S01E19 - The Berenstain Bears /119 The Birthday Boy",
    "The Berenstain Bears (2003)/119 The Birthday Boy.mp4"],
  ["theberenstainbearscompleteseries", "THE BERENSTAIN BEARS - S01E20 - The Berenstain Bears /120 The Green Eyed Monster",
    "The Berenstain Bears (2003)/120 The Green Eyed Monster.mp4"],
  ["theberenstainbearscompleteseries", "THE BERENSTAIN BEARS - S01E21 - The Berenstain Bears /121 The Baby Chipmunk",
    "The Berenstain Bears (2003)/121 The Baby Chipmunk.mp4"],
  ["theberenstainbearscompleteseries", "THE BERENSTAIN BEARS - S01E22 - The Berenstain Bears /122 The Wishing Star",
    "The Berenstain Bears (2003)/122 The Wishing Star.mp4"],
  ["theberenstainbearscompleteseries", "THE BERENSTAIN BEARS - S01E23 - The Berenstain Bears /123 Get The Gimmies",
    "The Berenstain Bears (2003)/123 Get The Gimmies.mp4"],
  ["theberenstainbearscompleteseries", "THE BERENSTAIN BEARS - S01E24 - The Berenstain Bears /124 Lost In A Cave",
    "The Berenstain Bears (2003)/124 Lost In A Cave.mp4"],
  ["theberenstainbearscompleteseries", "THE BERENSTAIN BEARS - S01E25 - The Berenstain Bears /125 Too Much Junk Food",
    "The Berenstain Bears (2003)/125 Too Much Junk Food.mp4"],
  ["theberenstainbearscompleteseries", "THE BERENSTAIN BEARS - S01E26 - The Berenstain Bears /126 Go To Camp",
    "The Berenstain Bears (2003)/126 Go To Camp.mp4"],
  ["theberenstainbearscompleteseries", "THE BERENSTAIN BEARS - S01E27 - The Berenstain Bears /127 The Excuse Note",
    "The Berenstain Bears (2003)/127 The Excuse Note.mp4"],
  ["theberenstainbearscompleteseries", "THE BERENSTAIN BEARS - S01E28 - The Berenstain Bears /128 On The Job",
    "The Berenstain Bears (2003)/128 On The Job.mp4"],
  ["theberenstainbearscompleteseries", "THE BERENSTAIN BEARS - S01E29 - The Berenstain Bears /129 Too Small For The Team",
    "The Berenstain Bears (2003)/129 Too Small For The Team.mp4"],
  ["theberenstainbearscompleteseries", "THE BERENSTAIN BEARS - S01E30 - The Berenstain Bears /130 The Jump Rope Contest",
    "The Berenstain Bears (2003)/130 The Jump Rope Contest.mp4"],
  ["theberenstainbearscompleteseries", "THE BERENSTAIN BEARS - S01E31 - The Berenstain Bears /131 The Bad Habit",
    "The Berenstain Bears (2003)/131 The Bad Habit.mp4"],
  ["theberenstainbearscompleteseries", "THE BERENSTAIN BEARS - S01E32 - The Berenstain Bears /132 The Prize Pumpkin",
    "The Berenstain Bears (2003)/132 The Prize Pumpkin.mp4"],
  ["theberenstainbearscompleteseries", "THE BERENSTAIN BEARS - S01E33 - The Berenstain Bears /133 Ferdy Factual",
    "The Berenstain Bears (2003)/133 Ferdy Factual.mp4"],
  ["theberenstainbearscompleteseries", "THE BERENSTAIN BEARS - S01E34 - The Berenstain Bears /134 Lend A Helping Hand",
    "The Berenstain Bears (2003)/134 Lend A Helping Hand.mp4"],
  ["theberenstainbearscompleteseries", "THE BERENSTAIN BEARS - S01E35 - The Berenstain Bears /136 Nothing To Do",
    "The Berenstain Bears (2003)/136 Nothing To Do.mp4"],
  ["theberenstainbearscompleteseries", "THE BERENSTAIN BEARS - S01E36 - The Berenstain Bears /137 House Of Mirrors",
    "The Berenstain Bears (2003)/137 House Of Mirrors.mp4"],
  ["theberenstainbearscompleteseries", "THE BERENSTAIN BEARS - S01E37 - The Berenstain Bears /138 Too Much Pressure",
    "The Berenstain Bears (2003)/138 Too Much Pressure.mp4"],
  ["theberenstainbearscompleteseries", "THE BERENSTAIN BEARS - S01E38 - The Berenstain Bears /139 Visit Fun Park",
    "The Berenstain Bears (2003)/139 Visit Fun Park.mp4"],
  ["theberenstainbearscompleteseries", "THE BERENSTAIN BEARS - S01E39 - The Berenstain Bears /140 The Perfect Fishing Spot",
    "The Berenstain Bears (2003)/140 The Perfect Fishing Spot.mp4"],
  ["theberenstainbearscompleteseries", "THE BERENSTAIN BEARS - S01E40 - The Berenstain Bears /141 Summer Job",
    "The Berenstain Bears (2003)/141 Summer Job.mp4"],
  ["theberenstainbearscompleteseries", "THE BERENSTAIN BEARS - S01E41 - The Berenstain Bears /142 The Red Kite",
    "The Berenstain Bears (2003)/142 The Red Kite.mp4"],
  ["theberenstainbearscompleteseries", "THE BERENSTAIN BEARS - S01E42 - The Berenstain Bears /143 Too Much Vacation",
    "The Berenstain Bears (2003)/143 Too Much Vacation.mp4"],
  ["theberenstainbearscompleteseries", "THE BERENSTAIN BEARS - S01E43 - The Berenstain Bears /144 Trouble With Grown Ups",
    "The Berenstain Bears (2003)/144 Trouble With Grown-Ups.mp4"],
  ["theberenstainbearscompleteseries", "THE BERENSTAIN BEARS - S01E44 - The Berenstain Bears /145 Go To The Doctor",
    "The Berenstain Bears (2003)/145 Go To The Doctor.mp4"],
  ["theberenstainbearscompleteseries", "THE BERENSTAIN BEARS - S01E45 - The Berenstain Bears /146 Don't Pollute (Anymore",
    "The Berenstain Bears (2003)/146 Don't Pollute (Anymore).mp4"],
  ["theberenstainbearscompleteseries", "THE BERENSTAIN BEARS - S01E46 - The Berenstain Bears /147 In The Crowd",
    "The Berenstain Bears (2003)/147 In The Crowd.mp4"],
  ["theberenstainbearscompleteseries", "THE BERENSTAIN BEARS - S01E47 - The Berenstain Bears /148 Fly It",
    "The Berenstain Bears (2003)/148 Fly It.mp4"],
  ["theberenstainbearscompleteseries", "THE BERENSTAIN BEARS - S01E48 - The Berenstain Bears /149 By The Sea",
    "The Berenstain Bears (2003)/149 By The Sea.mp4"],
  ["theberenstainbearscompleteseries", "THE BERENSTAIN BEARS - S01E49 - The Berenstain Bears /150 Catch The Bus",
    "The Berenstain Bears (2003)/150 Catch The Bus.mp4"],
  ["theberenstainbearscompleteseries", "THE BERENSTAIN BEARS - S01E50 - The Berenstain Bears /151 Family Get Together",
    "The Berenstain Bears (2003)/151 Family Get Together.mp4"],
  ["theberenstainbearscompleteseries", "THE BERENSTAIN BEARS - S01E51 - The Berenstain Bears /152 The Stinky Milk Mystery",
    "The Berenstain Bears (2003)/152 The Stinky Milk Mystery.mp4"],
  ["theberenstainbearscompleteseries", "THE BERENSTAIN BEARS - S01E52 - The Berenstain Bears /153 New Neighors",
    "The Berenstain Bears (2003)/153 New Neighors.mp4"],
  ["theberenstainbearscompleteseries", "THE BERENSTAIN BEARS - S01E53 - The Berenstain Bears /154 The Big Election",
    "The Berenstain Bears (2003)/154 The Big Election.mp4"],
  ["theberenstainbearscompleteseries", "THE BERENSTAIN BEARS - S01E54 - The Berenstain Bears /155 At The Giant Mall",
    "The Berenstain Bears (2003)/155 At The Giant Mall.mp4"],
  ["theberenstainbearscompleteseries", "THE BERENSTAIN BEARS - S01E55 - The Berenstain Bears /156 The Giddy Grandma",
    "The Berenstain Bears (2003)/156 The Giddy Grandma.mp4"],
  ["theberenstainbearscompleteseries", "THE BERENSTAIN BEARS - S01E56 - The Berenstain Bears /157 Think Of Those In Need",
    "The Berenstain Bears (2003)/157 Think Of Those In Need.mp4"],
  ["theberenstainbearscompleteseries", "THE BERENSTAIN BEARS - S01E57 - The Berenstain Bears /158 The Hicup Cure",
    "The Berenstain Bears (2003)/158 The Hicup Cure.mp4"],
  ["theberenstainbearscompleteseries", "THE BERENSTAIN BEARS - S01E58 - The Berenstain Bears /159 Go To The Movies",
    "The Berenstain Bears (2003)/159 Go To The Movies.mp4"],
  ["theberenstainbearscompleteseries", "THE BERENSTAIN BEARS - S01E59 - The Berenstain Bears /160 Car Trip",
    "The Berenstain Bears (2003)/160 Car Trip.mp4"],
  ["theberenstainbearscompleteseries", "THE BERENSTAIN BEARS - S01E60 - The Berenstain Bears /161 Pet Show",
    "The Berenstain Bears (2003)/161 Pet Show.mp4"],
  ["theberenstainbearscompleteseries", "THE BERENSTAIN BEARS - S01E61 - The Berenstain Bears /162 Pick Up & Put Away",
    "The Berenstain Bears (2003)/162 Pick Up & Put Away.mp4"],
  ["theberenstainbearscompleteseries", "THE BERENSTAIN BEARS - S01E62 - The Berenstain Bears /163 Hug & Make Up",
    "The Berenstain Bears (2003)/163 Hug & Make Up.mp4"],
  ["theberenstainbearscompleteseries", "THE BERENSTAIN BEARS - S01E63 - The Berenstain Bears /164 Big Road Race",
    "The Berenstain Bears (2003)/164 Big Road Race.mp4"],
  ["theberenstainbearscompleteseries", "THE BERENSTAIN BEARS - S01E64 - The Berenstain Bears /165 Attic Treasure",
    "The Berenstain Bears (2003)/165 Attic Treasure.mp4"],
  ["theberenstainbearscompleteseries", "THE BERENSTAIN BEARS - S01E65 - The Berenstain Bears /166 Moving Day",
    "The Berenstain Bears (2003)/166 Moving Day.mp4"],
  ["theberenstainbearscompleteseries", "THE BERENSTAIN BEARS - S01E66 - The Berenstain Bears /167 Gotta Dance",
    "The Berenstain Bears (2003)/167 Gotta Dance.mp4"],
  ["theberenstainbearscompleteseries", "THE BERENSTAIN BEARS - S01E67 - The Berenstain Bears /168 The Bad Dream",
    "The Berenstain Bears (2003)/168 The Bad Dream.mp4"],
  ["theberenstainbearscompleteseries", "THE BERENSTAIN BEARS - S01E68 - The Berenstain Bears /169 Say Please & Thank You",
    "The Berenstain Bears (2003)/169 Say Please & Thank You.mp4"],
  ["theberenstainbearscompleteseries", "THE BERENSTAIN BEARS - S01E69 - The Berenstain Bears /170 Help Around The Workshop",
    "The Berenstain Bears (2003)/170 Help Around The Workshop.mp4"],
  ["theberenstainbearscompleteseries", "THE BERENSTAIN BEARS - S01E70 - The Berenstain Bears /171 White Water Adventure",
    "The Berenstain Bears (2003)/171 White Water Adventure.mp4"],
  ["theberenstainbearscompleteseries", "THE BERENSTAIN BEARS - S01E71 - The Berenstain Bears /172 Showdown At Birders Wood",
    "The Berenstain Bears (2003)/172 Showdown At Birders Wood.mp4"],
  ["theberenstainbearscompleteseries", "THE BERENSTAIN BEARS - S01E72 - The Berenstain Bears /173 That Stump Must Go",
    "The Berenstain Bears (2003)/173 That Stump Must Go.mp4"],
  ["theberenstainbearscompleteseries", "THE BERENSTAIN BEARS - S01E73 - The Berenstain Bears /174 Draw It",
    "The Berenstain Bears (2003)/174 Draw It.mp4"],
  ["theberenstainbearscompleteseries", "THE BERENSTAIN BEARS - S01E74 - The Berenstain Bears /175 Papa's Pizza",
    "The Berenstain Bears (2003)/175 Papa's Pizza.mp4"],
  ["theberenstainbearscompleteseries", "THE BERENSTAIN BEARS - S01E75 - The Berenstain Bears /176 The Female Fullback",
    "The Berenstain Bears (2003)/176 The Female Fullback.mp4"],
  ["theberenstainbearscompleteseries", "THE BERENSTAIN BEARS - S01E76 - The Berenstain Bears /177 Bears For All Seasons",
    "The Berenstain Bears (2003)/177 Bears For All Seasons.mp4"],
  ["theberenstainbearscompleteseries", "THE BERENSTAIN BEARS - S01E77 - The Berenstain Bears /178 Grow It",
    "The Berenstain Bears (2003)/178 Grow It.mp4"],
  ["theberenstainbearscompleteseries", "THE BERENSTAIN BEARS - S01E78 - The Berenstain Bears /179 Go Up & Down",
    "The Berenstain Bears (2003)/179 Go Up & Down.mp4"],
  ["theberenstainbearscompleteseries", "THE BERENSTAIN BEARS - S01E79 - The Berenstain Bears /180 Big Bear Small Bear",
    "The Berenstain Bears (2003)/180 Big Bear Small Bear.mp4"],
],
  durations: {
  "theberenstainbearscompleteseries::The Berenstain Bears (2003)/101 Trouble At School.mp4": 781,
  "theberenstainbearscompleteseries::The Berenstain Bears (2003)/102 Visit The Dentist.mp4": 781,
  "theberenstainbearscompleteseries::The Berenstain Bears (2003)/103 Mama's New Job.mp4": 781,
  "theberenstainbearscompleteseries::The Berenstain Bears (2003)/104 Mighty Milton.mp4": 781,
  "theberenstainbearscompleteseries::The Berenstain Bears (2003)/105 Go To School.mp4": 781,
  "theberenstainbearscompleteseries::The Berenstain Bears (2003)/106 Week At Grandma's.mp4": 781,
  "theberenstainbearscompleteseries::The Berenstain Bears (2003)/107 Trouble With Pets.mp4": 780,
  "theberenstainbearscompleteseries::The Berenstain Bears (2003)/108 The Sitter.mp4": 780,
  "theberenstainbearscompleteseries::The Berenstain Bears (2003)/109 Too Much TV.mp4": 780,
  "theberenstainbearscompleteseries::The Berenstain Bears (2003)/110 Trick Or Treat.mp4": 781,
  "theberenstainbearscompleteseries::The Berenstain Bears (2003)/111 Trouble With Money.mp4": 781,
  "theberenstainbearscompleteseries::The Berenstain Bears (2003)/112 The Double Dare.mp4": 781,
  "theberenstainbearscompleteseries::The Berenstain Bears (2003)/113 Out For The Team.mp4": 780,
  "theberenstainbearscompleteseries::The Berenstain Bears (2003)/114 Count Their Blessings.mp4": 780,
  "theberenstainbearscompleteseries::The Berenstain Bears (2003)/115 The Slumber Party.mp4": 781,
  "theberenstainbearscompleteseries::The Berenstain Bears (2003)/116 The Homework Hassle.mp4": 781,
  "theberenstainbearscompleteseries::The Berenstain Bears (2003)/117 The Talent Show.mp4": 781,
  "theberenstainbearscompleteseries::The Berenstain Bears (2003)/118 The Haunted Lighthouse.mp4": 781,
  "theberenstainbearscompleteseries::The Berenstain Bears (2003)/119 The Birthday Boy.mp4": 781,
  "theberenstainbearscompleteseries::The Berenstain Bears (2003)/120 The Green Eyed Monster.mp4": 781,
  "theberenstainbearscompleteseries::The Berenstain Bears (2003)/121 The Baby Chipmunk.mp4": 781,
  "theberenstainbearscompleteseries::The Berenstain Bears (2003)/122 The Wishing Star.mp4": 781,
  "theberenstainbearscompleteseries::The Berenstain Bears (2003)/123 Get The Gimmies.mp4": 781,
  "theberenstainbearscompleteseries::The Berenstain Bears (2003)/124 Lost In A Cave.mp4": 781,
  "theberenstainbearscompleteseries::The Berenstain Bears (2003)/125 Too Much Junk Food.mp4": 780,
  "theberenstainbearscompleteseries::The Berenstain Bears (2003)/126 Go To Camp.mp4": 780,
  "theberenstainbearscompleteseries::The Berenstain Bears (2003)/127 The Excuse Note.mp4": 781,
  "theberenstainbearscompleteseries::The Berenstain Bears (2003)/128 On The Job.mp4": 781,
  "theberenstainbearscompleteseries::The Berenstain Bears (2003)/129 Too Small For The Team.mp4": 781,
  "theberenstainbearscompleteseries::The Berenstain Bears (2003)/130 The Jump Rope Contest.mp4": 781,
  "theberenstainbearscompleteseries::The Berenstain Bears (2003)/131 The Bad Habit.mp4": 781,
  "theberenstainbearscompleteseries::The Berenstain Bears (2003)/132 The Prize Pumpkin.mp4": 781,
  "theberenstainbearscompleteseries::The Berenstain Bears (2003)/133 Ferdy Factual.mp4": 781,
  "theberenstainbearscompleteseries::The Berenstain Bears (2003)/134 Lend A Helping Hand.mp4": 781,
  "theberenstainbearscompleteseries::The Berenstain Bears (2003)/136 Nothing To Do.mp4": 781,
  "theberenstainbearscompleteseries::The Berenstain Bears (2003)/137 House Of Mirrors.mp4": 781,
  "theberenstainbearscompleteseries::The Berenstain Bears (2003)/138 Too Much Pressure.mp4": 781,
  "theberenstainbearscompleteseries::The Berenstain Bears (2003)/139 Visit Fun Park.mp4": 781,
  "theberenstainbearscompleteseries::The Berenstain Bears (2003)/140 The Perfect Fishing Spot.mp4": 781,
  "theberenstainbearscompleteseries::The Berenstain Bears (2003)/141 Summer Job.mp4": 781,
  "theberenstainbearscompleteseries::The Berenstain Bears (2003)/142 The Red Kite.mp4": 781,
  "theberenstainbearscompleteseries::The Berenstain Bears (2003)/143 Too Much Vacation.mp4": 781,
  "theberenstainbearscompleteseries::The Berenstain Bears (2003)/144 Trouble With Grown-Ups.mp4": 781,
  "theberenstainbearscompleteseries::The Berenstain Bears (2003)/145 Go To The Doctor.mp4": 781,
  "theberenstainbearscompleteseries::The Berenstain Bears (2003)/146 Don't Pollute (Anymore).mp4": 781,
  "theberenstainbearscompleteseries::The Berenstain Bears (2003)/147 In The Crowd.mp4": 781,
  "theberenstainbearscompleteseries::The Berenstain Bears (2003)/148 Fly It.mp4": 781,
  "theberenstainbearscompleteseries::The Berenstain Bears (2003)/149 By The Sea.mp4": 781,
  "theberenstainbearscompleteseries::The Berenstain Bears (2003)/150 Catch The Bus.mp4": 781,
  "theberenstainbearscompleteseries::The Berenstain Bears (2003)/151 Family Get Together.mp4": 781,
  "theberenstainbearscompleteseries::The Berenstain Bears (2003)/152 The Stinky Milk Mystery.mp4": 781,
  "theberenstainbearscompleteseries::The Berenstain Bears (2003)/153 New Neighors.mp4": 781,
  "theberenstainbearscompleteseries::The Berenstain Bears (2003)/154 The Big Election.mp4": 781,
  "theberenstainbearscompleteseries::The Berenstain Bears (2003)/155 At The Giant Mall.mp4": 781,
  "theberenstainbearscompleteseries::The Berenstain Bears (2003)/156 The Giddy Grandma.mp4": 781,
  "theberenstainbearscompleteseries::The Berenstain Bears (2003)/157 Think Of Those In Need.mp4": 781,
  "theberenstainbearscompleteseries::The Berenstain Bears (2003)/158 The Hicup Cure.mp4": 781,
  "theberenstainbearscompleteseries::The Berenstain Bears (2003)/159 Go To The Movies.mp4": 783,
  "theberenstainbearscompleteseries::The Berenstain Bears (2003)/160 Car Trip.mp4": 783,
  "theberenstainbearscompleteseries::The Berenstain Bears (2003)/161 Pet Show.mp4": 782,
  "theberenstainbearscompleteseries::The Berenstain Bears (2003)/162 Pick Up & Put Away.mp4": 782,
  "theberenstainbearscompleteseries::The Berenstain Bears (2003)/163 Hug & Make Up.mp4": 783,
  "theberenstainbearscompleteseries::The Berenstain Bears (2003)/164 Big Road Race.mp4": 782,
  "theberenstainbearscompleteseries::The Berenstain Bears (2003)/165 Attic Treasure.mp4": 782,
  "theberenstainbearscompleteseries::The Berenstain Bears (2003)/166 Moving Day.mp4": 782,
  "theberenstainbearscompleteseries::The Berenstain Bears (2003)/167 Gotta Dance.mp4": 782,
  "theberenstainbearscompleteseries::The Berenstain Bears (2003)/168 The Bad Dream.mp4": 782,
  "theberenstainbearscompleteseries::The Berenstain Bears (2003)/169 Say Please & Thank You.mp4": 813,
  "theberenstainbearscompleteseries::The Berenstain Bears (2003)/170 Help Around The Workshop.mp4": 813,
  "theberenstainbearscompleteseries::The Berenstain Bears (2003)/171 White Water Adventure.mp4": 783,
  "theberenstainbearscompleteseries::The Berenstain Bears (2003)/172 Showdown At Birders Wood.mp4": 782,
  "theberenstainbearscompleteseries::The Berenstain Bears (2003)/173 That Stump Must Go.mp4": 782,
  "theberenstainbearscompleteseries::The Berenstain Bears (2003)/174 Draw It.mp4": 782,
  "theberenstainbearscompleteseries::The Berenstain Bears (2003)/175 Papa's Pizza.mp4": 782,
  "theberenstainbearscompleteseries::The Berenstain Bears (2003)/176 The Female Fullback.mp4": 782,
  "theberenstainbearscompleteseries::The Berenstain Bears (2003)/177 Bears For All Seasons.mp4": 814,
  "theberenstainbearscompleteseries::The Berenstain Bears (2003)/178 Grow It.mp4": 813,
  "theberenstainbearscompleteseries::The Berenstain Bears (2003)/179 Go Up & Down.mp4": 782,
  "theberenstainbearscompleteseries::The Berenstain Bears (2003)/180 Big Bear Small Bear.mp4": 782,
},
};
