window.SHOW = {
  id: "Simpsons",
  title: "The Simpsons",
  art: "Simpsons.jpg",
  storageProgressKey: "simpsons-progress",
  storageSettingsKey: "simpsons-settings",
  nestedPaths: true,
  grouping: "season",
  segments: "none",
  episodes: [
  ["the-simpsons-full-series", "THE SIMPSONS - S00E00 - The Simpsons Thumbnail (Sorry, this is so that this image will come…",
    "The Simpsons S00E00 - Thumbnail (Sorry, this is so that this image will come up as thumbnail on IA).ia.mp4"],
  ["the-simpsons-full-series", "THE SIMPSONS - S01E01 - Simpsons Roasting on an Open Fire",
    "The Simpsons S01E01 - Simpsons Roasting on an Open Fire.mp4"],
  ["the-simpsons-full-series", "THE SIMPSONS - S01E02 - Bart the Genius",
    "The Simpsons S01E02 - Bart the Genius.ia.mp4"],
  ["the-simpsons-full-series", "THE SIMPSONS - S01E03 - Homer's Odyssey",
    "The Simpsons S01E03 - Homer's Odyssey.ia.mp4"],
  ["the-simpsons-full-series", "THE SIMPSONS - S01E04 - There's No Disgrace Like Home",
    "The Simpsons S01E04 - There's No Disgrace Like Home.ia.mp4"],
  ["the-simpsons-full-series", "THE SIMPSONS - S01E05 - Bart the General",
    "The Simpsons S01E05 - Bart the General.ia.mp4"],
  ["the-simpsons-full-series", "THE SIMPSONS - S01E06 - Moaning Lisa",
    "The Simpsons S01E06 - Moaning Lisa.ia.mp4"],
  ["the-simpsons-full-series", "THE SIMPSONS - S01E07 - The Call of the Simpsons",
    "The Simpsons S01E07 - The Call of the Simpsons.ia.mp4"],
  ["the-simpsons-full-series", "THE SIMPSONS - S01E08 - The Telltale Head",
    "The Simpsons S01E08 - The Telltale Head.ia.mp4"],
  ["the-simpsons-full-series", "THE SIMPSONS - S01E09 - Life on the Fast Lane",
    "The Simpsons S01E09 - Life on the Fast Lane.ia.mp4"],
  ["the-simpsons-full-series", "THE SIMPSONS - S01E10 - Homer's Night Out",
    "The Simpsons S01E10 - Homer's Night Out.ia.mp4"],
  ["the-simpsons-full-series", "THE SIMPSONS - S01E11 - The Crepes of Wrath",
    "The Simpsons S01E11 - The Crepes of Wrath.ia.mp4"],
  ["the-simpsons-full-series", "THE SIMPSONS - S01E12 - Krusty Gets Busted",
    "The Simpsons S01E12 - Krusty Gets Busted.ia.mp4"],
  ["the-simpsons-full-series", "THE SIMPSONS - S01E13 - Some Enchanted Evening",
    "The Simpsons S01E13 - Some Enchanted Evening.ia.mp4"],
  ["the-simpsons-full-series", "THE SIMPSONS - S02E01 - Bart Gets an F",
    "The Simpsons S02E01 - Bart Gets an 'F'.ia.mp4"],
  ["the-simpsons-full-series", "THE SIMPSONS - S02E02 - Simpson and Delilah",
    "The Simpsons S02E02 - Simpson and Delilah.ia.mp4"],
  ["the-simpsons-full-series", "THE SIMPSONS - S02E03 - Treehouse of Horror",
    "The Simpsons S02E03 - Treehouse of Horror.ia.mp4"],
  ["the-simpsons-full-series", "THE SIMPSONS - S02E05 - Dancin' Homer",
    "The Simpsons S02E05 - Dancin' Homer.mp4"],
  ["the-simpsons-full-series", "THE SIMPSONS - S02E06 - Dead Putting Society",
    "The Simpsons S02E06 - Dead Putting Society.mp4"],
],
  durations: {
  "the-simpsons-full-series::The Simpsons S00E00 - Thumbnail (Sorry, this is so that this image will come up as thumbnail on IA).ia.mp4": 3600,
  "the-simpsons-full-series::The Simpsons S01E01 - Simpsons Roasting on an Open Fire.mp4": 1393,
  "the-simpsons-full-series::The Simpsons S01E02 - Bart the Genius.ia.mp4": 1387,
  "the-simpsons-full-series::The Simpsons S01E03 - Homer's Odyssey.ia.mp4": 1391,
  "the-simpsons-full-series::The Simpsons S01E04 - There's No Disgrace Like Home.ia.mp4": 1345,
  "the-simpsons-full-series::The Simpsons S01E05 - Bart the General.ia.mp4": 1362,
  "the-simpsons-full-series::The Simpsons S01E06 - Moaning Lisa.ia.mp4": 1389,
  "the-simpsons-full-series::The Simpsons S01E07 - The Call of the Simpsons.ia.mp4": 1387,
  "the-simpsons-full-series::The Simpsons S01E08 - The Telltale Head.ia.mp4": 1366,
  "the-simpsons-full-series::The Simpsons S01E09 - Life on the Fast Lane.ia.mp4": 1389,
  "the-simpsons-full-series::The Simpsons S01E10 - Homer's Night Out.ia.mp4": 1388,
  "the-simpsons-full-series::The Simpsons S01E11 - The Crepes of Wrath.ia.mp4": 1392,
  "the-simpsons-full-series::The Simpsons S01E12 - Krusty Gets Busted.ia.mp4": 1392,
  "the-simpsons-full-series::The Simpsons S01E13 - Some Enchanted Evening.ia.mp4": 1377,
  "the-simpsons-full-series::The Simpsons S02E01 - Bart Gets an 'F'.ia.mp4": 1389,
  "the-simpsons-full-series::The Simpsons S02E02 - Simpson and Delilah.ia.mp4": 1390,
  "the-simpsons-full-series::The Simpsons S02E03 - Treehouse of Horror.ia.mp4": 1396,
  "the-simpsons-full-series::The Simpsons S02E05 - Dancin' Homer.mp4": 1393,
  "the-simpsons-full-series::The Simpsons S02E06 - Dead Putting Society.mp4": 1380,
},
};
