window.SHOW = {
  id: "DoogieHowserMD",
  title: "Doogie Howser, M.D.",
  art: "DoogieHowserMD.jpg",
  storageProgressKey: "doogiehowsermd-progress",
  storageSettingsKey: "doogiehowsermd-settings",
  grouping: "season",
  segments: "none",
  episodes: [
    [
      "doogie-howser-m.d.-season-1-of-4-xvid-avi",
      "DOOGIE HOWSER, M.D. - S01E01 - Pilot",
      "Doogie Howser, M.D. - S01E01 - Pilot.mp4",
    ],
    [
      "doogie-howser-m.d.-season-1-of-4-xvid-avi",
      "DOOGIE HOWSER, M.D. - S01E02 - The Ice Queen Cometh",
      "Doogie Howser, M.D. - S01E02 - The Ice Queen Cometh.mp4",
    ],
    [
      "doogie-howser-m.d.-season-1-of-4-xvid-avi",
      "DOOGIE HOWSER, M.D. - S01E03 - A Stitch Called Wanda",
      "Doogie Howser, M.D. - S01E03 - A Stitch Called Wanda.mp4",
    ],
    [
      "doogie-howser-m.d.-season-1-of-4-xvid-avi",
      "DOOGIE HOWSER, M.D. - S01E04 - Frisky Business",
      "Doogie Howser, M.D. - S01E04 - Frisky Business.mp4",
    ],
    [
      "doogie-howser-m.d.-season-1-of-4-xvid-avi",
      "DOOGIE HOWSER, M.D. - S01E05 - The Short Goodbye",
      "Doogie Howser, M.D. - S01E05 - The Short Goodbye.mp4",
    ],
    [
      "doogie-howser-m.d.-season-1-of-4-xvid-avi",
      "DOOGIE HOWSER, M.D. - S01E06 - Simply Irresistible",
      "Doogie Howser, M.D. - S01E06 - Simply Irresistible.mp4",
    ],
    [
      "doogie-howser-m.d.-season-1-of-4-xvid-avi",
      "DOOGIE HOWSER, M.D. - S01E07 - Vinnie Video Vici",
      "Doogie Howser, M.D. - S01E07 - Vinnie Video Vici.mp4",
    ],
    [
      "doogie-howser-m.d.-season-1-of-4-xvid-avi",
      "DOOGIE HOWSER, M.D. - S01E08 - Blood and Remembrance",
      "Doogie Howser, M.D. - S01E08 - Blood And Remembrance.mp4",
    ],
    [
      "doogie-howser-m.d.-season-1-of-4-xvid-avi",
      "DOOGIE HOWSER, M.D. - S01E09 - She Ain't Heavy, She's My Cousin",
      "Doogie Howser, M.D. - S01E09 - She Ain't Heavy, She's My Cousin.mp4",
    ],
    [
      "doogie-howser-m.d.-season-1-of-4-xvid-avi",
      "DOOGIE HOWSER, M.D. - S01E10 - My Old Man and the Sea",
      "Doogie Howser, M.D. - S01E10 - My Old Man And The Sea.mp4",
    ],
    [
      "doogie-howser-m.d.-season-1-of-4-xvid-avi",
      "DOOGIE HOWSER, M.D. - S01E11 - Tonight's the Night",
      "Doogie Howser, M.D. - S01E11 - Tonight's The Night.mp4",
    ],
    [
      "doogie-howser-m.d.-season-1-of-4-xvid-avi",
      "DOOGIE HOWSER, M.D. - S01E12 - Every Dog Has His Doogie",
      "Doogie Howser, M.D. - S01E12 - Every Dog Has His Doogie.mp4",
    ],
    [
      "doogie-howser-m.d.-season-1-of-4-xvid-avi",
      "DOOGIE HOWSER, M.D. - S01E13 - Doogie the Red-Nosed Reindeer",
      "Doogie Howser, M.D. - S01E13 - Doogie The Red-Nosed Reindeer.mp4",
    ],
    [
      "doogie-howser-m.d.-season-1-of-4-xvid-avi",
      "DOOGIE HOWSER, M.D. - S01E14 - Greed Is Good",
      "Doogie Howser, M.D. - S01E14 - Greed Is Good.mp4",
    ],
    [
      "doogie-howser-m.d.-season-1-of-4-xvid-avi",
      "DOOGIE HOWSER, M.D. - S01E15 - Attack of the Green-Eyed Monster",
      "Doogie Howser, M.D. - S01E15 - Attack Of The Green-Eyed Monster.mp4",
    ],
    [
      "doogie-howser-m.d.-season-1-of-4-xvid-avi",
      "DOOGIE HOWSER, M.D. - S01E16 - It Ain't Over Till Mrs. Howser Sings",
      "Doogie Howser, M.D. - S01E16 - It Ain't Over Till Mrs. Howser Sings.mp4",
    ],
    [
      "doogie-howser-m.d.-season-1-of-4-xvid-avi",
      "DOOGIE HOWSER, M.D. - S01E17 - Tough Guys Don't Teach",
      "Doogie Howser, M.D. - S01E17 - Tough Guys Don't Teach.mp4",
    ],
    [
      "doogie-howser-m.d.-season-1-of-4-xvid-avi",
      "DOOGIE HOWSER, M.D. - S01E18 - I Never Sold Shower Heads for My Father",
      "Doogie Howser, M.D. - S01E18 - I Never Sold Shower Heads For My Father.mp4",
    ],
    [
      "doogie-howser-m.d.-season-1-of-4-xvid-avi",
      "DOOGIE HOWSER, M.D. - S01E19 - Doogie's Awesome, Excellent Adventure",
      "Doogie Howser, M.D. - S01E19 - Doogie's Awesome, Excellent Adventure.mp4",
    ],
    [
      "doogie-howser-m.d.-season-1-of-4-xvid-avi",
      "DOOGIE HOWSER, M.D. - S01E20 - Use a Slurpy, Go to Jail",
      "Doogie Howser, M.D. - S01E20 - Use A Slurpy, Go To Jail.mp4",
    ],
    [
      "doogie-howser-m.d.-season-1-of-4-xvid-avi",
      "DOOGIE HOWSER, M.D. - S01E21 - Whose Mid-Life Crisis Is It Anyway?",
      "Doogie Howser, M.D. - S01E21 - Whose Mid-Life Crisis Is It Anyway.mp4",
    ],
    [
      "doogie-howser-m.d.-season-1-of-4-xvid-avi",
      "DOOGIE HOWSER, M.D. - S01E22 - Vinnie's Blind Date",
      "Doogie Howser, M.D. - S01E22 - Vinnie's Blind Date.mp4",
    ],
    [
      "doogie-howser-m.d.-season-1-of-4-xvid-avi",
      "DOOGIE HOWSER, M.D. - S01E23 - And the Winner Is...",
      "Doogie Howser, M.D. - S01E23 - And The Winner Is.mp4",
    ],
    [
      "doogie-howser-m.d.-season-1-of-4-xvid-avi",
      "DOOGIE HOWSER, M.D. - S01E24 - Breaking Up Is Hard to Doogie",
      "Doogie Howser, M.D. - S01E24 - Breaking Up Is Hard To Doogie.mp4",
    ],
    [
      "doogie-howser-m.d.-season-1-of-4-xvid-avi",
      "DOOGIE HOWSER, M.D. - S01E25 - The Grass Ain't Always Greener",
      "Doogie Howser, M.D. - S01E25 - The Grass Ain't Always Greener.mp4",
    ],
    [
      "doogie-howser-m.d.-season-1-of-4-xvid-avi",
      "DOOGIE HOWSER, M.D. - S01E26 - Frankly, My Dear, I Don't Give a Grand",
      "Doogie Howser, M.D. - S01E26 - Frankly, My Dear, I Don't Give A Grand.mp4",
    ],
    [
      "doogie-howser-m.d.-season-2-of-4-xvid-avi",
      "DOOGIE HOWSER, M.D. - S02E01 - Doogenstein",
      "Doogie Howser, M.D. - S02E01 - Doogenstein.mp4",
    ],
    [
      "doogie-howser-m.d.-season-2-of-4-xvid-avi",
      "DOOGIE HOWSER, M.D. - S02E02 - Guess Who's Coming to Doogie's",
      "Doogie Howser, M.D. - S02E02 - Guess Who's Coming to Doogie's.mp4",
    ],
    [
      "doogie-howser-m.d.-season-2-of-4-xvid-avi",
      "DOOGIE HOWSER, M.D. - S02E03 - Ask Dr. Doogie",
      "Doogie Howser, M.D. - S02E03 - Ask Doctor Doogie.mp4",
    ],
    [
      "doogie-howser-m.d.-season-2-of-4-xvid-avi",
      "DOOGIE HOWSER, M.D. - S02E04 - C'est la Vinnie",
      "Doogie Howser, M.D. - S02E04 - C'est La Vinnie.mp4",
    ],
    [
      "doogie-howser-m.d.-season-2-of-4-xvid-avi",
      "DOOGIE HOWSER, M.D. - S02E05 - Car Wars",
      "Doogie Howser, M.D. - S02E05 - Car Wars.mp4",
    ],
    [
      "doogie-howser-m.d.-season-2-of-4-xvid-avi",
      "DOOGIE HOWSER, M.D. - S02E06 - Doogie Sings the Blues",
      "Doogie Howser, M.D. - S02E06 - Doogie Sings the Blues.mp4",
    ],
    [
      "doogie-howser-m.d.-season-2-of-4-xvid-avi",
      "DOOGIE HOWSER, M.D. - S02E07 - Academia Nuts",
      "Doogie Howser, M.D. - S02E07 - Academia Nuts.mp4",
    ],
    [
      "doogie-howser-m.d.-season-2-of-4-xvid-avi",
      "DOOGIE HOWSER, M.D. - S02E08 - Revenge of the Teenage Dead",
      "Doogie Howser, M.D. - S02E08 - Revenge of the Teenage Dead.mp4",
    ],
    [
      "doogie-howser-m.d.-season-2-of-4-xvid-avi",
      "DOOGIE HOWSER, M.D. - S02E09 - Nautilus for Naught",
      "Doogie Howser, M.D. - S02E09 - Nautilus For Naught.mp4",
    ],
    [
      "doogie-howser-m.d.-season-2-of-4-xvid-avi",
      "DOOGIE HOWSER, M.D. - S02E10 - Don't Let the Turkeys Get You Down",
      "Doogie Howser, M.D. - S02E10 - Don't Let the Turkeys Get Down.mp4",
    ],
    [
      "doogie-howser-m.d.-season-2-of-4-xvid-avi",
      "DOOGIE HOWSER, M.D. - S02E11 - Oh Very Young",
      "Doogie Howser, M.D. - S02E11 - Oh Very Young.mp4",
    ],
    [
      "doogie-howser-m.d.-season-2-of-4-xvid-avi",
      "DOOGIE HOWSER, M.D. - S02E12 - TV or Not TV",
      "Doogie Howser, M.D. - S02E12 - TV or Not TV.mp4",
    ],
    [
      "doogie-howser-m.d.-season-2-of-4-xvid-avi",
      "DOOGIE HOWSER, M.D. - S02E13 - A Woman Too Far",
      "Doogie Howser, M.D. - S02E13 - A Woman Too Far.mp4",
    ],
    [
      "doogie-howser-m.d.-season-2-of-4-xvid-avi",
      "DOOGIE HOWSER, M.D. - S02E14 - Presumed Guilty",
      "Doogie Howser, M.D. - S02E14 - Presumed Guilty.mp4",
    ],
    [
      "doogie-howser-m.d.-season-2-of-4-xvid-avi",
      "DOOGIE HOWSER, M.D. - S02E15 - To Live and Die in Brentwood",
      "Doogie Howser, M.D. - S02E15 - To Live and Die in Brentwood.mp4",
    ],
    [
      "doogie-howser-m.d.-season-2-of-4-xvid-avi",
      "DOOGIE HOWSER, M.D. - S02E16 - Air Doogie",
      "Doogie Howser, M.D. - S02E16 - Air Doogie.mp4",
    ],
    [
      "doogie-howser-m.d.-season-2-of-4-xvid-avi",
      "DOOGIE HOWSER, M.D. - S02E17 - A Life in Progress",
      "Doogie Howser, M.D. - S02E17 - A Life in Progress.mp4",
    ],
    [
      "doogie-howser-m.d.-season-2-of-4-xvid-avi",
      "DOOGIE HOWSER, M.D. - S02E18 - My Two Dads",
      "Doogie Howser, M.D. - S02E18 - My Two Dads.mp4",
    ],
    [
      "doogie-howser-m.d.-season-2-of-4-xvid-avi",
      "DOOGIE HOWSER, M.D. - S02E19 - Nobody Expects the Spanish Inquisition",
      "Doogie Howser, M.D. - S02E19 - Nobody Expects the Spanish Inquisition.mp4",
    ],
    [
      "doogie-howser-m.d.-season-2-of-4-xvid-avi",
      "DOOGIE HOWSER, M.D. - S02E20 - Fatal Distraction",
      "Doogie Howser, M.D. - S02E20 - Fatal Distraction.mp4",
    ],
    [
      "doogie-howser-m.d.-season-2-of-4-xvid-avi",
      "DOOGIE HOWSER, M.D. - S02E21 - The Doctor, the Wife, Her Son and the Job",
      "Doogie Howser, M.D. - S02E21 - The Doctor, The Wife, Her Son, and The Job.mp4",
    ],
    [
      "doogie-howser-m.d.-season-2-of-4-xvid-avi",
      "DOOGIE HOWSER, M.D. - S02E22 - Planet of the Dateless",
      "Doogie Howser, M.D. - S02E22 - Planet of the Dateless.mp4",
    ],
    [
      "doogie-howser-m.d.-season-2-of-4-xvid-avi",
      "DOOGIE HOWSER, M.D. - S02E23 - Doogie's Wager",
      "Doogie Howser, M.D. - S02E23 - Doogie's Wager.mp4",
    ],
    [
      "doogie-howser-m.d.-season-2-of-4-xvid-avi",
      "DOOGIE HOWSER, M.D. - S02E24 - A Kiss Ain't Just a Kiss",
      "Doogie Howser, M.D. - S02E24 - A Kiss Ain't Just a Kiss.mp4",
    ],
    [
      "doogie-howser-m.d.-season-2-of-4-xvid-avi",
      "DOOGIE HOWSER, M.D. - S02E25 - Dances with Wanda",
      "Doogie Howser, M.D. - S02E25 - Dances with Wanda.mp4",
    ],
    [
      "doogie-howser-m.d.-season-3-of-4-xvid-avi",
      "DOOGIE HOWSER, M.D. - S03E01 - The Summer of '91",
      "Doogie Howser, M.D. - S03E01 - The Summer of '91.mp4",
    ],
    [
      "doogie-howser-m.d.-season-3-of-4-xvid-avi",
      "DOOGIE HOWSER, M.D. - S03E02 - Doogie Has Left the Building: Part 1",
      "Doogie Howser, M.D. - S03E02 - Doogie Has Left the Building (Part 1).mp4",
    ],
    [
      "doogie-howser-m.d.-season-3-of-4-xvid-avi",
      "DOOGIE HOWSER, M.D. - S03E03 - Doogie Has Left the Building: Part 2",
      "Doogie Howser, M.D. - S03E03 - Doogie Has Left the Building (Part 2).mp4",
    ],
    [
      "doogie-howser-m.d.-season-3-of-4-xvid-avi",
      "DOOGIE HOWSER, M.D. - S03E04 - It's a Darn Shaman",
      "Doogie Howser, M.D. - S03E04 - It's a Damn Shaman.mp4",
    ],
    [
      "doogie-howser-m.d.-season-3-of-4-xvid-avi",
      "DOOGIE HOWSER, M.D. - S03E05 - The Cheese Stands Alone",
      "Doogie Howser, M.D. - S03E05 - The Cheese Stands Alone.mp4",
    ],
    [
      "doogie-howser-m.d.-season-3-of-4-xvid-avi",
      "DOOGIE HOWSER, M.D. - S03E06 - Lonesome Doog",
      "Doogie Howser, M.D. - S03E06 - Lonesome Doog.mp4",
    ],
    [
      "doogie-howser-m.d.-season-3-of-4-xvid-avi",
      "DOOGIE HOWSER, M.D. - S03E07 - When Doogie Comes Marching Home",
      "Doogie Howser, M.D. - S03E07 - When Doogie Comes Marching Home.mp4",
    ],
    [
      "doogie-howser-m.d.-season-3-of-4-xvid-avi",
      "DOOGIE HOWSER, M.D. - S03E08 - Doogstruck",
      "Doogie Howser, M.D. - S03E08 - Doogstruck.mp4",
    ],
    [
      "doogie-howser-m.d.-season-3-of-4-xvid-avi",
      "DOOGIE HOWSER, M.D. - S03E09 - Room and Broad",
      "Doogie Howser, M.D. - S03E09 - Room and Broad.mp4",
    ],
    [
      "doogie-howser-m.d.-season-3-of-4-xvid-avi",
      "DOOGIE HOWSER, M.D. - S03E10 - Doogiesomething",
      "Doogie Howser, M.D. - S03E10 - Doogiesomething.mp4",
    ],
    [
      "doogie-howser-m.d.-season-3-of-4-xvid-avi",
      "DOOGIE HOWSER, M.D. - S03E11 - Truth and Consequences",
      "Doogie Howser, M.D. - S03E11 - Truth and Consequences.mp4",
    ],
    [
      "doogie-howser-m.d.-season-3-of-4-xvid-avi",
      "DOOGIE HOWSER, M.D. - S03E12 - It's a Wonderful Laugh",
      "Doogie Howser, M.D. - S03E12 - It's a Wonderful Laugh.mp4",
    ],
    [
      "doogie-howser-m.d.-season-3-of-4-xvid-avi",
      "DOOGIE HOWSER, M.D. - S03E13 - Dangerous Reunions",
      "Doogie Howser, M.D. - S03E13 - Dangerous Reunions.mp4",
    ],
    [
      "doogie-howser-m.d.-season-3-of-4-xvid-avi",
      "DOOGIE HOWSER, M.D. - S03E14 - Mummy Dearest",
      "Doogie Howser, M.D. - S03E14 - Mummy Dearest.mp4",
    ],
    [
      "doogie-howser-m.d.-season-3-of-4-xvid-avi",
      "DOOGIE HOWSER, M.D. - S03E15 - Double Doogie with Cheese",
      "Doogie Howser, M.D. - S03E15 - Double Doogie with Cheese.mp4",
    ],
    [
      "doogie-howser-m.d.-season-3-of-4-xvid-avi",
      "DOOGIE HOWSER, M.D. - S03E16 - The Show Mustn't Go On",
      "Doogie Howser, M.D. - S03E16 - The Show Musn't Go On.mp4",
    ],
    [
      "doogie-howser-m.d.-season-3-of-4-xvid-avi",
      "DOOGIE HOWSER, M.D. - S03E17 - If This Is Adulthood, I'd Rather Be in Philadelphia",
      "Doogie Howser, M.D. - S03E17 - If This Is Adulthood, I'd Rather Be in Philadelphia.mp4",
    ],
    [
      "doogie-howser-m.d.-season-3-of-4-xvid-avi",
      "DOOGIE HOWSER, M.D. - S03E18 - What You See Ain't Necessarily What You Get",
      "Doogie Howser, M.D. - S03E18 - What You See Ain't Necessarily What You Get.mp4",
    ],
    [
      "doogie-howser-m.d.-season-3-of-4-xvid-avi",
      "DOOGIE HOWSER, M.D. - S03E19 - My Father, Myself",
      "Doogie Howser, M.D. - S03E19 - My Father, My Self.mp4",
    ],
    [
      "doogie-howser-m.d.-season-3-of-4-xvid-avi",
      "DOOGIE HOWSER, M.D. - S03E20 - Educating Janine",
      "Doogie Howser, M.D. - S03E20 - Educating Janine.mp4",
    ],
    [
      "doogie-howser-m.d.-season-3-of-4-xvid-avi",
      "DOOGIE HOWSER, M.D. - S03E21 - Son of the Desert",
      "Doogie Howser, M.D. - S03E21 - Sons of the Desert.mp4",
    ],
    [
      "doogie-howser-m.d.-season-3-of-4-xvid-avi",
      "DOOGIE HOWSER, M.D. - S03E22 - That's What Friends Are For",
      "Doogie Howser, M.D. - S03E22 - That's What Friends Are For.mp4",
    ],
    [
      "doogie-howser-m.d.-season-3-of-4-xvid-avi",
      "DOOGIE HOWSER, M.D. - S03E23 - Thanks for the Memories",
      "Doogie Howser, M.D. - S03E23 - Thanks for the Memories.mp4",
    ],
    [
      "doogie-howser-m.d.-season-3-of-4-xvid-avi",
      "DOOGIE HOWSER, M.D. - S03E24 - Club Medicine",
      "Doogie Howser, M.D. - S03E24 - Club Medicine.mp4",
    ],
    [
      "doogie-howser-m.d.-season-4-of-4-xvid-avi",
      "DOOGIE HOWSER, M.D. - S04E01 - There's a Riot Going On",
      "Doogie Howser, M.D. - S04E01 - There's a Riot Going On.mp4",
    ],
    [
      "doogie-howser-m.d.-season-4-of-4-xvid-avi",
      "DOOGIE HOWSER, M.D. - S04E02 - Look Ma, No Pants",
      "Doogie Howser, M.D. - S04E02 - Look Ma, No Pants.mp4",
    ],
    [
      "doogie-howser-m.d.-season-4-of-4-xvid-avi",
      "DOOGIE HOWSER, M.D. - S04E03 - Doogie Got a Gun",
      "Doogie Howser, M.D. - S04E03 - Doogie Got a Gun.mp4",
    ],
    [
      "doogie-howser-m.d.-season-4-of-4-xvid-avi",
      "DOOGIE HOWSER, M.D. - S04E04 - Doogie Doesn't Live Here Anymore",
      "Doogie Howser, M.D. - S04E04 - Doogie Doesn't Live Here Anymore.mp4",
    ],
    [
      "doogie-howser-m.d.-season-4-of-4-xvid-avi",
      "DOOGIE HOWSER, M.D. - S04E05 - The Patient in Spite of Himself",
      "Doogie Howser, M.D. - S04E05 - The Patient in Spite of Himself.mp4",
    ],
    [
      "doogie-howser-m.d.-season-4-of-4-xvid-avi",
      "DOOGIE HOWSER, M.D. - S04E06 - To Err is Human, to Give Up Isn't a Bad Idea",
      "Doogie Howser, M.D. - S04E06 - To Err is Human, to Give Up Isn't a Bad Idea.mp4",
    ],
    [
      "doogie-howser-m.d.-season-4-of-4-xvid-avi",
      "DOOGIE HOWSER, M.D. - S04E07 - Doogie, Can You Hear Me?",
      "Doogie Howser, M.D. - S04E07 - Doogie, Can You Hear Me.mp4",
    ],
    [
      "doogie-howser-m.d.-season-4-of-4-xvid-avi",
      "DOOGIE HOWSER, M.D. - S04E08 - Nothing Compares 2 U",
      "Doogie Howser, M.D. - S04E08 - Nothing Compares 2 U.mp4",
    ],
    [
      "doogie-howser-m.d.-season-4-of-4-xvid-avi",
      "DOOGIE HOWSER, M.D. - S04E09 - Do the Right Thing, If You Can Figure Out What It Is",
      "Doogie Howser, M.D. - S04E09 - Do the Right Thing… If You Can Figure Out What It Is.mp4",
    ],
    [
      "doogie-howser-m.d.-season-4-of-4-xvid-avi",
      "DOOGIE HOWSER, M.D. - S04E10 - The Big Sleep ... Not!",
      "Doogie Howser, M.D. - S04E10 - The Big Sleep… Not.mp4",
    ],
    [
      "doogie-howser-m.d.-season-4-of-4-xvid-avi",
      "DOOGIE HOWSER, M.D. - S04E11 - Will the Real Dr. Howser Please Stand Up?",
      "Doogie Howser, M.D. - S04E11 - Will The Real Dr. Howser Please Stand Up.mp4",
    ],
    [
      "doogie-howser-m.d.-season-4-of-4-xvid-avi",
      "DOOGIE HOWSER, M.D. - S04E12 - The Mother of All Fishing Trips",
      "Doogie Howser, M.D. - S04E12 - The Mother of All Fishing Trips.mp4",
    ],
    [
      "doogie-howser-m.d.-season-4-of-4-xvid-avi",
      "DOOGIE HOWSER, M.D. - S04E13 - Roommate with a View",
      "Doogie Howser, M.D. - S04E13 - Roommate with a View.mp4",
    ],
    [
      "doogie-howser-m.d.-season-4-of-4-xvid-avi",
      "DOOGIE HOWSER, M.D. - S04E14 - Spell It... 'M-A-N!'",
      "Doogie Howser, M.D. - S04E14 - Spell it M-A-N.mp4",
    ],
    [
      "doogie-howser-m.d.-season-4-of-4-xvid-avi",
      "DOOGIE HOWSER, M.D. - S04E15 - It's a Tough Job ... But Why Does My Father Have to Do It?",
      "Doogie Howser, M.D. - S04E15 - It's a Tough Job…But Why Does My Father Have To Do It.mp4",
    ],
    [
      "doogie-howser-m.d.-season-4-of-4-xvid-avi",
      "DOOGIE HOWSER, M.D. - S04E16 - The Adventures of Sherlock Howser",
      "Doogie Howser, M.D. - S04E16 - The Adventures of Sherlock Howser.mp4",
    ],
    [
      "doogie-howser-m.d.-season-4-of-4-xvid-avi",
      "DOOGIE HOWSER, M.D. - S04E17 - Love Means Constantly Having to Say You're Sorry",
      "Doogie Howser, M.D. - S04E17 - Love Means Constantly Having to Say You're Sorry.mp4",
    ],
    [
      "doogie-howser-m.d.-season-4-of-4-xvid-avi",
      "DOOGIE HOWSER, M.D. - S04E18 - You've Come a Long Way, Babysitter",
      "Doogie Howser, M.D. - S04E18 - You've Come a Long Way, Babysitter.mp4",
    ],
    [
      "doogie-howser-m.d.-season-4-of-4-xvid-avi",
      "DOOGIE HOWSER, M.D. - S04E19 - Love Makes the World Go 'Round...or Is It Money?",
      "Doogie Howser, M.D. - S04E19 - Love Makes the World Go 'Round… Or Is It Money.mp4",
    ],
    [
      "doogie-howser-m.d.-season-4-of-4-xvid-avi",
      "DOOGIE HOWSER, M.D. - S04E20 - Dorky Housecall, M.D.\"[95]",
      "Doogie Howser, M.D. - S04E20 - Dorky Housecall, MD.mp4",
    ],
    [
      "doogie-howser-m.d.-season-4-of-4-xvid-avi",
      "DOOGIE HOWSER, M.D. - S04E21 - Eleven Angry People...and Vinnie",
      "Doogie Howser, M.D. - S04E21 - Eleven Angry People… And Vinnie.mp4",
    ],
    [
      "doogie-howser-m.d.-season-4-of-4-xvid-avi",
      "DOOGIE HOWSER, M.D. - S04E22 - What Makes Doogie Run",
      "Doogie Howser, M.D. - S04E22 - What Makes Doogie Run.mp4",
    ],
  ],
  durations: {
    "doogie-howser-m.d.-season-1-of-4-xvid-avi::Doogie Howser, M.D. - S01E01 - Pilot.mp4": 1457,
    "doogie-howser-m.d.-season-1-of-4-xvid-avi::Doogie Howser, M.D. - S01E02 - The Ice Queen Cometh.mp4": 1439,
    "doogie-howser-m.d.-season-1-of-4-xvid-avi::Doogie Howser, M.D. - S01E03 - A Stitch Called Wanda.mp4": 1417,
    "doogie-howser-m.d.-season-1-of-4-xvid-avi::Doogie Howser, M.D. - S01E04 - Frisky Business.mp4": 1411,
    "doogie-howser-m.d.-season-1-of-4-xvid-avi::Doogie Howser, M.D. - S01E05 - The Short Goodbye.mp4": 1435,
    "doogie-howser-m.d.-season-1-of-4-xvid-avi::Doogie Howser, M.D. - S01E06 - Simply Irresistible.mp4": 1431,
    "doogie-howser-m.d.-season-1-of-4-xvid-avi::Doogie Howser, M.D. - S01E07 - Vinnie Video Vici.mp4": 1436,
    "doogie-howser-m.d.-season-1-of-4-xvid-avi::Doogie Howser, M.D. - S01E08 - Blood And Remembrance.mp4": 1423,
    "doogie-howser-m.d.-season-1-of-4-xvid-avi::Doogie Howser, M.D. - S01E09 - She Ain't Heavy, She's My Cousin.mp4": 1416,
    "doogie-howser-m.d.-season-1-of-4-xvid-avi::Doogie Howser, M.D. - S01E10 - My Old Man And The Sea.mp4": 1418,
    "doogie-howser-m.d.-season-1-of-4-xvid-avi::Doogie Howser, M.D. - S01E11 - Tonight's The Night.mp4": 1436,
    "doogie-howser-m.d.-season-1-of-4-xvid-avi::Doogie Howser, M.D. - S01E12 - Every Dog Has His Doogie.mp4": 1426,
    "doogie-howser-m.d.-season-1-of-4-xvid-avi::Doogie Howser, M.D. - S01E13 - Doogie The Red-Nosed Reindeer.mp4": 1422,
    "doogie-howser-m.d.-season-1-of-4-xvid-avi::Doogie Howser, M.D. - S01E14 - Greed Is Good.mp4": 1422,
    "doogie-howser-m.d.-season-1-of-4-xvid-avi::Doogie Howser, M.D. - S01E15 - Attack Of The Green-Eyed Monster.mp4": 1422,
    "doogie-howser-m.d.-season-1-of-4-xvid-avi::Doogie Howser, M.D. - S01E16 - It Ain't Over Till Mrs. Howser Sings.mp4": 1426,
    "doogie-howser-m.d.-season-1-of-4-xvid-avi::Doogie Howser, M.D. - S01E17 - Tough Guys Don't Teach.mp4": 1379,
    "doogie-howser-m.d.-season-1-of-4-xvid-avi::Doogie Howser, M.D. - S01E18 - I Never Sold Shower Heads For My Father.mp4": 1412,
    "doogie-howser-m.d.-season-1-of-4-xvid-avi::Doogie Howser, M.D. - S01E19 - Doogie's Awesome, Excellent Adventure.mp4": 1406,
    "doogie-howser-m.d.-season-1-of-4-xvid-avi::Doogie Howser, M.D. - S01E20 - Use A Slurpy, Go To Jail.mp4": 1414,
    "doogie-howser-m.d.-season-1-of-4-xvid-avi::Doogie Howser, M.D. - S01E21 - Whose Mid-Life Crisis Is It Anyway.mp4": 1416,
    "doogie-howser-m.d.-season-1-of-4-xvid-avi::Doogie Howser, M.D. - S01E22 - Vinnie's Blind Date.mp4": 1413,
    "doogie-howser-m.d.-season-1-of-4-xvid-avi::Doogie Howser, M.D. - S01E23 - And The Winner Is.mp4": 1407,
    "doogie-howser-m.d.-season-1-of-4-xvid-avi::Doogie Howser, M.D. - S01E24 - Breaking Up Is Hard To Doogie.mp4": 1422,
    "doogie-howser-m.d.-season-1-of-4-xvid-avi::Doogie Howser, M.D. - S01E25 - The Grass Ain't Always Greener.mp4": 1413,
    "doogie-howser-m.d.-season-1-of-4-xvid-avi::Doogie Howser, M.D. - S01E26 - Frankly, My Dear, I Don't Give A Grand.mp4": 1366,
    "doogie-howser-m.d.-season-2-of-4-xvid-avi::Doogie Howser, M.D. - S02E01 - Doogenstein.mp4": 1408,
    "doogie-howser-m.d.-season-2-of-4-xvid-avi::Doogie Howser, M.D. - S02E02 - Guess Who's Coming to Doogie's.mp4": 1413,
    "doogie-howser-m.d.-season-2-of-4-xvid-avi::Doogie Howser, M.D. - S02E03 - Ask Doctor Doogie.mp4": 1399,
    "doogie-howser-m.d.-season-2-of-4-xvid-avi::Doogie Howser, M.D. - S02E04 - C'est La Vinnie.mp4": 1420,
    "doogie-howser-m.d.-season-2-of-4-xvid-avi::Doogie Howser, M.D. - S02E05 - Car Wars.mp4": 1420,
    "doogie-howser-m.d.-season-2-of-4-xvid-avi::Doogie Howser, M.D. - S02E06 - Doogie Sings the Blues.mp4": 1415,
    "doogie-howser-m.d.-season-2-of-4-xvid-avi::Doogie Howser, M.D. - S02E07 - Academia Nuts.mp4": 1421,
    "doogie-howser-m.d.-season-2-of-4-xvid-avi::Doogie Howser, M.D. - S02E08 - Revenge of the Teenage Dead.mp4": 1418,
    "doogie-howser-m.d.-season-2-of-4-xvid-avi::Doogie Howser, M.D. - S02E09 - Nautilus For Naught.mp4": 1420,
    "doogie-howser-m.d.-season-2-of-4-xvid-avi::Doogie Howser, M.D. - S02E10 - Don't Let the Turkeys Get Down.mp4": 1394,
    "doogie-howser-m.d.-season-2-of-4-xvid-avi::Doogie Howser, M.D. - S02E11 - Oh Very Young.mp4": 1420,
    "doogie-howser-m.d.-season-2-of-4-xvid-avi::Doogie Howser, M.D. - S02E12 - TV or Not TV.mp4": 1394,
    "doogie-howser-m.d.-season-2-of-4-xvid-avi::Doogie Howser, M.D. - S02E13 - A Woman Too Far.mp4": 1419,
    "doogie-howser-m.d.-season-2-of-4-xvid-avi::Doogie Howser, M.D. - S02E14 - Presumed Guilty.mp4": 1409,
    "doogie-howser-m.d.-season-2-of-4-xvid-avi::Doogie Howser, M.D. - S02E15 - To Live and Die in Brentwood.mp4": 1371,
    "doogie-howser-m.d.-season-2-of-4-xvid-avi::Doogie Howser, M.D. - S02E16 - Air Doogie.mp4": 1391,
    "doogie-howser-m.d.-season-2-of-4-xvid-avi::Doogie Howser, M.D. - S02E17 - A Life in Progress.mp4": 1361,
    "doogie-howser-m.d.-season-2-of-4-xvid-avi::Doogie Howser, M.D. - S02E18 - My Two Dads.mp4": 1399,
    "doogie-howser-m.d.-season-2-of-4-xvid-avi::Doogie Howser, M.D. - S02E19 - Nobody Expects the Spanish Inquisition.mp4": 1395,
    "doogie-howser-m.d.-season-2-of-4-xvid-avi::Doogie Howser, M.D. - S02E20 - Fatal Distraction.mp4": 1405,
    "doogie-howser-m.d.-season-2-of-4-xvid-avi::Doogie Howser, M.D. - S02E21 - The Doctor, The Wife, Her Son, and The Job.mp4": 1399,
    "doogie-howser-m.d.-season-2-of-4-xvid-avi::Doogie Howser, M.D. - S02E22 - Planet of the Dateless.mp4": 1397,
    "doogie-howser-m.d.-season-2-of-4-xvid-avi::Doogie Howser, M.D. - S02E23 - Doogie's Wager.mp4": 1389,
    "doogie-howser-m.d.-season-2-of-4-xvid-avi::Doogie Howser, M.D. - S02E24 - A Kiss Ain't Just a Kiss.mp4": 1402,
    "doogie-howser-m.d.-season-2-of-4-xvid-avi::Doogie Howser, M.D. - S02E25 - Dances with Wanda.mp4": 1391,
    "doogie-howser-m.d.-season-3-of-4-xvid-avi::Doogie Howser, M.D. - S03E01 - The Summer of '91.mp4": 1413,
    "doogie-howser-m.d.-season-3-of-4-xvid-avi::Doogie Howser, M.D. - S03E02 - Doogie Has Left the Building (Part 1).mp4": 1349,
    "doogie-howser-m.d.-season-3-of-4-xvid-avi::Doogie Howser, M.D. - S03E03 - Doogie Has Left the Building (Part 2).mp4": 1383,
    "doogie-howser-m.d.-season-3-of-4-xvid-avi::Doogie Howser, M.D. - S03E04 - It's a Damn Shaman.mp4": 1378,
    "doogie-howser-m.d.-season-3-of-4-xvid-avi::Doogie Howser, M.D. - S03E05 - The Cheese Stands Alone.mp4": 1398,
    "doogie-howser-m.d.-season-3-of-4-xvid-avi::Doogie Howser, M.D. - S03E06 - Lonesome Doog.mp4": 1387,
    "doogie-howser-m.d.-season-3-of-4-xvid-avi::Doogie Howser, M.D. - S03E07 - When Doogie Comes Marching Home.mp4": 1404,
    "doogie-howser-m.d.-season-3-of-4-xvid-avi::Doogie Howser, M.D. - S03E08 - Doogstruck.mp4": 1406,
    "doogie-howser-m.d.-season-3-of-4-xvid-avi::Doogie Howser, M.D. - S03E09 - Room and Broad.mp4": 1403,
    "doogie-howser-m.d.-season-3-of-4-xvid-avi::Doogie Howser, M.D. - S03E10 - Doogiesomething.mp4": 1407,
    "doogie-howser-m.d.-season-3-of-4-xvid-avi::Doogie Howser, M.D. - S03E11 - Truth and Consequences.mp4": 1345,
    "doogie-howser-m.d.-season-3-of-4-xvid-avi::Doogie Howser, M.D. - S03E12 - It's a Wonderful Laugh.mp4": 1396,
    "doogie-howser-m.d.-season-3-of-4-xvid-avi::Doogie Howser, M.D. - S03E13 - Dangerous Reunions.mp4": 1387,
    "doogie-howser-m.d.-season-3-of-4-xvid-avi::Doogie Howser, M.D. - S03E14 - Mummy Dearest.mp4": 1319,
    "doogie-howser-m.d.-season-3-of-4-xvid-avi::Doogie Howser, M.D. - S03E15 - Double Doogie with Cheese.mp4": 1303,
    "doogie-howser-m.d.-season-3-of-4-xvid-avi::Doogie Howser, M.D. - S03E16 - The Show Musn't Go On.mp4": 1356,
    "doogie-howser-m.d.-season-3-of-4-xvid-avi::Doogie Howser, M.D. - S03E17 - If This Is Adulthood, I'd Rather Be in Philadelphia.mp4": 1398,
    "doogie-howser-m.d.-season-3-of-4-xvid-avi::Doogie Howser, M.D. - S03E18 - What You See Ain't Necessarily What You Get.mp4": 1401,
    "doogie-howser-m.d.-season-3-of-4-xvid-avi::Doogie Howser, M.D. - S03E19 - My Father, My Self.mp4": 1395,
    "doogie-howser-m.d.-season-3-of-4-xvid-avi::Doogie Howser, M.D. - S03E20 - Educating Janine.mp4": 1392,
    "doogie-howser-m.d.-season-3-of-4-xvid-avi::Doogie Howser, M.D. - S03E21 - Sons of the Desert.mp4": 1403,
    "doogie-howser-m.d.-season-3-of-4-xvid-avi::Doogie Howser, M.D. - S03E22 - That's What Friends Are For.mp4": 1396,
    "doogie-howser-m.d.-season-3-of-4-xvid-avi::Doogie Howser, M.D. - S03E23 - Thanks for the Memories.mp4": 1393,
    "doogie-howser-m.d.-season-3-of-4-xvid-avi::Doogie Howser, M.D. - S03E24 - Club Medicine.mp4": 1407,
    "doogie-howser-m.d.-season-4-of-4-xvid-avi::Doogie Howser, M.D. - S04E01 - There's a Riot Going On.mp4": 1372,
    "doogie-howser-m.d.-season-4-of-4-xvid-avi::Doogie Howser, M.D. - S04E02 - Look Ma, No Pants.mp4": 1391,
    "doogie-howser-m.d.-season-4-of-4-xvid-avi::Doogie Howser, M.D. - S04E03 - Doogie Got a Gun.mp4": 1385,
    "doogie-howser-m.d.-season-4-of-4-xvid-avi::Doogie Howser, M.D. - S04E04 - Doogie Doesn't Live Here Anymore.mp4": 1389,
    "doogie-howser-m.d.-season-4-of-4-xvid-avi::Doogie Howser, M.D. - S04E05 - The Patient in Spite of Himself.mp4": 1402,
    "doogie-howser-m.d.-season-4-of-4-xvid-avi::Doogie Howser, M.D. - S04E06 - To Err is Human, to Give Up Isn't a Bad Idea.mp4": 1373,
    "doogie-howser-m.d.-season-4-of-4-xvid-avi::Doogie Howser, M.D. - S04E07 - Doogie, Can You Hear Me.mp4": 1401,
    "doogie-howser-m.d.-season-4-of-4-xvid-avi::Doogie Howser, M.D. - S04E08 - Nothing Compares 2 U.mp4": 1372,
    "doogie-howser-m.d.-season-4-of-4-xvid-avi::Doogie Howser, M.D. - S04E09 - Do the Right Thing… If You Can Figure Out What It Is.mp4": 1395,
    "doogie-howser-m.d.-season-4-of-4-xvid-avi::Doogie Howser, M.D. - S04E10 - The Big Sleep… Not.mp4": 1400,
    "doogie-howser-m.d.-season-4-of-4-xvid-avi::Doogie Howser, M.D. - S04E11 - Will The Real Dr. Howser Please Stand Up.mp4": 1378,
    "doogie-howser-m.d.-season-4-of-4-xvid-avi::Doogie Howser, M.D. - S04E12 - The Mother of All Fishing Trips.mp4": 1406,
    "doogie-howser-m.d.-season-4-of-4-xvid-avi::Doogie Howser, M.D. - S04E13 - Roommate with a View.mp4": 1343,
    "doogie-howser-m.d.-season-4-of-4-xvid-avi::Doogie Howser, M.D. - S04E14 - Spell it M-A-N.mp4": 1396,
    "doogie-howser-m.d.-season-4-of-4-xvid-avi::Doogie Howser, M.D. - S04E15 - It's a Tough Job…But Why Does My Father Have To Do It.mp4": 1374,
    "doogie-howser-m.d.-season-4-of-4-xvid-avi::Doogie Howser, M.D. - S04E16 - The Adventures of Sherlock Howser.mp4": 1399,
    "doogie-howser-m.d.-season-4-of-4-xvid-avi::Doogie Howser, M.D. - S04E17 - Love Means Constantly Having to Say You're Sorry.mp4": 1392,
    "doogie-howser-m.d.-season-4-of-4-xvid-avi::Doogie Howser, M.D. - S04E18 - You've Come a Long Way, Babysitter.mp4": 1395,
    "doogie-howser-m.d.-season-4-of-4-xvid-avi::Doogie Howser, M.D. - S04E19 - Love Makes the World Go 'Round… Or Is It Money.mp4": 1380,
    "doogie-howser-m.d.-season-4-of-4-xvid-avi::Doogie Howser, M.D. - S04E20 - Dorky Housecall, MD.mp4": 1373,
    "doogie-howser-m.d.-season-4-of-4-xvid-avi::Doogie Howser, M.D. - S04E21 - Eleven Angry People… And Vinnie.mp4": 1384,
    "doogie-howser-m.d.-season-4-of-4-xvid-avi::Doogie Howser, M.D. - S04E22 - What Makes Doogie Run.mp4": 1377,
  },
};
