window.SHOW = {
  id: "NightGallery",
  title: "Night Gallery",
  art: "NightGallery.jpg",
  storageProgressKey: "nightgallery-progress",
  storageSettingsKey: "nightgallery-settings",
  nestedPaths: true,
  grouping: "season",
  segments: "none",
  seasonNames: { 0: "Pilot (1969 TV movie)" },
  incompleteEpisodes: ["S03E16"],
  episodes: [
    ["night-gallery-101-the-cemetery-eyes-the-escape-route", "NIGHT GALLERY - S00E01 - The Cemetery / Eyes / Escape Route",
      "Night Gallery 101 - The Cemetery, Eyes, The Escape Route.ia.mp4"],
    ["night-gallery-101-the-cemetery-eyes-the-escape-route", "NIGHT GALLERY - S01E01 - The Dead Man / The Housekeeper",
      "Night Gallery 102 - The Dead Man.ia.mp4"],
    ["night-gallery-101-the-cemetery-eyes-the-escape-route", "NIGHT GALLERY - S01E02 - Room with a View / The Little Black Bag / The Nature of the Enemy",
      "Night Gallery 103 - Room with a View.ia.mp4"],
    ["night-gallery-101-the-cemetery-eyes-the-escape-route", "NIGHT GALLERY - S01E03 - The House / Certain Shadows on the Wall",
      "Night Gallery 104 - The House, Certain Shadows on the Wall.ia.mp4"],
    ["night-gallery-101-the-cemetery-eyes-the-escape-route", "NIGHT GALLERY - S01E04 - Make Me Laugh / Clean Kills and Other Trophies",
      "Night Gallery 105 - Make Me Laugh.mp4"],
    ["night-gallery-101-the-cemetery-eyes-the-escape-route", "NIGHT GALLERY - S01E05 - Pamela's Voice / Lone Survivor / The Doll",
      "Night Gallery 106 - Pamela's Voice.ia.mp4"],
    ["night-gallery-101-the-cemetery-eyes-the-escape-route", "NIGHT GALLERY - S01E06 - They're Tearing Down Tim Riley's Bar / The Last Laurel",
      "Night Gallery 107 - They're Tearing Down Tim Riley's Bar.ia.mp4"],
    ["night-gallery-101-the-cemetery-eyes-the-escape-route", "NIGHT GALLERY - S02E01 - The Boy Who Predicted Earthquakes / Miss Lovecraft Sent Me / The Hand of Borgus Weems / Phantom of What Opera?",
      "Night Gallery 201 - The Boy Who Predicted Earthquakes.ia.mp4"],
    ["night-gallery-101-the-cemetery-eyes-the-escape-route", "NIGHT GALLERY - S02E02 - Death in the Family / The Merciful / Class of '99 / Witches' Feast",
      "Night Gallery 202 - A Death in the Family.ia.mp4"],
    ["night-gallery-101-the-cemetery-eyes-the-escape-route", "NIGHT GALLERY - S02E03 - Since Aunt Ada Came to Stay / With Apologies to Mr. Hyde / The Flip-Side of Satan",
      "Night Gallery 203 - Since Aunt Ada Came to Stay.ia.mp4"],
    ["night-gallery-101-the-cemetery-eyes-the-escape-route", "NIGHT GALLERY - S02E04 - A Fear of Spiders / Junior / Marmalade Wine / The Academy",
      "Night Gallery 204 - A Fear of Spiders.ia.mp4"],
    ["night-gallery-101-the-cemetery-eyes-the-escape-route", "NIGHT GALLERY - S02E05 - The Phantom Farmhouse / Silent Snow, Secret Snow",
      "Night Gallery 205 - The Phantom Farmhouse.ia.mp4"],
    ["night-gallery-101-the-cemetery-eyes-the-escape-route", "NIGHT GALLERY - S02E06 - A Question of Fear / The Devil Is Not Mocked",
      "Night Gallery 206 - A Question of Fear.ia.mp4"],
    ["night-gallery-101-the-cemetery-eyes-the-escape-route", "NIGHT GALLERY - S02E07 - Midnight Never Ends / Brenda",
      "Night Gallery 207 - Midnight Never Ends.ia.mp4"],
    ["night-gallery-101-the-cemetery-eyes-the-escape-route", "NIGHT GALLERY - S02E08 - The Diary / A Matter of Semantics / Big Surprise / Professor Peabody's Last Lecture",
      "Night Gallery 208 - The Diary.ia.mp4"],
    ["night-gallery-101-the-cemetery-eyes-the-escape-route", "NIGHT GALLERY - S02E09 - House—With Ghost / A Midnight Visit to the Neighborhood Blood Bank / Dr. Stringfellow's Rejuvenator / Hell's Bells",
      "Night Gallery 209 - House with Ghost.ia.mp4"],
    ["night-gallery-101-the-cemetery-eyes-the-escape-route", "NIGHT GALLERY - S02E10 - The Dark Boy / Keep in Touch—We'll Think of Something",
      "Night Gallery 210 - The Dark Boy.ia.mp4"],
    ["night-gallery-101-the-cemetery-eyes-the-escape-route", "NIGHT GALLERY - S02E11 - Pickman's Model / The Dear Departed / An Act of Chivalry",
      "Night Gallery 211 - Pickman's Model.ia.mp4"],
    ["night-gallery-101-the-cemetery-eyes-the-escape-route", "NIGHT GALLERY - S02E12 - Cool Air / Camera Obscura / Quoth the Raven",
      "Night Gallery 212 - Cool Air.ia.mp4"],
    ["night-gallery-101-the-cemetery-eyes-the-escape-route", "NIGHT GALLERY - S02E13 - The Messiah on Mott Street / The Painted Mirror",
      "Night Gallery 213 - The Messiah on Mott Street.ia.mp4"],
    ["night-gallery-101-the-cemetery-eyes-the-escape-route", "NIGHT GALLERY - S02E14 - The Different Ones / Tell David… / Logoda's Heads",
      "Night Gallery 214 - The Different Ones.ia.mp4"],
    ["night-gallery-101-the-cemetery-eyes-the-escape-route", "NIGHT GALLERY - S02E15 - Green Fingers / The Funeral / The Tune in Dan's Café",
      "Night Gallery 215 - Green Fingers.ia.mp4"],
    ["night-gallery-101-the-cemetery-eyes-the-escape-route", "NIGHT GALLERY - S02E16 - Lindemann's Catch / The Late Mr. Peddington / A Feast of Blood",
      "Night Gallery 216 - Lindemann's Catch.ia.mp4"],
    ["night-gallery-101-the-cemetery-eyes-the-escape-route", "NIGHT GALLERY - S02E17 - The Miracle at Camafeo / The Ghost of Sorworth Place",
      "Night Gallery 217 - The Miracle at Camafeo.ia.mp4"],
    ["night-gallery-101-the-cemetery-eyes-the-escape-route", "NIGHT GALLERY - S02E18 - The Waiting Room / Last Rites for a Dead Druid",
      "Night Gallery 218 - The Waiting Room.ia.mp4"],
    ["night-gallery-101-the-cemetery-eyes-the-escape-route", "NIGHT GALLERY - S02E19 - Deliveries in the Rear / Stop Killing Me / Dead Weight",
      "Night Gallery 219 - Deliveries in the Rear.ia.mp4"],
    ["night-gallery-101-the-cemetery-eyes-the-escape-route", "NIGHT GALLERY - S02E20 - I'll Never Leave You—Ever / There Aren't Anymore MacBanes",
      "Night Gallery 220 - I'll Never Leave You—Ever.ia.mp4"],
    ["night-gallery-101-the-cemetery-eyes-the-escape-route", "NIGHT GALLERY - S02E21 - The Sins of the Fathers / You Can't Get Help Like That Anymore",
      "Night Gallery 221 - The Sins of the Fathers.ia.mp4"],
    ["night-gallery-101-the-cemetery-eyes-the-escape-route", "NIGHT GALLERY - S02E22 - The Caterpillar / Little Girl Lost",
      "Night Gallery 222 - The Caterpillar.ia.mp4"],
    ["night-gallery-101-the-cemetery-eyes-the-escape-route", "NIGHT GALLERY - S03E01 - The Return of the Sorcerer",
      "Night Gallery 301 - Return of the Sorcerer.ia.mp4"],
    ["night-gallery-101-the-cemetery-eyes-the-escape-route", "NIGHT GALLERY - S03E02 - The Girl with the Hungry Eyes",
      "Night Gallery 302 - The Girl with the Hungry Eyes.ia.mp4"],
    ["night-gallery-101-the-cemetery-eyes-the-escape-route", "NIGHT GALLERY - S03E03 - Rare Objects",
      "Night Gallery 303 - Rare Objects.ia.mp4"],
    ["night-gallery-101-the-cemetery-eyes-the-escape-route", "NIGHT GALLERY - S03E04 - Spectre in Tap-Shoes",
      "Night Gallery 304 - Spectre in Tap-Shoes.ia.mp4"],
    ["night-gallery-101-the-cemetery-eyes-the-escape-route", "NIGHT GALLERY - S03E05 - You Can Come Up Now, Mrs. Millikan / Smile, Please",
      "Night Gallery 305 - You Can Come Up Now, Mrs Millikan.ia.mp4"],
    ["night-gallery-101-the-cemetery-eyes-the-escape-route", "NIGHT GALLERY - S03E06 - The Other Way Out",
      "Night Gallery 306 - The Other Way Out.ia.mp4"],
    ["night-gallery-101-the-cemetery-eyes-the-escape-route", "NIGHT GALLERY - S03E07 - Fright Night",
      "Night Gallery 307 - Fright Night.ia.mp4"],
    ["night-gallery-101-the-cemetery-eyes-the-escape-route", "NIGHT GALLERY - S03E08 - Finnegan's Flight",
      "Night Gallery 308 - Finnegan's Flight.ia.mp4"],
    ["night-gallery-101-the-cemetery-eyes-the-escape-route", "NIGHT GALLERY - S03E09 - She'll Be Company for You",
      "Night Gallery 309 - She'll be Company for You.ia.mp4"],
    ["night-gallery-101-the-cemetery-eyes-the-escape-route", "NIGHT GALLERY - S03E10 - The Ring with the Red Velvet Ropes",
      "Night Gallery 310 - The Ring with the Red Velvet Ropes.ia.mp4"],
    ["night-gallery-101-the-cemetery-eyes-the-escape-route", "NIGHT GALLERY - S03E11 - Something in the Woodwork",
      "Night Gallery 311 - Something in the Woodwork.ia.mp4"],
    ["night-gallery-101-the-cemetery-eyes-the-escape-route", "NIGHT GALLERY - S03E12 - Death on a Barge",
      "Night Gallery 312 - Death on a Barge.ia.mp4"],
    ["night-gallery-101-the-cemetery-eyes-the-escape-route", "NIGHT GALLERY - S03E13 - Whisper",
      "Night Gallery 313 - Whisper.ia.mp4"],
    ["night-gallery-101-the-cemetery-eyes-the-escape-route", "NIGHT GALLERY - S03E14 - The Doll of Death",
      "Night Gallery 314 - The Doll of Death.ia.mp4"],
    ["night-gallery-101-the-cemetery-eyes-the-escape-route", "NIGHT GALLERY - S03E15 - Hatred unto Death / How to Cure the Common Vampire",
      "Night Gallery 315 - Hatred Unto Death .ia.mp4"],
    ["night-gallery-101-the-cemetery-eyes-the-escape-route", "NIGHT GALLERY - S03E16 - Die Now, Pay Later",
      "Night Gallery 316 - Die Now, Pay Later.ia.mp4"],
  ],
  durations: {
    "night-gallery-101-the-cemetery-eyes-the-escape-route::Night Gallery 101 - The Cemetery, Eyes, The Escape Route.ia.mp4": 5864,
    "night-gallery-101-the-cemetery-eyes-the-escape-route::Night Gallery 102 - The Dead Man.ia.mp4": 3047,
    "night-gallery-101-the-cemetery-eyes-the-escape-route::Night Gallery 103 - Room with a View.ia.mp4": 3045,
    "night-gallery-101-the-cemetery-eyes-the-escape-route::Night Gallery 104 - The House, Certain Shadows on the Wall.ia.mp4": 3050,
    "night-gallery-101-the-cemetery-eyes-the-escape-route::Night Gallery 105 - Make Me Laugh.mp4": 3045,
    "night-gallery-101-the-cemetery-eyes-the-escape-route::Night Gallery 106 - Pamela's Voice.ia.mp4": 3045,
    "night-gallery-101-the-cemetery-eyes-the-escape-route::Night Gallery 107 - They're Tearing Down Tim Riley's Bar.ia.mp4": 3043,
    "night-gallery-101-the-cemetery-eyes-the-escape-route::Night Gallery 201 - The Boy Who Predicted Earthquakes.ia.mp4": 3056,
    "night-gallery-101-the-cemetery-eyes-the-escape-route::Night Gallery 202 - A Death in the Family.ia.mp4": 3052,
    "night-gallery-101-the-cemetery-eyes-the-escape-route::Night Gallery 203 - Since Aunt Ada Came to Stay.ia.mp4": 3056,
    "night-gallery-101-the-cemetery-eyes-the-escape-route::Night Gallery 204 - A Fear of Spiders.ia.mp4": 3056,
    "night-gallery-101-the-cemetery-eyes-the-escape-route::Night Gallery 205 - The Phantom Farmhouse.ia.mp4": 3048,
    "night-gallery-101-the-cemetery-eyes-the-escape-route::Night Gallery 206 - A Question of Fear.ia.mp4": 3055,
    "night-gallery-101-the-cemetery-eyes-the-escape-route::Night Gallery 207 - Midnight Never Ends.ia.mp4": 3055,
    "night-gallery-101-the-cemetery-eyes-the-escape-route::Night Gallery 208 - The Diary.ia.mp4": 3057,
    "night-gallery-101-the-cemetery-eyes-the-escape-route::Night Gallery 209 - House with Ghost.ia.mp4": 3054,
    "night-gallery-101-the-cemetery-eyes-the-escape-route::Night Gallery 210 - The Dark Boy.ia.mp4": 3057,
    "night-gallery-101-the-cemetery-eyes-the-escape-route::Night Gallery 211 - Pickman's Model.ia.mp4": 3057,
    "night-gallery-101-the-cemetery-eyes-the-escape-route::Night Gallery 212 - Cool Air.ia.mp4": 3045,
    "night-gallery-101-the-cemetery-eyes-the-escape-route::Night Gallery 213 - The Messiah on Mott Street.ia.mp4": 3055,
    "night-gallery-101-the-cemetery-eyes-the-escape-route::Night Gallery 214 - The Different Ones.ia.mp4": 3055,
    "night-gallery-101-the-cemetery-eyes-the-escape-route::Night Gallery 215 - Green Fingers.ia.mp4": 3074,
    "night-gallery-101-the-cemetery-eyes-the-escape-route::Night Gallery 216 - Lindemann's Catch.ia.mp4": 3056,
    "night-gallery-101-the-cemetery-eyes-the-escape-route::Night Gallery 217 - The Miracle at Camafeo.ia.mp4": 3057,
    "night-gallery-101-the-cemetery-eyes-the-escape-route::Night Gallery 218 - The Waiting Room.ia.mp4": 3054,
    "night-gallery-101-the-cemetery-eyes-the-escape-route::Night Gallery 219 - Deliveries in the Rear.ia.mp4": 3056,
    "night-gallery-101-the-cemetery-eyes-the-escape-route::Night Gallery 220 - I'll Never Leave You—Ever.ia.mp4": 3057,
    "night-gallery-101-the-cemetery-eyes-the-escape-route::Night Gallery 221 - The Sins of the Fathers.ia.mp4": 3058,
    "night-gallery-101-the-cemetery-eyes-the-escape-route::Night Gallery 222 - The Caterpillar.ia.mp4": 3059,
    "night-gallery-101-the-cemetery-eyes-the-escape-route::Night Gallery 301 - Return of the Sorcerer.ia.mp4": 1554,
    "night-gallery-101-the-cemetery-eyes-the-escape-route::Night Gallery 302 - The Girl with the Hungry Eyes.ia.mp4": 1555,
    "night-gallery-101-the-cemetery-eyes-the-escape-route::Night Gallery 303 - Rare Objects.ia.mp4": 1551,
    "night-gallery-101-the-cemetery-eyes-the-escape-route::Night Gallery 304 - Spectre in Tap-Shoes.ia.mp4": 1555,
    "night-gallery-101-the-cemetery-eyes-the-escape-route::Night Gallery 305 - You Can Come Up Now, Mrs Millikan.ia.mp4": 1555,
    "night-gallery-101-the-cemetery-eyes-the-escape-route::Night Gallery 306 - The Other Way Out.ia.mp4": 1555,
    "night-gallery-101-the-cemetery-eyes-the-escape-route::Night Gallery 307 - Fright Night.ia.mp4": 1555,
    "night-gallery-101-the-cemetery-eyes-the-escape-route::Night Gallery 308 - Finnegan's Flight.ia.mp4": 1555,
    "night-gallery-101-the-cemetery-eyes-the-escape-route::Night Gallery 309 - She'll be Company for You.ia.mp4": 1557,
    "night-gallery-101-the-cemetery-eyes-the-escape-route::Night Gallery 310 - The Ring with the Red Velvet Ropes.ia.mp4": 1556,
    "night-gallery-101-the-cemetery-eyes-the-escape-route::Night Gallery 311 - Something in the Woodwork.ia.mp4": 1556,
    "night-gallery-101-the-cemetery-eyes-the-escape-route::Night Gallery 312 - Death on a Barge.ia.mp4": 1556,
    "night-gallery-101-the-cemetery-eyes-the-escape-route::Night Gallery 313 - Whisper.ia.mp4": 1554,
    "night-gallery-101-the-cemetery-eyes-the-escape-route::Night Gallery 314 - The Doll of Death.ia.mp4": 1554,
    "night-gallery-101-the-cemetery-eyes-the-escape-route::Night Gallery 315 - Hatred Unto Death .ia.mp4": 1554,
    "night-gallery-101-the-cemetery-eyes-the-escape-route::Night Gallery 316 - Die Now, Pay Later.ia.mp4": 793,
  },
};
