window.SHOW = {
  id: "BlessThisHouse",
  title: "Bless This House",
  art: "BlessThisHouse.jpg",
  storageProgressKey: "blessthishouse-progress",
  storageSettingsKey: "blessthishouse-settings",
  nestedPaths: true,
  grouping: "season",
  segments: "none",
  episodes: [
  ["bless-this-house-1995-epds", "BLESS THIS HOUSE - S01E01 - Pilot",
    "Bless This House S01E01 Pilot.ia.mp4"],
  ["bless-this-house-1995-epds", "BLESS THIS HOUSE - S01E02 - A Woman's Work is Never Done",
    "Bless This House S01E02 A Woman's Work Is Never Done.ia.mp4"],
  ["bless-this-house-1995-epds", "BLESS THIS HOUSE - S01E03 - Company Loves Misery",
    "Bless This House S01E03 Company Loves Misery.ia.mp4"],
  ["bless-this-house-1995-epds", "BLESS THIS HOUSE - S01E04 - A Date Which Will Live in Infamy",
    "Bless This House S01E04 A Date Which Will Live in Infamy.ia.mp4"],
  ["bless-this-house-1995-epds", "BLESS THIS HOUSE - S01E05 - I Am Not My Sister's Keeper",
    "Bless This House S01E05 I Am Not My Sister's Keeper.ia.mp4"],
  ["bless-this-house-1995-epds", "BLESS THIS HOUSE - S01E06 - Where There's Smoke, You're Fired",
    "Bless This House S01E06 Where There's Smoke, You're Fired.ia.mp4"],
  ["bless-this-house-1995-epds", "BLESS THIS HOUSE - S01E07 - The Road to Hell is Paved with Good Intentions",
    "Bless This House S01E07 The Road to Hell Is Paved With Good Intentions.ia.mp4"],
  ["bless-this-house-1995-epds", "BLESS THIS HOUSE - S01E08 - A Fight a Day Keeps the Doctor Away",
    "Bless This House S01E08 A Fight a Day Keeps the Doctor Away.ia.mp4"],
  ["bless-this-house-1995-epds", "BLESS THIS HOUSE - S01E09 - Fish and Guests Stink After Three Days",
    "Bless This House S01E09 Fish and Guests Stink After Three Days.ia.mp4"],
  ["bless-this-house-1995-epds", "BLESS THIS HOUSE - S01E10 - The Postman Always Moves Twice",
    "Bless This House S01E10 The Postman Always Moves Twice.ia.mp4"],
  ["bless-this-house-1995-epds", "BLESS THIS HOUSE - S01E11 - Neither a Borrower Nor a Landlord Be",
    "Bless This House S01E11 Neither a Borrower Nor a Landlord Be.ia.mp4"],
  ["bless-this-house-1995-epds", "BLESS THIS HOUSE - S01E12 - If It Ain't Broke, Break It",
    "Bless This House S01E12 If It Ain't Broke, Break It.ia.mp4"],
  ["bless-this-house-1995-epds", "BLESS THIS HOUSE - S01E13 - Misery on 34th Street",
    "Bless This House S01E13 Misery on 34th Street.ia.mp4"],
  ["bless-this-house-1995-epds", "BLESS THIS HOUSE - S01E14 - The Bowling Method",
    "Bless This House S01E14 The Bowling Method.ia.mp4"],
  ["bless-this-house-1995-epds", "BLESS THIS HOUSE - S01E15 - One Man's Ceiling is Another Man's Stereo",
    "Bless This House S01E15 One Man's Ceiling Is Another Man's Stereo.ia.mp4"],
  ["bless-this-house-1995-epds", "BLESS THIS HOUSE - S01E16 - Natural Born Parents",
    "Bless This House S01E16 Natural Born Parents.ia.mp4"],
  ["bless-this-house-complete-series-1971", "BLESS THIS HOUSE - S02E01 - Bless This House Two Heads Are Better Than One",
    "Bless This House - S02E01 - Two Heads Are Better Than One.mp4"],
  ["bless-this-house-complete-series-1971", "BLESS THIS HOUSE - S02E02 - Bless This House Love Me, Love My Tree",
    "Bless This House - S02E02 - Love Me, Love My Tree.mp4"],
  ["bless-this-house-complete-series-1971", "BLESS THIS HOUSE - S02E03 - Bless This House It's All In The Mind",
    "Bless This House - S02E03 - It's All In The Mind.mp4"],
  ["bless-this-house-complete-series-1971", "BLESS THIS HOUSE - S02E04 - Bless This House Another Lost Weekend",
    "Bless This House - S02E04 - Another Lost Weekend.mp4"],
  ["bless-this-house-complete-series-1971", "BLESS THIS HOUSE - S02E05 - Bless This House Parents Should Be Seen And Not Heard",
    "Bless This House - S02E05 - Parents Should Be Seen And Not Heard.mp4"],
  ["bless-this-house-complete-series-1971", "BLESS THIS HOUSE - S02E06 - Bless This House Strangers In The Night",
    "Bless This House - S02E06 - Strangers In The Night.mp4"],
  ["bless-this-house-complete-series-1971", "BLESS THIS HOUSE - S02E07 - Bless This House Get Me To The Match On Time",
    "Bless This House - S02E07 - Get Me To The Match On Time.mp4"],
  ["bless-this-house-complete-series-1971", "BLESS THIS HOUSE - S02E08 - Bless This House Wives And Lovers",
    "Bless This House - S02E08 - Wives And Lovers.mp4"],
  ["bless-this-house-complete-series-1971", "BLESS THIS HOUSE - S02E09 - Bless This House Never Again On Sunday",
    "Bless This House - S02E09 - Never Again On Sunday.mp4"],
  ["bless-this-house-complete-series-1971", "BLESS THIS HOUSE - S02E10 - Bless This House People In Glass Houses",
    "Bless This House - S02E10 - People In Glass Houses....mp4"],
  ["bless-this-house-complete-series-1971", "BLESS THIS HOUSE - S02E11 - Bless This House A Rolls By Any Other Name",
    "Bless This House - S02E11 - A Rolls By Any Other Name.mp4"],
  ["bless-this-house-complete-series-1971", "BLESS THIS HOUSE - S02E12 - Bless This House A Touch Of The Unknown",
    "Bless This House - S02E12 - A Touch Of The Unknown.mp4"],
  ["bless-this-house-complete-series-1971", "BLESS THIS HOUSE - S03E01 - Bless This House It Comes To Us All In The End",
    "Bless This House - S03E01 - It Comes To Us All In The End.mp4"],
  ["bless-this-house-complete-series-1971", "BLESS THIS HOUSE - S03E02 - Bless This House Tea For Two And Four For Tea",
    "Bless This House - S03E02 - Tea For Two And Four For Tea.mp4"],
  ["bless-this-house-complete-series-1971", "BLESS THIS HOUSE - S03E03 - Bless This House To Tell Or Not To Tell",
    "Bless This House - S03E03 - To Tell Or Not To Tell.mp4"],
  ["bless-this-house-complete-series-1971", "BLESS THIS HOUSE - S03E04 - Bless This House Blood Is Thicker Than Water",
    "Bless This House - S03E04 - Blood Is Thicker Than Water.mp4"],
  ["bless-this-house-complete-series-1971", "BLESS THIS HOUSE - S03E05 - Bless This House One Good Turn Deserves A Bother",
    "Bless This House - S03E05 - One Good Turn Deserves A Bother.mp4"],
  ["bless-this-house-complete-series-1971", "BLESS THIS HOUSE - S03E06 - Bless This House The Loneliness Of The Short Distance Walker",
    "Bless This House - S03E06 - The Loneliness Of The Short Distance Walker.mp4"],
  ["bless-this-house-complete-series-1971", "BLESS THIS HOUSE - S03E07 - Bless This House Watch The Birdie",
    "Bless This House - S03E07 - Watch The Birdie.mp4"],
  ["bless-this-house-complete-series-1971", "BLESS THIS HOUSE - S03E08 - Bless This House Atishoo! Atishoo! We All Fall Down",
    "Bless This House - S03E08 - Atishoo! Atishoo! We All Fall Down.mp4"],
  ["bless-this-house-complete-series-1971", "BLESS THIS HOUSE - S03E09 - Bless This House Entente Not So Cordiale",
    "Bless This House - S03E09 - Entente Not So Cordiale.mp4"],
  ["bless-this-house-complete-series-1971", "BLESS THIS HOUSE - S03E10 - Bless This House Will The Real Sid Abbott Please Stand Up",
    "Bless This House - S03E10 - Will The Real Sid Abbott Please Stand Up.mp4"],
  ["bless-this-house-complete-series-1971", "BLESS THIS HOUSE - S03E11 - Bless This House I'm Not Jealous, I'll Kill Him",
    "Bless This House - S03E11 - I'm Not Jealous, I'll Kill Him.mp4"],
  ["bless-this-house-complete-series-1971", "BLESS THIS HOUSE - S03E12 - Bless This House A Girl's Worst Friend Is Her Father",
    "Bless This House - S03E12 - A Girl's Worst Friend Is Her Father.mp4"],
  ["bless-this-house-complete-series-1971", "BLESS THIS HOUSE - S04E01 - Bless This House Money Is The Root Of",
    "Bless This House - S04E01 - Money Is The Root Of....mp4"],
  ["bless-this-house-complete-series-1971", "BLESS THIS HOUSE - S04E02 - Bless This House And They Will Come Home",
    "Bless This House - S04E02 - And They Will Come Home....mp4"],
  ["bless-this-house-complete-series-1971", "BLESS THIS HOUSE - S04E03 - Bless This House Who's Minding The Baby",
    "Bless This House - S04E03 - Who's Minding The Baby.mp4"],
  ["bless-this-house-complete-series-1971", "BLESS THIS HOUSE - S04E04 - Bless This House A Beef In His Bonnet",
    "Bless This House - S04E04 - A Beef In His Bonnet.mp4"],
  ["bless-this-house-complete-series-1971", "BLESS THIS HOUSE - S04E05 - Bless This House The Bells Are Ringing",
    "Bless This House - S04E05 - The Bells Are Ringing.mp4"],
  ["bless-this-house-complete-series-1971", "BLESS THIS HOUSE - S04E06 - Bless This House The First 25 Years Are The Worst",
    "Bless This House - S04E06 - The First 25 Years Are The Worst.mp4"],
  ["bless-this-house-complete-series-1971", "BLESS THIS HOUSE - S05E01 - Bless This House They Don't Write Songs Like That Anymore",
    "Bless This House - S05E01 - They Don't Write Songs Like That Anymore.mp4"],
  ["bless-this-house-complete-series-1971", "BLESS THIS HOUSE - S05E02 - Bless This House The Gypsy's Warning",
    "Bless This House - S05E02 - The Gypsy's Warning.mp4"],
  ["bless-this-house-complete-series-1971", "BLESS THIS HOUSE - S05E03 - Bless This House The Biggest Woodworm in the World",
    "Bless This House - S05E03 - The Biggest Woodworm in the World.mp4"],
  ["bless-this-house-complete-series-1971", "BLESS THIS HOUSE - S05E04 - Bless This House Home Tweet Home",
    "Bless This House - S05E04 - Home Tweet Home.mp4"],
  ["bless-this-house-complete-series-1971", "BLESS THIS HOUSE - S05E05 - Bless This House You're Never Too Old To Be Young",
    "Bless This House - S05E05 - You're Never Too Old To Be Young.mp4"],
  ["bless-this-house-complete-series-1971", "BLESS THIS HOUSE - S05E06 - Bless This House The Policeman, The Paint And The Pirates",
    "Bless This House - S05E06 - The Policeman, The Paint And The Pirates.mp4"],
  ["bless-this-house-complete-series-1971", "BLESS THIS HOUSE - S05E07 - Bless This House Happy Birthday Sid",
    "Bless This House - S05E07 - Happy Birthday Sid.mp4"],
  ["bless-this-house-complete-series-1971", "BLESS THIS HOUSE - S05E08 - Bless This House Freedom Is",
    "Bless This House - S05E08 - Freedom Is....mp4"],
  ["bless-this-house-complete-series-1971", "BLESS THIS HOUSE - S05E09 - Bless This House 'Mr Chairman",
    "Bless This House - S05E09 - 'Mr Chairman...'.mp4"],
  ["bless-this-house-complete-series-1971", "BLESS THIS HOUSE - S05E10 - Bless This House ...And Afterwards At",
    "Bless This House - S05E10 - ...And Afterwards At....mp4"],
  ["bless-this-house-complete-series-1971", "BLESS THIS HOUSE - S06E01 - Bless This House The Frozen Limit",
    "Bless This House - S06E01 - The Frozen Limit.mp4"],
  ["bless-this-house-complete-series-1971", "BLESS THIS HOUSE - S06E02 - Bless This House Beautiful Dreamer",
    "Bless This House - S06E02 - Beautiful Dreamer.mp4"],
  ["bless-this-house-complete-series-1971", "BLESS THIS HOUSE - S06E03 - Bless This House Fish With Everything",
    "Bless This House - S06E03 - Fish With Everything.mp4"],
  ["bless-this-house-complete-series-1971", "BLESS THIS HOUSE - S06E04 - Bless This House The Naked Paperhanger",
    "Bless This House - S06E04 - The Naked Paperhanger.mp4"],
  ["bless-this-house-complete-series-1971", "BLESS THIS HOUSE - S06E05 - Bless This House Remember Me",
    "Bless This House - S06E05 - Remember Me.mp4"],
  ["bless-this-house-complete-series-1971", "BLESS THIS HOUSE - S06E06 - Bless This House Something Of Value",
    "Bless This House - S06E06 - Something Of Value.mp4"],
  ["bless-this-house-complete-series-1971", "BLESS THIS HOUSE - S06E07 - Bless This House Men Of Consequence",
    "Bless This House - S06E07 - Men Of Consequence.mp4"],
  ["bless-this-house-complete-series-1971", "BLESS THIS HOUSE - S06E08 - Bless This House Skin Deep",
    "Bless This House - S06E08 - Skin Deep.mp4"],
  ["bless-this-house-complete-series-1971", "BLESS THIS HOUSE - S06E09 - Bless This House Friends And Neighbours",
    "Bless This House - S06E09 - Friends And Neighbours.mp4"],
  ["bless-this-house-complete-series-1971", "BLESS THIS HOUSE - S06E10 - Bless This House Well, Well, Well",
    "Bless This House - S06E10 - Well, Well, Well....mp4"],
  ["bless-this-house-complete-series-1971", "BLESS THIS HOUSE - S06E11 - Bless This House The Phantom Pools Winner",
    "Bless This House - S06E11 - The Phantom Pools Winner.mp4"],
  ["bless-this-house-complete-series-1971", "BLESS THIS HOUSE - S06E12 - Bless This House A Matter Of Principle",
    "Bless This House - S06E12 - A Matter Of Principle.mp4"],
  ["bless-this-house-complete-series-1971", "BLESS THIS HOUSE - S06E13 - Bless This House Some Enchanted Evening",
    "Bless This House - S06E13 - Some Enchanted Evening.mp4"],
  ["bless-this-house-complete-series-1971", "BLESS THIS HOUSE - S07E01 - Bless This House All This and Christmas Too",
    "Bless This House - S07E01 - All This and Christmas Too.mp4"],
],
  durations: {
  "bless-this-house-1995-epds::Bless This House S01E01 Pilot.ia.mp4": 1267,
  "bless-this-house-1995-epds::Bless This House S01E02 A Woman's Work Is Never Done.ia.mp4": 1362,
  "bless-this-house-1995-epds::Bless This House S01E03 Company Loves Misery.ia.mp4": 1286,
  "bless-this-house-1995-epds::Bless This House S01E04 A Date Which Will Live in Infamy.ia.mp4": 1260,
  "bless-this-house-1995-epds::Bless This House S01E05 I Am Not My Sister's Keeper.ia.mp4": 1358,
  "bless-this-house-1995-epds::Bless This House S01E06 Where There's Smoke, You're Fired.ia.mp4": 1358,
  "bless-this-house-1995-epds::Bless This House S01E07 The Road to Hell Is Paved With Good Intentions.ia.mp4": 1297,
  "bless-this-house-1995-epds::Bless This House S01E08 A Fight a Day Keeps the Doctor Away.ia.mp4": 1358,
  "bless-this-house-1995-epds::Bless This House S01E09 Fish and Guests Stink After Three Days.ia.mp4": 1309,
  "bless-this-house-1995-epds::Bless This House S01E10 The Postman Always Moves Twice.ia.mp4": 1358,
  "bless-this-house-1995-epds::Bless This House S01E11 Neither a Borrower Nor a Landlord Be.ia.mp4": 1318,
  "bless-this-house-1995-epds::Bless This House S01E12 If It Ain't Broke, Break It.ia.mp4": 1297,
  "bless-this-house-1995-epds::Bless This House S01E13 Misery on 34th Street.ia.mp4": 1357,
  "bless-this-house-1995-epds::Bless This House S01E14 The Bowling Method.ia.mp4": 1327,
  "bless-this-house-1995-epds::Bless This House S01E15 One Man's Ceiling Is Another Man's Stereo.ia.mp4": 1317,
  "bless-this-house-1995-epds::Bless This House S01E16 Natural Born Parents.ia.mp4": 1307,
  "bless-this-house-complete-series-1971::Bless This House - S02E01 - Two Heads Are Better Than One.mp4": 1568,
  "bless-this-house-complete-series-1971::Bless This House - S02E02 - Love Me, Love My Tree.mp4": 1567,
  "bless-this-house-complete-series-1971::Bless This House - S02E03 - It's All In The Mind.mp4": 1422,
  "bless-this-house-complete-series-1971::Bless This House - S02E04 - Another Lost Weekend.mp4": 1594,
  "bless-this-house-complete-series-1971::Bless This House - S02E05 - Parents Should Be Seen And Not Heard.mp4": 1447,
  "bless-this-house-complete-series-1971::Bless This House - S02E06 - Strangers In The Night.mp4": 1523,
  "bless-this-house-complete-series-1971::Bless This House - S02E07 - Get Me To The Match On Time.mp4": 1581,
  "bless-this-house-complete-series-1971::Bless This House - S02E08 - Wives And Lovers.mp4": 1422,
  "bless-this-house-complete-series-1971::Bless This House - S02E09 - Never Again On Sunday.mp4": 1516,
  "bless-this-house-complete-series-1971::Bless This House - S02E10 - People In Glass Houses....mp4": 1426,
  "bless-this-house-complete-series-1971::Bless This House - S02E11 - A Rolls By Any Other Name.mp4": 1518,
  "bless-this-house-complete-series-1971::Bless This House - S02E12 - A Touch Of The Unknown.mp4": 1426,
  "bless-this-house-complete-series-1971::Bless This House - S03E01 - It Comes To Us All In The End.mp4": 1562,
  "bless-this-house-complete-series-1971::Bless This House - S03E02 - Tea For Two And Four For Tea.mp4": 1542,
  "bless-this-house-complete-series-1971::Bless This House - S03E03 - To Tell Or Not To Tell.mp4": 1395,
  "bless-this-house-complete-series-1971::Bless This House - S03E04 - Blood Is Thicker Than Water.mp4": 1517,
  "bless-this-house-complete-series-1971::Bless This House - S03E05 - One Good Turn Deserves A Bother.mp4": 1589,
  "bless-this-house-complete-series-1971::Bless This House - S03E06 - The Loneliness Of The Short Distance Walker.mp4": 1523,
  "bless-this-house-complete-series-1971::Bless This House - S03E07 - Watch The Birdie.mp4": 1518,
  "bless-this-house-complete-series-1971::Bless This House - S03E08 - Atishoo! Atishoo! We All Fall Down.mp4": 1441,
  "bless-this-house-complete-series-1971::Bless This House - S03E09 - Entente Not So Cordiale.mp4": 1555,
  "bless-this-house-complete-series-1971::Bless This House - S03E10 - Will The Real Sid Abbott Please Stand Up.mp4": 1500,
  "bless-this-house-complete-series-1971::Bless This House - S03E11 - I'm Not Jealous, I'll Kill Him.mp4": 1466,
  "bless-this-house-complete-series-1971::Bless This House - S03E12 - A Girl's Worst Friend Is Her Father.mp4": 1535,
  "bless-this-house-complete-series-1971::Bless This House - S04E01 - Money Is The Root Of....mp4": 1571,
  "bless-this-house-complete-series-1971::Bless This House - S04E02 - And They Will Come Home....mp4": 1582,
  "bless-this-house-complete-series-1971::Bless This House - S04E03 - Who's Minding The Baby.mp4": 1514,
  "bless-this-house-complete-series-1971::Bless This House - S04E04 - A Beef In His Bonnet.mp4": 1549,
  "bless-this-house-complete-series-1971::Bless This House - S04E05 - The Bells Are Ringing.mp4": 1539,
  "bless-this-house-complete-series-1971::Bless This House - S04E06 - The First 25 Years Are The Worst.mp4": 1519,
  "bless-this-house-complete-series-1971::Bless This House - S05E01 - They Don't Write Songs Like That Anymore.mp4": 1509,
  "bless-this-house-complete-series-1971::Bless This House - S05E02 - The Gypsy's Warning.mp4": 1276,
  "bless-this-house-complete-series-1971::Bless This House - S05E03 - The Biggest Woodworm in the World.mp4": 1531,
  "bless-this-house-complete-series-1971::Bless This House - S05E04 - Home Tweet Home.mp4": 1475,
  "bless-this-house-complete-series-1971::Bless This House - S05E05 - You're Never Too Old To Be Young.mp4": 1491,
  "bless-this-house-complete-series-1971::Bless This House - S05E06 - The Policeman, The Paint And The Pirates.mp4": 1475,
  "bless-this-house-complete-series-1971::Bless This House - S05E07 - Happy Birthday Sid.mp4": 1299,
  "bless-this-house-complete-series-1971::Bless This House - S05E08 - Freedom Is....mp4": 1451,
  "bless-this-house-complete-series-1971::Bless This House - S05E09 - 'Mr Chairman...'.mp4": 1353,
  "bless-this-house-complete-series-1971::Bless This House - S05E10 - ...And Afterwards At....mp4": 1454,
  "bless-this-house-complete-series-1971::Bless This House - S06E01 - The Frozen Limit.mp4": 1544,
  "bless-this-house-complete-series-1971::Bless This House - S06E02 - Beautiful Dreamer.mp4": 1519,
  "bless-this-house-complete-series-1971::Bless This House - S06E03 - Fish With Everything.mp4": 1469,
  "bless-this-house-complete-series-1971::Bless This House - S06E04 - The Naked Paperhanger.mp4": 1522,
  "bless-this-house-complete-series-1971::Bless This House - S06E05 - Remember Me.mp4": 1431,
  "bless-this-house-complete-series-1971::Bless This House - S06E06 - Something Of Value.mp4": 1503,
  "bless-this-house-complete-series-1971::Bless This House - S06E07 - Men Of Consequence.mp4": 1396,
  "bless-this-house-complete-series-1971::Bless This House - S06E08 - Skin Deep.mp4": 1476,
  "bless-this-house-complete-series-1971::Bless This House - S06E09 - Friends And Neighbours.mp4": 1488,
  "bless-this-house-complete-series-1971::Bless This House - S06E10 - Well, Well, Well....mp4": 1436,
  "bless-this-house-complete-series-1971::Bless This House - S06E11 - The Phantom Pools Winner.mp4": 1475,
  "bless-this-house-complete-series-1971::Bless This House - S06E12 - A Matter Of Principle.mp4": 1515,
  "bless-this-house-complete-series-1971::Bless This House - S06E13 - Some Enchanted Evening.mp4": 1414,
  "bless-this-house-complete-series-1971::Bless This House - S07E01 - All This and Christmas Too.mp4": 3119,
},
};
