window.SHOW = {
  id: "WorldsWildestPoliceVideos",
  title: "World's Wildest Police Videos",
  art: "WorldsWildestPoliceVideos.jpg",
  storageProgressKey: "worldswildestpolicevideos-progress",
  storageSettingsKey: "worldswildestpolicevideos-settings",
  nestedPaths: true,
  grouping: "season",
  segments: "none",
  episodes: [
  ["WWPVTheCompleteOriginalSeries", "WORLD'S WILDEST POLICE VIDEOS - S01E01 - Episode 1",
    "S00x01 - World's Scariest Police Chases (1997).mp4"],
  ["WWPVTheCompleteOriginalSeries", "WORLD'S WILDEST POLICE VIDEOS - S01E02 - Episode 2",
    "S00x02 - World's Scariest Police Chases 2 (1997).mp4"],
  ["WWPVTheCompleteOriginalSeries", "WORLD'S WILDEST POLICE VIDEOS - S01E03 - Episode 3",
    "S00x03 - World's Scariest Police Chases 3 (1997).mp4"],
  ["WWPVTheCompleteOriginalSeries", "WORLD'S WILDEST POLICE VIDEOS - S01E04 - Episode 4",
    "S00x04 - World's Scariest Police Chases 4 (1998).mp4"],
  ["WWPVTheCompleteOriginalSeries", "WORLD'S WILDEST POLICE VIDEOS - S01E05 - Episode 5",
    "S00x05 - World's Scariest Police Chases 5 (1998).mp4"],
  ["WWPVTheCompleteOriginalSeries", "WORLD'S WILDEST POLICE VIDEOS - S01E06 - Episode 6",
    "S00x06 - World's Scariest Police Chases 6 (1999).mp4"],
  ["WWPVTheCompleteOriginalSeries", "WORLD'S WILDEST POLICE VIDEOS - S01E07 - Untitled",
    "S00x07 - World's Scariest Police Shootouts (1997).mp4"],
  ["WWPVTheCompleteOriginalSeries", "WORLD'S WILDEST POLICE VIDEOS - S01E08 - Untitled",
    "S00x08 - World's Scariest Police Shootouts 2 (1997).mp4"],
  ["WWPVTheCompleteOriginalSeries", "WORLD'S WILDEST POLICE VIDEOS - S01E09 - Untitled",
    "S00x09 - Surviving the Moment of Impact.mp4"],
  ["WWPVTheCompleteOriginalSeries", "WORLD'S WILDEST POLICE VIDEOS - S01E10 - Untitled",
    "S00x10 - Surviving the Moment of Impact 2 (1998).mp4"],
  ["WWPVTheCompleteOriginalSeries", "WORLD'S WILDEST POLICE VIDEOS - S01E11 - Untitled",
    "S00x11 - Surviving the Moment of Impact 3.mp4"],
  ["WWPVTheCompleteOriginalSeries", "WORLD'S WILDEST POLICE VIDEOS - S01E12 - Untitled",
    "S00x12 - Surviving the Moment of Impact 4.mp4"],
  ["WWPVTheCompleteOriginalSeries", "WORLD'S WILDEST POLICE VIDEOS - S01E13 - Untitled",
    "S00x13 - World's Worst Drivers Caught on Tape.mp4"],
  ["WWPVTheCompleteOriginalSeries", "WORLD'S WILDEST POLICE VIDEOS - S01E14 - Untitled",
    "S00x14 - World's Worst Drivers Caught on Tape 2.mp4"],
  ["WWPVTheCompleteOriginalSeries", "WORLD'S WILDEST POLICE VIDEOS - S01E15 - Untitled",
    "S00x15 - World's Worst Drivers Caught on Tape 3.mp4"],
  ["WWPVTheCompleteOriginalSeries", "WORLD'S WILDEST POLICE VIDEOS - S01E16 - Untitled",
    "S00x16 - World's Most Shocking Moments Caught on Tape (1998).ia.mp4"],
  ["WWPVTheCompleteOriginalSeries", "WORLD'S WILDEST POLICE VIDEOS - S01E17 - Untitled",
    "S00x17 - World's Most Shocking Moments Caught on Tape 2 (1999).mp4"],
  ["WWPVTheCompleteOriginalSeries", "WORLD'S WILDEST POLICE VIDEOS - S01E18 - Untitled",
    "S00x18 - World's Most Shocking Moments Caught on Tape 3 (1999).mp4"],
  ["WWPVTheCompleteOriginalSeries", "WORLD'S WILDEST POLICE VIDEOS - S01E19 - Untitled",
    "S00x19 - World's Scariest Police Stings.mp4"],
  ["WWPVTheCompleteOriginalSeries", "WORLD'S WILDEST POLICE VIDEOS - S01E20 - Untitled",
    "S00x20 - Prisoners - Out of Control.mp4"],
  ["WWPVTheCompleteOriginalSeries", "WORLD'S WILDEST POLICE VIDEOS - S01E21 - Untitled",
    "S00x21 - Riots - Mobs Out of Control.mp4"],
  ["WWPVTheCompleteOriginalSeries", "WORLD'S WILDEST POLICE VIDEOS - S01E22 - Untitled",
    "S00x22 - Train Wrecks.mp4"],
  ["WWPVTheCompleteOriginalSeries", "WORLD'S WILDEST POLICE VIDEOS - S01E23 - Untitled",
    "S00x23 - Getting a Ticket in America.mp4"],
  ["WWPVTheCompleteOriginalSeries", "WORLD'S WILDEST POLICE VIDEOS - S01E24 - Untitled",
    "S00x24 - Special Forces.mp4"],
  ["WWPVTheCompleteOriginalSeries", "WORLD'S WILDEST POLICE VIDEOS - S01E25 - Untitled",
    "S00x25 - World's Most Dangerous Police Chases.mp4"],
  ["WWPVTheCompleteOriginalSeries", "WORLD'S WILDEST POLICE VIDEOS - S01E26 - Untitled",
    "S00x26 - World's Fastest Police Chases.mp4"],
  ["WWPVTheCompleteOriginalSeries", "WORLD'S WILDEST POLICE VIDEOS - S01E27 - Untitled",
    "S00x27 - World's Craziest Police Chases.mp4"],
  ["WWPVTheCompleteOriginalSeries", "WORLD'S WILDEST POLICE VIDEOS - S01E28 - Untitled",
    "S01x01 - High Speed Car Chase.mp4"],
  ["WWPVTheCompleteOriginalSeries", "WORLD'S WILDEST POLICE VIDEOS - S01E29 - Untitled",
    "S01x02 - Russian Mafia Footage.mp4"],
  ["WWPVTheCompleteOriginalSeries", "WORLD'S WILDEST POLICE VIDEOS - S01E30 - Untitled",
    "S01x03 - California Riots.mp4"],
  ["WWPVTheCompleteOriginalSeries", "WORLD'S WILDEST POLICE VIDEOS - S01E31 - Untitled",
    "S01x04 - Montana Car Chase.mp4"],
  ["WWPVTheCompleteOriginalSeries", "WORLD'S WILDEST POLICE VIDEOS - S01E32 - Untitled",
    "S01x05 - Riot in Tahiti.mp4"],
  ["WWPVTheCompleteOriginalSeries", "WORLD'S WILDEST POLICE VIDEOS - S01E33 - Untitled",
    "S01x06 - Armed with a Sword.mp4"],
  ["WWPVTheCompleteOriginalSeries", "WORLD'S WILDEST POLICE VIDEOS - S01E34 - Untitled",
    "S02x01 - Longest Prison Riot in History.mp4"],
  ["WWPVTheCompleteOriginalSeries", "WORLD'S WILDEST POLICE VIDEOS - S01E35 - Untitled",
    "S02x02 - Soccer Game Riot.mp4"],
  ["WWPVTheCompleteOriginalSeries", "WORLD'S WILDEST POLICE VIDEOS - S01E36 - Untitled",
    "S02x03 - Armed Standoff.mp4"],
  ["WWPVTheCompleteOriginalSeries", "WORLD'S WILDEST POLICE VIDEOS - S01E37 - Untitled",
    "S02x04 - Riots in Nicaragua.mp4"],
  ["WWPVTheCompleteOriginalSeries", "WORLD'S WILDEST POLICE VIDEOS - S01E38 - Untitled",
    "S02x05 - Amazing Police Chases and Car Crashes.mp4"],
  ["WWPVTheCompleteOriginalSeries", "WORLD'S WILDEST POLICE VIDEOS - S01E39 - Untitled",
    "S02x06 - Massive Fireworks Disaster.mp4"],
  ["WWPVTheCompleteOriginalSeries", "WORLD'S WILDEST POLICE VIDEOS - S01E40 - Untitled",
    "S02x07 - Helicopter Pursuit.mp4"],
  ["WWPVTheCompleteOriginalSeries", "WORLD'S WILDEST POLICE VIDEOS - S01E41 - Untitled",
    "S02x08 - Bank Heist.mp4"],
  ["WWPVTheCompleteOriginalSeries", "WORLD'S WILDEST POLICE VIDEOS - S01E42 - Untitled",
    "S02x09 - ATM Robbery.mp4"],
  ["WWPVTheCompleteOriginalSeries", "WORLD'S WILDEST POLICE VIDEOS - S01E43 - Untitled",
    "S02x10 - Riot at College Football Game.mp4"],
  ["WWPVTheCompleteOriginalSeries", "WORLD'S WILDEST POLICE VIDEOS - S01E44 - Untitled",
    "S02x11 - Riots in Brazil.mp4"],
  ["WWPVTheCompleteOriginalSeries", "WORLD'S WILDEST POLICE VIDEOS - S01E45 - Untitled",
    "S02x12 - Store Robbery Footage.mp4"],
  ["WWPVTheCompleteOriginalSeries", "WORLD'S WILDEST POLICE VIDEOS - S01E46 - Untitled",
    "S02x13 - Hostage Situation Footage.mp4"],
  ["WWPVTheCompleteOriginalSeries", "WORLD'S WILDEST POLICE VIDEOS - S01E47 - Untitled",
    "S02x14 - Hostage Situation in Brazil.mp4"],
  ["WWPVTheCompleteOriginalSeries", "WORLD'S WILDEST POLICE VIDEOS - S01E48 - Untitled",
    "S02x15 - Mugging Footage.mp4"],
  ["WWPVTheCompleteOriginalSeries", "WORLD'S WILDEST POLICE VIDEOS - S01E49 - Untitled",
    "S02x16 - Belligerent Drunk Driver.mp4"],
  ["WWPVTheCompleteOriginalSeries", "WORLD'S WILDEST POLICE VIDEOS - S01E50 - Untitled",
    "S02x17 - Trapped in a Burning Vehicle.mp4"],
  ["WWPVTheCompleteOriginalSeries", "WORLD'S WILDEST POLICE VIDEOS - S01E51 - Untitled",
    "S02x18 - Hate March.mp4"],
  ["WWPVTheCompleteOriginalSeries", "WORLD'S WILDEST POLICE VIDEOS - S01E52 - Untitled",
    "S02x19 - Jumper.mp4"],
  ["WWPVTheCompleteOriginalSeries", "WORLD'S WILDEST POLICE VIDEOS - S01E53 - Untitled",
    "S02x20 - Resisting Arrest.mp4"],
  ["WWPVTheCompleteOriginalSeries", "WORLD'S WILDEST POLICE VIDEOS - S01E54 - Untitled",
    "S03x01 - Brazen Bank Robber.mp4"],
  ["WWPVTheCompleteOriginalSeries", "WORLD'S WILDEST POLICE VIDEOS - S01E55 - Untitled",
    "S03x02 - World's Worst Drivers.mp4"],
  ["WWPVTheCompleteOriginalSeries", "WORLD'S WILDEST POLICE VIDEOS - S01E56 - Untitled",
    "S03x03 - Most Dangerous Crashes.mp4"],
  ["WWPVTheCompleteOriginalSeries", "WORLD'S WILDEST POLICE VIDEOS - S01E57 - Untitled",
    "S03x04 - Football Riot in the Netherlands.mp4"],
  ["WWPVTheCompleteOriginalSeries", "WORLD'S WILDEST POLICE VIDEOS - S01E58 - Untitled",
    "S03x05 - High-Speed Chases.mp4"],
  ["WWPVTheCompleteOriginalSeries", "WORLD'S WILDEST POLICE VIDEOS - S01E59 - Untitled",
    "S03x06 - Grieving Father Attacks His Son's Killers.mp4"],
  ["WWPVTheCompleteOriginalSeries", "WORLD'S WILDEST POLICE VIDEOS - S01E60 - Untitled",
    "S03x07 - Most Dangerous Chases.mp4"],
  ["WWPVTheCompleteOriginalSeries", "WORLD'S WILDEST POLICE VIDEOS - S01E61 - Untitled",
    "S03x08 - Strangest Police Chases.mp4"],
  ["WWPVTheCompleteOriginalSeries", "WORLD'S WILDEST POLICE VIDEOS - S01E62 - Untitled",
    "S03x09 - Arson Footage.mp4"],
  ["WWPVTheCompleteOriginalSeries", "WORLD'S WILDEST POLICE VIDEOS - S01E63 - Untitled",
    "S03x10 - Riots in Australia.mp4"],
  ["WWPVTheCompleteOriginalSeries", "WORLD'S WILDEST POLICE VIDEOS - S01E64 - Untitled",
    "S03x11 - Mailman Hires Hitman.mp4"],
  ["WWPVTheCompleteOriginalSeries", "WORLD'S WILDEST POLICE VIDEOS - S01E65 - Untitled",
    "S03x12 - Riots in Kenya.mp4"],
  ["WWPVTheCompleteOriginalSeries", "WORLD'S WILDEST POLICE VIDEOS - S01E66 - Untitled",
    "S04x01 - Dangerous Crashes and Chases.mp4"],
  ["WWPVTheCompleteOriginalSeries", "WORLD'S WILDEST POLICE VIDEOS - S01E67 - Untitled",
    "S04x02 - Craziest Chases.mp4"],
  ["WWPVTheCompleteOriginalSeries", "WORLD'S WILDEST POLICE VIDEOS - S01E68 - Untitled",
    "S04x03 - Robbers on the Run.mp4"],
  ["WWPVTheCompleteOriginalSeries", "WORLD'S WILDEST POLICE VIDEOS - S01E69 - Untitled",
    "S04x04 - California Police Videos.mp4"],
  ["WWPVTheCompleteOriginalSeries", "WORLD'S WILDEST POLICE VIDEOS - S01E70 - Untitled",
    "S04x05 - Armed Parolee.mp4"],
  ["WWPVTheCompleteOriginalSeries", "WORLD'S WILDEST POLICE VIDEOS - S01E71 - Untitled",
    "S04x06 - Cop Killer.mp4"],
  ["WWPVTheCompleteOriginalSeries", "WORLD'S WILDEST POLICE VIDEOS - S01E72 - Untitled",
    "S04x07 - Wanted Drug Dealer.mp4"],
  ["WWPVTheCompleteOriginalSeries", "WORLD'S WILDEST POLICE VIDEOS - S01E73 - Untitled",
    "S04x08 - Backroad Pursuit.mp4"],
  ["WWPVTheCompleteOriginalSeries", "WORLD'S WILDEST POLICE VIDEOS - S01E74 - Untitled",
    "S04x09 - Liquor Store Robbery Footage.mp4"],
  ["WWPVTheCompleteOriginalSeries", "WORLD'S WILDEST POLICE VIDEOS - S01E75 - Untitled",
    "S04x10 - Truck Theft.mp4"],
  ["WWPVTheCompleteOriginalSeries", "WORLD'S WILDEST POLICE VIDEOS - S01E76 - Untitled",
    "S04x11 - Parole Violation.mp4"],
  ["WWPVTheCompleteOriginalSeries", "WORLD'S WILDEST POLICE VIDEOS - S01E77 - Untitled",
    "S04x12 - Speed in Real Life.mp4"],
  ["WWPVTheCompleteOriginalSeries", "WORLD'S WILDEST POLICE VIDEOS - S01E78 - Untitled",
    "S04x13 - Fleeing Crooks Get Caught.mp4"],
  ["WWPVTheCompleteOriginalSeries", "WORLD'S WILDEST POLICE VIDEOS - S01E79 - Untitled",
    "S04x14 - Nevada Police Chase.mp4"],
  ["WWPVTheCompleteOriginalSeries", "WORLD'S WILDEST POLICE VIDEOS - S01E80 - Untitled",
    "S04x15 - Muggers in Michigan.mp4"],
  ["WWPVTheCompleteOriginalSeries", "WORLD'S WILDEST POLICE VIDEOS - S01E81 - Untitled",
    "S04x16 - Convenience Store Crooks.mp4"],
  ["WWPVTheCompleteOriginalSeries", "WORLD'S WILDEST POLICE VIDEOS - S01E82 - Untitled",
    "S04x17 - Shooting Outside the White House.mp4"],
  ["WWPVTheCompleteOriginalSeries", "WORLD'S WILDEST POLICE VIDEOS - S01E83 - Untitled",
    "S04x18 - Armed Drug Dealer.mp4"],
],
  durations: {
  "WWPVTheCompleteOriginalSeries::S00x01 - World's Scariest Police Chases (1997).mp4": 2672,
  "WWPVTheCompleteOriginalSeries::S00x02 - World's Scariest Police Chases 2 (1997).mp4": 2654,
  "WWPVTheCompleteOriginalSeries::S00x03 - World's Scariest Police Chases 3 (1997).mp4": 2693,
  "WWPVTheCompleteOriginalSeries::S00x04 - World's Scariest Police Chases 4 (1998).mp4": 2723,
  "WWPVTheCompleteOriginalSeries::S00x05 - World's Scariest Police Chases 5 (1998).mp4": 2708,
  "WWPVTheCompleteOriginalSeries::S00x06 - World's Scariest Police Chases 6 (1999).mp4": 2723,
  "WWPVTheCompleteOriginalSeries::S00x07 - World's Scariest Police Shootouts (1997).mp4": 2701,
  "WWPVTheCompleteOriginalSeries::S00x08 - World's Scariest Police Shootouts 2 (1997).mp4": 2729,
  "WWPVTheCompleteOriginalSeries::S00x09 - Surviving the Moment of Impact.mp4": 2725,
  "WWPVTheCompleteOriginalSeries::S00x10 - Surviving the Moment of Impact 2 (1998).mp4": 2660,
  "WWPVTheCompleteOriginalSeries::S00x11 - Surviving the Moment of Impact 3.mp4": 2725,
  "WWPVTheCompleteOriginalSeries::S00x12 - Surviving the Moment of Impact 4.mp4": 2665,
  "WWPVTheCompleteOriginalSeries::S00x13 - World's Worst Drivers Caught on Tape.mp4": 2713,
  "WWPVTheCompleteOriginalSeries::S00x14 - World's Worst Drivers Caught on Tape 2.mp4": 2575,
  "WWPVTheCompleteOriginalSeries::S00x15 - World's Worst Drivers Caught on Tape 3.mp4": 2645,
  "WWPVTheCompleteOriginalSeries::S00x16 - World's Most Shocking Moments Caught on Tape (1998).ia.mp4": 2664,
  "WWPVTheCompleteOriginalSeries::S00x17 - World's Most Shocking Moments Caught on Tape 2 (1999).mp4": 2635,
  "WWPVTheCompleteOriginalSeries::S00x18 - World's Most Shocking Moments Caught on Tape 3 (1999).mp4": 2520,
  "WWPVTheCompleteOriginalSeries::S00x19 - World's Scariest Police Stings.mp4": 2694,
  "WWPVTheCompleteOriginalSeries::S00x20 - Prisoners - Out of Control.mp4": 2695,
  "WWPVTheCompleteOriginalSeries::S00x21 - Riots - Mobs Out of Control.mp4": 2693,
  "WWPVTheCompleteOriginalSeries::S00x22 - Train Wrecks.mp4": 2519,
  "WWPVTheCompleteOriginalSeries::S00x23 - Getting a Ticket in America.mp4": 2665,
  "WWPVTheCompleteOriginalSeries::S00x24 - Special Forces.mp4": 2724,
  "WWPVTheCompleteOriginalSeries::S00x25 - World's Most Dangerous Police Chases.mp4": 2664,
  "WWPVTheCompleteOriginalSeries::S00x26 - World's Fastest Police Chases.mp4": 2663,
  "WWPVTheCompleteOriginalSeries::S00x27 - World's Craziest Police Chases.mp4": 2664,
  "WWPVTheCompleteOriginalSeries::S01x01 - High Speed Car Chase.mp4": 2678,
  "WWPVTheCompleteOriginalSeries::S01x02 - Russian Mafia Footage.mp4": 2711,
  "WWPVTheCompleteOriginalSeries::S01x03 - California Riots.mp4": 2713,
  "WWPVTheCompleteOriginalSeries::S01x04 - Montana Car Chase.mp4": 2714,
  "WWPVTheCompleteOriginalSeries::S01x05 - Riot in Tahiti.mp4": 2706,
  "WWPVTheCompleteOriginalSeries::S01x06 - Armed with a Sword.mp4": 2704,
  "WWPVTheCompleteOriginalSeries::S02x01 - Longest Prison Riot in History.mp4": 2713,
  "WWPVTheCompleteOriginalSeries::S02x02 - Soccer Game Riot.mp4": 2712,
  "WWPVTheCompleteOriginalSeries::S02x03 - Armed Standoff.mp4": 2713,
  "WWPVTheCompleteOriginalSeries::S02x04 - Riots in Nicaragua.mp4": 2712,
  "WWPVTheCompleteOriginalSeries::S02x05 - Amazing Police Chases and Car Crashes.mp4": 2728,
  "WWPVTheCompleteOriginalSeries::S02x06 - Massive Fireworks Disaster.mp4": 2712,
  "WWPVTheCompleteOriginalSeries::S02x07 - Helicopter Pursuit.mp4": 2718,
  "WWPVTheCompleteOriginalSeries::S02x08 - Bank Heist.mp4": 2713,
  "WWPVTheCompleteOriginalSeries::S02x09 - ATM Robbery.mp4": 2713,
  "WWPVTheCompleteOriginalSeries::S02x10 - Riot at College Football Game.mp4": 2711,
  "WWPVTheCompleteOriginalSeries::S02x11 - Riots in Brazil.mp4": 2713,
  "WWPVTheCompleteOriginalSeries::S02x12 - Store Robbery Footage.mp4": 2713,
  "WWPVTheCompleteOriginalSeries::S02x13 - Hostage Situation Footage.mp4": 2713,
  "WWPVTheCompleteOriginalSeries::S02x14 - Hostage Situation in Brazil.mp4": 2713,
  "WWPVTheCompleteOriginalSeries::S02x15 - Mugging Footage.mp4": 2713,
  "WWPVTheCompleteOriginalSeries::S02x16 - Belligerent Drunk Driver.mp4": 2713,
  "WWPVTheCompleteOriginalSeries::S02x17 - Trapped in a Burning Vehicle.mp4": 2713,
  "WWPVTheCompleteOriginalSeries::S02x18 - Hate March.mp4": 2711,
  "WWPVTheCompleteOriginalSeries::S02x19 - Jumper.mp4": 2713,
  "WWPVTheCompleteOriginalSeries::S02x20 - Resisting Arrest.mp4": 2711,
  "WWPVTheCompleteOriginalSeries::S03x01 - Brazen Bank Robber.mp4": 2625,
  "WWPVTheCompleteOriginalSeries::S03x02 - World's Worst Drivers.mp4": 2649,
  "WWPVTheCompleteOriginalSeries::S03x03 - Most Dangerous Crashes.mp4": 2644,
  "WWPVTheCompleteOriginalSeries::S03x04 - Football Riot in the Netherlands.mp4": 2636,
  "WWPVTheCompleteOriginalSeries::S03x05 - High-Speed Chases.mp4": 2648,
  "WWPVTheCompleteOriginalSeries::S03x06 - Grieving Father Attacks His Son's Killers.mp4": 2649,
  "WWPVTheCompleteOriginalSeries::S03x07 - Most Dangerous Chases.mp4": 2647,
  "WWPVTheCompleteOriginalSeries::S03x08 - Strangest Police Chases.mp4": 2648,
  "WWPVTheCompleteOriginalSeries::S03x09 - Arson Footage.mp4": 2648,
  "WWPVTheCompleteOriginalSeries::S03x10 - Riots in Australia.mp4": 2649,
  "WWPVTheCompleteOriginalSeries::S03x11 - Mailman Hires Hitman.mp4": 2635,
  "WWPVTheCompleteOriginalSeries::S03x12 - Riots in Kenya.mp4": 2649,
  "WWPVTheCompleteOriginalSeries::S04x01 - Dangerous Crashes and Chases.mp4": 2583,
  "WWPVTheCompleteOriginalSeries::S04x02 - Craziest Chases.mp4": 2588,
  "WWPVTheCompleteOriginalSeries::S04x03 - Robbers on the Run.mp4": 2588,
  "WWPVTheCompleteOriginalSeries::S04x04 - California Police Videos.mp4": 2589,
  "WWPVTheCompleteOriginalSeries::S04x05 - Armed Parolee.mp4": 2587,
  "WWPVTheCompleteOriginalSeries::S04x06 - Cop Killer.mp4": 2589,
  "WWPVTheCompleteOriginalSeries::S04x07 - Wanted Drug Dealer.mp4": 2649,
  "WWPVTheCompleteOriginalSeries::S04x08 - Backroad Pursuit.mp4": 2646,
  "WWPVTheCompleteOriginalSeries::S04x09 - Liquor Store Robbery Footage.mp4": 2649,
  "WWPVTheCompleteOriginalSeries::S04x10 - Truck Theft.mp4": 2649,
  "WWPVTheCompleteOriginalSeries::S04x11 - Parole Violation.mp4": 2649,
  "WWPVTheCompleteOriginalSeries::S04x12 - Speed in Real Life.mp4": 2662,
  "WWPVTheCompleteOriginalSeries::S04x13 - Fleeing Crooks Get Caught.mp4": 2644,
  "WWPVTheCompleteOriginalSeries::S04x14 - Nevada Police Chase.mp4": 2644,
  "WWPVTheCompleteOriginalSeries::S04x15 - Muggers in Michigan.mp4": 2663,
  "WWPVTheCompleteOriginalSeries::S04x16 - Convenience Store Crooks.mp4": 2647,
  "WWPVTheCompleteOriginalSeries::S04x17 - Shooting Outside the White House.mp4": 2649,
  "WWPVTheCompleteOriginalSeries::S04x18 - Armed Drug Dealer.mp4": 2649,
},
};
