window.SHOW = {
  id: "McHalesNavySeries",
  title: "McHale's Navy Series",
  art: "McHalesNavySeries.jpg",
  storageProgressKey: "mchalesnavyseries-progress",
  storageSettingsKey: "mchalesnavyseries-settings",
  nestedPaths: true,
  grouping: "season",
  segments: "none",
  episodes: [
  ["mc-hales-navy-complete", "MCHALE'S NAVY SERIES - S01E01 - McHales Navy An Ensign for McHale",
    "McHales Navy S1E01 - An Ensign for McHale.mp4"],
  ["mc-hales-navy-complete", "MCHALE'S NAVY SERIES - S01E02 - McHales Navy A Purple Heart for Gruber",
    "McHales Navy S1E02 - A Purple Heart for Gruber.mp4"],
  ["mc-hales-navy-complete", "MCHALE'S NAVY SERIES - S01E03 - McHales Navy McHale and His Seven Cupids",
    "McHales Navy S1E03 - McHale and His Seven Cupids.mp4"],
  ["mc-hales-navy-complete", "MCHALE'S NAVY SERIES - S01E04 - McHales Navy , Where Are You",
    "McHales Navy S1E04 - PT 73, Where Are You.mp4"],
  ["mc-hales-navy-complete", "MCHALE'S NAVY SERIES - S01E05 - McHales Navy Movies Are Your Best Diversion",
    "McHales Navy S1E05 - Movies Are Your Best Diversion.mp4"],
  ["mc-hales-navy-complete", "MCHALE'S NAVY SERIES - S01E06 - McHales Navy Operation Wedding Party",
    "McHales Navy S1E06 - Operation Wedding Party.mp4"],
  ["mc-hales-navy-complete", "MCHALE'S NAVY SERIES - S01E07 - McHales Navy Who Do the Voodoo",
    "McHales Navy S1E07 - Who Do the Voodoo.mp4"],
  ["mc-hales-navy-complete", "MCHALE'S NAVY SERIES - S01E08 - McHales Navy Three Girls on an Island",
    "McHales Navy S1E08 - Three Girls on an Island.mp4"],
  ["mc-hales-navy-complete", "MCHALE'S NAVY SERIES - S01E09 - McHales Navy McHale's Paradise Motel",
    "McHales Navy S1E09 - McHale's Paradise Motel.mp4"],
  ["mc-hales-navy-complete", "MCHALE'S NAVY SERIES - S01E10 - McHales Navy The Battle of McHale's Island",
    "McHales Navy S1E10 - The Battle of McHale's Island.mp4"],
  ["mc-hales-navy-complete", "MCHALE'S NAVY SERIES - S01E11 - McHales Navy The Day They Captured Santa Claus",
    "McHales Navy S1E11 - The Day They Captured Santa Claus.mp4"],
  ["mc-hales-navy-complete", "MCHALE'S NAVY SERIES - S01E12 - McHales Navy Beauty and the Beast",
    "McHales Navy S1E12 - Beauty and the Beast.mp4"],
  ["mc-hales-navy-complete", "MCHALE'S NAVY SERIES - S01E13 - McHales Navy The Captain's Mission",
    "McHales Navy S1E13 - The Captain's Mission.mp4"],
  ["mc-hales-navy-complete", "MCHALE'S NAVY SERIES - S01E14 - McHales Navy Send Us a Hero",
    "McHales Navy S1E14 - Send Us a Hero.mp4"],
  ["mc-hales-navy-complete", "MCHALE'S NAVY SERIES - S01E15 - McHales Navy The Captain Steals a Cook",
    "McHales Navy S1E15 - The Captain Steals a Cook.mp4"],
  ["mc-hales-navy-complete", "MCHALE'S NAVY SERIES - S01E16 - McHales Navy The Ensign Gets a Zero",
    "McHales Navy S1E16 - The Ensign Gets a Zero.mp4"],
  ["mc-hales-navy-complete", "MCHALE'S NAVY SERIES - S01E17 - McHales Navy The Big Raffle",
    "McHales Navy S1E17 - The Big Raffle.mp4"],
  ["mc-hales-navy-complete", "MCHALE'S NAVY SERIES - S01E18 - McHales Navy One of Our Engines Is Missing",
    "McHales Navy S1E18 - One of Our Engines Is Missing.mp4"],
  ["mc-hales-navy-complete", "MCHALE'S NAVY SERIES - S01E19 - McHales Navy The Natives Get Restless",
    "McHales Navy S1E19 - The Natives Get Restless.mp4"],
  ["mc-hales-navy-complete", "MCHALE'S NAVY SERIES - S01E20 - McHales Navy The Confidence Game",
    "McHales Navy S1E20 - The Confidence Game.mp4"],
  ["mc-hales-navy-complete", "MCHALE'S NAVY SERIES - S01E21 - McHales Navy Six Pounds from Paradise",
    "McHales Navy S1E21 - Six Pounds from Paradise.mp4"],
  ["mc-hales-navy-complete", "MCHALE'S NAVY SERIES - S01E22 - McHales Navy Washing Machine Charlie",
    "McHales Navy S1E22 - Washing Machine Charlie.mp4"],
  ["mc-hales-navy-complete", "MCHALE'S NAVY SERIES - S01E23 - McHales Navy Nippon Nancy Calling",
    "McHales Navy S1E23 - Nippon Nancy Calling.mp4"],
  ["mc-hales-navy-complete", "MCHALE'S NAVY SERIES - S01E24 - McHales Navy One Enchanted Weekend",
    "McHales Navy S1E24 - One Enchanted Weekend.mp4"],
  ["mc-hales-navy-complete", "MCHALE'S NAVY SERIES - S01E25 - McHales Navy The Mothers of",
    "McHales Navy S1E25 - The Mothers of PT 73.mp4"],
  ["mc-hales-navy-complete", "MCHALE'S NAVY SERIES - S01E26 - McHales Navy HMS 73",
    "McHales Navy S1E26 - HMS 73.mp4"],
  ["mc-hales-navy-complete", "MCHALE'S NAVY SERIES - S01E27 - McHales Navy A Wreath for McHale",
    "McHales Navy S1E27 - A Wreath for McHale.mp4"],
  ["mc-hales-navy-complete", "MCHALE'S NAVY SERIES - S01E28 - McHales Navy Portrait of a Peerless Leader",
    "McHales Navy S1E28 - Portrait of a Peerless Leader.mp4"],
  ["mc-hales-navy-complete", "MCHALE'S NAVY SERIES - S01E29 - McHales Navy Instant Democracy",
    "McHales Navy S1E29 - Instant Democracy.mp4"],
  ["mc-hales-navy-complete", "MCHALE'S NAVY SERIES - S01E30 - McHales Navy Camera, Action, Panic",
    "McHales Navy S1E30 - Camera, Action, Panic.mp4"],
  ["mc-hales-navy-complete", "MCHALE'S NAVY SERIES - S01E31 - McHales Navy Alias Captain Binghamton",
    "McHales Navy S1E31 - Alias Captain Binghamton.mp4"],
  ["mc-hales-navy-complete", "MCHALE'S NAVY SERIES - S01E32 - McHales Navy Parents Anonymous",
    "McHales Navy S1E32 - Parents Anonymous.mp4"],
  ["mc-hales-navy-complete", "MCHALE'S NAVY SERIES - S01E33 - McHales Navy McHale's Millions",
    "McHales Navy S1E33 - McHale's Millions.mp4"],
  ["mc-hales-navy-complete", "MCHALE'S NAVY SERIES - S01E34 - McHales Navy The Hillbillies of",
    "McHales Navy S1E34 - The Hillbillies of PT 73.mp4"],
  ["mc-hales-navy-complete", "MCHALE'S NAVY SERIES - S01E35 - McHales Navy The Monster of McHale's Island",
    "McHales Navy S1E35 - The Monster of McHale's Island.mp4"],
  ["mc-hales-navy-complete", "MCHALE'S NAVY SERIES - S01E36 - McHales Navy Uncle Admiral",
    "McHales Navy S1E36 - Uncle Admiral.mp4"],
  ["mc-hales-navy-complete", "MCHALE'S NAVY SERIES - S02E01 - McHales Navy The Day the War Stood Still",
    "McHales Navy S2E01 - The Day the War Stood Still.mp4"],
  ["mc-hales-navy-complete", "MCHALE'S NAVY SERIES - S02E02 - McHales Navy The Binghamton Murder Plot",
    "McHales Navy S2E02 - The Binghamton Murder Plot.mp4"],
  ["mc-hales-navy-complete", "MCHALE'S NAVY SERIES - S02E03 - McHales Navy McHale and His Schweinhunds",
    "McHales Navy S2E03 - McHale and His Schweinhunds.mp4"],
  ["mc-hales-navy-complete", "MCHALE'S NAVY SERIES - S02E04 - McHales Navy Is There a Doctor in the Hut",
    "McHales Navy S2E04 - Is There a Doctor in the Hut.mp4"],
  ["mc-hales-navy-complete", "MCHALE'S NAVY SERIES - S02E05 - McHales Navy To Binghamton with Love",
    "McHales Navy S2E05 - To Binghamton with Love.mp4"],
  ["mc-hales-navy-complete", "MCHALE'S NAVY SERIES - S02E06 - McHales Navy Have Kimono, Will Travel",
    "McHales Navy S2E06 - Have Kimono, Will Travel.mp4"],
  ["mc-hales-navy-complete", "MCHALE'S NAVY SERIES - S02E07 - McHales Navy Today I Am a Man",
    "McHales Navy S2E07 - Today I Am a Man!.mp4"],
  ["mc-hales-navy-complete", "MCHALE'S NAVY SERIES - S02E08 - McHales Navy Jolly Wally",
    "McHales Navy S2E08 - Jolly Wally.mp4"],
  ["mc-hales-navy-complete", "MCHALE'S NAVY SERIES - S02E09 - McHales Navy Scuttlebutt",
    "McHales Navy S2E09 - Scuttlebutt.mp4"],
  ["mc-hales-navy-complete", "MCHALE'S NAVY SERIES - S02E10 - McHales Navy The August Teahouse of Quint McHale",
    "McHales Navy S2E10 - The August Teahouse of Quint McHale.mp4"],
  ["mc-hales-navy-complete", "MCHALE'S NAVY SERIES - S02E11 - McHales Navy French Leave for McHale",
    "McHales Navy S2E11 - French Leave for McHale.mp4"],
  ["mc-hales-navy-complete", "MCHALE'S NAVY SERIES - S02E12 - McHales Navy The Happy Sleepwalker",
    "McHales Navy S2E12 - The Happy Sleepwalker.mp4"],
  ["mc-hales-navy-complete", "MCHALE'S NAVY SERIES - S02E13 - McHales Navy A Letter for Fuji",
    "McHales Navy S2E13 - A Letter for Fuji.mp4"],
  ["mc-hales-navy-complete", "MCHALE'S NAVY SERIES - S02E14 - McHales Navy My Ensign, the Lawyer",
    "McHales Navy S2E14 - My Ensign, the Lawyer.mp4"],
  ["mc-hales-navy-complete", "MCHALE'S NAVY SERIES - S02E15 - McHales Navy Orange Blossoms for McHale",
    "McHales Navy S2E15 - Orange Blossoms for McHale.mp4"],
  ["mc-hales-navy-complete", "MCHALE'S NAVY SERIES - S02E16 - McHales Navy The Creature from McHale's Lagoon",
    "McHales Navy S2E16 - The Creature from McHale's Lagoon.mp4"],
  ["mc-hales-navy-complete", "MCHALE'S NAVY SERIES - S02E17 - McHales Navy A Medal for Parker",
    "McHales Navy S2E17 - A Medal for Parker.mp4"],
  ["mc-hales-navy-complete", "MCHALE'S NAVY SERIES - S02E18 - McHales Navy The Balloon Goes Up",
    "McHales Navy S2E18 - The Balloon Goes Up.mp4"],
  ["mc-hales-navy-complete", "MCHALE'S NAVY SERIES - S02E19 - McHales Navy Who'll Buy My Sarongs",
    "McHales Navy S2E19 - Who'll Buy My Sarongs.mp4"],
  ["mc-hales-navy-complete", "MCHALE'S NAVY SERIES - S02E20 - McHales Navy Evil Eye Parker",
    "McHales Navy S2E20 - Evil-Eye Parker.mp4"],
  ["mc-hales-navy-complete", "MCHALE'S NAVY SERIES - S02E21 - McHales Navy The Great Impersonation",
    "McHales Navy S2E21 - The Great Impersonation.mp4"],
  ["mc-hales-navy-complete", "MCHALE'S NAVY SERIES - S02E22 - McHales Navy Urulu's Paradise West",
    "McHales Navy S2E22 - Urulu's Paradise West.mp4"],
  ["mc-hales-navy-complete", "MCHALE'S NAVY SERIES - S02E23 - McHales Navy Dear Diary",
    "McHales Navy S2E23 - Dear Diary.mp4"],
  ["mc-hales-navy-complete", "MCHALE'S NAVY SERIES - S02E24 - McHales Navy Babette Go Home",
    "McHales Navy S2E24 - Babette Go Home.mp4"],
  ["mc-hales-navy-complete", "MCHALE'S NAVY SERIES - S02E25 - McHales Navy The Novocain Mutiny",
    "McHales Navy S2E25 - The Novocain Mutiny.mp4"],
  ["mc-hales-navy-complete", "MCHALE'S NAVY SERIES - S02E26 - McHales Navy Stars Over Taratupa",
    "McHales Navy S2E26 - Stars Over Taratupa.mp4"],
  ["mc-hales-navy-complete", "MCHALE'S NAVY SERIES - S02E27 - McHales Navy Comrades of",
    "McHales Navy S2E27 - Comrades of PT 73.mp4"],
  ["mc-hales-navy-complete", "MCHALE'S NAVY SERIES - S02E34 - McHales Navy Marryin' Chuck",
    "McHales Navy S2E34 - Marryin' Chuck.mp4"],
  ["mc-hales-navy-complete", "MCHALE'S NAVY SERIES - S02E35 - McHales Navy The Dart Gun Wedding",
    "McHales Navy S2E35 - The Dart Gun Wedding.mp4"],
  ["mc-hales-navy-complete", "MCHALE'S NAVY SERIES - S02E36 - McHales Navy A Da Da for Christy",
    "McHales Navy S2E36 - A Da-Da for Christy.mp4"],
  ["mc-hales-navy-complete", "MCHALE'S NAVY SERIES - S04E02 - McHale's Navy The Bathtub Thief",
    "McHale's Navy - 4x02 - The Bathtub Thief.mp4"],
  ["mc-hales-navy-complete", "MCHALE'S NAVY SERIES - S04E03 - McHale's Navy Marriage, McHale Style",
    "McHale's Navy - 4x03 - Marriage, McHale Style.mp4"],
  ["mc-hales-navy-complete", "MCHALE'S NAVY SERIES - S04E04 - McHale's Navy Guiseppe McHale",
    "McHale's Navy - 4x04 - Guiseppe McHale.mp4"],
  ["mc-hales-navy-complete", "MCHALE'S NAVY SERIES - S04E05 - McHale's Navy A Nip in Time",
    "McHale's Navy - 4x05 - A Nip in Time.mp4"],
  ["mc-hales-navy-complete", "MCHALE'S NAVY SERIES - S04E06 - McHale's Navy Piazza Binghamtoni",
    "McHale's Navy - 4x06 - Piazza Binghamtoni.mp4"],
  ["mc-hales-navy-complete", "MCHALE'S NAVY SERIES - S04E07 - McHale's Navy The Bald Headed Contessa",
    "McHale's Navy - 4x07 - The Bald-Headed Contessa.mp4"],
  ["mc-hales-navy-complete", "MCHALE'S NAVY SERIES - S04E08 - McHale's Navy Voltafiore Fish Fry",
    "McHale's Navy - 4x08 - Voltafiore Fish-Fry.mp4"],
  ["mc-hales-navy-complete", "MCHALE'S NAVY SERIES - S04E09 - McHale's Navy A Wine Cellar Is Not a Home",
    "McHale's Navy - 4x09 - A Wine Cellar Is Not a Home.mp4"],
  ["mc-hales-navy-complete", "MCHALE'S NAVY SERIES - S04E10 - McHale's Navy Vino, Vino, Who's Got the Vino",
    "McHale's Navy - 4x10 - Vino, Vino, Who's Got the Vino.mp4"],
  ["mc-hales-navy-complete", "MCHALE'S NAVY SERIES - S04E11 - McHale's Navy The McHale Opera Company",
    "McHale's Navy - 4x11 - The McHale Opera Company.mp4"],
  ["mc-hales-navy-complete", "MCHALE'S NAVY SERIES - S04E12 - McHale's Navy The Good Luck Fountain",
    "McHale's Navy - 4x12 - The Good Luck Fountain.mp4"],
  ["mc-hales-navy-complete", "MCHALE'S NAVY SERIES - S04E13 - McHale's Navy Blitzkrieg at McHale's Beach",
    "McHale's Navy - 4x13 - Blitzkrieg at McHale's Beach.mp4"],
  ["mc-hales-navy-complete", "MCHALE'S NAVY SERIES - S04E14 - McHale's Navy Reunion for",
    "McHale's Navy - 4x14 - Reunion for PT 73.mp4"],
  ["mc-hales-navy-complete", "MCHALE'S NAVY SERIES - S04E15 - McHale's Navy The Return of Guiseppe",
    "McHale's Navy - 4x15 - The Return of Guiseppe.mp4"],
  ["mc-hales-navy-complete", "MCHALE'S NAVY SERIES - S04E16 - McHale's Navy The Boy Scouts of 73",
    "McHale's Navy - 4x16 - The Boy Scouts of 73.mp4"],
  ["mc-hales-navy-complete", "MCHALE'S NAVY SERIES - S04E17 - McHale's Navy Fire in the Liquor Locker",
    "McHale's Navy - 4x17 - Fire in the Liquor Locker.mp4"],
  ["mc-hales-navy-complete", "MCHALE'S NAVY SERIES - S04E18 - McHale's Navy The Fugitive Ensign",
    "McHale's Navy - 4x18 - The Fugitive Ensign.mp4"],
  ["mc-hales-navy-complete", "MCHALE'S NAVY SERIES - S04E19 - McHale's Navy The Wacky WAC",
    "McHale's Navy - 4x19 - The Wacky WAC.mp4"],
  ["mc-hales-navy-complete", "MCHALE'S NAVY SERIES - S04E20 - McHale's Navy La Dolce 73",
    "McHale's Navy - 4x20 - La Dolce 73.mp4"],
  ["mc-hales-navy-complete", "MCHALE'S NAVY SERIES - S04E21 - McHale's Navy McHale's Country Club Caper",
    "McHale's Navy - 4x21 - McHale's Country Club Caper.mp4"],
  ["mc-hales-navy-complete", "MCHALE'S NAVY SERIES - S04E22 - McHale's Navy Secret Chimp 007",
    "McHale's Navy - 4x22 - Secret Chimp 007.mp4"],
  ["mc-hales-navy-complete", "MCHALE'S NAVY SERIES - S04E23 - McHale's Navy",
    "McHale's Navy - 4x23 - 36-24-73.mp4"],
  ["mc-hales-navy-complete", "MCHALE'S NAVY SERIES - S04E24 - McHale's Navy My Son, the Skipper",
    "McHale's Navy - 4x24 - My Son, the Skipper.mp4"],
  ["mc-hales-navy-complete", "MCHALE'S NAVY SERIES - S04E25 - McHale's Navy Little Red Riding Doctor",
    "McHale's Navy - 4x25 - Little Red Riding Doctor.mp4"],
  ["mc-hales-navy-complete", "MCHALE'S NAVY SERIES - S04E26 - McHale's Navy Who Was That German I Saw You With",
    "McHale's Navy - 4x26 - Who Was That German I Saw You With.mp4"],
  ["mc-hales-navy-complete", "MCHALE'S NAVY SERIES - S04E27 - McHale's Navy The McHale Grand Prix",
    "McHale's Navy - 4x27 - The McHale Grand Prix.mp4"],
  ["mc-hales-navy-complete", "MCHALE'S NAVY SERIES - S04E28 - McHale's Navy An Ensign's Best Friend",
    "McHale's Navy - 4x28 - An Ensign's Best Friend.mp4"],
  ["mc-hales-navy-complete", "MCHALE'S NAVY SERIES - S04E29 - McHale's Navy Binghamton, at 20 Paces",
    "McHale's Navy - 4x29 - Binghamton, at 20 Paces.mp4"],
  ["mc-hales-navy-complete", "MCHALE'S NAVY SERIES - S04E30 - McHale's Navy Wally for Congress",
    "McHale's Navy - 4x30 - Wally for Congress.mp4"],
],
  durations: {
  "mc-hales-navy-complete::McHales Navy S1E01 - An Ensign for McHale.mp4": 1525,
  "mc-hales-navy-complete::McHales Navy S1E02 - A Purple Heart for Gruber.mp4": 1534,
  "mc-hales-navy-complete::McHales Navy S1E03 - McHale and His Seven Cupids.mp4": 1546,
  "mc-hales-navy-complete::McHales Navy S1E04 - PT 73, Where Are You.mp4": 1524,
  "mc-hales-navy-complete::McHales Navy S1E05 - Movies Are Your Best Diversion.mp4": 1534,
  "mc-hales-navy-complete::McHales Navy S1E06 - Operation Wedding Party.mp4": 1531,
  "mc-hales-navy-complete::McHales Navy S1E07 - Who Do the Voodoo.mp4": 1536,
  "mc-hales-navy-complete::McHales Navy S1E08 - Three Girls on an Island.mp4": 1538,
  "mc-hales-navy-complete::McHales Navy S1E09 - McHale's Paradise Motel.mp4": 1535,
  "mc-hales-navy-complete::McHales Navy S1E10 - The Battle of McHale's Island.mp4": 1535,
  "mc-hales-navy-complete::McHales Navy S1E11 - The Day They Captured Santa Claus.mp4": 1535,
  "mc-hales-navy-complete::McHales Navy S1E12 - Beauty and the Beast.mp4": 1538,
  "mc-hales-navy-complete::McHales Navy S1E13 - The Captain's Mission.mp4": 1537,
  "mc-hales-navy-complete::McHales Navy S1E14 - Send Us a Hero.mp4": 1533,
  "mc-hales-navy-complete::McHales Navy S1E15 - The Captain Steals a Cook.mp4": 1536,
  "mc-hales-navy-complete::McHales Navy S1E16 - The Ensign Gets a Zero.mp4": 1537,
  "mc-hales-navy-complete::McHales Navy S1E17 - The Big Raffle.mp4": 1536,
  "mc-hales-navy-complete::McHales Navy S1E18 - One of Our Engines Is Missing.mp4": 1533,
  "mc-hales-navy-complete::McHales Navy S1E19 - The Natives Get Restless.mp4": 1537,
  "mc-hales-navy-complete::McHales Navy S1E20 - The Confidence Game.mp4": 1535,
  "mc-hales-navy-complete::McHales Navy S1E21 - Six Pounds from Paradise.mp4": 1533,
  "mc-hales-navy-complete::McHales Navy S1E22 - Washing Machine Charlie.mp4": 1538,
  "mc-hales-navy-complete::McHales Navy S1E23 - Nippon Nancy Calling.mp4": 1525,
  "mc-hales-navy-complete::McHales Navy S1E24 - One Enchanted Weekend.mp4": 1535,
  "mc-hales-navy-complete::McHales Navy S1E25 - The Mothers of PT 73.mp4": 1536,
  "mc-hales-navy-complete::McHales Navy S1E26 - HMS 73.mp4": 1534,
  "mc-hales-navy-complete::McHales Navy S1E27 - A Wreath for McHale.mp4": 1535,
  "mc-hales-navy-complete::McHales Navy S1E28 - Portrait of a Peerless Leader.mp4": 1536,
  "mc-hales-navy-complete::McHales Navy S1E29 - Instant Democracy.mp4": 1535,
  "mc-hales-navy-complete::McHales Navy S1E30 - Camera, Action, Panic.mp4": 1538,
  "mc-hales-navy-complete::McHales Navy S1E31 - Alias Captain Binghamton.mp4": 1536,
  "mc-hales-navy-complete::McHales Navy S1E32 - Parents Anonymous.mp4": 1531,
  "mc-hales-navy-complete::McHales Navy S1E33 - McHale's Millions.mp4": 1534,
  "mc-hales-navy-complete::McHales Navy S1E34 - The Hillbillies of PT 73.mp4": 1534,
  "mc-hales-navy-complete::McHales Navy S1E35 - The Monster of McHale's Island.mp4": 1534,
  "mc-hales-navy-complete::McHales Navy S1E36 - Uncle Admiral.mp4": 1534,
  "mc-hales-navy-complete::McHales Navy S2E01 - The Day the War Stood Still.mp4": 1525,
  "mc-hales-navy-complete::McHales Navy S2E02 - The Binghamton Murder Plot.mp4": 1534,
  "mc-hales-navy-complete::McHales Navy S2E03 - McHale and His Schweinhunds.mp4": 1533,
  "mc-hales-navy-complete::McHales Navy S2E04 - Is There a Doctor in the Hut.mp4": 1524,
  "mc-hales-navy-complete::McHales Navy S2E05 - To Binghamton with Love.mp4": 1534,
  "mc-hales-navy-complete::McHales Navy S2E06 - Have Kimono, Will Travel.mp4": 1534,
  "mc-hales-navy-complete::McHales Navy S2E07 - Today I Am a Man!.mp4": 1536,
  "mc-hales-navy-complete::McHales Navy S2E08 - Jolly Wally.mp4": 1536,
  "mc-hales-navy-complete::McHales Navy S2E09 - Scuttlebutt.mp4": 1531,
  "mc-hales-navy-complete::McHales Navy S2E10 - The August Teahouse of Quint McHale.mp4": 1533,
  "mc-hales-navy-complete::McHales Navy S2E11 - French Leave for McHale.mp4": 1531,
  "mc-hales-navy-complete::McHales Navy S2E12 - The Happy Sleepwalker.mp4": 1533,
  "mc-hales-navy-complete::McHales Navy S2E13 - A Letter for Fuji.mp4": 1537,
  "mc-hales-navy-complete::McHales Navy S2E14 - My Ensign, the Lawyer.mp4": 1533,
  "mc-hales-navy-complete::McHales Navy S2E15 - Orange Blossoms for McHale.mp4": 1531,
  "mc-hales-navy-complete::McHales Navy S2E16 - The Creature from McHale's Lagoon.mp4": 1531,
  "mc-hales-navy-complete::McHales Navy S2E17 - A Medal for Parker.mp4": 1530,
  "mc-hales-navy-complete::McHales Navy S2E18 - The Balloon Goes Up.mp4": 1530,
  "mc-hales-navy-complete::McHales Navy S2E19 - Who'll Buy My Sarongs.mp4": 1529,
  "mc-hales-navy-complete::McHales Navy S2E20 - Evil-Eye Parker.mp4": 1527,
  "mc-hales-navy-complete::McHales Navy S2E21 - The Great Impersonation.mp4": 1530,
  "mc-hales-navy-complete::McHales Navy S2E22 - Urulu's Paradise West.mp4": 1526,
  "mc-hales-navy-complete::McHales Navy S2E23 - Dear Diary.mp4": 1528,
  "mc-hales-navy-complete::McHales Navy S2E24 - Babette Go Home.mp4": 1525,
  "mc-hales-navy-complete::McHales Navy S2E25 - The Novocain Mutiny.mp4": 1527,
  "mc-hales-navy-complete::McHales Navy S2E26 - Stars Over Taratupa.mp4": 1527,
  "mc-hales-navy-complete::McHales Navy S2E27 - Comrades of PT 73.mp4": 1528,
  "mc-hales-navy-complete::McHales Navy S2E34 - Marryin' Chuck.mp4": 1531,
  "mc-hales-navy-complete::McHales Navy S2E35 - The Dart Gun Wedding.mp4": 1530,
  "mc-hales-navy-complete::McHales Navy S2E36 - A Da-Da for Christy.mp4": 1530,
  "mc-hales-navy-complete::McHale's Navy - 4x02 - The Bathtub Thief.mp4": 1585,
  "mc-hales-navy-complete::McHale's Navy - 4x03 - Marriage, McHale Style.mp4": 1582,
  "mc-hales-navy-complete::McHale's Navy - 4x04 - Guiseppe McHale.mp4": 1583,
  "mc-hales-navy-complete::McHale's Navy - 4x05 - A Nip in Time.mp4": 1585,
  "mc-hales-navy-complete::McHale's Navy - 4x06 - Piazza Binghamtoni.mp4": 1587,
  "mc-hales-navy-complete::McHale's Navy - 4x07 - The Bald-Headed Contessa.mp4": 1589,
  "mc-hales-navy-complete::McHale's Navy - 4x08 - Voltafiore Fish-Fry.mp4": 1587,
  "mc-hales-navy-complete::McHale's Navy - 4x09 - A Wine Cellar Is Not a Home.mp4": 1586,
  "mc-hales-navy-complete::McHale's Navy - 4x10 - Vino, Vino, Who's Got the Vino.mp4": 1584,
  "mc-hales-navy-complete::McHale's Navy - 4x11 - The McHale Opera Company.mp4": 1587,
  "mc-hales-navy-complete::McHale's Navy - 4x12 - The Good Luck Fountain.mp4": 1587,
  "mc-hales-navy-complete::McHale's Navy - 4x13 - Blitzkrieg at McHale's Beach.mp4": 1588,
  "mc-hales-navy-complete::McHale's Navy - 4x14 - Reunion for PT 73.mp4": 1588,
  "mc-hales-navy-complete::McHale's Navy - 4x15 - The Return of Guiseppe.mp4": 1587,
  "mc-hales-navy-complete::McHale's Navy - 4x16 - The Boy Scouts of 73.mp4": 1587,
  "mc-hales-navy-complete::McHale's Navy - 4x17 - Fire in the Liquor Locker.mp4": 1580,
  "mc-hales-navy-complete::McHale's Navy - 4x18 - The Fugitive Ensign.mp4": 1586,
  "mc-hales-navy-complete::McHale's Navy - 4x19 - The Wacky WAC.mp4": 1585,
  "mc-hales-navy-complete::McHale's Navy - 4x20 - La Dolce 73.mp4": 1586,
  "mc-hales-navy-complete::McHale's Navy - 4x21 - McHale's Country Club Caper.mp4": 1588,
  "mc-hales-navy-complete::McHale's Navy - 4x22 - Secret Chimp 007.mp4": 1586,
  "mc-hales-navy-complete::McHale's Navy - 4x23 - 36-24-73.mp4": 1586,
  "mc-hales-navy-complete::McHale's Navy - 4x24 - My Son, the Skipper.mp4": 1586,
  "mc-hales-navy-complete::McHale's Navy - 4x25 - Little Red Riding Doctor.mp4": 1586,
  "mc-hales-navy-complete::McHale's Navy - 4x26 - Who Was That German I Saw You With.mp4": 1586,
  "mc-hales-navy-complete::McHale's Navy - 4x27 - The McHale Grand Prix.mp4": 1587,
  "mc-hales-navy-complete::McHale's Navy - 4x28 - An Ensign's Best Friend.mp4": 1585,
  "mc-hales-navy-complete::McHale's Navy - 4x29 - Binghamton, at 20 Paces.mp4": 1585,
  "mc-hales-navy-complete::McHale's Navy - 4x30 - Wally for Congress.mp4": 1585,
},
};
