window.SHOW = {
  id: "Houndcats",
  title: "The Houndcats",
  art: "Houndcats.jpg",
  storageProgressKey: "houndcats-progress",
  storageSettingsKey: "houndcats-settings",
  nestedPaths: true,
  grouping: "season",
  segments: "none",
  episodes: [
  ["the-houndcats-1972", "THE HOUNDCATS - S01E01 - The Misbehavin' Raven Mission",
    "The Houndcats - E01 (The Misbehavin' Raven Mission).mp4"],
  ["the-houndcats-1972", "THE HOUNDCATS - S01E02 - The Double Dealing Diamond Mission",
    "The Houndcats - E02 (The Double Dealing Diamond Mission).mp4"],
  ["the-houndcats-1972", "THE HOUNDCATS - S01E03 - The Great Gold Train Mission",
    "The Houndcats - E03 (The Great Gold Train Mission).mp4"],
  ["the-houndcats-1972", "THE HOUNDCATS - S01E04 - The Over the Waves Mission",
    "The Houndcats - E04 (The Over the Waves Mission).mp4"],
  ["the-houndcats-1972", "THE HOUNDCATS - S01E05 - There's Snow Biz Like Snow Biz Mission",
    "The Houndcats - E05 (There's No Biz Like Snow Biz Mission).mp4"],
  ["the-houndcats-1972", "THE HOUNDCATS - S01E06 - The Strangeless Than Fiction Mission",
    "The Houndcats - E06 (The Strangeless Than Fiction Mission).mp4"],
  ["the-houndcats-1972", "THE HOUNDCATS - S01E07 - The Ruckus on the Rails Mission",
    "The Houndcats - E07 (The Ruckus on the Rails Mission).mp4"],
  ["the-houndcats-1972", "THE HOUNDCATS - S01E08 - The Who's Who That's Who Mission",
    "The Houndcats - E08 (The Who's Who That's Who Mission).mp4"],
  ["the-houndcats-1972", "THE HOUNDCATS - S01E09 - The Perilous, Possibly, Pilfered Plans Mission",
    "The Houndcats - E09 (The Perilous, Possibly, Pilfered Plans Mission).mp4"],
  ["the-houndcats-1972", "THE HOUNDCATS - S01E10 - The French Collection Mission",
    "The Houndcats - E10 (The French Collection Mission).mp4"],
  ["the-houndcats-1972", "THE HOUNDCATS - S01E11 - The Outta Sight Blight Mission",
    "The Houndcats - E11 (The Outta Sight Blight Mission).mp4"],
  ["the-houndcats-1972", "THE HOUNDCATS - S01E12 - Is There a Doctor in the Greenhouse Mission",
    "The Houndcats - E12 (Is There a Doctor in the Greenhouse Mission).mp4"],
  ["the-houndcats-1972", "THE HOUNDCATS - S01E13 - The Call Me Madame X Mission",
    "The Houndcats - E13 (The Call Me Madam X Mission).mp4"],
],
  durations: {
  "the-houndcats-1972::The Houndcats - E01 (The Misbehavin' Raven Mission).mp4": 1305,
  "the-houndcats-1972::The Houndcats - E02 (The Double Dealing Diamond Mission).mp4": 1305,
  "the-houndcats-1972::The Houndcats - E03 (The Great Gold Train Mission).mp4": 1307,
  "the-houndcats-1972::The Houndcats - E04 (The Over the Waves Mission).mp4": 1305,
  "the-houndcats-1972::The Houndcats - E05 (There's No Biz Like Snow Biz Mission).mp4": 1306,
  "the-houndcats-1972::The Houndcats - E06 (The Strangeless Than Fiction Mission).mp4": 1304,
  "the-houndcats-1972::The Houndcats - E07 (The Ruckus on the Rails Mission).mp4": 1303,
  "the-houndcats-1972::The Houndcats - E08 (The Who's Who That's Who Mission).mp4": 1304,
  "the-houndcats-1972::The Houndcats - E09 (The Perilous, Possibly, Pilfered Plans Mission).mp4": 1306,
  "the-houndcats-1972::The Houndcats - E10 (The French Collection Mission).mp4": 1301,
  "the-houndcats-1972::The Houndcats - E11 (The Outta Sight Blight Mission).mp4": 1304,
  "the-houndcats-1972::The Houndcats - E12 (Is There a Doctor in the Greenhouse Mission).mp4": 1304,
  "the-houndcats-1972::The Houndcats - E13 (The Call Me Madam X Mission).mp4": 1304,
},
};
