window.SHOW = {
  id: "GeneRoddenberrysAndromeda",
  title: "Gene Roddenberry's Andromeda",
  art: "GeneRoddenberrysAndromeda.jpg",
  storageProgressKey: "generoddenberrysandromeda-progress",
  storageSettingsKey: "generoddenberrysandromeda-settings",
  nestedPaths: true,
  grouping: "season",
  segments: "none",
  episodes: [
  ["andromeda-complete-series", "GENE RODDENBERRY'S ANDROMEDA - S01E01 - Under the Night",
    "Andromeda S01 (360p re-dvdrip)/Andromeda S01E01 Under the Night.mp4"],
  ["andromeda-complete-series", "GENE RODDENBERRY'S ANDROMEDA - S01E02 - An Affirming Flame",
    "Andromeda S01 (360p re-dvdrip)/Andromeda S01E02 An Affirming Flame.mp4"],
  ["andromeda-complete-series", "GENE RODDENBERRY'S ANDROMEDA - S01E03 - To Loose the Fateful Lightning",
    "Andromeda S01 (360p re-dvdrip)/Andromeda S01E03 To Loose the Fateful Lightning.mp4"],
  ["andromeda-complete-series", "GENE RODDENBERRY'S ANDROMEDA - S01E04 - D Minus Zero",
    "Andromeda S01 (360p re-dvdrip)/Andromeda S01E04 D Minus Zero.mp4"],
  ["andromeda-complete-series", "GENE RODDENBERRY'S ANDROMEDA - S01E05 - Double Helix",
    "Andromeda S01 (360p re-dvdrip)/Andromeda S01E05 Double Helix.mp4"],
  ["andromeda-complete-series", "GENE RODDENBERRY'S ANDROMEDA - S01E06 - Angel Dark, Demon Bright",
    "Andromeda S01 (360p re-dvdrip)/Andromeda S01E06 Angel Dark, Demon Bright.mp4"],
  ["andromeda-complete-series", "GENE RODDENBERRY'S ANDROMEDA - S01E07 - The Ties That Blind",
    "Andromeda S01 (360p re-dvdrip)/Andromeda S01E07 The Ties That Blind.mp4"],
  ["andromeda-complete-series", "GENE RODDENBERRY'S ANDROMEDA - S01E08 - The Banks of the Lethe",
    "Andromeda S01 (360p re-dvdrip)/Andromeda S01E08 The Banks of the Lethe.mp4"],
  ["andromeda-complete-series", "GENE RODDENBERRY'S ANDROMEDA - S01E09 - A Rose in the Ashes",
    "Andromeda S01 (360p re-dvdrip)/Andromeda S01E09 A Rose in the Ashes.mp4"],
  ["andromeda-complete-series", "GENE RODDENBERRY'S ANDROMEDA - S01E10 - All Great Neptune's Ocean",
    "Andromeda S01 (360p re-dvdrip)/Andromeda S01E10 All Great Neptune's Ocean.mp4"],
  ["andromeda-complete-series", "GENE RODDENBERRY'S ANDROMEDA - S01E11 - The Pearls That Were His Eyes",
    "Andromeda S01 (360p re-dvdrip)/Andromeda S01E11 The Pearls That Were His Eyes.mp4"],
  ["andromeda-complete-series", "GENE RODDENBERRY'S ANDROMEDA - S01E12 - The Mathematics of Tears",
    "Andromeda S01 (360p re-dvdrip)/Andromeda S01E12 The Mathematics of Tears.mp4"],
  ["andromeda-complete-series", "GENE RODDENBERRY'S ANDROMEDA - S01E13 - Music of a Distant Drum",
    "Andromeda S01 (360p re-dvdrip)/Andromeda S01E13 Music of a Distant Drum.mp4"],
  ["andromeda-complete-series", "GENE RODDENBERRY'S ANDROMEDA - S01E14 - Harper 2.0",
    "Andromeda S01 (360p re-dvdrip)/Andromeda S01E14 Harper 2.0.mp4"],
  ["andromeda-complete-series", "GENE RODDENBERRY'S ANDROMEDA - S01E15 - Forced Perspective",
    "Andromeda S01 (360p re-dvdrip)/Andromeda S01E15 Forced Perspective.mp4"],
  ["andromeda-complete-series", "GENE RODDENBERRY'S ANDROMEDA - S01E16 - The Sum of Its Parts",
    "Andromeda S01 (360p re-dvdrip)/Andromeda S01E16 The Sum of Its Parts.mp4"],
  ["andromeda-complete-series", "GENE RODDENBERRY'S ANDROMEDA - S01E17 - Fear and Loathing in the Milky Way",
    "Andromeda S01 (360p re-dvdrip)/Andromeda S01E17 Fear and Loathing in the Milky Way.mp4"],
  ["andromeda-complete-series", "GENE RODDENBERRY'S ANDROMEDA - S01E18 - The Devil Take the Hindmost",
    "Andromeda S01 (360p re-dvdrip)/Andromeda S01E18 The Devil Take the Hindmost.mp4"],
  ["andromeda-complete-series", "GENE RODDENBERRY'S ANDROMEDA - S01E19 - The Honey Offering",
    "Andromeda S01 (360p re-dvdrip)/Andromeda S01E19 The Honey Offering.mp4"],
  ["andromeda-complete-series", "GENE RODDENBERRY'S ANDROMEDA - S01E20 - Star-Crossed",
    "Andromeda S01 (360p re-dvdrip)/Andromeda S01E20 Star-Crossed.mp4"],
  ["andromeda-complete-series", "GENE RODDENBERRY'S ANDROMEDA - S01E21 - It Makes a Lovely Light",
    "Andromeda S01 (360p re-dvdrip)/Andromeda S01E21 It Makes a Lovely Light.mp4"],
  ["andromeda-complete-series", "GENE RODDENBERRY'S ANDROMEDA - S01E22 - ... Its Hour Come Round at Last",
    "Andromeda S01 (360p re-dvdrip)/Andromeda S01E22 Its Hour Come 'Round at Last.mp4"],
  ["andromeda-complete-series", "GENE RODDENBERRY'S ANDROMEDA - S02E01 - The Widening Gyre",
    "Andromeda S02 (360p re-dvdrip)/Andromeda S02E01 The Widening Gyre.mp4"],
  ["andromeda-complete-series", "GENE RODDENBERRY'S ANDROMEDA - S02E02 - Exit Strategies",
    "Andromeda S02 (360p re-dvdrip)/Andromeda S02E02 Exit Strategies.mp4"],
  ["andromeda-complete-series", "GENE RODDENBERRY'S ANDROMEDA - S02E03 - A Heart for Falsehood Framed",
    "Andromeda S02 (360p re-dvdrip)/Andromeda S02E03 A Heart for Falsehood Framed.mp4"],
  ["andromeda-complete-series", "GENE RODDENBERRY'S ANDROMEDA - S02E04 - Pitiless as the Sun",
    "Andromeda S02 (360p re-dvdrip)/Andromeda S02E04 Pitiless as the Sun.mp4"],
  ["andromeda-complete-series", "GENE RODDENBERRY'S ANDROMEDA - S02E05 - Last Call at the Broken Hammer",
    "Andromeda S02 (360p re-dvdrip)/Andromeda S02E05 Last Call at the Broken Hammer.mp4"],
  ["andromeda-complete-series", "GENE RODDENBERRY'S ANDROMEDA - S02E06 - All Too Human",
    "Andromeda S02 (360p re-dvdrip)/Andromeda S02E06 All Too Human.mp4"],
  ["andromeda-complete-series", "GENE RODDENBERRY'S ANDROMEDA - S02E07 - Una Salus Victus",
    "Andromeda S02 (360p re-dvdrip)/Andromeda S02E07 Una Salus Victus.mp4"],
  ["andromeda-complete-series", "GENE RODDENBERRY'S ANDROMEDA - S02E08 - Home Fires",
    "Andromeda S02 (360p re-dvdrip)/Andromeda S02E08 Home Fires.mp4"],
  ["andromeda-complete-series", "GENE RODDENBERRY'S ANDROMEDA - S02E09 - Into the Labyrinth",
    "Andromeda S02 (360p re-dvdrip)/Andromeda S02E09 Into the Labyrinth.mp4"],
  ["andromeda-complete-series", "GENE RODDENBERRY'S ANDROMEDA - S02E10 - The Prince",
    "Andromeda S02 (360p re-dvdrip)/Andromeda S02E10 The Prince.mp4"],
  ["andromeda-complete-series", "GENE RODDENBERRY'S ANDROMEDA - S02E11 - Bunker Hill",
    "Andromeda S02 (360p re-dvdrip)/Andromeda S02E11 Bunker Hill.mp4"],
  ["andromeda-complete-series", "GENE RODDENBERRY'S ANDROMEDA - S02E12 - Ouroboros",
    "Andromeda S02 (360p re-dvdrip)/Andromeda S02E12 Ouroboros.mp4"],
  ["andromeda-complete-series", "GENE RODDENBERRY'S ANDROMEDA - S02E13 - Lava and Rockets",
    "Andromeda S02 (360p re-dvdrip)/Andromeda S02E13 Lava and Rockets.mp4"],
  ["andromeda-complete-series", "GENE RODDENBERRY'S ANDROMEDA - S02E14 - Be All My Sins Remembered",
    "Andromeda S02 (360p re-dvdrip)/Andromeda S02E14 Be All My Sins Remembered.mp4"],
  ["andromeda-complete-series", "GENE RODDENBERRY'S ANDROMEDA - S02E15 - Dance of the Mayflies",
    "Andromeda S02 (360p re-dvdrip)/Andromeda S02E15 Dance of the Mayflies.mp4"],
  ["andromeda-complete-series", "GENE RODDENBERRY'S ANDROMEDA - S02E16 - In Heaven Now are Three",
    "Andromeda S02 (360p re-dvdrip)/Andromeda S02E16 In Heaven Now Are Three.mp4"],
  ["andromeda-complete-series", "GENE RODDENBERRY'S ANDROMEDA - S02E17 - The Things We Cannot Change",
    "Andromeda S02 (360p re-dvdrip)/Andromeda S02E17 The Things We Cannot Change.mp4"],
  ["andromeda-complete-series", "GENE RODDENBERRY'S ANDROMEDA - S02E18 - The Fair Unknown",
    "Andromeda S02 (360p re-dvdrip)/Andromeda S02E18 The Fair Unknown.mp4"],
  ["andromeda-complete-series", "GENE RODDENBERRY'S ANDROMEDA - S02E19 - Belly of the Beast",
    "Andromeda S02 (360p re-dvdrip)/Andromeda S02E19 Belly of the Beast.mp4"],
  ["andromeda-complete-series", "GENE RODDENBERRY'S ANDROMEDA - S02E20 - The Knight, Death, and the Devil",
    "Andromeda S02 (360p re-dvdrip)/Andromeda S02E20 The Knight, Death, and the Devil.mp4"],
  ["andromeda-complete-series", "GENE RODDENBERRY'S ANDROMEDA - S02E21 - Immaculate Perception",
    "Andromeda S02 (360p re-dvdrip)/Andromeda S02E21 Immaculate Perception.mp4"],
  ["andromeda-complete-series", "GENE RODDENBERRY'S ANDROMEDA - S02E22 - Tunnel at the End of the Light",
    "Andromeda S02 (360p re-dvdrip)/Andromeda S02E22 Tunnel at the End of the Light.mp4"],
  ["andromeda-complete-series", "GENE RODDENBERRY'S ANDROMEDA - S03E01 - If the Wheel Is Fixed",
    "Andromeda S03 (360p re-dvdrip)/Andromeda S03E01 If the Wheel is Fixed.mp4"],
  ["andromeda-complete-series", "GENE RODDENBERRY'S ANDROMEDA - S03E02 - The Shards of Rimni",
    "Andromeda S03 (360p re-dvdrip)/Andromeda S03E02 The Shards of Rimni.mp4"],
  ["andromeda-complete-series", "GENE RODDENBERRY'S ANDROMEDA - S03E03 - Mad to Be Saved",
    "Andromeda S03 (360p re-dvdrip)/Andromeda S03E03 Mad to be Saved.mp4"],
  ["andromeda-complete-series", "GENE RODDENBERRY'S ANDROMEDA - S03E04 - Cui Bono",
    "Andromeda S03 (360p re-dvdrip)/Andromeda S03E04 Cui Bono.mp4"],
  ["andromeda-complete-series", "GENE RODDENBERRY'S ANDROMEDA - S03E05 - The Lone and Level Sands",
    "Andromeda S03 (360p re-dvdrip)/Andromeda S03E05 The Lone and Level Sands.mp4"],
  ["andromeda-complete-series", "GENE RODDENBERRY'S ANDROMEDA - S03E06 - Slipfighter the Dogs of War",
    "Andromeda S03 (360p re-dvdrip)/Andromeda S03E06 Slipfighter the Dogs of War.mp4"],
  ["andromeda-complete-series", "GENE RODDENBERRY'S ANDROMEDA - S03E07 - The Leper's Kiss",
    "Andromeda S03 (360p re-dvdrip)/Andromeda S03E07 The Leper's Kiss.mp4"],
  ["andromeda-complete-series", "GENE RODDENBERRY'S ANDROMEDA - S03E08 - For Whom the Bell Tolls",
    "Andromeda S03 (360p re-dvdrip)/Andromeda S03E08 For Whom the Bell Tolls.mp4"],
  ["andromeda-complete-series", "GENE RODDENBERRY'S ANDROMEDA - S03E09 - And Your Heart Will Fly Away...",
    "Andromeda S03 (360p re-dvdrip)/Andromeda S03E09 And Your Heart Will Fly Away.mp4"],
  ["andromeda-complete-series", "GENE RODDENBERRY'S ANDROMEDA - S03E10 - The Unconquerable Man",
    "Andromeda S03 (360p re-dvdrip)/Andromeda S03E10 The Unconquerable Man.mp4"],
  ["andromeda-complete-series", "GENE RODDENBERRY'S ANDROMEDA - S03E11 - Delenda Est",
    "Andromeda S03 (360p re-dvdrip)/Andromeda S03E11 Delenda Est.mp4"],
  ["andromeda-complete-series", "GENE RODDENBERRY'S ANDROMEDA - S03E12 - The Dark Backward",
    "Andromeda S03 (360p re-dvdrip)/Andromeda S03E12 The Dark Backward.mp4"],
  ["andromeda-complete-series", "GENE RODDENBERRY'S ANDROMEDA - S03E13 - The Risk All Point",
    "Andromeda S03 (360p re-dvdrip)/Andromeda S03E13 The Risk-All Point.mp4"],
  ["andromeda-complete-series", "GENE RODDENBERRY'S ANDROMEDA - S03E14 - The Right Horse",
    "Andromeda S03 (360p re-dvdrip)/Andromeda S03E14 The Right Horse.mp4"],
  ["andromeda-complete-series", "GENE RODDENBERRY'S ANDROMEDA - S03E15 - What Happens to a Rev Deferred?",
    "Andromeda S03 (360p re-dvdrip)/Andromeda S03E15 What Happens to a Rev Deferred.mp4"],
  ["andromeda-complete-series", "GENE RODDENBERRY'S ANDROMEDA - S03E16 - Point of the Spear",
    "Andromeda S03 (360p re-dvdrip)/Andromeda S03E16 Point of the Spear.mp4"],
  ["andromeda-complete-series", "GENE RODDENBERRY'S ANDROMEDA - S03E17 - Vault of the Heavens",
    "Andromeda S03 (360p re-dvdrip)/Andromeda S03E17 Vault of the Heavens.mp4"],
  ["andromeda-complete-series", "GENE RODDENBERRY'S ANDROMEDA - S03E18 - Deep Midnight's Voice",
    "Andromeda S03 (360p re-dvdrip)/Andromeda S03E18 Deep Midnight's Voice.mp4"],
  ["andromeda-complete-series", "GENE RODDENBERRY'S ANDROMEDA - S03E19 - The Illusion of Majesty",
    "Andromeda S03 (360p re-dvdrip)/Andromeda S03E19 The Illusion of Majesty.mp4"],
  ["andromeda-complete-series", "GENE RODDENBERRY'S ANDROMEDA - S03E20 - Twilight of the Idols",
    "Andromeda S03 (360p re-dvdrip)/Andromeda S03E20 Twilight of the Idols.mp4"],
  ["andromeda-complete-series", "GENE RODDENBERRY'S ANDROMEDA - S03E21 - Day of Judgement, Day of Wrath",
    "Andromeda S03 (360p re-dvdrip)/Andromeda S03E21 Day of Judgement, Day of Wrath.mp4"],
  ["andromeda-complete-series", "GENE RODDENBERRY'S ANDROMEDA - S03E22 - Shadows Cast by a Final Salute",
    "Andromeda S03 (360p re-dvdrip)/Andromeda S03E22 Shadows Cast by a Final Salute.mp4"],
  ["andromeda-complete-series", "GENE RODDENBERRY'S ANDROMEDA - S04E01 - Answers Given to Questions Never Asked",
    "Andromeda S04 (360p re-dvdrip)/Andromeda S04E01 Answers Given to Questions Never Asked.mp4"],
  ["andromeda-complete-series", "GENE RODDENBERRY'S ANDROMEDA - S04E02 - Pieces of Eight",
    "Andromeda S04 (360p re-dvdrip)/Andromeda S04E02 Pieces of Eight.mp4"],
  ["andromeda-complete-series", "GENE RODDENBERRY'S ANDROMEDA - S04E03 - Waking the Tyrant's Device",
    "Andromeda S04 (360p re-dvdrip)/Andromeda S04E03 Waking the Tyrant's Device.mp4"],
  ["andromeda-complete-series", "GENE RODDENBERRY'S ANDROMEDA - S04E04 - Double or Nothingness",
    "Andromeda S04 (360p re-dvdrip)/Andromeda S04E04 Double or Nothingness.mp4"],
  ["andromeda-complete-series", "GENE RODDENBERRY'S ANDROMEDA - S04E05 - Harper/Delete",
    "Andromeda S04 (360p re-dvdrip)/Andromeda S04E05 HarperDelete.mp4"],
  ["andromeda-complete-series", "GENE RODDENBERRY'S ANDROMEDA - S04E06 - Soon the Nearing Vortex",
    "Andromeda S04 (360p re-dvdrip)/Andromeda S04E06 Soon the Nearing Vortex.mp4"],
  ["andromeda-complete-series", "GENE RODDENBERRY'S ANDROMEDA - S04E07 - The World Turns All Around Her",
    "Andromeda S04 (360p re-dvdrip)/Andromeda S04E07 The World Turns All Around Her.mp4"],
  ["andromeda-complete-series", "GENE RODDENBERRY'S ANDROMEDA - S04E08 - Conduit to Destiny",
    "Andromeda S04 (360p re-dvdrip)/Andromeda S04E08 Conduit to Destiny.mp4"],
  ["andromeda-complete-series", "GENE RODDENBERRY'S ANDROMEDA - S04E09 - Machinery of the Mind",
    "Andromeda S04 (360p re-dvdrip)/Andromeda S04E09 Machinery of the Mind.mp4"],
  ["andromeda-complete-series", "GENE RODDENBERRY'S ANDROMEDA - S04E10 - Exalted Reason, Resplendent Daughter",
    "Andromeda S04 (360p re-dvdrip)/Andromeda S04E10 Exalted Reason, Resplendent Daughter.mp4"],
  ["andromeda-complete-series", "GENE RODDENBERRY'S ANDROMEDA - S04E11 - The Torment, the Release",
    "Andromeda S04 (360p re-dvdrip)/Andromeda S04E11 The Torment, the Release.mp4"],
  ["andromeda-complete-series", "GENE RODDENBERRY'S ANDROMEDA - S04E12 - The Spider's Stratagem",
    "Andromeda S04 (360p re-dvdrip)/Andromeda S04E12 The Spider's Stratagem.mp4"],
  ["andromeda-complete-series", "GENE RODDENBERRY'S ANDROMEDA - S04E13 - The Warmth of an Invisible Light",
    "Andromeda S04 (360p re-dvdrip)/Andromeda S04E13 The Warmth of an Invisible Light.mp4"],
  ["andromeda-complete-series", "GENE RODDENBERRY'S ANDROMEDA - S04E14 - The Others",
    "Andromeda S04 (360p re-dvdrip)/Andromeda S04E14 The Others.mp4"],
  ["andromeda-complete-series", "GENE RODDENBERRY'S ANDROMEDA - S04E15 - Fear Burns Down to Ashes",
    "Andromeda S04 (360p re-dvdrip)/Andromeda S04E15 Fear Burns Down to Ashes.mp4"],
  ["andromeda-complete-series", "GENE RODDENBERRY'S ANDROMEDA - S04E16 - Lost in a Space That Isn't There",
    "Andromeda S04 (360p re-dvdrip)/Andromeda S04E16 Lost in a Space that isn't There.mp4"],
  ["andromeda-complete-series", "GENE RODDENBERRY'S ANDROMEDA - S04E17 - Abridging the Devil's Divide",
    "Andromeda S04 (360p re-dvdrip)/Andromeda S04E17 Abridging the Devil's Divide.mp4"],
  ["andromeda-complete-series", "GENE RODDENBERRY'S ANDROMEDA - S04E18 - Trusting the Gordian Maze",
    "Andromeda S04 (360p re-dvdrip)/Andromeda S04E18 Trusting the Gordian Maze.mp4"],
  ["andromeda-complete-series", "GENE RODDENBERRY'S ANDROMEDA - S04E19 - A Symmetry of Imperfection",
    "Andromeda S04 (360p re-dvdrip)/Andromeda S04E19 A Symmetry of Imperfection.mp4"],
  ["andromeda-complete-series", "GENE RODDENBERRY'S ANDROMEDA - S04E20 - Time Out of Mind",
    "Andromeda S04 (360p re-dvdrip)/Andromeda S04E20 Time Out of Mind.mp4"],
  ["andromeda-complete-series", "GENE RODDENBERRY'S ANDROMEDA - S04E21 - The Dissonant Interval: Part 1",
    "Andromeda S04 (360p re-dvdrip)/Andromeda S04E21 The Dissonant Interval Pt 1.mp4"],
  ["andromeda-complete-series", "GENE RODDENBERRY'S ANDROMEDA - S04E22 - The Dissonant Interval: Part 2",
    "Andromeda S04 (360p re-dvdrip)/Andromeda S04E22 The Dissonant Interval Pt 2.mp4"],
  ["andromeda-complete-series", "GENE RODDENBERRY'S ANDROMEDA - S05E01 - The Weight: Part 1",
    "Andromeda S05 (360p re-dvdrip)/Andromeda S05E01 The Weight Pt 1.mp4"],
  ["andromeda-complete-series", "GENE RODDENBERRY'S ANDROMEDA - S05E02 - The Weight: Part 2",
    "Andromeda S05 (360p re-dvdrip)/Andromeda S05E02 The Weight Pt 2.mp4"],
  ["andromeda-complete-series", "GENE RODDENBERRY'S ANDROMEDA - S05E03 - Phear Phactor Phenom",
    "Andromeda S05 (360p re-dvdrip)/Andromeda S05E03 Phear Phactor Phenom.mp4"],
  ["andromeda-complete-series", "GENE RODDENBERRY'S ANDROMEDA - S05E04 - Decay of the Angel",
    "Andromeda S05 (360p re-dvdrip)/Andromeda S05E04 Decay of the Angel.mp4"],
  ["andromeda-complete-series", "GENE RODDENBERRY'S ANDROMEDA - S05E05 - The Eschatology of Our Present",
    "Andromeda S05 (360p re-dvdrip)/Andromeda S05E05 The Eschatology of Our Present.mp4"],
  ["andromeda-complete-series", "GENE RODDENBERRY'S ANDROMEDA - S05E06 - When Goes Around...",
    "Andromeda S05 (360p re-dvdrip)/Andromeda S05E06 When Goes Around....mp4"],
  ["andromeda-complete-series", "GENE RODDENBERRY'S ANDROMEDA - S05E07 - Attempting Screed",
    "Andromeda S05 (360p re-dvdrip)/Andromeda S05E07 Attempting Screed.mp4"],
  ["andromeda-complete-series", "GENE RODDENBERRY'S ANDROMEDA - S05E08 - So Burn the Untamed Lands",
    "Andromeda S05 (360p re-dvdrip)/Andromeda S05E08 So Burn the Untamed Lands.mp4"],
  ["andromeda-complete-series", "GENE RODDENBERRY'S ANDROMEDA - S05E09 - What Will Be Was Not",
    "Andromeda S05 (360p re-dvdrip)/Andromeda S05E09 What Will be Was Not.mp4"],
  ["andromeda-complete-series", "GENE RODDENBERRY'S ANDROMEDA - S05E10 - The Test",
    "Andromeda S05 (360p re-dvdrip)/Andromeda S05E10 The Test.mp4"],
  ["andromeda-complete-series", "GENE RODDENBERRY'S ANDROMEDA - S05E11 - Through a Glass Darkly",
    "Andromeda S05 (360p re-dvdrip)/Andromeda S05E11 Through a Glass Darkly.mp4"],
  ["andromeda-complete-series", "GENE RODDENBERRY'S ANDROMEDA - S05E12 - Pride Before the Fall",
    "Andromeda S05 (360p re-dvdrip)/Andromeda S05E12 Pride Before the Fall.mp4"],
  ["andromeda-complete-series", "GENE RODDENBERRY'S ANDROMEDA - S05E13 - Moonlight Becomes You",
    "Andromeda S05 (360p re-dvdrip)/Andromeda S05E13 Moonlight Becomes You.mp4"],
  ["andromeda-complete-series", "GENE RODDENBERRY'S ANDROMEDA - S05E14 - Past Is Prolix",
    "Andromeda S05 (360p re-dvdrip)/Andromeda S05E14 Past is Prolix.mp4"],
  ["andromeda-complete-series", "GENE RODDENBERRY'S ANDROMEDA - S05E15 - The Opposites of Attraction",
    "Andromeda S05 (360p re-dvdrip)/Andromeda S05E15 The Opposites of Attraction.mp4"],
  ["andromeda-complete-series", "GENE RODDENBERRY'S ANDROMEDA - S05E16 - Saving Light from a Black Sun",
    "Andromeda S05 (360p re-dvdrip)/Andromeda S05E16 Saving Light from a Black Sun.mp4"],
  ["andromeda-complete-series", "GENE RODDENBERRY'S ANDROMEDA - S05E17 - Totaled Recall",
    "Andromeda S05 (360p re-dvdrip)/Andromeda S05E17 Totaled Recall.mp4"],
  ["andromeda-complete-series", "GENE RODDENBERRY'S ANDROMEDA - S05E18 - Quantum Tractate Delirium",
    "Andromeda S05 (360p re-dvdrip)/Andromeda S05E18 Quantum Tractate Delirium.mp4"],
  ["andromeda-complete-series", "GENE RODDENBERRY'S ANDROMEDA - S05E19 - One More Day's Light",
    "Andromeda S05 (360p re-dvdrip)/Andromeda S05E19 One More Day's Light.mp4"],
  ["andromeda-complete-series", "GENE RODDENBERRY'S ANDROMEDA - S05E20 - Chaos and the Stillness of It",
    "Andromeda S05 (360p re-dvdrip)/Andromeda S05E20 Chaos and the Stillness of It.mp4"],
  ["andromeda-complete-series", "GENE RODDENBERRY'S ANDROMEDA - S05E21 - The Heart of the Journey: Part 1",
    "Andromeda S05 (360p re-dvdrip)/Andromeda S05E21 The Heart of the Journey Pt 1.mp4"],
  ["andromeda-complete-series", "GENE RODDENBERRY'S ANDROMEDA - S05E22 - The Heart of the Journey: Part 2",
    "Andromeda S05 (360p re-dvdrip)/Andromeda S05E22 The Heart of the Journey Pt 2.mp4"],
],
  durations: {
  "andromeda-complete-series::Andromeda S01 (360p re-dvdrip)/Andromeda S01E01 Under the Night.mp4": 2577,
  "andromeda-complete-series::Andromeda S01 (360p re-dvdrip)/Andromeda S01E02 An Affirming Flame.mp4": 2577,
  "andromeda-complete-series::Andromeda S01 (360p re-dvdrip)/Andromeda S01E03 To Loose the Fateful Lightning.mp4": 2577,
  "andromeda-complete-series::Andromeda S01 (360p re-dvdrip)/Andromeda S01E04 D Minus Zero.mp4": 2577,
  "andromeda-complete-series::Andromeda S01 (360p re-dvdrip)/Andromeda S01E05 Double Helix.mp4": 2577,
  "andromeda-complete-series::Andromeda S01 (360p re-dvdrip)/Andromeda S01E06 Angel Dark, Demon Bright.mp4": 2577,
  "andromeda-complete-series::Andromeda S01 (360p re-dvdrip)/Andromeda S01E07 The Ties That Blind.mp4": 2579,
  "andromeda-complete-series::Andromeda S01 (360p re-dvdrip)/Andromeda S01E08 The Banks of the Lethe.mp4": 2577,
  "andromeda-complete-series::Andromeda S01 (360p re-dvdrip)/Andromeda S01E09 A Rose in the Ashes.mp4": 2578,
  "andromeda-complete-series::Andromeda S01 (360p re-dvdrip)/Andromeda S01E10 All Great Neptune's Ocean.mp4": 2577,
  "andromeda-complete-series::Andromeda S01 (360p re-dvdrip)/Andromeda S01E11 The Pearls That Were His Eyes.mp4": 2577,
  "andromeda-complete-series::Andromeda S01 (360p re-dvdrip)/Andromeda S01E12 The Mathematics of Tears.mp4": 2577,
  "andromeda-complete-series::Andromeda S01 (360p re-dvdrip)/Andromeda S01E13 Music of a Distant Drum.mp4": 2577,
  "andromeda-complete-series::Andromeda S01 (360p re-dvdrip)/Andromeda S01E14 Harper 2.0.mp4": 2577,
  "andromeda-complete-series::Andromeda S01 (360p re-dvdrip)/Andromeda S01E15 Forced Perspective.mp4": 2577,
  "andromeda-complete-series::Andromeda S01 (360p re-dvdrip)/Andromeda S01E16 The Sum of Its Parts.mp4": 2577,
  "andromeda-complete-series::Andromeda S01 (360p re-dvdrip)/Andromeda S01E17 Fear and Loathing in the Milky Way.mp4": 2577,
  "andromeda-complete-series::Andromeda S01 (360p re-dvdrip)/Andromeda S01E18 The Devil Take the Hindmost.mp4": 2577,
  "andromeda-complete-series::Andromeda S01 (360p re-dvdrip)/Andromeda S01E19 The Honey Offering.mp4": 2577,
  "andromeda-complete-series::Andromeda S01 (360p re-dvdrip)/Andromeda S01E20 Star-Crossed.mp4": 2577,
  "andromeda-complete-series::Andromeda S01 (360p re-dvdrip)/Andromeda S01E21 It Makes a Lovely Light.mp4": 2577,
  "andromeda-complete-series::Andromeda S01 (360p re-dvdrip)/Andromeda S01E22 Its Hour Come 'Round at Last.mp4": 2577,
  "andromeda-complete-series::Andromeda S02 (360p re-dvdrip)/Andromeda S02E01 The Widening Gyre.mp4": 2574,
  "andromeda-complete-series::Andromeda S02 (360p re-dvdrip)/Andromeda S02E02 Exit Strategies.mp4": 2574,
  "andromeda-complete-series::Andromeda S02 (360p re-dvdrip)/Andromeda S02E03 A Heart for Falsehood Framed.mp4": 2574,
  "andromeda-complete-series::Andromeda S02 (360p re-dvdrip)/Andromeda S02E04 Pitiless as the Sun.mp4": 2574,
  "andromeda-complete-series::Andromeda S02 (360p re-dvdrip)/Andromeda S02E05 Last Call at the Broken Hammer.mp4": 2574,
  "andromeda-complete-series::Andromeda S02 (360p re-dvdrip)/Andromeda S02E06 All Too Human.mp4": 2574,
  "andromeda-complete-series::Andromeda S02 (360p re-dvdrip)/Andromeda S02E07 Una Salus Victus.mp4": 2574,
  "andromeda-complete-series::Andromeda S02 (360p re-dvdrip)/Andromeda S02E08 Home Fires.mp4": 2574,
  "andromeda-complete-series::Andromeda S02 (360p re-dvdrip)/Andromeda S02E09 Into the Labyrinth.mp4": 2574,
  "andromeda-complete-series::Andromeda S02 (360p re-dvdrip)/Andromeda S02E10 The Prince.mp4": 2574,
  "andromeda-complete-series::Andromeda S02 (360p re-dvdrip)/Andromeda S02E11 Bunker Hill.mp4": 2574,
  "andromeda-complete-series::Andromeda S02 (360p re-dvdrip)/Andromeda S02E12 Ouroboros.mp4": 2574,
  "andromeda-complete-series::Andromeda S02 (360p re-dvdrip)/Andromeda S02E13 Lava and Rockets.mp4": 2574,
  "andromeda-complete-series::Andromeda S02 (360p re-dvdrip)/Andromeda S02E14 Be All My Sins Remembered.mp4": 2574,
  "andromeda-complete-series::Andromeda S02 (360p re-dvdrip)/Andromeda S02E15 Dance of the Mayflies.mp4": 2574,
  "andromeda-complete-series::Andromeda S02 (360p re-dvdrip)/Andromeda S02E16 In Heaven Now Are Three.mp4": 2574,
  "andromeda-complete-series::Andromeda S02 (360p re-dvdrip)/Andromeda S02E17 The Things We Cannot Change.mp4": 2574,
  "andromeda-complete-series::Andromeda S02 (360p re-dvdrip)/Andromeda S02E18 The Fair Unknown.mp4": 2574,
  "andromeda-complete-series::Andromeda S02 (360p re-dvdrip)/Andromeda S02E19 Belly of the Beast.mp4": 2574,
  "andromeda-complete-series::Andromeda S02 (360p re-dvdrip)/Andromeda S02E20 The Knight, Death, and the Devil.mp4": 2574,
  "andromeda-complete-series::Andromeda S02 (360p re-dvdrip)/Andromeda S02E21 Immaculate Perception.mp4": 2574,
  "andromeda-complete-series::Andromeda S02 (360p re-dvdrip)/Andromeda S02E22 Tunnel at the End of the Light.mp4": 2574,
  "andromeda-complete-series::Andromeda S03 (360p re-dvdrip)/Andromeda S03E01 If the Wheel is Fixed.mp4": 2575,
  "andromeda-complete-series::Andromeda S03 (360p re-dvdrip)/Andromeda S03E02 The Shards of Rimni.mp4": 2574,
  "andromeda-complete-series::Andromeda S03 (360p re-dvdrip)/Andromeda S03E03 Mad to be Saved.mp4": 2574,
  "andromeda-complete-series::Andromeda S03 (360p re-dvdrip)/Andromeda S03E04 Cui Bono.mp4": 2574,
  "andromeda-complete-series::Andromeda S03 (360p re-dvdrip)/Andromeda S03E05 The Lone and Level Sands.mp4": 2574,
  "andromeda-complete-series::Andromeda S03 (360p re-dvdrip)/Andromeda S03E06 Slipfighter the Dogs of War.mp4": 2575,
  "andromeda-complete-series::Andromeda S03 (360p re-dvdrip)/Andromeda S03E07 The Leper's Kiss.mp4": 2575,
  "andromeda-complete-series::Andromeda S03 (360p re-dvdrip)/Andromeda S03E08 For Whom the Bell Tolls.mp4": 2574,
  "andromeda-complete-series::Andromeda S03 (360p re-dvdrip)/Andromeda S03E09 And Your Heart Will Fly Away.mp4": 2575,
  "andromeda-complete-series::Andromeda S03 (360p re-dvdrip)/Andromeda S03E10 The Unconquerable Man.mp4": 2574,
  "andromeda-complete-series::Andromeda S03 (360p re-dvdrip)/Andromeda S03E11 Delenda Est.mp4": 2575,
  "andromeda-complete-series::Andromeda S03 (360p re-dvdrip)/Andromeda S03E12 The Dark Backward.mp4": 2575,
  "andromeda-complete-series::Andromeda S03 (360p re-dvdrip)/Andromeda S03E13 The Risk-All Point.mp4": 2575,
  "andromeda-complete-series::Andromeda S03 (360p re-dvdrip)/Andromeda S03E14 The Right Horse.mp4": 2574,
  "andromeda-complete-series::Andromeda S03 (360p re-dvdrip)/Andromeda S03E15 What Happens to a Rev Deferred.mp4": 2574,
  "andromeda-complete-series::Andromeda S03 (360p re-dvdrip)/Andromeda S03E16 Point of the Spear.mp4": 2574,
  "andromeda-complete-series::Andromeda S03 (360p re-dvdrip)/Andromeda S03E17 Vault of the Heavens.mp4": 2574,
  "andromeda-complete-series::Andromeda S03 (360p re-dvdrip)/Andromeda S03E18 Deep Midnight's Voice.mp4": 2574,
  "andromeda-complete-series::Andromeda S03 (360p re-dvdrip)/Andromeda S03E19 The Illusion of Majesty.mp4": 2574,
  "andromeda-complete-series::Andromeda S03 (360p re-dvdrip)/Andromeda S03E20 Twilight of the Idols.mp4": 2575,
  "andromeda-complete-series::Andromeda S03 (360p re-dvdrip)/Andromeda S03E21 Day of Judgement, Day of Wrath.mp4": 2575,
  "andromeda-complete-series::Andromeda S03 (360p re-dvdrip)/Andromeda S03E22 Shadows Cast by a Final Salute.mp4": 2575,
  "andromeda-complete-series::Andromeda S04 (360p re-dvdrip)/Andromeda S04E01 Answers Given to Questions Never Asked.mp4": 2575,
  "andromeda-complete-series::Andromeda S04 (360p re-dvdrip)/Andromeda S04E02 Pieces of Eight.mp4": 2575,
  "andromeda-complete-series::Andromeda S04 (360p re-dvdrip)/Andromeda S04E03 Waking the Tyrant's Device.mp4": 2575,
  "andromeda-complete-series::Andromeda S04 (360p re-dvdrip)/Andromeda S04E04 Double or Nothingness.mp4": 2574,
  "andromeda-complete-series::Andromeda S04 (360p re-dvdrip)/Andromeda S04E05 HarperDelete.mp4": 2575,
  "andromeda-complete-series::Andromeda S04 (360p re-dvdrip)/Andromeda S04E06 Soon the Nearing Vortex.mp4": 2575,
  "andromeda-complete-series::Andromeda S04 (360p re-dvdrip)/Andromeda S04E07 The World Turns All Around Her.mp4": 2574,
  "andromeda-complete-series::Andromeda S04 (360p re-dvdrip)/Andromeda S04E08 Conduit to Destiny.mp4": 2574,
  "andromeda-complete-series::Andromeda S04 (360p re-dvdrip)/Andromeda S04E09 Machinery of the Mind.mp4": 2574,
  "andromeda-complete-series::Andromeda S04 (360p re-dvdrip)/Andromeda S04E10 Exalted Reason, Resplendent Daughter.mp4": 2575,
  "andromeda-complete-series::Andromeda S04 (360p re-dvdrip)/Andromeda S04E11 The Torment, the Release.mp4": 2574,
  "andromeda-complete-series::Andromeda S04 (360p re-dvdrip)/Andromeda S04E12 The Spider's Stratagem.mp4": 2574,
  "andromeda-complete-series::Andromeda S04 (360p re-dvdrip)/Andromeda S04E13 The Warmth of an Invisible Light.mp4": 2574,
  "andromeda-complete-series::Andromeda S04 (360p re-dvdrip)/Andromeda S04E14 The Others.mp4": 2574,
  "andromeda-complete-series::Andromeda S04 (360p re-dvdrip)/Andromeda S04E15 Fear Burns Down to Ashes.mp4": 2574,
  "andromeda-complete-series::Andromeda S04 (360p re-dvdrip)/Andromeda S04E16 Lost in a Space that isn't There.mp4": 2574,
  "andromeda-complete-series::Andromeda S04 (360p re-dvdrip)/Andromeda S04E17 Abridging the Devil's Divide.mp4": 2574,
  "andromeda-complete-series::Andromeda S04 (360p re-dvdrip)/Andromeda S04E18 Trusting the Gordian Maze.mp4": 2575,
  "andromeda-complete-series::Andromeda S04 (360p re-dvdrip)/Andromeda S04E19 A Symmetry of Imperfection.mp4": 2574,
  "andromeda-complete-series::Andromeda S04 (360p re-dvdrip)/Andromeda S04E20 Time Out of Mind.mp4": 2575,
  "andromeda-complete-series::Andromeda S04 (360p re-dvdrip)/Andromeda S04E21 The Dissonant Interval Pt 1.mp4": 2574,
  "andromeda-complete-series::Andromeda S04 (360p re-dvdrip)/Andromeda S04E22 The Dissonant Interval Pt 2.mp4": 2575,
  "andromeda-complete-series::Andromeda S05 (360p re-dvdrip)/Andromeda S05E01 The Weight Pt 1.mp4": 2575,
  "andromeda-complete-series::Andromeda S05 (360p re-dvdrip)/Andromeda S05E02 The Weight Pt 2.mp4": 2575,
  "andromeda-complete-series::Andromeda S05 (360p re-dvdrip)/Andromeda S05E03 Phear Phactor Phenom.mp4": 2575,
  "andromeda-complete-series::Andromeda S05 (360p re-dvdrip)/Andromeda S05E04 Decay of the Angel.mp4": 2575,
  "andromeda-complete-series::Andromeda S05 (360p re-dvdrip)/Andromeda S05E05 The Eschatology of Our Present.mp4": 2575,
  "andromeda-complete-series::Andromeda S05 (360p re-dvdrip)/Andromeda S05E06 When Goes Around....mp4": 2575,
  "andromeda-complete-series::Andromeda S05 (360p re-dvdrip)/Andromeda S05E07 Attempting Screed.mp4": 2575,
  "andromeda-complete-series::Andromeda S05 (360p re-dvdrip)/Andromeda S05E08 So Burn the Untamed Lands.mp4": 2575,
  "andromeda-complete-series::Andromeda S05 (360p re-dvdrip)/Andromeda S05E09 What Will be Was Not.mp4": 2575,
  "andromeda-complete-series::Andromeda S05 (360p re-dvdrip)/Andromeda S05E10 The Test.mp4": 2575,
  "andromeda-complete-series::Andromeda S05 (360p re-dvdrip)/Andromeda S05E11 Through a Glass Darkly.mp4": 2575,
  "andromeda-complete-series::Andromeda S05 (360p re-dvdrip)/Andromeda S05E12 Pride Before the Fall.mp4": 2575,
  "andromeda-complete-series::Andromeda S05 (360p re-dvdrip)/Andromeda S05E13 Moonlight Becomes You.mp4": 2575,
  "andromeda-complete-series::Andromeda S05 (360p re-dvdrip)/Andromeda S05E14 Past is Prolix.mp4": 2575,
  "andromeda-complete-series::Andromeda S05 (360p re-dvdrip)/Andromeda S05E15 The Opposites of Attraction.mp4": 2575,
  "andromeda-complete-series::Andromeda S05 (360p re-dvdrip)/Andromeda S05E16 Saving Light from a Black Sun.mp4": 2575,
  "andromeda-complete-series::Andromeda S05 (360p re-dvdrip)/Andromeda S05E17 Totaled Recall.mp4": 2575,
  "andromeda-complete-series::Andromeda S05 (360p re-dvdrip)/Andromeda S05E18 Quantum Tractate Delirium.mp4": 2575,
  "andromeda-complete-series::Andromeda S05 (360p re-dvdrip)/Andromeda S05E19 One More Day's Light.mp4": 2575,
  "andromeda-complete-series::Andromeda S05 (360p re-dvdrip)/Andromeda S05E20 Chaos and the Stillness of It.mp4": 2575,
  "andromeda-complete-series::Andromeda S05 (360p re-dvdrip)/Andromeda S05E21 The Heart of the Journey Pt 1.mp4": 2575,
  "andromeda-complete-series::Andromeda S05 (360p re-dvdrip)/Andromeda S05E22 The Heart of the Journey Pt 2.mp4": 2575,
},
};
