window.SHOW = {
  id: "DuckDodgers",
  title: "Duck Dodgers",
  art: "DuckDodgers.jpg",
  storageProgressKey: "duckdodgers-progress",
  storageSettingsKey: "duckdodgers-settings",
  nestedPaths: true,
  grouping: "season",
  segments: "none",
  episodes: [
  ["duck-dodgers-109-the-green-loontern-moonsong", "DUCK DODGERS - S01E01 - Duck Deception",
    "Duck_Dodgers_101a_Duck_Deception_[Moonsong].mp4"],
  ["duck-dodgers-109-the-green-loontern-moonsong", "DUCK DODGERS - S01E02 - The Spy Who Didn't Love Me",
    "Duck_Dodgers_101b_The_Spy_Who_Didn't_Love_Me_[Moonsong].mp4"],
  ["duck-dodgers-109-the-green-loontern-moonsong", "DUCK DODGERS - S01E03 - The Fowl Friend",
    "Duck_Dodgers_102a_The_Fowl_Friend_[Moonsong].mp4"],
  ["duck-dodgers-109-the-green-loontern-moonsong", "DUCK DODGERS - S01E04 - The Fast and the Feathery",
    "Duck_Dodgers_102b_The _Fast_&_the_Feathery_[Moonsong].mp4"],
  ["duck-dodgers-109-the-green-loontern-moonsong", "DUCK DODGERS - S01E05 - Trial of Duck Dodgers",
    "Duck_Dodgers_103a_Trial_of_Duck_Dodgers_[Moonsong].mp4"],
  ["duck-dodgers-109-the-green-loontern-moonsong", "DUCK DODGERS - S01E06 - Big Bug Mamas",
    "Duck_Dodgers_103b_Big_Bug_Mamas_[Moonsong].mp4"],
  ["duck-dodgers-109-the-green-loontern-moonsong", "DUCK DODGERS - S01E07 - Duck Codgers",
    "Duck_Dodgers_104a_Duck_Codgers_[Moonsong].mp4"],
  ["duck-dodgers-109-the-green-loontern-moonsong", "DUCK DODGERS - S01E08 - Where's Baby Smartypants",
    "Duck_Dodgers_104b_Where's_Baby_Smartypants_[Moonsong].mp4"],
  ["duck-dodgers-109-the-green-loontern-moonsong", "DUCK DODGERS - S01E09 - I'm Going to Get You, Fat Sucka",
    "Duck_Dodgers_105a_I'm_Going_To_Get_You,_Fat_Sucka_[Moonsong].mp4"],
  ["duck-dodgers-109-the-green-loontern-moonsong", "DUCK DODGERS - S01E10 - Detained Duck",
    "Duck_Dodgers_105b_Detained_Duck_[Moonsong].mp4"],
  ["duck-dodgers-109-the-green-loontern-moonsong", "DUCK DODGERS - S01E11 - K-9 Kaddy",
    "Duck_Dodgers_106a_K-9_Kaddy_[Moonsong].mp4"],
  ["duck-dodgers-109-the-green-loontern-moonsong", "DUCK DODGERS - S01E12 - Pig of Action",
    "Duck_Dodgers_106b_Pig_of_Action_[Moonsong].mp4"],
  ["duck-dodgers-2003-complete-series", "DUCK DODGERS - S01E13 - Shiver Me Dodgers",
    "Duck Dodgers S01 E13.Shiver Me Dodgers.mp4"],
  ["duck-dodgers_", "DUCK DODGERS - S01E14 - They Stole Dodgers' Brain",
    "Duck Dodgers S03E02A Villainstruck.mp4"],
  ["duck-dodgers_", "DUCK DODGERS - S01E15 - The Wrath of Canasta",
    "Duck Dodgers S03E02B Just The Two of Us.mp4"],
  ["duck-dodgers_", "DUCK DODGERS - S01E16 - The Green Loontern",
    "Duck Dodgers S03E03A The Kids Are All Wrong.mp4"],
  ["duck-dodgers_", "DUCK DODGERS - S01E17 - Quarterback Quack",
    "Duck Dodgers S03E03B Win Lose Or Duck.mp4"],
  ["duck-dodgers_", "DUCK DODGERS - S01E18 - To Love a Duck",
    "Duck Dodgers S03E04A Boar To Be Riled.mp4"],
  ["duck-dodgers_", "DUCK DODGERS - S01E19 - Hooray for Hollywood Planet",
    "Duck Dodgers S03E04B Clean Bill of Health.mp4"],
  ["duck-dodgers_", "DUCK DODGERS - S01E20 - The Queen is Wild",
    "Duck Dodgers S03E05A The Best of Captains The Worst of Captains.mp4"],
  ["duck-dodgers_", "DUCK DODGERS - S01E21 - Back to the Academy",
    "Duck Dodgers S03E05B Thats Lifomatica.mp4"],
  ["duck-dodgers_", "DUCK DODGERS - S01E22 - Enemy Yours",
    "Duck Dodgers S03E06A Diamond Boogie.mp4"],
  ["duck-dodgers_", "DUCK DODGERS - S01E23 - Duck Departure",
    "Duck Dodgers S03E06B Corporate Pigfall.mp4"],
  ["duck-dodgers_", "DUCK DODGERS - S01E24 - Duck Dodgers S03E08A Too Close For Combat",
    "Duck Dodgers S03E08A Too Close For Combat.mp4"],
  ["duck-dodgers_", "DUCK DODGERS - S01E25 - Duck Dodgers S03E08B The Fins of War",
    "Duck Dodgers S03E08B The Fins of War.mp4"],
  ["duck-dodgers-109-the-green-loontern-moonsong", "DUCK DODGERS - S01E26 - Duck Dodgers S03E09A Good Duck Hunting",
    "Duck_Dodgers_202b_Pet_Peeved_[Moonsong].mp4"],
  ["duck-dodgers-109-the-green-loontern-moonsong", "DUCK DODGERS - S01E27 - Duck Dodgers S03E09B Consumption Overruled",
    "Duck_Dodgers_203a_The_Menace_of_Maninsuit_[Moonsong].mp4"],
  ["duck-dodgers-109-the-green-loontern-moonsong", "DUCK DODGERS - S01E28 - Duck Dodgers S03E11A Master Disaster",
    "Duck_Dodgers_203b_K9_Quarry_[Moonsong].mp4"],
  ["duck-dodgers-109-the-green-loontern-moonsong", "DUCK DODGERS - S01E29 - Duck Dodgers S03E11B All In The Crime Family",
    "Duck_Dodgers_204a_Talent_Show_a_Go-Go_[Moonsong].mp4"],
  ["duck-dodgers-109-the-green-loontern-moonsong", "DUCK DODGERS - S01E30 - Duck Dodgers S03E12A In Space No One Can Hear You Rock",
    "Duck_Dodgers_204b_The_Love_of_a_Father_[Moonsong].mp4"],
  ["duck-dodgers-109-the-green-loontern-moonsong", "DUCK DODGERS - S01E31 - Duck Dodgers S03E12B Ridealong Calamity",
    "Duck_Dodgers_205a_The_New_Cadet_[Moonsong].mp4"],
  ["duck-dodgers-109-the-green-loontern-moonsong", "DUCK DODGERS - S01E32 - Duck Dodgers 205b The Love Duck",
    "Duck_Dodgers_205b_The_Love_Duck_[Moonsong].mp4"],
  ["duck-dodgers-109-the-green-loontern-moonsong", "DUCK DODGERS - S01E33 - Duck Dodgers 206 The Fudd",
    "Duck_Dodgers_206_The_Fudd_[Moonsong].mp4"],
  ["duck-dodgers-109-the-green-loontern-moonsong", "DUCK DODGERS - S01E34 - Duck Dodgers 207 The Mark of Xero & I See Duck People",
    "Duck_Dodgers_207_The_Mark_of_Xero_&_I_See_Duck_People_[mbaldw].mp4"],
  ["duck-dodgers-109-the-green-loontern-moonsong", "DUCK DODGERS - S01E35 - Duck Dodgers 208 Deathmatch Duck & Deconstructing Dodgers",
    "Duck_Dodgers_208_Deathmatch_Duck_&_Deconstructing_Dodgers_[mbaldw].mp4"],
  ["duck-dodgers-109-the-green-loontern-moonsong", "DUCK DODGERS - S01E36 - Duck Dodgers 209 M.M.O.R.D & Old Mcdodgers",
    "Duck_Dodgers_209_M.M.O.R.D_&_Old_Mcdodgers_[mbaldw].mp4"],
  ["duck-dodgers-109-the-green-loontern-moonsong", "DUCK DODGERS - S01E37 - Duck Dodgers 210 Diva Delivery & Castle High",
    "Duck_Dodgers_210_Diva_Delivery_&_Castle_High_[thunder_monkey].mp4"],
  ["duck-dodgers-109-the-green-loontern-moonsong", "DUCK DODGERS - S01E38 - Duck Dodgers 211 Surf the Stars & Samurai Quack",
    "Duck_Dodgers_211_Surf_the_Stars_&_Samurai_Quack_[mbaldw].mp4"],
  ["duck-dodgers-109-the-green-loontern-moonsong", "DUCK DODGERS - S01E39 - Duck Dodgers 212 Of Course You Know This Means War & Peace",
    "Duck_Dodgers_212_Of_Course_You_Know_This_Means_War_&_Peace_(part_1)_[mbaldw].mp4"],
  ["duck-dodgers-109-the-green-loontern-moonsong", "DUCK DODGERS - S01E40 - Duck Dodgers 213 Of Course You Know This Means War & Peace",
    "Duck_Dodgers_213_Of_Course_You_Know_This_Means_War_&_Peace_(part_2)_[mbaldw].mp4"],
  ["duck-dodgers-109-the-green-loontern-moonsong", "DUCK DODGERS - S01E41 - Duck Dodgers 301 Till Doom Do Us Part",
    "Duck_Dodgers_301_Till_Doom_Do_Us_Part_[Moonsong].mp4"],
  ["duck-dodgers-109-the-green-loontern-moonsong", "DUCK DODGERS - S01E42 - Duck Dodgers 302a Villainstruck",
    "Duck_Dodgers_302a_Villainstruck_[Moonsong].mp4"],
  ["duck-dodgers-109-the-green-loontern-moonsong", "DUCK DODGERS - S01E43 - Duck Dodgers 302b Just the Two of Us",
    "Duck_Dodgers_302b_Just_the_Two_of_Us_[Moonsong].mp4"],
  ["duck-dodgers-109-the-green-loontern-moonsong", "DUCK DODGERS - S01E44 - Duck Dodgers 303a The Kids Are All Wrong",
    "Duck_Dodgers_303a_The_Kids_Are_All_Wrong_[Moonsong].mp4"],
  ["duck-dodgers-109-the-green-loontern-moonsong", "DUCK DODGERS - S01E45 - Duck Dodgers 303b Win, Lose or Duck",
    "Duck_Dodgers_303b_Win,_Lose_or_Duck_[Moonsong].mp4"],
  ["duck-dodgers-109-the-green-loontern-moonsong", "DUCK DODGERS - S01E46 - Duck Dodgers 304a Boar to be Riled",
    "Duck_Dodgers_304a_Boar_to_be_Riled_[Moonsong].mp4"],
  ["duck-dodgers-109-the-green-loontern-moonsong", "DUCK DODGERS - S01E47 - Duck Dodgers 304b Clean Bill of Health",
    "Duck_Dodgers_304b_Clean_Bill_of_Health_[Moonsong].mp4"],
  ["duck-dodgers-109-the-green-loontern-moonsong", "DUCK DODGERS - S01E48 - Duck Dodgers 305a The Best of Captains, The Worst of Captains",
    "Duck_Dodgers_305a_The_Best_of_Captains,_The_Worst_of_Captains_[Moonsong].mp4"],
  ["duck-dodgers-109-the-green-loontern-moonsong", "DUCK DODGERS - S01E49 - Duck Dodgers 305b That's Lifomatica",
    "Duck_Dodgers_305b_That's_Lifomatica_[Moonsong].mp4"],
  ["duck-dodgers-109-the-green-loontern-moonsong", "DUCK DODGERS - S01E50 - Duck Dodgers 306a Diamond Boogie",
    "Duck_Dodgers_306a_Diamond_Boogie_[Moonsong].mp4"],
  ["duck-dodgers-109-the-green-loontern-moonsong", "DUCK DODGERS - S01E51 - Duck Dodgers 306b Corporate Pigfall",
    "Duck_Dodgers_306b_Corporate_Pigfall_[Moonsong].mp4"],
  ["duck-dodgers-109-the-green-loontern-moonsong", "DUCK DODGERS - S01E52 - Duck Dodgers 307 The Six Wazillion Dollar Duck",
    "Duck_Dodgers_307_The_Six_Wazillion_Dollar_Duck_[Moonsong].mp4"],
  ["duck-dodgers-109-the-green-loontern-moonsong", "DUCK DODGERS - S01E53 - Duck Dodgers 308a Too Close for Combat",
    "Duck_Dodgers_308a_Too_Close_for_Combat_[Moonsong].mp4"],
  ["duck-dodgers-109-the-green-loontern-moonsong", "DUCK DODGERS - S01E54 - Duck Dodgers 308b The Fins of War",
    "Duck_Dodgers_308b_The_Fins_of_War_[Moonsong].mp4"],
  ["duck-dodgers-109-the-green-loontern-moonsong", "DUCK DODGERS - S01E55 - Duck Dodgers 309a Good Duck Hunting",
    "Duck_Dodgers_309a_Good_Duck_Hunting_[Moonsong].mp4"],
  ["duck-dodgers-109-the-green-loontern-moonsong", "DUCK DODGERS - S01E56 - Duck Dodgers 309b Consumption Overruled",
    "Duck_Dodgers_309b_Consumption_Overruled_[Moonsong].mp4"],
  ["duck-dodgers-109-the-green-loontern-moonsong", "DUCK DODGERS - S01E57 - Duck Dodgers 310 A Lame Duck Mind",
    "Duck_Dodgers_310_A_Lame_Duck_Mind_[Moonsong].mp4"],
  ["duck-dodgers-109-the-green-loontern-moonsong", "DUCK DODGERS - S01E58 - Duck Dodgers 311a Master & Disaster",
    "Duck_Dodgers_311a_Master_&_Disaster_[Moonsong].mp4"],
  ["duck-dodgers-109-the-green-loontern-moonsong", "DUCK DODGERS - S01E59 - Duck Dodgers 311b All in the Crime Family",
    "Duck_Dodgers_311b_All_in_the_Crime_Family_[Moonsong].mp4"],
  ["duck-dodgers-109-the-green-loontern-moonsong", "DUCK DODGERS - S01E60 - Duck Dodgers 312a In Space, No One Can Hear You Rock",
    "Duck_Dodgers_312a_In_Space,_No_One_Can_Hear_You_Rock_[Moonsong].mp4"],
  ["duck-dodgers-109-the-green-loontern-moonsong", "DUCK DODGERS - S01E61 - Duck Dodgers 312b Ridealong Calamity",
    "Duck_Dodgers_312b_Ridealong_Calamity_[Moonsong].mp4"],
  ["duck-dodgers-109-the-green-loontern-moonsong", "DUCK DODGERS - S01E62 - Duck Dodgers 313 Bonafide Heroes",
    "Duck_Dodgers_313_Bonafide_Heroes_[Moonsong].mp4"],
  ["duck-dodgers-2003-complete-series", "DUCK DODGERS - S02E01 - Pig Planet",
    "Duck Dodgers S02 E01.Pig Planet.mp4"],
  ["duck-dodgers-2003-complete-series", "DUCK DODGERS - S02E02 - Invictus Interruptus",
    "Duck Dodgers S02 E02+E03.Invictus Interruptus - Pet Peeved.mp4"],
  ["duck-dodgers_", "DUCK DODGERS - S02E03 - Pet Peeved",
    "Duck Dodgers S02E03 The Menace of Maninsuit  K-9 Quarry.mp4"],
  ["duck-dodgers_", "DUCK DODGERS - S02E04 - The Menace of Maninsuit",
    "Duck Dodgers S02E04 Talent Show A Go-Go  The Love of A Father.mp4"],
  ["duck-dodgers_", "DUCK DODGERS - S02E05 - K-9 Quarry",
    "Duck Dodgers S02E05 The New Cadet  The Love Duck.mp4"],
  ["duck-dodgers-2003-complete-series", "DUCK DODGERS - S02E06 - Talent Show-a-Go-Go",
    "Duck Dodgers S02 E06+E07.Talent Show a Go-Go - The Love of a Father.mp4"],
  ["duck-dodgers_", "DUCK DODGERS - S02E07 - The Love of a Father",
    "Duck Dodgers S02E07 The Mark of Xero  I See Duck People.mp4"],
  ["duck-dodgers-2003-complete-series", "DUCK DODGERS - S02E08 - The New Cadet",
    "Duck Dodgers S02 E08+E09.The New Cadet - The Love Duck.mp4"],
  ["duck-dodgers_", "DUCK DODGERS - S02E09 - The Love Duck",
    "Duck Dodgers S02E09 MMORPD  Old McDodgers.mp4"],
  ["duck-dodgers-2003-complete-series", "DUCK DODGERS - S02E10 - The Fudd",
    "Duck Dodgers S02 E10.The Fudd.mp4"],
  ["duck-dodgers-2003-complete-series", "DUCK DODGERS - S02E11 - The Mark of Xero",
    "Duck Dodgers S02 E11+E12.The Mark of Xero - I See Duck People.mp4"],
  ["duck-dodgers_", "DUCK DODGERS - S02E12 - I See Duck People",
    "Duck Dodgers S02E12 Of Course You Know This Means War And Peace (Part 1).mp4"],
  ["duck-dodgers-2003-complete-series", "DUCK DODGERS - S02E13 - Deathmatch Duck",
    "Duck Dodgers S02 E13+E14.Deathmatch Duck - Deconstructing Dodgers.mp4"],
  ["duck-dodgers-2003-complete-series", "DUCK DODGERS - S02E15 - MMORPD",
    "Duck Dodgers S02 E15+E16.M.M.O.R.P.D. - Old McDodgers.mp4"],
  ["duck-dodgers-2003-complete-series", "DUCK DODGERS - S02E17 - Diva Delivery",
    "Duck Dodgers S02 E17+E18.Diva Delivery - Castle High.mp4"],
  ["duck-dodgers-2003-complete-series", "DUCK DODGERS - S02E19 - Surf the Stars",
    "Duck Dodgers S02 E19+E20.Surf the Stars - Samurai Quack.mp4"],
  ["duck-dodgers-2003-complete-series", "DUCK DODGERS - S02E21 - Of Course You Know This Means War and Peace (1)",
    "Duck Dodgers S02 E21.Of Course You Know This Means War and Peace (1).mp4"],
  ["duck-dodgers-2003-complete-series", "DUCK DODGERS - S02E22 - Of Course You Know This Means War and Peace (2)",
    "Duck Dodgers S02 E22.Of Course You Know This Means War and Peace (2).mp4"],
  ["duck-dodgers-2003-complete-series", "DUCK DODGERS - S03E01 - Till Doom Do Us Part",
    "Duck Dodgers S03 E01.Till Doom Do Us Part.mp4"],
  ["duck-dodgers-2003-complete-series", "DUCK DODGERS - S03E02 - Villainstruck",
    "Duck Dodgers S03 E02.Villainstruck.mp4"],
  ["duck-dodgers-2003-complete-series", "DUCK DODGERS - S03E03 - Just the Two of Us",
    "Duck Dodgers S03 E03.Just the Two of Us.mp4"],
  ["duck-dodgers-2003-complete-series", "DUCK DODGERS - S03E04 - The Kids Are All Wrong",
    "Duck Dodgers S03 E04.The Kids Are All Wrong.mp4"],
  ["duck-dodgers-2003-complete-series", "DUCK DODGERS - S03E05 - Win, Lose or Duck",
    "Duck Dodgers S03 E05.Win, Lose or Duck.mp4"],
  ["duck-dodgers-2003-complete-series", "DUCK DODGERS - S03E06 - Boar to Be Riled",
    "Duck Dodgers S03 E06.Boar to Be Riled.mp4"],
  ["duck-dodgers-2003-complete-series", "DUCK DODGERS - S03E07 - Clean Bill of Health",
    "Duck Dodgers S03 E07.Clean Bill of Health.mp4"],
  ["duck-dodgers-2003-complete-series", "DUCK DODGERS - S03E08 - Best of Captains, Worst of Captains",
    "Duck Dodgers S03 E08.The Best of Captains, the Worst of Captains.mp4"],
  ["duck-dodgers-2003-complete-series", "DUCK DODGERS - S03E09 - That's Lifoma",
    "Duck Dodgers S03 E09.That's Lifomatica.mp4"],
  ["duck-dodgers-2003-complete-series", "DUCK DODGERS - S03E10 - Diamond Boogie",
    "Duck Dodgers S03 E10.Diamond Boogie.mp4"],
  ["duck-dodgers-2003-complete-series", "DUCK DODGERS - S03E11 - Corporate Pigfall",
    "Duck Dodgers S03 E11.Corporate Pigfall.mp4"],
  ["duck-dodgers-2003-complete-series", "DUCK DODGERS - S03E12 - The Six Wazillion Dollar Duck",
    "Duck Dodgers S03 E12.The Six Wazillion Dollar Duck.mp4"],
  ["duck-dodgers-2003-complete-series", "DUCK DODGERS - S03E13 - Too Close for Combat",
    "Duck Dodgers S03 E13.Too Close for Combat.mp4"],
  ["duck-dodgers-2003-complete-series", "DUCK DODGERS - S03E14 - Fins of War",
    "Duck Dodgers S03 E14.The Fins of War.mp4"],
  ["duck-dodgers-2003-complete-series", "DUCK DODGERS - S03E15 - Good Duck Hunting",
    "Duck Dodgers S03 E15.Good Duck Hunting.mp4"],
  ["duck-dodgers-2003-complete-series", "DUCK DODGERS - S03E16 - Consumption Overruled",
    "Duck Dodgers S03 E16.Consumption Overruled.mp4"],
  ["duck-dodgers-2003-complete-series", "DUCK DODGERS - S03E17 - A Lame Duck Mind",
    "Duck Dodgers S03 E17.A Lame Duck Mind.mp4"],
  ["duck-dodgers-2003-complete-series", "DUCK DODGERS - S03E18 - Master & Disaster",
    "Duck Dodgers S03 E18.Master & Disaster.mp4"],
  ["duck-dodgers-2003-complete-series", "DUCK DODGERS - S03E19 - All in the Crime Family",
    "Duck Dodgers S03 E19.All in the Crime Family.mp4"],
  ["duck-dodgers-2003-complete-series", "DUCK DODGERS - S03E20 - In Space, No One Can Hear You Rock",
    "Duck Dodgers S03 E20.In Space, No One Can Hear You Rock.mp4"],
  ["duck-dodgers-2003-complete-series", "DUCK DODGERS - S03E21 - Ridealong Calamity",
    "Duck Dodgers S03 E21.Ridealong Calamity.mp4"],
  ["duck-dodgers-2003-complete-series", "DUCK DODGERS - S03E22 - Bonafide Hero: Captain Duck Dodgers",
    "Duck Dodgers S03 E22.Bonafide Heroes.mp4"],
],
  durations: {
  "duck-dodgers-109-the-green-loontern-moonsong::Duck_Dodgers_101a_Duck_Deception_[Moonsong].mp4": 707,
  "duck-dodgers-109-the-green-loontern-moonsong::Duck_Dodgers_101b_The_Spy_Who_Didn't_Love_Me_[Moonsong].mp4": 658,
  "duck-dodgers-109-the-green-loontern-moonsong::Duck_Dodgers_102a_The_Fowl_Friend_[Moonsong].mp4": 767,
  "duck-dodgers-109-the-green-loontern-moonsong::Duck_Dodgers_102b_The _Fast_&_the_Feathery_[Moonsong].mp4": 618,
  "duck-dodgers-109-the-green-loontern-moonsong::Duck_Dodgers_103a_Trial_of_Duck_Dodgers_[Moonsong].mp4": 706,
  "duck-dodgers-109-the-green-loontern-moonsong::Duck_Dodgers_103b_Big_Bug_Mamas_[Moonsong].mp4": 677,
  "duck-dodgers-109-the-green-loontern-moonsong::Duck_Dodgers_104a_Duck_Codgers_[Moonsong].mp4": 737,
  "duck-dodgers-109-the-green-loontern-moonsong::Duck_Dodgers_104b_Where's_Baby_Smartypants_[Moonsong].mp4": 635,
  "duck-dodgers-109-the-green-loontern-moonsong::Duck_Dodgers_105a_I'm_Going_To_Get_You,_Fat_Sucka_[Moonsong].mp4": 614,
  "duck-dodgers-109-the-green-loontern-moonsong::Duck_Dodgers_105b_Detained_Duck_[Moonsong].mp4": 765,
  "duck-dodgers-109-the-green-loontern-moonsong::Duck_Dodgers_106a_K-9_Kaddy_[Moonsong].mp4": 690,
  "duck-dodgers-109-the-green-loontern-moonsong::Duck_Dodgers_106b_Pig_of_Action_[Moonsong].mp4": 691,
  "duck-dodgers-2003-complete-series::Duck Dodgers S01 E13.Shiver Me Dodgers.mp4": 1348,
  "duck-dodgers_::Duck Dodgers S03E02A Villainstruck.mp4": 703,
  "duck-dodgers_::Duck Dodgers S03E02B Just The Two of Us.mp4": 670,
  "duck-dodgers_::Duck Dodgers S03E03A The Kids Are All Wrong.mp4": 673,
  "duck-dodgers_::Duck Dodgers S03E03B Win Lose Or Duck.mp4": 703,
  "duck-dodgers_::Duck Dodgers S03E04A Boar To Be Riled.mp4": 702,
  "duck-dodgers_::Duck Dodgers S03E04B Clean Bill of Health.mp4": 675,
  "duck-dodgers_::Duck Dodgers S03E05A The Best of Captains The Worst of Captains.mp4": 757,
  "duck-dodgers_::Duck Dodgers S03E05B Thats Lifomatica.mp4": 623,
  "duck-dodgers_::Duck Dodgers S03E06A Diamond Boogie.mp4": 693,
  "duck-dodgers_::Duck Dodgers S03E06B Corporate Pigfall.mp4": 682,
  "duck-dodgers_::Duck Dodgers S03E08A Too Close For Combat.mp4": 685,
  "duck-dodgers_::Duck Dodgers S03E08B The Fins of War.mp4": 688,
  "duck-dodgers-109-the-green-loontern-moonsong::Duck_Dodgers_202b_Pet_Peeved_[Moonsong].mp4": 602,
  "duck-dodgers-109-the-green-loontern-moonsong::Duck_Dodgers_203a_The_Menace_of_Maninsuit_[Moonsong].mp4": 678,
  "duck-dodgers-109-the-green-loontern-moonsong::Duck_Dodgers_203b_K9_Quarry_[Moonsong].mp4": 611,
  "duck-dodgers-109-the-green-loontern-moonsong::Duck_Dodgers_204a_Talent_Show_a_Go-Go_[Moonsong].mp4": 684,
  "duck-dodgers-109-the-green-loontern-moonsong::Duck_Dodgers_204b_The_Love_of_a_Father_[Moonsong].mp4": 688,
  "duck-dodgers-109-the-green-loontern-moonsong::Duck_Dodgers_205a_The_New_Cadet_[Moonsong].mp4": 668,
  "duck-dodgers-109-the-green-loontern-moonsong::Duck_Dodgers_205b_The_Love_Duck_[Moonsong].mp4": 704,
  "duck-dodgers-109-the-green-loontern-moonsong::Duck_Dodgers_206_The_Fudd_[Moonsong].mp4": 1360,
  "duck-dodgers-109-the-green-loontern-moonsong::Duck_Dodgers_207_The_Mark_of_Xero_&_I_See_Duck_People_[mbaldw].mp4": 1323,
  "duck-dodgers-109-the-green-loontern-moonsong::Duck_Dodgers_208_Deathmatch_Duck_&_Deconstructing_Dodgers_[mbaldw].mp4": 1299,
  "duck-dodgers-109-the-green-loontern-moonsong::Duck_Dodgers_209_M.M.O.R.D_&_Old_Mcdodgers_[mbaldw].mp4": 1183,
  "duck-dodgers-109-the-green-loontern-moonsong::Duck_Dodgers_210_Diva_Delivery_&_Castle_High_[thunder_monkey].mp4": 1283,
  "duck-dodgers-109-the-green-loontern-moonsong::Duck_Dodgers_211_Surf_the_Stars_&_Samurai_Quack_[mbaldw].mp4": 1311,
  "duck-dodgers-109-the-green-loontern-moonsong::Duck_Dodgers_212_Of_Course_You_Know_This_Means_War_&_Peace_(part_1)_[mbaldw].mp4": 1226,
  "duck-dodgers-109-the-green-loontern-moonsong::Duck_Dodgers_213_Of_Course_You_Know_This_Means_War_&_Peace_(part_2)_[mbaldw].mp4": 1318,
  "duck-dodgers-109-the-green-loontern-moonsong::Duck_Dodgers_301_Till_Doom_Do_Us_Part_[Moonsong].mp4": 1378,
  "duck-dodgers-109-the-green-loontern-moonsong::Duck_Dodgers_302a_Villainstruck_[Moonsong].mp4": 703,
  "duck-dodgers-109-the-green-loontern-moonsong::Duck_Dodgers_302b_Just_the_Two_of_Us_[Moonsong].mp4": 670,
  "duck-dodgers-109-the-green-loontern-moonsong::Duck_Dodgers_303a_The_Kids_Are_All_Wrong_[Moonsong].mp4": 673,
  "duck-dodgers-109-the-green-loontern-moonsong::Duck_Dodgers_303b_Win,_Lose_or_Duck_[Moonsong].mp4": 703,
  "duck-dodgers-109-the-green-loontern-moonsong::Duck_Dodgers_304a_Boar_to_be_Riled_[Moonsong].mp4": 702,
  "duck-dodgers-109-the-green-loontern-moonsong::Duck_Dodgers_304b_Clean_Bill_of_Health_[Moonsong].mp4": 675,
  "duck-dodgers-109-the-green-loontern-moonsong::Duck_Dodgers_305a_The_Best_of_Captains,_The_Worst_of_Captains_[Moonsong].mp4": 757,
  "duck-dodgers-109-the-green-loontern-moonsong::Duck_Dodgers_305b_That's_Lifomatica_[Moonsong].mp4": 623,
  "duck-dodgers-109-the-green-loontern-moonsong::Duck_Dodgers_306a_Diamond_Boogie_[Moonsong].mp4": 693,
  "duck-dodgers-109-the-green-loontern-moonsong::Duck_Dodgers_306b_Corporate_Pigfall_[Moonsong].mp4": 682,
  "duck-dodgers-109-the-green-loontern-moonsong::Duck_Dodgers_307_The_Six_Wazillion_Dollar_Duck_[Moonsong].mp4": 1377,
  "duck-dodgers-109-the-green-loontern-moonsong::Duck_Dodgers_308a_Too_Close_for_Combat_[Moonsong].mp4": 685,
  "duck-dodgers-109-the-green-loontern-moonsong::Duck_Dodgers_308b_The_Fins_of_War_[Moonsong].mp4": 688,
  "duck-dodgers-109-the-green-loontern-moonsong::Duck_Dodgers_309a_Good_Duck_Hunting_[Moonsong].mp4": 648,
  "duck-dodgers-109-the-green-loontern-moonsong::Duck_Dodgers_309b_Consumption_Overruled_[Moonsong].mp4": 720,
  "duck-dodgers-109-the-green-loontern-moonsong::Duck_Dodgers_310_A_Lame_Duck_Mind_[Moonsong].mp4": 1374,
  "duck-dodgers-109-the-green-loontern-moonsong::Duck_Dodgers_311a_Master_&_Disaster_[Moonsong].mp4": 692,
  "duck-dodgers-109-the-green-loontern-moonsong::Duck_Dodgers_311b_All_in_the_Crime_Family_[Moonsong].mp4": 686,
  "duck-dodgers-109-the-green-loontern-moonsong::Duck_Dodgers_312a_In_Space,_No_One_Can_Hear_You_Rock_[Moonsong].mp4": 675,
  "duck-dodgers-109-the-green-loontern-moonsong::Duck_Dodgers_312b_Ridealong_Calamity_[Moonsong].mp4": 690,
  "duck-dodgers-109-the-green-loontern-moonsong::Duck_Dodgers_313_Bonafide_Heroes_[Moonsong].mp4": 1362,
  "duck-dodgers-2003-complete-series::Duck Dodgers S02 E01.Pig Planet.mp4": 1365,
  "duck-dodgers-2003-complete-series::Duck Dodgers S02 E02+E03.Invictus Interruptus - Pet Peeved.mp4": 1395,
  "duck-dodgers_::Duck Dodgers S02E03 The Menace of Maninsuit  K-9 Quarry.mp4": 1303,
  "duck-dodgers_::Duck Dodgers S02E04 Talent Show A Go-Go  The Love of A Father.mp4": 1392,
  "duck-dodgers_::Duck Dodgers S02E05 The New Cadet  The Love Duck.mp4": 1386,
  "duck-dodgers-2003-complete-series::Duck Dodgers S02 E06+E07.Talent Show a Go-Go - The Love of a Father.mp4": 1392,
  "duck-dodgers_::Duck Dodgers S02E07 The Mark of Xero  I See Duck People.mp4": 1394,
  "duck-dodgers-2003-complete-series::Duck Dodgers S02 E08+E09.The New Cadet - The Love Duck.mp4": 1386,
  "duck-dodgers_::Duck Dodgers S02E09 MMORPD  Old McDodgers.mp4": 1246,
  "duck-dodgers-2003-complete-series::Duck Dodgers S02 E10.The Fudd.mp4": 1376,
  "duck-dodgers-2003-complete-series::Duck Dodgers S02 E11+E12.The Mark of Xero - I See Duck People.mp4": 1394,
  "duck-dodgers_::Duck Dodgers S02E12 Of Course You Know This Means War And Peace (Part 1).mp4": 1301,
  "duck-dodgers-2003-complete-series::Duck Dodgers S02 E13+E14.Deathmatch Duck - Deconstructing Dodgers.mp4": 1370,
  "duck-dodgers-2003-complete-series::Duck Dodgers S02 E15+E16.M.M.O.R.P.D. - Old McDodgers.mp4": 1246,
  "duck-dodgers-2003-complete-series::Duck Dodgers S02 E17+E18.Diva Delivery - Castle High.mp4": 1357,
  "duck-dodgers-2003-complete-series::Duck Dodgers S02 E19+E20.Surf the Stars - Samurai Quack.mp4": 1387,
  "duck-dodgers-2003-complete-series::Duck Dodgers S02 E21.Of Course You Know This Means War and Peace (1).mp4": 1301,
  "duck-dodgers-2003-complete-series::Duck Dodgers S02 E22.Of Course You Know This Means War and Peace (2).mp4": 1395,
  "duck-dodgers-2003-complete-series::Duck Dodgers S03 E01.Till Doom Do Us Part.mp4": 1381,
  "duck-dodgers-2003-complete-series::Duck Dodgers S03 E02.Villainstruck.mp4": 737,
  "duck-dodgers-2003-complete-series::Duck Dodgers S03 E03.Just the Two of Us.mp4": 734,
  "duck-dodgers-2003-complete-series::Duck Dodgers S03 E04.The Kids Are All Wrong.mp4": 707,
  "duck-dodgers-2003-complete-series::Duck Dodgers S03 E05.Win, Lose or Duck.mp4": 768,
  "duck-dodgers-2003-complete-series::Duck Dodgers S03 E06.Boar to Be Riled.mp4": 735,
  "duck-dodgers-2003-complete-series::Duck Dodgers S03 E07.Clean Bill of Health.mp4": 740,
  "duck-dodgers-2003-complete-series::Duck Dodgers S03 E08.The Best of Captains, the Worst of Captains.mp4": 790,
  "duck-dodgers-2003-complete-series::Duck Dodgers S03 E09.That's Lifomatica.mp4": 687,
  "duck-dodgers-2003-complete-series::Duck Dodgers S03 E10.Diamond Boogie.mp4": 728,
  "duck-dodgers-2003-complete-series::Duck Dodgers S03 E11.Corporate Pigfall.mp4": 747,
  "duck-dodgers-2003-complete-series::Duck Dodgers S03 E12.The Six Wazillion Dollar Duck.mp4": 1381,
  "duck-dodgers-2003-complete-series::Duck Dodgers S03 E13.Too Close for Combat.mp4": 721,
  "duck-dodgers-2003-complete-series::Duck Dodgers S03 E14.The Fins of War.mp4": 752,
  "duck-dodgers-2003-complete-series::Duck Dodgers S03 E15.Good Duck Hunting.mp4": 682,
  "duck-dodgers-2003-complete-series::Duck Dodgers S03 E16.Consumption Overruled.mp4": 784,
  "duck-dodgers-2003-complete-series::Duck Dodgers S03 E17.A Lame Duck Mind.mp4": 1377,
  "duck-dodgers-2003-complete-series::Duck Dodgers S03 E18.Master & Disaster.mp4": 728,
  "duck-dodgers-2003-complete-series::Duck Dodgers S03 E19.All in the Crime Family.mp4": 750,
  "duck-dodgers-2003-complete-series::Duck Dodgers S03 E20.In Space, No One Can Hear You Rock.mp4": 709,
  "duck-dodgers-2003-complete-series::Duck Dodgers S03 E21.Ridealong Calamity.mp4": 755,
  "duck-dodgers-2003-complete-series::Duck Dodgers S03 E22.Bonafide Heroes.mp4": 1390,
},
};
