window.SHOW = {
  id: "BeakmansWorld",
  title: "Beakman's World",
  art: "BeakmansWorld.jpg",
  storageProgressKey: "beakmansworld-progress",
  storageSettingsKey: "beakmansworld-settings",
  nestedPaths: true,
  grouping: "season",
  segments: "none",
  episodes: [
  ["beakmans-world", "BEAKMAN'S WORLD - S01E01 - Rain, Beakmania & Volcanoes",
    "Beakman's World - Season 1/Beakman's World - 101 - Rain, Beakmania & Volcanoes.mp4"],
  ["beakmans-world", "BEAKMAN'S WORLD - S01E02 - Gravity, Beakmania & Inertia",
    "Beakman's World - Season 1/Beakman's World - 102 - Gravity, Beakmania & Inertia.mp4"],
  ["beakmans-world", "BEAKMAN'S WORLD - S01E03 - Noises At Night, Beakmania & The Nose",
    "Beakman's World - Season 1/Beakman's World - 103 - Noises At Night, Beakmania & The Nose.mp4"],
  ["beakmans-world", "BEAKMAN'S WORLD - S01E04 - Blood, Beakmania & Dreams",
    "Beakman's World - Season 1/Beakman's World - 104 - Blood, Beakmania & Dreams.mp4"],
  ["beakmans-world", "BEAKMAN'S WORLD - S01E05 - Leaves, Beakmania & Paper",
    "Beakman's World - Season 1/Beakman's World - 105 - Leaves, Beakmania & Paper.mp4"],
  ["beakmans-world", "BEAKMAN'S WORLD - S01E06 - Soap, Beakmania & Auto Engines",
    "Beakman's World - Season 1/Beakman's World - 106 - Soap, Beakmania & Auto Engines.mp4"],
  ["beakmans-world", "BEAKMAN'S WORLD - S01E07 - Electricity, Beakmania & Light Bulbs",
    "Beakman's World - Season 1/Beakman's World - 107 - Electricity, Beakmania & Light Bulbs.mp4"],
  ["beakmans-world", "BEAKMAN'S WORLD - S01E08 - Sound, Beakmania & Explosions",
    "Beakman's World - Season 1/Beakman's World - 108 - Sound, Beakmania & Explosions.mp4"],
  ["beakmans-world", "BEAKMAN'S WORLD - S01E09 - Refraction, Attraction & Beakmania",
    "Beakman's World - Season 1/Beakman's World - 109 - Refraction, Attraction & Beakmania.mp4"],
  ["beakmans-world", "BEAKMAN'S WORLD - S01E10 - Levers, Beakmania & Television",
    "Beakman's World - Season 1/Beakman's World - 110 - Levers, Beakmania and Television.mp4"],
  ["beakmans-world", "BEAKMAN'S WORLD - S01E11 - Boats, Beakmania & Airplanes",
    "Beakman's World - Season 1/Beakman's World - 111 - Boats, Beakmania & Airplanes.mp4"],
  ["beakmans-world", "BEAKMAN'S WORLD - S01E12 - Bubbles, Beakmania & Feet",
    "Beakman's World - Season 1/Beakman's World - 112 - Bubbles, Beakmania & Feet.mp4"],
  ["beakmans-world", "BEAKMAN'S WORLD - S01E13 - Microscopes, Beakmania & Healing",
    "Beakman's World - Season 1/Beakman's World - 113 - Microscopes, Beakmania & Healing.mp4"],
  ["beakmans-world", "BEAKMAN'S WORLD - S01E14 - Scientific Method, Beakmania & Rainbows",
    "Beakman's World - Season 1/Beakman's World - 114 - Scientific Method, Beakmania & Rainbows.mp4"],
  ["beakmans-world", "BEAKMAN'S WORLD - S01E15 - Vaccinations, Beakmania & Friction",
    "Beakman's World - Season 1/Beakman's World - 115 - Vaccinations, Beakmania & Friction.mp4"],
  ["beakmans-world", "BEAKMAN'S WORLD - S01E16 - Thermodynamics, Beakmania & Pimples",
    "Beakman's World - Season 1/Beakman's World - 116 - Thermodynamics, Beakmania & Pimples.mp4"],
  ["beakmans-world", "BEAKMAN'S WORLD - S01E17 - Fossils, Beakmania & The Human Voice",
    "Beakman's World - Season 1/Beakman's World - 117 - Fossils, Beakmania & The Human Voice.mp4"],
  ["beakmans-world", "BEAKMAN'S WORLD - S01E18 - Lungs, Beakmania & Telephones",
    "Beakman's World - Season 1/Beakman's World - 118 - Lungs, Beakmania & Telephones.mp4"],
  ["beakmans-world", "BEAKMAN'S WORLD - S01E19 - Tape Recordings, Beakmania & Force Vs. Pressure",
    "Beakman's World - Season 1/Beakman's World - 119 - Tape Recordings, Beakmania & Force Vs. Pressure.mp4"],
  ["beakmans-world", "BEAKMAN'S WORLD - S01E20 - Microwaves, Beakmania & Spiders",
    "Beakman's World - Season 1/Beakman's World - 120 - Microwaves, Beakmania & Spiders.mp4"],
  ["beakmans-world", "BEAKMAN'S WORLD - S01E21 - Earwax, Beakmania & Rocket Engines",
    "Beakman's World - Season 1/Beakman's World - 121 - Earwax, Beakmania & Rocket Engines.mp4"],
  ["beakmans-world", "BEAKMAN'S WORLD - S01E22 - Ozone, Beakmania & Acid",
    "Beakman's World - Season 1/Beakman's World - 122 - Ozone, Beakmania & Acid.mp4"],
  ["beakmans-world", "BEAKMAN'S WORLD - S01E23 - Plumbing, Beakmania & Roller Coasters",
    "Beakman's World - Season 1/Beakman's World - 123 - Plumbing, Beakmania & Roller Coasters.mp4"],
  ["beakmans-world", "BEAKMAN'S WORLD - S01E24 - Bees, Beakmania & Earthquakes",
    "Beakman's World - Season 1/Beakman's World - 124 - Bees, Beakmania & Earthquakes.mp4"],
  ["beakmans-world", "BEAKMAN'S WORLD - S01E25 - Reflection, Beakmania & Madame Curie",
    "Beakman's World - Season 1/Beakman's World - 125 - Reflection, Beakmania & Madame Curie.mp4"],
  ["beakmans-world", "BEAKMAN'S WORLD - S01E26 - Wheels, Beakmania & Finding Answers",
    "Beakman's World - Season 1/Beakman's World - 126 - Wheels, Beakmania & Finding Answers.mp4"],
  ["beakmans-world", "BEAKMAN'S WORLD - S02E01 - Submarines, Beakmania & Digestion",
    "Beakman's World - Season 2/Beakman's World - S02E01 - Submarines, Beakmania & Digestion.mp4"],
  ["beakmans-world", "BEAKMAN'S WORLD - S02E02 - Heart, Beakmania & Helicopters",
    "Beakman's World - Season 2/Beakman's World - S02E02 - Heart, Beakmania & Helicopters.mp4"],
  ["beakmans-world", "BEAKMAN'S WORLD - S02E03 - Batteries, Beakmania & Balloons",
    "Beakman's World - Season 2/Beakman's World - S02E03 - Batteries, Beakmania & Balloons.mp4"],
  ["beakmans-world", "BEAKMAN'S WORLD - S02E04 - Tunnels, Beakmania & Trains",
    "Beakman's World - Season 2/Beakman's World - S02E04 - Tunnels, Beakmania & Trains.mp4"],
  ["beakmans-world", "BEAKMAN'S WORLD - S02E05 - Bats, Beakmania & Energy",
    "Beakman's World - Season 2/Beakman's World - S02E05 - Bats, Beakmania & Energy.mp4"],
  ["beakmans-world", "BEAKMAN'S WORLD - S02E06 - Sky, Beakmania & Henry Ford",
    "Beakman's World - Season 2/Beakman's World - S02E06 - Sky, Beakmania & Henry Ford.mp4"],
  ["beakmans-world", "BEAKMAN'S WORLD - S02E07 - Sound, Beakmania & Illusions",
    "Beakman's World - Season 2/Beakman's World - S02E07 - Sound, Beakmania & Illusions.mp4"],
  ["beakmans-world", "BEAKMAN'S WORLD - S02E08 - Lightning, Beakmania & Bones",
    "Beakman's World - Season 2/Beakman's World - S02E08 - Lightning, Beakmania & Bones.mp4"],
  ["beakmans-world", "BEAKMAN'S WORLD - S02E09 - Moon, Beakmania & Elevators",
    "Beakman's World - Season 2/Beakman's World - S02E09 - Moon, Beakmania & Elevators.mp4"],
  ["beakmans-world", "BEAKMAN'S WORLD - S02E10 - Video Games, Beakmania & Teeth",
    "Beakman's World - Season 2/Beakman's World - S02E10 - Video Games, Beakmania & Teeth.mp4"],
  ["beakmans-world", "BEAKMAN'S WORLD - S02E11 - Check-Up Time, Beakmania & Oil",
    "Beakman's World - Season 2/Beakman's World - S02E11 - Check-Up Time, Beakmania & Oil.mp4"],
  ["beakmans-world", "BEAKMAN'S WORLD - S02E12 - Ben Franklin, Beakmania & Chemical Reactions",
    "Beakman's World - Season 2/Beakman's World - S02E12 - Ben Franklin, Beakmania & Chemical Reactions.mp4"],
  ["beakmans-world", "BEAKMAN'S WORLD - S02E13 - Ants, Beakmania & Collisions",
    "Beakman's World - Season 2/Beakman's World - S02E13 - Ants, Beakmania & Collisions.mp4"],
  ["beakmans-world", "BEAKMAN'S WORLD - S02E14 - Pain, Beakmania & Comets",
    "Beakman's World - Season 2/Beakman's World - S02E14 - Pain, Beakmania & Comets.mp4"],
  ["beakmans-world", "BEAKMAN'S WORLD - S02E15 - Hydraulics, Beakmania & Dinosaurs",
    "Beakman's World - Season 2/Beakman's World - S02E15 - Hydraulics, Beakmania & Dinosaurs.mp4"],
  ["beakmans-world", "BEAKMAN'S WORLD - S02E16 - Electronic Motors, Beakmania & Time",
    "Beakman's World - Season 2/Beakman's World - S02E16 - Electronic Motors, Beakmania & Time.mp4"],
  ["beakmans-world", "BEAKMAN'S WORLD - S02E17 - Frogs and Toads, Beakmania & Polymers",
    "Beakman's World - Season 2/Beakman's World - S02E17 - Frogs and Toads, Beakmania & Polymers.mp4"],
  ["beakmans-world", "BEAKMAN'S WORLD - S02E18 - Money, Beakmania & Water Power",
    "Beakman's World - Season 2/Beakman's World - S02E18 - Money, Beakmania & Water Power.mp4"],
  ["beakmans-world", "BEAKMAN'S WORLD - S02E19 - Garbage, Beakmania & Meteorology",
    "Beakman's World - Season 2/Beakman's World - S02E19 - Garbage, Beakmania & Meteorology.mp4"],
  ["beakmans-world", "BEAKMAN'S WORLD - S02E20 - Skyscrapers, Beakmania & Indicators",
    "Beakman's World - Season 2/Beakman's World - S02E20 - Skyscrapers, Beakmania & Indicators.mp4"],
  ["beakmans-world", "BEAKMAN'S WORLD - S02E21 - Sharks, Beakmania & Einstein",
    "Beakman's World - Season 2/Beakman's World - S02E21 - Sharks, Beakmania & Einstein.mp4"],
  ["beakmans-world", "BEAKMAN'S WORLD - S02E22 - Mold, Beakmania & Caves",
    "Beakman's World - Season 2/Beakman's World - S02E22 - Mold, Beakmania & Caves.mp4"],
  ["beakmans-world", "BEAKMAN'S WORLD - S02E23 - Momentum, Beakmania & Cows",
    "Beakman's World - Season 2/Beakman's World - S02E23 - Momentum, Beakmania & Cows.mp4"],
  ["beakmans-world", "BEAKMAN'S WORLD - S02E24 - Allergies, Beakmania & Codes",
    "Beakman's World - Season 2/Beakman's World - S02E24 - Allergies, Beakmania & Codes.mp4"],
  ["beakmans-world", "BEAKMAN'S WORLD - S02E25 - Snakes, Beakmania & Seasons",
    "Beakman's World - Season 2/Beakman's World - S02E25 - Snakes, Beakmania & Seasons.mp4"],
  ["beakmans-world", "BEAKMAN'S WORLD - S02E26 - Tornadoes, Beakmania & Firefighting",
    "Beakman's World - Season 2/Beakman's World - S02E26 - Tornadoes, Beakmania & Firefighting.mp4"],
  ["beakmans-world", "BEAKMAN'S WORLD - S03E01 - Seeds, Beakmania & Bridges",
    "Beakman's World - Season 3/Beakman's World - S03E01 - Seeds, Beakmania & Bridges.mp4"],
  ["beakmans-world", "BEAKMAN'S WORLD - S03E02 - Balance, Beakmania & Camouflage",
    "Beakman's World - Season 3/Beakman's World - S03E02 - Balance, Beakmania & Camoflage.mp4"],
  ["beakmans-world", "BEAKMAN'S WORLD - S03E03 - Carbon, Beakmania & Inventions",
    "Beakman's World - Season 3/Beakman's World - S03E03 - Carbon, Beakmania & Inventions.mp4"],
  ["beakmans-world", "BEAKMAN'S WORLD - S03E04 - Gyroscopes, Beakmania & the Heart",
    "Beakman's World - Season 3/Beakman's World - S03E04 - Gyroscopes, Beakmania & the Heart.mp4"],
  ["beakmans-world", "BEAKMAN'S WORLD - S03E05 - Steel, Beakmania & Developing Film",
    "Beakman's World - Season 3/Beakman's World - S03E05 - Steel, Beakmania & Developing Film.mp4"],
  ["beakmans-world", "BEAKMAN'S WORLD - S03E06 - The Sun, Beakmania & Metamorphosis",
    "Beakman's World - Season 3/Beakman's World - S03E06 - The Sun, Beakmania & Metamorphysis.mp4"],
  ["beakmans-world", "BEAKMAN'S WORLD - S03E07 - Vacuums, Beakmania & Weaving",
    "Beakman's World - Season 3/Beakman's World - S03E07 - Vacuums, Beakmania & Weaving.mp4"],
  ["beakmans-world", "BEAKMAN'S WORLD - S03E08 - Snow, Beakmania & Natural Selection",
    "Beakman's World - Season 3/Beakman's World - S03E08 - Snow, Beakmania & Natural Selection.mp4"],
  ["beakmans-world", "BEAKMAN'S WORLD - S03E09 - Alligators and Crocodiles, Beakmania & Robots",
    "Beakman's World - Season 3/Beakman's World - S03E09 - Alligators and Crocodiles, Beakmania & Robots.mp4"],
  ["beakmans-world", "BEAKMAN'S WORLD - S03E10 - Geysers and Hot Springs, Beakmania & Kidneys",
    "Beakman's World - Season 3/Beakman's World - S03E10 - Geysers and Hot Springs, Beakmania & Kidneys.mp4"],
  ["beakmans-world", "BEAKMAN'S WORLD - S03E11 - Sleep, Beakmania & Amplification",
    "Beakman's World - Season 3/Beakman's World - S03E11 - Sleep, Beakmania & Amplification.mp4"],
  ["beakmans-world", "BEAKMAN'S WORLD - S03E12 - Crustaceans, Beakmania & Bernoulli",
    "Beakman's World - Season 3/Beakman's World - S03E12 - Crustaceans, Beakmania & Bernoulli.mp4"],
  ["beakmans-world", "BEAKMAN'S WORLD - S03E13 - Islands, Beakmania & Energy",
    "Beakman's World - Season 3/Beakman's World - S03E13 - Islands, Beakmania & Energy.mp4"],
  ["beakmans-world", "BEAKMAN'S WORLD - S04E01 - Sweat, Beakmania & Weighing a Car",
    "Beakman's World - Season 4/Beakman's World  - s04e01 - Sweat, Beakmania & Weighing a Car.mp4"],
  ["beakmans-world", "BEAKMAN'S WORLD - S04E02 - Migration, Beakmania & Living Space",
    "Beakman's World - Season 4/Beakman's World  - s04e02 - Migration, Beakmania & Living Space.mp4"],
  ["beakmans-world", "BEAKMAN'S WORLD - S04E03 - Bunsen, Beakmania & Sewage",
    "Beakman's World - Season 4/Beakman's World  - s04e03 - Bunsen, Beakmania & Sewage.mp4"],
  ["beakmans-world", "BEAKMAN'S WORLD - S04E04 - Cats, Beakmania & Dynamite",
    "Beakman's World - Season 4/Beakman's World  - s04e04 - Cats, Beakmania & Dynamite.mp4"],
  ["beakmans-world", "BEAKMAN'S WORLD - S04E05 - The Mouth, Beakmania & Scale",
    "Beakman's World - Season 4/Beakman's World  - s04e05 - The Mouth, Beakmania & Scale.mp4"],
  ["beakmans-world", "BEAKMAN'S WORLD - S04E06 - Catalysts, Beakmania & Aerosol Cans",
    "Beakman's World - Season 4/Beakman's World  - s04e06 - Catalysts, Beakmania & Aerosal Cans.mp4"],
  ["beakmans-world", "BEAKMAN'S WORLD - S04E07 - Rubber, Beakmania & Hair",
    "Beakman's World - Season 4/Beakman's World  - s04e07 - Rubber, Beakmania & Hair.mp4"],
  ["beakmans-world", "BEAKMAN'S WORLD - S04E08 - Camels, Beakmania & Density",
    "Beakman's World - Season 4/Beakman's World  - s04e08 - Camels, Beakmania & Density.mp4"],
  ["beakmans-world", "BEAKMAN'S WORLD - S04E09 - Boomerangs, Beakmania & Circus Science",
    "Beakman's World - Season 4/Beakman's World  - s04e09 - Boomerangs, Beakmania & Circus Science.mp4"],
  ["beakmans-world", "BEAKMAN'S WORLD - S04E10 - Elephants, Beakmania & X-Rays",
    "Beakman's World - Season 4/Beakman's World  - s04e10 - Elephants, Beakmania & X-Rays.mp4"],
  ["beakmans-world", "BEAKMAN'S WORLD - S04E11 - Skin, Beakmania & Oxygen",
    "Beakman's World - Season 4/Beakman's World  - s04e11 - Skin, Beakmania & Oxygen.mp4"],
  ["beakmans-world", "BEAKMAN'S WORLD - S04E12 - Bread, Beakmania & Measurement",
    "Beakman's World - Season 4/Beakman's World  - s04e12 - Bread, Beakmania & Measurement.mp4"],
  ["beakmans-world", "BEAKMAN'S WORLD - S04E13 - Electromagnets, Beakmania & Senses",
    "Beakman's World - Season 4/Beakman's World  - s04e13 - Electromagnets, Beakmania & Senses.mp4"],
  ["beakmans-world", "BEAKMAN'S WORLD - S04E14 - Chimps, Beakmania & Eye Exams",
    "Beakman's World - Season 4/Beakman's World  - s04e14 - Chimps, Beakmania & Eye Exams.mp4"],
  ["beakmans-world", "BEAKMAN'S WORLD - S04E15 - Magic, Beakmania & Cosmetic Chemistry",
    "Beakman's World - Season 4/Beakman's World  - s04e15 - Magic, Beakmania & Cosmetic Chemistry.mp4"],
  ["beakmans-world", "BEAKMAN'S WORLD - S04E16 - Pigs, Beakmania & Sound Frequency",
    "Beakman's World - Season 4/Beakman's World  - s04e16 - Pigs, Beakmania & Sound Frequency.mp4"],
  ["beakmans-world", "BEAKMAN'S WORLD - S04E17 - Sunken Treasure, Beakmania & Archimedean Screw",
    "Beakman's World - Season 4/Beakman's World  - s04e17 - Sunken Treasure, Beakmania & Archimedian Screw.mp4"],
  ["beakmans-world", "BEAKMAN'S WORLD - S04E18 - Whales, Beakmania & Optical Illusions II",
    "Beakman's World - Season 4/Beakman's World  - s04e18 - Whales, Beakmania & Optical Illusions II.mp4"],
  ["beakmans-world", "BEAKMAN'S WORLD - S04E19 - Sound Barrier, Beakmania & Healthy Living",
    "Beakman's World - Season 4/Beakman's World  - s04e19 - Sound Barrier, Beakmania & Healthy Living.mp4"],
  ["beakmans-world", "BEAKMAN'S WORLD - S04E20 - Polar Exploration, Beakmania & Circular Motion",
    "Beakman's World - Season 4/Beakman's World  - s04e20 - Polar Exploration, Beakmania & Circular Motion.mp4"],
  ["beakmans-world", "BEAKMAN'S WORLD - S04E21 - Dogs, Beakmania & Bio-Medical Engineering",
    "Beakman's World - Season 4/Beakman's World  - s04e21 - Dogs, Beakmania & Bio-Medical Engineering.mp4"],
  ["beakmans-world", "BEAKMAN'S WORLD - S04E22 - Human Growth, Beakmania & Solutions and Suspensions",
    "Beakman's World - Season 4/Beakman's World  - s04e22 - Human Growth, Beakmania & Solutions and Suspensions.mp4"],
  ["beakmans-world", "BEAKMAN'S WORLD - S04E23 - Action-Reaction, Beakmania & Talking Birds",
    "Beakman's World - Season 4/Beakman's World  - s04e23 - Action-Reaction, Beakmania & Talking Birds.mp4"],
  ["beakmans-world", "BEAKMAN'S WORLD - S04E24 - Protozoology, Beakmania & Movie Stunts",
    "Beakman's World - Season 4/Beakman's World  - s04e24 - Protozoology, Beakmania & Movie Stunts.mp4"],
  ["beakmans-world", "BEAKMAN'S WORLD - S04E25 - Horses, Beakmania & Refrigerators",
    "Beakman's World - Season 4/Beakman's World  - s04e25 - Horses, Beakmania & Refrigerators.mp4"],
  ["beakmans-world", "BEAKMAN'S WORLD - S04E26 - Fingerprints, Beakmania & Flatulence",
    "Beakman's World - Season 4/Beakman's World  - s04e26 - Fingerprints, Beakmania & Flatulence.mp4"],
],
  durations: {
  "beakmans-world::Beakman's World - Season 1/Beakman's World - 101 - Rain, Beakmania & Volcanoes.mp4": 1297,
  "beakmans-world::Beakman's World - Season 1/Beakman's World - 102 - Gravity, Beakmania & Inertia.mp4": 1295,
  "beakmans-world::Beakman's World - Season 1/Beakman's World - 103 - Noises At Night, Beakmania & The Nose.mp4": 1298,
  "beakmans-world::Beakman's World - Season 1/Beakman's World - 104 - Blood, Beakmania & Dreams.mp4": 1208,
  "beakmans-world::Beakman's World - Season 1/Beakman's World - 105 - Leaves, Beakmania & Paper.mp4": 1297,
  "beakmans-world::Beakman's World - Season 1/Beakman's World - 106 - Soap, Beakmania & Auto Engines.mp4": 1282,
  "beakmans-world::Beakman's World - Season 1/Beakman's World - 107 - Electricity, Beakmania & Light Bulbs.mp4": 1294,
  "beakmans-world::Beakman's World - Season 1/Beakman's World - 108 - Sound, Beakmania & Explosions.mp4": 1294,
  "beakmans-world::Beakman's World - Season 1/Beakman's World - 109 - Refraction, Attraction & Beakmania.mp4": 1293,
  "beakmans-world::Beakman's World - Season 1/Beakman's World - 110 - Levers, Beakmania and Television.mp4": 1293,
  "beakmans-world::Beakman's World - Season 1/Beakman's World - 111 - Boats, Beakmania & Airplanes.mp4": 1301,
  "beakmans-world::Beakman's World - Season 1/Beakman's World - 112 - Bubbles, Beakmania & Feet.mp4": 1294,
  "beakmans-world::Beakman's World - Season 1/Beakman's World - 113 - Microscopes, Beakmania & Healing.mp4": 1286,
  "beakmans-world::Beakman's World - Season 1/Beakman's World - 114 - Scientific Method, Beakmania & Rainbows.mp4": 1278,
  "beakmans-world::Beakman's World - Season 1/Beakman's World - 115 - Vaccinations, Beakmania & Friction.mp4": 1286,
  "beakmans-world::Beakman's World - Season 1/Beakman's World - 116 - Thermodynamics, Beakmania & Pimples.mp4": 1294,
  "beakmans-world::Beakman's World - Season 1/Beakman's World - 117 - Fossils, Beakmania & The Human Voice.mp4": 1271,
  "beakmans-world::Beakman's World - Season 1/Beakman's World - 118 - Lungs, Beakmania & Telephones.mp4": 1287,
  "beakmans-world::Beakman's World - Season 1/Beakman's World - 119 - Tape Recordings, Beakmania & Force Vs. Pressure.mp4": 1290,
  "beakmans-world::Beakman's World - Season 1/Beakman's World - 120 - Microwaves, Beakmania & Spiders.mp4": 1287,
  "beakmans-world::Beakman's World - Season 1/Beakman's World - 121 - Earwax, Beakmania & Rocket Engines.mp4": 1281,
  "beakmans-world::Beakman's World - Season 1/Beakman's World - 122 - Ozone, Beakmania & Acid.mp4": 1290,
  "beakmans-world::Beakman's World - Season 1/Beakman's World - 123 - Plumbing, Beakmania & Roller Coasters.mp4": 1285,
  "beakmans-world::Beakman's World - Season 1/Beakman's World - 124 - Bees, Beakmania & Earthquakes.mp4": 1282,
  "beakmans-world::Beakman's World - Season 1/Beakman's World - 125 - Reflection, Beakmania & Madame Curie.mp4": 1297,
  "beakmans-world::Beakman's World - Season 1/Beakman's World - 126 - Wheels, Beakmania & Finding Answers.mp4": 1292,
  "beakmans-world::Beakman's World - Season 2/Beakman's World - S02E01 - Submarines, Beakmania & Digestion.mp4": 1306,
  "beakmans-world::Beakman's World - Season 2/Beakman's World - S02E02 - Heart, Beakmania & Helicopters.mp4": 1302,
  "beakmans-world::Beakman's World - Season 2/Beakman's World - S02E03 - Batteries, Beakmania & Balloons.mp4": 1303,
  "beakmans-world::Beakman's World - Season 2/Beakman's World - S02E04 - Tunnels, Beakmania & Trains.mp4": 1307,
  "beakmans-world::Beakman's World - Season 2/Beakman's World - S02E05 - Bats, Beakmania & Energy.mp4": 1303,
  "beakmans-world::Beakman's World - Season 2/Beakman's World - S02E06 - Sky, Beakmania & Henry Ford.mp4": 1306,
  "beakmans-world::Beakman's World - Season 2/Beakman's World - S02E07 - Sound, Beakmania & Illusions.mp4": 1302,
  "beakmans-world::Beakman's World - Season 2/Beakman's World - S02E08 - Lightning, Beakmania & Bones.mp4": 1305,
  "beakmans-world::Beakman's World - Season 2/Beakman's World - S02E09 - Moon, Beakmania & Elevators.mp4": 1308,
  "beakmans-world::Beakman's World - Season 2/Beakman's World - S02E10 - Video Games, Beakmania & Teeth.mp4": 1304,
  "beakmans-world::Beakman's World - Season 2/Beakman's World - S02E11 - Check-Up Time, Beakmania & Oil.mp4": 1307,
  "beakmans-world::Beakman's World - Season 2/Beakman's World - S02E12 - Ben Franklin, Beakmania & Chemical Reactions.mp4": 1304,
  "beakmans-world::Beakman's World - Season 2/Beakman's World - S02E13 - Ants, Beakmania & Collisions.mp4": 1304,
  "beakmans-world::Beakman's World - Season 2/Beakman's World - S02E14 - Pain, Beakmania & Comets.mp4": 1303,
  "beakmans-world::Beakman's World - Season 2/Beakman's World - S02E15 - Hydraulics, Beakmania & Dinosaurs.mp4": 1303,
  "beakmans-world::Beakman's World - Season 2/Beakman's World - S02E16 - Electronic Motors, Beakmania & Time.mp4": 1301,
  "beakmans-world::Beakman's World - Season 2/Beakman's World - S02E17 - Frogs and Toads, Beakmania & Polymers.mp4": 1300,
  "beakmans-world::Beakman's World - Season 2/Beakman's World - S02E18 - Money, Beakmania & Water Power.mp4": 1311,
  "beakmans-world::Beakman's World - Season 2/Beakman's World - S02E19 - Garbage, Beakmania & Meteorology.mp4": 1307,
  "beakmans-world::Beakman's World - Season 2/Beakman's World - S02E20 - Skyscrapers, Beakmania & Indicators.mp4": 1303,
  "beakmans-world::Beakman's World - Season 2/Beakman's World - S02E21 - Sharks, Beakmania & Einstein.mp4": 1303,
  "beakmans-world::Beakman's World - Season 2/Beakman's World - S02E22 - Mold, Beakmania & Caves.mp4": 1310,
  "beakmans-world::Beakman's World - Season 2/Beakman's World - S02E23 - Momentum, Beakmania & Cows.mp4": 1304,
  "beakmans-world::Beakman's World - Season 2/Beakman's World - S02E24 - Allergies, Beakmania & Codes.mp4": 1309,
  "beakmans-world::Beakman's World - Season 2/Beakman's World - S02E25 - Snakes, Beakmania & Seasons.mp4": 1301,
  "beakmans-world::Beakman's World - Season 2/Beakman's World - S02E26 - Tornadoes, Beakmania & Firefighting.mp4": 1300,
  "beakmans-world::Beakman's World - Season 3/Beakman's World - S03E01 - Seeds, Beakmania & Bridges.mp4": 1287,
  "beakmans-world::Beakman's World - Season 3/Beakman's World - S03E02 - Balance, Beakmania & Camoflage.mp4": 1287,
  "beakmans-world::Beakman's World - Season 3/Beakman's World - S03E03 - Carbon, Beakmania & Inventions.mp4": 1287,
  "beakmans-world::Beakman's World - Season 3/Beakman's World - S03E04 - Gyroscopes, Beakmania & the Heart.mp4": 1286,
  "beakmans-world::Beakman's World - Season 3/Beakman's World - S03E05 - Steel, Beakmania & Developing Film.mp4": 1287,
  "beakmans-world::Beakman's World - Season 3/Beakman's World - S03E06 - The Sun, Beakmania & Metamorphysis.mp4": 1287,
  "beakmans-world::Beakman's World - Season 3/Beakman's World - S03E07 - Vacuums, Beakmania & Weaving.mp4": 1287,
  "beakmans-world::Beakman's World - Season 3/Beakman's World - S03E08 - Snow, Beakmania & Natural Selection.mp4": 1287,
  "beakmans-world::Beakman's World - Season 3/Beakman's World - S03E09 - Alligators and Crocodiles, Beakmania & Robots.mp4": 1287,
  "beakmans-world::Beakman's World - Season 3/Beakman's World - S03E10 - Geysers and Hot Springs, Beakmania & Kidneys.mp4": 1287,
  "beakmans-world::Beakman's World - Season 3/Beakman's World - S03E11 - Sleep, Beakmania & Amplification.mp4": 1287,
  "beakmans-world::Beakman's World - Season 3/Beakman's World - S03E12 - Crustaceans, Beakmania & Bernoulli.mp4": 1287,
  "beakmans-world::Beakman's World - Season 3/Beakman's World - S03E13 - Islands, Beakmania & Energy.mp4": 1287,
  "beakmans-world::Beakman's World - Season 4/Beakman's World  - s04e01 - Sweat, Beakmania & Weighing a Car.mp4": 1315,
  "beakmans-world::Beakman's World - Season 4/Beakman's World  - s04e02 - Migration, Beakmania & Living Space.mp4": 1300,
  "beakmans-world::Beakman's World - Season 4/Beakman's World  - s04e03 - Bunsen, Beakmania & Sewage.mp4": 1299,
  "beakmans-world::Beakman's World - Season 4/Beakman's World  - s04e04 - Cats, Beakmania & Dynamite.mp4": 1296,
  "beakmans-world::Beakman's World - Season 4/Beakman's World  - s04e05 - The Mouth, Beakmania & Scale.mp4": 1301,
  "beakmans-world::Beakman's World - Season 4/Beakman's World  - s04e06 - Catalysts, Beakmania & Aerosal Cans.mp4": 1310,
  "beakmans-world::Beakman's World - Season 4/Beakman's World  - s04e07 - Rubber, Beakmania & Hair.mp4": 1315,
  "beakmans-world::Beakman's World - Season 4/Beakman's World  - s04e08 - Camels, Beakmania & Density.mp4": 1295,
  "beakmans-world::Beakman's World - Season 4/Beakman's World  - s04e09 - Boomerangs, Beakmania & Circus Science.mp4": 1297,
  "beakmans-world::Beakman's World - Season 4/Beakman's World  - s04e10 - Elephants, Beakmania & X-Rays.mp4": 1314,
  "beakmans-world::Beakman's World - Season 4/Beakman's World  - s04e11 - Skin, Beakmania & Oxygen.mp4": 1304,
  "beakmans-world::Beakman's World - Season 4/Beakman's World  - s04e12 - Bread, Beakmania & Measurement.mp4": 1295,
  "beakmans-world::Beakman's World - Season 4/Beakman's World  - s04e13 - Electromagnets, Beakmania & Senses.mp4": 1314,
  "beakmans-world::Beakman's World - Season 4/Beakman's World  - s04e14 - Chimps, Beakmania & Eye Exams.mp4": 1298,
  "beakmans-world::Beakman's World - Season 4/Beakman's World  - s04e15 - Magic, Beakmania & Cosmetic Chemistry.mp4": 1304,
  "beakmans-world::Beakman's World - Season 4/Beakman's World  - s04e16 - Pigs, Beakmania & Sound Frequency.mp4": 1295,
  "beakmans-world::Beakman's World - Season 4/Beakman's World  - s04e17 - Sunken Treasure, Beakmania & Archimedian Screw.mp4": 1302,
  "beakmans-world::Beakman's World - Season 4/Beakman's World  - s04e18 - Whales, Beakmania & Optical Illusions II.mp4": 1304,
  "beakmans-world::Beakman's World - Season 4/Beakman's World  - s04e19 - Sound Barrier, Beakmania & Healthy Living.mp4": 1296,
  "beakmans-world::Beakman's World - Season 4/Beakman's World  - s04e20 - Polar Exploration, Beakmania & Circular Motion.mp4": 1295,
  "beakmans-world::Beakman's World - Season 4/Beakman's World  - s04e21 - Dogs, Beakmania & Bio-Medical Engineering.mp4": 1295,
  "beakmans-world::Beakman's World - Season 4/Beakman's World  - s04e22 - Human Growth, Beakmania & Solutions and Suspensions.mp4": 1315,
  "beakmans-world::Beakman's World - Season 4/Beakman's World  - s04e23 - Action-Reaction, Beakmania & Talking Birds.mp4": 1312,
  "beakmans-world::Beakman's World - Season 4/Beakman's World  - s04e24 - Protozoology, Beakmania & Movie Stunts.mp4": 1313,
  "beakmans-world::Beakman's World - Season 4/Beakman's World  - s04e25 - Horses, Beakmania & Refrigerators.mp4": 1303,
  "beakmans-world::Beakman's World - Season 4/Beakman's World  - s04e26 - Fingerprints, Beakmania & Flatulence.mp4": 1312,
},
};
