window.SHOW = {
  id: "InvaderZIM",
  title: "Invader ZIM",
  art: "InvaderZIM.jpg",
  storageProgressKey: "invaderzim-progress",
  storageSettingsKey: "invaderzim-settings",
  nestedPaths: true,
  grouping: "season",
  segments: "none",
  episodes: [
  ["hnbt_invaderzim", "INVADER ZIM - S01E01 - The Nightmare Begins",
    "01 - The Nightmare Begins [1x01].mp4"],
  ["invader-zim-repaired", "INVADER ZIM - S01E02 - Parent Teacher Night",
    "01 The Nightmare Begins.mp4"],
  ["invader-zim-repaired", "INVADER ZIM - S01E03 - Walk of Doom",
    "02 Bestest Friend – Nanozim.mp4"],
  ["invader-zim-repaired", "INVADER ZIM - S01E04 - Bestest Friend",
    "03 Parent Teacher Night – Walk of Doom.mp4"],
  ["invader-zim-repaired", "INVADER ZIM - S01E05 - NanoZIM",
    "04 Germs – Dark Harvest.mp4"],
  ["invader-zim-repaired", "INVADER ZIM - S01E06 - Germs",
    "05 Attack of the Saucer Morons – The Wettening.mp4"],
  ["invader-zim-repaired", "INVADER ZIM - S01E07 - Dark Harvest",
    "06 Career Day – Battle-Dib.mp4"],
  ["invader-zim-repaired", "INVADER ZIM - S01E08 - Attack of the Saucer Morons",
    "07 Planet Jackers – Rise of the Zitboy.mp4"],
  ["invader-zim-repaired", "INVADER ZIM - S01E09 - The Wettening",
    "08 Invasion of the Idiot Dog Brain – Bad Bad Rubber Piggy.mp4"],
  ["invader-zim-repaired", "INVADER ZIM - S01E10 - Career Day",
    "09 A Room with a Moose – Hamstergeddon.mp4"],
  ["invader-zim-repaired", "INVADER ZIM - S01E11 - Battle-Dib",
    "10 Plague of Babies – Bloatys Pizza Hog.mp4"],
  ["invader-zim-repaired", "INVADER ZIM - S01E12 - A Room with a Moose",
    "11 Door to Door – FBI Warning of Doom.mp4"],
  ["invader-zim-repaired", "INVADER ZIM - S01E13 - Hamstergeddon",
    "12 Bolognius Maximus – Game Slave 2.mp4"],
  ["invader-zim-repaired", "INVADER ZIM - S01E14 - Invasion of the Idiot Dog Brain",
    "13 Battle of the Planets.mp4"],
  ["invader-zim-repaired", "INVADER ZIM - S01E15 - Bad, Bad Rubber Piggy",
    "14 Halloween Spectacular of Spooky Doom.mp4"],
  ["invader-zim-repaired", "INVADER ZIM - S01E16 - Planet Jackers",
    "15 Mysterious Mysteries – Future Dib.mp4"],
  ["invader-zim-repaired", "INVADER ZIM - S01E17 - Rise of the Zitboy",
    "16 HOBO 13 – Walk for Your Lives.mp4"],
  ["invader-zim-repaired", "INVADER ZIM - S01E18 - Plague of Babies",
    "17 Megadoomer – Lice.mp4"],
  ["invader-zim-repaired", "INVADER ZIM - S01E19 - Bloaty's Pizza Hog",
    "18 Abducted – The Sad Sad Tale of Chickenfoot.mp4"],
  ["invader-zim-repaired", "INVADER ZIM - S01E20 - Bolognius Maximus",
    "19 GIR Goes Crazy and Stuff - Dibs Wonderful Life of Doom.mp4"],
  ["invader-zim-repaired", "INVADER ZIM - S01E21 - Game Slave 2",
    "20 TAK The Hideous New Girl.mp4"],
  ["invader-zim-repaired", "INVADER ZIM - S01E22 - Halloween Spectacular of Spooky Doom",
    "21 Backseat Drivers from Beyond the Stars.mp4"],
  ["invader-zim-repaired", "INVADER ZIM - S01E23 - Mysterious Mysteries",
    "22 Mortos Der Soulstealer – ZIM Eats Waffles.mp4"],
  ["invader-zim-repaired", "INVADER ZIM - S01E24 - Future Dib",
    "23 The Girl Who Cried Gnome – Dibship Rising.mp4"],
  ["invader-zim-repaired", "INVADER ZIM - S01E25 - Door to Door",
    "24 Vindicated – The Voting of the Doomed.mp4"],
  ["invader-zim-repaired", "INVADER ZIM - S01E26 - FBI Warning of Doom",
    "25 Gaz Taster of Pork.mp4"],
  ["invader-zim-repaired", "INVADER ZIM - S01E27 - Battle of the Planets",
    "26 The Frycook What Came from All That Space.mp4"],
  ["invader-zim-repaired", "INVADER ZIM - S01E28 - Abducted",
    "27 The Most Horrible Xmas Ever.mp4"],
  ["hnbt_invaderzim", "INVADER ZIM - S01E29 - The Sad, Sad Tale of Chickenfoot",
    "28 - Hobo 13 [1x16a].mp4"],
  ["hnbt_invaderzim", "INVADER ZIM - S01E30 - Megadoomer",
    "29 - Walk for Your Lives [1x16b].mp4"],
  ["invader-zim-repaired", "INVADER ZIM - S01E31 - Lice",
    "30 Interview with the Production Staff.mp4"],
  ["invader-zim-repaired", "INVADER ZIM - S01E32 - TAK: The Hideous New Girl",
    "99zim_germs*part1953.mp4"],
  ["hnbt_invaderzim", "INVADER ZIM - S01E33 - GIR Goes Crazy and Stuff",
    "32 - Abducted [1x18a].mp4"],
  ["hnbt_invaderzim", "INVADER ZIM - S01E34 - Dib's Wonderful Life of Doom",
    "33 - The Sad, Sad Tale of Chickenfoot [1x18b].mp4"],
  ["hnbt_invaderzim", "INVADER ZIM - S01E35 - Hobo 13",
    "34 - GIR Goes Crazy and Stuff [1x19a].mp4"],
  ["hnbt_invaderzim", "INVADER ZIM - S01E36 - Walk for Your Lives",
    "35 - Dib's Wonderful Life of Doom [1x19b].mp4"],
  ["hnbt_invaderzim", "INVADER ZIM - S01E37 - Mortos der Soulstealer",
    "38 - Mortos der Soulstealer [2x02a].mp4"],
  ["hnbt_invaderzim", "INVADER ZIM - S01E38 - Zim Eats Waffles",
    "39 - Zim Eats Waffles [2x02b].mp4"],
  ["hnbt_invaderzim", "INVADER ZIM - S01E39 - The Girl Who Cried Gnome",
    "40 - The Girl Who Cried Gnome [2x03a].mp4"],
  ["hnbt_invaderzim", "INVADER ZIM - S01E40 - Dibship Rising",
    "41 - Dibship Rising [2x03b].mp4"],
  ["hnbt_invaderzim", "INVADER ZIM - S01E41 - Vindicated",
    "42 - Vindicated! [2x04a].mp4"],
  ["hnbt_invaderzim", "INVADER ZIM - S01E42 - The Voting of the Doomed",
    "43 - The Voting of the Doomed [2x04b].mp4"],
  ["hnbt_invaderzim", "INVADER ZIM - S01E43 - Extras/Interview with the production staff",
    "Extras/Interview with the production staff.mp4"],
  ["hnbt_invaderzim", "INVADER ZIM - S01E44 - Extras/Interview with the voice cast",
    "Extras/Interview with the voice cast.mp4"],
  ["hnbt_invaderzim", "INVADER ZIM - S01E45 - Extras/Interview with the writers",
    "Extras/Interview with the writers.mp4"],
  ["hnbt_invaderzim", "INVADER ZIM - S01E46 - Extras/Original pilot",
    "Extras/Original pilot.mp4"],
  ["hnbt_invaderzim", "INVADER ZIM - S01E47 - VIDEO TS/VTS 24 0",
    "ISOs/Zim Vol 01 Disc 01.mp4"],
  ["invzimbonus", "INVADER ZIM - S01E48 - VIDEO TS/VTS 24 1",
    "VIDEO_TS/VTS_24_1.mp4"],
  ["hnbt_invaderzim", "INVADER ZIM - S01E49 - Untitled",
    "ISOs/Zim Vol 02 Disc 03.mp4"],
  ["hnbt_invaderzim", "INVADER ZIM - S01E50 - Untitled",
    "ISOs/Zim Vol 02 Disc 04.mp4"],
  ["hnbt_invaderzim", "INVADER ZIM - S01E51 - Untitled",
    "ISOs/Zim Vol 03 Disc 05.mp4"],
  ["hnbt_invaderzim", "INVADER ZIM - S01E52 - Untitled",
    "ISOs/Zim Vol 03 Disc 06.mp4"],
  ["hnbt_invaderzim", "INVADER ZIM - S02E01 - The Most Horrible X-mas Ever",
    "37 - Backseat Drivers from Beyond the Stars [2x01].mp4"],
  ["hnbt_invaderzim", "INVADER ZIM - S02E05 - The Girl Who Cried Gnome",
    "44 - Gaz, Taster of Pork [2x05].mp4"],
  ["hnbt_invaderzim", "INVADER ZIM - S02E06 - Dibship Rising",
    "45 - The Frycook What Came from All That Space [2x06].mp4"],
  ["hnbt_invaderzim", "INVADER ZIM - S02E07 - Vindicated!",
    "46 - The Most Horrible X-Mas Ever [2x07].mp4"],
],
  durations: {
  "hnbt_invaderzim::01 - The Nightmare Begins [1x01].mp4": 1463,
  "invader-zim-repaired::01 The Nightmare Begins.mp4": 1463,
  "invader-zim-repaired::02 Bestest Friend – Nanozim.mp4": 1464,
  "invader-zim-repaired::03 Parent Teacher Night – Walk of Doom.mp4": 1463,
  "invader-zim-repaired::04 Germs – Dark Harvest.mp4": 1462,
  "invader-zim-repaired::05 Attack of the Saucer Morons – The Wettening.mp4": 1464,
  "invader-zim-repaired::06 Career Day – Battle-Dib.mp4": 1446,
  "invader-zim-repaired::07 Planet Jackers – Rise of the Zitboy.mp4": 1458,
  "invader-zim-repaired::08 Invasion of the Idiot Dog Brain – Bad Bad Rubber Piggy.mp4": 1464,
  "invader-zim-repaired::09 A Room with a Moose – Hamstergeddon.mp4": 1465,
  "invader-zim-repaired::10 Plague of Babies – Bloatys Pizza Hog.mp4": 1436,
  "invader-zim-repaired::11 Door to Door – FBI Warning of Doom.mp4": 1471,
  "invader-zim-repaired::12 Bolognius Maximus – Game Slave 2.mp4": 1464,
  "invader-zim-repaired::13 Battle of the Planets.mp4": 1466,
  "invader-zim-repaired::14 Halloween Spectacular of Spooky Doom.mp4": 1426,
  "invader-zim-repaired::15 Mysterious Mysteries – Future Dib.mp4": 1453,
  "invader-zim-repaired::16 HOBO 13 – Walk for Your Lives.mp4": 1447,
  "invader-zim-repaired::17 Megadoomer – Lice.mp4": 1453,
  "invader-zim-repaired::18 Abducted – The Sad Sad Tale of Chickenfoot.mp4": 1475,
  "invader-zim-repaired::19 GIR Goes Crazy and Stuff - Dibs Wonderful Life of Doom.mp4": 1464,
  "invader-zim-repaired::20 TAK The Hideous New Girl.mp4": 1466,
  "invader-zim-repaired::21 Backseat Drivers from Beyond the Stars.mp4": 1467,
  "invader-zim-repaired::22 Mortos Der Soulstealer – ZIM Eats Waffles.mp4": 1462,
  "invader-zim-repaired::23 The Girl Who Cried Gnome – Dibship Rising.mp4": 1451,
  "invader-zim-repaired::24 Vindicated – The Voting of the Doomed.mp4": 1462,
  "invader-zim-repaired::25 Gaz Taster of Pork.mp4": 1432,
  "invader-zim-repaired::26 The Frycook What Came from All That Space.mp4": 1435,
  "invader-zim-repaired::27 The Most Horrible Xmas Ever.mp4": 1481,
  "hnbt_invaderzim::28 - Hobo 13 [1x16a].mp4": 768,
  "hnbt_invaderzim::29 - Walk for Your Lives [1x16b].mp4": 772,
  "invader-zim-repaired::30 Interview with the Production Staff.mp4": 871,
  "invader-zim-repaired::99zim_germs*part1953.mp4": 5125,
  "hnbt_invaderzim::32 - Abducted [1x18a].mp4": 779,
  "hnbt_invaderzim::33 - The Sad, Sad Tale of Chickenfoot [1x18b].mp4": 800,
  "hnbt_invaderzim::34 - GIR Goes Crazy and Stuff [1x19a].mp4": 751,
  "hnbt_invaderzim::35 - Dib's Wonderful Life of Doom [1x19b].mp4": 805,
  "hnbt_invaderzim::38 - Mortos der Soulstealer [2x02a].mp4": 800,
  "hnbt_invaderzim::39 - Zim Eats Waffles [2x02b].mp4": 755,
  "hnbt_invaderzim::40 - The Girl Who Cried Gnome [2x03a].mp4": 787,
  "hnbt_invaderzim::41 - Dibship Rising [2x03b].mp4": 757,
  "hnbt_invaderzim::42 - Vindicated! [2x04a].mp4": 786,
  "hnbt_invaderzim::43 - The Voting of the Doomed [2x04b].mp4": 769,
  "hnbt_invaderzim::Extras/Interview with the production staff.mp4": 871,
  "hnbt_invaderzim::Extras/Interview with the voice cast.mp4": 784,
  "hnbt_invaderzim::Extras/Interview with the writers.mp4": 596,
  "hnbt_invaderzim::Extras/Original pilot.mp4": 814,
  "hnbt_invaderzim::ISOs/Zim Vol 01 Disc 01.mp4": 7330,
  "invzimbonus::VIDEO_TS/VTS_24_1.mp4": 101,
  "hnbt_invaderzim::ISOs/Zim Vol 02 Disc 03.mp4": 7267,
  "hnbt_invaderzim::ISOs/Zim Vol 02 Disc 04.mp4": 5836,
  "hnbt_invaderzim::ISOs/Zim Vol 03 Disc 05.mp4": 7321,
  "hnbt_invaderzim::ISOs/Zim Vol 03 Disc 06.mp4": 5817,
  "hnbt_invaderzim::37 - Backseat Drivers from Beyond the Stars [2x01].mp4": 1467,
  "hnbt_invaderzim::44 - Gaz, Taster of Pork [2x05].mp4": 1432,
  "hnbt_invaderzim::45 - The Frycook What Came from All That Space [2x06].mp4": 1435,
  "hnbt_invaderzim::46 - The Most Horrible X-Mas Ever [2x07].mp4": 1481,
},
};
