window.SHOW = {
  id: "HammerHouseofHorror",
  title: "Hammer House of Horror",
  art: "HammerHouseofHorror.jpg",
  storageProgressKey: "hammerhouseofhorror-progress",
  storageSettingsKey: "hammerhouseofhorror-settings",
  nestedPaths: true,
  grouping: "season",
  segments: "none",
  episodes: [
  ["hammer-house-of-horror-the-complete-series-1980", "HAMMER HOUSE OF HORROR - S01E01 - Witching Time",
    "Hammer House of Horror S01E01 - Witching Time.mp4"],
  ["hammer-house-of-horror-the-complete-series-1980", "HAMMER HOUSE OF HORROR - S01E02 - The Thirteenth Reunion",
    "Hammer House of Horror S01E02 - The Thirteenth Reunion.mp4"],
  ["hammer-house-of-horror-the-complete-series-1980", "HAMMER HOUSE OF HORROR - S01E03 - Rude Awakening",
    "Hammer House of Horror S01E03 - Rude Awakening.mp4"],
  ["hammer-house-of-horror-the-complete-series-1980", "HAMMER HOUSE OF HORROR - S01E04 - Growing Pains",
    "Hammer House of Horror S01E04 - Growing Pains.mp4"],
  ["hammer-house-of-horror-the-complete-series-1980", "HAMMER HOUSE OF HORROR - S01E05 - The House that Bled to Death",
    "Hammer House of Horror S01E05 - The House that Bled to Death.mp4"],
  ["hammer-house-of-horror-the-complete-series-1980", "HAMMER HOUSE OF HORROR - S01E06 - Charlie Boy",
    "Hammer House of Horror S01E06 - Charlie Boy.mp4"],
  ["hammer-house-of-horror-the-complete-series-1980", "HAMMER HOUSE OF HORROR - S01E07 - The Silent Scream",
    "Hammer House of Horror S01E07 - The Silent Scream.mp4"],
  ["hammer-house-of-horror-the-complete-series-1980", "HAMMER HOUSE OF HORROR - S01E08 - Children of the Full Moon",
    "Hammer House of Horror S01E08 - Children of the Full Moon.mp4"],
  ["hammer-house-of-horror-the-complete-series-1980", "HAMMER HOUSE OF HORROR - S01E09 - Carpathian Eagle",
    "Hammer House of Horror S01E09 - The Carpathian Eagle.mp4"],
  ["hammer-house-of-horror-the-complete-series-1980", "HAMMER HOUSE OF HORROR - S01E10 - Guardian of the Abyss",
    "Hammer House of Horror S01E10 - Guardian of the Abyss.mp4"],
  ["hammer-house-of-horror-the-complete-series-1980", "HAMMER HOUSE OF HORROR - S01E11 - Visitor from the Grave",
    "Hammer House of Horror S01E11 - Visitor from the Grave.mp4"],
  ["hammer-house-of-horror-the-complete-series-1980", "HAMMER HOUSE OF HORROR - S01E12 - The Two Faces of Evil",
    "Hammer House of Horror S01E12 - Two Faces Of Evil.mp4"],
  ["hammer-house-of-horror-the-complete-series-1980", "HAMMER HOUSE OF HORROR - S01E13 - The Mark of Satan",
    "Hammer House of Horror S01E13 - The Mark of Satan.mp4"],
],
  durations: {
  "hammer-house-of-horror-the-complete-series-1980::Hammer House of Horror S01E01 - Witching Time.mp4": 3103,
  "hammer-house-of-horror-the-complete-series-1980::Hammer House of Horror S01E02 - The Thirteenth Reunion.mp4": 3104,
  "hammer-house-of-horror-the-complete-series-1980::Hammer House of Horror S01E03 - Rude Awakening.mp4": 3106,
  "hammer-house-of-horror-the-complete-series-1980::Hammer House of Horror S01E04 - Growing Pains.mp4": 3116,
  "hammer-house-of-horror-the-complete-series-1980::Hammer House of Horror S01E05 - The House that Bled to Death.mp4": 3103,
  "hammer-house-of-horror-the-complete-series-1980::Hammer House of Horror S01E06 - Charlie Boy.mp4": 3104,
  "hammer-house-of-horror-the-complete-series-1980::Hammer House of Horror S01E07 - The Silent Scream.mp4": 3104,
  "hammer-house-of-horror-the-complete-series-1980::Hammer House of Horror S01E08 - Children of the Full Moon.mp4": 3103,
  "hammer-house-of-horror-the-complete-series-1980::Hammer House of Horror S01E09 - The Carpathian Eagle.mp4": 3102,
  "hammer-house-of-horror-the-complete-series-1980::Hammer House of Horror S01E10 - Guardian of the Abyss.mp4": 3102,
  "hammer-house-of-horror-the-complete-series-1980::Hammer House of Horror S01E11 - Visitor from the Grave.mp4": 3103,
  "hammer-house-of-horror-the-complete-series-1980::Hammer House of Horror S01E12 - Two Faces Of Evil.mp4": 3100,
  "hammer-house-of-horror-the-complete-series-1980::Hammer House of Horror S01E13 - The Mark of Satan.mp4": 3103,
},
};
