window.SHOW = {
  id: "InspectorGadget",
  title: "Inspector Gadget",
  art: "InspectorGadget.jpg",
  storageProgressKey: "inspectorgadget-progress",
  storageSettingsKey: "inspectorgadget-settings",
  nestedPaths: true,
  grouping: "season",
  segments: "none",
  episodes: [
  ["inspector-gadget-1-1", "INSPECTOR GADGET - S01E00 - Winter Olympics (Pilot",
    "S01e00 Winter Olympics (Pilot).ia.mp4"],
  ["inspector-gadgets-field-trip", "INSPECTOR GADGET - S01E01 - Winter Olympics",
    "Inspector Gadget's Field Trip - Animals of Australia _ Barcelona.ia.mp4"],
  ["inspector-gadgets-field-trip", "INSPECTOR GADGET - S01E02 - Monster Lake",
    "Inspector Gadget's Field Trip - Australia _ Florida Keys.ia.mp4"],
  ["inspector-gadgets-field-trip", "INSPECTOR GADGET - S01E03 - Down on the Farm",
    "Inspector Gadget's Field Trip - Australia _ Hawaii.ia.mp4"],
  ["inspector-gadgets-field-trip", "INSPECTOR GADGET - S01E04 - Gadget at the Circus",
    "Inspector Gadget's Field Trip - Boston _ Tombstone.ia.mp4"],
  ["inspector-gadgets-field-trip", "INSPECTOR GADGET - S01E05 - The Amazon",
    "Inspector Gadget's Field Trip - China _ Hawaii.ia.mp4"],
  ["inspector-gadgets-field-trip", "INSPECTOR GADGET - S01E06 - Health Spa",
    "Inspector Gadget's Field Trip - Egypt _ China.ia.mp4"],
  ["inspector-gadgets-field-trip", "INSPECTOR GADGET - S01E07 - The Boat",
    "Inspector Gadget's Field Trip - Egypt.ia.mp4"],
  ["inspector-gadgets-field-trip", "INSPECTOR GADGET - S01E08 - Haunted Castle",
    "Inspector Gadget's Field Trip - Florida _ Colonial Williamsburg.ia.mp4"],
  ["inspector-gadgets-field-trip", "INSPECTOR GADGET - S01E09 - Race to the Finish",
    "Inspector Gadget's Field Trip - Florida Space Coast _ National Air and Space Museum.ia.mp4"],
  ["inspector-gadgets-field-trip", "INSPECTOR GADGET - S01E10 - The Ruby",
    "Inspector Gadget's Field Trip - Great Britain.ia.mp4"],
  ["inspector-gadgets-field-trip", "INSPECTOR GADGET - S01E11 - A Star Is Lost",
    "Inspector Gadget's Field Trip - Great Wall of China _ Venice Canals.ia.mp4"],
  ["inspector-gadgets-field-trip", "INSPECTOR GADGET - S01E12 - All That Glitters",
    "Inspector Gadget's Field Trip - Greek Islands _ Los Angeles.ia.mp4"],
  ["inspector-gadgets-field-trip", "INSPECTOR GADGET - S01E13 - Movie Set",
    "Inspector Gadget's Field Trip - Greek Islands.ia.mp4"],
  ["inspector-gadgets-field-trip", "INSPECTOR GADGET - S01E14 - Amusement Park",
    "Inspector Gadget's Field Trip - Hawaii _ Mt. Vesuvius.ia.mp4"],
  ["inspector-gadgets-field-trip", "INSPECTOR GADGET - S01E15 - Art Heist",
    "Inspector Gadget's Field Trip - Italy _ San Francisco.ia.mp4"],
  ["inspector-gadgets-field-trip", "INSPECTOR GADGET - S01E16 - Volcano Island (Gadget Goes Hawaiian)",
    "Inspector Gadget's Field Trip - Madrid _ Cowboys.ia.mp4"],
  ["inspector-gadgets-field-trip", "INSPECTOR GADGET - S01E17 - The Invasion",
    "Inspector Gadget's Field Trip - Native America _ Plymouth Plantation.ia.mp4"],
  ["inspector-gadgets-field-trip", "INSPECTOR GADGET - S01E18 - The Infiltration",
    "Inspector Gadget's Field Trip - New York City Sights.ia.mp4"],
  ["inspector-gadgets-field-trip", "INSPECTOR GADGET - S01E19 - The Curse of the Pharoah (Poot-Ta-Foot's Curse)",
    "Inspector Gadget's Field Trip - Paris Museums _ San Francisco.ia.mp4"],
  ["inspector-gadgets-field-trip", "INSPECTOR GADGET - S01E20 - M.A.D. Trap",
    "Inspector Gadget's Field Trip - Paris, France.ia.mp4"],
  ["inspector-gadgets-field-trip", "INSPECTOR GADGET - S01E21 - Basic Training",
    "Inspector Gadget's Field Trip - Quest for Gold _ Southwest.ia.mp4"],
  ["inspector-gadgets-field-trip", "INSPECTOR GADGET - S01E22 - Sleeping Gas",
    "Inspector Gadget's Field Trip - Rome _ Vatican City.ia.mp4"],
  ["inspector-gadgets-field-trip", "INSPECTOR GADGET - S01E23 - Gadget's Replacement",
    "Inspector Gadget's Field Trip - Smithsonian _ New York Museums.ia.mp4"],
  ["inspector-gadgets-field-trip", "INSPECTOR GADGET - S01E24 - Greenfinger",
    "Inspector Gadget's Field Trip - Sydney _ Alcatraz.ia.mp4"],
  ["inspector-gadgets-field-trip", "INSPECTOR GADGET - S01E25 - Gadget Goes West",
    "Inspector Gadget's Field Trip - Venice _ Nile River.ia.mp4"],
  ["inspector-gadgets-field-trip", "INSPECTOR GADGET - S01E26 - Launch Time",
    "Inspector Gadget's Field Trip - Washington DC.ia.mp4"],
  ["inspector-gadget-1-1", "INSPECTOR GADGET - S01E27 - Photo Safari",
    "S01e27 The Coo Coo Clock Caper.ia.mp4"],
  ["inspector-gadget-1-1", "INSPECTOR GADGET - S01E28 - The Coo Coo Clock Caper",
    "S01e28 Bermuda Triangle.ia.mp4"],
  ["inspector-gadget-1-1", "INSPECTOR GADGET - S01E29 - Bermuda Triangle",
    "S01e29 The Japanese Connection.ia.mp4"],
  ["inspector-gadget-1-1", "INSPECTOR GADGET - S01E30 - The Japanese Connection",
    "S01e30 Arabian Nights.ia.mp4"],
  ["inspector-gadget-1-1", "INSPECTOR GADGET - S01E32 - A Clear Case",
    "S01e32 Clear Case.ia.mp4"],
  ["inspector-gadget-1-1", "INSPECTOR GADGET - S01E33 - Dutch Treat",
    "S01e33 The Great Divide.ia.mp4"],
  ["inspector-gadget-1-1", "INSPECTOR GADGET - S01E34 - The Great Divide",
    "S01e34 Eye Of The Dragon.ia.mp4"],
  ["inspector-gadget-1-1", "INSPECTOR GADGET - S01E35 - Eye of the Dragon",
    "S01e35 Doubled Agent.ia.mp4"],
  ["inspector-gadget-1-2", "INSPECTOR GADGET - S01E36 - Doubled Agent",
    "S01e36 Plantform Of The Opera.ia.mp4"],
  ["inspector-gadget-1-2", "INSPECTOR GADGET - S01E37 - Plantform of the Opera",
    "S01e37 Don't Hold Your Breath.ia.mp4"],
  ["inspector-gadget-1-2", "INSPECTOR GADGET - S01E38 - Don't Hold Your Breath",
    "S01e38 Gone Went The Wind.ia.mp4"],
  ["inspector-gadget-1-2", "INSPECTOR GADGET - S01E39 - Gone Went the Wind",
    "S01e39 King Wrong.ia.mp4"],
  ["inspector-gadget-1-2", "INSPECTOR GADGET - S01E40 - King Wrong",
    "S01e40 Pirate Island.ia.mp4"],
  ["inspector-gadget-1-2", "INSPECTOR GADGET - S01E41 - Pirate Island",
    "S01e41 M.A.D. Academy.ia.mp4"],
  ["inspector-gadget-1-2", "INSPECTOR GADGET - S01E42 - M.A.D. Acadamy",
    "S01e42 No Flies On Us.ia.mp4"],
  ["inspector-gadget-1-2", "INSPECTOR GADGET - S01E43 - No Flies on Us",
    "S01e43 Luck Of The Irish.ia.mp4"],
  ["inspector-gadget-1-2", "INSPECTOR GADGET - S01E44 - Luck of the Irish",
    "S01e44 Prince Of The Gypsies.ia.mp4"],
  ["inspector-gadget-1-2", "INSPECTOR GADGET - S01E45 - Prince of the Gypsies",
    "S01e45 Old Man Of The Mountain.ia.mp4"],
  ["inspector-gadget-1-2", "INSPECTOR GADGET - S01E46 - Old Man of the Mountain",
    "S01e46 The Emerald Duck.ia.mp4"],
  ["inspector-gadget-1-2", "INSPECTOR GADGET - S01E47 - The Emerald Duck",
    "S01e47 Do Unto Udders.ia.mp4"],
  ["inspector-gadget-1-2", "INSPECTOR GADGET - S01E48 - Do Unto Udders",
    "S01e48 Did You Myth Me.ia.mp4"],
  ["inspector-gadget-1-2", "INSPECTOR GADGET - S01E49 - Did You Myth Me?",
    "S01e49 A Bad Altitude.ia.mp4"],
  ["inspector-gadget-1-2", "INSPECTOR GADGET - S01E50 - A Bad Altitude",
    "S01e50 Funny Money.ia.mp4"],
  ["inspector-gadget-1-2", "INSPECTOR GADGET - S01E51 - Funny Money",
    "S01e51 Follow That Jet.ia.mp4"],
  ["inspector-gadget-1-2", "INSPECTOR GADGET - S01E52 - Follow That Jet",
    "S01e52 Dry Spell.ia.mp4"],
  ["inspector-gadget-1-2", "INSPECTOR GADGET - S01E53 - Dry Spell",
    "S01e53 Smeldorado.ia.mp4"],
  ["inspector-gadget-1-2", "INSPECTOR GADGET - S01E54 - Smeldorado",
    "S01e54 Quimby Exchange.ia.mp4"],
  ["inspector-gadget-1-2", "INSPECTOR GADGET - S01E55 - Quimby Exchange",
    "S01e55 Weather In Tibet.ia.mp4"],
  ["inspector-gadget-1-2", "INSPECTOR GADGET - S01E56 - Weather in Tibet",
    "S01e56 Unhenged.ia.mp4"],
  ["inspector-gadget-1-2", "INSPECTOR GADGET - S01E57 - Unhenged",
    "S01e57 Snakin' All Over.ia.mp4"],
  ["inspector-gadget-1-2", "INSPECTOR GADGET - S01E58 - Snakin' All Over",
    "S01e58 In Seine.ia.mp4"],
  ["inspector-gadget-1-2", "INSPECTOR GADGET - S01E59 - In Seine",
    "S01e59 Tree Guesses.ia.mp4"],
  ["inspector-gadget-1-2", "INSPECTOR GADGET - S01E60 - Tree Guesses",
    "S01e60 Birds Of A Feather.ia.mp4"],
  ["inspector-gadget-1-2", "INSPECTOR GADGET - S01E61 - Birds of a Feather",
    "S01e61 So It Is Written.ia.mp4"],
  ["inspector-gadget-1-2", "INSPECTOR GADGET - S01E62 - So It Is Written",
    "S01e62 Fang The Wonder Dog.ia.mp4"],
  ["inspector-gadget-1-2", "INSPECTOR GADGET - S01E63 - Fang the Wonder Dog",
    "S01e63 School For Pickpockets.ia.mp4"],
  ["inspector-gadget-1-2", "INSPECTOR GADGET - S01E64 - School for Pickpockets",
    "S01e64 Quizz Master.ia.mp4"],
  ["inspector-gadget-2", "INSPECTOR GADGET - S02E01 - Magic Gadget",
    "S02E01_Gadget In Mini-Madness.ia.mp4"],
  ["inspector-gadget-2", "INSPECTOR GADGET - S02E02 - The Great Wambini's Seance",
    "S02E02_The Incredible Shrinking Gadget.ia.mp4"],
  ["inspector-gadget-2", "INSPECTOR GADGET - S02E03 - Wambini Predicts",
    "S02E03_Gadget Meets The Grappler.ia.mp4"],
  ["inspector-gadget-2", "INSPECTOR GADGET - S02E04 - The Capeman Cometh",
    "S02E04_Focus On Gadget.ia.mp4"],
  ["inspector-gadget-2", "INSPECTOR GADGET - S02E05 - Crashcourse in Crime",
    "S02E05_Mad In The Moon.ia.mp4"],
  ["inspector-gadget-2", "INSPECTOR GADGET - S02E06 - Gadget's Gadgets",
    "S02E06_N_S_F_ Gadget.ia.mp4"],
  ["inspector-gadget-2", "INSPECTOR GADGET - S02E07 - Gadget in Minimadness",
    "S02E07_Magic Gadget.ia.mp4"],
  ["inspector-gadget-2", "INSPECTOR GADGET - S02E08 - The Incredible Shrinking Gadget",
    "S02E08_The Great Wambini's Seance.ia.mp4"],
  ["inspector-gadget-2", "INSPECTOR GADGET - S02E09 - Gadget Meets the Grappler",
    "S02E09_Wambini Predicts.ia.mp4"],
  ["inspector-gadget-2", "INSPECTOR GADGET - S02E10 - Ghost Catchers",
    "S02E10_Bad Dreams Are Made Of This.ia.mp4"],
  ["inspector-gadget-2", "INSPECTOR GADGET - S02E11 - Busy Signal",
    "S02E11_Ghost Catchers.ia.mp4"],
  ["inspector-gadget-2", "INSPECTOR GADGET - S02E12 - Bad Dreams Are Made of This",
    "S02E12_Busy Signal.ia.mp4"],
  ["inspector-gadget-2", "INSPECTOR GADGET - S02E13 - Focus on Gadget",
    "S02E13_The Capeman Cometh.ia.mp4"],
  ["inspector-gadget-2", "INSPECTOR GADGET - S02E14 - M.A.D. in the Moon",
    "S02E14_Crashcourse In Crime.ia.mp4"],
  ["inspector-gadget-2", "INSPECTOR GADGET - S02E15 - N.S.F. Gadget",
    "S02E15_Gadget's Gadgets.ia.mp4"],
  ["inspector-gadget-2", "INSPECTOR GADGET - S02E16 - Tyrannosaurus Gadget",
    "S02E16_Tyrannosaurus Gadget.ia.mp4"],
  ["inspector-gadget-2", "INSPECTOR GADGET - S02E17 - Gadget's Roma",
    "S02E17_Gadget's Roma.ia.mp4"],
  ["inspector-gadget-2", "INSPECTOR GADGET - S02E18 - Gadget's Clean Sweep",
    "S02E18_Gadget's Clean Sweep.ia.mp4"],
  ["inspector-gadget-2", "INSPECTOR GADGET - S02E19 - Gadget Meets the Clan",
    "S02E19_Gadget Meets The Clan.ia.mp4"],
  ["inspector-gadget-2", "INSPECTOR GADGET - S02E20 - Gadget and Old Lace",
    "S02E20_Gadget And Old Lace.ia.mp4"],
  ["inspector-gadget-2", "INSPECTOR GADGET - S02E21 - Gadget and the Red Rose",
    "S02E21_Gadget And The Red Rose.ia.mp4"],
],
  durations: {
  "inspector-gadget-1-1::S01e00 Winter Olympics (Pilot).ia.mp4": 1348,
  "inspector-gadgets-field-trip::Inspector Gadget's Field Trip - Animals of Australia _ Barcelona.ia.mp4": 1336,
  "inspector-gadgets-field-trip::Inspector Gadget's Field Trip - Australia _ Florida Keys.ia.mp4": 1337,
  "inspector-gadgets-field-trip::Inspector Gadget's Field Trip - Australia _ Hawaii.ia.mp4": 1336,
  "inspector-gadgets-field-trip::Inspector Gadget's Field Trip - Boston _ Tombstone.ia.mp4": 1336,
  "inspector-gadgets-field-trip::Inspector Gadget's Field Trip - China _ Hawaii.ia.mp4": 1336,
  "inspector-gadgets-field-trip::Inspector Gadget's Field Trip - Egypt _ China.ia.mp4": 1338,
  "inspector-gadgets-field-trip::Inspector Gadget's Field Trip - Egypt.ia.mp4": 1336,
  "inspector-gadgets-field-trip::Inspector Gadget's Field Trip - Florida _ Colonial Williamsburg.ia.mp4": 1336,
  "inspector-gadgets-field-trip::Inspector Gadget's Field Trip - Florida Space Coast _ National Air and Space Museum.ia.mp4": 1336,
  "inspector-gadgets-field-trip::Inspector Gadget's Field Trip - Great Britain.ia.mp4": 1348,
  "inspector-gadgets-field-trip::Inspector Gadget's Field Trip - Great Wall of China _ Venice Canals.ia.mp4": 1336,
  "inspector-gadgets-field-trip::Inspector Gadget's Field Trip - Greek Islands _ Los Angeles.ia.mp4": 1336,
  "inspector-gadgets-field-trip::Inspector Gadget's Field Trip - Greek Islands.ia.mp4": 1336,
  "inspector-gadgets-field-trip::Inspector Gadget's Field Trip - Hawaii _ Mt. Vesuvius.ia.mp4": 1337,
  "inspector-gadgets-field-trip::Inspector Gadget's Field Trip - Italy _ San Francisco.ia.mp4": 1335,
  "inspector-gadgets-field-trip::Inspector Gadget's Field Trip - Madrid _ Cowboys.ia.mp4": 1336,
  "inspector-gadgets-field-trip::Inspector Gadget's Field Trip - Native America _ Plymouth Plantation.ia.mp4": 1336,
  "inspector-gadgets-field-trip::Inspector Gadget's Field Trip - New York City Sights.ia.mp4": 1335,
  "inspector-gadgets-field-trip::Inspector Gadget's Field Trip - Paris Museums _ San Francisco.ia.mp4": 1368,
  "inspector-gadgets-field-trip::Inspector Gadget's Field Trip - Paris, France.ia.mp4": 1336,
  "inspector-gadgets-field-trip::Inspector Gadget's Field Trip - Quest for Gold _ Southwest.ia.mp4": 1335,
  "inspector-gadgets-field-trip::Inspector Gadget's Field Trip - Rome _ Vatican City.ia.mp4": 1336,
  "inspector-gadgets-field-trip::Inspector Gadget's Field Trip - Smithsonian _ New York Museums.ia.mp4": 1334,
  "inspector-gadgets-field-trip::Inspector Gadget's Field Trip - Sydney _ Alcatraz.ia.mp4": 1336,
  "inspector-gadgets-field-trip::Inspector Gadget's Field Trip - Venice _ Nile River.ia.mp4": 1337,
  "inspector-gadgets-field-trip::Inspector Gadget's Field Trip - Washington DC.ia.mp4": 1336,
  "inspector-gadget-1-1::S01e27 The Coo Coo Clock Caper.ia.mp4": 1351,
  "inspector-gadget-1-1::S01e28 Bermuda Triangle.ia.mp4": 1348,
  "inspector-gadget-1-1::S01e29 The Japanese Connection.ia.mp4": 1351,
  "inspector-gadget-1-1::S01e30 Arabian Nights.ia.mp4": 1316,
  "inspector-gadget-1-1::S01e32 Clear Case.ia.mp4": 1349,
  "inspector-gadget-1-1::S01e33 The Great Divide.ia.mp4": 1345,
  "inspector-gadget-1-1::S01e34 Eye Of The Dragon.ia.mp4": 1347,
  "inspector-gadget-1-1::S01e35 Doubled Agent.ia.mp4": 1346,
  "inspector-gadget-1-2::S01e36 Plantform Of The Opera.ia.mp4": 1346,
  "inspector-gadget-1-2::S01e37 Don't Hold Your Breath.ia.mp4": 1350,
  "inspector-gadget-1-2::S01e38 Gone Went The Wind.ia.mp4": 1350,
  "inspector-gadget-1-2::S01e39 King Wrong.ia.mp4": 1347,
  "inspector-gadget-1-2::S01e40 Pirate Island.ia.mp4": 1347,
  "inspector-gadget-1-2::S01e41 M.A.D. Academy.ia.mp4": 1347,
  "inspector-gadget-1-2::S01e42 No Flies On Us.ia.mp4": 1347,
  "inspector-gadget-1-2::S01e43 Luck Of The Irish.ia.mp4": 1347,
  "inspector-gadget-1-2::S01e44 Prince Of The Gypsies.ia.mp4": 1346,
  "inspector-gadget-1-2::S01e45 Old Man Of The Mountain.ia.mp4": 1346,
  "inspector-gadget-1-2::S01e46 The Emerald Duck.ia.mp4": 1346,
  "inspector-gadget-1-2::S01e47 Do Unto Udders.ia.mp4": 1348,
  "inspector-gadget-1-2::S01e48 Did You Myth Me.ia.mp4": 1348,
  "inspector-gadget-1-2::S01e49 A Bad Altitude.ia.mp4": 1348,
  "inspector-gadget-1-2::S01e50 Funny Money.ia.mp4": 1348,
  "inspector-gadget-1-2::S01e51 Follow That Jet.ia.mp4": 1347,
  "inspector-gadget-1-2::S01e52 Dry Spell.ia.mp4": 1347,
  "inspector-gadget-1-2::S01e53 Smeldorado.ia.mp4": 1349,
  "inspector-gadget-1-2::S01e54 Quimby Exchange.ia.mp4": 1349,
  "inspector-gadget-1-2::S01e55 Weather In Tibet.ia.mp4": 1349,
  "inspector-gadget-1-2::S01e56 Unhenged.ia.mp4": 1348,
  "inspector-gadget-1-2::S01e57 Snakin' All Over.ia.mp4": 1347,
  "inspector-gadget-1-2::S01e58 In Seine.ia.mp4": 1347,
  "inspector-gadget-1-2::S01e59 Tree Guesses.ia.mp4": 1346,
  "inspector-gadget-1-2::S01e60 Birds Of A Feather.ia.mp4": 1348,
  "inspector-gadget-1-2::S01e61 So It Is Written.ia.mp4": 1347,
  "inspector-gadget-1-2::S01e62 Fang The Wonder Dog.ia.mp4": 1346,
  "inspector-gadget-1-2::S01e63 School For Pickpockets.ia.mp4": 1349,
  "inspector-gadget-1-2::S01e64 Quizz Master.ia.mp4": 1349,
  "inspector-gadget-2::S02E01_Gadget In Mini-Madness.ia.mp4": 1265,
  "inspector-gadget-2::S02E02_The Incredible Shrinking Gadget.ia.mp4": 1255,
  "inspector-gadget-2::S02E03_Gadget Meets The Grappler.ia.mp4": 1266,
  "inspector-gadget-2::S02E04_Focus On Gadget.ia.mp4": 1265,
  "inspector-gadget-2::S02E05_Mad In The Moon.ia.mp4": 1264,
  "inspector-gadget-2::S02E06_N_S_F_ Gadget.ia.mp4": 1222,
  "inspector-gadget-2::S02E07_Magic Gadget.ia.mp4": 1264,
  "inspector-gadget-2::S02E08_The Great Wambini's Seance.ia.mp4": 1320,
  "inspector-gadget-2::S02E09_Wambini Predicts.ia.mp4": 1320,
  "inspector-gadget-2::S02E10_Bad Dreams Are Made Of This.ia.mp4": 1265,
  "inspector-gadget-2::S02E11_Ghost Catchers.ia.mp4": 1266,
  "inspector-gadget-2::S02E12_Busy Signal.ia.mp4": 1266,
  "inspector-gadget-2::S02E13_The Capeman Cometh.ia.mp4": 1310,
  "inspector-gadget-2::S02E14_Crashcourse In Crime.ia.mp4": 1320,
  "inspector-gadget-2::S02E15_Gadget's Gadgets.ia.mp4": 1266,
  "inspector-gadget-2::S02E16_Tyrannosaurus Gadget.ia.mp4": 1265,
  "inspector-gadget-2::S02E17_Gadget's Roma.ia.mp4": 1265,
  "inspector-gadget-2::S02E18_Gadget's Clean Sweep.ia.mp4": 1265,
  "inspector-gadget-2::S02E19_Gadget Meets The Clan.ia.mp4": 1257,
  "inspector-gadget-2::S02E20_Gadget And Old Lace.ia.mp4": 1265,
  "inspector-gadget-2::S02E21_Gadget And The Red Rose.ia.mp4": 1266,
},
};
