window.SHOW = {
  id: "HeathcliffandtheCatillacCatsTVSeries",
  title: "Heathcliff and the Catillac Cats TV Series",
  art: "HeathcliffandtheCatillacCatsTVSeries.png",
  storageProgressKey: "heathcliffandthecatillaccatstvseries-progress",
  storageSettingsKey: "heathcliffandthecatillaccatstvseries-settings",
  nestedPaths: true,
  grouping: "season",
  segments: "none",
  episodes: [
  ["heathcliff-and-the-catillac-cats-1984-complete-series", "HEATHCLIFF AND THE CATILLAC CATS TV SERIES - S01E01 - Heathcliff E01 The Great Pussini",
    "Heathcliff E01 - The Great Pussini.mp4"],
  ["heathcliff-and-the-catillac-cats-1984-complete-series", "HEATHCLIFF AND THE CATILLAC CATS TV SERIES - S01E02 - Heathcliff E02 Kitty Kat Kennels",
    "Heathcliff E02 - Kitty Kat Kennels.mp4"],
  ["heathcliff-and-the-catillac-cats-1984-complete-series", "HEATHCLIFF AND THE CATILLAC CATS TV SERIES - S01E03 - Heathcliff E03 Chauncey's Great Escape",
    "Heathcliff E03 - Chauncey's Great Escape.mp4"],
  ["heathcliff-and-the-catillac-cats-1984-complete-series", "HEATHCLIFF AND THE CATILLAC CATS TV SERIES - S01E04 - Heathcliff E04 Carnival Capers",
    "Heathcliff E04 - Carnival Capers.mp4"],
  ["heathcliff-and-the-catillac-cats-1984-complete-series", "HEATHCLIFF AND THE CATILLAC CATS TV SERIES - S01E05 - Heathcliff E05 Mad Dog Catcher",
    "Heathcliff E05 - Mad Dog Catcher.mp4"],
  ["heathcliff-and-the-catillac-cats-1984-complete-series", "HEATHCLIFF AND THE CATILLAC CATS TV SERIES - S01E06 - Heathcliff E06 Circus Beserkus",
    "Heathcliff E06 - Circus Beserkus.mp4"],
  ["heathcliff-and-the-catillac-cats-1984-complete-series", "HEATHCLIFF AND THE CATILLAC CATS TV SERIES - S01E07 - Heathcliff E07 Rebel Without a Claws",
    "Heathcliff E07 - Rebel Without a Claws.mp4"],
  ["heathcliff-and-the-catillac-cats-1984-complete-series", "HEATHCLIFF AND THE CATILLAC CATS TV SERIES - S01E08 - Heathcliff E08 The Farming Life Ain't For Me",
    "Heathcliff E08 - The Farming Life Ain't For Me.mp4"],
  ["heathcliff-and-the-catillac-cats-1984-complete-series", "HEATHCLIFF AND THE CATILLAC CATS TV SERIES - S01E09 - Heathcliff E09 Heathcliff's Middle Name",
    "Heathcliff E09 - Heathcliff's Middle Name.mp4"],
  ["heathcliff-and-the-catillac-cats-1984-complete-series", "HEATHCLIFF AND THE CATILLAC CATS TV SERIES - S01E10 - Heathcliff E10 Wishful Thinking",
    "Heathcliff E10 - Wishful Thinking.mp4"],
  ["heathcliff-and-the-catillac-cats-1984-complete-series", "HEATHCLIFF AND THE CATILLAC CATS TV SERIES - S01E11 - Heathcliff E11 Teed Off",
    "Heathcliff E11 - Teed Off.mp4"],
  ["heathcliff-and-the-catillac-cats-1984-complete-series", "HEATHCLIFF AND THE CATILLAC CATS TV SERIES - S01E12 - Heathcliff E12 Monstro vs. the Wolf Hound",
    "Heathcliff E12 - Monstro vs. the Wolf Hound.mp4"],
  ["heathcliff-and-the-catillac-cats-1984-complete-series", "HEATHCLIFF AND THE CATILLAC CATS TV SERIES - S01E13 - Heathcliff E13 Say Cheese",
    "Heathcliff E13 - Say Cheese.mp4"],
  ["heathcliff-and-the-catillac-cats-1984-complete-series", "HEATHCLIFF AND THE CATILLAC CATS TV SERIES - S01E14 - Heathcliff E14 Cat's Angels",
    "Heathcliff E14 - Cat's Angels.mp4"],
  ["heathcliff-and-the-catillac-cats-1984-complete-series", "HEATHCLIFF AND THE CATILLAC CATS TV SERIES - S01E15 - Heathcliff E15 Meow Meow Island",
    "Heathcliff E15 - Meow Meow Island.mp4"],
  ["heathcliff-and-the-catillac-cats-1984-complete-series", "HEATHCLIFF AND THE CATILLAC CATS TV SERIES - S01E16 - Heathcliff E16 Iron Cats",
    "Heathcliff E16 - Iron Cats.mp4"],
  ["heathcliff-and-the-catillac-cats-1984-complete-series", "HEATHCLIFF AND THE CATILLAC CATS TV SERIES - S01E17 - Heathcliff E17 Family Tree",
    "Heathcliff E17 - Family Tree.mp4"],
  ["heathcliff-and-the-catillac-cats-1984-complete-series", "HEATHCLIFF AND THE CATILLAC CATS TV SERIES - S01E18 - Heathcliff E18 Who's Got the Chocolate",
    "Heathcliff E18 - Who's Got the Chocolate.mp4"],
  ["heathcliff-and-the-catillac-cats-1984-complete-series", "HEATHCLIFF AND THE CATILLAC CATS TV SERIES - S01E19 - Heathcliff E19 Be Prepared",
    "Heathcliff E19 - Be Prepared.mp4"],
  ["heathcliff-and-the-catillac-cats-1984-complete-series", "HEATHCLIFF AND THE CATILLAC CATS TV SERIES - S01E20 - Heathcliff E20 Cruisin' for a Bruisin",
    "Heathcliff E20 - Cruisin' for a Bruisin'.mp4"],
  ["heathcliff-and-the-catillac-cats-1984-complete-series", "HEATHCLIFF AND THE CATILLAC CATS TV SERIES - S01E21 - Heathcliff E21 Heathcliff Gets Canned",
    "Heathcliff E21 - Heathcliff Gets Canned.mp4"],
  ["heathcliff-and-the-catillac-cats-1984-complete-series", "HEATHCLIFF AND THE CATILLAC CATS TV SERIES - S01E22 - Heathcliff E22 Wild Cat Heathcliff",
    "Heathcliff E22 - Wild Cat Heathcliff.mp4"],
  ["heathcliff-and-the-catillac-cats-1984-complete-series", "HEATHCLIFF AND THE CATILLAC CATS TV SERIES - S01E23 - Heathcliff E23 Kitten Around",
    "Heathcliff E23 - Kitten Around.mp4"],
  ["heathcliff-and-the-catillac-cats-1984-complete-series", "HEATHCLIFF AND THE CATILLAC CATS TV SERIES - S01E24 - Heathcliff E24 Cat Burglar Heathcliff",
    "Heathcliff E24 - Cat Burglar Heathcliff.mp4"],
  ["heathcliff-and-the-catillac-cats-1984-complete-series", "HEATHCLIFF AND THE CATILLAC CATS TV SERIES - S01E25 - Heathcliff E25 Lucky's Unlucky Day",
    "Heathcliff E25 - Lucky's Unlucky Day.mp4"],
  ["heathcliff-and-the-catillac-cats-1984-complete-series", "HEATHCLIFF AND THE CATILLAC CATS TV SERIES - S01E26 - Heathcliff E26 The Blizzard Bandit",
    "Heathcliff E26 - The Blizzard Bandit.mp4"],
  ["heathcliff-and-the-catillac-cats-1984-complete-series", "HEATHCLIFF AND THE CATILLAC CATS TV SERIES - S01E27 - Heathcliff E27 Harem Cat",
    "Heathcliff E27 - Harem Cat.mp4"],
  ["heathcliff-and-the-catillac-cats-1984-complete-series", "HEATHCLIFF AND THE CATILLAC CATS TV SERIES - S01E28 - Heathcliff E28 Kitten Smitten",
    "Heathcliff E28 - Kitten Smitten.mp4"],
  ["heathcliff-and-the-catillac-cats-1984-complete-series", "HEATHCLIFF AND THE CATILLAC CATS TV SERIES - S01E29 - Heathcliff E29 Young Cat with a Horn",
    "Heathcliff E29 - Young Cat with a Horn.mp4"],
  ["heathcliff-and-the-catillac-cats-1984-complete-series", "HEATHCLIFF AND THE CATILLAC CATS TV SERIES - S01E30 - Heathcliff E30 The Gang's All Here",
    "Heathcliff E30 - The Gang's All Here.mp4"],
  ["heathcliff-and-the-catillac-cats-1984-complete-series", "HEATHCLIFF AND THE CATILLAC CATS TV SERIES - S01E31 - Heathcliff E31 The Meowsic Goes Round and Round",
    "Heathcliff E31 - The Meowsic Goes Round and Round.mp4"],
  ["heathcliff-and-the-catillac-cats-1984-complete-series", "HEATHCLIFF AND THE CATILLAC CATS TV SERIES - S01E32 - Heathcliff E32 Snow Job",
    "Heathcliff E32 - Snow Job.mp4"],
  ["heathcliff-and-the-catillac-cats-1984-complete-series", "HEATHCLIFF AND THE CATILLAC CATS TV SERIES - S01E33 - Heathcliff E33 Spike's Slave",
    "Heathcliff E33 - Spike's Slave.mp4"],
  ["heathcliff-and-the-catillac-cats-1984-complete-series", "HEATHCLIFF AND THE CATILLAC CATS TV SERIES - S01E34 - Heathcliff E34 Scaredy Cats",
    "Heathcliff E34 - Scaredy Cats.mp4"],
  ["heathcliff-and-the-catillac-cats-1984-complete-series", "HEATHCLIFF AND THE CATILLAC CATS TV SERIES - S01E35 - Heathcliff E35 Gopher Broke",
    "Heathcliff E35 - Gopher Broke.mp4"],
  ["heathcliff-and-the-catillac-cats-1984-complete-series", "HEATHCLIFF AND THE CATILLAC CATS TV SERIES - S01E36 - Heathcliff E36 A Camping We Will Go",
    "Heathcliff E36 - A Camping We Will Go.mp4"],
  ["heathcliff-and-the-catillac-cats-1984-complete-series", "HEATHCLIFF AND THE CATILLAC CATS TV SERIES - S01E37 - Heathcliff E37 Where There's an Ill, There's a Way",
    "Heathcliff E37 - Where There's an Ill, There's a Way.mp4"],
  ["heathcliff-and-the-catillac-cats-1984-complete-series", "HEATHCLIFF AND THE CATILLAC CATS TV SERIES - S01E38 - Heathcliff E38 Yes Sewer That's my Baby",
    "Heathcliff E38 - Yes Sewer That's my Baby.mp4"],
  ["heathcliff-and-the-catillac-cats-1984-complete-series", "HEATHCLIFF AND THE CATILLAC CATS TV SERIES - S01E39 - Heathcliff E39 Soap Box Derby",
    "Heathcliff E39 - Soap Box Derby.mp4"],
  ["heathcliff-and-the-catillac-cats-1984-complete-series", "HEATHCLIFF AND THE CATILLAC CATS TV SERIES - S01E40 - Heathcliff E40 A Better Mousetrap",
    "Heathcliff E40 - A Better Mousetrap.mp4"],
  ["heathcliff-and-the-catillac-cats-1984-complete-series", "HEATHCLIFF AND THE CATILLAC CATS TV SERIES - S01E41 - Heathcliff E41 Bamboo Island",
    "Heathcliff E41 - Bamboo Island.mp4"],
  ["heathcliff-and-the-catillac-cats-1984-complete-series", "HEATHCLIFF AND THE CATILLAC CATS TV SERIES - S01E42 - Heathcliff E42 Superhero Mungo",
    "Heathcliff E42 - Superhero Mungo.mp4"],
  ["heathcliff-and-the-catillac-cats-1984-complete-series", "HEATHCLIFF AND THE CATILLAC CATS TV SERIES - S01E43 - Heathcliff E43 Butter Up",
    "Heathcliff E43 - Butter Up.mp4"],
  ["heathcliff-and-the-catillac-cats-1984-complete-series", "HEATHCLIFF AND THE CATILLAC CATS TV SERIES - S01E44 - Heathcliff E44 The Siamese Twins",
    "Heathcliff E44 - The Siamese Twins.mp4"],
  ["heathcliff-and-the-catillac-cats-1984-complete-series", "HEATHCLIFF AND THE CATILLAC CATS TV SERIES - S01E45 - Heathcliff E45 The Mungo Mash",
    "Heathcliff E45 - The Mungo Mash.mp4"],
  ["heathcliff-and-the-catillac-cats-1984-complete-series", "HEATHCLIFF AND THE CATILLAC CATS TV SERIES - S01E46 - Heathcliff E46 Copa ca Heathcliff",
    "Heathcliff E46 - Copa-ca-Heathcliff.mp4"],
  ["heathcliff-and-the-catillac-cats-1984-complete-series", "HEATHCLIFF AND THE CATILLAC CATS TV SERIES - S01E47 - Heathcliff E47 Leroy's in Love",
    "Heathcliff E47 - Leroy's in Love.mp4"],
  ["heathcliff-and-the-catillac-cats-1984-complete-series", "HEATHCLIFF AND THE CATILLAC CATS TV SERIES - S01E48 - Heathcliff E48 Used Pets",
    "Heathcliff E48 - Used Pets.mp4"],
  ["heathcliff-and-the-catillac-cats-1984-complete-series", "HEATHCLIFF AND THE CATILLAC CATS TV SERIES - S01E49 - Heathcliff E49 Search for a Star",
    "Heathcliff E49 - Search for a Star.mp4"],
  ["heathcliff-and-the-catillac-cats-1984-complete-series", "HEATHCLIFF AND THE CATILLAC CATS TV SERIES - S01E50 - Heathcliff E50 An Officer and an Alley Cat",
    "Heathcliff E50 - An Officer and an Alley-Cat.mp4"],
  ["heathcliff-and-the-catillac-cats-1984-complete-series", "HEATHCLIFF AND THE CATILLAC CATS TV SERIES - S01E51 - Heathcliff E51 Hector Spector",
    "Heathcliff E51 - Hector Spector.mp4"],
  ["heathcliff-and-the-catillac-cats-1984-complete-series", "HEATHCLIFF AND THE CATILLAC CATS TV SERIES - S01E52 - Heathcliff E52 Service with a Smile",
    "Heathcliff E52 - Service with a Smile.mp4"],
  ["heathcliff-and-the-catillac-cats-1984-complete-series", "HEATHCLIFF AND THE CATILLAC CATS TV SERIES - S01E53 - Heathcliff E53 Junk Food",
    "Heathcliff E53 - Junk Food.mp4"],
  ["heathcliff-and-the-catillac-cats-1984-complete-series", "HEATHCLIFF AND THE CATILLAC CATS TV SERIES - S01E54 - Heathcliff E54 Boom Boom Pussini",
    "Heathcliff E54 - Boom Boom Pussini.mp4"],
  ["heathcliff-and-the-catillac-cats-1984-complete-series", "HEATHCLIFF AND THE CATILLAC CATS TV SERIES - S01E55 - Heathcliff E55 Heathcliff Surprise",
    "Heathcliff E55 - Heathcliff Surprise.mp4"],
  ["heathcliff-and-the-catillac-cats-1984-complete-series", "HEATHCLIFF AND THE CATILLAC CATS TV SERIES - S01E56 - Heathcliff E56 The Big Break In",
    "Heathcliff E56 - The Big Break-In.mp4"],
  ["heathcliff-and-the-catillac-cats-1984-complete-series", "HEATHCLIFF AND THE CATILLAC CATS TV SERIES - S01E57 - Heathcliff E57 The Catfather",
    "Heathcliff E57 - The Catfather.mp4"],
  ["heathcliff-and-the-catillac-cats-1984-complete-series", "HEATHCLIFF AND THE CATILLAC CATS TV SERIES - S01E58 - Heathcliff E58 The Big Swipe",
    "Heathcliff E58 - The Big Swipe.mp4"],
  ["heathcliff-and-the-catillac-cats-1984-complete-series", "HEATHCLIFF AND THE CATILLAC CATS TV SERIES - S01E59 - Heathcliff E59 Tally Ho Heathcliff",
    "Heathcliff E59 - Tally-Ho Heathcliff.mp4"],
  ["heathcliff-and-the-catillac-cats-1984-complete-series", "HEATHCLIFF AND THE CATILLAC CATS TV SERIES - S01E60 - Heathcliff E60 The Baby Buggy Bad Guys",
    "Heathcliff E60 - The Baby Buggy Bad Guys.mp4"],
  ["heathcliff-and-the-catillac-cats-1984-complete-series", "HEATHCLIFF AND THE CATILLAC CATS TV SERIES - S01E61 - Heathcliff E61 Grandpa vs. Grandpa",
    "Heathcliff E61 - Grandpa vs. Grandpa.mp4"],
  ["heathcliff-and-the-catillac-cats-1984-complete-series", "HEATHCLIFF AND THE CATILLAC CATS TV SERIES - S01E62 - Heathcliff E62 The Big Game Hunter",
    "Heathcliff E62 - The Big Game Hunter.mp4"],
  ["heathcliff-and-the-catillac-cats-1984-complete-series", "HEATHCLIFF AND THE CATILLAC CATS TV SERIES - S01E63 - Heathcliff E63 The Great Tuna Caper",
    "Heathcliff E63 - The Great Tuna Caper.mp4"],
  ["heathcliff-and-the-catillac-cats-1984-complete-series", "HEATHCLIFF AND THE CATILLAC CATS TV SERIES - S01E64 - Heathcliff E64 Peco's Treasure",
    "Heathcliff E64 - Peco's Treasure.mp4"],
  ["heathcliff-and-the-catillac-cats-1984-complete-series", "HEATHCLIFF AND THE CATILLAC CATS TV SERIES - S01E65 - Heathcliff E65 Cleo Moves In",
    "Heathcliff E65 - Cleo Moves In.mp4"],
  ["heathcliff-and-the-catillac-cats-1984-complete-series", "HEATHCLIFF AND THE CATILLAC CATS TV SERIES - S01E66 - Heathcliff E66 The White Cliffs of Dover",
    "Heathcliff E66 - The White Cliffs of Dover.ia.mp4"],
  ["heathcliff-and-the-catillac-cats-1984-complete-series", "HEATHCLIFF AND THE CATILLAC CATS TV SERIES - S01E67 - Heathcliff E67 Nightmare in Beverly Hills + The Cat in the Iron…",
    "Heathcliff E67 - Nightmare in Beverly Hills + The Cat in the Iron Mask.ia.mp4"],
  ["heathcliff-and-the-catillac-cats-1984-complete-series", "HEATHCLIFF AND THE CATILLAC CATS TV SERIES - S01E68 - Heathcliff E68 The Shrink + Brushing Up",
    "Heathcliff E68 - The Shrink + Brushing Up.ia.mp4"],
  ["heathcliff-and-the-catillac-cats-1984-complete-series", "HEATHCLIFF AND THE CATILLAC CATS TV SERIES - S01E69 - Heathcliff E69 Dr. Heathcliff and Mr. Spike + Time Warped",
    "Heathcliff E69 - Dr. Heathcliff and Mr. Spike + Time Warped.ia.mp4"],
  ["heathcliff-and-the-catillac-cats-1984-complete-series", "HEATHCLIFF AND THE CATILLAC CATS TV SERIES - S01E70 - Heathcliff E70 Spike's New Home + Mungo's Big Romance",
    "Heathcliff E70 - Spike's New Home + Mungo's Big Romance.ia.mp4"],
  ["heathcliff-and-the-catillac-cats-1984-complete-series", "HEATHCLIFF AND THE CATILLAC CATS TV SERIES - S01E71 - Heathcliff E71 The Cat and the Pauper + Mungo of the Jungle",
    "Heathcliff E71 - The Cat and the Pauper + Mungo of the Jungle.ia.mp4"],
  ["heathcliff-and-the-catillac-cats-1984-complete-series", "HEATHCLIFF AND THE CATILLAC CATS TV SERIES - S01E72 - Heathcliff E72 In the Beginning + Catlympic Cats",
    "Heathcliff E72 - In the Beginning + Catlympic Cats.ia.mp4"],
  ["heathcliff-and-the-catillac-cats-1984-complete-series", "HEATHCLIFF AND THE CATILLAC CATS TV SERIES - S01E73 - Heathcliff E73 Rear Cat Window + Cat Days, Ninja Nights",
    "Heathcliff E73 - Rear Cat Window + Cat Days, Ninja Nights.ia.mp4"],
  ["heathcliff-and-the-catillac-cats-1984-complete-series", "HEATHCLIFF AND THE CATILLAC CATS TV SERIES - S01E74 - Heathcliff E74 Something Fishy + Christmas Memories",
    "Heathcliff E74 - Something Fishy + Christmas Memories.ia.mp4"],
  ["heathcliff-and-the-catillac-cats-1984-complete-series", "HEATHCLIFF AND THE CATILLAC CATS TV SERIES - S01E75 - Heathcliff E75 Heathcliff's Mom + Hockey Pucks",
    "Heathcliff E75 - Heathcliff's Mom + Hockey Pucks.ia.mp4"],
  ["heathcliff-and-the-catillac-cats-1984-complete-series", "HEATHCLIFF AND THE CATILLAC CATS TV SERIES - S01E76 - Heathcliff E76 Cat Day Afternoon + Hector Protector",
    "Heathcliff E76 - Cat Day Afternoon + Hector Protector.ia.mp4"],
  ["heathcliff-and-the-catillac-cats-1984-complete-series", "HEATHCLIFF AND THE CATILLAC CATS TV SERIES - S01E77 - Heathcliff E77 Feline Good + Off Road Racer",
    "Heathcliff E77 - Feline Good + Off-Road Racer.ia.mp4"],
  ["heathcliff-and-the-catillac-cats-1984-complete-series", "HEATHCLIFF AND THE CATILLAC CATS TV SERIES - S01E78 - Heathcliff E78 Spike's Coach + The Trojan Catillac",
    "Heathcliff E78 - Spike's Coach + The Trojan Catillac.ia.mp4"],
  ["heathcliff-and-the-catillac-cats-1984-complete-series", "HEATHCLIFF AND THE CATILLAC CATS TV SERIES - S01E79 - Heathcliff E79 Heathcliff Gets Framed + Repo Cat",
    "Heathcliff E79 - Heathcliff Gets Framed + Repo Cat.ia.mp4"],
  ["heathcliff-and-the-catillac-cats-1984-complete-series", "HEATHCLIFF AND THE CATILLAC CATS TV SERIES - S01E80 - Heathcliff E80 Missing in Action + Bag Cat Sings the Blues",
    "Heathcliff E80 - Missing in Action + Bag Cat Sings the Blues.ia.mp4"],
  ["heathcliff-and-the-catillac-cats-1984-complete-series", "HEATHCLIFF AND THE CATILLAC CATS TV SERIES - S01E81 - Heathcliff E81 It's a Terrible Life + Leroy Gets Canned",
    "Heathcliff E81 - It's a Terrible Life + Leroy Gets Canned.ia.mp4"],
  ["heathcliff-and-the-catillac-cats-1984-complete-series", "HEATHCLIFF AND THE CATILLAC CATS TV SERIES - S01E82 - Heathcliff E82 Hair of the Cat + Tenting Tonight",
    "Heathcliff E82 - Hair of the Cat + Tenting Tonight.ia.mp4"],
  ["heathcliff-and-the-catillac-cats-1984-complete-series", "HEATHCLIFF AND THE CATILLAC CATS TV SERIES - S01E83 - Heathcliff E83 The Fortune Teller + Cottontails, Chickens, & Colored Eggs",
    "Heathcliff E83 - The Fortune Teller + Cottontails, Chickens, & Colored Eggs.ia.mp4"],
  ["heathcliff-and-the-catillac-cats-1984-complete-series", "HEATHCLIFF AND THE CATILLAC CATS TV SERIES - S01E84 - Heathcliff E84 Break an Egg + A Letter to Granny",
    "Heathcliff E84 - Break an Egg + A Letter to Granny.ia.mp4"],
  ["heathcliff-and-the-catillac-cats-1984-complete-series", "HEATHCLIFF AND THE CATILLAC CATS TV SERIES - S01E85 - Heathcliff E85 The New York City Sewer System + High Goon",
    "Heathcliff E85 - The New York City Sewer System + High Goon.ia.mp4"],
  ["heathcliff-and-the-catillac-cats-1984-complete-series", "HEATHCLIFF AND THE CATILLAC CATS TV SERIES - S01E86 - Heathcliff E86 North Pole Cat + He Ain't Heavy, He's My Brother",
    "Heathcliff E86 - North Pole Cat + He Ain't Heavy, He's My Brother.ia.mp4"],
],
  durations: {
  "heathcliff-and-the-catillac-cats-1984-complete-series::Heathcliff E01 - The Great Pussini.mp4": 664,
  "heathcliff-and-the-catillac-cats-1984-complete-series::Heathcliff E02 - Kitty Kat Kennels.mp4": 671,
  "heathcliff-and-the-catillac-cats-1984-complete-series::Heathcliff E03 - Chauncey's Great Escape.mp4": 665,
  "heathcliff-and-the-catillac-cats-1984-complete-series::Heathcliff E04 - Carnival Capers.mp4": 665,
  "heathcliff-and-the-catillac-cats-1984-complete-series::Heathcliff E05 - Mad Dog Catcher.mp4": 664,
  "heathcliff-and-the-catillac-cats-1984-complete-series::Heathcliff E06 - Circus Beserkus.mp4": 671,
  "heathcliff-and-the-catillac-cats-1984-complete-series::Heathcliff E07 - Rebel Without a Claws.mp4": 665,
  "heathcliff-and-the-catillac-cats-1984-complete-series::Heathcliff E08 - The Farming Life Ain't For Me.mp4": 671,
  "heathcliff-and-the-catillac-cats-1984-complete-series::Heathcliff E09 - Heathcliff's Middle Name.mp4": 664,
  "heathcliff-and-the-catillac-cats-1984-complete-series::Heathcliff E10 - Wishful Thinking.mp4": 670,
  "heathcliff-and-the-catillac-cats-1984-complete-series::Heathcliff E11 - Teed Off.mp4": 664,
  "heathcliff-and-the-catillac-cats-1984-complete-series::Heathcliff E12 - Monstro vs. the Wolf Hound.mp4": 640,
  "heathcliff-and-the-catillac-cats-1984-complete-series::Heathcliff E13 - Say Cheese.mp4": 665,
  "heathcliff-and-the-catillac-cats-1984-complete-series::Heathcliff E14 - Cat's Angels.mp4": 671,
  "heathcliff-and-the-catillac-cats-1984-complete-series::Heathcliff E15 - Meow Meow Island.mp4": 665,
  "heathcliff-and-the-catillac-cats-1984-complete-series::Heathcliff E16 - Iron Cats.mp4": 671,
  "heathcliff-and-the-catillac-cats-1984-complete-series::Heathcliff E17 - Family Tree.mp4": 664,
  "heathcliff-and-the-catillac-cats-1984-complete-series::Heathcliff E18 - Who's Got the Chocolate.mp4": 670,
  "heathcliff-and-the-catillac-cats-1984-complete-series::Heathcliff E19 - Be Prepared.mp4": 665,
  "heathcliff-and-the-catillac-cats-1984-complete-series::Heathcliff E20 - Cruisin' for a Bruisin'.mp4": 668,
  "heathcliff-and-the-catillac-cats-1984-complete-series::Heathcliff E21 - Heathcliff Gets Canned.mp4": 664,
  "heathcliff-and-the-catillac-cats-1984-complete-series::Heathcliff E22 - Wild Cat Heathcliff.mp4": 664,
  "heathcliff-and-the-catillac-cats-1984-complete-series::Heathcliff E23 - Kitten Around.mp4": 672,
  "heathcliff-and-the-catillac-cats-1984-complete-series::Heathcliff E24 - Cat Burglar Heathcliff.mp4": 665,
  "heathcliff-and-the-catillac-cats-1984-complete-series::Heathcliff E25 - Lucky's Unlucky Day.mp4": 673,
  "heathcliff-and-the-catillac-cats-1984-complete-series::Heathcliff E26 - The Blizzard Bandit.mp4": 665,
  "heathcliff-and-the-catillac-cats-1984-complete-series::Heathcliff E27 - Harem Cat.mp4": 673,
  "heathcliff-and-the-catillac-cats-1984-complete-series::Heathcliff E28 - Kitten Smitten.mp4": 664,
  "heathcliff-and-the-catillac-cats-1984-complete-series::Heathcliff E29 - Young Cat with a Horn.mp4": 545,
  "heathcliff-and-the-catillac-cats-1984-complete-series::Heathcliff E30 - The Gang's All Here.mp4": 665,
  "heathcliff-and-the-catillac-cats-1984-complete-series::Heathcliff E31 - The Meowsic Goes Round and Round.mp4": 672,
  "heathcliff-and-the-catillac-cats-1984-complete-series::Heathcliff E32 - Snow Job.mp4": 664,
  "heathcliff-and-the-catillac-cats-1984-complete-series::Heathcliff E33 - Spike's Slave.mp4": 668,
  "heathcliff-and-the-catillac-cats-1984-complete-series::Heathcliff E34 - Scaredy Cats.mp4": 671,
  "heathcliff-and-the-catillac-cats-1984-complete-series::Heathcliff E35 - Gopher Broke.mp4": 656,
  "heathcliff-and-the-catillac-cats-1984-complete-series::Heathcliff E36 - A Camping We Will Go.mp4": 672,
  "heathcliff-and-the-catillac-cats-1984-complete-series::Heathcliff E37 - Where There's an Ill, There's a Way.mp4": 656,
  "heathcliff-and-the-catillac-cats-1984-complete-series::Heathcliff E38 - Yes Sewer That's my Baby.mp4": 674,
  "heathcliff-and-the-catillac-cats-1984-complete-series::Heathcliff E39 - Soap Box Derby.mp4": 656,
  "heathcliff-and-the-catillac-cats-1984-complete-series::Heathcliff E40 - A Better Mousetrap.mp4": 710,
  "heathcliff-and-the-catillac-cats-1984-complete-series::Heathcliff E41 - Bamboo Island.mp4": 656,
  "heathcliff-and-the-catillac-cats-1984-complete-series::Heathcliff E42 - Superhero Mungo.mp4": 669,
  "heathcliff-and-the-catillac-cats-1984-complete-series::Heathcliff E43 - Butter Up.mp4": 656,
  "heathcliff-and-the-catillac-cats-1984-complete-series::Heathcliff E44 - The Siamese Twins.mp4": 657,
  "heathcliff-and-the-catillac-cats-1984-complete-series::Heathcliff E45 - The Mungo Mash.mp4": 669,
  "heathcliff-and-the-catillac-cats-1984-complete-series::Heathcliff E46 - Copa-ca-Heathcliff.mp4": 656,
  "heathcliff-and-the-catillac-cats-1984-complete-series::Heathcliff E47 - Leroy's in Love.mp4": 673,
  "heathcliff-and-the-catillac-cats-1984-complete-series::Heathcliff E48 - Used Pets.mp4": 655,
  "heathcliff-and-the-catillac-cats-1984-complete-series::Heathcliff E49 - Search for a Star.mp4": 671,
  "heathcliff-and-the-catillac-cats-1984-complete-series::Heathcliff E50 - An Officer and an Alley-Cat.mp4": 656,
  "heathcliff-and-the-catillac-cats-1984-complete-series::Heathcliff E51 - Hector Spector.mp4": 672,
  "heathcliff-and-the-catillac-cats-1984-complete-series::Heathcliff E52 - Service with a Smile.mp4": 656,
  "heathcliff-and-the-catillac-cats-1984-complete-series::Heathcliff E53 - Junk Food.mp4": 671,
  "heathcliff-and-the-catillac-cats-1984-complete-series::Heathcliff E54 - Boom Boom Pussini.mp4": 656,
  "heathcliff-and-the-catillac-cats-1984-complete-series::Heathcliff E55 - Heathcliff Surprise.mp4": 656,
  "heathcliff-and-the-catillac-cats-1984-complete-series::Heathcliff E56 - The Big Break-In.mp4": 672,
  "heathcliff-and-the-catillac-cats-1984-complete-series::Heathcliff E57 - The Catfather.mp4": 656,
  "heathcliff-and-the-catillac-cats-1984-complete-series::Heathcliff E58 - The Big Swipe.mp4": 670,
  "heathcliff-and-the-catillac-cats-1984-complete-series::Heathcliff E59 - Tally-Ho Heathcliff.mp4": 656,
  "heathcliff-and-the-catillac-cats-1984-complete-series::Heathcliff E60 - The Baby Buggy Bad Guys.mp4": 656,
  "heathcliff-and-the-catillac-cats-1984-complete-series::Heathcliff E61 - Grandpa vs. Grandpa.mp4": 657,
  "heathcliff-and-the-catillac-cats-1984-complete-series::Heathcliff E62 - The Big Game Hunter.mp4": 670,
  "heathcliff-and-the-catillac-cats-1984-complete-series::Heathcliff E63 - The Great Tuna Caper.mp4": 657,
  "heathcliff-and-the-catillac-cats-1984-complete-series::Heathcliff E64 - Peco's Treasure.mp4": 671,
  "heathcliff-and-the-catillac-cats-1984-complete-series::Heathcliff E65 - Cleo Moves In.mp4": 671,
  "heathcliff-and-the-catillac-cats-1984-complete-series::Heathcliff E66 - The White Cliffs of Dover.ia.mp4": 1331,
  "heathcliff-and-the-catillac-cats-1984-complete-series::Heathcliff E67 - Nightmare in Beverly Hills + The Cat in the Iron Mask.ia.mp4": 1331,
  "heathcliff-and-the-catillac-cats-1984-complete-series::Heathcliff E68 - The Shrink + Brushing Up.ia.mp4": 1331,
  "heathcliff-and-the-catillac-cats-1984-complete-series::Heathcliff E69 - Dr. Heathcliff and Mr. Spike + Time Warped.ia.mp4": 1331,
  "heathcliff-and-the-catillac-cats-1984-complete-series::Heathcliff E70 - Spike's New Home + Mungo's Big Romance.ia.mp4": 1331,
  "heathcliff-and-the-catillac-cats-1984-complete-series::Heathcliff E71 - The Cat and the Pauper + Mungo of the Jungle.ia.mp4": 1331,
  "heathcliff-and-the-catillac-cats-1984-complete-series::Heathcliff E72 - In the Beginning + Catlympic Cats.ia.mp4": 1331,
  "heathcliff-and-the-catillac-cats-1984-complete-series::Heathcliff E73 - Rear Cat Window + Cat Days, Ninja Nights.ia.mp4": 1331,
  "heathcliff-and-the-catillac-cats-1984-complete-series::Heathcliff E74 - Something Fishy + Christmas Memories.ia.mp4": 1331,
  "heathcliff-and-the-catillac-cats-1984-complete-series::Heathcliff E75 - Heathcliff's Mom + Hockey Pucks.ia.mp4": 1331,
  "heathcliff-and-the-catillac-cats-1984-complete-series::Heathcliff E76 - Cat Day Afternoon + Hector Protector.ia.mp4": 1331,
  "heathcliff-and-the-catillac-cats-1984-complete-series::Heathcliff E77 - Feline Good + Off-Road Racer.ia.mp4": 1331,
  "heathcliff-and-the-catillac-cats-1984-complete-series::Heathcliff E78 - Spike's Coach + The Trojan Catillac.ia.mp4": 1331,
  "heathcliff-and-the-catillac-cats-1984-complete-series::Heathcliff E79 - Heathcliff Gets Framed + Repo Cat.ia.mp4": 1331,
  "heathcliff-and-the-catillac-cats-1984-complete-series::Heathcliff E80 - Missing in Action + Bag Cat Sings the Blues.ia.mp4": 1331,
  "heathcliff-and-the-catillac-cats-1984-complete-series::Heathcliff E81 - It's a Terrible Life + Leroy Gets Canned.ia.mp4": 1331,
  "heathcliff-and-the-catillac-cats-1984-complete-series::Heathcliff E82 - Hair of the Cat + Tenting Tonight.ia.mp4": 1331,
  "heathcliff-and-the-catillac-cats-1984-complete-series::Heathcliff E83 - The Fortune Teller + Cottontails, Chickens, & Colored Eggs.ia.mp4": 1331,
  "heathcliff-and-the-catillac-cats-1984-complete-series::Heathcliff E84 - Break an Egg + A Letter to Granny.ia.mp4": 1331,
  "heathcliff-and-the-catillac-cats-1984-complete-series::Heathcliff E85 - The New York City Sewer System + High Goon.ia.mp4": 1331,
  "heathcliff-and-the-catillac-cats-1984-complete-series::Heathcliff E86 - North Pole Cat + He Ain't Heavy, He's My Brother.ia.mp4": 1331,
},
};
