window.SHOW = {
  id: "SwitchedatBirth",
  title: "Switched at Birth",
  art: "SwitchedatBirth.jpg",
  storageProgressKey: "switchedatbirth-progress",
  storageSettingsKey: "switchedatbirth-settings",
  nestedPaths: true,
  grouping: "season",
  segments: "none",
  episodes: [
  ["switched-at-birth-complete-series", "SWITCHED AT BIRTH - S01E01 - This is Not a Pipe",
    "Switched at Birth S01E01 - This is Not A Pipe.ia.mp4"],
  ["switched-at-birth-complete-series", "SWITCHED AT BIRTH - S01E02 - American Gothic",
    "Switched at Birth S01E02 - American Gothic.ia.mp4"],
  ["switched-at-birth-complete-series", "SWITCHED AT BIRTH - S01E03 - Portrait of My Father",
    "Switched at Birth S01E03 - Portrait of My Father.ia.mp4"],
  ["switched-at-birth-complete-series", "SWITCHED AT BIRTH - S01E04 - Dance Amongst Daggers",
    "Switched at Birth S01E04 - Dance Amongst Daggers.ia.mp4"],
  ["switched-at-birth-complete-series", "SWITCHED AT BIRTH - S01E05 - Dogs Playing Poker",
    "Switched at Birth S01E05 - Dogs Playing Poker.ia.mp4"],
  ["switched-at-birth-complete-series", "SWITCHED AT BIRTH - S01E06 - The Persistence of Memory",
    "Switched at Birth S01E06 - The Persistence of Memory.ia.mp4"],
  ["switched-at-birth-complete-series", "SWITCHED AT BIRTH - S01E07 - The Stag Hunt",
    "Switched at Birth S01E07 - The Stag Hunt.ia.mp4"],
  ["switched-at-birth-complete-series", "SWITCHED AT BIRTH - S01E08 - Pandora's Box",
    "Switched at Birth S01E08 - Pandora's Box.ia.mp4"],
  ["switched-at-birth-complete-series", "SWITCHED AT BIRTH - S01E09 - Paradise Lost",
    "Switched at Birth S01E09 - Paradise Lost.ia.mp4"],
  ["switched-at-birth-complete-series", "SWITCHED AT BIRTH - S01E10 - The Homecoming",
    "Switched at Birth S01E10 - The Homecoming.ia.mp4"],
  ["switched-at-birth-complete-series", "SWITCHED AT BIRTH - S01E11 - Starry Night",
    "Switched at Birth S01E11 - Starry Night.ia.mp4"],
  ["switched-at-birth-complete-series", "SWITCHED AT BIRTH - S01E12 - The Tempest",
    "Switched at Birth S01E12 - The Tempest.ia.mp4"],
  ["switched-at-birth-complete-series", "SWITCHED AT BIRTH - S01E13 - Self-Portrait with a Bandaged Ear",
    "Switched at Birth S01E13 - Self-Portrait With Bandaged Ear.ia.mp4"],
  ["switched-at-birth-complete-series", "SWITCHED AT BIRTH - S01E14 - Les soeurs d'Estrees",
    "Switched at Birth S01E14 - Les Soeurs d'Estrees.ia.mp4"],
  ["switched-at-birth-complete-series", "SWITCHED AT BIRTH - S01E15 - Expulsion from the Garden of Eden",
    "Switched at Birth S01E15 - Expulsion From the Garden of Eden.ia.mp4"],
  ["switched-at-birth-complete-series", "SWITCHED AT BIRTH - S01E16 - Las Dos Fridas",
    "Switched at Birth S01E16 - Las Dos Fridas.ia.mp4"],
  ["switched-at-birth-complete-series", "SWITCHED AT BIRTH - S01E17 - Protect Me from What I Want",
    "Switched at Birth S01E17 - Protect Me  from What I Want.ia.mp4"],
  ["switched-at-birth-complete-series", "SWITCHED AT BIRTH - S01E18 - The Art of Painting",
    "Switched at Birth S01E18 - The Art of Painting.ia.mp4"],
  ["switched-at-birth-complete-series", "SWITCHED AT BIRTH - S01E19 - Write a Lonely Soldier",
    "Switched at Birth S01E19 - Write A Lonely Soldier.ia.mp4"],
  ["switched-at-birth-complete-series", "SWITCHED AT BIRTH - S01E20 - Game On",
    "Switched at Birth S01E20 - Game On.ia.mp4"],
  ["switched-at-birth-complete-series", "SWITCHED AT BIRTH - S01E21 - The Sleep of Reason Produces Monsters",
    "Switched at Birth S01E21 - The Sleep of Reason Produces Monsters.ia.mp4"],
  ["switched-at-birth-complete-series", "SWITCHED AT BIRTH - S01E22 - Venus, Cupid, Folly and Time",
    "Switched at Birth S01E22 - Venus, Cupid, Folly, and Time.ia.mp4"],
  ["switched-at-birth-complete-series", "SWITCHED AT BIRTH - S01E23 - This is the Color of My Dreams",
    "Switched at Birth S01E23 - This Is The Color of My.ia.mp4"],
  ["switched-at-birth-complete-series", "SWITCHED AT BIRTH - S01E24 - The Intruder",
    "Switched at Birth S01E24 - The Intruder.ia.mp4"],
  ["switched-at-birth-complete-series", "SWITCHED AT BIRTH - S01E25 - The Shock of Being Seen",
    "Switched at Birth S01E25 - The Shock of Being Seen.ia.mp4"],
  ["switched-at-birth-complete-series", "SWITCHED AT BIRTH - S01E26 - The Tree of Forgiveness",
    "Switched at Birth S01E26 - The Tree of Forgiveness.ia.mp4"],
  ["switched-at-birth-complete-series", "SWITCHED AT BIRTH - S01E27 - The Declaration of Independence",
    "Switched at Birth S01E27 - The Declaration of Independence.ia.mp4"],
  ["switched-at-birth-complete-series", "SWITCHED AT BIRTH - S01E28 - We Are the Kraken of Our Own Sinking Ships",
    "Switched at Birth S01E28 We're The Kraken of Our Own Sinking Ships.ia.mp4"],
  ["switched-at-birth-complete-series", "SWITCHED AT BIRTH - S01E29 - The Trial",
    "Switched at Birth S01E29 - The Trial.ia.mp4"],
  ["switched-at-birth-complete-series", "SWITCHED AT BIRTH - S01E30 - Street Noises Invade the House",
    "Switched at Birth S01E30 - Street Noises Invade The House.ia.mp4"],
  ["switched-at-birth-complete-series", "SWITCHED AT BIRTH - S02E01 - The Door to Freedom",
    "Switched at Birth S02E01 - The Door to Freedom.ia.mp4"],
  ["switched-at-birth-complete-series", "SWITCHED AT BIRTH - S02E02 - The Awakening Conscience",
    "Switched at Birth S02E02 - The Awakening Conscience.ia.mp4"],
  ["switched-at-birth-complete-series", "SWITCHED AT BIRTH - S02E03 - Duel Between Two Women",
    "Switched at Birth S02E03 - Duel of Two Women.ia.mp4"],
  ["switched-at-birth-complete-series", "SWITCHED AT BIRTH - S02E04 - Dressing for the Charade",
    "Switched at Birth S02E04 - Dressing for The Charade.ia.mp4"],
  ["switched-at-birth-complete-series", "SWITCHED AT BIRTH - S02E05 - The Acquired Inability to Escape",
    "Switched at Birth S02E05 - The Acquired Inability to Escape.ia.mp4"],
  ["switched-at-birth-complete-series", "SWITCHED AT BIRTH - S02E06 - Human/Need/Desire",
    "Switched at Birth S02E06 - Human Need Desire.ia.mp4"],
  ["switched-at-birth-complete-series", "SWITCHED AT BIRTH - S02E07 - Drive in the Knife",
    "Switched at Birth S02E07 - Drive in The Knife.ia.mp4"],
  ["switched-at-birth-complete-series", "SWITCHED AT BIRTH - S02E08 - Tightrope Walker",
    "Switched at Birth S02E08 - Tight Rope Walker.ia.mp4"],
  ["switched-at-birth-complete-series", "SWITCHED AT BIRTH - S02E09 - Uprising",
    "Switched at Birth S02E09 - Uprising.ia.mp4"],
  ["switched-at-birth-complete-series", "SWITCHED AT BIRTH - S02E10 - Introducing the Miracle",
    "Switched at Birth S02E10 - Introducing The Miracle.ia.mp4"],
  ["switched-at-birth-complete-series", "SWITCHED AT BIRTH - S02E11 - Mother and Child Divided",
    "Switched at Birth S02E11 - Mother & Daughter Divided.ia.mp4"],
  ["switched-at-birth-complete-series", "SWITCHED AT BIRTH - S02E12 - Distorted House",
    "Switched at Birth S02E12 - Distorted House.ia.mp4"],
  ["switched-at-birth-complete-series", "SWITCHED AT BIRTH - S02E13 - The Good Samaritan",
    "Switched at Birth S02E13 - The Good Samaritan.ia.mp4"],
  ["switched-at-birth-complete-series", "SWITCHED AT BIRTH - S02E14 - He Did What He Wanted",
    "Switched at Birth S02E14 - He Did What He Wanted.ia.mp4"],
  ["switched-at-birth-complete-series", "SWITCHED AT BIRTH - S02E15 - Ecce Mono",
    "Switched at Birth S02E15 - Ecce Mono.ia.mp4"],
  ["switched-at-birth-complete-series", "SWITCHED AT BIRTH - S02E16 - The Physical Impossibility of Death in the Mind of Someone Living",
    "Switched at Birth S02E16 - The Physical Impossibility of Death in the Mind of Someone Living.ia.mp4"],
  ["switched-at-birth-complete-series", "SWITCHED AT BIRTH - S02E17 - Prudence, Avarice, Lust, Justice, Anger",
    "Switched at Birth S02E17 - Prudence, Avarice, Lust, Justice, Anger.ia.mp4"],
  ["switched-at-birth-complete-series", "SWITCHED AT BIRTH - S02E18 - As the Shadows Deepen",
    "Switched at Birth S02E18 - As The Shadows Deepen.ia.mp4"],
  ["switched-at-birth-complete-series", "SWITCHED AT BIRTH - S02E19 - What Goes Up Must Come Down",
    "Switched at Birth S02E19 - What Goes Up Must Come Down.ia.mp4"],
  ["switched-at-birth-complete-series", "SWITCHED AT BIRTH - S02E20 - The Merrymakers",
    "Switched at Birth S02E20 - The Merrymakers.ia.mp4"],
  ["switched-at-birth-complete-series", "SWITCHED AT BIRTH - S02E21 - Departure of Summer",
    "Switched at Birth S02E21 - Departure of Summer.ia.mp4"],
  ["switched-at-birth-complete-series", "SWITCHED AT BIRTH - S03E01 - Drowning Girl",
    "Switched at Birth S03E01 - Drowning Girl.ia.mp4"],
  ["switched-at-birth-complete-series", "SWITCHED AT BIRTH - S03E02 - Your Body is a Battleground",
    "Switched at Birth S03E02 - Your Body is A Battleground.ia.mp4"],
  ["switched-at-birth-complete-series", "SWITCHED AT BIRTH - S03E03 - Fountain",
    "Switched at Birth S03E03 - Fountain.ia.mp4"],
  ["switched-at-birth-complete-series", "SWITCHED AT BIRTH - S03E04 - It Hurts to Wait with Love If Love is Somewhere Else",
    "Switched at Birth S03E04 - It Hurts to Wait With Love If Love is Somewhere Else.ia.mp4"],
  ["switched-at-birth-complete-series", "SWITCHED AT BIRTH - S03E05 - Have You Really the Courage?",
    "Switched at Birth S03E05 - Have You Really The Courage.ia.mp4"],
  ["switched-at-birth-complete-series", "SWITCHED AT BIRTH - S03E06 - The Scream",
    "Switched at Birth S03E06 - The Scream.ia.mp4"],
  ["switched-at-birth-complete-series", "SWITCHED AT BIRTH - S03E07 - Memory is Your Image of Perfection",
    "Switched at Birth S03E07 - Memory is Your Image of Perfection.ia.mp4"],
  ["switched-at-birth-complete-series", "SWITCHED AT BIRTH - S03E08 - Dance Me to the End of Love",
    "Switched at Birth S03E08 - Dance Me to The End of Love.ia.mp4"],
  ["switched-at-birth-complete-series", "SWITCHED AT BIRTH - S03E09 - The Past",
    "Switched at Birth S03E09 - The Past (Forgotten-Swallowed).ia.mp4"],
  ["switched-at-birth-complete-series", "SWITCHED AT BIRTH - S03E10 - The Ambush",
    "Switched at Birth S03E10 - The Ambush.ia.mp4"],
  ["switched-at-birth-complete-series", "SWITCHED AT BIRTH - S03E11 - Love Seduces Innocence, Pleasure Entraps, and Remorse Follows",
    "Switched at Birth S03E11 - Love Seduces Innocence, Pleasure Entraps, and Remorse Follows.ia.mp4"],
  ["switched-at-birth-complete-series", "SWITCHED AT BIRTH - S03E12 - Love Among the Ruins",
    "Switched at Birth S03E12 - Love Among The Ruins.ia.mp4"],
  ["switched-at-birth-complete-series", "SWITCHED AT BIRTH - S03E13 - Like a Snowball Down a Mountain",
    "Switched at Birth S03E13 - Like A Snowball Down A Mountain.ia.mp4"],
  ["switched-at-birth-complete-series", "SWITCHED AT BIRTH - S03E14 - Oh, Future!",
    "Switched at Birth S03E14 - Oh, Future.ia.mp4"],
  ["switched-at-birth-complete-series", "SWITCHED AT BIRTH - S03E15 - And We Bring the Light",
    "Switched at Birth S03E15 - And We Bring The Light.ia.mp4"],
  ["switched-at-birth-complete-series", "SWITCHED AT BIRTH - S03E16 - The Image Disappears",
    "Switched at Birth S03E16 - The Image Disappears.ia.mp4"],
  ["switched-at-birth-complete-series", "SWITCHED AT BIRTH - S03E17 - Girl with Death Mask",
    "Switched at Birth S03E17 - Girl Death Mask (She Plays Alone).ia.mp4"],
  ["switched-at-birth-complete-series", "SWITCHED AT BIRTH - S03E18 - It Isn't What You Think",
    "Switched at Birth S03E18 - It Isn't What You Think.ia.mp4"],
  ["switched-at-birth-complete-series", "SWITCHED AT BIRTH - S03E19 - You Will Not Escape",
    "Switched at Birth S03E19 - You Will Not Escape.ia.mp4"],
  ["switched-at-birth-complete-series", "SWITCHED AT BIRTH - S03E20 - The Girl on the Cliff",
    "Switched at Birth S03E20 - Girl on the Cliff.ia.mp4"],
  ["switched-at-birth-complete-series", "SWITCHED AT BIRTH - S03E21 - And Life Begins Right Away",
    "Switched at Birth S03E21 - And Life Begins Right Away.ia.mp4"],
  ["switched-at-birth-complete-series", "SWITCHED AT BIRTH - S03E22 - Yuletide Fortune Tellers",
    "Switched at Birth S03E22 - Yuletide Fortune Tellers.ia.mp4"],
  ["switched-at-birth-complete-series", "SWITCHED AT BIRTH - S04E01 - And It Cannot Be Changed",
    "Switched at Birth S04E01 - And It Cannot Be Changed.ia.mp4"],
  ["switched-at-birth-complete-series", "SWITCHED AT BIRTH - S04E02 - Bracing the Waves",
    "Switched at Birth S04E02 - Bracing the Waves.ia.mp4"],
  ["switched-at-birth-complete-series", "SWITCHED AT BIRTH - S04E03 - I Lock the Door Upon Myself",
    "Switched at Birth S04E03 - I Lock The Door Upon Myself.ia.mp4"],
  ["switched-at-birth-complete-series", "SWITCHED AT BIRTH - S04E04 - We Were So Close That Nothing Used to Stand Between Us",
    "Switched at Birth S04E04 - We Were So Close That Nothing Used to Stand Between Us.ia.mp4"],
  ["switched-at-birth-complete-series", "SWITCHED AT BIRTH - S04E05 - At First Clear Word",
    "Switched at Birth S04E05 - At The First Clear Word.ia.mp4"],
  ["switched-at-birth-complete-series", "SWITCHED AT BIRTH - S04E06 - Black and Gray",
    "Switched at Birth S04E06 - Black and Gray.ia.mp4"],
  ["switched-at-birth-complete-series", "SWITCHED AT BIRTH - S04E07 - Fog and Storm and Rain",
    "Switched at Birth S04E07 - Fog and Storm and Rain.ia.mp4"],
  ["switched-at-birth-complete-series", "SWITCHED AT BIRTH - S04E08 - Art Like Love is Dedication",
    "Switched at Birth S04E08 - Art Like Love is Dedication.ia.mp4"],
  ["switched-at-birth-complete-series", "SWITCHED AT BIRTH - S04E09 - The Player's Choice",
    "Switched at Birth S04E09 - The Player's Choice.ia.mp4"],
  ["switched-at-birth-complete-series", "SWITCHED AT BIRTH - S04E10 - There is My Heart",
    "Switched at Birth S04E10 - There is My Heart.ia.mp4"],
  ["switched-at-birth-complete-series", "SWITCHED AT BIRTH - S04E11 - To Repel Ghosts",
    "Switched at Birth S04E11 - To Repel Ghosts.ia.mp4"],
  ["switched-at-birth-complete-series", "SWITCHED AT BIRTH - S04E12 - How Does a Girl Like You Get to Be a Girl Like You",
    "Switched at Birth S04E12 - How Does A Girl Like You Get to Be  A Girl Like You.ia.mp4"],
  ["switched-at-birth-complete-series", "SWITCHED AT BIRTH - S04E13 - Between Hope and Fear",
    "Switched at Birth S04E13 - Between Hope and Fear.ia.mp4"],
  ["switched-at-birth-complete-series", "SWITCHED AT BIRTH - S04E14 - We Mourn, We Weep, We Love Again",
    "Switched at Birth S04E14 - We Mourn, We Weep, We Love Again.ia.mp4"],
  ["switched-at-birth-complete-series", "SWITCHED AT BIRTH - S04E15 - Instead of Damning the Darkness, It's Better to Light a Little Lantern",
    "Switched at Birth S04E15 - Instead of Damning The Darkness, it's Better to Light a Little Lantern.ia.mp4"],
  ["switched-at-birth-complete-series", "SWITCHED AT BIRTH - S04E16 - Borrowing Your Enemy's Arrows",
    "Switched at Birth S04E16 - Borrowing Your Enemy's Arrows.ia.mp4"],
  ["switched-at-birth-complete-series", "SWITCHED AT BIRTH - S04E17 - To the Victor Belong the Spoils",
    "Switched at Birth S04E17 - To The Victor Belong the Spoils.ia.mp4"],
  ["switched-at-birth-complete-series", "SWITCHED AT BIRTH - S04E18 - The Accommodations of Desire",
    "Switched at Birth S04E18 - The Accommodations of Desire.ia.mp4"],
  ["switched-at-birth-complete-series", "SWITCHED AT BIRTH - S04E19 - A Mad Tea Party",
    "Switched at Birth S04E19 - A Mad Tea Party.ia.mp4"],
  ["switched-at-birth-complete-series", "SWITCHED AT BIRTH - S04E20 - And Always Searching for Beauty",
    "Switched at Birth S04E20 - And Always Searching for Beauty.ia.mp4"],
  ["switched-at-birth-complete-series", "SWITCHED AT BIRTH - S05E01 - The Call",
    "Switched at Birth S05E01 - The Call.ia.mp4"],
  ["switched-at-birth-complete-series", "SWITCHED AT BIRTH - S05E02 - This Has to Do with Me",
    "Switched at Birth S05E02 - This Has to Do with Me.ia.mp4"],
  ["switched-at-birth-complete-series", "SWITCHED AT BIRTH - S05E03 - Surprise",
    "Switched at Birth S05E03 - Surprise.ia.mp4"],
  ["switched-at-birth-complete-series", "SWITCHED AT BIRTH - S05E04 - Relation of Lines and Colors",
    "Switched at Birth S05E04 - Relation of Lines and Colors.ia.mp4"],
  ["switched-at-birth-complete-series", "SWITCHED AT BIRTH - S05E05 - Occupy Truth",
    "Switched at Birth S05E05 - Occupy Truth.ia.mp4"],
  ["switched-at-birth-complete-series", "SWITCHED AT BIRTH - S05E06 - Four Ages in Life",
    "Switched at Birth S05E06 - Four Ages in Life.ia.mp4"],
  ["switched-at-birth-complete-series", "SWITCHED AT BIRTH - S05E07 - Memory (The Heart)",
    "Switched at Birth S05E07 - Memory (The Heart).ia.mp4"],
  ["switched-at-birth-complete-series", "SWITCHED AT BIRTH - S05E08 - Left in Charge",
    "Switched at Birth S05E08 - Left in Charge.ia.mp4"],
  ["switched-at-birth-complete-series", "SWITCHED AT BIRTH - S05E09 - The Wolf is Waiting",
    "Switched at Birth S05E09 - The Wolf is Waiting.ia.mp4"],
  ["switched-at-birth-complete-series", "SWITCHED AT BIRTH - S05E10 - Long Live Love",
    "Switched at Birth S05E10 - Long Live Love.ia.mp4"],
],
  durations: {
  "switched-at-birth-complete-series::Switched at Birth S01E01 - This is Not A Pipe.ia.mp4": 2698,
  "switched-at-birth-complete-series::Switched at Birth S01E02 - American Gothic.ia.mp4": 2643,
  "switched-at-birth-complete-series::Switched at Birth S01E03 - Portrait of My Father.ia.mp4": 2656,
  "switched-at-birth-complete-series::Switched at Birth S01E04 - Dance Amongst Daggers.ia.mp4": 2616,
  "switched-at-birth-complete-series::Switched at Birth S01E05 - Dogs Playing Poker.ia.mp4": 2656,
  "switched-at-birth-complete-series::Switched at Birth S01E06 - The Persistence of Memory.ia.mp4": 2594,
  "switched-at-birth-complete-series::Switched at Birth S01E07 - The Stag Hunt.ia.mp4": 2602,
  "switched-at-birth-complete-series::Switched at Birth S01E08 - Pandora's Box.ia.mp4": 2682,
  "switched-at-birth-complete-series::Switched at Birth S01E09 - Paradise Lost.ia.mp4": 2660,
  "switched-at-birth-complete-series::Switched at Birth S01E10 - The Homecoming.ia.mp4": 2569,
  "switched-at-birth-complete-series::Switched at Birth S01E11 - Starry Night.ia.mp4": 2594,
  "switched-at-birth-complete-series::Switched at Birth S01E12 - The Tempest.ia.mp4": 2583,
  "switched-at-birth-complete-series::Switched at Birth S01E13 - Self-Portrait With Bandaged Ear.ia.mp4": 2623,
  "switched-at-birth-complete-series::Switched at Birth S01E14 - Les Soeurs d'Estrees.ia.mp4": 2633,
  "switched-at-birth-complete-series::Switched at Birth S01E15 - Expulsion From the Garden of Eden.ia.mp4": 2593,
  "switched-at-birth-complete-series::Switched at Birth S01E16 - Las Dos Fridas.ia.mp4": 2589,
  "switched-at-birth-complete-series::Switched at Birth S01E17 - Protect Me  from What I Want.ia.mp4": 2622,
  "switched-at-birth-complete-series::Switched at Birth S01E18 - The Art of Painting.ia.mp4": 2572,
  "switched-at-birth-complete-series::Switched at Birth S01E19 - Write A Lonely Soldier.ia.mp4": 2579,
  "switched-at-birth-complete-series::Switched at Birth S01E20 - Game On.ia.mp4": 2633,
  "switched-at-birth-complete-series::Switched at Birth S01E21 - The Sleep of Reason Produces Monsters.ia.mp4": 2633,
  "switched-at-birth-complete-series::Switched at Birth S01E22 - Venus, Cupid, Folly, and Time.ia.mp4": 2699,
  "switched-at-birth-complete-series::Switched at Birth S01E23 - This Is The Color of My.ia.mp4": 2633,
  "switched-at-birth-complete-series::Switched at Birth S01E24 - The Intruder.ia.mp4": 2620,
  "switched-at-birth-complete-series::Switched at Birth S01E25 - The Shock of Being Seen.ia.mp4": 2624,
  "switched-at-birth-complete-series::Switched at Birth S01E26 - The Tree of Forgiveness.ia.mp4": 2631,
  "switched-at-birth-complete-series::Switched at Birth S01E27 - The Declaration of Independence.ia.mp4": 2587,
  "switched-at-birth-complete-series::Switched at Birth S01E28 We're The Kraken of Our Own Sinking Ships.ia.mp4": 2599,
  "switched-at-birth-complete-series::Switched at Birth S01E29 - The Trial.ia.mp4": 2610,
  "switched-at-birth-complete-series::Switched at Birth S01E30 - Street Noises Invade The House.ia.mp4": 2623,
  "switched-at-birth-complete-series::Switched at Birth S02E01 - The Door to Freedom.ia.mp4": 2631,
  "switched-at-birth-complete-series::Switched at Birth S02E02 - The Awakening Conscience.ia.mp4": 2631,
  "switched-at-birth-complete-series::Switched at Birth S02E03 - Duel of Two Women.ia.mp4": 2631,
  "switched-at-birth-complete-series::Switched at Birth S02E04 - Dressing for The Charade.ia.mp4": 2587,
  "switched-at-birth-complete-series::Switched at Birth S02E05 - The Acquired Inability to Escape.ia.mp4": 2616,
  "switched-at-birth-complete-series::Switched at Birth S02E06 - Human Need Desire.ia.mp4": 2629,
  "switched-at-birth-complete-series::Switched at Birth S02E07 - Drive in The Knife.ia.mp4": 2620,
  "switched-at-birth-complete-series::Switched at Birth S02E08 - Tight Rope Walker.ia.mp4": 2585,
  "switched-at-birth-complete-series::Switched at Birth S02E09 - Uprising.ia.mp4": 2611,
  "switched-at-birth-complete-series::Switched at Birth S02E10 - Introducing The Miracle.ia.mp4": 2629,
  "switched-at-birth-complete-series::Switched at Birth S02E11 - Mother & Daughter Divided.ia.mp4": 2627,
  "switched-at-birth-complete-series::Switched at Birth S02E12 - Distorted House.ia.mp4": 2589,
  "switched-at-birth-complete-series::Switched at Birth S02E13 - The Good Samaritan.ia.mp4": 2589,
  "switched-at-birth-complete-series::Switched at Birth S02E14 - He Did What He Wanted.ia.mp4": 2615,
  "switched-at-birth-complete-series::Switched at Birth S02E15 - Ecce Mono.ia.mp4": 2633,
  "switched-at-birth-complete-series::Switched at Birth S02E16 - The Physical Impossibility of Death in the Mind of Someone Living.ia.mp4": 2631,
  "switched-at-birth-complete-series::Switched at Birth S02E17 - Prudence, Avarice, Lust, Justice, Anger.ia.mp4": 2631,
  "switched-at-birth-complete-series::Switched at Birth S02E18 - As The Shadows Deepen.ia.mp4": 2625,
  "switched-at-birth-complete-series::Switched at Birth S02E19 - What Goes Up Must Come Down.ia.mp4": 2624,
  "switched-at-birth-complete-series::Switched at Birth S02E20 - The Merrymakers.ia.mp4": 2632,
  "switched-at-birth-complete-series::Switched at Birth S02E21 - Departure of Summer.ia.mp4": 2615,
  "switched-at-birth-complete-series::Switched at Birth S03E01 - Drowning Girl.ia.mp4": 2574,
  "switched-at-birth-complete-series::Switched at Birth S03E02 - Your Body is A Battleground.ia.mp4": 2538,
  "switched-at-birth-complete-series::Switched at Birth S03E03 - Fountain.ia.mp4": 2515,
  "switched-at-birth-complete-series::Switched at Birth S03E04 - It Hurts to Wait With Love If Love is Somewhere Else.ia.mp4": 2567,
  "switched-at-birth-complete-series::Switched at Birth S03E05 - Have You Really The Courage.ia.mp4": 2546,
  "switched-at-birth-complete-series::Switched at Birth S03E06 - The Scream.ia.mp4": 2536,
  "switched-at-birth-complete-series::Switched at Birth S03E07 - Memory is Your Image of Perfection.ia.mp4": 2565,
  "switched-at-birth-complete-series::Switched at Birth S03E08 - Dance Me to The End of Love.ia.mp4": 2560,
  "switched-at-birth-complete-series::Switched at Birth S03E09 - The Past (Forgotten-Swallowed).ia.mp4": 2513,
  "switched-at-birth-complete-series::Switched at Birth S03E10 - The Ambush.ia.mp4": 2571,
  "switched-at-birth-complete-series::Switched at Birth S03E11 - Love Seduces Innocence, Pleasure Entraps, and Remorse Follows.ia.mp4": 2573,
  "switched-at-birth-complete-series::Switched at Birth S03E12 - Love Among The Ruins.ia.mp4": 2569,
  "switched-at-birth-complete-series::Switched at Birth S03E13 - Like A Snowball Down A Mountain.ia.mp4": 2574,
  "switched-at-birth-complete-series::Switched at Birth S03E14 - Oh, Future.ia.mp4": 2574,
  "switched-at-birth-complete-series::Switched at Birth S03E15 - And We Bring The Light.ia.mp4": 2574,
  "switched-at-birth-complete-series::Switched at Birth S03E16 - The Image Disappears.ia.mp4": 2572,
  "switched-at-birth-complete-series::Switched at Birth S03E17 - Girl Death Mask (She Plays Alone).ia.mp4": 2570,
  "switched-at-birth-complete-series::Switched at Birth S03E18 - It Isn't What You Think.ia.mp4": 2575,
  "switched-at-birth-complete-series::Switched at Birth S03E19 - You Will Not Escape.ia.mp4": 2565,
  "switched-at-birth-complete-series::Switched at Birth S03E20 - Girl on the Cliff.ia.mp4": 2538,
  "switched-at-birth-complete-series::Switched at Birth S03E21 - And Life Begins Right Away.ia.mp4": 2570,
  "switched-at-birth-complete-series::Switched at Birth S03E22 - Yuletide Fortune Tellers.ia.mp4": 2576,
  "switched-at-birth-complete-series::Switched at Birth S04E01 - And It Cannot Be Changed.ia.mp4": 2566,
  "switched-at-birth-complete-series::Switched at Birth S04E02 - Bracing the Waves.ia.mp4": 2499,
  "switched-at-birth-complete-series::Switched at Birth S04E03 - I Lock The Door Upon Myself.ia.mp4": 2570,
  "switched-at-birth-complete-series::Switched at Birth S04E04 - We Were So Close That Nothing Used to Stand Between Us.ia.mp4": 2571,
  "switched-at-birth-complete-series::Switched at Birth S04E05 - At The First Clear Word.ia.mp4": 2553,
  "switched-at-birth-complete-series::Switched at Birth S04E06 - Black and Gray.ia.mp4": 2575,
  "switched-at-birth-complete-series::Switched at Birth S04E07 - Fog and Storm and Rain.ia.mp4": 2544,
  "switched-at-birth-complete-series::Switched at Birth S04E08 - Art Like Love is Dedication.ia.mp4": 2567,
  "switched-at-birth-complete-series::Switched at Birth S04E09 - The Player's Choice.ia.mp4": 2563,
  "switched-at-birth-complete-series::Switched at Birth S04E10 - There is My Heart.ia.mp4": 2542,
  "switched-at-birth-complete-series::Switched at Birth S04E11 - To Repel Ghosts.ia.mp4": 2537,
  "switched-at-birth-complete-series::Switched at Birth S04E12 - How Does A Girl Like You Get to Be  A Girl Like You.ia.mp4": 2521,
  "switched-at-birth-complete-series::Switched at Birth S04E13 - Between Hope and Fear.ia.mp4": 2567,
  "switched-at-birth-complete-series::Switched at Birth S04E14 - We Mourn, We Weep, We Love Again.ia.mp4": 2519,
  "switched-at-birth-complete-series::Switched at Birth S04E15 - Instead of Damning The Darkness, it's Better to Light a Little Lantern.ia.mp4": 2569,
  "switched-at-birth-complete-series::Switched at Birth S04E16 - Borrowing Your Enemy's Arrows.ia.mp4": 2569,
  "switched-at-birth-complete-series::Switched at Birth S04E17 - To The Victor Belong the Spoils.ia.mp4": 2560,
  "switched-at-birth-complete-series::Switched at Birth S04E18 - The Accommodations of Desire.ia.mp4": 2560,
  "switched-at-birth-complete-series::Switched at Birth S04E19 - A Mad Tea Party.ia.mp4": 2538,
  "switched-at-birth-complete-series::Switched at Birth S04E20 - And Always Searching for Beauty.ia.mp4": 2565,
  "switched-at-birth-complete-series::Switched at Birth S05E01 - The Call.ia.mp4": 2561,
  "switched-at-birth-complete-series::Switched at Birth S05E02 - This Has to Do with Me.ia.mp4": 2572,
  "switched-at-birth-complete-series::Switched at Birth S05E03 - Surprise.ia.mp4": 2539,
  "switched-at-birth-complete-series::Switched at Birth S05E04 - Relation of Lines and Colors.ia.mp4": 2572,
  "switched-at-birth-complete-series::Switched at Birth S05E05 - Occupy Truth.ia.mp4": 2575,
  "switched-at-birth-complete-series::Switched at Birth S05E06 - Four Ages in Life.ia.mp4": 2555,
  "switched-at-birth-complete-series::Switched at Birth S05E07 - Memory (The Heart).ia.mp4": 2571,
  "switched-at-birth-complete-series::Switched at Birth S05E08 - Left in Charge.ia.mp4": 2561,
  "switched-at-birth-complete-series::Switched at Birth S05E09 - The Wolf is Waiting.ia.mp4": 2559,
  "switched-at-birth-complete-series::Switched at Birth S05E10 - Long Live Love.ia.mp4": 3788,
},
};
