window.SHOW = {
  id: "ArchieBunkersPlace",
  title: "Archie Bunker's Place",
  art: "ArchieBunkersPlace.jpg",
  storageProgressKey: "archiebunkersplace-progress",
  storageSettingsKey: "archiebunkersplace-settings",
  nestedPaths: true,
  grouping: "season",
  segments: "none",
  episodes: [
  ["archie-bunkers-place-complete-series", "ARCHIE BUNKER'S PLACE - S01E01 - Archie's New Partner: Part 1",
    "Archie Bunker's Place - S01E01.ia.mp4"],
  ["archie-bunkers-place-complete-series", "ARCHIE BUNKER'S PLACE - S01E02 - Archie's New Partner: Part 2",
    "Archie Bunker's Place - S01E02.ia.mp4"],
  ["archie-bunkers-place-complete-series", "ARCHIE BUNKER'S PLACE - S01E03 - Edith Gets Hired",
    "Archie Bunker's Place - S01E03.ia.mp4"],
  ["archie-bunkers-place-complete-series", "ARCHIE BUNKER'S PLACE - S01E04 - Archie and the Oldest Profession",
    "Archie Bunker's Place - S01E04.ia.mp4"],
  ["archie-bunkers-place-complete-series", "ARCHIE BUNKER'S PLACE - S01E05 - Edith vs. the Energy Crisis",
    "Archie Bunker's Place - S01E05.ia.mp4"],
  ["archie-bunkers-place-complete-series", "ARCHIE BUNKER'S PLACE - S01E06 - Bosom Partners",
    "Archie Bunker's Place - S01E06.ia.mp4"],
  ["archie-bunkers-place-complete-series", "ARCHIE BUNKER'S PLACE - S01E07 - Building the Restaurant",
    "Archie Bunker's Place - S01E07.ia.mp4"],
  ["archie-bunkers-place-complete-series", "ARCHIE BUNKER'S PLACE - S01E08 - The Cook",
    "Archie Bunker's Place - S01E08.ia.mp4"],
  ["archie-bunkers-place-complete-series", "ARCHIE BUNKER'S PLACE - S01E09 - Murray and the Liquor Board",
    "Archie Bunker's Place - S01E09.ia.mp4"],
  ["archie-bunkers-place-complete-series", "ARCHIE BUNKER'S PLACE - S01E10 - Thanksgiving Reunion: Part 1",
    "Archie Bunker's Place - S01E10.ia.mp4"],
  ["archie-bunkers-place-complete-series", "ARCHIE BUNKER'S PLACE - S01E11 - Thanksgiving Reunion: Part 2",
    "Archie Bunker's Place - S01E11.ia.mp4"],
  ["archie-bunkers-place-complete-series", "ARCHIE BUNKER'S PLACE - S01E12 - Barney and the Hooker",
    "Archie Bunker's Place - S01E12.ia.mp4"],
  ["archie-bunkers-place-complete-series", "ARCHIE BUNKER'S PLACE - S01E13 - Man of the Year",
    "Archie Bunker's Place - S01E13.ia.mp4"],
  ["archie-bunkers-place-complete-series", "ARCHIE BUNKER'S PLACE - S01E14 - The Shabbat Dinner",
    "Archie Bunker's Place - S01E14.ia.mp4"],
  ["archie-bunkers-place-complete-series", "ARCHIE BUNKER'S PLACE - S01E15 - Barney's Lawsuit",
    "Archie Bunker's Place - S01E15.ia.mp4"],
  ["archie-bunkers-place-complete-series", "ARCHIE BUNKER'S PLACE - S01E16 - Blanche and Murray",
    "Archie Bunker's Place - S01E16.ia.mp4"],
  ["archie-bunkers-place-complete-series", "ARCHIE BUNKER'S PLACE - S01E17 - Murray's Daughter",
    "Archie Bunker's Place - S01E17.ia.mp4"],
  ["archie-bunkers-place-complete-series", "ARCHIE BUNKER'S PLACE - S01E18 - The Ambush",
    "Archie Bunker's Place - S01E18.ia.mp4"],
  ["archie-bunkers-place-complete-series", "ARCHIE BUNKER'S PLACE - S01E19 - The Return of Sammy",
    "Archie Bunker's Place - S01E19.ia.mp4"],
  ["archie-bunkers-place-complete-series", "ARCHIE BUNKER'S PLACE - S01E20 - Archie Fixes Up Fred",
    "Archie Bunker's Place - S01E20.ia.mp4"],
  ["archie-bunkers-place-complete-series", "ARCHIE BUNKER'S PLACE - S01E21 - Father and Daughter Night",
    "Archie Bunker's Place - S01E21.ia.mp4"],
  ["archie-bunkers-place-complete-series", "ARCHIE BUNKER'S PLACE - S01E22 - Van Ranseleer's Operation",
    "Archie Bunker's Place - S01E22.ia.mp4"],
  ["archie-bunkers-place-complete-series", "ARCHIE BUNKER'S PLACE - S01E23 - Veronica's Ex",
    "Archie Bunker's Place - S01E23.ia.mp4"],
  ["archie-bunkers-place-complete-series", "ARCHIE BUNKER'S PLACE - S01E24 - A Small Mafia Favor",
    "Archie Bunker's Place - S01E24.ia.mp4"],
  ["archie-bunkers-place-complete-series", "ARCHIE BUNKER'S PLACE - S02E01 - Archie Alone: Part 1",
    "Archie Bunker's Place - S02E01.ia.mp4"],
  ["archie-bunkers-place-complete-series", "ARCHIE BUNKER'S PLACE - S02E02 - Archie Alone: Part 2",
    "Archie Bunker's Place - S02E02.ia.mp4"],
  ["archie-bunkers-place-complete-series", "ARCHIE BUNKER'S PLACE - S02E03 - Home Again",
    "Archie Bunker's Place - S02E03.ia.mp4"],
  ["archie-bunkers-place-complete-series", "ARCHIE BUNKER'S PLACE - S02E04 - Hiring the Housekeeper",
    "Archie Bunker's Place - S02E04.ia.mp4"],
  ["archie-bunkers-place-complete-series", "ARCHIE BUNKER'S PLACE - S02E05 - The Wildcat Strike",
    "Archie Bunker's Place - S02E05.ia.mp4"],
  ["archie-bunkers-place-complete-series", "ARCHIE BUNKER'S PLACE - S02E06 - Veronica and the Health Inspector",
    "Archie Bunker's Place - S02E06.ia.mp4"],
  ["archie-bunkers-place-complete-series", "ARCHIE BUNKER'S PLACE - S02E07 - Murray's Wife",
    "Archie Bunker's Place - S02E07.ia.mp4"],
  ["archie-bunkers-place-complete-series", "ARCHIE BUNKER'S PLACE - S02E08 - The Camping Trip",
    "Archie Bunker's Place - S02E08.ia.mp4"],
  ["archie-bunkers-place-complete-series", "ARCHIE BUNKER'S PLACE - S02E09 - The Incident",
    "Archie Bunker's Place - S02E09.ia.mp4"],
  ["archie-bunkers-place-complete-series", "ARCHIE BUNKER'S PLACE - S02E10 - Custody: Part 1",
    "Archie Bunker's Place - S02E10.ia.mp4"],
  ["archie-bunkers-place-complete-series", "ARCHIE BUNKER'S PLACE - S02E11 - Custody: Part 2",
    "Archie Bunker's Place - S02E11.ia.mp4"],
  ["archie-bunkers-place-complete-series", "ARCHIE BUNKER'S PLACE - S02E12 - Barney the Gambler",
    "Archie Bunker's Place - S02E12.ia.mp4"],
  ["archie-bunkers-place-complete-series", "ARCHIE BUNKER'S PLACE - S02E13 - Murray Klein's Place",
    "Archie Bunker's Place - S02E13.ia.mp4"],
  ["archie-bunkers-place-complete-series", "ARCHIE BUNKER'S PLACE - S02E14 - Weekend Away",
    "Archie Bunker's Place - S02E14.ia.mp4"],
  ["archie-bunkers-place-complete-series", "ARCHIE BUNKER'S PLACE - S02E15 - Stephanie's Science Project",
    "Archie Bunker's Place - S02E15.ia.mp4"],
  ["archie-bunkers-place-complete-series", "ARCHIE BUNKER'S PLACE - S02E16 - Tough Love",
    "Archie Bunker's Place - S02E16.ia.mp4"],
  ["archie-bunkers-place-complete-series", "ARCHIE BUNKER'S PLACE - S02E17 - The Trashing of the Temple",
    "Archie Bunker's Place - S02E17.ia.mp4"],
  ["archie-bunkers-place-complete-series", "ARCHIE BUNKER'S PLACE - S02E18 - La Cage Aux Bunker",
    "Archie Bunker's Place - S02E18.ia.mp4"],
  ["archie-bunkers-place-complete-series", "ARCHIE BUNKER'S PLACE - S02E19 - Death of a Saint",
    "Archie Bunker's Place - S02E19.ia.mp4"],
  ["archie-bunkers-place-complete-series", "ARCHIE BUNKER'S PLACE - S02E20 - Goodbye, Murray",
    "Archie Bunker's Place - S02E20.ia.mp4"],
  ["archie-bunkers-place-complete-series", "ARCHIE BUNKER'S PLACE - S03E01 - Billie",
    "Archie Bunker's Place - S03E01.ia.mp4"],
  ["archie-bunkers-place-complete-series", "ARCHIE BUNKER'S PLACE - S03E02 - The Business Manager",
    "Archie Bunker's Place - S03E02.ia.mp4"],
  ["archie-bunkers-place-complete-series", "ARCHIE BUNKER'S PLACE - S03E03 - The Date",
    "Archie Bunker's Place - S03E03.ia.mp4"],
  ["archie-bunkers-place-complete-series", "ARCHIE BUNKER'S PLACE - S03E04 - Norma Rae Bunker",
    "Archie Bunker's Place - S03E04.ia.mp4"],
  ["archie-bunkers-place-complete-series", "ARCHIE BUNKER'S PLACE - S03E05 - Harry's Investment",
    "Archie Bunker's Place - S03E05.ia.mp4"],
  ["archie-bunkers-place-complete-series", "ARCHIE BUNKER'S PLACE - S03E06 - Three's a Crowd",
    "Archie Bunker's Place - S03E06.ia.mp4"],
  ["archie-bunkers-place-complete-series", "ARCHIE BUNKER'S PLACE - S03E07 - Happy Birthday, Stephanie",
    "Archie Bunker's Place - S03E07.ia.mp4"],
  ["archie-bunkers-place-complete-series", "ARCHIE BUNKER'S PLACE - S03E08 - Growing Up Is Hard to Do: Part 1",
    "Archie Bunker's Place - S03E08.ia.mp4"],
  ["archie-bunkers-place-complete-series", "ARCHIE BUNKER'S PLACE - S03E09 - Growing Up Is Hard to Do: Part 2",
    "Archie Bunker's Place - S03E09.ia.mp4"],
  ["archie-bunkers-place-complete-series", "ARCHIE BUNKER'S PLACE - S03E10 - Stephanie's Dance",
    "Archie Bunker's Place - S03E10.ia.mp4"],
  ["archie-bunkers-place-complete-series", "ARCHIE BUNKER'S PLACE - S03E11 - The Photo Contest",
    "Archie Bunker's Place - S03E11.ia.mp4"],
  ["archie-bunkers-place-complete-series", "ARCHIE BUNKER'S PLACE - S03E12 - Stephanie's Tryout",
    "Archie Bunker's Place - S03E12.ia.mp4"],
  ["archie-bunkers-place-complete-series", "ARCHIE BUNKER'S PLACE - S03E13 - The Night Visitor",
    "Archie Bunker's Place - S03E13.ia.mp4"],
  ["archie-bunkers-place-complete-series", "ARCHIE BUNKER'S PLACE - S03E14 - Reggie, 3; Archie, 0",
    "Archie Bunker's Place - S03E14.ia.mp4"],
  ["archie-bunkers-place-complete-series", "ARCHIE BUNKER'S PLACE - S03E15 - Blind Man's Bluff",
    "Archie Bunker's Place - S03E15.ia.mp4"],
  ["archie-bunkers-place-complete-series", "ARCHIE BUNKER'S PLACE - S03E16 - A Blast from the Past",
    "Archie Bunker's Place - S03E16.ia.mp4"],
  ["archie-bunkers-place-complete-series", "ARCHIE BUNKER'S PLACE - S03E17 - Sex and the Single Parent",
    "Archie Bunker's Place - S03E17.ia.mp4"],
  ["archie-bunkers-place-complete-series", "ARCHIE BUNKER'S PLACE - S03E18 - Gloria Comes Home: Part 1",
    "Archie Bunker's Place - S03E18.ia.mp4"],
  ["archie-bunkers-place-complete-series", "ARCHIE BUNKER'S PLACE - S03E19 - Gloria Comes Home: Part 2",
    "Archie Bunker's Place - S03E19.ia.mp4"],
  ["archie-bunkers-place-complete-series", "ARCHIE BUNKER'S PLACE - S03E20 - Of Mice and Bunker",
    "Archie Bunker's Place - S03E20.ia.mp4"],
  ["archie-bunkers-place-complete-series", "ARCHIE BUNKER'S PLACE - S03E21 - Relapse",
    "Archie Bunker's Place - S03E21.ia.mp4"],
  ["archie-bunkers-place-complete-series", "ARCHIE BUNKER'S PLACE - S03E22 - Love is Hell",
    "Archie Bunker's Place - S03E22.ia.mp4"],
  ["archie-bunkers-place-complete-series", "ARCHIE BUNKER'S PLACE - S03E23 - The Second Time Around",
    "Archie Bunker's Place - S03E23.ia.mp4"],
  ["archie-bunkers-place-complete-series", "ARCHIE BUNKER'S PLACE - S03E24 - West Side Astoria",
    "Archie Bunker's Place - S03E24.ia.mp4"],
  ["archie-bunkers-place-complete-series", "ARCHIE BUNKER'S PLACE - S03E25 - Billie Moves Out",
    "Archie Bunker's Place - S03E25.ia.mp4"],
  ["archie-bunkers-place-complete-series", "ARCHIE BUNKER'S PLACE - S03E26 - Rabinowitz's Brother",
    "Archie Bunker's Place - S03E26.ia.mp4"],
  ["archie-bunkers-place-complete-series", "ARCHIE BUNKER'S PLACE - S03E27 - Death of a Lodger",
    "Archie Bunker's Place - S03E27.ia.mp4"],
  ["archie-bunkers-place-complete-series", "ARCHIE BUNKER'S PLACE - S03E28 - The Battle of Bunker III",
    "Archie Bunker's Place - S03E28.ia.mp4"],
  ["archie-bunkers-place-complete-series", "ARCHIE BUNKER'S PLACE - S03E29 - Gloria: The First Day",
    "Archie Bunker's Place - S03E29.ia.mp4"],
  ["archie-bunkers-place-complete-series", "ARCHIE BUNKER'S PLACE - S04E01 - Archie's Night Out",
    "Archie Bunker's Place - S04E01.ia.mp4"],
  ["archie-bunkers-place-complete-series", "ARCHIE BUNKER'S PLACE - S04E02 - Gary's Ex",
    "Archie Bunker's Place - S04E02.ia.mp4"],
  ["archie-bunkers-place-complete-series", "ARCHIE BUNKER'S PLACE - S04E03 - The Eyewitnesses",
    "Archie Bunker's Place - S04E03.ia.mp4"],
  ["archie-bunkers-place-complete-series", "ARCHIE BUNKER'S PLACE - S04E04 - Double Date",
    "Archie Bunker's Place - S04E04.ia.mp4"],
  ["archie-bunkers-place-complete-series", "ARCHIE BUNKER'S PLACE - S04E05 - From the Waldorf to Astoria",
    "Archie Bunker's Place - S04E05.ia.mp4"],
  ["archie-bunkers-place-complete-series", "ARCHIE BUNKER'S PLACE - S04E06 - Stay Out of My Briefs",
    "Archie Bunker's Place - S04E06.ia.mp4"],
  ["archie-bunkers-place-complete-series", "ARCHIE BUNKER'S PLACE - S04E07 - Break a Leg, Stephanie",
    "Archie Bunker's Place - S04E07.ia.mp4"],
  ["archie-bunkers-place-complete-series", "ARCHIE BUNKER'S PLACE - S04E08 - Archie Gets a Head",
    "Archie Bunker's Place - S04E08.ia.mp4"],
  ["archie-bunkers-place-complete-series", "ARCHIE BUNKER'S PLACE - S04E09 - Barney Gets Laid Off",
    "Archie Bunker's Place - S04E09.ia.mp4"],
  ["archie-bunkers-place-complete-series", "ARCHIE BUNKER'S PLACE - S04E10 - Marriage on the Rocks",
    "Archie Bunker's Place - S04E10.ia.mp4"],
  ["archie-bunkers-place-complete-series", "ARCHIE BUNKER'S PLACE - S04E11 - Father Christmas",
    "Archie Bunker's Place - S04E11.ia.mp4"],
  ["archie-bunkers-place-complete-series", "ARCHIE BUNKER'S PLACE - S04E12 - Teacher's Pet",
    "Archie Bunker's Place - S04E12.ia.mp4"],
  ["archie-bunkers-place-complete-series", "ARCHIE BUNKER'S PLACE - S04E13 - Captain Video",
    "Archie Bunker's Place - S04E13.ia.mp4"],
  ["archie-bunkers-place-complete-series", "ARCHIE BUNKER'S PLACE - S04E14 - The Promotion",
    "Archie Bunker's Place - S04E14.ia.mp4"],
  ["archie-bunkers-place-complete-series", "ARCHIE BUNKER'S PLACE - S04E15 - Three Women",
    "Archie Bunker's Place - S04E15.ia.mp4"],
  ["archie-bunkers-place-complete-series", "ARCHIE BUNKER'S PLACE - S04E16 - Relief Bartender",
    "Archie Bunker's Place - S04E16.ia.mp4"],
  ["archie-bunkers-place-complete-series", "ARCHIE BUNKER'S PLACE - S04E17 - The Red Herring",
    "Archie Bunker's Place - S04E17.ia.mp4"],
  ["archie-bunkers-place-complete-series", "ARCHIE BUNKER'S PLACE - S04E18 - The Boys' Night Out",
    "Archie Bunker's Place - S04E18.ia.mp4"],
  ["archie-bunkers-place-complete-series", "ARCHIE BUNKER'S PLACE - S04E19 - I Can Manage",
    "Archie Bunker's Place - S04E19.ia.mp4"],
  ["archie-bunkers-place-complete-series", "ARCHIE BUNKER'S PLACE - S04E20 - Store Wars",
    "Archie Bunker's Place - S04E20.ia.mp4"],
  ["archie-bunkers-place-complete-series", "ARCHIE BUNKER'S PLACE - S04E21 - Bunker Madness",
    "Archie Bunker's Place - S04E21.ia.mp4"],
  ["archie-bunkers-place-complete-series", "ARCHIE BUNKER'S PLACE - S04E22 - No One Said It Was Easy",
    "Archie Bunker's Place - S04E22.ia.mp4"],
  ["archie-bunkers-place-complete-series", "ARCHIE BUNKER'S PLACE - S04E23 - Small Claims Court",
    "Archie Bunker's Place - S04E23.ia.mp4"],
  ["archie-bunkers-place-complete-series", "ARCHIE BUNKER'S PLACE - S04E24 - I'm Torn Here",
    "Archie Bunker's Place - S04E24.ia.mp4"],
],
  durations: {
  "archie-bunkers-place-complete-series::Archie Bunker's Place - S01E01.ia.mp4": 1329,
  "archie-bunkers-place-complete-series::Archie Bunker's Place - S01E02.ia.mp4": 1524,
  "archie-bunkers-place-complete-series::Archie Bunker's Place - S01E03.ia.mp4": 1486,
  "archie-bunkers-place-complete-series::Archie Bunker's Place - S01E04.ia.mp4": 1470,
  "archie-bunkers-place-complete-series::Archie Bunker's Place - S01E05.ia.mp4": 1478,
  "archie-bunkers-place-complete-series::Archie Bunker's Place - S01E06.ia.mp4": 1455,
  "archie-bunkers-place-complete-series::Archie Bunker's Place - S01E07.ia.mp4": 1452,
  "archie-bunkers-place-complete-series::Archie Bunker's Place - S01E08.ia.mp4": 1453,
  "archie-bunkers-place-complete-series::Archie Bunker's Place - S01E09.ia.mp4": 1494,
  "archie-bunkers-place-complete-series::Archie Bunker's Place - S01E10.ia.mp4": 1492,
  "archie-bunkers-place-complete-series::Archie Bunker's Place - S01E11.ia.mp4": 1492,
  "archie-bunkers-place-complete-series::Archie Bunker's Place - S01E12.ia.mp4": 1502,
  "archie-bunkers-place-complete-series::Archie Bunker's Place - S01E13.ia.mp4": 1475,
  "archie-bunkers-place-complete-series::Archie Bunker's Place - S01E14.ia.mp4": 1485,
  "archie-bunkers-place-complete-series::Archie Bunker's Place - S01E15.ia.mp4": 1489,
  "archie-bunkers-place-complete-series::Archie Bunker's Place - S01E16.ia.mp4": 1495,
  "archie-bunkers-place-complete-series::Archie Bunker's Place - S01E17.ia.mp4": 1495,
  "archie-bunkers-place-complete-series::Archie Bunker's Place - S01E18.ia.mp4": 1465,
  "archie-bunkers-place-complete-series::Archie Bunker's Place - S01E19.ia.mp4": 1490,
  "archie-bunkers-place-complete-series::Archie Bunker's Place - S01E20.ia.mp4": 1483,
  "archie-bunkers-place-complete-series::Archie Bunker's Place - S01E21.ia.mp4": 1490,
  "archie-bunkers-place-complete-series::Archie Bunker's Place - S01E22.ia.mp4": 1476,
  "archie-bunkers-place-complete-series::Archie Bunker's Place - S01E23.ia.mp4": 1468,
  "archie-bunkers-place-complete-series::Archie Bunker's Place - S01E24.ia.mp4": 1448,
  "archie-bunkers-place-complete-series::Archie Bunker's Place - S02E01.ia.mp4": 1328,
  "archie-bunkers-place-complete-series::Archie Bunker's Place - S02E02.ia.mp4": 1330,
  "archie-bunkers-place-complete-series::Archie Bunker's Place - S02E03.ia.mp4": 1494,
  "archie-bunkers-place-complete-series::Archie Bunker's Place - S02E04.ia.mp4": 1440,
  "archie-bunkers-place-complete-series::Archie Bunker's Place - S02E05.ia.mp4": 1494,
  "archie-bunkers-place-complete-series::Archie Bunker's Place - S02E06.ia.mp4": 1492,
  "archie-bunkers-place-complete-series::Archie Bunker's Place - S02E07.ia.mp4": 1475,
  "archie-bunkers-place-complete-series::Archie Bunker's Place - S02E08.ia.mp4": 1495,
  "archie-bunkers-place-complete-series::Archie Bunker's Place - S02E09.ia.mp4": 1492,
  "archie-bunkers-place-complete-series::Archie Bunker's Place - S02E10.ia.mp4": 1491,
  "archie-bunkers-place-complete-series::Archie Bunker's Place - S02E11.ia.mp4": 1493,
  "archie-bunkers-place-complete-series::Archie Bunker's Place - S02E12.ia.mp4": 1483,
  "archie-bunkers-place-complete-series::Archie Bunker's Place - S02E13.ia.mp4": 1485,
  "archie-bunkers-place-complete-series::Archie Bunker's Place - S02E14.ia.mp4": 1495,
  "archie-bunkers-place-complete-series::Archie Bunker's Place - S02E15.ia.mp4": 1498,
  "archie-bunkers-place-complete-series::Archie Bunker's Place - S02E16.ia.mp4": 1475,
  "archie-bunkers-place-complete-series::Archie Bunker's Place - S02E17.ia.mp4": 1496,
  "archie-bunkers-place-complete-series::Archie Bunker's Place - S02E18.ia.mp4": 1497,
  "archie-bunkers-place-complete-series::Archie Bunker's Place - S02E19.ia.mp4": 1498,
  "archie-bunkers-place-complete-series::Archie Bunker's Place - S02E20.ia.mp4": 1482,
  "archie-bunkers-place-complete-series::Archie Bunker's Place - S03E01.ia.mp4": 1498,
  "archie-bunkers-place-complete-series::Archie Bunker's Place - S03E02.ia.mp4": 1499,
  "archie-bunkers-place-complete-series::Archie Bunker's Place - S03E03.ia.mp4": 1484,
  "archie-bunkers-place-complete-series::Archie Bunker's Place - S03E04.ia.mp4": 1497,
  "archie-bunkers-place-complete-series::Archie Bunker's Place - S03E05.ia.mp4": 1499,
  "archie-bunkers-place-complete-series::Archie Bunker's Place - S03E06.ia.mp4": 1501,
  "archie-bunkers-place-complete-series::Archie Bunker's Place - S03E07.ia.mp4": 1497,
  "archie-bunkers-place-complete-series::Archie Bunker's Place - S03E08.ia.mp4": 1498,
  "archie-bunkers-place-complete-series::Archie Bunker's Place - S03E09.ia.mp4": 1497,
  "archie-bunkers-place-complete-series::Archie Bunker's Place - S03E10.ia.mp4": 1496,
  "archie-bunkers-place-complete-series::Archie Bunker's Place - S03E11.ia.mp4": 1490,
  "archie-bunkers-place-complete-series::Archie Bunker's Place - S03E12.ia.mp4": 1494,
  "archie-bunkers-place-complete-series::Archie Bunker's Place - S03E13.ia.mp4": 1494,
  "archie-bunkers-place-complete-series::Archie Bunker's Place - S03E14.ia.mp4": 1499,
  "archie-bunkers-place-complete-series::Archie Bunker's Place - S03E15.ia.mp4": 1491,
  "archie-bunkers-place-complete-series::Archie Bunker's Place - S03E16.ia.mp4": 1497,
  "archie-bunkers-place-complete-series::Archie Bunker's Place - S03E17.ia.mp4": 1487,
  "archie-bunkers-place-complete-series::Archie Bunker's Place - S03E18.ia.mp4": 1333,
  "archie-bunkers-place-complete-series::Archie Bunker's Place - S03E19.ia.mp4": 1332,
  "archie-bunkers-place-complete-series::Archie Bunker's Place - S03E20.ia.mp4": 1496,
  "archie-bunkers-place-complete-series::Archie Bunker's Place - S03E21.ia.mp4": 1495,
  "archie-bunkers-place-complete-series::Archie Bunker's Place - S03E22.ia.mp4": 1493,
  "archie-bunkers-place-complete-series::Archie Bunker's Place - S03E23.ia.mp4": 1504,
  "archie-bunkers-place-complete-series::Archie Bunker's Place - S03E24.ia.mp4": 1495,
  "archie-bunkers-place-complete-series::Archie Bunker's Place - S03E25.ia.mp4": 1494,
  "archie-bunkers-place-complete-series::Archie Bunker's Place - S03E26.ia.mp4": 1497,
  "archie-bunkers-place-complete-series::Archie Bunker's Place - S03E27.ia.mp4": 1488,
  "archie-bunkers-place-complete-series::Archie Bunker's Place - S03E28.ia.mp4": 1495,
  "archie-bunkers-place-complete-series::Archie Bunker's Place - S03E29.ia.mp4": 1487,
  "archie-bunkers-place-complete-series::Archie Bunker's Place - S04E01.ia.mp4": 1495,
  "archie-bunkers-place-complete-series::Archie Bunker's Place - S04E02.ia.mp4": 1496,
  "archie-bunkers-place-complete-series::Archie Bunker's Place - S04E03.ia.mp4": 1495,
  "archie-bunkers-place-complete-series::Archie Bunker's Place - S04E04.ia.mp4": 1495,
  "archie-bunkers-place-complete-series::Archie Bunker's Place - S04E05.ia.mp4": 1475,
  "archie-bunkers-place-complete-series::Archie Bunker's Place - S04E06.ia.mp4": 1495,
  "archie-bunkers-place-complete-series::Archie Bunker's Place - S04E07.ia.mp4": 1494,
  "archie-bunkers-place-complete-series::Archie Bunker's Place - S04E08.ia.mp4": 1485,
  "archie-bunkers-place-complete-series::Archie Bunker's Place - S04E09.ia.mp4": 1495,
  "archie-bunkers-place-complete-series::Archie Bunker's Place - S04E10.ia.mp4": 1496,
  "archie-bunkers-place-complete-series::Archie Bunker's Place - S04E11.ia.mp4": 1495,
  "archie-bunkers-place-complete-series::Archie Bunker's Place - S04E12.ia.mp4": 1496,
  "archie-bunkers-place-complete-series::Archie Bunker's Place - S04E13.ia.mp4": 1484,
  "archie-bunkers-place-complete-series::Archie Bunker's Place - S04E14.ia.mp4": 1489,
  "archie-bunkers-place-complete-series::Archie Bunker's Place - S04E15.ia.mp4": 1495,
  "archie-bunkers-place-complete-series::Archie Bunker's Place - S04E16.ia.mp4": 1483,
  "archie-bunkers-place-complete-series::Archie Bunker's Place - S04E17.ia.mp4": 1481,
  "archie-bunkers-place-complete-series::Archie Bunker's Place - S04E18.ia.mp4": 1495,
  "archie-bunkers-place-complete-series::Archie Bunker's Place - S04E19.ia.mp4": 1496,
  "archie-bunkers-place-complete-series::Archie Bunker's Place - S04E20.ia.mp4": 1491,
  "archie-bunkers-place-complete-series::Archie Bunker's Place - S04E21.ia.mp4": 1474,
  "archie-bunkers-place-complete-series::Archie Bunker's Place - S04E22.ia.mp4": 1486,
  "archie-bunkers-place-complete-series::Archie Bunker's Place - S04E23.ia.mp4": 1490,
  "archie-bunkers-place-complete-series::Archie Bunker's Place - S04E24.ia.mp4": 1495,
},
};
