window.SHOW = {
  id: "MaryTylerMooreShow",
  title: "The Mary Tyler Moore Show",
  art: "MaryTylerMooreShow.jpg",
  storageProgressKey: "marytylermooreshow-progress",
  storageSettingsKey: "marytylermooreshow-settings",
  nestedPaths: true,
  grouping: "season",
  segments: "none",
  episodes: [
  ["the-mary-tyler-moore-show-complete-series", "THE MARY TYLER MOORE SHOW - S01E01 - Love is All Around",
    "The Mary Tyler Moore Show S01E01 - Love is All Around.mp4"],
  ["the-mary-tyler-moore-show-complete-series", "THE MARY TYLER MOORE SHOW - S01E02 - Today I Am a Ma'am",
    "The Mary Tyler Moore Show S01E02 - Today I Am A Ma'am.mp4"],
  ["the-mary-tyler-moore-show-complete-series", "THE MARY TYLER MOORE SHOW - S01E03 - Bess, You is My Daughter Now",
    "The Mary Tyler Moore Show S01E03 - Bess, You is My Daughter Now.mp4"],
  ["the-mary-tyler-moore-show-complete-series", "THE MARY TYLER MOORE SHOW - S01E04 - Divorce Isn't Everything",
    "The Mary Tyler Moore Show S01E04 - Divorce Isn't Everything.mp4"],
  ["the-mary-tyler-moore-show-complete-series", "THE MARY TYLER MOORE SHOW - S01E05 - Keep Your Guard Up",
    "The Mary Tyler Moore Show S01E05 - Keep Your Guard Up.mp4"],
  ["the-mary-tyler-moore-show-complete-series", "THE MARY TYLER MOORE SHOW - S01E06 - Support Your Local Mother",
    "The Mary Tyler Moore Show S01E06 - Support Your Local Mother.mp4"],
  ["the-mary-tyler-moore-show-complete-series", "THE MARY TYLER MOORE SHOW - S01E07 - Toulousse-Lautrec is One of My Favorite Artists",
    "The Mary Tyler Moore Show S01E07 - Toulouse-Lautrec is One of My Favorite Artists.mp4"],
  ["the-mary-tyler-moore-show-complete-series", "THE MARY TYLER MOORE SHOW - S01E08 - The Snow Must Go On",
    "The Mary Tyler Moore Show S01E08 - The Snow Must Go On.mp4"],
  ["the-mary-tyler-moore-show-complete-series", "THE MARY TYLER MOORE SHOW - S01E09 - Bob & Rhoda & Teddy & Mary",
    "The Mary Tyler Moore Show S01E09 - Bob & Rhoda & Teddy & Mary.mp4"],
  ["the-mary-tyler-moore-show-complete-series", "THE MARY TYLER MOORE SHOW - S01E10 - Assistant Wanted, Female",
    "The Mary Tyler Moore Show S01E10 - Assistant Wanted, Female.mp4"],
  ["the-mary-tyler-moore-show-complete-series", "THE MARY TYLER MOORE SHOW - S01E11 - 1040 or Fight",
    "The Mary Tyler Moore Show S01E11 - 1040 or Fight.mp4"],
  ["the-mary-tyler-moore-show-complete-series", "THE MARY TYLER MOORE SHOW - S01E12 - Anchorman Overboard",
    "The Mary Tyler Moore Show S01E12 - Anchorman Overboard.mp4"],
  ["the-mary-tyler-moore-show-complete-series", "THE MARY TYLER MOORE SHOW - S01E13 - He's All Yours",
    "The Mary Tyler Moore Show S01E13 - He's All Yours.mp4"],
  ["the-mary-tyler-moore-show-complete-series", "THE MARY TYLER MOORE SHOW - S01E14 - Christmas and the Hard Luck Kid II",
    "The Mary Tyler Moore Show S01E14 - Christmas and The Hard Luck Kid II.mp4"],
  ["the-mary-tyler-moore-show-complete-series", "THE MARY TYLER MOORE SHOW - S01E15 - Howard's Girl",
    "The Mary Tyler Moore Show S01E15 - Howard's Girl.mp4"],
  ["the-mary-tyler-moore-show-complete-series", "THE MARY TYLER MOORE SHOW - S01E16 - Party is Such Sweet Sorrow",
    "The Mary Tyler Moore Show S01E16 - Party is Such Sweet Sorrow.mp4"],
  ["the-mary-tyler-moore-show-complete-series", "THE MARY TYLER MOORE SHOW - S01E17 - Just a Lunch",
    "The Mary Tyler Moore Show S01E17 - Just A Lunch.mp4"],
  ["the-mary-tyler-moore-show-complete-series", "THE MARY TYLER MOORE SHOW - S01E18 - Second Story Story",
    "The Mary Tyler Moore Show S01E18 - Second Story Story.mp4"],
  ["the-mary-tyler-moore-show-complete-series", "THE MARY TYLER MOORE SHOW - S01E19 - We Closed in Minneapolis",
    "The Mary Tyler Moore Show S01E19 - We Closed in Minneapolis.mp4"],
  ["the-mary-tyler-moore-show-complete-series", "THE MARY TYLER MOORE SHOW - S01E20 - Hi!",
    "The Mary Tyler Moore Show S01E20 - Hi!.mp4"],
  ["the-mary-tyler-moore-show-complete-series", "THE MARY TYLER MOORE SHOW - S01E21 - The Boss Isn't Coming to Dinner",
    "The Mary Tyler Moore Show S01E21 - The Boss Isn't Coming to Dinner.mp4"],
  ["the-mary-tyler-moore-show-complete-series", "THE MARY TYLER MOORE SHOW - S01E22 - A Friend in Deed",
    "The Mary Tyler Moore Show S01E22 - A Friend in Deed.mp4"],
  ["the-mary-tyler-moore-show-complete-series", "THE MARY TYLER MOORE SHOW - S01E23 - Smokey the Bear Wants You",
    "The Mary Tyler Moore Show S01E23 - Smokey The Bear Wants You.mp4"],
  ["the-mary-tyler-moore-show-complete-series", "THE MARY TYLER MOORE SHOW - S01E24 - The 45-Year-Old Man",
    "The Mary Tyler Moore Show S01E24 - The 45-Year-Old Man.mp4"],
  ["the-mary-tyler-moore-show-complete-series", "THE MARY TYLER MOORE SHOW - S02E01 - The Birds . . . and . . . um . . . Bees",
    "The Mary Tyler Moore Show S02E01 - The Birds . . . and . . . um . . . Bees.mp4"],
  ["the-mary-tyler-moore-show-complete-series", "THE MARY TYLER MOORE SHOW - S02E02 - I Am Curious Cooper",
    "The Mary Tyler Moore Show S02E02 - I Am Curious Cooper.mp4"],
  ["the-mary-tyler-moore-show-complete-series", "THE MARY TYLER MOORE SHOW - S02E03 - He's No Heavy . . . He's My Brother",
    "The Mary Tyler Moore Show S02E03 - He's No Heavy . . . He's My Brother.mp4"],
  ["the-mary-tyler-moore-show-complete-series", "THE MARY TYLER MOORE SHOW - S02E04 - Room 223",
    "The Mary Tyler Moore Show S02E04 - Room 223.mp4"],
  ["the-mary-tyler-moore-show-complete-series", "THE MARY TYLER MOORE SHOW - S02E05 - A Girl's Best Mother is Not Her Friend",
    "The Mary Tyler Moore Show S02E05 - A Girl's Best Mother is Not Her Friend.mp4"],
  ["the-mary-tyler-moore-show-complete-series", "THE MARY TYLER MOORE SHOW - S02E06 - Cover Boy",
    "The Mary Tyler Moore Show S02E06 - Cover Boy.mp4"],
  ["the-mary-tyler-moore-show-complete-series", "THE MARY TYLER MOORE SHOW - S02E07 - Didn't You Used to Be . . . Wait . . . Don't Tell Me",
    "The Mary Tyler Moore Show S02E07 - Didn't You Used to Be . . . Wait . . . Don't Tell Me.mp4"],
  ["the-mary-tyler-moore-show-complete-series", "THE MARY TYLER MOORE SHOW - S02E08 - Thoroughly Unmilitant Mary",
    "The Mary Tyler Moore Show S02E08 - Thoroughly Unmilitant Mary.mp4"],
  ["the-mary-tyler-moore-show-complete-series", "THE MARY TYLER MOORE SHOW - S02E09 - And Now, Sitting in for Ted Baxter",
    "The Mary Tyler Moore Show S02E09 - And Now, Sitting in for Ted Baxter.mp4"],
  ["the-mary-tyler-moore-show-complete-series", "THE MARY TYLER MOORE SHOW - S02E10 - Don't Break the Chain",
    "The Mary Tyler Moore Show S02E10 - Don't Break The Chain.mp4"],
  ["the-mary-tyler-moore-show-complete-series", "THE MARY TYLER MOORE SHOW - S02E11 - The Six-and-a-Half-Year Itch",
    "The Mary Tyler Moore Show S02E11 - The Six-and-a-Half-Year Itch.mp4"],
  ["the-mary-tyler-moore-show-complete-series", "THE MARY TYLER MOORE SHOW - S02E12 - . . . Is a Friend in Need",
    "The Mary Tyler Moore Show S02E12 - . . . Is A Friend in Need.mp4"],
  ["the-mary-tyler-moore-show-complete-series", "THE MARY TYLER MOORE SHOW - S02E13 - The Square-Shaped Room",
    "The Mary Tyler Moore Show S02E13 - The Square-Shaped Room.mp4"],
  ["the-mary-tyler-moore-show-complete-series", "THE MARY TYLER MOORE SHOW - S02E14 - Ted Over Heels",
    "The Mary Tyler Moore Show S02E14 - Ted Over Heels.mp4"],
  ["the-mary-tyler-moore-show-complete-series", "THE MARY TYLER MOORE SHOW - S02E15 - The Five-Minute Dress",
    "The Mary Tyler Moore Show S02E15 - The Five-Minute Dress.mp4"],
  ["the-mary-tyler-moore-show-complete-series", "THE MARY TYLER MOORE SHOW - S02E16 - Feeb",
    "The Mary Tyler Moore Show S02E16 - Feeb.mp4"],
  ["the-mary-tyler-moore-show-complete-series", "THE MARY TYLER MOORE SHOW - S02E17 - The Slaughter Affair",
    "The Mary Tyler Moore Show S02E17 - The Slaughter Affair.mp4"],
  ["the-mary-tyler-moore-show-complete-series", "THE MARY TYLER MOORE SHOW - S02E18 - Baby Sit-Com",
    "The Mary Tyler Moore Show S02E18 - Baby Sit-Com.mp4"],
  ["the-mary-tyler-moore-show-complete-series", "THE MARY TYLER MOORE SHOW - S02E19 - More Than Neighbors",
    "The Mary Tyler Moore Show S02E19 - More Than Neighbors.mp4"],
  ["the-mary-tyler-moore-show-complete-series", "THE MARY TYLER MOORE SHOW - S02E20 - The Care and Feeding of Parents",
    "The Mary Tyler Moore Show S02E20 - The Care and Feeding of Parents.mp4"],
  ["the-mary-tyler-moore-show-complete-series", "THE MARY TYLER MOORE SHOW - S02E21 - Where There's Smoke, There's Rhoda",
    "The Mary Tyler Moore Show S02E21 - Where There's Smoke, There's Rhoda.mp4"],
  ["the-mary-tyler-moore-show-complete-series", "THE MARY TYLER MOORE SHOW - S02E22 - You Certainly Are a Big Boy",
    "The Mary Tyler Moore Show S02E22 - You Certainly Are A Big Boy.mp4"],
  ["the-mary-tyler-moore-show-complete-series", "THE MARY TYLER MOORE SHOW - S02E23 - Some of My Best Friends Are Rhoda",
    "The Mary Tyler Moore Show S02E23 - Some of My Best Friends Are Rhoda.mp4"],
  ["the-mary-tyler-moore-show-complete-series", "THE MARY TYLER MOORE SHOW - S02E24 - His Two Right Arms",
    "The Mary Tyler Moore Show S02E24 - His Two Right Arms.mp4"],
  ["the-mary-tyler-moore-show-complete-series", "THE MARY TYLER MOORE SHOW - S03E01 - The Good-Time News",
    "The Mary Tyler Moore Show S03E01 - The Good-Time News.mp4"],
  ["the-mary-tyler-moore-show-complete-series", "THE MARY TYLER MOORE SHOW - S03E02 - What is Mary Richards Really Like?",
    "The Mary Tyler Moore Show S03E02 - What is Mary Richards Really Like.mp4"],
  ["the-mary-tyler-moore-show-complete-series", "THE MARY TYLER MOORE SHOW - S03E03 - Who's in Charge Here?",
    "The Mary Tyler Moore Show S03E03 - Who's in Charge Here.mp4"],
  ["the-mary-tyler-moore-show-complete-series", "THE MARY TYLER MOORE SHOW - S03E04 - Enter Rhoda's Parents",
    "The Mary Tyler Moore Show S03E04 - Enter Rhoda's Parents.mp4"],
  ["the-mary-tyler-moore-show-complete-series", "THE MARY TYLER MOORE SHOW - S03E05 - It's Whether You Win or Lose",
    "The Mary Tyler Moore Show S03E05 - It's Whether You Win or Lose.mp4"],
  ["the-mary-tyler-moore-show-complete-series", "THE MARY TYLER MOORE SHOW - S03E06 - Rhoda the Beautiful",
    "The Mary Tyler Moore Show S03E06 - Rhoda The Beautiful.mp4"],
  ["the-mary-tyler-moore-show-complete-series", "THE MARY TYLER MOORE SHOW - S03E07 - Just Around the Corner",
    "The Mary Tyler Moore Show S03E07 - Just Around the Corner.mp4"],
  ["the-mary-tyler-moore-show-complete-series", "THE MARY TYLER MOORE SHOW - S03E08 - But Seriously, Folks",
    "The Mary Tyler Moore Show S03E08 - But Seriously, Folks.mp4"],
  ["the-mary-tyler-moore-show-complete-series", "THE MARY TYLER MOORE SHOW - S03E09 - Farmer Ted and the News",
    "The Mary Tyler Moore Show S03E09 - Farmer Ted and The News.mp4"],
  ["the-mary-tyler-moore-show-complete-series", "THE MARY TYLER MOORE SHOW - S03E10 - Have I Found a Guy for You",
    "The Mary Tyler Moore Show S03E10 - Have I Found A Guy for You.mp4"],
  ["the-mary-tyler-moore-show-complete-series", "THE MARY TYLER MOORE SHOW - S03E11 - You've Got a Friend",
    "The Mary Tyler Moore Show S03E11 - You've Got A Friend.mp4"],
  ["the-mary-tyler-moore-show-complete-series", "THE MARY TYLER MOORE SHOW - S03E12 - It Was Fascination, I Know",
    "The Mary Tyler Moore Show S03E12 - It Was Fascination, I Know.mp4"],
  ["the-mary-tyler-moore-show-complete-series", "THE MARY TYLER MOORE SHOW - S03E13 - Operation: Lou",
    "The Mary Tyler Moore Show S03E13 - Operation Lou.mp4"],
  ["the-mary-tyler-moore-show-complete-series", "THE MARY TYLER MOORE SHOW - S03E14 - Rhoda Morgenstern: Minneapolis to New York",
    "The Mary Tyler Moore Show S03E14 - Rhoda Morgenstern Minneapolis to New York.mp4"],
  ["the-mary-tyler-moore-show-complete-series", "THE MARY TYLER MOORE SHOW - S03E15 - The Courtship of Mary's Father's Daughter",
    "The Mary Tyler Moore Show S03E15 - The Courtship of Mary's Father's Daughter.mp4"],
  ["the-mary-tyler-moore-show-complete-series", "THE MARY TYLER MOORE SHOW - S03E16 - Lou's Place",
    "The Mary Tyler Moore Show S03E16 - Lou's Place.mp4"],
  ["the-mary-tyler-moore-show-complete-series", "THE MARY TYLER MOORE SHOW - S03E17 - My Brother's Keeper",
    "The Mary Tyler Moore Show S03E17 - My Brother's Keeper.mp4"],
  ["the-mary-tyler-moore-show-complete-series", "THE MARY TYLER MOORE SHOW - S03E18 - The Georgette Story",
    "The Mary Tyler Moore Show S03E18 - The Georgette Story.mp4"],
  ["the-mary-tyler-moore-show-complete-series", "THE MARY TYLER MOORE SHOW - S03E19 - Romeo and Mary",
    "The Mary Tyler Moore Show S03E19 - Romeo and Mary.mp4"],
  ["the-mary-tyler-moore-show-complete-series", "THE MARY TYLER MOORE SHOW - S03E20 - What Do You Do When the Boss Says, \"I Love You\"?",
    "The Mary Tyler Moore Show S03E20 - What Do You Do When The Boss Says, “I Love You”.mp4"],
  ["the-mary-tyler-moore-show-complete-series", "THE MARY TYLER MOORE SHOW - S03E21 - Murray Faces Life",
    "The Mary Tyler Moore Show S03E21 - Murray Faces Life.mp4"],
  ["the-mary-tyler-moore-show-complete-series", "THE MARY TYLER MOORE SHOW - S03E22 - Remembrance of Things Past",
    "The Mary Tyler Moore Show S03E22 - Remembrance of Things Past.mp4"],
  ["the-mary-tyler-moore-show-complete-series", "THE MARY TYLER MOORE SHOW - S03E23 - Put on a Happy Face",
    "The Mary Tyler Moore Show S03E23 - Put On A Happy Face.mp4"],
  ["the-mary-tyler-moore-show-complete-series", "THE MARY TYLER MOORE SHOW - S03E24 - Mary Richards and the Incredible Plant Lady",
    "The Mary Tyler Moore Show S03E24 - Mary Richards and The Incredible Plant Lady.mp4"],
  ["the-mary-tyler-moore-show-complete-series", "THE MARY TYLER MOORE SHOW - S04E01 - The Lars Affair",
    "The Mary Tyler Moore Show S04E01 - The Lars Affair.mp4"],
  ["the-mary-tyler-moore-show-complete-series", "THE MARY TYLER MOORE SHOW - S04E02 - Angels in the Snow",
    "The Mary Tyler Moore Show S04E02 - Angels in The Snow.mp4"],
  ["the-mary-tyler-moore-show-complete-series", "THE MARY TYLER MOORE SHOW - S04E03 - Rhoda's Sister Gets Married",
    "The Mary Tyler Moore Show S04E03 - Rhoda's Sister Gets Married.mp4"],
  ["the-mary-tyler-moore-show-complete-series", "THE MARY TYLER MOORE SHOW - S04E04 - The Lou and Edie Story",
    "The Mary Tyler Moore Show S04E04 - The Lou and Edie Story.mp4"],
  ["the-mary-tyler-moore-show-complete-series", "THE MARY TYLER MOORE SHOW - S04E05 - Hi There, Sports Fans",
    "The Mary Tyler Moore Show S04E05 - Hi There, Sports Fans.mp4"],
  ["the-mary-tyler-moore-show-complete-series", "THE MARY TYLER MOORE SHOW - S04E06 - Father's Day",
    "The Mary Tyler Moore Show S04E06 - Father's Day.mp4"],
  ["the-mary-tyler-moore-show-complete-series", "THE MARY TYLER MOORE SHOW - S04E07 - Son of \"But Seriously, Folks\"",
    "The Mary Tyler Moore Show S04E07 - Son of “But Seriously, Folks”.mp4"],
  ["the-mary-tyler-moore-show-complete-series", "THE MARY TYLER MOORE SHOW - S04E08 - Lou's First Date",
    "The Mary Tyler Moore Show S04E08 - Lou's First Date.mp4"],
  ["the-mary-tyler-moore-show-complete-series", "THE MARY TYLER MOORE SHOW - S04E09 - Love Blooms at Hemples",
    "The Mary Tyler Moore Show S04E09 - Love Blooms at Hemples.mp4"],
  ["the-mary-tyler-moore-show-complete-series", "THE MARY TYLER MOORE SHOW - S04E10 - The Dinner Party",
    "The Mary Tyler Moore Show S04E10 - The Dinner Party.mp4"],
  ["the-mary-tyler-moore-show-complete-series", "THE MARY TYLER MOORE SHOW - S04E11 - Just Friends",
    "The Mary Tyler Moore Show S04E11 - Just Friends.mp4"],
  ["the-mary-tyler-moore-show-complete-series", "THE MARY TYLER MOORE SHOW - S04E12 - We Want Baxter",
    "The Mary Tyler Moore Show S04E12 - We Want Baxter.mp4"],
  ["the-mary-tyler-moore-show-complete-series", "THE MARY TYLER MOORE SHOW - S04E13 - I Gave at the Office",
    "The Mary Tyler Moore Show S04E13 - I Gave at The Office.mp4"],
  ["the-mary-tyler-moore-show-complete-series", "THE MARY TYLER MOORE SHOW - S04E14 - Almost a Nun's Story",
    "The Mary Tyler Moore Show S04E14 - Almost A Nun's Story.mp4"],
  ["the-mary-tyler-moore-show-complete-series", "THE MARY TYLER MOORE SHOW - S04E15 - Happy Birthday, Lou!",
    "The Mary Tyler Moore Show S04E15 - Happy Birthday, Lou!.mp4"],
  ["the-mary-tyler-moore-show-complete-series", "THE MARY TYLER MOORE SHOW - S04E16 - WJM Tries Harder",
    "The Mary Tyler Moore Show S04E16 - WJM Tries Harder.mp4"],
  ["the-mary-tyler-moore-show-complete-series", "THE MARY TYLER MOORE SHOW - S04E17 - Cottage for Sale",
    "The Mary Tyler Moore Show S04E17 - Cottage for Sale.mp4"],
  ["the-mary-tyler-moore-show-complete-series", "THE MARY TYLER MOORE SHOW - S04E18 - The Co-Producers",
    "The Mary Tyler Moore Show S04E18 - The Co-Producers.mp4"],
  ["the-mary-tyler-moore-show-complete-series", "THE MARY TYLER MOORE SHOW - S04E19 - Best of Enemies",
    "The Mary Tyler Moore Show S04E19 - Best of Enemies.mp4"],
  ["the-mary-tyler-moore-show-complete-series", "THE MARY TYLER MOORE SHOW - S04E20 - Better Late . . . That's a Pun . . . Than Never",
    "The Mary Tyler Moore Show S04E20 - Better Late . . . That's A Pun . . . Than Never.mp4"],
  ["the-mary-tyler-moore-show-complete-series", "THE MARY TYLER MOORE SHOW - S04E21 - Ted Baxter Meets Walter Cronkite",
    "The Mary Tyler Moore Show S04E21 - Ted Baxter Meets Walter Cronkite.mp4"],
  ["the-mary-tyler-moore-show-complete-series", "THE MARY TYLER MOORE SHOW - S04E22 - Lou's Second Date",
    "The Mary Tyler Moore Show S04E22 - Lou's Second Date.mp4"],
  ["the-mary-tyler-moore-show-complete-series", "THE MARY TYLER MOORE SHOW - S04E23 - Two Wrongs Don't Make a Writer",
    "The Mary Tyler Moore Show S04E23 - Two Wrongs Don't Make A Writer.mp4"],
  ["the-mary-tyler-moore-show-complete-series", "THE MARY TYLER MOORE SHOW - S04E24 - I Was a Single for WJM",
    "The Mary Tyler Moore Show S04E24 - I Was A Single for WJM.mp4"],
  ["the-mary-tyler-moore-show-complete-series", "THE MARY TYLER MOORE SHOW - S05E01 - Will Mary Richards Go to Jail?",
    "The Mary Tyler Moore Show S05E01 - Will Mary Richards Go to Jail.mp4"],
  ["the-mary-tyler-moore-show-complete-series", "THE MARY TYLER MOORE SHOW - S05E02 - Not Just Another Pretty Face",
    "The Mary Tyler Moore Show S05E02 - Not Just Another Pretty Face.mp4"],
  ["the-mary-tyler-moore-show-complete-series", "THE MARY TYLER MOORE SHOW - S05E03 - You Sometimes Hurt the One You Hate",
    "The Mary Tyler Moore Show S05E03 - You Sometimes Hurt The One You Hate.mp4"],
  ["the-mary-tyler-moore-show-complete-series", "THE MARY TYLER MOORE SHOW - S05E04 - Lou and That Woman",
    "The Mary Tyler Moore Show S05E04 - Lou and That Woman.mp4"],
  ["the-mary-tyler-moore-show-complete-series", "THE MARY TYLER MOORE SHOW - S05E05 - The Outsider",
    "The Mary Tyler Moore Show S05E05 - The Outsider.mp4"],
  ["the-mary-tyler-moore-show-complete-series", "THE MARY TYLER MOORE SHOW - S05E06 - I Love a Piano",
    "The Mary Tyler Moore Show S05E06 - I Love A Piano.mp4"],
  ["the-mary-tyler-moore-show-complete-series", "THE MARY TYLER MOORE SHOW - S05E07 - A New Sue Ann",
    "The Mary Tyler Moore Show S05E07 - The New Sue Ann.mp4"],
  ["the-mary-tyler-moore-show-complete-series", "THE MARY TYLER MOORE SHOW - S05E08 - Menage-a-Phyllis",
    "The Mary Tyler Moore Show S05E08 - Menage-a-Phyllis.mp4"],
  ["the-mary-tyler-moore-show-complete-series", "THE MARY TYLER MOORE SHOW - S05E09 - Not a Christmas Story",
    "The Mary Tyler Moore Show S05E09 - Not A Christmas Story.mp4"],
  ["the-mary-tyler-moore-show-complete-series", "THE MARY TYLER MOORE SHOW - S05E10 - What Are Friends For?",
    "The Mary Tyler Moore Show S05E10 - What are Friends For.mp4"],
  ["the-mary-tyler-moore-show-complete-series", "THE MARY TYLER MOORE SHOW - S05E11 - A Boy's Best Friend",
    "The Mary Tyler Moore Show S05E11 - A Boy's Best Friend.mp4"],
  ["the-mary-tyler-moore-show-complete-series", "THE MARY TYLER MOORE SHOW - S05E12 - A Son for Murray",
    "The Mary Tyler Moore Show S05E12 - A Son for Murray.mp4"],
  ["the-mary-tyler-moore-show-complete-series", "THE MARY TYLER MOORE SHOW - S05E13 - Neighbors",
    "The Mary Tyler Moore Show S05E13 - Neighbors.mp4"],
  ["the-mary-tyler-moore-show-complete-series", "THE MARY TYLER MOORE SHOW - S05E14 - A Girl Like Mary",
    "The Mary Tyler Moore Show S05E14 - A Girl Like Mary.mp4"],
  ["the-mary-tyler-moore-show-complete-series", "THE MARY TYLER MOORE SHOW - S05E15 - An Affair to Forget",
    "The Mary Tyler Moore Show S05E15 - An Affair to Forget.mp4"],
  ["the-mary-tyler-moore-show-complete-series", "THE MARY TYLER MOORE SHOW - S05E16 - Mary Richards: Producer",
    "The Mary Tyler Moore Show S05E16 - Mary Richards Producer.mp4"],
  ["the-mary-tyler-moore-show-complete-series", "THE MARY TYLER MOORE SHOW - S05E17 - The System",
    "The Mary Tyler Moore Show S05E17 - The System.mp4"],
  ["the-mary-tyler-moore-show-complete-series", "THE MARY TYLER MOORE SHOW - S05E18 - Phyllis Whips Inflation",
    "The Mary Tyler Moore Show S05E18 - Phyllis Whips Inflation.mp4"],
  ["the-mary-tyler-moore-show-complete-series", "THE MARY TYLER MOORE SHOW - S05E19 - The Shame of the Cities",
    "The Mary Tyler Moore Show S05E19 - The Shame of The Cities.mp4"],
  ["the-mary-tyler-moore-show-complete-series", "THE MARY TYLER MOORE SHOW - S05E20 - Marriage Minneapolis Style",
    "The Mary Tyler Moore Show S05E20 - Marriage Minneapolis Style.mp4"],
  ["the-mary-tyler-moore-show-complete-series", "THE MARY TYLER MOORE SHOW - S05E21 - You Try to Be a Nice Guy",
    "The Mary Tyler Moore Show S05E21 - You Try to Be A Nice Guy.mp4"],
  ["the-mary-tyler-moore-show-complete-series", "THE MARY TYLER MOORE SHOW - S05E22 - You Can't Lose 'em All",
    "The Mary Tyler Moore Show S05E22 - You Can't Lose 'em All.mp4"],
  ["the-mary-tyler-moore-show-complete-series", "THE MARY TYLER MOORE SHOW - S05E23 - Ted Baxter's Famous Broadcasters' School",
    "The Mary Tyler Moore Show S05E23 - Ted Baxter's Famous Broadcasters' School.mp4"],
  ["the-mary-tyler-moore-show-complete-series", "THE MARY TYLER MOORE SHOW - S05E24 - Anyone Who Hates Kids and Dogs",
    "The Mary Tyler Moore Show S05E24 - Anyone Who Hates Kids and Dogs.mp4"],
  ["the-mary-tyler-moore-show-complete-series", "THE MARY TYLER MOORE SHOW - S06E01 - Edie Gets Married",
    "The Mary Tyler Moore Show S06E01 - Edie Gets Married.mp4"],
  ["the-mary-tyler-moore-show-complete-series", "THE MARY TYLER MOORE SHOW - S06E02 - Mary Moves Out",
    "The Mary Tyler Moore Show S06E02 - Mary Moves Out.mp4"],
  ["the-mary-tyler-moore-show-complete-series", "THE MARY TYLER MOORE SHOW - S06E03 - Mary's Father",
    "The Mary Tyler Moore Show S06E03 - Mary's Father.mp4"],
  ["the-mary-tyler-moore-show-complete-series", "THE MARY TYLER MOORE SHOW - S06E04 - Murray in Love",
    "The Mary Tyler Moore Show S06E04 - Murray in Love.mp4"],
  ["the-mary-tyler-moore-show-complete-series", "THE MARY TYLER MOORE SHOW - S06E05 - Ted's Moment of Glory",
    "The Mary Tyler Moore Show S06E05 - Ted's Moment of Glory.mp4"],
  ["the-mary-tyler-moore-show-complete-series", "THE MARY TYLER MOORE SHOW - S06E06 - Mary's Aunt",
    "The Mary Tyler Moore Show S06E06 - Mary's Aunt.mp4"],
  ["the-mary-tyler-moore-show-complete-series", "THE MARY TYLER MOORE SHOW - S06E07 - Chuckles Bites the Dust",
    "The Mary Tyler Moore Show S06E07 - Chuckles Bites The Dust.mp4"],
  ["the-mary-tyler-moore-show-complete-series", "THE MARY TYLER MOORE SHOW - S06E08 - Mary's Delinquent",
    "The Mary Tyler Moore Show S06E08 - Mary's Delinquent.mp4"],
  ["the-mary-tyler-moore-show-complete-series", "THE MARY TYLER MOORE SHOW - S06E09 - Ted's Wedding",
    "The Mary Tyler Moore Show S06E09 - Ted's Wedding.mp4"],
  ["the-mary-tyler-moore-show-complete-series", "THE MARY TYLER MOORE SHOW - S06E10 - Lou Douses an Old Flame",
    "The Mary Tyler Moore Show S06E10 - Lou Douses An Old Flame.mp4"],
  ["the-mary-tyler-moore-show-complete-series", "THE MARY TYLER MOORE SHOW - S06E11 - Mary Richards Falls in Love",
    "The Mary Tyler Moore Show S06E11 - Mary Richards Falls in Love.mp4"],
  ["the-mary-tyler-moore-show-complete-series", "THE MARY TYLER MOORE SHOW - S06E12 - Ted's Tax Refund",
    "The Mary Tyler Moore Show S06E12 - Ted's Tax Refund.mp4"],
  ["the-mary-tyler-moore-show-complete-series", "THE MARY TYLER MOORE SHOW - S06E13 - The Happy Homemaker Takes Lou Home",
    "The Mary Tyler Moore Show S06E13 - The Happy Homemaker Takes Lou Home.mp4"],
  ["the-mary-tyler-moore-show-complete-series", "THE MARY TYLER MOORE SHOW - S06E14 - One Boyfriend Too Many",
    "The Mary Tyler Moore Show S06E14 - One Boyfriend Too Many.mp4"],
  ["the-mary-tyler-moore-show-complete-series", "THE MARY TYLER MOORE SHOW - S06E15 - What Do You Want to Do When You Produce?",
    "The Mary Tyler Moore Show S06E15 - What Do You Want to Do When You Produce.mp4"],
  ["the-mary-tyler-moore-show-complete-series", "THE MARY TYLER MOORE SHOW - S06E16 - Not with My Wife, I Don't",
    "The Mary Tyler Moore Show S06E16 - Not with My Wife, I Don't.mp4"],
  ["the-mary-tyler-moore-show-complete-series", "THE MARY TYLER MOORE SHOW - S06E17 - The Seminar",
    "The Mary Tyler Moore Show S06E17 - The Seminar.mp4"],
  ["the-mary-tyler-moore-show-complete-series", "THE MARY TYLER MOORE SHOW - S06E18 - Once I Had a Secret Love",
    "The Mary Tyler Moore Show S06E18 - Once I Had A Secret Love.mp4"],
  ["the-mary-tyler-moore-show-complete-series", "THE MARY TYLER MOORE SHOW - S06E19 - Menage-a-Lou",
    "The Mary Tyler Moore Show S06E19 - Menage-a-Lou.mp4"],
  ["the-mary-tyler-moore-show-complete-series", "THE MARY TYLER MOORE SHOW - S06E20 - Murray Takes a Stand",
    "The Mary Tyler Moore Show S06E20 - Murray Takes A Stand.mp4"],
  ["the-mary-tyler-moore-show-complete-series", "THE MARY TYLER MOORE SHOW - S06E21 - Mary's Aunt Returns",
    "The Mary Tyler Moore Show S06E21 - Mary's Aunt Returns.mp4"],
  ["the-mary-tyler-moore-show-complete-series", "THE MARY TYLER MOORE SHOW - S06E22 - A Reliable Source",
    "The Mary Tyler Moore Show S06E22 - A Reliable Source.mp4"],
  ["the-mary-tyler-moore-show-complete-series", "THE MARY TYLER MOORE SHOW - S06E23 - Sue Ann Falls in Love",
    "The Mary Tyler Moore Show S06E23 - Sue Ann Falls in Love.mp4"],
  ["the-mary-tyler-moore-show-complete-series", "THE MARY TYLER MOORE SHOW - S06E24 - Ted and the Kid",
    "The Mary Tyler Moore Show S06E24 - Ted and The Kid.mp4"],
  ["the-mary-tyler-moore-show-complete-series", "THE MARY TYLER MOORE SHOW - S07E01 - Mary Midwife",
    "The Mary Tyler Moore Show S07E01 - Mary Midwife.mp4"],
  ["the-mary-tyler-moore-show-complete-series", "THE MARY TYLER MOORE SHOW - S07E02 - Mary the Writer",
    "The Mary Tyler Moore Show S07E02 - Mary The Writer.mp4"],
  ["the-mary-tyler-moore-show-complete-series", "THE MARY TYLER MOORE SHOW - S07E03 - Sue Ann's Sister",
    "The Mary Tyler Moore Show S07E03 - Sue Ann's Sister.mp4"],
  ["the-mary-tyler-moore-show-complete-series", "THE MARY TYLER MOORE SHOW - S07E04 - What's Wrong with Swimming?",
    "The Mary Tyler Moore Show S07E04 - What's Wrong with Swimming.mp4"],
  ["the-mary-tyler-moore-show-complete-series", "THE MARY TYLER MOORE SHOW - S07E05 - Ted's Change of Heart",
    "The Mary Tyler Moore Show S07E05 - Ted's Change of Heart.mp4"],
  ["the-mary-tyler-moore-show-complete-series", "THE MARY TYLER MOORE SHOW - S07E06 - One Producer Too Many",
    "The Mary Tyler Moore Show S07E06 - One Producer Too Many.mp4"],
  ["the-mary-tyler-moore-show-complete-series", "THE MARY TYLER MOORE SHOW - S07E07 - My Son, the Genius",
    "The Mary Tyler Moore Show S07E07 - My Son, The Genius.mp4"],
  ["the-mary-tyler-moore-show-complete-series", "THE MARY TYLER MOORE SHOW - S07E08 - Mary Gets a Lawyer",
    "The Mary Tyler Moore Show S07E08 - Mary Gets A Lawyer.mp4"],
  ["the-mary-tyler-moore-show-complete-series", "THE MARY TYLER MOORE SHOW - S07E09 - Lou Proposes",
    "The Mary Tyler Moore Show S07E09 - Lou Proposes.mp4"],
  ["the-mary-tyler-moore-show-complete-series", "THE MARY TYLER MOORE SHOW - S07E10 - Murray Can't Lose",
    "The Mary Tyler Moore Show S07E10 - Murray Can't Lose.mp4"],
  ["the-mary-tyler-moore-show-complete-series", "THE MARY TYLER MOORE SHOW - S07E11 - Mary's Insomnia",
    "The Mary Tyler Moore Show S07E11 - Mary's Insomnia.mp4"],
  ["the-mary-tyler-moore-show-complete-series", "THE MARY TYLER MOORE SHOW - S07E12 - Ted's Temptation",
    "The Mary Tyler Moore Show S07E12 - Ted's Temptation.mp4"],
  ["the-mary-tyler-moore-show-complete-series", "THE MARY TYLER MOORE SHOW - S07E13 - Look at Us, We're Walking",
    "The Mary Tyler Moore Show S07E13 - Look at Us, We're Walking.mp4"],
  ["the-mary-tyler-moore-show-complete-series", "THE MARY TYLER MOORE SHOW - S07E14 - The Critic",
    "The Mary Tyler Moore Show S07E14 - The Critic.mp4"],
  ["the-mary-tyler-moore-show-complete-series", "THE MARY TYLER MOORE SHOW - S07E15 - Lou's Army Reunion",
    "The Mary Tyler Moore Show S07E15 - Lou's Army Reunion.mp4"],
  ["the-mary-tyler-moore-show-complete-series", "THE MARY TYLER MOORE SHOW - S07E16 - The Ted and Georgette Show",
    "The Mary Tyler Moore Show S07E16 - The Ted & Georgette Show.mp4"],
  ["the-mary-tyler-moore-show-complete-series", "THE MARY TYLER MOORE SHOW - S07E17 - Sue Ann Gets the Ax",
    "The Mary Tyler Moore Show S07E17 - Sue Ann Gets The Ax.mp4"],
  ["the-mary-tyler-moore-show-complete-series", "THE MARY TYLER MOORE SHOW - S07E18 - Hail the Conquering Gordy",
    "The Mary Tyler Moore Show S07E18 - Hail the Conquering Gordy.mp4"],
  ["the-mary-tyler-moore-show-complete-series", "THE MARY TYLER MOORE SHOW - S07E19 - Mary and the Sexagenarian",
    "The Mary Tyler Moore Show S07E19 - Mary and The Sexagenarian.mp4"],
  ["the-mary-tyler-moore-show-complete-series", "THE MARY TYLER MOORE SHOW - S07E20 - Murray Ghosts for Ted",
    "The Mary Tyler Moore Show S07E20 - Murray Ghosts for Ted.mp4"],
  ["the-mary-tyler-moore-show-complete-series", "THE MARY TYLER MOORE SHOW - S07E21 - Mary's Three Husbands",
    "The Mary Tyler Moore Show S07E21 - Mary's Three Husbands.mp4"],
  ["the-mary-tyler-moore-show-complete-series", "THE MARY TYLER MOORE SHOW - S07E22 - Mary's Big Party",
    "The Mary Tyler Moore Show S07E22 - Mary's Big Party.mp4"],
  ["the-mary-tyler-moore-show-complete-series", "THE MARY TYLER MOORE SHOW - S07E23 - Lou Dates Mary",
    "The Mary Tyler Moore Show S07E23 - Lou Dates Mary.mp4"],
  ["the-mary-tyler-moore-show-complete-series", "THE MARY TYLER MOORE SHOW - S07E24 - The Last Show",
    "The Mary Tyler Moore Show S07E24 - The Last Show.mp4"],
],
  durations: {
  "the-mary-tyler-moore-show-complete-series::The Mary Tyler Moore Show S01E01 - Love is All Around.mp4": 1541,
  "the-mary-tyler-moore-show-complete-series::The Mary Tyler Moore Show S01E02 - Today I Am A Ma'am.mp4": 1543,
  "the-mary-tyler-moore-show-complete-series::The Mary Tyler Moore Show S01E03 - Bess, You is My Daughter Now.mp4": 1534,
  "the-mary-tyler-moore-show-complete-series::The Mary Tyler Moore Show S01E04 - Divorce Isn't Everything.mp4": 1539,
  "the-mary-tyler-moore-show-complete-series::The Mary Tyler Moore Show S01E05 - Keep Your Guard Up.mp4": 1544,
  "the-mary-tyler-moore-show-complete-series::The Mary Tyler Moore Show S01E06 - Support Your Local Mother.mp4": 1538,
  "the-mary-tyler-moore-show-complete-series::The Mary Tyler Moore Show S01E07 - Toulouse-Lautrec is One of My Favorite Artists.mp4": 1542,
  "the-mary-tyler-moore-show-complete-series::The Mary Tyler Moore Show S01E08 - The Snow Must Go On.mp4": 1540,
  "the-mary-tyler-moore-show-complete-series::The Mary Tyler Moore Show S01E09 - Bob & Rhoda & Teddy & Mary.mp4": 1544,
  "the-mary-tyler-moore-show-complete-series::The Mary Tyler Moore Show S01E10 - Assistant Wanted, Female.mp4": 1542,
  "the-mary-tyler-moore-show-complete-series::The Mary Tyler Moore Show S01E11 - 1040 or Fight.mp4": 1518,
  "the-mary-tyler-moore-show-complete-series::The Mary Tyler Moore Show S01E12 - Anchorman Overboard.mp4": 1541,
  "the-mary-tyler-moore-show-complete-series::The Mary Tyler Moore Show S01E13 - He's All Yours.mp4": 1539,
  "the-mary-tyler-moore-show-complete-series::The Mary Tyler Moore Show S01E14 - Christmas and The Hard Luck Kid II.mp4": 1540,
  "the-mary-tyler-moore-show-complete-series::The Mary Tyler Moore Show S01E15 - Howard's Girl.mp4": 1539,
  "the-mary-tyler-moore-show-complete-series::The Mary Tyler Moore Show S01E16 - Party is Such Sweet Sorrow.mp4": 1536,
  "the-mary-tyler-moore-show-complete-series::The Mary Tyler Moore Show S01E17 - Just A Lunch.mp4": 1542,
  "the-mary-tyler-moore-show-complete-series::The Mary Tyler Moore Show S01E18 - Second Story Story.mp4": 1540,
  "the-mary-tyler-moore-show-complete-series::The Mary Tyler Moore Show S01E19 - We Closed in Minneapolis.mp4": 1536,
  "the-mary-tyler-moore-show-complete-series::The Mary Tyler Moore Show S01E20 - Hi!.mp4": 1541,
  "the-mary-tyler-moore-show-complete-series::The Mary Tyler Moore Show S01E21 - The Boss Isn't Coming to Dinner.mp4": 1541,
  "the-mary-tyler-moore-show-complete-series::The Mary Tyler Moore Show S01E22 - A Friend in Deed.mp4": 1539,
  "the-mary-tyler-moore-show-complete-series::The Mary Tyler Moore Show S01E23 - Smokey The Bear Wants You.mp4": 1538,
  "the-mary-tyler-moore-show-complete-series::The Mary Tyler Moore Show S01E24 - The 45-Year-Old Man.mp4": 1510,
  "the-mary-tyler-moore-show-complete-series::The Mary Tyler Moore Show S02E01 - The Birds . . . and . . . um . . . Bees.mp4": 1533,
  "the-mary-tyler-moore-show-complete-series::The Mary Tyler Moore Show S02E02 - I Am Curious Cooper.mp4": 1528,
  "the-mary-tyler-moore-show-complete-series::The Mary Tyler Moore Show S02E03 - He's No Heavy . . . He's My Brother.mp4": 1529,
  "the-mary-tyler-moore-show-complete-series::The Mary Tyler Moore Show S02E04 - Room 223.mp4": 1534,
  "the-mary-tyler-moore-show-complete-series::The Mary Tyler Moore Show S02E05 - A Girl's Best Mother is Not Her Friend.mp4": 1535,
  "the-mary-tyler-moore-show-complete-series::The Mary Tyler Moore Show S02E06 - Cover Boy.mp4": 1534,
  "the-mary-tyler-moore-show-complete-series::The Mary Tyler Moore Show S02E07 - Didn't You Used to Be . . . Wait . . . Don't Tell Me.mp4": 1529,
  "the-mary-tyler-moore-show-complete-series::The Mary Tyler Moore Show S02E08 - Thoroughly Unmilitant Mary.mp4": 1526,
  "the-mary-tyler-moore-show-complete-series::The Mary Tyler Moore Show S02E09 - And Now, Sitting in for Ted Baxter.mp4": 1535,
  "the-mary-tyler-moore-show-complete-series::The Mary Tyler Moore Show S02E10 - Don't Break The Chain.mp4": 1531,
  "the-mary-tyler-moore-show-complete-series::The Mary Tyler Moore Show S02E11 - The Six-and-a-Half-Year Itch.mp4": 1534,
  "the-mary-tyler-moore-show-complete-series::The Mary Tyler Moore Show S02E12 - . . . Is A Friend in Need.mp4": 1532,
  "the-mary-tyler-moore-show-complete-series::The Mary Tyler Moore Show S02E13 - The Square-Shaped Room.mp4": 1533,
  "the-mary-tyler-moore-show-complete-series::The Mary Tyler Moore Show S02E14 - Ted Over Heels.mp4": 1532,
  "the-mary-tyler-moore-show-complete-series::The Mary Tyler Moore Show S02E15 - The Five-Minute Dress.mp4": 1531,
  "the-mary-tyler-moore-show-complete-series::The Mary Tyler Moore Show S02E16 - Feeb.mp4": 1535,
  "the-mary-tyler-moore-show-complete-series::The Mary Tyler Moore Show S02E17 - The Slaughter Affair.mp4": 1536,
  "the-mary-tyler-moore-show-complete-series::The Mary Tyler Moore Show S02E18 - Baby Sit-Com.mp4": 1532,
  "the-mary-tyler-moore-show-complete-series::The Mary Tyler Moore Show S02E19 - More Than Neighbors.mp4": 1534,
  "the-mary-tyler-moore-show-complete-series::The Mary Tyler Moore Show S02E20 - The Care and Feeding of Parents.mp4": 1530,
  "the-mary-tyler-moore-show-complete-series::The Mary Tyler Moore Show S02E21 - Where There's Smoke, There's Rhoda.mp4": 1536,
  "the-mary-tyler-moore-show-complete-series::The Mary Tyler Moore Show S02E22 - You Certainly Are A Big Boy.mp4": 1529,
  "the-mary-tyler-moore-show-complete-series::The Mary Tyler Moore Show S02E23 - Some of My Best Friends Are Rhoda.mp4": 1533,
  "the-mary-tyler-moore-show-complete-series::The Mary Tyler Moore Show S02E24 - His Two Right Arms.mp4": 1533,
  "the-mary-tyler-moore-show-complete-series::The Mary Tyler Moore Show S03E01 - The Good-Time News.mp4": 1535,
  "the-mary-tyler-moore-show-complete-series::The Mary Tyler Moore Show S03E02 - What is Mary Richards Really Like.mp4": 1531,
  "the-mary-tyler-moore-show-complete-series::The Mary Tyler Moore Show S03E03 - Who's in Charge Here.mp4": 1537,
  "the-mary-tyler-moore-show-complete-series::The Mary Tyler Moore Show S03E04 - Enter Rhoda's Parents.mp4": 1536,
  "the-mary-tyler-moore-show-complete-series::The Mary Tyler Moore Show S03E05 - It's Whether You Win or Lose.mp4": 1535,
  "the-mary-tyler-moore-show-complete-series::The Mary Tyler Moore Show S03E06 - Rhoda The Beautiful.mp4": 1537,
  "the-mary-tyler-moore-show-complete-series::The Mary Tyler Moore Show S03E07 - Just Around the Corner.mp4": 1537,
  "the-mary-tyler-moore-show-complete-series::The Mary Tyler Moore Show S03E08 - But Seriously, Folks.mp4": 1537,
  "the-mary-tyler-moore-show-complete-series::The Mary Tyler Moore Show S03E09 - Farmer Ted and The News.mp4": 1530,
  "the-mary-tyler-moore-show-complete-series::The Mary Tyler Moore Show S03E10 - Have I Found A Guy for You.mp4": 1535,
  "the-mary-tyler-moore-show-complete-series::The Mary Tyler Moore Show S03E11 - You've Got A Friend.mp4": 1535,
  "the-mary-tyler-moore-show-complete-series::The Mary Tyler Moore Show S03E12 - It Was Fascination, I Know.mp4": 1535,
  "the-mary-tyler-moore-show-complete-series::The Mary Tyler Moore Show S03E13 - Operation Lou.mp4": 1536,
  "the-mary-tyler-moore-show-complete-series::The Mary Tyler Moore Show S03E14 - Rhoda Morgenstern Minneapolis to New York.mp4": 1535,
  "the-mary-tyler-moore-show-complete-series::The Mary Tyler Moore Show S03E15 - The Courtship of Mary's Father's Daughter.mp4": 1536,
  "the-mary-tyler-moore-show-complete-series::The Mary Tyler Moore Show S03E16 - Lou's Place.mp4": 1537,
  "the-mary-tyler-moore-show-complete-series::The Mary Tyler Moore Show S03E17 - My Brother's Keeper.mp4": 1536,
  "the-mary-tyler-moore-show-complete-series::The Mary Tyler Moore Show S03E18 - The Georgette Story.mp4": 1537,
  "the-mary-tyler-moore-show-complete-series::The Mary Tyler Moore Show S03E19 - Romeo and Mary.mp4": 1531,
  "the-mary-tyler-moore-show-complete-series::The Mary Tyler Moore Show S03E20 - What Do You Do When The Boss Says, “I Love You”.mp4": 1537,
  "the-mary-tyler-moore-show-complete-series::The Mary Tyler Moore Show S03E21 - Murray Faces Life.mp4": 1535,
  "the-mary-tyler-moore-show-complete-series::The Mary Tyler Moore Show S03E22 - Remembrance of Things Past.mp4": 1537,
  "the-mary-tyler-moore-show-complete-series::The Mary Tyler Moore Show S03E23 - Put On A Happy Face.mp4": 1528,
  "the-mary-tyler-moore-show-complete-series::The Mary Tyler Moore Show S03E24 - Mary Richards and The Incredible Plant Lady.mp4": 1535,
  "the-mary-tyler-moore-show-complete-series::The Mary Tyler Moore Show S04E01 - The Lars Affair.mp4": 1536,
  "the-mary-tyler-moore-show-complete-series::The Mary Tyler Moore Show S04E02 - Angels in The Snow.mp4": 1534,
  "the-mary-tyler-moore-show-complete-series::The Mary Tyler Moore Show S04E03 - Rhoda's Sister Gets Married.mp4": 1535,
  "the-mary-tyler-moore-show-complete-series::The Mary Tyler Moore Show S04E04 - The Lou and Edie Story.mp4": 1537,
  "the-mary-tyler-moore-show-complete-series::The Mary Tyler Moore Show S04E05 - Hi There, Sports Fans.mp4": 1536,
  "the-mary-tyler-moore-show-complete-series::The Mary Tyler Moore Show S04E06 - Father's Day.mp4": 1538,
  "the-mary-tyler-moore-show-complete-series::The Mary Tyler Moore Show S04E07 - Son of “But Seriously, Folks”.mp4": 1537,
  "the-mary-tyler-moore-show-complete-series::The Mary Tyler Moore Show S04E08 - Lou's First Date.mp4": 1535,
  "the-mary-tyler-moore-show-complete-series::The Mary Tyler Moore Show S04E09 - Love Blooms at Hemples.mp4": 1534,
  "the-mary-tyler-moore-show-complete-series::The Mary Tyler Moore Show S04E10 - The Dinner Party.mp4": 1531,
  "the-mary-tyler-moore-show-complete-series::The Mary Tyler Moore Show S04E11 - Just Friends.mp4": 1536,
  "the-mary-tyler-moore-show-complete-series::The Mary Tyler Moore Show S04E12 - We Want Baxter.mp4": 1533,
  "the-mary-tyler-moore-show-complete-series::The Mary Tyler Moore Show S04E13 - I Gave at The Office.mp4": 1533,
  "the-mary-tyler-moore-show-complete-series::The Mary Tyler Moore Show S04E14 - Almost A Nun's Story.mp4": 1535,
  "the-mary-tyler-moore-show-complete-series::The Mary Tyler Moore Show S04E15 - Happy Birthday, Lou!.mp4": 1538,
  "the-mary-tyler-moore-show-complete-series::The Mary Tyler Moore Show S04E16 - WJM Tries Harder.mp4": 1536,
  "the-mary-tyler-moore-show-complete-series::The Mary Tyler Moore Show S04E17 - Cottage for Sale.mp4": 1537,
  "the-mary-tyler-moore-show-complete-series::The Mary Tyler Moore Show S04E18 - The Co-Producers.mp4": 1526,
  "the-mary-tyler-moore-show-complete-series::The Mary Tyler Moore Show S04E19 - Best of Enemies.mp4": 1537,
  "the-mary-tyler-moore-show-complete-series::The Mary Tyler Moore Show S04E20 - Better Late . . . That's A Pun . . . Than Never.mp4": 1535,
  "the-mary-tyler-moore-show-complete-series::The Mary Tyler Moore Show S04E21 - Ted Baxter Meets Walter Cronkite.mp4": 1540,
  "the-mary-tyler-moore-show-complete-series::The Mary Tyler Moore Show S04E22 - Lou's Second Date.mp4": 1538,
  "the-mary-tyler-moore-show-complete-series::The Mary Tyler Moore Show S04E23 - Two Wrongs Don't Make A Writer.mp4": 1537,
  "the-mary-tyler-moore-show-complete-series::The Mary Tyler Moore Show S04E24 - I Was A Single for WJM.mp4": 1537,
  "the-mary-tyler-moore-show-complete-series::The Mary Tyler Moore Show S05E01 - Will Mary Richards Go to Jail.mp4": 1568,
  "the-mary-tyler-moore-show-complete-series::The Mary Tyler Moore Show S05E02 - Not Just Another Pretty Face.mp4": 1565,
  "the-mary-tyler-moore-show-complete-series::The Mary Tyler Moore Show S05E03 - You Sometimes Hurt The One You Hate.mp4": 1565,
  "the-mary-tyler-moore-show-complete-series::The Mary Tyler Moore Show S05E04 - Lou and That Woman.mp4": 1565,
  "the-mary-tyler-moore-show-complete-series::The Mary Tyler Moore Show S05E05 - The Outsider.mp4": 1568,
  "the-mary-tyler-moore-show-complete-series::The Mary Tyler Moore Show S05E06 - I Love A Piano.mp4": 1569,
  "the-mary-tyler-moore-show-complete-series::The Mary Tyler Moore Show S05E07 - The New Sue Ann.mp4": 1568,
  "the-mary-tyler-moore-show-complete-series::The Mary Tyler Moore Show S05E08 - Menage-a-Phyllis.mp4": 1565,
  "the-mary-tyler-moore-show-complete-series::The Mary Tyler Moore Show S05E09 - Not A Christmas Story.mp4": 1536,
  "the-mary-tyler-moore-show-complete-series::The Mary Tyler Moore Show S05E10 - What are Friends For.mp4": 1536,
  "the-mary-tyler-moore-show-complete-series::The Mary Tyler Moore Show S05E11 - A Boy's Best Friend.mp4": 1565,
  "the-mary-tyler-moore-show-complete-series::The Mary Tyler Moore Show S05E12 - A Son for Murray.mp4": 1565,
  "the-mary-tyler-moore-show-complete-series::The Mary Tyler Moore Show S05E13 - Neighbors.mp4": 1566,
  "the-mary-tyler-moore-show-complete-series::The Mary Tyler Moore Show S05E14 - A Girl Like Mary.mp4": 1564,
  "the-mary-tyler-moore-show-complete-series::The Mary Tyler Moore Show S05E15 - An Affair to Forget.mp4": 1537,
  "the-mary-tyler-moore-show-complete-series::The Mary Tyler Moore Show S05E16 - Mary Richards Producer.mp4": 1566,
  "the-mary-tyler-moore-show-complete-series::The Mary Tyler Moore Show S05E17 - The System.mp4": 1569,
  "the-mary-tyler-moore-show-complete-series::The Mary Tyler Moore Show S05E18 - Phyllis Whips Inflation.mp4": 1564,
  "the-mary-tyler-moore-show-complete-series::The Mary Tyler Moore Show S05E19 - The Shame of The Cities.mp4": 1566,
  "the-mary-tyler-moore-show-complete-series::The Mary Tyler Moore Show S05E20 - Marriage Minneapolis Style.mp4": 1568,
  "the-mary-tyler-moore-show-complete-series::The Mary Tyler Moore Show S05E21 - You Try to Be A Nice Guy.mp4": 1564,
  "the-mary-tyler-moore-show-complete-series::The Mary Tyler Moore Show S05E22 - You Can't Lose 'em All.mp4": 1565,
  "the-mary-tyler-moore-show-complete-series::The Mary Tyler Moore Show S05E23 - Ted Baxter's Famous Broadcasters' School.mp4": 1563,
  "the-mary-tyler-moore-show-complete-series::The Mary Tyler Moore Show S05E24 - Anyone Who Hates Kids and Dogs.mp4": 1564,
  "the-mary-tyler-moore-show-complete-series::The Mary Tyler Moore Show S06E01 - Edie Gets Married.mp4": 1563,
  "the-mary-tyler-moore-show-complete-series::The Mary Tyler Moore Show S06E02 - Mary Moves Out.mp4": 1565,
  "the-mary-tyler-moore-show-complete-series::The Mary Tyler Moore Show S06E03 - Mary's Father.mp4": 1563,
  "the-mary-tyler-moore-show-complete-series::The Mary Tyler Moore Show S06E04 - Murray in Love.mp4": 1564,
  "the-mary-tyler-moore-show-complete-series::The Mary Tyler Moore Show S06E05 - Ted's Moment of Glory.mp4": 1563,
  "the-mary-tyler-moore-show-complete-series::The Mary Tyler Moore Show S06E06 - Mary's Aunt.mp4": 1566,
  "the-mary-tyler-moore-show-complete-series::The Mary Tyler Moore Show S06E07 - Chuckles Bites The Dust.mp4": 1562,
  "the-mary-tyler-moore-show-complete-series::The Mary Tyler Moore Show S06E08 - Mary's Delinquent.mp4": 1565,
  "the-mary-tyler-moore-show-complete-series::The Mary Tyler Moore Show S06E09 - Ted's Wedding.mp4": 1561,
  "the-mary-tyler-moore-show-complete-series::The Mary Tyler Moore Show S06E10 - Lou Douses An Old Flame.mp4": 1560,
  "the-mary-tyler-moore-show-complete-series::The Mary Tyler Moore Show S06E11 - Mary Richards Falls in Love.mp4": 1560,
  "the-mary-tyler-moore-show-complete-series::The Mary Tyler Moore Show S06E12 - Ted's Tax Refund.mp4": 1561,
  "the-mary-tyler-moore-show-complete-series::The Mary Tyler Moore Show S06E13 - The Happy Homemaker Takes Lou Home.mp4": 1561,
  "the-mary-tyler-moore-show-complete-series::The Mary Tyler Moore Show S06E14 - One Boyfriend Too Many.mp4": 1563,
  "the-mary-tyler-moore-show-complete-series::The Mary Tyler Moore Show S06E15 - What Do You Want to Do When You Produce.mp4": 1562,
  "the-mary-tyler-moore-show-complete-series::The Mary Tyler Moore Show S06E16 - Not with My Wife, I Don't.mp4": 1565,
  "the-mary-tyler-moore-show-complete-series::The Mary Tyler Moore Show S06E17 - The Seminar.mp4": 1560,
  "the-mary-tyler-moore-show-complete-series::The Mary Tyler Moore Show S06E18 - Once I Had A Secret Love.mp4": 1561,
  "the-mary-tyler-moore-show-complete-series::The Mary Tyler Moore Show S06E19 - Menage-a-Lou.mp4": 1560,
  "the-mary-tyler-moore-show-complete-series::The Mary Tyler Moore Show S06E20 - Murray Takes A Stand.mp4": 1558,
  "the-mary-tyler-moore-show-complete-series::The Mary Tyler Moore Show S06E21 - Mary's Aunt Returns.mp4": 1564,
  "the-mary-tyler-moore-show-complete-series::The Mary Tyler Moore Show S06E22 - A Reliable Source.mp4": 1563,
  "the-mary-tyler-moore-show-complete-series::The Mary Tyler Moore Show S06E23 - Sue Ann Falls in Love.mp4": 1562,
  "the-mary-tyler-moore-show-complete-series::The Mary Tyler Moore Show S06E24 - Ted and The Kid.mp4": 1567,
  "the-mary-tyler-moore-show-complete-series::The Mary Tyler Moore Show S07E01 - Mary Midwife.mp4": 1535,
  "the-mary-tyler-moore-show-complete-series::The Mary Tyler Moore Show S07E02 - Mary The Writer.mp4": 1539,
  "the-mary-tyler-moore-show-complete-series::The Mary Tyler Moore Show S07E03 - Sue Ann's Sister.mp4": 1537,
  "the-mary-tyler-moore-show-complete-series::The Mary Tyler Moore Show S07E04 - What's Wrong with Swimming.mp4": 1535,
  "the-mary-tyler-moore-show-complete-series::The Mary Tyler Moore Show S07E05 - Ted's Change of Heart.mp4": 1531,
  "the-mary-tyler-moore-show-complete-series::The Mary Tyler Moore Show S07E06 - One Producer Too Many.mp4": 1532,
  "the-mary-tyler-moore-show-complete-series::The Mary Tyler Moore Show S07E07 - My Son, The Genius.mp4": 1529,
  "the-mary-tyler-moore-show-complete-series::The Mary Tyler Moore Show S07E08 - Mary Gets A Lawyer.mp4": 1532,
  "the-mary-tyler-moore-show-complete-series::The Mary Tyler Moore Show S07E09 - Lou Proposes.mp4": 1532,
  "the-mary-tyler-moore-show-complete-series::The Mary Tyler Moore Show S07E10 - Murray Can't Lose.mp4": 1530,
  "the-mary-tyler-moore-show-complete-series::The Mary Tyler Moore Show S07E11 - Mary's Insomnia.mp4": 1533,
  "the-mary-tyler-moore-show-complete-series::The Mary Tyler Moore Show S07E12 - Ted's Temptation.mp4": 1530,
  "the-mary-tyler-moore-show-complete-series::The Mary Tyler Moore Show S07E13 - Look at Us, We're Walking.mp4": 1530,
  "the-mary-tyler-moore-show-complete-series::The Mary Tyler Moore Show S07E14 - The Critic.mp4": 1532,
  "the-mary-tyler-moore-show-complete-series::The Mary Tyler Moore Show S07E15 - Lou's Army Reunion.mp4": 1533,
  "the-mary-tyler-moore-show-complete-series::The Mary Tyler Moore Show S07E16 - The Ted & Georgette Show.mp4": 1532,
  "the-mary-tyler-moore-show-complete-series::The Mary Tyler Moore Show S07E17 - Sue Ann Gets The Ax.mp4": 1530,
  "the-mary-tyler-moore-show-complete-series::The Mary Tyler Moore Show S07E18 - Hail the Conquering Gordy.mp4": 1530,
  "the-mary-tyler-moore-show-complete-series::The Mary Tyler Moore Show S07E19 - Mary and The Sexagenarian.mp4": 1533,
  "the-mary-tyler-moore-show-complete-series::The Mary Tyler Moore Show S07E20 - Murray Ghosts for Ted.mp4": 1529,
  "the-mary-tyler-moore-show-complete-series::The Mary Tyler Moore Show S07E21 - Mary's Three Husbands.mp4": 1531,
  "the-mary-tyler-moore-show-complete-series::The Mary Tyler Moore Show S07E22 - Mary's Big Party.mp4": 1530,
  "the-mary-tyler-moore-show-complete-series::The Mary Tyler Moore Show S07E23 - Lou Dates Mary.mp4": 1530,
  "the-mary-tyler-moore-show-complete-series::The Mary Tyler Moore Show S07E24 - The Last Show.mp4": 1541,
},
};
